In [1]:
# ======================================================
# LIBRERÍAS
# ======================================================

import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 100)

print("✅ Librerías cargadas")

✅ Librerías cargadas

In [2]:
# ======================================================
# CONFIGURACIÓN DE RUTAS
# ======================================================
# El notebook está pensado para ejecutarse dentro de Equip_32,
# normalmente desde una carpeta como Notebooks/. Detecta automáticamente
# la carpeta Data sin depender de una ruta absoluta del ordenador.

PROJECT_DIR = Path.cwd().resolve()

DATA_DIR_CANDIDATES = [
    PROJECT_DIR / "Data",
    PROJECT_DIR.parent / "Data",
    PROJECT_DIR,
]

DATA_FILENAMES = [
    "2026-07-20_ECF_2021_01_raw.dta"
]

DATA_PATH = next(
    (folder / name
     for folder in DATA_DIR_CANDIDATES
     for name in DATA_FILENAMES
     if (folder / name).exists()),
    None
)

if DATA_PATH is None:
    searched = "\n".join(
        str(folder / name)
        for folder in DATA_DIR_CANDIDATES
        for name in DATA_FILENAMES
    )
    raise FileNotFoundError(
        "No se ha encontrado el fichero ECF 2021. Rutas comprobadas:\n"
        + searched
    )

DATA_DIR = DATA_PATH.parent

print(f"✅ Dataset localizado: {DATA_PATH}")
print(f"✅ Carpeta de salida: {DATA_DIR}")

✅ Dataset localizado: /Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/04_Simulador/ProjecteData/Equip_32/Data/2026-07-20_ECF_2021_01_raw.dta
✅ Carpeta de salida: /Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/04_Simulador/ProjecteData/Equip_32/Data

In [3]:
# ======================================================
# CARGA DEL DATASET
# ======================================================

df = pd.read_stata(

    DATA_PATH,

    convert_categoricals=True

)

print(df.shape)

(7764, 429)

In [4]:
# ======================================================
# INFORMACIÓN GENERAL
# ======================================================

print("="*70)
print("DATASET ORIGINAL")
print("="*70)

print(f"Observaciones : {df.shape[0]:,}")
print(f"Variables     : {df.shape[1]}")

display(df.head())

======================================================================
DATASET ORIGINAL
======================================================================
Observaciones : 7,764
Variables     : 429

,a01,a02,a0000,a0400,a04,a0800,a0100,a0320,a1030,a1040,a0910,a1100,a1200,a1300,a1400,a1410,a1420a,a1420b,a1420c,a1420d,a1420e,a1420f,a1420g,a1500,a1510,a1600,a1520,a1530,a2000,a1700,a1710,a1900,a2100,a2200,a2300,a2500,a2400,a2600,a2700,b0100,b0110a,b0110b,b0110c,b0110d,b0110e,b0110f,b0110g,b0120a,b0120b,b0120c,b0120d,b0120e,b0120f,b0130a,b0130b,b0130c,b0208,b0308,b0408,b0201,b0301,b0401,b0202,b0302,b0402,b0203,b0303,b0403,b0204,b0304,b0404,b0205,b0305,b0405,b0206,b0306,b0406,b0207,b0307,b0407,b0209,b0309,b0409,b0210,b0310,b0410,b0212,b0312,b0412,b1100a,b1100b,b1100c,b1100d,b1100e,b1100f,b1100g,b1100i,b1100h,b0502,b0503,b0600,b0720a,b0720b,b0720c,b0720d,b0720e,b0720f,b0720g,b0720h,b0720i,b0710a,b0710b,b0710c,b0710d,b0710e,b0710f,b0710g,b0710h,b0710i,b1000a,b1000b,b1000c,b1000d,b1000e,b1000f,b1000g,b1000h,b1000i,b1000j,b1103,b1201,b1203a,b1203b,b1203c,b1203d,b1203e,b1203f,b1203g,b1204a,b1204b,b1204c,b1204d,b1204e,b1204f,b1204g,b1205a,b1205b,b1205c,b1205d,b1205e,b1206a,b1206b,b1206c,b1206d,b1206e,b1207a,b1207b,b1207c,b1208a,b1208b,b1208c,b1208d,b1209a,b1209b,b1209c,b1209d,b1230a,b1230b,b1230c,b1230d,b1230e,b1230f,b1230g,b1230h,c0100,c0200a,c0200b,c0200c,c0200d,c0200e,c0200f,c0200g,c0200h,c0200i,c0200j,c0200k,c0300,c0500,c0600a,c0600b,c0600c,c0600d,c0600e,c0600f,c0600g,c0600h,c0600i,c0600j,c0600k,c0400a,c0400b,c0400c,c0400d,c0400e,c0400f,c0400g,c0400h,c0400i,c0400j,c0400k,c0400l,c0400m,c0400n,d0101,d0104,d0110,d0113,d0102,d0114,d0115,d0117,d0103,d0116,d0105,d0106,d0107,d0108,d0109,d0111,d0112,d0300,d0400,d0500,d0600,d0610a,d0610b,d0610c,d0610d,d0610e,e0100,e0500,e0600,e0700,e0800,e0900,e1001,e1002,e1003,e1004,e1005,e1200,e1101,e0401,e0402,e0300,e1400,e1500,e1600,e1701,e1702,e1800,e1300,i0100,i0200a,i0200b,i0200c,i0200d,i0200e,i0200h,i0200f,i0200g,i0200j,i0300,i0500a,i0500b,i0500c,i0500d,i0500e,i0500f,i0500g,i0500h,i0500i,i0500k,i0500j,i0800,i0510,i0520a,i0520b,i0520c,i0520e,i0520f,i0520d,i0520g,i0601,i0602,i0700,i0900,i1000,i0400a,i0400b,i0400c,i0400d,i0400e,j0100,j0110,j0200,j0300a,j0300b,j0300c,j0300d,j0300e,j0300f,j0300g,j0300h,j0300i,j0300j,j0300k,j0300l,j0300m,j0300n,j0300p,j0300o,j0400,j0500,j0600,j0700,j0800a,j0800b,j0800c,j0800d,j0800e,j0800f,j0800h,j0800g,j0810,j0900a,j0900b,j0900c,j0900d,j0910a,j0910b,j0910c,j0910d,j0910e,j0910f,j0920,j1000,j1100,j1201,j1202,j1203,j1300,j1400,j1600,k1908,k1901,k1902,k1903,k1904,k1905,k1906,k1907,k1909,k1910,k1912,k0100,k0500,k0600,k0700,k0800,k0900,k1001,k1002,k1003,k1004,k1005,k1200,k1101,k0401,k0402,k0300,k1400,k1500,k1600,k1701,k1702,k1800,k1300,k2020,negativa_pmi,tmp_e0401,age,f0900a,f1000a,weight,a0940,a0930,a0300,a0310,ccaaf,a0930_b,a0950,f1100,f1200,f1200_b,f1300,a0900b,a0900c,a0900d,a0900e,a0900f,a0900l,a0900j,a0900h,a0900g,a0900i,a0900a,a0900k,a1800,a0200,f0900b,f1000b,f0900c,f1000c,f0900d,f1000d,f0900e,f1000e,ID
0,2022,6,Mujer,1982,40,No ha lugar (no aplica filtro),España,No,Casado,Gananciales,3,"g. Diplomaturas universitarias, grados universitarios de 240 créditos y similares","e. Otras ciencias sociales (Psicología, Sociología, Periodismo e Información...) y ciencias jurí...",No ha lugar (no aplica filtro),d. Los suficientes para llenar dos estanterías (entre 101 y 200 libros),Sí,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,b. Trabaja por cuenta ajena,No tengo una segunda situación laboral,No ha lugar (no aplica filtro),A tiempo parcial,No ha lugar (no aplica filtro),Indefinido,No ha lugar (no aplica filtro),21,No,50,80,No ha lugar (no aplica filtro),c. Primera etapa de Educación Secundaria y similar,b. Trabaja por cuenta ajena,k. Dedicado a labores del hogar,"h. Operadores de instalaciones y maquinaria, y montadores",Sí,No mencionado,Mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,No mencionado,Sí,No,No,Sí,Sí,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,Sí,Sí,Sí,Sí,No,Sí,No,No,Sí,No,No,Sí,No,No,No mencionado,No ha lugar (no aplica filtro),No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,Mencionado,Préstamo personal,Conjunta,b. Consideré/ consideramos varias opciones de una única empresa o institución,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No,No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,1 (MUY MAL),Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,60,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),5-Siempre,5-Siempre,5-Siempre,3-En ocasiones,2-Poco,4-Bastante,4-Bastante,5-Completamente,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,2-Bastante en desacuerdo,3-Ni de acuerdo ni en desacuerdo,5-Completamente de acuerdo,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),20,4,1,3,1,1,3- Medios,200.0,a. Más de lo que podrían comprar hoy con su parte del dinero,0.0,120.0,Exactamente 110 euros,Verdadero,Verdadero,No sabe,Verdadero,1 Nada Seguro,Verdadero,Fondo 1 (Azul),"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",18,500.0,1.0,30.0,"d. Aproximadamente, 15 de cada 100 personas que utilizan esta medicación desarrollan un sarpullido.",Tipo de interés del 1%,Tipo de interés del 3%,a. La economía ha crecido en un 1%,5,a. Propiedad por compra (mayoritariamente) –incluye permuta y construcción propia,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,2007,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,Para financiar la compra de la vivienda principal,450,80,No,1,2,5,1,1,Sí,No,Sí,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,g. Un año o más,800,Un mes,1500,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Todas las personas seleccionadas forman parte del hogar,No mencionado,No mencionado,No mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No,No,No,d. Entre 27.001 y 47.000 euros,-5,No lo he consultado hasta el momento de realizar la entrevista,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),69.70,40,Mencionado,Mencionado,6814.125977,Hombre,44.0,No ha lugar (no aplica filtro),-98.0,Andalucía,No ha lugar (no aplica filtro),15.0,Titular muestral,40.0,No ha lugar (no aplica filtro),Mujer,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0,Andalucía,Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,1.0
1,2022,3,Mujer,1967,54,No ha lugar (no aplica filtro),España,No,Soltero,No ha lugar (no aplica filtro),2,"h. Grados universitarios de más de 240 créditos, licenciaturas, másteres y similares","e. Otras ciencias sociales (Psicología, Sociología, Periodismo e Información...) y ciencias jurí...",No ha lugar (no aplica filtro),a. Ninguno o muy pocos (entre 0 y 10 libros),No,No mencionado,Mencionado,Mencionado,Mencionado,Mencionado,No mencionado,No mencionado,b. Trabaja por cuenta ajena,No tengo una segunda situación laboral,No ha lugar (no aplica filtro),A tiempo completo,No ha lugar (no aplica filtro),No contesta,No ha lugar (no aplica filtro),27,No,20,10,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),k. Dedicado a labores del hogar,"h. Operadores de instalaciones y maquinaria, y montadores",Sí,Mencionado,Mencionado,Mencionado,Mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,No,No,Sí,Sí,No,Sí,Sí,No,Sí,No,No,Sí,Sí,No,Sí,No,No,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No,No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,3 (REGULAR),Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,67,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),3-En ocasiones,5-Siempre,4-Con frecuencia,4-Con frecuencia,2-Poco,2-Poco,2-Poco,4-Bastante,2-Bastante en desacuerdo,2-Bastante en desacuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,1-Completamente en desacuerdo,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),50,0,2,0,8,0,3- Medios,200.0,c. Menos de lo que podrían comprar hoy,0.0,100.0,No sabe,No sabe,Verdadero,No sabe,Falso,3,Falso,Fondo 2 (Verde),"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",24,No sabe,3.0,30.0,"b. Para aplicaciones en la piel, utilizar solo un 15% de la dosis recomendada.",Tipo de interés del 3%,Tipo de interés del 1%,e. El valor del euro ha crecido en un 1%,1 - Nada Seguro,b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,0,2,1,6,1,Sí,No,Sí,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,"c. Por lo menos un mes, pero menos de tres meses",300,Un mes,0,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Ambos,No,No ha lugar (no aplica filtro),No,No,Sí,d. Entre 27.001 y 47.000 euros,-98,No lo he consultado hasta el momento de realizar la entrevista,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),88.47,54,Mencionado,Mencionado,3277.015137,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),-98.0,Canarias,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Titular muestral,54.0,No ha lugar (no aplica filtro),Mujer,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,Canarias,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),2.0

In [5]:
# ======================================================
# INFORMACIÓN DE VARIABLES
# ======================================================

variables = pd.DataFrame({
    "Variable": df.columns,
    "Tipo": df.dtypes.astype(str)
})

display(variables.head(20))

       Variable      Tipo
a01         a01     int16
a02         a02      int8
a0000     a0000  category
a0400     a0400  category
a04         a04  category
a0800     a0800  category
a0100     a0100  category
a0320     a0320  category
a1030     a1030  category
a1040     a1040  category
a0910     a0910      int8
a1100     a1100  category
a1200     a1200  category
a1300     a1300  category
a1400     a1400  category
a1410     a1410  category
a1420a   a1420a  category
a1420b   a1420b  category
a1420c   a1420c  category
a1420d   a1420d  category

In [6]:
# ======================================================
# VARIABLES COMUNES
# Variables utilizadas en todos los análisis
# ======================================================

# ------------------------------------------------------
# DEMOGRAFÍA
# ------------------------------------------------------
# Información sociodemográfica básica del entrevistado.

DEMOGRAFIA = [

    "ccaaf",      # Comunidad Autónoma
    "a04",        # Edad
    "a0000",      # Sexo
    "a0100",      # País de nacimiento
    "a0910",      # Número de miembros del hogar
    "a1030"       # Estado civil

]

# ------------------------------------------------------
# EDUCACIÓN
# ------------------------------------------------------
# Máximo nivel educativo alcanzado.

EDUCACION = [

    "a1100"

]

# ------------------------------------------------------
# SITUACIÓN LABORAL
# ------------------------------------------------------
# Situación laboral y experiencia profesional.

SITUACION_LABORAL = [

    "a1500",
    "a1510",
    "a1520",
    "a1530",
    "a1700",
    "a1710",
    "a1800",
    "a1900"

]

# ------------------------------------------------------
# ANTECEDENTES FINANCIEROS
# ------------------------------------------------------
# Exposición temprana a la educación financiera.

ANTECEDENTES_FINANCIEROS = [

    "a1400",
    "a1410"

]

# ------------------------------------------------------
# VARIABLES COMUNES
# ------------------------------------------------------

COMMON_VARS = (

    DEMOGRAFIA
    + EDUCACION
    + SITUACION_LABORAL
    + ANTECEDENTES_FINANCIEROS

)

In [7]:
# ======================================================
# COMPORTAMIENTO FINANCIERO
# ======================================================

# ------------------------------------------------------
# RELACIÓN CON LAS ENTIDADES FINANCIERAS
# Cuentas bancarias, canales de acceso y medios de pago
# ------------------------------------------------------

RELACION_BANCARIA = sorted(

    c for c in df.columns
    if c.startswith("b01")

)

# ------------------------------------------------------
# CONOCIMIENTO DE PRODUCTOS FINANCIEROS
# Productos que el entrevistado conoce
# ------------------------------------------------------

CONOCIMIENTO_PRODUCTOS = sorted(

    c for c in df.columns
    if c.startswith("b02")

)

# ------------------------------------------------------
# TENENCIA ACTUAL DE PRODUCTOS
# Productos financieros que posee actualmente
# ------------------------------------------------------

PRODUCTOS_ACTUALES = sorted(

    c for c in df.columns
    if c.startswith("b03")

)

# ------------------------------------------------------
# CONTRATACIÓN RECIENTE
# Productos contratados en los últimos dos años
# ------------------------------------------------------

CONTRATACION_RECIENTE = sorted(

    c for c in df.columns
    if c.startswith("b04")

)

# ------------------------------------------------------
# TOMA DE DECISIONES
# Cómo decide contratar productos financieros
# ------------------------------------------------------

TOMA_DECISIONES = sorted(

    c for c in df.columns
    if c.startswith(("b05", "b06"))

)

# ------------------------------------------------------
# FUENTES DE INFORMACIÓN
# Información utilizada antes de contratar productos
# ------------------------------------------------------

FUENTES_INFORMACION = sorted(

    c for c in df.columns
    if c.startswith("b07")

)

# ------------------------------------------------------
# HÁBITOS DE AHORRO
# Formas de ahorro del entrevistado
# ------------------------------------------------------

HABITOS_AHORRO = sorted(

    c for c in df.columns
    if c.startswith("b10")

)

# ------------------------------------------------------
# TITULARIDAD Y SEGURIDAD
# Titularidad de productos e incidencias de fraude
# ------------------------------------------------------

TITULARIDAD_SEGURIDAD = sorted(

    c for c in df.columns
    if c.startswith("b11")

)

# ------------------------------------------------------
# RECLAMACIONES Y AYUDA
# Conflictos con entidades financieras y búsqueda de ayuda
# ------------------------------------------------------

RECLAMACIONES_AYUDA = sorted(

    c for c in df.columns
    if c.startswith("b12")

)

# ------------------------------------------------------
# COMPORTAMIENTO FINANCIERO
# ------------------------------------------------------

FINANCIAL_BEHAVIOUR = (

    RELACION_BANCARIA
    + CONOCIMIENTO_PRODUCTOS
    + PRODUCTOS_ACTUALES
    + CONTRATACION_RECIENTE
    + TOMA_DECISIONES
    + FUENTES_INFORMACION
    + HABITOS_AHORRO
    + TITULARIDAD_SEGURIDAD
    + RECLAMACIONES_AYUDA

)

In [8]:
# ======================================================
# ACTITUDES FINANCIERAS
# Actitudes frente al ahorro, preferencia temporal y gasto
# ======================================================

ATTITUDES = sorted(

    c for c in df.columns
    if c.startswith("d")

)

In [9]:
# ======================================================
# PLANIFICACIÓN DE LA JUBILACIÓN
# Expectativas y planificación financiera para la jubilación
# ======================================================

RETIREMENT = sorted(

    c for c in df.columns
    if c.startswith("c")

)

In [10]:
# ======================================================
# VIVIENDA
# Información sobre la vivienda habitual y financiación
# ======================================================

HOUSING = sorted(

    c for c in df.columns
    if c.startswith("i")

)

In [11]:
# ======================================================
# FRAGILIDAD FINANCIERA
# Liquidez, capacidad económica y resiliencia financiera
# ======================================================

FRAGILITY = sorted(

    c for c in df.columns
    if c.startswith("j")

)

In [12]:
# ======================================================
# COMPETENCIAS FINANCIERAS
# Conocimientos financieros y educación financiera
# ======================================================

# ------------------------------------------------------
# EDUCACIÓN FINANCIERA
# Formación financiera recibida
# ------------------------------------------------------

EDUCACION_FINANCIERA = sorted(

    c for c in df.columns
    if c.startswith("a1420")

)

# ------------------------------------------------------
# RESPONSABLE FINANCIERO DEL HOGAR
# Persona con mayor conocimiento financiero del hogar
# ------------------------------------------------------

RESPONSABLE_FINANCIERO = sorted(

    c for c in df.columns
    if c.startswith("f1100")

)

# ------------------------------------------------------
# TEST DE COMPETENCIAS FINANCIERAS (OCDE)
# Autoevaluación y conocimientos financieros
# ------------------------------------------------------

TEST_OCDE = sorted(

    c for c in df.columns
    if c.startswith("e")

)

# ------------------------------------------------------
# COMPETENCIAS FINANCIERAS
# ------------------------------------------------------

FINANCIAL_COMPETENCIES = (

    EDUCACION_FINANCIERA
    + RESPONSABLE_FINANCIERO
    + TEST_OCDE

)

In [13]:
# ======================================================
# BLOQUES DE VARIABLES
# ======================================================

VARIABLE_BLOCKS = {

    "COMMON": COMMON_VARS,

    "FINANCIAL_BEHAVIOUR": FINANCIAL_BEHAVIOUR,

    "ATTITUDES": ATTITUDES,

    "RETIREMENT": RETIREMENT,

    "HOUSING": HOUSING,

    "FRAGILITY": FRAGILITY,

    "FINANCIAL_COMPETENCIES": FINANCIAL_COMPETENCIES

}

In [14]:
# ======================================================
# VALIDACIÓN DE VARIABLES
# ======================================================

def validate_block(df, block_name, variables):

    existing = [v for v in variables if v in df.columns]
    missing = [v for v in variables if v not in df.columns]

    print("=" * 70)
    print(f"{block_name}")
    print("=" * 70)
    print(f"Variables definidas : {len(variables)}")
    print(f"Variables válidas   : {len(existing)}")
    print(f"Variables ausentes  : {len(missing)}")

    if missing:
        print("\nVariables NO encontradas:")
        for v in missing:
            print(f"   ❌ {v}")

    return existing

In [15]:
# ======================================================
# VALIDAR TODOS LOS BLOQUES
# ======================================================

VALIDATED_BLOCKS = {}

for block_name, variables in VARIABLE_BLOCKS.items():

    VALIDATED_BLOCKS[block_name] = validate_block(
        df,
        block_name,
        variables
    )

======================================================================
COMMON
======================================================================
Variables definidas : 17
Variables válidas   : 17
Variables ausentes  : 0
======================================================================
FINANCIAL_BEHAVIOUR
======================================================================
Variables definidas : 135
Variables válidas   : 135
Variables ausentes  : 0
======================================================================
ATTITUDES
======================================================================
Variables definidas : 26
Variables válidas   : 26
Variables ausentes  : 0
======================================================================
RETIREMENT
======================================================================
Variables definidas : 40
Variables válidas   : 40
Variables ausentes  : 0
======================================================================
HOUSING
======================================================================
Variables definidas : 41
Variables válidas   : 41
Variables ausentes  : 0
======================================================================
FRAGILITY
======================================================================
Variables definidas : 51
Variables válidas   : 51
Variables ausentes  : 0
======================================================================
FINANCIAL_COMPETENCIES
======================================================================
Variables definidas : 31
Variables válidas   : 31
Variables ausentes  : 0

In [16]:
# ======================================================
# CREACIÓN DEL MASTER DATASET
# ======================================================

MASTER_VARIABLES = []

for variables in VALIDATED_BLOCKS.values():

    MASTER_VARIABLES.extend(variables)

MASTER_VARIABLES = list(dict.fromkeys(MASTER_VARIABLES))

master_df = df[MASTER_VARIABLES].copy()

print("="*70)
print("MASTER DATASET")
print("="*70)

print(f"Observaciones : {master_df.shape[0]:,}")
print(f"Variables     : {master_df.shape[1]}")

======================================================================
MASTER DATASET
======================================================================
Observaciones : 7,764
Variables     : 340

In [17]:
# ======================================================
# CREACIÓN DEL MASTER DATASET
# ======================================================

MASTER_VARIABLES = []

for block in VARIABLE_BLOCKS.values():

    MASTER_VARIABLES.extend(block)

MASTER_VARIABLES = list(dict.fromkeys(MASTER_VARIABLES))

print(f"Variables seleccionadas: {len(MASTER_VARIABLES)}")

Variables seleccionadas: 340

In [18]:
master_df = df[MASTER_VARIABLES].copy()

In [19]:
# ======================================================
# COMPROBACIONES
# ======================================================

print("="*70)

print(f"Observaciones : {master_df.shape[0]:,}")

print(f"Variables     : {master_df.shape[1]}")

print("="*70)

======================================================================
Observaciones : 7,764
Variables     : 340
======================================================================

In [20]:
missing = (
    master_df
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(missing.head(30))

ccaaf     0
i0200g    0
i0400e    0
i0400d    0
i0400c    0
i0400b    0
i0400a    0
i0300     0
i0200j    0
i0200h    0
i0200f    0
c0600h    0
i0200e    0
i0200d    0
i0200c    0
i0200b    0
i0200a    0
i0100     0
c0600k    0
c0600j    0
i0500a    0
i0500b    0
i0500c    0
i0500d    0
i0602     0
i0601     0
i0520g    0
i0520f    0
i0520e    0
i0520d    0
dtype: int64

In [21]:
# ======================================================
# EXPORTACIÓN DEL MASTER DATASET
# ======================================================

# MASTER_OUTPUT_PATH = DATA_DIR / "2026-07-20_ECF_2021_MasterDataset.csv"
# master_df.to_csv(MASTER_OUTPUT_PATH, index=False)

# print(f"✅ Master Dataset exportado en: {MASTER_OUTPUT_PATH}")

In [22]:
# ======================================================
# RESUMEN DE BLOQUES DE VARIABLES
# ======================================================

print("=" * 70)
print("RESUMEN DEL MASTER DATASET")
print("=" * 70)

for nombre, variables in VARIABLE_BLOCKS.items():

    print(f"{nombre:<30} {len(variables):>3} variables")

print("=" * 70)
print(f"TOTAL DE VARIABLES: {sum(len(v) for v in VARIABLE_BLOCKS.values())}")
print("=" * 70)

======================================================================
RESUMEN DEL MASTER DATASET
======================================================================
COMMON                          17 variables
FINANCIAL_BEHAVIOUR            135 variables
ATTITUDES                       26 variables
RETIREMENT                      40 variables
HOUSING                         41 variables
FRAGILITY                       51 variables
FINANCIAL_COMPETENCIES          31 variables
======================================================================
TOTAL DE VARIABLES: 341
======================================================================

In [23]:
# ==========================================================
# ANALYTICAL DATASET
# Selección de variables para el análisis de Banco Atlas
# ==========================================================

In [24]:
PROFILE_VARS = [

    # Identificación territorial
    "ccaaf",

    # Demografía
    "a0000",     # Sexo
    "a0100",     # Edad

    # Nivel socioeconómico
    "a1030",     # Ingresos
    "a1100",     # Educación
    "a1500",     # Situación laboral

    # Entorno
    "a1900"     # Tamaño municipio

    
]

In [25]:
RELATIONSHIP_VARS = [

    "b0100",

    # Canales utilizados
    "b0110a",
    "b0110b",
    "b0110c",
    "b0110d",
    "b0110e",

    # Canales preferidos
    "b0120a",
    "b0120b",
    "b0120c",
    "b0120d",
    "b0120e"

]

In [26]:
ANALYTICAL_VARIABLES = (

    PROFILE_VARS +
    RELATIONSHIP_VARS

)

In [27]:
missing = [v for v in ANALYTICAL_VARIABLES if v not in master_df.columns]

if missing:
    print("Variables no encontradas:")
    print(missing)
else:
    print("Todas las variables encontradas.")

Todas las variables encontradas.

In [28]:
analytical_df = master_df[ANALYTICAL_VARIABLES].copy()

print(f"Número de variables: {analytical_df.shape[1]}")
print(f"Número de registros: {analytical_df.shape[0]}")

Número de variables: 18
Número de registros: 7764

In [29]:
# ======================================================
# EXPORTACIÓN DEL DATASET ANALÍTICO AMPLIO (212 VARIABLES)
# ======================================================

# ANALYTICAL_OUTPUT_PATH = DATA_DIR / "2026-07-20_ECF_2021_Analytical_Dataset_212.csv"
# analytical_df.to_csv(ANALYTICAL_OUTPUT_PATH, index=False)

# print(f"✅ Dataset analítico amplio exportado en: {ANALYTICAL_OUTPUT_PATH}")

In [30]:
# ==========================================================
# BLOQUE B - Relación con la banca y productos financieros
# Selección de variables para el Dataset Analítico
# ----------------------------------------------------------
# Objetivo de negocio:
# Conservar únicamente las variables que aportan información
# relevante para analizar:
#
# 1. Relación con las entidades financieras
# 2. Uso de la banca digital
# 3. Tenencia de productos financieros
# 4. Comportamiento de ahorro
# 5. Incidencias o reclamaciones con entidades financieras
#
# Se excluyen las preguntas de seguimiento (motivos,
# detalles de reclamaciones, etc.) para mantener un
# dataset analítico compacto y orientado al negocio.
# ==========================================================


# ==========================================================
# 1. RELACIÓN CON LAS ENTIDADES FINANCIERAS
# ==========================================================
RELATIONSHIP_VARS = [

    # Número de entidades financieras con las que opera
    "b0100",

    # Canales utilizados para relacionarse con las entidades
    "b0110a",
    "b0110b",
    "b0110c",
    "b0110d",
    "b0110e",
    "b0110f",

    # Frecuencia de utilización de los distintos canales
    "b0120a",
    "b0120b",
    "b0120c",
    "b0120d",
    "b0120e",
    "b0120f",

    # Uso de banca digital y aplicaciones móviles
    "b0130a",
    "b0130b"
]


# ==========================================================
# 2. PRODUCTOS FINANCIEROS ACTUALMENTE CONTRATADOS
# ==========================================================
PRODUCT_VARS = [

    "b0301",
    "b0302",
    "b0303",
    "b0304",
    "b0305",
    "b0306",
    "b0307",
    "b0308",
    "b0309",
    "b0310",
    "b0312"
]


# ==========================================================
# 3. COMPORTAMIENTO DE AHORRO
# ==========================================================
SAVING_VARS = [

    "b1000a",
    "b1000b",
    "b1000c",
    "b1000d",
    "b1000e",
    "b1000f",
    "b1000g",
    "b1000h",
    "b1000i",
    "b1000j"
]


# ==========================================================
# 4. INCIDENCIAS CON ENTIDADES FINANCIERAS
# ==========================================================
INCIDENT_VARS = [

    # Ha tenido alguna reclamación o incidencia con una entidad financiera
    "b1201"
]


# ==========================================================
# VARIABLES FINALES DEL BLOQUE B
# ==========================================================
BLOCK_B_VARS = (
    RELATIONSHIP_VARS +
    PRODUCT_VARS +
    SAVING_VARS +
    INCIDENT_VARS
)


print(f"Variables seleccionadas del bloque B: {len(BLOCK_B_VARS)}")
print(BLOCK_B_VARS)

Variables seleccionadas del bloque B: 37
['b0100', 'b0110a', 'b0110b', 'b0110c', 'b0110d', 'b0110e', 'b0110f', 'b0120a', 'b0120b', 'b0120c', 'b0120d', 'b0120e', 'b0120f', 'b0130a', 'b0130b', 'b0301', 'b0302', 'b0303', 'b0304', 'b0305', 'b0306', 'b0307', 'b0308', 'b0309', 'b0310', 'b0312', 'b1000a', 'b1000b', 'b1000c', 'b1000d', 'b1000e', 'b1000f', 'b1000g', 'b1000h', 'b1000i', 'b1000j', 'b1201']

In [31]:
# ==========================================================
# BLOQUE C - Ingresos y planificación económica
# Selección de variables para el Dataset Analítico
# ----------------------------------------------------------
# Objetivo de negocio:
# Conservar las variables que describen la situación
# económica del entrevistado y sus principales fuentes de
# ingresos, ya que pueden influir en el comportamiento
# financiero y en la contratación de productos.
#
# Se excluyen preguntas de detalle o desgloses excesivamente
# específicos que pueden generar ruido en el análisis.
# ==========================================================


# ==========================================================
# 1. SITUACIÓN ECONÓMICA GENERAL
# ==========================================================
ECONOMIC_STATUS_VARS = [

    # Situación económica principal
    "c0100",

    # Situación económica del hogar
    "c0300",

    # Indicador general relacionado con planificación económica
    "c0500"
]


# ==========================================================
# 2. FUENTES DE INGRESOS PERSONALES
# ==========================================================
INCOME_SOURCE_VARS = [

    "c0200a",
    "c0200b",
    "c0200c",
    "c0200d",
    "c0200e",
    "c0200f",
    "c0200g",
    "c0200h",
    "c0200i",
    "c0200j",
    "c0200k"
]


# ==========================================================
# 3. FUENTES DE INGRESOS DEL HOGAR
# ==========================================================
HOUSEHOLD_INCOME_VARS = [

    "c0400a",
    "c0400b",
    "c0400c",
    "c0400d",
    "c0400e",
    "c0400f",
    "c0400g",
    "c0400h",
    "c0400i",
    "c0400j",
    "c0400k",
    "c0400l",
    "c0400m",
    "c0400n"
]


# ==========================================================
# 4. INGRESOS COMPLEMENTARIOS
# ==========================================================
ADDITIONAL_INCOME_VARS = [

    "c0600a",
    "c0600b",
    "c0600c",
    "c0600d",
    "c0600e",
    "c0600f",
    "c0600g",
    "c0600h",
    "c0600i",
    "c0600j",
    "c0600k"
]


# ==========================================================
# VARIABLES FINALES DEL BLOQUE C
# ==========================================================
BLOCK_C_VARS = (
    ECONOMIC_STATUS_VARS +
    INCOME_SOURCE_VARS +
    HOUSEHOLD_INCOME_VARS +
    ADDITIONAL_INCOME_VARS
)

print(f"Variables seleccionadas del bloque C: {len(BLOCK_C_VARS)}")
print(BLOCK_C_VARS)

Variables seleccionadas del bloque C: 39
['c0100', 'c0300', 'c0500', 'c0200a', 'c0200b', 'c0200c', 'c0200d', 'c0200e', 'c0200f', 'c0200g', 'c0200h', 'c0200i', 'c0200j', 'c0200k', 'c0400a', 'c0400b', 'c0400c', 'c0400d', 'c0400e', 'c0400f', 'c0400g', 'c0400h', 'c0400i', 'c0400j', 'c0400k', 'c0400l', 'c0400m', 'c0400n', 'c0600a', 'c0600b', 'c0600c', 'c0600d', 'c0600e', 'c0600f', 'c0600g', 'c0600h', 'c0600i', 'c0600j', 'c0600k']

In [32]:
# ==========================================================
# BLOQUE D - Actitudes ante el ahorro
# Selección de variables para el Dataset Analítico
# ----------------------------------------------------------
# Objetivo de negocio:
# Conservar todas las variables relacionadas con hábitos,
# actitudes, planificación financiera y motivaciones para
# el ahorro, ya que son fundamentales para segmentar
# clientes y detectar oportunidades para adaptar o diseñar
# nuevos productos financieros.
# ==========================================================


# ==========================================================
# 1. HÁBITOS Y ACTITUDES FINANCIERAS
# ==========================================================
FINANCIAL_ATTITUDE_VARS = [

    "d0101",
    "d0102",
    "d0103",
    "d0104",
    "d0105",
    "d0106",
    "d0107",
    "d0108",
    "d0109",
    "d0110",
    "d0111",
    "d0112",
    "d0113",
    "d0114",
    "d0115",
    "d0116",
    "d0117"
]


# ==========================================================
# 2. ACTITUDES Y PLANIFICACIÓN DEL AHORRO
# ==========================================================
SAVING_ATTITUDE_VARS = [

    "d0300",
    "d0400",
    "d0500",
    "d0600"
]


# ==========================================================
# 3. MOTIVACIONES / FINALIDADES DEL AHORRO
# ==========================================================
SAVING_REASON_VARS = [

    "d0610a",
    "d0610b",
    "d0610c",
    "d0610d",
    "d0610e"
]


# ==========================================================
# VARIABLES FINALES DEL BLOQUE D
# ==========================================================
BLOCK_D_VARS = (
    FINANCIAL_ATTITUDE_VARS +
    SAVING_ATTITUDE_VARS +
    SAVING_REASON_VARS
)

print(f"Variables seleccionadas del bloque D: {len(BLOCK_D_VARS)}")
print(BLOCK_D_VARS)

Variables seleccionadas del bloque D: 26
['d0101', 'd0102', 'd0103', 'd0104', 'd0105', 'd0106', 'd0107', 'd0108', 'd0109', 'd0110', 'd0111', 'd0112', 'd0113', 'd0114', 'd0115', 'd0116', 'd0117', 'd0300', 'd0400', 'd0500', 'd0600', 'd0610a', 'd0610b', 'd0610c', 'd0610d', 'd0610e']

In [33]:
# ==========================================================
# BLOQUE E - Competencias financieras, estadísticas y económicas
# ==========================================================

FINANCIAL_LITERACY_VARS = [

    "e0100",
    "e0300",

    "e0401",
    "e0402",

    "e0500",
    "e0600",
    "e0700",
    "e0800",
    "e0900",

    "e1001",
    "e1002",
    "e1003",
    "e1004",
    "e1005",

    "e1101",

    "e1200",

    "e1300",

    "e1400",
    "e1500",
    "e1600",

    "e1701",
    "e1702",

    "e1800"
]


BLOCK_E_VARS = FINANCIAL_LITERACY_VARS

print(f"Variables seleccionadas del bloque E: {len(BLOCK_E_VARS)}")
print(BLOCK_E_VARS)

Variables seleccionadas del bloque E: 23
['e0100', 'e0300', 'e0401', 'e0402', 'e0500', 'e0600', 'e0700', 'e0800', 'e0900', 'e1001', 'e1002', 'e1003', 'e1004', 'e1005', 'e1101', 'e1200', 'e1300', 'e1400', 'e1500', 'e1600', 'e1701', 'e1702', 'e1800']

In [34]:
# ==========================================================
# BLOQUE F - Toma de decisiones en el hogar
# ==========================================================

HOUSEHOLD_DECISION_VARS = [

    "f1100"

]


# ==========================================================
# VARIABLES FINALES DEL BLOQUE F
# ==========================================================
BLOCK_F_VARS = HOUSEHOLD_DECISION_VARS

print(f"Variables seleccionadas del bloque F: {len(BLOCK_F_VARS)}")
print(BLOCK_F_VARS)

Variables seleccionadas del bloque F: 1
['f1100']

In [35]:
# ==========================================================
# BLOQUE I - Vivienda principal
# ==========================================================

# ----------------------------------------------------------
# 1. CARACTERÍSTICAS DE LA VIVIENDA
# ----------------------------------------------------------
HOUSING_VARS = [

    "i0100",

    "i0200a",
    "i0200b",
    "i0200c",
    "i0200d",
    "i0200e",
    "i0200f",
    "i0200g",
    "i0200h",
    "i0200j",

    "i0300"
]


# ----------------------------------------------------------
# 2. HIPOTECA Y FINANCIACIÓN
# ----------------------------------------------------------
MORTGAGE_VARS = [

    "i0400a",
    "i0400b",
    "i0400c",
    "i0400d",
    "i0400e",

    "i0510",

    "i0520a",
    "i0520b",
    "i0520c",
    "i0520d",
    "i0520e",
    "i0520f",
    "i0520g",

    "i0601",
    "i0602"
]


# ----------------------------------------------------------
# 3. SEGUROS Y VALORACIÓN ECONÓMICA
# ----------------------------------------------------------
PROTECTION_VARS = [

    "i0700",
    "i0800",
    "i0900",
    "i1000"
]


# ==========================================================
# VARIABLES FINALES DEL BLOQUE I
# ==========================================================
BLOCK_I_VARS = (
    HOUSING_VARS +
    MORTGAGE_VARS +
    PROTECTION_VARS
)

print(f"Variables seleccionadas del bloque I: {len(BLOCK_I_VARS)}")
print(BLOCK_I_VARS)

Variables seleccionadas del bloque I: 30
['i0100', 'i0200a', 'i0200b', 'i0200c', 'i0200d', 'i0200e', 'i0200f', 'i0200g', 'i0200h', 'i0200j', 'i0300', 'i0400a', 'i0400b', 'i0400c', 'i0400d', 'i0400e', 'i0510', 'i0520a', 'i0520b', 'i0520c', 'i0520d', 'i0520e', 'i0520f', 'i0520g', 'i0601', 'i0602', 'i0700', 'i0800', 'i0900', 'i1000']

In [36]:
# ==========================================================
# BLOQUE J - Gasto y fragilidad financiera
# ==========================================================

EXPENSE_VARS = [

    "j0100",
    "j0110",
    "j0200",

    "j0300a",
    "j0300b",
    "j0300c",
    "j0300d",
    "j0300e",
    "j0300f",
    "j0300g",
    "j0300h",
    "j0300i",
    "j0300j",
    "j0300k",
    "j0300l",
    "j0300m",
    "j0300n",
    "j0300o",
    "j0300p",

    "j0400",
    "j0500",
    "j0600",
    "j0700",

    "j0800a",
    "j0800b",
    "j0800c",
    "j0800d",
    "j0800e",
    "j0800f",
    "j0800g",
    "j0800h",

    "j0810",

    "j0900a",
    "j0900b",
    "j0900c",
    "j0900d",

    "j0910a",
    "j0910b",
    "j0910c",
    "j0910d",
    "j0910e",
    "j0910f",

    "j0920",

    "j1000",
    "j1100",

    "j1201",
    "j1202",
    "j1203",

    "j1300"
]


BLOCK_J_VARS = EXPENSE_VARS

print(f"Variables seleccionadas del bloque J: {len(BLOCK_J_VARS)}")

Variables seleccionadas del bloque J: 49

In [37]:
# ==========================================================
# VARIABLES FINALES DEL ANALYTICAL DATASET
# ==========================================================

ANALYTICAL_VARS = (
    PROFILE_VARS +
    BLOCK_B_VARS +
    BLOCK_C_VARS +
    BLOCK_D_VARS +
    BLOCK_E_VARS +
    BLOCK_F_VARS +
    BLOCK_I_VARS +
    BLOCK_J_VARS
)

# Eliminar posibles duplicados conservando el orden
ANALYTICAL_VARS = list(dict.fromkeys(ANALYTICAL_VARS))

print(f"Número total de variables: {len(ANALYTICAL_VARS)}")

Número total de variables: 212

In [38]:
analytical_df = master_df[ANALYTICAL_VARS].copy()

print(analytical_df.shape)

analytical_df.head()

(7764, 212)

,ccaaf,a0000,a0100,a1030,a1100,a1500,a1900,b0100,b0110a,b0110b,b0110c,b0110d,b0110e,b0110f,b0120a,b0120b,b0120c,b0120d,b0120e,b0120f,b0130a,b0130b,b0301,b0302,b0303,b0304,b0305,b0306,b0307,b0308,b0309,b0310,b0312,b1000a,b1000b,b1000c,b1000d,b1000e,b1000f,b1000g,b1000h,b1000i,b1000j,b1201,c0100,c0300,c0500,c0200a,c0200b,c0200c,c0200d,c0200e,c0200f,c0200g,c0200h,c0200i,c0200j,c0200k,c0400a,c0400b,c0400c,c0400d,c0400e,c0400f,c0400g,c0400h,c0400i,c0400j,c0400k,c0400l,c0400m,c0400n,c0600a,c0600b,c0600c,c0600d,c0600e,c0600f,c0600g,c0600h,c0600i,c0600j,c0600k,d0101,d0102,d0103,d0104,d0105,d0106,d0107,d0108,d0109,d0110,d0111,d0112,d0113,d0114,d0115,d0116,d0117,d0300,d0400,d0500,d0600,d0610a,d0610b,d0610c,d0610d,d0610e,e0100,e0300,e0401,e0402,e0500,e0600,e0700,e0800,e0900,e1001,e1002,e1003,e1004,e1005,e1101,e1200,e1300,e1400,e1500,e1600,e1701,e1702,e1800,f1100,i0100,i0200a,i0200b,i0200c,i0200d,i0200e,i0200f,i0200g,i0200h,i0200j,i0300,i0400a,i0400b,i0400c,i0400d,i0400e,i0510,i0520a,i0520b,i0520c,i0520d,i0520e,i0520f,i0520g,i0601,i0602,i0700,i0800,i0900,i1000,j0100,j0110,j0200,j0300a,j0300b,j0300c,j0300d,j0300e,j0300f,j0300g,j0300h,j0300i,j0300j,j0300k,j0300l,j0300m,j0300n,j0300o,j0300p,j0400,j0500,j0600,j0700,j0800a,j0800b,j0800c,j0800d,j0800e,j0800f,j0800g,j0800h,j0810,j0900a,j0900b,j0900c,j0900d,j0910a,j0910b,j0910c,j0910d,j0910e,j0910f,j0920,j1000,j1100,j1201,j1202,j1203,j1300
0,Andalucía,Mujer,España,Casado,"g. Diplomaturas universitarias, grados universitarios de 240 créditos y similares",b. Trabaja por cuenta ajena,No,Sí,No mencionado,Mencionado,No mencionado,Mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,Sí,No,No,No,No,Sí,Sí,No,No,No,No,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No,1 (MUY MAL),60,No ha lugar (no aplica filtro),Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),5-Siempre,2-Poco,3-Ni de acuerdo ni en desacuerdo,5-Siempre,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,2-Bastante en desacuerdo,3-Ni de acuerdo ni en desacuerdo,5-Completamente de acuerdo,5-Siempre,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,3-En ocasiones,4-Bastante,4-Bastante,2-Bastante en desacuerdo,5-Completamente,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),20,4,1,3,1,1,3- Medios,500.0,"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",18,200.0,a. Más de lo que podrían comprar hoy con su parte del dinero,0.0,120.0,Exactamente 110 euros,Verdadero,Verdadero,No sabe,Verdadero,1 Nada Seguro,Fondo 1 (Azul),Verdadero,5,1.0,30.0,"d. Aproximadamente, 15 de cada 100 personas que utilizan esta medicación desarrollan un sarpullido.",Tipo de interés del 1%,Tipo de interés del 3%,a. La economía ha crecido en un 1%,Titular muestral,a. Propiedad por compra (mayoritariamente) –incluye permuta y construcción propia,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),1,2,5,1,1,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,Para financiar la compra de la vivienda principal,450,2007,80,No,Sí,No,Sí,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,g. Un año o más,800,Un mes,1500,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Todas las personas seleccionadas forman parte del hogar,No mencionado,No mencionado,No mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No,No,No,d. Entre 27.001 y 47.000 euros
1,Canarias,Mujer,España,Soltero,"h. Grados universitarios de más de 240 créditos, licenciaturas, másteres y similares",b. Trabaja por cuenta ajena,No,Sí,Mencionado,Mencionado,Mencionado,Mencionado,Mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No,No,No,No,No,Sí,Sí,No,No,Sí,No,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No,3 (REGULAR),67,No ha lugar (no aplica filtro),Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),3-En ocasiones,2-Poco,2-Bastante en desacuerdo,5-Siempre,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Bastante de acuerdo,4-Con frecuencia,4-Bastante de acuerdo,1-Completamente en desacuerdo,4-Con frecuencia,2-Poco,2-Poco,2-Bastante en desacuerdo,4-Bastante,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),50,0,2,0,8,0,3- Medios,No sabe,"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",24,200.0,c. Menos de lo que podrían comprar hoy,0.0,100.0,No sabe,No sabe,Verdadero,No sabe,Falso,3,Fondo 2 (Verde),Falso,1 - Nada Seguro,3.0,30.0,"b. Para aplicaciones en la piel, utilizar solo un 15% de la dosis recomendada.",Tipo de interés del 3%,Tipo de interés del 1%,e. El valor del euro ha crecido en un 1%,Titular muestral,b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),0,2,1,6,1,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,Sí,No,Sí,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,"c. Por lo menos un mes, pero menos de tres meses",300,Un mes,0,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Ambos,No,No ha lugar (no aplica filtro),No,No,Sí,d. Entre 27.001 y 47.000 euros
2,Extremadura,Hombre,España,Viudo,d. Segunda etapa de Educación Secundaria y similar,b. Trabaja por cuenta ajena,No,Sí,No mencionado,Mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,No mencionado,Mencionado,Mencionado,No,Sí,Sí,Sí,No,No,Sí,No,No,Sí,Sí,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,No,4 (BIEN),60,No ha lugar (no aplica filtro),Mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,Mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),4-Con frecuencia,3-Indiferente,2-Bastante en desacuerdo,5-Siempre,4-Bastante de acuerdo,3-Ni de acuerdo ni en desacuerdo,3-Ni de acuerdo ni en desacuerdo,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,5-Siempre,1-Completamente en desacuerdo,5-Completamente de acuerdo,3-En ocasiones,3-Indiferente,2-Poco,1-Completamente en desacuerdo,1-No en absoluto,2.200 euros dentro de un año,No ha lugar (no aplica filtro),2.100 euros dentro de un año,0,5,0,5,0,0,3- Medios,5.0,"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",18,200.0,c. Menos de lo que podrían comprar hoy,0.0,102.0,Más de 110 euros,Verdadero,Verdadero,Verdadero,No ha lugar (no aplica filtro),9,Fondo 1 (Azul),Verdadero,10 - Muy Seguro,10.0,30.0,"d. Aproximadamente, 15 de cada 100 personas que utilizan esta medicación desarrollan un sarpullido.",Tipo de interés del 1%,Tipo de interés del 3%,a. La economía ha crecido en un 1%,No ha lugar (no aplica filtro),b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),0,0,0,10,0,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),Sí,No,No,No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),g. Un año o más,350,Un mes,0,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No,No,No,d. Entre 27.001 y 47.000 euros
3,Canarias,Hombre,España,Casado,d. Segunda etapa de Educación Secundaria y similar,b. Trabaja por cuenta ajena,No,Sí,No mencionado,Mencionado,No mencionado,Mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,Mencionado,Mencionado,Sí,Sí,No,No,No,No,Sí,Sí,Sí,No,No,No mencionado,No mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No,4 (BIEN),62,No ha lugar (no aplica filtro),Mencionado,Mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),5-Siempre,1-No en absoluto,1-Completamente en desacuerdo,5-Siempre,1-Completamente en desacuerdo,5-Completamente de acuerdo,3-Ni de acuerdo ni en desacuerdo,2-Bastante en desacuerdo,4-Bastante de acuerdo,5-Siempre,2-Bastante en desacuerdo,4-Bastante de acuerdo,3-En ocasiones,5-Completamente,2-Poco,3-Ni de acuerdo ni en desacuerdo,4-Bastante,2.000 euros hoy,3.000 euros dentro de un año,No ha lugar (no aplica filtro),50,0,8,2,0,0,3- Medios,100.0,"Un portavoz de la nadadora, Javier Pascual, dijo que durante la prueba Cabañero repuso fuerzas a...",18,200.0,b. La misma cantidad,0.0,102.0,Exactamente 110 euros,Verdadero,Verdadero,No sabe,No sabe,No ha lugar (no aplica filtro),Fondo 3 (Rojo),Verdadero,7,10.0,30.0,"d. Aproximadamente, 15 de cada 100 personas que utilizan esta medicación desarrollan un sarpullido.",Tipo de interés del 1%,Tipo de interés del 3%,a. La economía ha crecido en un 1%,Titular muestral,a. Propiedad por compra (mayoritariamente) –incluye permuta y construcción propia,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),0,0,2,8,0,Sí,No mencionado,No mencionado,No mencionado,Mencionado,No mencionado,Mencionado,No mencionado,Sí,Para financiar la compra de la vivienda principal,289,2021,100,No,No,No,No,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),"d. Por lo menos tres meses, pero menos de seis meses",500,Un mes,0,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No mencionado,No mencionado,No mencionado,Mencionado,No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No ha lugar (no aplica filtro),No,No ha lugar (no aplica filtro),No,No,No,d. Entre 27.001 y 47.000 euros

In [39]:
print(f"Número de filas : {analytical_df.shape[0]}")
print(f"Número de columnas : {analytical_df.shape[1]}")

Número de filas : 7764
Número de columnas : 212

In [40]:
blocks = {
    "Perfil (A)": PROFILE_VARS,
    "Productos (B)": BLOCK_B_VARS,
    "Rentas (C)": BLOCK_C_VARS,
    "Actitudes (D)": BLOCK_D_VARS,
    "Competencias (E)": BLOCK_E_VARS,
    "Hogar (F)": BLOCK_F_VARS,
    "Vivienda (I)": BLOCK_I_VARS,
    "Fragilidad (J)": BLOCK_J_VARS,
}

for name, vars_ in blocks.items():
    print(f"{name:<20} {len(vars_):>3} variables")

Perfil (A)             7 variables
Productos (B)         37 variables
Rentas (C)            39 variables
Actitudes (D)         26 variables
Competencias (E)      23 variables
Hogar (F)              1 variables
Vivienda (I)          30 variables
Fragilidad (J)        49 variables


# Dataset analítico compacto: reducción de 212 a 65 variables

Esta sección continúa **sobre el notebook original** y parte del `analytical_df` construido anteriormente.

## Objetivo

Crear un dataset compacto y orientado a negocio para responder:

> **¿Es necesario adaptar las ofertas actuales o crear nuevas en función de las tendencias nacionales en comportamiento financiero y competencias financieras?**

La reducción se realiza mediante **feature engineering interpretable**, no mediante PCA, selección automática, correlaciones ni modelos de caja negra.

Se conservan variables escalares clave y se sustituyen grupos de preguntas múltiples por indicadores de:

- relación y digitalización bancaria;
- tenencia de productos y comportamiento de ahorro;
- fuentes de ingresos y planificación;
- actitudes financieras;
- competencias financieras;
- acceso a vivienda;
- fragilidad y restricción crediticia.

El resultado final contiene **7.764 observaciones y exactamente 65 variables**.

In [41]:

# ==========================================================
# FEATURE ENGINEERING — DATASET ANALÍTICO COMPACTO (65 VAR.)
# ==========================================================
# Esta sección parte de analytical_df (212 variables) y crea indicadores
# interpretables. Las variables originales no se modifican.

compact_work = analytical_df.copy()

# ---------- Utilidades ----------
NA_LABELS = {"No sabe", "No contesta", "-4", "-5", "No ha lugar (no aplica filtro)"}

def _norm_text(s):
    return s.astype("string").str.strip()

def es_mencionado(s):
    return _norm_text(s).eq("Mencionado")

def es_si(s):
    return _norm_text(s).eq("Sí")

def contar_mencionados(data, cols):
    """Cuenta opciones seleccionadas en preguntas de respuesta múltiple."""
    cols = [c for c in cols if c in data.columns]
    if not cols:
        return pd.Series(np.nan, index=data.index, dtype="float")
    return data[cols].apply(es_mencionado).sum(axis=1).astype("Int64")

def alguna_mencionada(data, cols):
    """1 cuando al menos una opción del grupo fue seleccionada."""
    return (contar_mencionados(data, cols) > 0).astype("Int64")

def alguna_si(data, cols):
    """1 cuando al menos una variable binaria del grupo toma el valor Sí."""
    cols = [c for c in cols if c in data.columns]
    if not cols:
        return pd.Series(pd.NA, index=data.index, dtype="Int64")
    return data[cols].apply(es_si).any(axis=1).astype("Int64")

def numeric_safe(s):
    return pd.to_numeric(s, errors="coerce")

def likert_score(s):
    """Extrae el valor inicial de etiquetas como '4-Con frecuencia'."""
    return pd.to_numeric(
        _norm_text(s).str.extract(r"^\s*(\d+)", expand=False),
        errors="coerce"
    )

def mean_likert(data, cols, reverse=None):
    """Media de ítems Likert; permite invertir ítems formulados negativamente."""
    reverse = set(reverse or [])
    values = pd.DataFrame(index=data.index)
    for c in cols:
        x = likert_score(data[c])
        if c in reverse:
            x = 6 - x
        values[c] = x
    return values.mean(axis=1, skipna=True)

def correct_score(series, accepted):
    """1 correcta; 0 incorrecta, no sabe o no contesta."""
    accepted = {str(v).strip() for v in accepted}
    return _norm_text(series).isin(accepted).astype("Int64")


# ==========================================================
# BLOQUE B — RELACIÓN BANCARIA, PRODUCTOS Y AHORRO
# ==========================================================
B0110 = [f"b0110{x}" for x in "abcdef"]
B0120 = [f"b0120{x}" for x in "abcdef"]
B030 = [
    "b0301", "b0302", "b0303", "b0304", "b0305", "b0306",
    "b0307", "b0308", "b0309", "b0310", "b0312"
]
B1000_ACTIVE = [f"b1000{x}" for x in "abcdefghi"]

compact_work["n_canales_uso_banco"] = contar_mencionados(compact_work, B0110)
compact_work["usa_banca_digital"] = alguna_mencionada(
    compact_work, ["b0110d", "b0110e"]
)
compact_work["pref_banca_digital"] = alguna_mencionada(
    compact_work, ["b0120d", "b0120e"]
)
compact_work["usa_pago_digital"] = alguna_mencionada(
    compact_work, ["b0130a", "b0130b"]
)

compact_work["n_productos_financieros"] = (
    compact_work[B030].apply(es_si).sum(axis=1).astype("Int64")
)
compact_work["tiene_vehiculo_ahorro"] = alguna_si(
    compact_work, ["b0302", "b0303", "b0304", "b0305", "b0308", "b0312"]
)
compact_work["tiene_exposicion_credito"] = alguna_si(
    compact_work, ["b0301", "b0306", "b0307"]
)
compact_work["tiene_seguro"] = alguna_si(
    compact_work, ["b0309", "b0310"]
)

compact_work["n_vehiculos_ahorro"] = contar_mencionados(
    compact_work, B1000_ACTIVE
)
compact_work["ahorra_12m"] = (
    compact_work["n_vehiculos_ahorro"].gt(0).astype("Int64")
)
# La opción explícita «no ha estado ahorrando» prevalece.
compact_work.loc[
    es_mencionado(compact_work["b1000j"]), "ahorra_12m"
] = 0

compact_work["ahorro_formal"] = alguna_mencionada(
    compact_work, ["b1000b", "b1000c", "b1000g", "b1000h"]
)
compact_work["ahorro_informal"] = alguna_mencionada(
    compact_work, ["b1000a", "b1000d", "b1000e", "b1000f", "b1000i"]
)

INDICATORS_B = [
    "n_canales_uso_banco", "usa_banca_digital", "pref_banca_digital",
    "usa_pago_digital", "n_productos_financieros", "tiene_vehiculo_ahorro",
    "tiene_exposicion_credito", "tiene_seguro", "ahorra_12m",
    "n_vehiculos_ahorro", "ahorro_formal", "ahorro_informal"
]
SCALARS_B = ["b0100", "b1201"]


# ==========================================================
# BLOQUE C — FUENTES DE INGRESO Y JUBILACIÓN
# ==========================================================
C0200 = [f"c0200{x}" for x in "abcdefghijk"]
C0400 = [f"c0400{x}" for x in "abcdefghijklmn"]
C0600 = [f"c0600{x}" for x in "abcdefghijk"]
C_ALL = C0200 + C0400 + C0600

compact_work["n_fuentes_ingreso"] = contar_mencionados(compact_work, C_ALL)
compact_work["ingreso_por_activos"] = alguna_mencionada(
    compact_work,
    [
        "c0200f", "c0200g", "c0200h",
        "c0400h", "c0400i", "c0400j", "c0400k", "c0400m",
        "c0600f", "c0600g", "c0600h"
    ]
)
compact_work["dependencia_ingresos_familiares"] = alguna_mencionada(
    compact_work,
    [
        "c0200d", "c0200e", "c0200i",
        "c0400c", "c0400d", "c0400e", "c0400f", "c0400l",
        "c0600d", "c0600e", "c0600i"
    ]
)

INDICATORS_C = [
    "n_fuentes_ingreso", "ingreso_por_activos",
    "dependencia_ingresos_familiares"
]
SCALARS_C = ["c0100", "c0300", "c0500"]


# ==========================================================
# BLOQUE D — ACTITUDES Y USO DE UN INGRESO EXTRA
# ==========================================================
# Constructos sin ítems duplicados:
# control/disciplina, orientación al futuro y preocupación financiera.
compact_work["score_disciplina_financiera"] = mean_likert(
    compact_work, ["d0101", "d0104", "d0106", "d0113"]
)
compact_work["score_planificacion_financiera"] = mean_likert(
    compact_work,
    ["d0102", "d0103", "d0107", "d0108", "d0116"],
    reverse=["d0102", "d0103", "d0108", "d0116"]
)
compact_work["score_preocupacion_financiera"] = mean_likert(
    compact_work, ["d0109", "d0110", "d0111", "d0114", "d0117"]
)

for c in ["d0610a", "d0610b", "d0610c", "d0610d", "d0610e"]:
    compact_work[c] = numeric_safe(compact_work[c])

compact_work["puntos_destino_consumo"] = (
    compact_work["d0610a"] + compact_work["d0610b"]
)
compact_work["puntos_destino_ahorro"] = compact_work["d0610c"]
compact_work["puntos_destino_deuda"] = compact_work["d0610d"]

INDICATORS_D = [
    "score_disciplina_financiera", "score_preocupacion_financiera",
    "score_planificacion_financiera", "puntos_destino_consumo",
    "puntos_destino_ahorro", "puntos_destino_deuda"
]
SCALARS_D = ["d0300", "d0400", "d0500", "d0600"]


# ==========================================================
# BLOQUE E — COMPETENCIAS FINANCIERAS
# ==========================================================
compact_work["score_alfabetizacion_financiera"] = (
    correct_score(
        compact_work["e0600"],
        {"c. Menos de lo que podrían comprar hoy"}
    )
    + correct_score(compact_work["e0900"], {"Más de 110 euros"})
    + correct_score(compact_work["e1003"], {"Verdadero"})
).astype("Int64")

compact_work["score_numeracy_financiera"] = (
    numeric_safe(compact_work["e0500"]).eq(200).astype("Int64")
    + numeric_safe(compact_work["e0700"]).eq(0).astype("Int64")
    + numeric_safe(compact_work["e0800"]).eq(102).astype("Int64")
).astype("Int64")

compact_work["score_comprension_riesgo"] = (
    correct_score(compact_work["e1001"], {"Verdadero"})
    + correct_score(compact_work["e1003"], {"Verdadero"})
    + correct_score(compact_work["e1101"], {"Fondo 1 (Azul)"})
).astype("Int64")

compact_work["score_competencia_economica"] = (
    correct_score(compact_work["e1701"], {"Tipo de interés del 1%"})
    + correct_score(compact_work["e1702"], {"Tipo de interés del 3%"})
    + correct_score(
        compact_work["e1800"],
        {"a. La economía ha crecido en un 1%"}
    )
).astype("Int64")

compact_work["score_conocimiento_productos"] = (
    correct_score(compact_work["e1002"], {"Verdadero"})
    + correct_score(compact_work["e1200"], {"Verdadero"})
).astype("Int64")

INDICATORS_E = [
    "score_alfabetizacion_financiera", "score_numeracy_financiera",
    "score_comprension_riesgo", "score_competencia_economica",
    "score_conocimiento_productos"
]
SCALARS_E = ["e0100", "e0300"]


# ==========================================================
# BLOQUE F — DECISIONES FINANCIERAS DEL HOGAR
# ==========================================================
SCALARS_F = ["f1100"]


# ==========================================================
# BLOQUE I — VIVIENDA
# ==========================================================
I0520 = [f"i0520{x}" for x in "abcdefg"]

compact_work["barrera_acceso_vivienda"] = alguna_mencionada(
    compact_work,
    ["i0200d", "i0200e", "i0200h", "i0520d", "i0520e", "i0520f"]
)
compact_work["n_dificultades_compra_vivienda"] = contar_mencionados(
    compact_work, I0520
)

for c in ["i0400a", "i0400b", "i0400c", "i0400d", "i0400e"]:
    compact_work[c] = numeric_safe(compact_work[c])

compact_work["expectativa_subida_precio_vivienda"] = (
    compact_work["i0400d"] + compact_work["i0400e"]
)

INDICATORS_I = [
    "barrera_acceso_vivienda", "expectativa_subida_precio_vivienda",
    "n_dificultades_compra_vivienda"
]
SCALARS_I = ["i0100", "i0510", "i1000"]


# ==========================================================
# BLOQUE J — FRAGILIDAD FINANCIERA
# ==========================================================
compact_work["financiacion_ahorros_activos"] = alguna_mencionada(
    compact_work, ["j0300a", "j0300b"]
)
compact_work["financiacion_credito_informal"] = alguna_mencionada(
    compact_work, ["j0300c", "j0300d", "j0300l"]
)
compact_work["financiacion_credito_formal"] = alguna_mencionada(
    compact_work,
    [
        "j0300e", "j0300f", "j0300g", "j0300h",
        "j0300i", "j0300j", "j0300k"
    ]
)
compact_work["financiacion_estres_pago"] = alguna_mencionada(
    compact_work, ["j0300m", "j0300n"]
)
compact_work["restriccion_acceso_credito"] = alguna_mencionada(
    compact_work, ["j0900a", "j0900b", "j0900c"]
)

compact_work["score_fragilidad_financiera"] = (
    es_si(compact_work["j0200"]).astype("Int64")
    + es_si(compact_work["j1000"]).astype("Int64")
    + es_si(compact_work["j1201"]).astype("Int64")
    + compact_work["restriccion_acceso_credito"]
).astype("Int64")

INDICATORS_J = [
    "financiacion_ahorros_activos", "financiacion_credito_informal",
    "financiacion_credito_formal", "financiacion_estres_pago",
    "restriccion_acceso_credito", "score_fragilidad_financiera"
]
SCALARS_J = [
    "j0100", "j0110", "j0200", "j0400",
    "j1000", "j1201", "j1203", "j1300"
]


# ==========================================================
# DATASET FINAL — EXACTAMENTE 65 VARIABLES
# ==========================================================
PROFILE_FINAL = [
    "ccaaf", "a0000", "a0100", "a1030",
    "a1100", "a1500", "a1900"
]

COMPACT_FINAL_VARS = (
    PROFILE_FINAL
    + SCALARS_B + INDICATORS_B
    + SCALARS_C + INDICATORS_C
    + SCALARS_D + INDICATORS_D
    + SCALARS_E + INDICATORS_E
    + SCALARS_F
    + SCALARS_I + INDICATORS_I
    + SCALARS_J + INDICATORS_J
)

assert len(COMPACT_FINAL_VARS) == 65, (
    f"Se esperaban 65 variables y se han definido {len(COMPACT_FINAL_VARS)}"
)
assert len(COMPACT_FINAL_VARS) == len(set(COMPACT_FINAL_VARS)), (
    "Hay variables duplicadas en COMPACT_FINAL_VARS"
)

missing_final = [
    c for c in COMPACT_FINAL_VARS if c not in compact_work.columns
]
assert not missing_final, f"Faltan variables finales: {missing_final}"

analytical_df_compact = compact_work[COMPACT_FINAL_VARS].copy()

assert analytical_df_compact.shape[0] == analytical_df.shape[0]
assert analytical_df_compact.shape[1] == 65

print("✅ Dataset analítico compacto creado correctamente")
print(f"Observaciones : {analytical_df_compact.shape[0]:,}")
print(f"Variables     : {analytical_df_compact.shape[1]}")

✅ Dataset analítico compacto creado correctamente
Observaciones : 7,764
Variables     : 65

In [42]:

# ==========================================================
# VALIDACIÓN Y TRAZABILIDAD DE LA REDUCCIÓN
# ==========================================================

BLOCK_FINALS = {
    "A — Perfil": PROFILE_FINAL,
    "B — Banca y ahorro": SCALARS_B + INDICATORS_B,
    "C — Ingresos": SCALARS_C + INDICATORS_C,
    "D — Actitudes": SCALARS_D + INDICATORS_D,
    "E — Competencias": SCALARS_E + INDICATORS_E,
    "F — Hogar": SCALARS_F,
    "I — Vivienda": SCALARS_I + INDICATORS_I,
    "J — Fragilidad": SCALARS_J + INDICATORS_J,
}

ORIGINAL_COUNTS = {
    "A — Perfil": len(PROFILE_VARS),
    "B — Banca y ahorro": len(BLOCK_B_VARS),
    "C — Ingresos": len(BLOCK_C_VARS),
    "D — Actitudes": len(BLOCK_D_VARS),
    "E — Competencias": len(BLOCK_E_VARS),
    "F — Hogar": len(BLOCK_F_VARS),
    "I — Vivienda": len(BLOCK_I_VARS),
    "J — Fragilidad": len(BLOCK_J_VARS),
}

reduction_summary = pd.DataFrame([
    {
        "Bloque": block,
        "Variables originales": ORIGINAL_COUNTS[block],
        "Variables finales": len(final_vars),
        "Reducción": ORIGINAL_COUNTS[block] - len(final_vars),
    }
    for block, final_vars in BLOCK_FINALS.items()
])

reduction_summary.loc["TOTAL"] = {
    "Bloque": "TOTAL",
    "Variables originales": len(ANALYTICAL_VARS),
    "Variables finales": analytical_df_compact.shape[1],
    "Reducción": len(ANALYTICAL_VARS) - analytical_df_compact.shape[1],
}

display(reduction_summary)

print("\nDuplicados en el dataset final:",
      analytical_df_compact.columns.duplicated().sum())
print("Columnas completamente vacías:",
      analytical_df_compact.isna().all().sum())

display(analytical_df_compact.head())

                   Bloque  Variables originales  Variables finales  Reducción
0              A — Perfil                     7                  7          0
1      B — Banca y ahorro                    37                 14         23
2            C — Ingresos                    39                  6         33
3           D — Actitudes                    26                 10         16
4        E — Competencias                    23                  7         16
5               F — Hogar                     1                  1          0
6            I — Vivienda                    30                  6         24
7          J — Fragilidad                    49                 14         35
TOTAL               TOTAL                   212                 65        147

Duplicados en el dataset final: 0
Columnas completamente vacías: 0

,ccaaf,a0000,a0100,a1030,a1100,a1500,a1900,b0100,b1201,n_canales_uso_banco,usa_banca_digital,pref_banca_digital,usa_pago_digital,n_productos_financieros,tiene_vehiculo_ahorro,tiene_exposicion_credito,tiene_seguro,ahorra_12m,n_vehiculos_ahorro,ahorro_formal,ahorro_informal,c0100,c0300,c0500,n_fuentes_ingreso,ingreso_por_activos,dependencia_ingresos_familiares,d0300,d0400,d0500,d0600,score_disciplina_financiera,score_preocupacion_financiera,score_planificacion_financiera,puntos_destino_consumo,puntos_destino_ahorro,puntos_destino_deuda,e0100,e0300,score_alfabetizacion_financiera,score_numeracy_financiera,score_comprension_riesgo,score_competencia_economica,score_conocimiento_productos,f1100,i0100,i0510,i1000,barrera_acceso_vivienda,expectativa_subida_precio_vivienda,n_dificultades_compra_vivienda,j0100,j0110,j0200,j0400,j1000,j1201,j1203,j1300,financiacion_ahorros_activos,financiacion_credito_informal,financiacion_credito_formal,financiacion_estres_pago,restriccion_acceso_credito,score_fragilidad_financiera
0,Andalucía,Mujer,España,Casado,"g. Diplomaturas universitarias, grados universitarios de 240 créditos y similares",b. Trabaja por cuenta ajena,No,Sí,No,3,1,0,1,3,0,1,0,1,1,0,1,1 (MUY MAL),60,No ha lugar (no aplica filtro),2,0,1,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),20,3.75,4.4,3.2,5.0,3.0,1.0,3- Medios,500.0,0,2,2,3,2,Titular muestral,a. Propiedad por compra (mayoritariamente) –incluye permuta y construcción propia,No ha lugar (no aplica filtro),No,0,2.0,0,Sí,No,Sí,g. Un año o más,No,No,No,d. Entre 27.001 y 47.000 euros,1,0,0,0,0,1
1,Canarias,Mujer,España,Soltero,"h. Grados universitarios de más de 240 créditos, licenciaturas, másteres y similares",b. Trabaja por cuenta ajena,No,Sí,No,5,1,0,1,3,0,1,1,0,0,0,0,3 (REGULAR),67,No ha lugar (no aplica filtro),1,0,0,2.000 euros hoy,2.000 euros hoy,No ha lugar (no aplica filtro),50,4.0,3.6,3.6,2.0,0.0,8.0,3- Medios,No sabe,1,2,0,0,1,Titular muestral,b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),Sí,0,7.0,0,Sí,No,Sí,"c. Por lo menos un mes, pero menos de tres meses",No,No,Sí,d. Entre 27.001 y 47.000 euros,0,1,0,0,1,2
2,Extremadura,Hombre,España,Viudo,d. Segunda etapa de Educación Secundaria y similar,b. Trabaja por cuenta ajena,No,Sí,No,3,1,1,1,6,1,1,1,1,3,1,0,4 (BIEN),60,No ha lugar (no aplica filtro),5,1,0,2.200 euros dentro de un año,No ha lugar (no aplica filtro),2.100 euros dentro de un año,0,3.75,2.4,3.6,5.0,5.0,0.0,3- Medios,5.0,3,3,3,3,2,No ha lugar (no aplica filtro),b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),Sí,0,10.0,0,No,No,No,g. Un año o más,No,No,No,d. Entre 27.001 y 47.000 euros,0,0,0,0,0,0
3,Canarias,Hombre,España,Casado,d. Segunda etapa de Educación Secundaria y similar,b. Trabaja por cuenta ajena,No,Sí,No,3,1,1,1,5,1,1,1,1,1,1,0,4 (BIEN),62,No ha lugar (no aplica filtro),2,0,0,2.000 euros hoy,3.000 euros dentro de un año,No ha lugar (no aplica filtro),50,4.5,4.0,4.0,8.0,2.0,0.0,3- Medios,100.0,0,3,1,3,2,Titular muestral,a. Propiedad por compra (mayoritariamente) –incluye permuta y construcción propia,Sí,No,1,8.0,2,No,No,No,"d. Por lo menos tres meses, pero menos de seis meses",No,No,No,d. Entre 27.001 y 47.000 euros,0,0,0,0,0,0
4,"Balears, Illes",Hombre,España,Soltero,b. Educación primaria Incluye sabe leer y escribir pero no tiene título,b. Trabaja por cuenta ajena,No,Sí,No,4,1,0,1,2,0,1,0,0,0,0,0,3 (REGULAR),65,No ha lugar (no aplica filtro),2,0,1,2.200 euros dentro de un año,No ha lugar (no aplica filtro),2.100 euros dentro de un año,25,4.0,2.6,3.8,10.0,0.0,0.0,1- Muy bajos,2.0,1,1,1,0,2,Madre,b. Propiedad por herencia o regalo (mayoritariamente),No ha lugar (no aplica filtro),No,0,0.0,0,Sí,Sí,Sí,"b. Por lo menos una semana, pero menos de un mes",Sí,Sí,No,b. Entre 9.501 y 15.000 euros,0,0,1,0,0,3

In [43]:

# ==========================================================
# DICCIONARIO DE INDICADORES CREADOS
# ==========================================================

INDICATOR_DICTIONARY = pd.DataFrame([
    ("n_canales_uso_banco", "Número de canales utilizados para relacionarse con el banco."),
    ("usa_banca_digital", "Uso de ordenador/tablet o app móvil bancaria."),
    ("pref_banca_digital", "Preferencia por ordenador/tablet o app móvil bancaria."),
    ("usa_pago_digital", "Uso de aplicaciones o banca online para realizar pagos."),
    ("n_productos_financieros", "Número de familias/productos financieros actualmente contratados."),
    ("tiene_vehiculo_ahorro", "Tenencia de algún producto de ahorro o inversión."),
    ("tiene_exposicion_credito", "Tenencia de hipoteca, préstamo personal o tarjeta de crédito."),
    ("tiene_seguro", "Tenencia de seguro de vida o seguro médico."),
    ("ahorra_12m", "Ha utilizado al menos un mecanismo de ahorro en los últimos 12 meses."),
    ("n_vehiculos_ahorro", "Número de mecanismos de ahorro utilizados."),
    ("ahorro_formal", "Uso de cuentas, depósitos, fondos o planes de pensiones para ahorrar."),
    ("ahorro_informal", "Uso de efectivo, familia, inmuebles, remesas u otros mecanismos."),
    ("n_fuentes_ingreso", "Número de fuentes actuales o previstas de ingresos."),
    ("ingreso_por_activos", "Obtiene o prevé obtener ingresos mediante activos o ahorros."),
    ("dependencia_ingresos_familiares", "Dependencia de pareja, familia, ayudas o instituciones."),
    ("score_disciplina_financiera", "Media 1–5 de control, pago puntual, vigilancia e información."),
    ("score_preocupacion_financiera", "Media 1–5 de preocupación, endeudamiento e inquietud."),
    ("score_planificacion_financiera", "Media 1–5 orientada al futuro; ítems negativos invertidos."),
    ("puntos_destino_consumo", "Puntos del ingreso extra destinados a consumo."),
    ("puntos_destino_ahorro", "Puntos del ingreso extra destinados a ahorro."),
    ("puntos_destino_deuda", "Puntos del ingreso extra destinados a pagar deuda."),
    ("score_alfabetizacion_financiera", "Aciertos 0–3: inflación, interés compuesto y diversificación."),
    ("score_numeracy_financiera", "Aciertos 0–3 en cálculos financieros básicos."),
    ("score_comprension_riesgo", "Aciertos 0–3 sobre riesgo, diversificación y rendimiento."),
    ("score_competencia_economica", "Aciertos 0–3 sobre tipos de interés y crecimiento económico."),
    ("score_conocimiento_productos", "Aciertos 0–2 sobre inflación y características hipotecarias."),
    ("barrera_acceso_vivienda", "Presenta barreras de entrada, cuota o acceso hipotecario."),
    ("expectativa_subida_precio_vivienda", "Puntos asignados a escenarios de subida del precio."),
    ("n_dificultades_compra_vivienda", "Número de dificultades experimentadas al comprar vivienda."),
    ("financiacion_ahorros_activos", "Cubrió el déficit utilizando ahorros o vendiendo activos."),
    ("financiacion_credito_informal", "Cubrió el déficit mediante familia, adelantos o proveedores."),
    ("financiacion_credito_formal", "Cubrió el déficit mediante crédito o financiación formal."),
    ("financiacion_estres_pago", "Utilizó descubierto no autorizado o retrasó pagos."),
    ("restriccion_acceso_credito", "Rechazo, concesión parcial o autoexclusión crediticia."),
    ("score_fragilidad_financiera", "Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia."),
], columns=["Variable", "Definición"])

display(INDICATOR_DICTIONARY)

,Variable,Definición
0,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.
1,usa_banca_digital,Uso de ordenador/tablet o app móvil bancaria.
2,pref_banca_digital,Preferencia por ordenador/tablet o app móvil bancaria.
3,usa_pago_digital,Uso de aplicaciones o banca online para realizar pagos.
4,n_productos_financieros,Número de familias/productos financieros actualmente contratados.
5,tiene_vehiculo_ahorro,Tenencia de algún producto de ahorro o inversión.
6,tiene_exposicion_credito,"Tenencia de hipoteca, préstamo personal o tarjeta de crédito."
7,tiene_seguro,Tenencia de seguro de vida o seguro médico.
8,ahorra_12m,Ha utilizado al menos un mecanismo de ahorro en los últimos 12 meses.
9,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.
10,ahorro_formal,"Uso de cuentas, depósitos, fondos o planes de pensiones para ahorrar."
11,ahorro_informal,"Uso de efectivo, familia, inmuebles, remesas u otros mecanismos."
12,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.
13,ingreso_por_activos,Obtiene o prevé obtener ingresos mediante activos o ahorros.
14,dependencia_ingresos_familiares,"Dependencia de pareja, familia, ayudas o instituciones."
15,score_disciplina_financiera,"Media 1–5 de control, pago puntual, vigilancia e información."
16,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud."
17,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.
18,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.
19,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.
20,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.
21,score_alfabetizacion_financiera,"Aciertos 0–3: inflación, interés compuesto y diversificación."
22,score_numeracy_financiera,Aciertos 0–3 en cálculos financieros básicos.
23,score_comprension_riesgo,"Aciertos 0–3 sobre riesgo, diversificación y rendimiento."
24,score_competencia_economica,Aciertos 0–3 sobre tipos de interés y crecimiento económico.
25,score_conocimiento_productos,Aciertos 0–2 sobre inflación y características hipotecarias.
26,barrera_acceso_vivienda,"Presenta barreras de entrada, cuota o acceso hipotecario."
27,expectativa_subida_precio_vivienda,Puntos asignados a escenarios de subida del precio.
28,n_dificultades_compra_vivienda,Número de dificultades experimentadas al comprar vivienda.
29,financiacion_ahorros_activos,Cubrió el déficit utilizando ahorros o vendiendo activos.
30,financiacion_credito_informal,"Cubrió el déficit mediante familia, adelantos o proveedores."
31,financiacion_credito_formal,Cubrió el déficit mediante crédito o financiación formal.
32,financiacion_estres_pago,Utilizó descubierto no autorizado o retrasó pagos.
33,restriccion_acceso_credito,"Rechazo, concesión parcial o autoexclusión crediticia."
34,score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia."

In [44]:
# ==========================================================
# EXPORTACIÓN DEL DATASET COMPACTO
# ==========================================================

OUTPUT_PATH = DATA_DIR / "2026-07-20_ECF_2021_02_MasterDataset.csv"
DICTIONARY_PATH = DATA_DIR / "2026-07-20_ECF_2021_02_MasterDataset_Diccionario.csv"

analytical_df_compact.to_csv(OUTPUT_PATH, index=False)
INDICATOR_DICTIONARY.to_csv(DICTIONARY_PATH, index=False)

print(f"✅ Dataset compacto exportado en: {OUTPUT_PATH}")
print(f"✅ Diccionario exportado en: {DICTIONARY_PATH}")
print(f"   Dimensiones: {analytical_df_compact.shape}")

✅ Dataset compacto exportado en: /Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/04_Simulador/ProjecteData/Equip_32/Data/2026-07-20_ECF_2021_02_MasterDataset.csv
✅ Diccionario exportado en: /Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/04_Simulador/ProjecteData/Equip_32/Data/2026-07-20_ECF_2021_02_MasterDataset_Diccionario.csv
   Dimensiones: (7764, 65)