
# ECF 2021 — Análisis de comportamiento financiero

**Notebook:** `2026-07-20_ECF_2021_02_Comportamiento_Analysis.ipynb`

## Objetivo general

Descubrir hallazgos sobre el comportamiento financiero de la población española que puedan:

1. aportar contexto nacional al análisis interno de **Banco Atlas**;
2. revelar patrones de ahorro, uso de canales, tenencia de productos, planificación y fragilidad;
3. identificar segmentos con necesidades financieras diferenciadas;
4. apoyar propuestas de adaptación o creación de productos, servicios y comunicaciones.

## Enfoque de trabajo

Este notebook comienza por la **Fase 1: preguntas, trazabilidad y exploración analítica sin visualizaciones**.

Antes de diseñar gráficos se hará lo siguiente:

- validar el nuevo master dataset amplio;
- conservar la equivalencia entre referencia de variable y pregunta original de la ECF;
- clasificar variables por temas de comportamiento financiero;
- formular preguntas de análisis conectadas con Banco Atlas;
- generar tablas de diagnóstico;
- localizar relaciones y segmentos candidatos;
- priorizar hallazgos para la fase de storytelling y visualización.

> Las asociaciones encontradas en la ECF son descriptivas. No deben interpretarse automáticamente como relaciones causales.

## 0. Librerías y configuración

In [20]:

from pathlib import Path
from itertools import combinations
import re
import warnings

import numpy as np
import pandas as pd

from IPython.display import display, Markdown

pd.set_option("display.max_columns", 150)
pd.set_option("display.max_rows", 150)
pd.set_option("display.max_colwidth", 180)

warnings.filterwarnings("ignore", category=FutureWarning)

## 1. Rutas del proyecto

In [21]:

# Estructura esperada:
#
# ProjecteData/
# ├── Data/
# │   ├── 2026-07-20_ECF_2021_01_raw.dta
# │   ├── 2026-07-20_ECF_2021_02_MasterDataset.csv
# │   └── 2026-07-20_ECF_2021_02_MasterDataset_Diccionario.csv
# └── Scripts/
#     └── 2026-07-20_ECF_2021_02_Comportamiento_Analysis.ipynb

SCRIPTS_DIR = Path.cwd().resolve()
DATA_DIR = (SCRIPTS_DIR / "../Data").resolve()

MASTER_PATH = DATA_DIR / "2026-07-20_ECF_2021_02_MasterDataset.csv"
RAW_PATH = DATA_DIR / "2026-07-20_ECF_2021_01_raw.dta"
INDICATOR_DICTIONARY_PATH = (
    DATA_DIR / "2026-07-20_ECF_2021_02_MasterDataset_Diccionario.csv"
)

required_paths = {
    "Master dataset": MASTER_PATH,
    "Fichero raw Stata": RAW_PATH,
}

missing_paths = {
    name: path
    for name, path in required_paths.items()
    if not path.exists()
}

if missing_paths:
    print("Archivos no encontrados:")
    for name, path in missing_paths.items():
        print(f"  - {name}: {path}")
    raise FileNotFoundError(
        "Ejecuta el notebook desde ../Scripts/ y comprueba que "
        "los datos estén disponibles en ../Data/."
    )

print(f"Scripts: {SCRIPTS_DIR}")
print(f"Data:    {DATA_DIR}")
print(f"Master:  {MASTER_PATH.name}")

Scripts: /Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/04_Simulador/ProjecteData/Equip_32/Scripts
Data:    /Users/rogerdefez/Documents/Cursos i Llibres/BootCamp IT Academy/04_Simulador/ProjecteData/Equip_32/Data
Master:  2026-07-20_ECF_2021_02_MasterDataset.csv

## 2. Carga del master y metadatos originales de la ECF

In [22]:

df = pd.read_csv(MASTER_PATH, low_memory=False)

stata_reader = pd.io.stata.StataReader(RAW_PATH)
raw_variable_labels = stata_reader.variable_labels()
raw_value_label_names = list(stata_reader._lbllist)
raw_value_label_sets = stata_reader.value_labels()
raw_columns = list(raw_variable_labels)

indicator_dictionary = pd.DataFrame(
    columns=["Variable", "Definición"]
)

if INDICATOR_DICTIONARY_PATH.exists():
    indicator_dictionary = pd.read_csv(
        INDICATOR_DICTIONARY_PATH
    )
    indicator_dictionary.columns = [
        str(column).strip()
        for column in indicator_dictionary.columns
    ]

print(f"Observaciones: {df.shape[0]:,}")
print(f"Variables:     {df.shape[1]:,}")
print(f"Duplicados de fila: {df.duplicated().sum():,}")
print(
    "Columnas duplicadas:",
    int(df.columns.duplicated().sum()),
)

if df.shape[1] < 100:
    print(
        "\n⚠️ AVISO: el master contiene menos de 100 variables. "
        "Comprueba que has ejecutado la versión amplia del notebook "
        "de creación del master y que ha sustituido el CSV anterior."
    )

Observaciones: 7,764
Variables:     255
Duplicados de fila: 0
Columnas duplicadas: 0


## 3. Trazabilidad: variable ↔ pregunta ECF

Se construye un catálogo de variables para que cada tabla posterior pueda mostrar:

- referencia técnica;
- pregunta original o resumida;
- bloque de la ECF;
- tipo de variable;
- condición de variable original, pregunta multirrespuesta agrupada o indicador derivado.

Para las preguntas padre multirrespuesta creadas en el master, la descripción se reconstruye a partir de las etiquetas de sus variables hijas originales.

In [23]:

def ecf_block(variable):
    first = str(variable).lower()[:1]

    block_names = {
        "a": "A — Características sociodemográficas",
        "b": "B — Productos, canales y ahorro",
        "c": "C — Fuentes de ingresos",
        "d": "D — Actitudes y comportamiento financiero",
        "e": "E — Competencias financieras",
        "f": "F — Decisiones financieras del hogar",
        "i": "I — Vivienda",
        "j": "J — Gasto, crédito y fragilidad financiera",
    }

    return block_names.get(
        first,
        "Indicadores o variables auxiliares",
    )


def clean_question_label(label):
    if pd.isna(label):
        return ""

    label = re.sub(r"\s+", " ", str(label)).strip()
    return label


def shorten_question(label, max_length=145):
    label = clean_question_label(label)

    if len(label) <= max_length:
        return label

    return label[: max_length - 1].rstrip() + "…"


def parent_children(parent_variable):
    match = re.fullmatch(
        r"([a-z]\d{4})x",
        str(parent_variable).lower(),
    )

    if not match:
        return []

    prefix = match.group(1)

    return [
        variable
        for variable in raw_columns
        if re.fullmatch(
            rf"{re.escape(prefix)}[a-z]",
            str(variable).lower(),
        )
    ]


def infer_parent_question(parent_variable):
    children = parent_children(parent_variable)

    if not children:
        return ""

    labels = [
        clean_question_label(
            raw_variable_labels.get(child, "")
        )
        for child in children
    ]
    labels = [label for label in labels if label]

    if not labels:
        return ""

    # En muchas multirrespuestas la parte inicial es común.
    common_prefix = labels[0]

    for label in labels[1:]:
        while (
            common_prefix
            and not label.startswith(common_prefix)
        ):
            common_prefix = common_prefix[:-1]

    common_prefix = common_prefix.rstrip(
        " :-;,.0123456789"
    )

    if len(common_prefix) >= 25:
        return common_prefix

    # Si no hay prefijo suficientemente claro,
    # se identifica como pregunta agrupada.
    return (
        f"Pregunta multirrespuesta agrupada a partir de: "
        f"{', '.join(children)}"
    )


indicator_descriptions = {}

if {
    "Variable",
    "Definición",
}.issubset(indicator_dictionary.columns):
    indicator_descriptions = dict(
        zip(
            indicator_dictionary["Variable"].astype(str),
            indicator_dictionary["Definición"].astype(str),
        )
    )


def variable_metadata(variable):
    variable = str(variable)

    if variable in raw_variable_labels:
        variable_type = "Original"
        full_question = clean_question_label(
            raw_variable_labels.get(variable, "")
        )
        source = variable

    elif re.fullmatch(r"[a-z]\d{4}x", variable.lower()):
        variable_type = "Multirrespuesta agrupada"
        full_question = infer_parent_question(variable)
        source = ", ".join(parent_children(variable))

    else:
        variable_type = "Indicador derivado"
        full_question = clean_question_label(
            indicator_descriptions.get(variable, "")
        )
        source = "Variables fuente documentadas en el master"

    return {
        "variable": variable,
        "bloque": ecf_block(variable),
        "tipo_variable": variable_type,
        "pregunta_ecf_resumida": shorten_question(
            full_question
        ),
        "pregunta_ecf_completa": full_question,
        "variables_fuente": source,
        "dtype": str(df[variable].dtype),
        "n_no_nulos": int(df[variable].notna().sum()),
        "pct_nulos": round(
            df[variable].isna().mean() * 100,
            2,
        ),
        "n_unicos": int(df[variable].nunique(dropna=True)),
    }


variable_catalog = pd.DataFrame(
    variable_metadata(variable)
    for variable in df.columns
)

display(variable_catalog.head(20))

,variable,bloque,tipo_variable,pregunta_ecf_resumida,pregunta_ecf_completa,variables_fuente,dtype,n_no_nulos,pct_nulos,n_unicos
0,ccaaf,C — Fuentes de ingresos,Original,ccaaf: codigos de comunidad autonoma de residencia,ccaaf: codigos de comunidad autonoma de residencia,ccaaf,str,7764,0.0,17
1,a0000,A — Características sociodemográficas,Original,"a0000: es requisito que pregunte su genero, es vd. hombre o mujer?","a0000: es requisito que pregunte su genero, es vd. hombre o mujer?",a0000,str,7764,0.0,2
2,a04,A — Características sociodemográficas,Original,a04: edad calculada,a04: edad calculada,a04,str,7764,0.0,64
3,a0100,A — Características sociodemográficas,Original,a0100: en que pais nacio?,a0100: en que pais nacio?,a0100,str,7764,0.0,2
4,a0320,A — Características sociodemográficas,Original,a0320: nacio alguno de sus padres fuera de espania?,a0320: nacio alguno de sus padres fuera de espania?,a0320,str,7764,0.0,3
5,a0910,A — Características sociodemográficas,Original,a0910: con cuantas personas vive habitualmente (incluyendose a si mismo)?,a0910: con cuantas personas vive habitualmente (incluyendose a si mismo)?,a0910,int64,7764,0.0,10
6,a1030,A — Características sociodemográficas,Original,a1030: cual es su estado civil actual?,a1030: cual es su estado civil actual?,a1030,str,7764,0.0,7
7,a1100,A — Características sociodemográficas,Original,a1100: cual es el mayor nivel de formacion que ha alcanzado?,a1100: cual es el mayor nivel de formacion que ha alcanzado?,a1100,str,7764,0.0,9
8,a1400,A — Características sociodemográficas,Original,"a1400: cuantos libros habia, donde vivia cuando tenia 10 anios?","a1400: cuantos libros habia, donde vivia cuando tenia 10 anios?",a1400,str,7764,0.0,7
9,a1410,A — Características sociodemográficas,Original,a1410: le explicaron sus padres como encargarse de asuntos financieros?,a1410: le explicaron sus padres como encargarse de asuntos financieros?,a1410,str,7764,0.0,3
10,a1500,A — Características sociodemográficas,Original,a1500: cual es su situacion laboral actual?,a1500: cual es su situacion laboral actual?,a1500,str,7764,0.0,9
11,a1510,A — Características sociodemográficas,Original,"a1510. si tiene más de una situacion laboral, cual es la secundaria?","a1510. si tiene más de una situacion laboral, cual es la secundaria?",a1510,str,7764,0.0,12
12,a1520,A — Características sociodemográficas,Original,a1520: trabaja a tiempo completo o parcial?,a1520: trabaja a tiempo completo o parcial?,a1520,str,7764,0.0,6
13,a1530,A — Características sociodemográficas,Original,a1530: tiene empleados a su cargo?,a1530: tiene empleados a su cargo?,a1530,str,7764,0.0,4
14,a1700,A — Características sociodemográficas,Original,a1700: ha trabajado alguna vez...?,a1700: ha trabajado alguna vez...?,a1700,str,7764,0.0,4
15,a1710,A — Características sociodemográficas,Original,a1710. cuantos años ha trabajado en total?,a1710. cuantos años ha trabajado en total?,a1710,str,7764,0.0,70
16,a1800,A — Características sociodemográficas,Original,a1800: profesion o trabajo (2 digitos cno-11),a1800: profesion o trabajo (2 digitos cno-11),a1800,str,7764,0.0,65
17,a1900,A — Características sociodemográficas,Original,a1900: su trabajo se relaciona/relacionaba con temas financieros?,a1900: su trabajo se relaciona/relacionaba con temas financieros?,a1900,str,7764,0.0,5
18,b0100,"B — Productos, canales y ahorro",Original,"b0100: poseen cuentas corrientes, libretas u otros depositos...?","b0100: poseen cuentas corrientes, libretas u otros depositos...?",b0100,str,7764,0.0,5
19,b0208,"B — Productos, canales y ahorro",Original,b0208: ha oido hablar de las cuentas o depositos de ahorro o a plazo...?,b0208: ha oido hablar de las cuentas o depositos de ahorro o a plazo...?,b0208,str,7764,0.0,3

### Buscador de variables por concepto

In [24]:

def search_variables(*terms, max_results=50):
    """Busca términos en nombre, pregunta, descripción y bloque."""

    if not terms:
        return variable_catalog.copy()

    mask = pd.Series(
        True,
        index=variable_catalog.index,
    )

    searchable = (
        variable_catalog[
            [
                "variable",
                "bloque",
                "pregunta_ecf_resumida",
                "pregunta_ecf_completa",
            ]
        ]
        .fillna("")
        .astype(str)
        .agg(" ".join, axis=1)
        .str.lower()
    )

    for term in terms:
        mask &= searchable.str.contains(
            str(term).lower(),
            regex=False,
        )

    return variable_catalog.loc[mask].head(max_results)


# Ejemplos:
display(search_variables("ahorro"))
display(search_variables("crédito"))
display(search_variables("banca"))

,variable,bloque,tipo_variable,pregunta_ecf_resumida,pregunta_ecf_completa,variables_fuente,dtype,n_no_nulos,pct_nulos,n_unicos
18,b0100,"B — Productos, canales y ahorro",Original,"b0100: poseen cuentas corrientes, libretas u otros depositos...?","b0100: poseen cuentas corrientes, libretas u otros depositos...?",b0100,str,7764,0.00,5
19,b0208,"B — Productos, canales y ahorro",Original,b0208: ha oido hablar de las cuentas o depositos de ahorro o a plazo...?,b0208: ha oido hablar de las cuentas o depositos de ahorro o a plazo...?,b0208,str,7764,0.00,3
20,b0308,"B — Productos, canales y ahorro",Original,"b0308: en la actualidad tiene, personal o conjuntamente, alguna cuenta...?","b0308: en la actualidad tiene, personal o conjuntamente, alguna cuenta...?",b0308,str,7764,0.00,5
21,b0408,"B — Productos, canales y ahorro",Original,"b0408: en los ultimos 2 anios ha contratado,(...) cuenta o deposito de ahorro...","b0408: en los ultimos 2 anios ha contratado,(...) cuenta o deposito de ahorro...",b0408,str,7764,0.00,5
22,b0201,"B — Productos, canales y ahorro",Original,b0201: ha oido hablar de las hipotecas?,b0201: ha oido hablar de las hipotecas?,b0201,str,7764,0.00,2
23,b0301,"B — Productos, canales y ahorro",Original,"b0301: en la actualidad tiene, personal o conjuntamente, alguna hipoteca?","b0301: en la actualidad tiene, personal o conjuntamente, alguna hipoteca?",b0301,str,7764,0.00,6
24,b0401,"B — Productos, canales y ahorro",Original,"b0401: en los ultimos 2 anios ha contratado,(...) alguna hipoteca...?","b0401: en los ultimos 2 anios ha contratado,(...) alguna hipoteca...?",b0401,str,7764,0.00,6
25,b0202,"B — Productos, canales y ahorro",Original,b0202: ha oido hablar de los planes de pensiones individuales o de empresa?,b0202: ha oido hablar de los planes de pensiones individuales o de empresa?,b0202,str,7764,0.00,3
26,b0302,"B — Productos, canales y ahorro",Original,b0302: en la actualidad tiene algun plan de pensiones individual o de empresa?,b0302: en la actualidad tiene algun plan de pensiones individual o de empresa?,b0302,str,7764,0.00,5
27,b0402,"B — Productos, canales y ahorro",Original,"b0402: en los ultimos 2 anios ha contratado,(...) plan de pensiones...?","b0402: en los ultimos 2 anios ha contratado,(...) plan de pensiones...?",b0402,str,7764,0.00,6
28,b0203,"B — Productos, canales y ahorro",Original,b0203: ha oido hablar de los fondos de inversion?,b0203: ha oido hablar de los fondos de inversion?,b0203,str,7764,0.00,3
29,b0303,"B — Productos, canales y ahorro",Original,"b0303: en la actualidad tiene, personal o conjuntamente, fondo de inversion?","b0303: en la actualidad tiene, personal o conjuntamente, fondo de inversion?",b0303,str,7764,0.00,6
30,b0403,"B — Productos, canales y ahorro",Original,"b0403: en los ultimos 2 anios ha contratado,(...)algun fondo de inversion...?","b0403: en los ultimos 2 anios ha contratado,(...)algun fondo de inversion...?",b0403,str,7764,0.00,5
31,b0204,"B — Productos, canales y ahorro",Original,b0204: ha oido hablar de las acciones?,b0204: ha oido hablar de las acciones?,b0204,str,7764,0.00,2
32,b0304,"B — Productos, canales y ahorro",Original,"b0304: en la actualidad tiene, personal o conjuntamente, acciones de empresas?","b0304: en la actualidad tiene, personal o conjuntamente, acciones de empresas?",b0304,str,7764,0.00,5
33,b0404,"B — Productos, canales y ahorro",Original,"b0404: en los ultimos 2 anios ha adquirido,(...)acciones de alguna empresa...?","b0404: en los ultimos 2 anios ha adquirido,(...)acciones de alguna empresa...?",b0404,str,7764,0.00,5
34,b0205,"B — Productos, canales y ahorro",Original,b0205: ha oido hablar de los activos de renta fija publica/privada...?,b0205: ha oido hablar de los activos de renta fija publica/privada...?,b0205,str,7764,0.00,3
35,b0305,"B — Productos, canales y ahorro",Original,"b0305: en la actualidad tiene, (...) algun activo de renta fija publica/privada?","b0305: en la actualidad tiene, (...) algun activo de renta fija publica/privada?",b0305,str,7764,0.00,6
36,b0405,"B — Productos, canales y ahorro",Original,"b0405: en los ultimos 2 anios ha adquirido,(...) algun activo de renta fija...?","b0405: en los ultimos 2 anios ha adquirido,(...) algun activo de renta fija...?",b0405,str,7764,0.00,5
37,b0206,"B — Productos, canales y ahorro",Original,b0206: ha oido hablar de los prestamos personales?,b0206: ha oido hablar de los prestamos personales?,b0206,str,7764,0.00,3
38,b0306,"B — Productos, canales y ahorro",Original,"b0306: en la actualidad tiene, personal o conjuntamente, prestamo personal?","b0306: en la actualidad tiene, personal o conjuntamente, prestamo personal?",b0306,str,7764,0.00,6
39,b0406,"B — Productos, canales y ahorro",Original,"b0406: en los ultimos 2 anios ha adquirido,(...) algun prestamo personal...?","b0406: en los ultimos 2 anios ha adquirido,(...) algun prestamo personal...?",b0406,str,7764,0.00,6
40,b0207,"B — Productos, canales y ahorro",Original,b0207: ha oido hablar de las tarjetas de credito?,b0207: ha oido hablar de las tarjetas de credito?,b0207,str,7764,0.00,3
41,b0307,"B — Productos, canales y ahorro",Original,"b0307: en la actualidad tiene, personal o conjuntamente, tarjeta de credito?","b0307: en la actualidad tiene, personal o conjuntamente, tarjeta de credito?",b0307,str,7764,0.00,4
42,b0407,"B — Productos, canales y ahorro",Original,"b0407: en los ultimos 2 anios ha adquirido,(...) alguna tarjeta de credito...?","b0407: en los ultimos 2 anios ha adquirido,(...) alguna tarjeta de credito...?",b0407,str,7764,0.00,5
43,b0209,"B — Productos, canales y ahorro",Original,b0209: ha oido hablar de los seguros de vida?,b0209: ha oido hablar de los seguros de vida?,b0209,str,7764,0.00,2
44,b0309,"B — Productos, canales y ahorro",Original,b0309: en la actualidad tiene suscrito algun seguro de vida?,b0309: en la actualidad tiene suscrito algun seguro de vida?,b0309,str,7764,0.00,5
45,b0409,"B — Productos, canales y ahorro",Original,"b0409: en los ultimos 2 anios ha adquirido,(...) algun seguro de vida...?","b0409: en los ultimos 2 anios ha adquirido,(...) algun seguro de vida...?",b0409,str,7764,0.00,5
46,b0210,"B — Productos, canales y ahorro",Original,b0210: ha oido hablar de los seguros medicos?,b0210: ha oido hablar de los seguros medicos?,b0210,str,7764,0.00,2
47,b0310,"B — Productos, canales y ahorro",Original,"b0310: en la actualidad tiene suscrito, personal o conjuntamente,seguro medico?","b0310: en la actualidad tiene suscrito, personal o conjuntamente,seguro medico?",b0310,str,7764,0.00,4
48,b0410,"B — Productos, canales y ahorro",Original,"b0410: en los ultimos 2 anios ha adquirido,(...) algun seguro medico...?","b0410: en los ultimos 2 anios ha adquirido,(...) algun seguro medico...?",b0410,str,7764,0.00,5
49,b0212,"B — Productos, canales y ahorro",Original,b0212: ha oido hablar de las criptomonedas?,b0212: ha oido hablar de las criptomonedas?,b0212,str,7764,0.00,2
50,b0312,"B — Productos, canales y ahorro",Original,"b0312: en la actualidad tiene suscrito, personal o conjuntamente, algunas cripto","b0312: en la actualidad tiene suscrito, personal o conjuntamente, algunas cripto",b0312,str,7764,0.00,6
51,b0412,"B — Productos, canales y ahorro",Original,"b0412: en los ultimos 2 anios ha adquirido,(...) alguna criptomoneda...?","b0412: en los ultimos 2 anios ha adquirido,(...) alguna criptomoneda...?",b0412,str,7764,0.00,5
52,b0502,"B — Productos, canales y ahorro",Original,b0502: cual fue el ultimo producto o servicio contratado por decision propia?,b0502: cual fue el ultimo producto o servicio contratado por decision propia?,b0502,str,7764,0.00,16
53,b0503,"B — Productos, canales y ahorro",Original,b0503: se trato de una decision individual o conjunta?,b0503: se trato de una decision individual o conjunta?,b0503,str,7764,0.00,5
54,b0600,"B — Productos, canales y ahorro",Original,b0600: cual de las afirmaciones siguientes describe mejor como eligio...?,b0600: cual de las afirmaciones siguientes describe mejor como eligio...?,b0600,str,7764,0.00,8
55,b1103,"B — Productos, canales y ahorro",Original,b1103: en los ultimos 2 anios ha utilizado algun desconocido el numero de su cue,b1103: en los ultimos 2 anios ha utilizado algun desconocido el numero de su cue,b1103,str,7764,0.00,4
56,b1201,"B — Productos, canales y ahorro",Original,"b1201: en los ultimos 5 anios, ha tenido alguna desavenencia por productos...?","b1201: en los ultimos 5 anios, ha tenido alguna desavenencia por productos...?",b1201,str,7764,0.00,4
83,d0610c,D — Actitudes y comportamiento financiero,Original,d0610c: como utilizaria ese ingreso extra en los proximos 12 meses?: c. ahorro,d0610c: como utilizaria ese ingreso extra en los proximos 12 meses?: c. ahorro,d0610c,float64,7689,0.97,13
90,e0800,E — Competencias financieras,Original,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0800,str,7764,0.00,118
140,k1908,Indicadores o variables auxiliares,Original,k1908: ha oido hablar de las cuentas o depositos de ahorro o a plazo...?,k1908: ha oido hablar de las cuentas o depositos de ahorro o a plazo...?,k1908,str,7764,0.00,5
155,k0800,Indicadores o variables auxiliares,Original,k0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,k0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,k0800,str,7764,0.00,67
194,b0110x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b0110a, b0110b, b0110c, b0110d, b0110e, b0110f, b0110g","Pregunta multirrespuesta agrupada a partir de: b0110a, b0110b, b0110c, b0110d, b0110e, b0110f, b0110g","b0110a, b0110b, b0110c, b0110d, b0110e, b0110f, b0110g",str,7764,0.00,41
195,b0120x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b0120a, b0120b, b0120c, b0120d, b0120e, b0120f","Pregunta multirrespuesta agrupada a partir de: b0120a, b0120b, b0120c, b0120d, b0120e, b0120f","b0120a, b0120b, b0120c, b0120d, b0120e, b0120f",str,7764,0.00,38
196,b0130x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b0130a, b0130b, b0130c","Pregunta multirrespuesta agrupada a partir de: b0130a, b0130b, b0130c","b0130a, b0130b, b0130c",str,7764,0.00,6
197,b1100x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b1100a, b1100b, b1100c, b1100d, b1100e, b1100f, b1100g, b1100i, b1100h","Pregunta multirrespuesta agrupada a partir de: b1100a, b1100b, b1100c, b1100d, b1100e, b1100f, b1100g, b1100i, b1100h","b1100a, b1100b, b1100c, b1100d, b1100e, b1100f, b1100g, b1100i, b1100h",str,7764,0.00,117
198,b0720x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b0720a, b0720b, b0720c, b0720d, b0720e, b0720f, b0720g, b0720h, b0720i","Pregunta multirrespuesta agrupada a partir de: b0720a, b0720b, b0720c, b0720d, b0720e, b0720f, b0720g, b0720h, b0720i","b0720a, b0720b, b0720c, b0720d, b0720e, b0720f, b0720g, b0720h, b0720i",str,7764,0.00,116
199,b0710x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b0710a, b0710b, b0710c, b0710d, b0710e, b0710f, b0710g, b0710h, b0710i","Pregunta multirrespuesta agrupada a partir de: b0710a, b0710b, b0710c, b0710d, b0710e, b0710f, b0710g, b0710h, b0710i","b0710a, b0710b, b0710c, b0710d, b0710e, b0710f, b0710g, b0710h, b0710i",str,7764,0.00,55
200,b1000x,"B — Productos, canales y ahorro",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: b1000a, b1000b, b1000c, b1000d, b1000e, b1000f, b1000g, b1000h, b1000i, b1000j","Pregunta multirrespuesta agrupada a partir de: b1000a, b1000b, b1000c, b1000d, b1000e, b1000f, b1000g, b1000h, b1000i, b1000j","b1000a, b1000b, b1000c, b1000d, b1000e, b1000f, b1000g, b1000h, b1000i, b1000j",str,7764,0.00,134

,variable,bloque,tipo_variable,pregunta_ecf_resumida,pregunta_ecf_completa,variables_fuente,dtype,n_no_nulos,pct_nulos,n_unicos
123,j0100,"J — Gasto, crédito y fragilidad financiera",Original,j0100: hace su hogar una planificacion de sus gastos?,j0100: hace su hogar una planificacion de sus gastos?,j0100,str,7764,0.0,5
124,j0110,"J — Gasto, crédito y fragilidad financiera",Original,j0110: usan alguna app bancaria o herramienta de administracion…,j0110: usan alguna app bancaria o herramienta de administracion…,j0110,str,7764,0.0,5
125,j0200,"J — Gasto, crédito y fragilidad financiera",Original,"j0200: en los ultimos 12 meses, han sido sus gastos mayores que sus ingresos?","j0200: en los ultimos 12 meses, han sido sus gastos mayores que sus ingresos?",j0200,str,7764,0.0,5
126,j0400,"J — Gasto, crédito y fragilidad financiera",Original,j0400: durante cuanto tiempo podria(n) hacer frente a sus gastos corrientes...?,j0400: durante cuanto tiempo podria(n) hacer frente a sus gastos corrientes...?,j0400,str,7764,0.0,10
127,j0500,"J — Gasto, crédito y fragilidad financiera",Original,"j0500: cuanto gastan en promedio en comida, dentro y fuera de casa?","j0500: cuanto gastan en promedio en comida, dentro y fuera de casa?",j0500,str,7764,0.0,110
128,j0600,"J — Gasto, crédito y fragilidad financiera",Original,"j0600: este gasto en comida del que me acaba de hablar, hace referencia a:","j0600: este gasto en comida del que me acaba de hablar, hace referencia a:",j0600,str,7764,0.0,3
129,j0700,"J — Gasto, crédito y fragilidad financiera",Original,j0700: cuanto gasto su hogar en educacion durante el ultimo anio?,j0700: cuanto gasto su hogar en educacion durante el ultimo anio?,j0700,str,7764,0.0,213
130,j0810,"J — Gasto, crédito y fragilidad financiera",Original,j0810: alguna de estas personas no forman parte de su hogar?,j0810: alguna de estas personas no forman parte de su hogar?,j0810,str,7764,0.0,4
131,j0920,"J — Gasto, crédito y fragilidad financiera",Original,j0920: considero pedir algun tipo de estos prestamos en los ultimos dos anios?,j0920: considero pedir algun tipo de estos prestamos en los ultimos dos anios?,j0920,str,7764,0.0,7
132,j1000,"J — Gasto, crédito y fragilidad financiera",Original,"j1000: en los ultimos 12 meses, han retrasado el pago de alguna de sus deudas...","j1000: en los ultimos 12 meses, han retrasado el pago de alguna de sus deudas...",j1000,str,7764,0.0,5
133,j1100,"J — Gasto, crédito y fragilidad financiera",Original,"j1100: estas deudas, son deudas contraidas con una entidad financiera o bancaria","j1100: estas deudas, son deudas contraidas con una entidad financiera o bancaria",j1100,str,7764,0.0,4
134,j1201,"J — Gasto, crédito y fragilidad financiera",Original,"j1201: ultimos 12 meses,algun miembro de su hogar ha perdido su empleo?","j1201: ultimos 12 meses,algun miembro de su hogar ha perdido su empleo?",j1201,str,7764,0.0,5
135,j1202,"J — Gasto, crédito y fragilidad financiera",Original,"j1202: ultimos 12 meses,algun miembro de su hogar en paro ha encontrado empleo?","j1202: ultimos 12 meses,algun miembro de su hogar en paro ha encontrado empleo?",j1202,str,7764,0.0,5
136,j1203,"J — Gasto, crédito y fragilidad financiera",Original,"j1203: ultimos 12 meses,algun miembro de su hogar ha tenido un accidente...?","j1203: ultimos 12 meses,algun miembro de su hogar ha tenido un accidente...?",j1203,str,7764,0.0,5
137,j1300,"J — Gasto, crédito y fragilidad financiera",Original,j1300: cuales son los ingresos brutos anuales totales del hogar?,j1300: cuales son los ingresos brutos anuales totales del hogar?,j1300,str,7764,0.0,9
138,j1400,"J — Gasto, crédito y fragilidad financiera",Original,j1400: hubiera estado dispuesto a realizar la entrevista presencialmente?,j1400: hubiera estado dispuesto a realizar la entrevista presencialmente?,j1400,int64,7764,0.0,2
139,j1600,"J — Gasto, crédito y fragilidad financiera",Original,"j1600: en cuanto al cuaderno de cartones…, lo ha consultado…?","j1600: en cuanto al cuaderno de cartones…, lo ha consultado…?",j1600,str,7764,0.0,4
215,j0300x,"J — Gasto, crédito y fragilidad financiera",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: j0300a, j0300b, j0300c, j0300d, j0300e, j0300f, j0300g, j0300h, j0300i, j0300j, j0300k, j0300l, j…","Pregunta multirrespuesta agrupada a partir de: j0300a, j0300b, j0300c, j0300d, j0300e, j0300f, j0300g, j0300h, j0300i, j0300j, j0300k, j0300l, j0300m, j0300n, j0300p, j0300o","j0300a, j0300b, j0300c, j0300d, j0300e, j0300f, j0300g, j0300h, j0300i, j0300j, j0300k, j0300l, j0300m, j0300n, j0300p, j0300o",str,7764,0.0,167
216,j0800x,"J — Gasto, crédito y fragilidad financiera",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: j0800a, j0800b, j0800c, j0800d, j0800e, j0800f, j0800h, j0800g","Pregunta multirrespuesta agrupada a partir de: j0800a, j0800b, j0800c, j0800d, j0800e, j0800f, j0800h, j0800g","j0800a, j0800b, j0800c, j0800d, j0800e, j0800f, j0800h, j0800g",str,7764,0.0,45
217,j0900x,"J — Gasto, crédito y fragilidad financiera",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: j0900a, j0900b, j0900c, j0900d","Pregunta multirrespuesta agrupada a partir de: j0900a, j0900b, j0900c, j0900d","j0900a, j0900b, j0900c, j0900d",str,7764,0.0,12
218,j0910x,"J — Gasto, crédito y fragilidad financiera",Multirrespuesta agrupada,"Pregunta multirrespuesta agrupada a partir de: j0910a, j0910b, j0910c, j0910d, j0910e, j0910f","Pregunta multirrespuesta agrupada a partir de: j0910a, j0910b, j0910c, j0910d, j0910e, j0910f","j0910a, j0910b, j0910c, j0910d, j0910e, j0910f",str,7764,0.0,23
226,tiene_exposicion_credito,Indicadores o variables auxiliares,Indicador derivado,"Tenencia de hipoteca, préstamo personal o tarjeta de crédito.","Tenencia de hipoteca, préstamo personal o tarjeta de crédito.",Variables fuente documentadas en el master,int64,7764,0.0,2
251,financiacion_credito_formal,F — Decisiones financieras del hogar,Indicador derivado,Cubrió el déficit mediante crédito o financiación formal.,Cubrió el déficit mediante crédito o financiación formal.,Variables fuente documentadas en el master,int64,7764,0.0,2

,variable,bloque,tipo_variable,pregunta_ecf_resumida,pregunta_ecf_completa,variables_fuente,dtype,n_no_nulos,pct_nulos,n_unicos
124,j0110,"J — Gasto, crédito y fragilidad financiera",Original,j0110: usan alguna app bancaria o herramienta de administracion…,j0110: usan alguna app bancaria o herramienta de administracion…,j0110,str,7764,0.0,5
133,j1100,"J — Gasto, crédito y fragilidad financiera",Original,"j1100: estas deudas, son deudas contraidas con una entidad financiera o bancaria","j1100: estas deudas, son deudas contraidas con una entidad financiera o bancaria",j1100,str,7764,0.0,4
221,usa_banca_digital,Indicadores o variables auxiliares,Indicador derivado,Uso de ordenador/tablet o app móvil bancaria.,Uso de ordenador/tablet o app móvil bancaria.,Variables fuente documentadas en el master,int64,7764,0.0,2
222,pref_banca_digital,Indicadores o variables auxiliares,Indicador derivado,Preferencia por ordenador/tablet o app móvil bancaria.,Preferencia por ordenador/tablet o app móvil bancaria.,Variables fuente documentadas en el master,int64,7764,0.0,2
223,usa_pago_digital,Indicadores o variables auxiliares,Indicador derivado,Uso de aplicaciones o banca online para realizar pagos.,Uso de aplicaciones o banca online para realizar pagos.,Variables fuente documentadas en el master,int64,7764,0.0,2


## 4. Marco analítico: preguntas antes que gráficos

La investigación se organiza alrededor de seis líneas. Cada línea debe terminar en:

1. un hallazgo verificable;
2. los segmentos afectados;
3. una implicación potencial para Banco Atlas;
4. una visualización posterior que comunique el resultado.

### Preguntas principales

| Línea | Pregunta ECF | Posible conexión con Banco Atlas |
|---|---|---|
| Canales | ¿Qué perfiles utilizan o prefieren la banca digital? | Adopción digital, onboarding, acompañamiento y estrategia omnicanal |
| Productos | ¿Qué segmentos presentan menor tenencia o diversidad de productos? | Venta cruzada, productos de entrada y paquetes adaptados |
| Ahorro | ¿Quién ahorra, por qué vías y con qué grado de formalización? | Cuentas de ahorro, automatización, inversión y educación financiera |
| Planificación | ¿Qué perfiles muestran más disciplina y planificación? | Herramientas de presupuesto, alertas y programas de acompañamiento |
| Fragilidad | ¿Qué grupos tienen más dificultad para afrontar gastos o acceder al crédito? | Prevención, refinanciación responsable y productos de liquidez |
| Vivienda y crédito | ¿Qué barreras de acceso aparecen y en qué segmentos? | Hipoteca, ahorro para entrada, simuladores y asesoramiento |

In [25]:

research_questions = pd.DataFrame([
    {
        "id": "Q1",
        "tema": "Canales",
        "pregunta": (
            "¿Qué segmentos usan banca digital y cuáles mantienen "
            "preferencia por canales presenciales?"
        ),
        "variables_resultado_candidatas": (
            "usa_banca_digital, pref_banca_digital, "
            "n_canales_uso_banco"
        ),
        "segmentaciones": (
            "edad, educación, ingresos, situación laboral, CCAA"
        ),
        "implicación_atlas": (
            "Diseño omnicanal, apoyo a la adopción y comunicaciones "
            "diferenciadas."
        ),
    },
    {
        "id": "Q2",
        "tema": "Tenencia de productos",
        "pregunta": (
            "¿Qué perfiles tienen menor diversidad de productos "
            "financieros y qué productos faltan?"
        ),
        "variables_resultado_candidatas": (
            "n_productos_financieros, tiene_vehiculo_ahorro, "
            "tiene_exposicion_credito, tiene_seguro"
        ),
        "segmentaciones": (
            "edad, ingresos, educación, empleo, hogar"
        ),
        "implicación_atlas": (
            "Productos de entrada, venta cruzada responsable y "
            "paquetes según etapa vital."
        ),
    },
    {
        "id": "Q3",
        "tema": "Ahorro",
        "pregunta": (
            "¿Qué segmentos ahorran menos y cuáles dependen de "
            "mecanismos informales?"
        ),
        "variables_resultado_candidatas": (
            "ahorra_12m, n_vehiculos_ahorro, ahorro_formal, "
            "ahorro_informal"
        ),
        "segmentaciones": (
            "ingresos, edad, empleo, educación, composición del hogar"
        ),
        "implicación_atlas": (
            "Ahorro automático, productos sencillos y transición "
            "desde ahorro informal."
        ),
    },
    {
        "id": "Q4",
        "tema": "Planificación",
        "pregunta": (
            "¿Cómo se relacionan disciplina, planificación y "
            "preocupación financiera con el ahorro?"
        ),
        "variables_resultado_candidatas": (
            "score_disciplina_financiera, "
            "score_planificacion_financiera, "
            "score_preocupacion_financiera"
        ),
        "segmentaciones": (
            "ahorro, ingresos, edad, productos, fragilidad"
        ),
        "implicación_atlas": (
            "Herramientas de presupuesto, nudges y alertas "
            "personalizadas."
        ),
    },
    {
        "id": "Q5",
        "tema": "Fragilidad financiera",
        "pregunta": (
            "¿Qué perfiles presentan mayor fragilidad y qué "
            "mecanismos usan para financiar imprevistos?"
        ),
        "variables_resultado_candidatas": (
            "score_fragilidad_financiera, "
            "financiacion_ahorros_activos, "
            "financiacion_credito_formal, "
            "financiacion_credito_informal, "
            "financiacion_estres_pago"
        ),
        "segmentaciones": (
            "ingresos, empleo, edad, hogar, ahorro, acceso al crédito"
        ),
        "implicación_atlas": (
            "Detección preventiva, colchón de emergencia y soluciones "
            "de liquidez responsable."
        ),
    },
    {
        "id": "Q6",
        "tema": "Vivienda y crédito",
        "pregunta": (
            "¿Qué segmentos afrontan mayores barreras para adquirir "
            "vivienda o acceder al crédito?"
        ),
        "variables_resultado_candidatas": (
            "barrera_acceso_vivienda, "
            "n_dificultades_compra_vivienda, "
            "restriccion_acceso_credito"
        ),
        "segmentaciones": (
            "edad, ingresos, empleo, hogar, CCAA"
        ),
        "implicación_atlas": (
            "Ahorro para entrada, simulación hipotecaria, "
            "asesoramiento y evaluación responsable."
        ),
    },
])

display(research_questions)

,id,tema,pregunta,variables_resultado_candidatas,segmentaciones,implicación_atlas
0,Q1,Canales,¿Qué segmentos usan banca digital y cuáles mantienen preferencia por canales presenciales?,"usa_banca_digital, pref_banca_digital, n_canales_uso_banco","edad, educación, ingresos, situación laboral, CCAA","Diseño omnicanal, apoyo a la adopción y comunicaciones diferenciadas."
1,Q2,Tenencia de productos,¿Qué perfiles tienen menor diversidad de productos financieros y qué productos faltan?,"n_productos_financieros, tiene_vehiculo_ahorro, tiene_exposicion_credito, tiene_seguro","edad, ingresos, educación, empleo, hogar","Productos de entrada, venta cruzada responsable y paquetes según etapa vital."
2,Q3,Ahorro,¿Qué segmentos ahorran menos y cuáles dependen de mecanismos informales?,"ahorra_12m, n_vehiculos_ahorro, ahorro_formal, ahorro_informal","ingresos, edad, empleo, educación, composición del hogar","Ahorro automático, productos sencillos y transición desde ahorro informal."
3,Q4,Planificación,"¿Cómo se relacionan disciplina, planificación y preocupación financiera con el ahorro?","score_disciplina_financiera, score_planificacion_financiera, score_preocupacion_financiera","ahorro, ingresos, edad, productos, fragilidad","Herramientas de presupuesto, nudges y alertas personalizadas."
4,Q5,Fragilidad financiera,¿Qué perfiles presentan mayor fragilidad y qué mecanismos usan para financiar imprevistos?,"score_fragilidad_financiera, financiacion_ahorros_activos, financiacion_credito_formal, financiacion_credito_informal, financiacion_estres_pago","ingresos, empleo, edad, hogar, ahorro, acceso al crédito","Detección preventiva, colchón de emergencia y soluciones de liquidez responsable."
5,Q6,Vivienda y crédito,¿Qué segmentos afrontan mayores barreras para adquirir vivienda o acceder al crédito?,"barrera_acceso_vivienda, n_dificultades_compra_vivienda, restriccion_acceso_credito","edad, ingresos, empleo, hogar, CCAA","Ahorro para entrada, simulación hipotecaria, asesoramiento y evaluación responsable."

## 5. Identificación automática de variables de comportamiento

In [26]:

THEME_PATTERNS = {
    "Canales y digitalización": [
        "canal",
        "banca digital",
        "internet",
        "móvil",
        "oficina",
        "cajero",
        "pago digital",
    ],
    "Productos financieros": [
        "producto",
        "cuenta",
        "tarjeta",
        "seguro",
        "pensión",
        "fondo",
        "acciones",
        "bonos",
        "hipoteca",
        "préstamo",
    ],
    "Ahorro": [
        "ahorra",
        "ahorro",
        "vehículo",
    ],
    "Ingresos": [
        "ingreso",
        "renta",
        "fuente",
    ],
    "Actitudes y planificación": [
        "disciplina",
        "planificación",
        "preocupación",
        "destino",
        "presupuesto",
        "gasto",
    ],
    "Fragilidad y financiación": [
        "fragilidad",
        "financiación",
        "financiacion",
        "dificultad",
        "imprevisto",
        "crédito informal",
        "restricción",
        "restriccion",
    ],
    "Vivienda": [
        "vivienda",
        "precio",
        "alquiler",
        "compra",
    ],
}


def classify_theme(row):
    searchable = " ".join([
        str(row["variable"]),
        str(row["pregunta_ecf_completa"]),
        str(row["bloque"]),
    ]).lower()

    matches = []

    for theme, patterns in THEME_PATTERNS.items():
        if any(pattern in searchable for pattern in patterns):
            matches.append(theme)

    return " | ".join(matches) if matches else "Otros"


variable_catalog["tema_analítico"] = variable_catalog.apply(
    classify_theme,
    axis=1,
)

theme_summary = (
    variable_catalog["tema_analítico"]
    .value_counts()
    .rename_axis("tema")
    .reset_index(name="n_variables")
)

display(theme_summary)

,tema,n_variables
0,Otros,94
1,Canales y digitalización | Productos financieros | Ahorro,51
2,Productos financieros,20
3,Actitudes y planificación | Fragilidad y financiación,19
4,Vivienda,15
5,Ingresos,14
6,Ahorro,5
7,Productos financieros | Ahorro,5
8,Fragilidad y financiación,5
9,Productos financieros | Vivienda,4
10,Canales y digitalización | Productos financieros | Ahorro | Ingresos,3
11,Actitudes y planificación,3
12,Canales y digitalización,3
13,Productos financieros | Ingresos,2
14,Ingresos | Actitudes y planificación | Fragilidad y financiación,2
15,Ingresos | Actitudes y planificación,2
16,Ahorro | Vivienda,1
17,Ahorro | Ingresos,1
18,Ingresos | Vivienda,1
19,Ahorro | Ingresos | Vivienda,1
20,Ahorro | Ingresos | Actitudes y planificación,1
21,Canales y digitalización | Productos financieros | Ahorro | Vivienda,1
22,Fragilidad y financiación | Vivienda,1
23,Ahorro | Fragilidad y financiación,1

## 6. Auditoría inicial del dataset

In [27]:

audit = variable_catalog[
    [
        "variable",
        "bloque",
        "tipo_variable",
        "pregunta_ecf_resumida",
        "dtype",
        "n_no_nulos",
        "pct_nulos",
        "n_unicos",
        "tema_analítico",
    ]
].copy()

audit["posible_identificador"] = (
    (audit["n_unicos"] == len(df))
    & (audit["pct_nulos"] == 0)
)

audit["constante"] = audit["n_unicos"] <= 1
audit["alta_cardinalidad"] = (
    audit["n_unicos"] > max(50, len(df) * 0.20)
)

display(
    audit.sort_values(
        ["pct_nulos", "n_unicos"],
        ascending=[False, True],
    ).head(40)
)

,variable,bloque,tipo_variable,pregunta_ecf_resumida,dtype,n_no_nulos,pct_nulos,n_unicos,tema_analítico,posible_identificador,constante,alta_cardinalidad
119,i0400b,I — Vivienda,Original,i0400b: como evolucionara el valor de la vivienda? b. caida entre 2% y 6%,float64,7494,3.48,11,Vivienda,False,False,False
118,i0400a,I — Vivienda,Original,i0400a: como evolucionara el valor de la vivienda? a. caida mas del 6%,float64,7494,3.48,12,Vivienda,False,False,False
120,i0400c,I — Vivienda,Original,i0400c: como evolucionara el valor de la vivienda? c. estable (<+-2%),float64,7494,3.48,12,Vivienda,False,False,False
121,i0400d,I — Vivienda,Original,i0400d: como evolucionara el valor de la vivienda? d. subida entre 2% y 6%,float64,7494,3.48,12,Vivienda,False,False,False
122,i0400e,I — Vivienda,Original,i0400e: como evolucionara el valor de la vivienda? e. subida mas del 6%,float64,7494,3.48,12,Vivienda,False,False,False
247,expectativa_subida_precio_vivienda,E — Competencias financieras,Indicador derivado,Puntos asignados a escenarios de subida del precio.,float64,7494,3.48,12,Vivienda,False,False,False
85,d0610e,D — Actitudes y comportamiento financiero,Original,d0610e: como utilizaria ese ingreso extra en los proximos 12 meses?: e. otros,float64,7689,0.97,12,Ingresos,False,False,False
81,d0610a,D — Actitudes y comportamiento financiero,Original,d0610a: como utilizaria ese ingreso extra en los proximos 12 meses?: a. producto,float64,7689,0.97,13,Productos financieros | Ingresos,False,False,False
82,d0610b,D — Actitudes y comportamiento financiero,Original,d0610b: como utilizaria ese ingreso extra en los proximos 12 meses?: b. producto,float64,7689,0.97,13,Productos financieros | Ingresos,False,False,False
83,d0610c,D — Actitudes y comportamiento financiero,Original,d0610c: como utilizaria ese ingreso extra en los proximos 12 meses?: c. ahorro,float64,7689,0.97,13,Ahorro | Ingresos,False,False,False
84,d0610d,D — Actitudes y comportamiento financiero,Original,d0610d: como utilizaria ese ingreso extra en los proximos 12 meses?: d. pagar de,float64,7689,0.97,13,Ingresos,False,False,False
238,puntos_destino_consumo,Indicadores o variables auxiliares,Indicador derivado,Puntos del ingreso extra destinados a consumo.,float64,7689,0.97,13,Ingresos | Actitudes y planificación,False,False,False
239,puntos_destino_ahorro,Indicadores o variables auxiliares,Indicador derivado,Puntos del ingreso extra destinados a ahorro.,float64,7689,0.97,13,Ahorro | Ingresos | Actitudes y planificación,False,False,False
240,puntos_destino_deuda,Indicadores o variables auxiliares,Indicador derivado,Puntos del ingreso extra destinados a pagar deuda.,float64,7689,0.97,13,Ingresos | Actitudes y planificación,False,False,False
235,score_disciplina_financiera,Indicadores o variables auxiliares,Indicador derivado,"Media 1–5 de control, pago puntual, vigilancia e información.",float64,7763,0.01,25,Actitudes y planificación,False,False,False
237,score_planificacion_financiera,Indicadores o variables auxiliares,Indicador derivado,Media 1–5 orientada al futuro; ítems negativos invertidos.,float64,7763,0.01,34,Otros,False,False,False
1,a0000,A — Características sociodemográficas,Original,"a0000: es requisito que pregunte su genero, es vd. hombre o mujer?",str,7764,0.00,2,Otros,False,False,False
3,a0100,A — Características sociodemográficas,Original,a0100: en que pais nacio?,str,7764,0.00,2,Otros,False,False,False
22,b0201,"B — Productos, canales y ahorro",Original,b0201: ha oido hablar de las hipotecas?,str,7764,0.00,2,Canales y digitalización | Productos financieros | Ahorro,False,False,False
31,b0204,"B — Productos, canales y ahorro",Original,b0204: ha oido hablar de las acciones?,str,7764,0.00,2,Canales y digitalización | Productos financieros | Ahorro,False,False,False
43,b0209,"B — Productos, canales y ahorro",Original,b0209: ha oido hablar de los seguros de vida?,str,7764,0.00,2,Canales y digitalización | Productos financieros | Ahorro,False,False,False
46,b0210,"B — Productos, canales y ahorro",Original,b0210: ha oido hablar de los seguros medicos?,str,7764,0.00,2,Canales y digitalización | Productos financieros | Ahorro,False,False,False
49,b0212,"B — Productos, canales y ahorro",Original,b0212: ha oido hablar de las criptomonedas?,str,7764,0.00,2,Canales y digitalización | Productos financieros | Ahorro,False,False,False
138,j1400,"J — Gasto, crédito y fragilidad financiera",Original,j1400: hubiera estado dispuesto a realizar la entrevista presencialmente?,int64,7764,0.00,2,Actitudes y planificación | Fragilidad y financiación,False,False,False
221,usa_banca_digital,Indicadores o variables auxiliares,Indicador derivado,Uso de ordenador/tablet o app móvil bancaria.,int64,7764,0.00,2,Canales y digitalización,False,False,False
222,pref_banca_digital,Indicadores o variables auxiliares,Indicador derivado,Preferencia por ordenador/tablet o app móvil bancaria.,int64,7764,0.00,2,Canales y digitalización,False,False,False
223,usa_pago_digital,Indicadores o variables auxiliares,Indicador derivado,Uso de aplicaciones o banca online para realizar pagos.,int64,7764,0.00,2,Otros,False,False,False
225,tiene_vehiculo_ahorro,Indicadores o variables auxiliares,Indicador derivado,Tenencia de algún producto de ahorro o inversión.,int64,7764,0.00,2,Productos financieros | Ahorro,False,False,False
226,tiene_exposicion_credito,Indicadores o variables auxiliares,Indicador derivado,"Tenencia de hipoteca, préstamo personal o tarjeta de crédito.",int64,7764,0.00,2,Productos financieros,False,False,False
227,tiene_seguro,Indicadores o variables auxiliares,Indicador derivado,Tenencia de seguro de vida o seguro médico.,int64,7764,0.00,2,Productos financieros,False,False,False
228,ahorra_12m,A — Características sociodemográficas,Indicador derivado,Ha utilizado al menos un mecanismo de ahorro en los últimos 12 meses.,int64,7764,0.00,2,Ahorro,False,False,False
230,ahorro_formal,A — Características sociodemográficas,Indicador derivado,"Uso de cuentas, depósitos, fondos o planes de pensiones para ahorrar.",int64,7764,0.00,2,Productos financieros | Ahorro,False,False,False
231,ahorro_informal,A — Características sociodemográficas,Indicador derivado,"Uso de efectivo, familia, inmuebles, remesas u otros mecanismos.",int64,7764,0.00,2,Ahorro,False,False,False
233,ingreso_por_activos,I — Vivienda,Indicador derivado,Obtiene o prevé obtener ingresos mediante activos o ahorros.,int64,7764,0.00,2,Ahorro | Ingresos | Vivienda,False,False,False
234,dependencia_ingresos_familiares,D — Actitudes y comportamiento financiero,Indicador derivado,"Dependencia de pareja, familia, ayudas o instituciones.",int64,7764,0.00,2,Ingresos,False,False,False
246,barrera_acceso_vivienda,"B — Productos, canales y ahorro",Indicador derivado,"Presenta barreras de entrada, cuota o acceso hipotecario.",int64,7764,0.00,2,Canales y digitalización | Productos financieros | Ahorro | Vivienda,False,False,False
249,financiacion_ahorros_activos,F — Decisiones financieras del hogar,Indicador derivado,Cubrió el déficit utilizando ahorros o vendiendo activos.,int64,7764,0.00,2,Ahorro | Fragilidad y financiación,False,False,False
250,financiacion_credito_informal,F — Decisiones financieras del hogar,Indicador derivado,"Cubrió el déficit mediante familia, adelantos o proveedores.",int64,7764,0.00,2,Fragilidad y financiación,False,False,False
251,financiacion_credito_formal,F — Decisiones financieras del hogar,Indicador derivado,Cubrió el déficit mediante crédito o financiación formal.,int64,7764,0.00,2,Fragilidad y financiación,False,False,False
252,financiacion_estres_pago,F — Decisiones financieras del hogar,Indicador derivado,Utilizó descubierto no autorizado o retrasó pagos.,int64,7764,0.00,2,Fragilidad y financiación,False,False,False

### Comprobaciones críticas

In [28]:

critical_checks = pd.DataFrame([
    {
        "comprobación": "Filas duplicadas",
        "resultado": int(df.duplicated().sum()),
        "estado": (
            "OK"
            if df.duplicated().sum() == 0
            else "REVISAR"
        ),
    },
    {
        "comprobación": "Columnas duplicadas",
        "resultado": int(df.columns.duplicated().sum()),
        "estado": (
            "OK"
            if df.columns.duplicated().sum() == 0
            else "REVISAR"
        ),
    },
    {
        "comprobación": "Columnas completamente vacías",
        "resultado": int(df.isna().all().sum()),
        "estado": (
            "OK"
            if df.isna().all().sum() == 0
            else "REVISAR"
        ),
    },
    {
        "comprobación": "Columnas constantes",
        "resultado": int((df.nunique(dropna=False) <= 1).sum()),
        "estado": (
            "OK"
            if (df.nunique(dropna=False) <= 1).sum() == 0
            else "REVISAR"
        ),
    },
])

display(critical_checks)

                    comprobación  resultado estado
0               Filas duplicadas          0     OK
1            Columnas duplicadas          0     OK
2  Columnas completamente vacías          0     OK
3            Columnas constantes          0     OK


## 7. Variables de segmentación

Esta sección localiza las variables demográficas disponibles. La selección definitiva debe validarse con sus etiquetas ECF y no únicamente con el nombre técnico.

In [29]:

SEGMENTATION_TERMS = [
    "sexo",
    "género",
    "edad",
    "comunidad autónoma",
    "comunidad autonoma",
    "nacimiento",
    "nacionalidad",
    "estado civil",
    "educación",
    "educacion",
    "estudios",
    "situación laboral",
    "situacion laboral",
    "ocupación",
    "ocupacion",
    "ingreso",
    "renta",
    "hogar",
    "miembros",
    "hijos",
]


def contains_any(text, terms):
    text = str(text).lower()
    return any(term in text for term in terms)


segmentation_catalog = variable_catalog.loc[
    variable_catalog.apply(
        lambda row: contains_any(
            " ".join([
                row["variable"],
                row["pregunta_ecf_completa"],
                row["bloque"],
            ]),
            SEGMENTATION_TERMS,
        ),
        axis=1,
    )
].copy()

display(
    segmentation_catalog[
        [
            "variable",
            "pregunta_ecf_resumida",
            "tipo_variable",
            "n_unicos",
            "pct_nulos",
        ]
    ].sort_values("variable")
)

,variable,pregunta_ecf_resumida,tipo_variable,n_unicos,pct_nulos
2,a04,a04: edad calculada,Original,64,0.00
6,a1030,a1030: cual es su estado civil actual?,Original,7,0.00
10,a1500,a1500: cual es su situacion laboral actual?,Original,9,0.00
11,a1510,"a1510. si tiene más de una situacion laboral, cual es la secundaria?",Original,12,0.00
34,b0205,b0205: ha oido hablar de los activos de renta fija publica/privada...?,Original,3,0.00
35,b0305,"b0305: en la actualidad tiene, (...) algun activo de renta fija publica/privada?",Original,6,0.00
36,b0405,"b0405: en los ultimos 2 anios ha adquirido,(...) algun activo de renta fija...?",Original,5,0.00
57,c0100,c0100: como cree que esta planificando su jubilacion o vejez?,Original,10,0.00
209,c0200x,"Pregunta multirrespuesta agrupada a partir de: c0200a, c0200b, c0200c, c0200d, c0200e, c0200f, c0200g, c0200h, c0200i, c0200j, c0200k",Multirrespuesta agrupada,382,0.00
58,c0300,c0300: a que edad espera jubilarse?,Original,43,0.00
211,c0400x,"Pregunta multirrespuesta agrupada a partir de: c0400a, c0400b, c0400c, c0400d, c0400e, c0400f, c0400g, c0400h, c0400i, c0400j, c0400k, c0400l, c…",Multirrespuesta agrupada,146,0.00
59,c0500,c0500: como cree que ha planificado su jubilacion?,Original,9,0.00
210,c0600x,"Pregunta multirrespuesta agrupada a partir de: c0600a, c0600b, c0600c, c0600d, c0600e, c0600f, c0600g, c0600h, c0600i, c0600j, c0600k",Multirrespuesta agrupada,76,0.00
0,ccaaf,ccaaf: codigos de comunidad autonoma de residencia,Original,17,0.00
81,d0610a,d0610a: como utilizaria ese ingreso extra en los proximos 12 meses?: a. producto,Original,13,0.97
82,d0610b,d0610b: como utilizaria ese ingreso extra en los proximos 12 meses?: b. producto,Original,13,0.97
83,d0610c,d0610c: como utilizaria ese ingreso extra en los proximos 12 meses?: c. ahorro,Original,13,0.97
84,d0610d,d0610d: como utilizaria ese ingreso extra en los proximos 12 meses?: d. pagar de,Original,13,0.97
85,d0610e,d0610e: como utilizaria ese ingreso extra en los proximos 12 meses?: e. otros,Original,12,0.97
234,dependencia_ingresos_familiares,"Dependencia de pareja, familia, ayudas o instituciones.",Indicador derivado,2,0.00
100,e0402,e0402: a que edad comenzo a participar cabaniero en competiciones de natacion?,Original,25,0.00
92,e1001,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,Original,4,0.00
177,f0900a,f0900a: quienes toman parte en las decisiones del dia a dia sobre el dinero?: a.,Original,4,0.00
184,f0900b,f0900b: quienes toman parte en las decisiones del dia a dia sobre el dinero?: b.,Original,4,0.00
186,f0900c,f0900c: quienes toman parte en las decisiones del dia a dia sobre el dinero?: c.,Original,3,0.00
188,f0900d,f0900d: quienes toman parte en las decisiones del dia a dia sobre el dinero?: d.,Original,3,0.00
190,f0900e,f0900e: quienes toman parte en las decisiones del dia a dia sobre el dinero?: e.,Original,3,0.00
178,f1000a,f1000a: quienes toman parte en las decisiones sobre las propiedades...?: a. pers,Original,4,0.00
185,f1000b,f1000b: quienes toman parte en las decisiones sobre las propiedades...?: b. pare,Original,4,0.00
187,f1000c,f1000c: quienes toman parte en las decisiones sobre las propiedades...?: c. madr,Original,4,0.00
189,f1000d,f1000d: quienes toman parte en las decisiones sobre las propiedades...?: d. padr,Original,4,0.00
191,f1000e,f1000e: quienes toman parte en las decisiones sobre las propiedades...?: e. otro,Original,3,0.00
180,f1100,f1100: quien tiene un mayor conocimiento de la economia y las finanzas del hogar,Original,7,0.00
181,f1200,f1200: edad de la persona informada,Original,75,0.00
182,f1200_b,f1200_b: edad de la persona informada (en brackets),Original,15,0.00
183,f1300,f1300: genero de la persona informada,Original,5,0.00
249,financiacion_ahorros_activos,Cubrió el déficit utilizando ahorros o vendiendo activos.,Indicador derivado,2,0.00
251,financiacion_credito_formal,Cubrió el déficit mediante crédito o financiación formal.,Indicador derivado,2,0.00
250,financiacion_credito_informal,"Cubrió el déficit mediante familia, adelantos o proveedores.",Indicador derivado,2,0.00
252,financiacion_estres_pago,Utilizó descubierto no autorizado o retrasó pagos.,Indicador derivado,2,0.00
112,i0510,i0510: alguna vez se ha enfrentado a algun obstaculo al intentar comprar su prop,Original,3,0.00
233,ingreso_por_activos,Obtiene o prevé obtener ingresos mediante activos o ahorros.,Indicador derivado,2,0.00
123,j0100,j0100: hace su hogar una planificacion de sus gastos?,Original,5,0.00
125,j0200,"j0200: en los ultimos 12 meses, han sido sus gastos mayores que sus ingresos?",Original,5,0.00
129,j0700,j0700: cuanto gasto su hogar en educacion durante el ultimo anio?,Original,213,0.00
130,j0810,j0810: alguna de estas personas no forman parte de su hogar?,Original,4,0.00
134,j1201,"j1201: ultimos 12 meses,algun miembro de su hogar ha perdido su empleo?",Original,5,0.00
135,j1202,"j1202: ultimos 12 meses,algun miembro de su hogar en paro ha encontrado empleo?",Original,5,0.00
136,j1203,"j1203: ultimos 12 meses,algun miembro de su hogar ha tenido un accidente...?",Original,5,0.00
137,j1300,j1300: cuales son los ingresos brutos anuales totales del hogar?,Original,9,0.00
165,k0402,k0402: a que edad comenzo a participar cabaniero en competiciones de natacion?,Original,17,0.00
157,k1001,k1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,Original,5,0.00
145,k1905,k1905: ha oido hablar de los activos de renta fija publica o privada?,Original,4,0.00
232,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,Indicador derivado,12,0.00
239,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,Indicador derivado,13,0.97
238,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.,Indicador derivado,13,0.97
240,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,Indicador derivado,13,0.97
236,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",Indicador derivado,39,0.00


## 8. Funciones de tablas con trazabilidad

Las tablas siguientes incorporan siempre la referencia de variable y la pregunta ECF resumida.

In [30]:

def question_for(variable):
    match = variable_catalog.loc[
        variable_catalog["variable"] == variable,
        "pregunta_ecf_resumida",
    ]

    return (
        match.iloc[0]
        if not match.empty
        else ""
    )


def frequency_table(variable, include_missing=True):
    if variable not in df.columns:
        raise KeyError(
            f"La variable '{variable}' no existe en el master."
        )

    series = df[variable]

    counts = series.value_counts(
        dropna=not include_missing
    )

    result = counts.rename("n").reset_index()
    result.columns = ["respuesta", "n"]
    result["porcentaje"] = (
        result["n"] / len(df) * 100
    ).round(2)

    result.insert(0, "variable", variable)
    result.insert(
        1,
        "pregunta_ecf",
        question_for(variable),
    )

    return result


def numeric_summary(variable):
    if variable not in df.columns:
        raise KeyError(
            f"La variable '{variable}' no existe en el master."
        )

    series = pd.to_numeric(
        df[variable],
        errors="coerce",
    )

    result = pd.DataFrame({
        "variable": [variable],
        "pregunta_ecf": [question_for(variable)],
        "n": [int(series.notna().sum())],
        "media": [series.mean()],
        "desv_std": [series.std()],
        "mínimo": [series.min()],
        "p25": [series.quantile(0.25)],
        "mediana": [series.median()],
        "p75": [series.quantile(0.75)],
        "máximo": [series.max()],
    })

    return result.round(3)


def segment_rate(
    outcome,
    segment,
    positive_value=1,
    min_group_n=30,
):
    required = {outcome, segment}

    missing = required - set(df.columns)

    if missing:
        raise KeyError(
            f"Faltan variables: {sorted(missing)}"
        )

    work = df[[outcome, segment]].copy()
    work = work.dropna()

    work["_positive"] = (
        work[outcome] == positive_value
    ).astype(int)

    result = (
        work.groupby(segment, dropna=False)
        .agg(
            n=("_positive", "size"),
            tasa=("_positive", "mean"),
        )
        .reset_index()
    )

    result = result.loc[result["n"] >= min_group_n]
    result["tasa_pct"] = (
        result["tasa"] * 100
    ).round(2)
    result = result.drop(columns="tasa")

    result.insert(0, "resultado", outcome)
    result.insert(
        1,
        "pregunta_resultado",
        question_for(outcome),
    )
    result.insert(2, "segmentación", segment)
    result.insert(
        3,
        "pregunta_segmentación",
        question_for(segment),
    )

    return result.sort_values(
        "tasa_pct",
        ascending=False,
    )

## 9. Diagnóstico inicial de indicadores clave

In [31]:

CORE_INDICATORS = [
    "n_canales_uso_banco",
    "usa_banca_digital",
    "pref_banca_digital",
    "usa_pago_digital",
    "n_productos_financieros",
    "tiene_vehiculo_ahorro",
    "tiene_exposicion_credito",
    "tiene_seguro",
    "ahorra_12m",
    "n_vehiculos_ahorro",
    "ahorro_formal",
    "ahorro_informal",
    "n_fuentes_ingreso",
    "ingreso_por_activos",
    "dependencia_ingresos_familiares",
    "score_disciplina_financiera",
    "score_preocupacion_financiera",
    "score_planificacion_financiera",
    "puntos_destino_consumo",
    "puntos_destino_ahorro",
    "puntos_destino_deuda",
    "barrera_acceso_vivienda",
    "n_dificultades_compra_vivienda",
    "financiacion_ahorros_activos",
    "financiacion_credito_informal",
    "financiacion_credito_formal",
    "financiacion_estres_pago",
    "restriccion_acceso_credito",
    "score_fragilidad_financiera",
]

available_core_indicators = [
    variable
    for variable in CORE_INDICATORS
    if variable in df.columns
]

missing_core_indicators = sorted(
    set(CORE_INDICATORS)
    - set(available_core_indicators)
)

print(
    f"Indicadores clave disponibles: "
    f"{len(available_core_indicators)}"
)
print(
    "Indicadores clave no encontrados:",
    missing_core_indicators,
)

core_indicator_catalog = variable_catalog.loc[
    variable_catalog["variable"].isin(
        available_core_indicators
    )
].copy()

display(
    core_indicator_catalog[
        [
            "variable",
            "pregunta_ecf_resumida",
            "dtype",
            "n_unicos",
            "pct_nulos",
        ]
    ]
)

Indicadores clave disponibles: 29
Indicadores clave no encontrados: []

,variable,pregunta_ecf_resumida,dtype,n_unicos,pct_nulos
220,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.,int64,7,0.00
221,usa_banca_digital,Uso de ordenador/tablet o app móvil bancaria.,int64,2,0.00
222,pref_banca_digital,Preferencia por ordenador/tablet o app móvil bancaria.,int64,2,0.00
223,usa_pago_digital,Uso de aplicaciones o banca online para realizar pagos.,int64,2,0.00
224,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,int64,10,0.00
225,tiene_vehiculo_ahorro,Tenencia de algún producto de ahorro o inversión.,int64,2,0.00
226,tiene_exposicion_credito,"Tenencia de hipoteca, préstamo personal o tarjeta de crédito.",int64,2,0.00
227,tiene_seguro,Tenencia de seguro de vida o seguro médico.,int64,2,0.00
228,ahorra_12m,Ha utilizado al menos un mecanismo de ahorro en los últimos 12 meses.,int64,2,0.00
229,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,int64,7,0.00
230,ahorro_formal,"Uso de cuentas, depósitos, fondos o planes de pensiones para ahorrar.",int64,2,0.00
231,ahorro_informal,"Uso de efectivo, familia, inmuebles, remesas u otros mecanismos.",int64,2,0.00
232,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,int64,12,0.00
233,ingreso_por_activos,Obtiene o prevé obtener ingresos mediante activos o ahorros.,int64,2,0.00
234,dependencia_ingresos_familiares,"Dependencia de pareja, familia, ayudas o instituciones.",int64,2,0.00
235,score_disciplina_financiera,"Media 1–5 de control, pago puntual, vigilancia e información.",float64,25,0.01
236,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",float64,39,0.00
237,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,float64,34,0.01
238,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.,float64,13,0.97
239,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,float64,13,0.97
240,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,float64,13,0.97
246,barrera_acceso_vivienda,"Presenta barreras de entrada, cuota o acceso hipotecario.",int64,2,0.00
248,n_dificultades_compra_vivienda,Número de dificultades experimentadas al comprar vivienda.,int64,7,0.00
249,financiacion_ahorros_activos,Cubrió el déficit utilizando ahorros o vendiendo activos.,int64,2,0.00
250,financiacion_credito_informal,"Cubrió el déficit mediante familia, adelantos o proveedores.",int64,2,0.00
251,financiacion_credito_formal,Cubrió el déficit mediante crédito o financiación formal.,int64,2,0.00
252,financiacion_estres_pago,Utilizó descubierto no autorizado o retrasó pagos.,int64,2,0.00
253,restriccion_acceso_credito,"Rechazo, concesión parcial o autoexclusión crediticia.",int64,2,0.00
254,score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia.",int64,5,0.00

In [32]:

numeric_core = [
    variable
    for variable in available_core_indicators
    if pd.api.types.is_numeric_dtype(df[variable])
    and df[variable].nunique(dropna=True) > 2
]

binary_or_categorical_core = [
    variable
    for variable in available_core_indicators
    if variable not in numeric_core
]

numeric_diagnostics = pd.concat(
    [
        numeric_summary(variable)
        for variable in numeric_core
    ],
    ignore_index=True,
) if numeric_core else pd.DataFrame()

display(numeric_diagnostics)

for variable in binary_or_categorical_core:
    display(frequency_table(variable))

,variable,pregunta_ecf,n,media,desv_std,mínimo,p25,mediana,p75,máximo
0,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.,7764,2.990,1.397,0.0,2.0,3.00,4.00,6.0
1,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,7764,2.494,1.902,0.0,1.0,2.00,4.00,9.0
2,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,7764,1.126,0.946,0.0,0.0,1.00,2.00,6.0
3,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,7764,2.464,1.403,0.0,1.0,2.00,3.00,11.0
4,score_disciplina_financiera,"Media 1–5 de control, pago puntual, vigilancia e información.",7763,4.254,0.571,1.0,4.0,4.25,4.75,5.0
5,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",7764,3.292,0.718,1.0,2.8,3.20,3.80,5.0
6,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,7763,3.593,0.729,1.0,3.2,3.60,4.20,5.0
7,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.,7689,4.071,3.933,-10.0,2.0,5.00,7.00,10.0
8,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,7689,2.913,3.191,-5.0,0.0,2.00,5.00,10.0
9,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,7689,1.402,2.912,-5.0,0.0,0.00,2.00,10.0
10,n_dificultades_compra_vivienda,Número de dificultades experimentadas al comprar vivienda.,7764,0.054,0.367,0.0,0.0,0.00,0.00,6.0
11,score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia.",7764,0.561,0.873,0.0,0.0,0.00,1.00,4.0

,variable,pregunta_ecf,respuesta,n,porcentaje
0,usa_banca_digital,Uso de ordenador/tablet o app móvil bancaria.,1,5818,74.94
1,usa_banca_digital,Uso de ordenador/tablet o app móvil bancaria.,0,1946,25.06

,variable,pregunta_ecf,respuesta,n,porcentaje
0,pref_banca_digital,Preferencia por ordenador/tablet o app móvil bancaria.,1,4242,54.64
1,pref_banca_digital,Preferencia por ordenador/tablet o app móvil bancaria.,0,3522,45.36

,variable,pregunta_ecf,respuesta,n,porcentaje
0,usa_pago_digital,Uso de aplicaciones o banca online para realizar pagos.,1,5484,70.63
1,usa_pago_digital,Uso de aplicaciones o banca online para realizar pagos.,0,2280,29.37

,variable,pregunta_ecf,respuesta,n,porcentaje
0,tiene_vehiculo_ahorro,Tenencia de algún producto de ahorro o inversión.,0,4356,56.11
1,tiene_vehiculo_ahorro,Tenencia de algún producto de ahorro o inversión.,1,3408,43.89

,variable,pregunta_ecf,respuesta,n,porcentaje
0,tiene_exposicion_credito,"Tenencia de hipoteca, préstamo personal o tarjeta de crédito.",1,5883,75.77
1,tiene_exposicion_credito,"Tenencia de hipoteca, préstamo personal o tarjeta de crédito.",0,1881,24.23

,variable,pregunta_ecf,respuesta,n,porcentaje
0,tiene_seguro,Tenencia de seguro de vida o seguro médico.,0,4335,55.83
1,tiene_seguro,Tenencia de seguro de vida o seguro médico.,1,3429,44.17

,variable,pregunta_ecf,respuesta,n,porcentaje
0,ahorra_12m,Ha utilizado al menos un mecanismo de ahorro en los últimos 12 meses.,1,5678,73.13
1,ahorra_12m,Ha utilizado al menos un mecanismo de ahorro en los últimos 12 meses.,0,2086,26.87

,variable,pregunta_ecf,respuesta,n,porcentaje
0,ahorro_formal,"Uso de cuentas, depósitos, fondos o planes de pensiones para ahorrar.",1,4556,58.68
1,ahorro_formal,"Uso de cuentas, depósitos, fondos o planes de pensiones para ahorrar.",0,3208,41.32

,variable,pregunta_ecf,respuesta,n,porcentaje
0,ahorro_informal,"Uso de efectivo, familia, inmuebles, remesas u otros mecanismos.",0,5204,67.03
1,ahorro_informal,"Uso de efectivo, familia, inmuebles, remesas u otros mecanismos.",1,2560,32.97

,variable,pregunta_ecf,respuesta,n,porcentaje
0,ingreso_por_activos,Obtiene o prevé obtener ingresos mediante activos o ahorros.,0,5297,68.23
1,ingreso_por_activos,Obtiene o prevé obtener ingresos mediante activos o ahorros.,1,2467,31.77

,variable,pregunta_ecf,respuesta,n,porcentaje
0,dependencia_ingresos_familiares,"Dependencia de pareja, familia, ayudas o instituciones.",0,4718,60.77
1,dependencia_ingresos_familiares,"Dependencia de pareja, familia, ayudas o instituciones.",1,3046,39.23

,variable,pregunta_ecf,respuesta,n,porcentaje
0,barrera_acceso_vivienda,"Presenta barreras de entrada, cuota o acceso hipotecario.",0,6705,86.36
1,barrera_acceso_vivienda,"Presenta barreras de entrada, cuota o acceso hipotecario.",1,1059,13.64

,variable,pregunta_ecf,respuesta,n,porcentaje
0,financiacion_ahorros_activos,Cubrió el déficit utilizando ahorros o vendiendo activos.,0,6744,86.86
1,financiacion_ahorros_activos,Cubrió el déficit utilizando ahorros o vendiendo activos.,1,1020,13.14

,variable,pregunta_ecf,respuesta,n,porcentaje
0,financiacion_credito_informal,"Cubrió el déficit mediante familia, adelantos o proveedores.",0,7205,92.8
1,financiacion_credito_informal,"Cubrió el déficit mediante familia, adelantos o proveedores.",1,559,7.2

,variable,pregunta_ecf,respuesta,n,porcentaje
0,financiacion_credito_formal,Cubrió el déficit mediante crédito o financiación formal.,0,7417,95.53
1,financiacion_credito_formal,Cubrió el déficit mediante crédito o financiación formal.,1,347,4.47

,variable,pregunta_ecf,respuesta,n,porcentaje
0,financiacion_estres_pago,Utilizó descubierto no autorizado o retrasó pagos.,0,7545,97.18
1,financiacion_estres_pago,Utilizó descubierto no autorizado o retrasó pagos.,1,219,2.82

,variable,pregunta_ecf,respuesta,n,porcentaje
0,restriccion_acceso_credito,"Rechazo, concesión parcial o autoexclusión crediticia.",0,7259,93.5
1,restriccion_acceso_credito,"Rechazo, concesión parcial o autoexclusión crediticia.",1,505,6.5


## 10. Cribado de relaciones candidatas

Este cribado no constituye todavía una conclusión. Sirve para encontrar relaciones que merezcan una comprobación más profunda.

Se revisarán:

- correlaciones entre indicadores numéricos;
- diferencias de indicadores por segmentos;
- tasas de resultados binarios por segmento;
- tamaños de muestra para evitar destacar grupos demasiado pequeños.

In [33]:

def spearman_screen(
    variables,
    min_complete=100,
    min_abs_correlation=0.10,
):
    existing = [
        variable
        for variable in variables
        if variable in df.columns
    ]

    numeric = df[existing].apply(
        pd.to_numeric,
        errors="coerce",
    )

    rows = []

    for variable_a, variable_b in combinations(
        existing,
        2,
    ):
        pair = numeric[
            [variable_a, variable_b]
        ].dropna()

        if len(pair) < min_complete:
            continue

        correlation = pair.corr(
            method="spearman"
        ).iloc[0, 1]

        if (
            pd.notna(correlation)
            and abs(correlation) >= min_abs_correlation
        ):
            rows.append({
                "variable_1": variable_a,
                "pregunta_1": question_for(variable_a),
                "variable_2": variable_b,
                "pregunta_2": question_for(variable_b),
                "n_completo": len(pair),
                "rho_spearman": round(
                    correlation,
                    3,
                ),
                "intensidad_abs": round(
                    abs(correlation),
                    3,
                ),
            })

    if not rows:
        return pd.DataFrame()

    return (
        pd.DataFrame(rows)
        .sort_values(
            "intensidad_abs",
            ascending=False,
        )
        .reset_index(drop=True)
    )


behaviour_numeric_candidates = [
    "n_canales_uso_banco",
    "n_productos_financieros",
    "n_vehiculos_ahorro",
    "n_fuentes_ingreso",
    "score_disciplina_financiera",
    "score_preocupacion_financiera",
    "score_planificacion_financiera",
    "puntos_destino_consumo",
    "puntos_destino_ahorro",
    "puntos_destino_deuda",
    "n_dificultades_compra_vivienda",
    "score_fragilidad_financiera",
]

correlation_candidates = spearman_screen(
    behaviour_numeric_candidates,
    min_complete=100,
    min_abs_correlation=0.10,
)

display(correlation_candidates.head(30))

,variable_1,pregunta_1,variable_2,pregunta_2,n_completo,rho_spearman,intensidad_abs
0,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,7764,0.394,0.394
1,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia.",7764,0.365,0.365
2,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,7689,-0.334,0.334
3,score_disciplina_financiera,"Media 1–5 de control, pago puntual, vigilancia e información.",score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,7762,0.316,0.316
4,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,7764,0.315,0.315
5,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,7764,0.301,0.301
6,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,7764,0.274,0.274
7,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,7689,-0.257,0.257
8,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",7764,-0.235,0.235
9,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,7689,0.221,0.221
10,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,7763,0.220,0.220
11,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,7764,0.220,0.220
12,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,7689,0.209,0.209
13,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,7764,0.189,0.189
14,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia.",7689,0.189,0.189
15,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia.",7764,-0.178,0.178
16,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,7689,-0.174,0.174
17,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,puntos_destino_deuda,Puntos del ingreso extra destinados a pagar deuda.,7689,0.149,0.149
18,n_vehiculos_ahorro,Número de mecanismos de ahorro utilizados.,puntos_destino_ahorro,Puntos del ingreso extra destinados a ahorro.,7689,0.148,0.148
19,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,7763,0.146,0.146
20,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",7764,-0.137,0.137
21,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,score_disciplina_financiera,"Media 1–5 de control, pago puntual, vigilancia e información.",7763,0.135,0.135
22,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,score_fragilidad_financiera,"Índice 0–4: déficit, impagos, pérdida de empleo y restricción crediticia.",7764,-0.133,0.133
23,n_productos_financieros,Número de familias/productos financieros actualmente contratados.,n_dificultades_compra_vivienda,Número de dificultades experimentadas al comprar vivienda.,7764,0.118,0.118
24,n_canales_uso_banco,Número de canales utilizados para relacionarse con el banco.,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,7763,0.111,0.111
25,score_planificacion_financiera,Media 1–5 orientada al futuro; ítems negativos invertidos.,puntos_destino_consumo,Puntos del ingreso extra destinados a consumo.,7689,-0.110,0.110
26,n_fuentes_ingreso,Número de fuentes actuales o previstas de ingresos.,score_preocupacion_financiera,"Media 1–5 de preocupación, endeudamiento e inquietud.",7764,-0.104,0.104

## 11. Priorización de preguntas para la Fase 2

In [34]:

priority_matrix = research_questions.copy()

priority_matrix["disponibilidad_variables"] = (
    priority_matrix[
        "variables_resultado_candidatas"
    ]
    .str.split(", ")
    .apply(
        lambda variables: (
            f"{sum(v in df.columns for v in variables)}"
            f"/{len(variables)}"
        )
    )
)

priority_matrix["prioridad_inicial"] = [
    "Alta",
    "Alta",
    "Muy alta",
    "Muy alta",
    "Muy alta",
    "Alta",
]

priority_matrix["razón_prioridad"] = [
    (
        "Permite contrastar la estrategia digital y detectar "
        "necesidades de acompañamiento."
    ),
    (
        "Conecta directamente con propuesta comercial y "
        "diversificación de productos."
    ),
    (
        "El ahorro es un comportamiento central y accionable "
        "para una entidad bancaria."
    ),
    (
        "Puede explicar diferencias de ahorro, productos y "
        "fragilidad."
    ),
    (
        "Tiene conexión directa con riesgo, prevención y "
        "bienestar financiero."
    ),
    (
        "Puede traducirse en productos de ahorro, hipoteca y "
        "asesoramiento."
    ),
]

display(
    priority_matrix[
        [
            "id",
            "tema",
            "pregunta",
            "disponibilidad_variables",
            "prioridad_inicial",
            "razón_prioridad",
        ]
    ]
)

,id,tema,pregunta,disponibilidad_variables,prioridad_inicial,razón_prioridad
0,Q1,Canales,¿Qué segmentos usan banca digital y cuáles mantienen preferencia por canales presenciales?,3/3,Alta,Permite contrastar la estrategia digital y detectar necesidades de acompañamiento.
1,Q2,Tenencia de productos,¿Qué perfiles tienen menor diversidad de productos financieros y qué productos faltan?,4/4,Alta,Conecta directamente con propuesta comercial y diversificación de productos.
2,Q3,Ahorro,¿Qué segmentos ahorran menos y cuáles dependen de mecanismos informales?,4/4,Muy alta,El ahorro es un comportamiento central y accionable para una entidad bancaria.
3,Q4,Planificación,"¿Cómo se relacionan disciplina, planificación y preocupación financiera con el ahorro?",3/3,Muy alta,"Puede explicar diferencias de ahorro, productos y fragilidad."
4,Q5,Fragilidad financiera,¿Qué perfiles presentan mayor fragilidad y qué mecanismos usan para financiar imprevistos?,5/5,Muy alta,"Tiene conexión directa con riesgo, prevención y bienestar financiero."
5,Q6,Vivienda y crédito,¿Qué segmentos afrontan mayores barreras para adquirir vivienda o acceder al crédito?,3/3,Alta,"Puede traducirse en productos de ahorro, hipoteca y asesoramiento."


## 12. Registro de hallazgos

Esta tabla se completará solo cuando una relación haya sido comprobada.

Un hallazgo válido debe incluir:

- evidencia cuantitativa;
- variable y pregunta ECF;
- segmento;
- tamaño de muestra;
- interpretación prudente;
- conexión con Banco Atlas;
- limitación;
- propuesta de visualización.

No se utilizarán expresiones causales como “provoca” o “genera” salvo que el diseño del análisis permita sostenerlas.

In [35]:

insight_register = pd.DataFrame(
    columns=[
        "id_hallazgo",
        "pregunta_análisis",
        "variable_resultado",
        "pregunta_ecf_resultado",
        "segmento_o_variable_relacionada",
        "pregunta_ecf_segmento",
        "evidencia_cuantitativa",
        "n_analizado",
        "interpretación",
        "implicación_para_banco_atlas",
        "limitación",
        "visualización_propuesta",
        "estado",
    ]
)

display(insight_register)

Empty DataFrame
Columns: [id_hallazgo, pregunta_análisis, variable_resultado, pregunta_ecf_resultado, segmento_o_variable_relacionada, pregunta_ecf_segmento, evidencia_cuantitativa, n_analizado, interpretación, implicación_para_banco_atlas, limitación, visualización_propuesta, estado]
Index: []


## 13. Próximo paso recomendado

La **Fase 2** debe comenzar por tres historias prioritarias:

### Historia A — Capacidad de ahorro y fragilidad

- ¿Quién ahorra?
- ¿Quién no puede ahorrar?
- ¿Cómo se relaciona el ahorro con la fragilidad?
- ¿Qué mecanismo se utiliza ante un imprevisto?
- ¿Qué solución podría ofrecer Banco Atlas?

### Historia B — Digitalización y brecha de canal

- ¿Quién usa banca digital?
- ¿Quién la usa pero no la prefiere?
- ¿Quién permanece fuera de los canales digitales?
- ¿Qué segmentos requieren acompañamiento o una experiencia omnicanal?

### Historia C — Planificación, productos y comportamiento

- ¿La disciplina y planificación se asocian con mayor ahorro?
- ¿Se relacionan con una cartera más diversificada?
- ¿Qué perfiles combinan baja planificación y elevada fragilidad?
- ¿Qué nudges o herramientas de gestión podrían resultar útiles?

Solo después de validar estas relaciones se diseñarán las visualizaciones.

## 14. Guardado opcional de catálogos de trabajo

In [36]:

# Se dejan preparados, pero no se exportan automáticamente para evitar
# generar archivos innecesarios durante cada ejecución.
#
# Descomenta cuando quieras conservarlos:

# variable_catalog.to_csv(
#     DATA_DIR / "2026-07-20_ECF_2021_02_Variable_Catalog.csv",
#     index=False,
#     encoding="utf-8-sig",
# )

# priority_matrix.to_csv(
#     DATA_DIR / "2026-07-20_ECF_2021_02_Research_Questions.csv",
#     index=False,
#     encoding="utf-8-sig",
# )

# insight_register.to_csv(
#     DATA_DIR / "2026-07-20_ECF_2021_02_Insight_Register.csv",
#     index=False,
#     encoding="utf-8-sig",
# )

print("Fase 1 preparada.")

Fase 1 preparada.