In [46]:
import mysql.connector
import pandas as pd
import numpy as np

config = {
    'host': '212.227.90.6',
    'user': 'Equipo28',
    'password': 'E1q2u3i4p5o28',
    'database': 'Equip_28'
}

conn = mysql.connector.connect(**config)
cursor = conn.cursor()

cursor.execute("SELECT database();")
db_actual = cursor.fetchone()[0]
print(f"--- Conectado a la base de datos: {db_actual} ---")

cursor.execute("SHOW TABLES;")
tablas = cursor.fetchall()

print("Tablas encontradas:")
for t in tablas:
    print(f" -> {t[0]}")
    globals()[t[0]] = pd.read_sql("SELECT * FROM " + t[0], conn)
    
cursor.close()
conn.close()

--- Conectado a la base de datos: Equip_28 ---
Tablas encontradas:
 -> RRHH
 -> RRHH_04052026
 -> RRHH_27042026

C:\Users\acaro\AppData\Local\Temp\ipykernel_32336\210026830.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  globals()[t[0]] = pd.read_sql("SELECT * FROM " + t[0], conn)

 -> vista_duplicados_exactos
 -> vista_duplicados_exactos2

In [47]:
RRHH_04052026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1110 entries, 0 to 1109
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       1110 non-null   int64
 1   Reason_absence           1110 non-null   int64
 2   Month_absence            1110 non-null   int64
 3   Day_week                 1110 non-null   int64
 4   Seasons                  1110 non-null   int64
 5   Transportation_expense   1110 non-null   int64
 6   Distance_Residence_Work  1110 non-null   int64
 7   Service_time             1110 non-null   int64
 8   Age                      1110 non-null   int64
 9   Work_load_Average_day    1110 non-null   object
 10  Hit_target               1110 non-null   int64
 11  Disciplinary_failure     1110 non-null   object
 12  Education                1110 non-null   object
 13  Son                      1110 non-null   object
 14  Social_drinker           1110 non-null   object
 15  Social_smoker            1110 non-null   object
 16  Pet                      1110 non-null   object
 17  Weight                   1110 non-null   int64
 18  Height                   1110 non-null   int64
 19  Body_mass_index          1110 non-null   int64
 20  Absenteeism_hours        1110 non-null   int64
dtypes: int64(14), object(7)
memory usage: 182.2+ KB

DATA CLEANING

In [48]:
df = RRHH_04052026.copy()

In [49]:
# verifica duplicados
df[df.duplicated()]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
92,10,22,12,4,4,361,52,3,28,"261,306",...,0,1,1,1,0,4,80,172,27,8
348,34,23,10,3,4,118,10,10,37,"253,465",...,0,1,0,0,0,0,83,172,28,3
383,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
386,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
387,3,27,2,6,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
388,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
389,3,27,2,6,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
396,22,23,5,4,3,179,26,9,30,"246,074",...,0,3,0,0,0,0,56,171,19,3
412,28,23,12,4,4,225,26,9,28,"280,549",...,0,1,1,0,0,2,69,169,24,3
431,3,27,3,5,2,179,51,18,38,"222,196",...,0,1,0,1,0,0,89,170,31,3
434,3,27,3,5,2,179,51,18,38,"222,196",...,0,1,0,1,0,0,89,170,31,3
454,3,23,7,6,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
479,34,27,1,2,2,118,10,10,37,"308,593",...,0,1,0,0,0,0,83,172,28,2
480,34,27,1,3,2,118,10,10,37,"308,593",...,0,1,0,0,0,0,83,172,28,2
481,34,27,1,4,2,118,10,10,37,"308,593",...,0,1,0,0,0,0,83,172,28,2
482,27,23,1,5,2,184,42,7,27,"308,593",...,0,1,0,0,0,0,58,167,21,2
483,34,27,1,5,2,118,10,10,37,"308,593",...,0,1,0,0,0,0,83,172,28,2
501,5,23,10,2,4,235,20,13,43,"265,017",...,0,1,1,1,0,0,106,167,38,2
528,24,28,7,3,1,246,25,16,41,"230,290",...,0,1,0,1,0,0,67,170,23,2
562,3,27,2,4,2,179,51,18,38,"264,249",...,0,1,0,1,0,0,89,170,31,2
563,3,27,2,6,2,179,51,18,38,"264,249",...,0,1,0,1,0,0,89,170,31,2
564,3,27,2,2,2,179,51,18,38,"264,249",...,0,1,0,1,0,0,89,170,31,2
569,3,27,2,4,2,179,51,18,38,"264,249",...,0,1,0,1,0,0,89,170,31,2
570,3,27,2,5,2,179,51,18,38,"264,249",...,0,1,0,1,0,0,89,170,31,2
577,3,27,3,4,2,179,51,18,38,"222,196",...,0,1,0,1,0,0,89,170,31,2
582,3,27,3,4,2,179,51,18,38,"222,196",...,0,1,0,1,0,0,89,170,31,2
589,22,27,4,6,3,179,26,9,30,"246,288",...,0,3,0,0,0,0,56,171,19,2
590,22,27,4,6,3,179,26,9,30,"246,288",...,0,3,0,0,0,0,56,171,19,2
592,22,27,4,6,3,179,26,9,30,"246,288",...,0,3,0,0,0,0,56,171,19,2
599,15,28,5,5,3,291,31,12,40,"237,656",...,0,1,1,1,0,1,73,171,25,2
600,22,27,5,6,3,179,26,9,30,"237,656",...,0,3,0,0,0,0,56,171,19,2
617,28,23,11,4,4,225,26,9,28,"306,345",...,0,1,1,0,0,2,69,169,24,1
663,3,28,12,6,4,179,51,18,38,"236,629",...,0,1,0,1,0,0,89,170,31,1
679,24,28,9,3,1,246,25,16,41,"261,756",...,0,1,0,1,0,0,67,170,23,1
840,14,11,11,2,4,155,12,14,34,"284,031",...,0,1,2,1,0,0,95,196,25,120
841,36,13,4,4,3,118,13,18,50,"239,409",...,0,1,1,1,0,0,98,178,31,120
842,9,6,7,3,1,228,14,16,58,"264,604",...,0,1,2,0,0,1,65,172,22,120
843,28,9,7,3,1,225,26,9,28,"230,290",...,0,1,1,0,0,2,69,169,24,112
844,9,12,3,3,2,228,14,16,58,"222,196",...,0,1,2,0,0,1,65,172,22,112
1095,14,11,11,2,4,155,12,14,34,"284,031",...,0,1,2,1,0,0,95,196,25,120
1096,36,13,4,4,3,118,13,18,50,"239,409",...,0,1,1,1,0,0,98,178,31,120
1097,9,6,7,3,1,228,14,16,58,"264,604",...,0,1,2,0,0,1,65,172,22,120
1098,28,9,7,3,1,225,26,9,28,"230,290",...,0,1,1,0,0,2,69,169,24,112
1099,9,12,3,3,2,228,14,16,58,"222,196",...,0,1,2,0,0,1,65,172,22,112
1100,11,19,3,2,3,289,36,13,33,"222,196",...,0,1,2,1,0,1,90,172,30,104
1101,36,13,6,4,3,118,13,18,50,"377,550",...,0,1,1,1,0,0,98,178,31,80
1102,14,18,12,3,2,155,12,14,34,"280,549",...,0,1,2,1,0,0,95,196,25,80
1103,13,13,7,2,1,369,17,12,31,"264,604",...,0,1,3,1,0,0,70,169,25,80
1104,34,19,12,3,4,118,10,10,37,"261,306",...,0,1,0,0,0,0,83,172,28,64
1105,22,1,10,4,4,179,26,9,30,"265,017",...,0,3,0,0,0,0,56,171,19,64
1106,26,19,5,6,3,300,26,13,43,"237,656",...,0,1,2,1,1,1,77,175,25,64
1107,34,19,12,3,4,118,10,10,37,"261,306",...,0,1,0,0,0,0,83,172,28,56
1108,20,19,4,6,3,260,50,11,36,"326,452",...,0,1,4,1,0,0,65,168,23,56
1109,14,10,5,2,3,155,12,14,34,"237,656",...,0,1,2,1,0,0,95,196,25,48

In [50]:
#borra duplicados
df = df.drop_duplicates()

VALORES FALTANTES

In [51]:
df.isnull().values.any()

False

### Check de valores unicos por cada columna

In [52]:
for col in df.columns:
    print(f"\nColonna: {col}")
    print(df[col].unique())

Colonna: ID
[ 14  36   9  28  11  13  34  22  26  20  10  15  17  24   3  18   7   1
  30   5   6   2  31  27  33  23  21  25  12  32  16  29  19   8   4  35
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386]

Colonna: Reason_absence
[11 13  6  9 12 19 18  1 10 14  7 28  2 26 23 22 21 24 17  8  5 15  4 25
  3 27 16  0]

Colonna: Month_absence
[11  4  7  3  6 12 10  5  8  9  1  2  0]

Colonna: Day_week
[2 4 3 6 5]

Colonna: Seasons
[4 3 1 2]

Colonna: Transportation_expense
[155 118 228 225 289 369 179 300 260 361 291 246 330 279 235 157 189 388
 184 248 378 268 233 231]

Colonna: Distance_Residence_Work
[12 13 14 26 36 17 10 50 52 31 22 25 51 16  5 11 27 20 29 15 42 49 48 35
 45]

Colonna: Service_time
[14 18 16  9 13 12 10 11  3 17  4  6  7  8  1 29 24 15]

Colonna: Age
[34 50 58 28 33 31 37 30 43 36 40 41 38 39 29 48 27 47 32 49 46 53]

Colonna: Work_load_Average_day
['284,031' '239,409' '264,604' '230,290' '222,196' '377,550' '280,549'
 '261,306' '265,017' '237,656' '326,452' '239,554' '205,917' '306,345'
 '343,253' '294,217' '253,957' '241,476' '275,312' '330,061' '378,884'
 '251,818' '268,519' '313,532' '246,288' '275,089' '253,465' '244,387'
 '246,074' '249,797' '308,593' '302,585' '265,615' '236,629' '261,756'
 '284,853' '264,249' '271,219']

Colonna: Hit_target
[ 97  98  93  92  99  94  88  96  95  81 100  91  87]

Colonna: Disciplinary_failure
['0' '1']

Colonna: Education
['1' '3' '2' '4']

Colonna: Son
['2' '1' '3' '0' '4']

Colonna: Social_drinker
['1' '0']

Colonna: Social_smoker
['0' '1']

Colonna: Pet
['0' '1' '2' '4' '5' '8']

Colonna: Weight
[ 95  98  65  69  90  70  83  56  77  80  73  63  67  89  84  68  88  75
 106  76  58  86  79 108  94 100]

Colonna: Height
[196 178 172 169 171 175 168 170 182 185 167 163 165 174]

Colonna: Body_mass_index
[25 31 22 24 30 28 19 23 27 29 38 33 21 32 36 35 34]

Colonna: Absenteeism_hours
[120 112 104  80  64  56  48  40  32  24  16   8   7   5   4   3   2   1
   0]

In [53]:
df[df['Month_absence'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
737,4,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",...,0,1,1,0,0,1,77,175,25,0
777,74,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
1060,352,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0

In [54]:
df[df['Absenteeism_hours'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
696,36,0,7,3,1,118,13,18,50,"239,554",...,1,1,1,1,0,0,98,178,31,0
697,20,0,9,2,4,260,50,11,36,"241,476",...,1,1,4,1,0,0,65,168,23,0
698,29,0,9,2,4,225,26,9,28,"241,476",...,1,1,1,0,0,2,69,169,24,0
699,11,0,9,3,4,289,36,13,33,"241,476",...,1,1,2,1,0,1,90,172,30,0
700,36,0,9,3,4,118,13,18,50,"241,476",...,1,1,1,1,0,0,98,178,31,0
701,13,0,9,4,4,369,17,12,31,"241,476",...,1,1,3,1,0,0,70,169,25,0
702,36,0,10,4,4,118,13,18,50,"253,465",...,1,1,1,1,0,0,98,178,31,0
703,34,27,1,2,2,118,10,10,37,"308,593",...,0,1,0,0,0,0,83,172,28,0
704,2,0,4,2,3,235,29,12,48,"326,452",...,1,1,1,0,1,5,88,163,33,0
705,7,0,5,4,3,279,5,14,39,"378,884",...,1,1,2,1,1,0,68,168,24,0
706,18,0,5,4,3,330,16,4,28,"378,884",...,1,2,0,0,0,0,84,182,25,0
707,23,0,5,4,3,378,49,11,36,"378,884",...,1,1,2,0,1,4,65,174,21,0
708,31,0,5,4,3,388,15,9,50,"378,884",...,1,1,0,0,0,0,76,178,24,0
709,20,0,7,5,1,260,50,11,36,"275,312",...,1,1,4,1,0,0,65,168,23,0
710,5,0,9,5,1,235,20,13,43,"294,217",...,1,1,1,1,0,0,106,167,38,0
711,8,0,9,3,1,231,35,14,39,"294,217",...,1,1,2,1,0,2,100,170,35,0
712,19,0,9,3,1,291,50,12,32,"294,217",...,1,1,0,1,0,0,65,169,23,0
713,5,0,9,5,4,235,20,13,43,"294,217",...,1,1,1,1,0,0,106,167,38,0
714,36,0,10,6,4,118,13,18,50,"265,017",...,1,1,1,1,0,0,98,178,31,0
715,33,0,10,6,4,248,25,14,47,"265,017",...,1,1,2,0,0,1,86,165,32,0
716,5,0,10,4,4,235,20,13,43,"265,017",...,1,1,1,1,0,0,106,167,38,0
717,5,0,10,6,4,235,20,13,43,"265,017",...,1,1,1,1,0,0,106,167,38,0
718,20,0,10,3,4,260,50,11,36,"265,017",...,1,1,4,1,0,0,65,168,23,0
719,15,0,10,3,4,291,31,12,40,"265,017",...,1,1,1,1,0,1,73,171,25,0
720,30,0,10,3,4,157,27,6,29,"265,017",...,1,1,0,1,1,0,75,185,22,0
721,18,0,11,3,4,330,16,4,28,"284,031",...,1,2,0,0,0,0,84,182,25,0
722,23,0,11,6,4,378,49,11,36,"284,031",...,1,1,2,0,1,4,65,174,21,0
723,7,0,11,3,4,279,5,14,39,"284,031",...,1,1,2,1,1,0,68,168,24,0
724,13,0,3,4,2,369,17,12,31,"244,387",...,1,1,3,1,0,0,70,169,25,0
725,1,0,3,5,3,235,11,14,37,"244,387",...,1,3,1,0,0,1,88,172,29,0
726,24,0,3,5,3,246,25,16,41,"244,387",...,1,1,0,1,0,0,67,170,23,0
727,36,0,3,5,3,118,13,18,50,"244,387",...,1,1,1,1,0,0,98,178,31,0
728,3,0,6,6,3,179,51,18,38,"253,957",...,1,1,0,1,0,0,89,170,31,0
729,28,0,10,2,4,225,26,9,28,"284,853",...,1,1,1,0,0,2,69,169,24,0
730,15,0,11,3,4,291,31,12,40,"268,519",...,1,1,1,1,0,1,73,171,25,0
731,11,0,11,4,4,289,36,13,33,"268,519",...,1,1,2,1,0,1,90,172,30,0
732,5,0,11,5,4,235,20,13,43,"268,519",...,1,1,1,1,0,0,106,167,38,0
733,36,0,5,3,3,118,13,18,50,"237,656",...,1,1,1,1,0,0,98,178,31,0
734,23,0,5,4,3,378,49,11,36,"237,656",...,1,1,2,0,1,4,65,174,21,0
735,2,0,6,2,3,235,29,12,48,"275,089",...,1,1,1,0,1,5,88,163,33,0
736,21,0,6,2,3,268,11,8,33,"275,089",...,1,2,0,0,0,0,79,178,25,0
737,4,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",...,0,1,1,0,0,1,77,175,25,0
742,39,0,9,3,4,289,36,13,33,"241,476",...,1,1,2,1,0,1,90,172,30,0
777,74,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
786,83,0,3,5,3,118,13,18,50,"244,387",...,1,1,1,1,0,0,98,178,31,0
833,130,0,10,3,4,157,27,6,29,"265,017",...,1,1,0,1,1,0,75,185,22,0
838,135,0,7,5,1,260,50,11,36,"275,312",...,1,1,4,1,0,0,65,168,23,0
917,209,0,7,5,1,260,50,11,36,"275,312",...,1,1,4,1,0,0,65,168,23,0
933,225,0,10,3,4,157,27,6,29,"265,017",...,1,1,0,1,1,0,75,185,22,0
974,266,0,11,3,4,330,16,4,28,"284,031",...,1,2,0,0,0,0,84,182,25,0
1015,307,0,3,5,3,235,11,14,37,"244,387",...,1,3,1,0,0,1,88,172,29,0
1056,348,0,3,5,3,118,13,18,50,"244,387",...,1,1,1,1,0,0,98,178,31,0
1060,352,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
1084,376,0,6,6,3,179,51,18,38,"253,957",...,1,1,0,1,0,0,89,170,31,0

Check strings vacias por columnas

In [55]:
for col in df.columns:
    empty_mask = df[col].astype(str).str.strip() == ""
    if empty_mask.any():
        print(f"\nColuna: {col}")
        print(df[empty_mask])

Contar strings vacias por columna

In [56]:
for col in df.columns:
    count_empty = (df[col].astype(str).str.strip() == "").sum()
    if count_empty > 0:
        print(f"{col}: {count_empty} strings vacias")
    
if count_empty == 0:
    print("no se ha encontrado columnas con strings vacias")

no se ha encontrado columnas con strings vacias

Check strings extrañas (espacios, commas sueltas, etc)

In [57]:
for col in df.columns:
    suspicious = df[col].astype(str).str.contains(r"^\s+$")
    if suspicious.any():
        print(f"\nValores extraños en la columna {col}:")
        print(df[suspicious])

1 - Primero creo el mapeo para la conversion.  
2 - Creo una nueva columna 'Diseas_flag' segun el CID (Code International Diseases) para distinguir entre enfermedad y no enfermedad.  
3 - Finalmente convierto las enfermedad en string con el correspondiente.

In [58]:
reason_map = {
    1: "Infecciosas y Parasitarias",
    2: "Neoplasias",
    3: "Sangre e Inmunidad",
    4: "Endocrinas y Metabólicas",
    5: "Transtornos Mentales",
    6: "Sistema Nervioso",
    7: "Oftalmología (Ojo)",
    8: "Otología (Oído)",
    9: "Sistema Circulatorio",
    10: "Sistema Respiratorio",
    11: "Sistema Digestivo",
    12: "Piel y Tejido Subcutáneo",
    13: "Sistema Osteomuscular",
    14: "Sistema Genitourinario",
    15: "Embarazo, Parto y Puerperio",
    16: "Periodo Perinatal",
    17: "Anomalias Congénitas",
    18: "Síntomas y Hallazgos Clínicos",
    19: "Lesiones y Envenenamientos",
    20: "Causas externas",
    21: "Factores de Salud",
    22: "Seguimiento del Paciente",
    23: "Consulta Médica",
    24: "Donación de Sangre",
    25: "Examen de Laboratorio",
    26: "Falta injustificada",
    27: "Fisioterapia",
    28: "Consulta Dental"
}

In [59]:
df["Disease_flag"] = df["Reason_absence"].apply(
    lambda x: np.nan if x == 0 else ("Enfermedad" if x <= 21 else "No Enfermedad")
)

In [60]:
df["Reason_absence_mapped"] = df["Reason_absence"].map(reason_map)

In [61]:
df[df["Reason_absence_mapped"].isnull()]

""" dejo los valore  NaN en la columna 'Reason_absence_mapped' para los casos que no tienen un mapeo definido,
ya que esto me permite identificar fácilmente los casos de ausencia. De esta manera, puedo mantener la integridad de los datos. """

" dejo los valore  NaN en la columna 'Reason_absence_mapped' para los casos que no tienen un mapeo definido,\nya que esto me permite identificar fácilmente los casos de ausencia. De esta manera, puedo mantener la integridad de los datos. "

In [62]:
df['Month_absence'] = df['Month_absence'].replace(0, pd.NA)

In [63]:
month_map = {
    1: "Enero",
    2: "Febrero",
    3: "Marzo",
    4: "Abril",
    5: "Mayo",
    6: "Junio",
    7: "Julio",
    8: "Agosto",
    9: "Septiembre",
    10: "Octubre",
    11: "Noviembre",
    12: "Diciembre"
}
df['Month_absence_mapped'] = df['Month_absence'].map(month_map)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       1056 non-null   int64
 1   Reason_absence           1056 non-null   int64
 2   Month_absence            1051 non-null   object
 3   Day_week                 1056 non-null   int64
 4   Seasons                  1056 non-null   int64
 5   Transportation_expense   1056 non-null   int64
 6   Distance_Residence_Work  1056 non-null   int64
 7   Service_time             1056 non-null   int64
 8   Age                      1056 non-null   int64
 9   Work_load_Average_day    1056 non-null   object
 10  Hit_target               1056 non-null   int64
 11  Disciplinary_failure     1056 non-null   object
 12  Education                1056 non-null   object
 13  Son                      1056 non-null   object
 14  Social_drinker           1056 non-null   object
 15  Social_smoker            1056 non-null   object
 16  Pet                      1056 non-null   object
 17  Weight                   1056 non-null   int64
 18  Height                   1056 non-null   int64
 19  Body_mass_index          1056 non-null   int64
 20  Absenteeism_hours        1056 non-null   int64
 21  Disease_flag             1001 non-null   object
 22  Reason_absence_mapped    1001 non-null   object
 23  Month_absence_mapped     1051 non-null   object
dtypes: int64(13), object(11)
memory usage: 206.2+ KB

In [65]:
season_map = {
    1: "Verano",
    2: "Otoño",
    3: "Invierno",
    4: "Primavera"
}

df["Seasons"] = df["Seasons"].map(season_map)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       1056 non-null   int64
 1   Reason_absence           1056 non-null   int64
 2   Month_absence            1051 non-null   object
 3   Day_week                 1056 non-null   int64
 4   Seasons                  1056 non-null   object
 5   Transportation_expense   1056 non-null   int64
 6   Distance_Residence_Work  1056 non-null   int64
 7   Service_time             1056 non-null   int64
 8   Age                      1056 non-null   int64
 9   Work_load_Average_day    1056 non-null   object
 10  Hit_target               1056 non-null   int64
 11  Disciplinary_failure     1056 non-null   object
 12  Education                1056 non-null   object
 13  Son                      1056 non-null   object
 14  Social_drinker           1056 non-null   object
 15  Social_smoker            1056 non-null   object
 16  Pet                      1056 non-null   object
 17  Weight                   1056 non-null   int64
 18  Height                   1056 non-null   int64
 19  Body_mass_index          1056 non-null   int64
 20  Absenteeism_hours        1056 non-null   int64
 21  Disease_flag             1001 non-null   object
 22  Reason_absence_mapped    1001 non-null   object
 23  Month_absence_mapped     1051 non-null   object
dtypes: int64(12), object(12)
memory usage: 206.2+ KB

In [67]:
df['Seasons'].unique()

array(['Primavera', 'Invierno', 'Verano', 'Otoño'], dtype=object)

In [68]:
df['Day_week'].unique()

array([2, 4, 3, 6, 5], dtype=int64)

In [69]:
day_map = {
    2: "Lunes",
    3: "Martes",
    4: "Miercoles",
    5: "Jueves",
    6: "Viernes"
}

df["Day_week"] = df["Day_week"].map(day_map)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       1056 non-null   int64
 1   Reason_absence           1056 non-null   int64
 2   Month_absence            1051 non-null   object
 3   Day_week                 1056 non-null   object
 4   Seasons                  1056 non-null   object
 5   Transportation_expense   1056 non-null   int64
 6   Distance_Residence_Work  1056 non-null   int64
 7   Service_time             1056 non-null   int64
 8   Age                      1056 non-null   int64
 9   Work_load_Average_day    1056 non-null   object
 10  Hit_target               1056 non-null   int64
 11  Disciplinary_failure     1056 non-null   object
 12  Education                1056 non-null   object
 13  Son                      1056 non-null   object
 14  Social_drinker           1056 non-null   object
 15  Social_smoker            1056 non-null   object
 16  Pet                      1056 non-null   object
 17  Weight                   1056 non-null   int64
 18  Height                   1056 non-null   int64
 19  Body_mass_index          1056 non-null   int64
 20  Absenteeism_hours        1056 non-null   int64
 21  Disease_flag             1001 non-null   object
 22  Reason_absence_mapped    1001 non-null   object
 23  Month_absence_mapped     1051 non-null   object
dtypes: int64(11), object(13)
memory usage: 206.2+ KB

In [71]:
df['Education'].unique()

array(['1', '3', '2', '4'], dtype=object)

In [72]:
df['Education']= df['Education'].astype(int)

In [73]:
education_map = {
    1: "Bachillerato",
    2: "Grado ",
    3: "Posgrado",
    4: "Máster"
}

df["Education_mapped"] = df["Education"].map(education_map)

In [74]:
df['Education_mapped']

0       Bachillerato
1       Bachillerato
2       Bachillerato
3       Bachillerato
4       Bachillerato
            ...
1090        Posgrado
1091    Bachillerato
1092    Bachillerato
1093    Bachillerato
1094    Bachillerato
Name: Education_mapped, Length: 1056, dtype: object

Primero quito la coma y despues casteo la columna 'Work_load_Average_day' a float

In [75]:
df["Work_load_Average_day"] = df["Work_load_Average_day"].str.replace(",", ".").astype(float)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       1056 non-null   int64
 1   Reason_absence           1056 non-null   int64
 2   Month_absence            1051 non-null   object
 3   Day_week                 1056 non-null   object
 4   Seasons                  1056 non-null   object
 5   Transportation_expense   1056 non-null   int64
 6   Distance_Residence_Work  1056 non-null   int64
 7   Service_time             1056 non-null   int64
 8   Age                      1056 non-null   int64
 9   Work_load_Average_day    1056 non-null   float64
 10  Hit_target               1056 non-null   int64
 11  Disciplinary_failure     1056 non-null   object
 12  Education                1056 non-null   int32
 13  Son                      1056 non-null   object
 14  Social_drinker           1056 non-null   object
 15  Social_smoker            1056 non-null   object
 16  Pet                      1056 non-null   object
 17  Weight                   1056 non-null   int64
 18  Height                   1056 non-null   int64
 19  Body_mass_index          1056 non-null   int64
 20  Absenteeism_hours        1056 non-null   int64
 21  Disease_flag             1001 non-null   object
 22  Reason_absence_mapped    1001 non-null   object
 23  Month_absence_mapped     1051 non-null   object
 24  Education_mapped         1056 non-null   object
dtypes: float64(1), int32(1), int64(11), object(12)
memory usage: 210.4+ KB

In [77]:
df['Work_load_Average_day'].unique()

array([284.031, 239.409, 264.604, 230.29 , 222.196, 377.55 , 280.549,
       261.306, 265.017, 237.656, 326.452, 239.554, 205.917, 306.345,
       343.253, 294.217, 253.957, 241.476, 275.312, 330.061, 378.884,
       251.818, 268.519, 313.532, 246.288, 275.089, 253.465, 244.387,
       246.074, 249.797, 308.593, 302.585, 265.615, 236.629, 261.756,
       284.853, 264.249, 271.219])

Converter columnas binarias para int

In [78]:
cols_binarias = ['Disciplinary_failure', 'Social_drinker', 'Social_smoker', 'Son', 'Pet']
for col in cols_binarias:
    df[col] = df[col].astype(int)

Estadística descriptiva

In [79]:
df.describe()

,ID,Reason_absence,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,Hit_target,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
count,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000,1056.000000
mean,82.262311,19.163826,222.228220,29.125000,12.497159,36.551136,271.295134,94.606061,0.047348,1.303977,1.045455,0.556818,0.069129,0.746212,78.898674,172.169508,26.621212,7.489583
std,108.418097,8.405970,66.429066,14.556102,4.326923,6.677488,38.300177,3.728476,0.212484,0.688031,1.109980,0.496997,0.253793,1.295265,12.789516,6.091145,4.247607,14.933149
min,1.000000,0.000000,118.000000,5.000000,1.000000,27.000000,205.917000,81.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,56.000000,163.000000,19.000000,0.000000
25%,14.000000,13.000000,179.000000,16.000000,9.000000,31.000000,244.387000,93.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,69.000000,169.000000,24.000000,2.000000
50%,28.000000,23.000000,225.000000,26.000000,13.000000,37.000000,264.249000,95.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,80.000000,170.000000,25.000000,3.000000
75%,122.250000,26.000000,260.000000,49.000000,16.000000,40.000000,284.853000,97.000000,0.000000,1.000000,2.000000,1.000000,0.000000,1.000000,89.000000,172.000000,31.000000,8.000000
max,386.000000,28.000000,388.000000,52.000000,29.000000,58.000000,378.884000,100.000000,1.000000,4.000000,4.000000,1.000000,1.000000,8.000000,108.000000,196.000000,38.000000,120.000000

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       1056 non-null   int64
 1   Reason_absence           1056 non-null   int64
 2   Month_absence            1051 non-null   object
 3   Day_week                 1056 non-null   object
 4   Seasons                  1056 non-null   object
 5   Transportation_expense   1056 non-null   int64
 6   Distance_Residence_Work  1056 non-null   int64
 7   Service_time             1056 non-null   int64
 8   Age                      1056 non-null   int64
 9   Work_load_Average_day    1056 non-null   float64
 10  Hit_target               1056 non-null   int64
 11  Disciplinary_failure     1056 non-null   int32
 12  Education                1056 non-null   int32
 13  Son                      1056 non-null   int32
 14  Social_drinker           1056 non-null   int32
 15  Social_smoker            1056 non-null   int32
 16  Pet                      1056 non-null   int32
 17  Weight                   1056 non-null   int64
 18  Height                   1056 non-null   int64
 19  Body_mass_index          1056 non-null   int64
 20  Absenteeism_hours        1056 non-null   int64
 21  Disease_flag             1001 non-null   object
 22  Reason_absence_mapped    1001 non-null   object
 23  Month_absence_mapped     1051 non-null   object
 24  Education_mapped         1056 non-null   object
dtypes: float64(1), int32(6), int64(11), object(7)
memory usage: 189.8+ KB

Renombrar nombre de columnas de ingles a castellano

In [81]:
# Dicionário de mapeo de columnas
mapeamento_es = {
    "ID": "id",
    "Reason_absence": "motivo_ausencia",
    "Month_absence": "mes_ausencia",
    "Day_week": "dia_semana",
    "Seasons": "estaciones",
    "Transportation_expense": "gasto_transporte",
    "Distance_Residence_Work": "distancia_casa_trabajo",
    "Service_time": "tiempo_servicio",
    "Age": "edad",
    "Work_load_Average_day": "carga_trabajo_diaria",
    "Hit_target": "cumplimiento_objetivo",
    "Disciplinary_failure": "falta_disciplinaria",
    "Education": "educacion",
    "Son": "hijos",
    "Social_drinker": "bebedor_social",
    "Social_smoker": "fumador_social",
    "Pet": "mascota",
    "Weight": "peso",
    "Height": "estatura",
    "Body_mass_index": "indice_masa_corporal",
    "Absenteeism_hours": "horas_ausentismo",
    "Disease_flag": "indicador_enfermedad",
    "Reason_absence_mapped": "motivo_ausencia_mapeado",
    "Month_absence_mapped": "mes_ausencia_mapeado",
    "Education_mapped": "educacion_mapeada"
}

# Renombrar en el dataset
df = df.rename(columns=mapeamento_es)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       1056 non-null   int64
 1   motivo_ausencia          1056 non-null   int64
 2   mes_ausencia             1051 non-null   object
 3   dia_semana               1056 non-null   object
 4   estaciones               1056 non-null   object
 5   gasto_transporte         1056 non-null   int64
 6   distancia_casa_trabajo   1056 non-null   int64
 7   tiempo_servicio          1056 non-null   int64
 8   edad                     1056 non-null   int64
 9   carga_trabajo_diaria     1056 non-null   float64
 10  cumplimiento_objetivo    1056 non-null   int64
 11  falta_disciplinaria      1056 non-null   int32
 12  educacion                1056 non-null   int32
 13  hijos                    1056 non-null   int32
 14  bebedor_social           1056 non-null   int32
 15  fumador_social           1056 non-null   int32
 16  mascota                  1056 non-null   int32
 17  peso                     1056 non-null   int64
 18  estatura                 1056 non-null   int64
 19  indice_masa_corporal     1056 non-null   int64
 20  horas_ausentismo         1056 non-null   int64
 21  indicador_enfermedad     1001 non-null   object
 22  motivo_ausencia_mapeado  1001 non-null   object
 23  mes_ausencia_mapeado     1051 non-null   object
 24  educacion_mapeada        1056 non-null   object
dtypes: float64(1), int32(6), int64(11), object(7)
memory usage: 189.8+ KB

In [83]:
df['carga_trabajo_diaria'].unique()

array([284.031, 239.409, 264.604, 230.29 , 222.196, 377.55 , 280.549,
       261.306, 265.017, 237.656, 326.452, 239.554, 205.917, 306.345,
       343.253, 294.217, 253.957, 241.476, 275.312, 330.061, 378.884,
       251.818, 268.519, 313.532, 246.288, 275.089, 253.465, 244.387,
       246.074, 249.797, 308.593, 302.585, 265.615, 236.629, 261.756,
       284.853, 264.249, 271.219])

In [85]:
df['carga_trabajo_diaria'].head()

0    284.031
1    239.409
2    264.604
3    230.290
4    222.196
Name: carga_trabajo_diaria, dtype: float64

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 0 to 1094
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       1056 non-null   int64
 1   motivo_ausencia          1056 non-null   int64
 2   mes_ausencia             1051 non-null   object
 3   dia_semana               1056 non-null   object
 4   estaciones               1056 non-null   object
 5   gasto_transporte         1056 non-null   int64
 6   distancia_casa_trabajo   1056 non-null   int64
 7   tiempo_servicio          1056 non-null   int64
 8   edad                     1056 non-null   int64
 9   carga_trabajo_diaria     1056 non-null   float64
 10  cumplimiento_objetivo    1056 non-null   int64
 11  falta_disciplinaria      1056 non-null   int32
 12  educacion                1056 non-null   int32
 13  hijos                    1056 non-null   int32
 14  bebedor_social           1056 non-null   int32
 15  fumador_social           1056 non-null   int32
 16  mascota                  1056 non-null   int32
 17  peso                     1056 non-null   int64
 18  estatura                 1056 non-null   int64
 19  indice_masa_corporal     1056 non-null   int64
 20  horas_ausentismo         1056 non-null   int64
 21  indicador_enfermedad     1001 non-null   object
 22  motivo_ausencia_mapeado  1001 non-null   object
 23  mes_ausencia_mapeado     1051 non-null   object
 24  educacion_mapeada        1056 non-null   object
dtypes: float64(1), int32(6), int64(11), object(7)
memory usage: 189.8+ KB

In [88]:
df.to_csv("data_cleaning_2026_04_05.csv", index=False, encoding="utf-8")