In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dfv=pd.read_csv(r'C:\Users\ismae\Desktop\ProjecteData\Equip_25\Data\clean_viajeros_07_04_2026.csv')

In [3]:
dfp=pd.read_csv(r'C:\Users\ismae\Desktop\ProjecteData\Equip_25\Data\clean_pernoctaciones_07_04_2026.csv')

In [4]:
dfv

           ccaa           pais_origen         mes  qty_viajeros   año
0     Andalucia  Residentes en España       Enero      435583.0  2015
1     Andalucia  Residentes en España     Febrero      592854.0  2015
2     Andalucia  Residentes en España       Marzo      671180.0  2015
3     Andalucia  Residentes en España       Abril      769073.0  2015
4     Andalucia  Residentes en España        Mayo      812986.0  2015
...         ...                   ...         ...           ...   ...
6895     Madrid      Países africanos      Agosto       11537.0  2019
6896     Madrid      Países africanos  Septiembre       10427.0  2019
6897     Madrid      Países africanos     Octubre       12293.0  2019
6898     Madrid      Países africanos   Noviembre       12779.0  2019
6899     Madrid      Países africanos   Diciembre       12503.0  2019

[6900 rows x 5 columns]

In [5]:
dfp

           ccaa           pais_origen         mes  qty_pernoctaciones   año
0     Andalucia  Residentes en España       Enero            902311.0  2015
1     Andalucia  Residentes en España     Febrero           1255482.0  2015
2     Andalucia  Residentes en España       Marzo           1644221.0  2015
3     Andalucia  Residentes en España       Abril           1900705.0  2015
4     Andalucia  Residentes en España        Mayo           1711168.0  2015
...         ...                   ...         ...                 ...   ...
6895     Madrid      Países africanos      Agosto             34269.0  2019
6896     Madrid      Países africanos  Septiembre             33728.0  2019
6897     Madrid      Países africanos     Octubre             37419.0  2019
6898     Madrid      Países africanos   Noviembre             47053.0  2019
6899     Madrid      Países africanos   Diciembre             38893.0  2019

[6900 rows x 5 columns]

In [6]:


dfp_medias = dfp.groupby('ccaa')['qty_pernoctaciones'].mean().reset_index().round(2)


display(dfp_medias)

                   ccaa  qty_pernoctaciones
0             Andalucia           174247.89
1              Cataluña           174715.28
2  Comunidad Valenciana            98845.72
3        Islas Baleares           204893.55
4                Madrid            65898.61

In [7]:
dfv_medias=dfv.groupby('ccaa')['qty_viajeros'].mean().reset_index().round(2)

display(dfv_medias)

                   ccaa  qty_viajeros
0             Andalucia      59575.99
1              Cataluña      60652.52
2  Comunidad Valenciana      28997.68
3        Islas Baleares      34645.85
4                Madrid      34988.96

In [8]:
dfmedias=pd.merge(dfv_medias,dfp_medias,on='ccaa',how='inner')

dfmedias['Media_per_capita']=round(dfmedias['qty_pernoctaciones'] / dfmedias['qty_viajeros'],2)

display(dfmedias)

                   ccaa  qty_viajeros  qty_pernoctaciones  Media_per_capita
0             Andalucia      59575.99           174247.89              2.92
1              Cataluña      60652.52           174715.28              2.88
2  Comunidad Valenciana      28997.68            98845.72              3.41
3        Islas Baleares      34645.85           204893.55              5.91
4                Madrid      34988.96            65898.61              1.88