In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dfv=pd.read_csv(r'..\..\Data\clean_viajeros_07_04_2026.csv')

In [3]:
dfp=pd.read_csv(r'..\..\Data\clean_pernoctaciones_07_04_2026.csv')

In [4]:
dfv

           ccaa           pais_origen         mes  qty_viajeros   año
0     Andalucia  Residentes en España       Enero      435583.0  2015
1     Andalucia  Residentes en España     Febrero      592854.0  2015
2     Andalucia  Residentes en España       Marzo      671180.0  2015
3     Andalucia  Residentes en España       Abril      769073.0  2015
4     Andalucia  Residentes en España        Mayo      812986.0  2015
...         ...                   ...         ...           ...   ...
6895     Madrid      Países africanos      Agosto       11537.0  2019
6896     Madrid      Países africanos  Septiembre       10427.0  2019
6897     Madrid      Países africanos     Octubre       12293.0  2019
6898     Madrid      Países africanos   Noviembre       12779.0  2019
6899     Madrid      Países africanos   Diciembre       12503.0  2019

[6900 rows x 5 columns]

In [5]:
dfp

           ccaa           pais_origen         mes  qty_pernoctaciones   año
0     Andalucia  Residentes en España       Enero            902311.0  2015
1     Andalucia  Residentes en España     Febrero           1255482.0  2015
2     Andalucia  Residentes en España       Marzo           1644221.0  2015
3     Andalucia  Residentes en España       Abril           1900705.0  2015
4     Andalucia  Residentes en España        Mayo           1711168.0  2015
...         ...                   ...         ...                 ...   ...
6895     Madrid      Países africanos      Agosto             29715.0  2019
6896     Madrid      Países africanos  Septiembre             31773.0  2019
6897     Madrid      Países africanos     Octubre             34520.0  2019
6898     Madrid      Países africanos   Noviembre             36234.0  2019
6899     Madrid      Países africanos   Diciembre             35413.0  2019

[6900 rows x 5 columns]

In [6]:


dfp_medias = dfp.groupby('ccaa')['qty_pernoctaciones'].mean().reset_index().round(2)


display(dfp_medias)

                   ccaa  qty_pernoctaciones
0             Andalucia           175104.74
1              Cataluña           175041.48
2  Comunidad Valenciana            98987.02
3        Islas Baleares           203881.71
4                Madrid            66271.43

In [7]:
dfv_medias=dfv.groupby('ccaa')['qty_viajeros'].mean().reset_index().round(2)

display(dfv_medias)

                   ccaa  qty_viajeros
0             Andalucia      59575.99
1              Cataluña      60652.52
2  Comunidad Valenciana      28997.68
3        Islas Baleares      34645.85
4                Madrid      34988.96

In [8]:
dfmedias=pd.merge(dfv_medias,dfp_medias,on='ccaa',how='inner')

dfmedias['Media_per_capita']=round(dfmedias['qty_pernoctaciones'] / dfmedias['qty_viajeros'],2)

display(dfmedias)

                   ccaa  qty_viajeros  qty_pernoctaciones  Media_per_capita
0             Andalucia      59575.99           175104.74              2.94
1              Cataluña      60652.52           175041.48              2.89
2  Comunidad Valenciana      28997.68            98987.02              3.41
3        Islas Baleares      34645.85           203881.71              5.88
4                Madrid      34988.96            66271.43              1.89

In [9]:
dfp_medias_año= dfp.groupby(['ccaa','año'])['qty_pernoctaciones'].mean().reset_index().round(2)

In [10]:
dfp_medias_año

                    ccaa   año  qty_pernoctaciones
0              Andalucia  2015           162153.78
1              Andalucia  2016           174908.81
2              Andalucia  2017           176375.08
3              Andalucia  2018           178900.89
4              Andalucia  2019           183185.14
5               Cataluña  2015           165639.85
6               Cataluña  2016           176060.11
7               Cataluña  2017           179510.64
8               Cataluña  2018           176182.90
9               Cataluña  2019           177813.89
10  Comunidad Valenciana  2015            92175.60
11  Comunidad Valenciana  2016            98513.96
12  Comunidad Valenciana  2017           100714.52
13  Comunidad Valenciana  2018           101412.27
14  Comunidad Valenciana  2019           102118.73
15        Islas Baleares  2015           194137.09
16        Islas Baleares  2016           207098.33
17        Islas Baleares  2017           208629.64
18        Islas Baleares  2018           207262.38
19        Islas Baleares  2019           202210.52
20                Madrid  2015            63533.71
21                Madrid  2016            63817.10
22                Madrid  2017            66630.62
23                Madrid  2018            67755.81
24                Madrid  2019            69619.93

In [11]:
dfv_medias_año= dfv.groupby(['ccaa','año'])['qty_viajeros'].mean().reset_index().round(2)

In [12]:
dfv_medias_año

                    ccaa   año  qty_viajeros
0              Andalucia  2015      54911.94
1              Andalucia  2016      58679.30
2              Andalucia  2017      59445.66
3              Andalucia  2018      60800.51
4              Andalucia  2019      64042.56
5               Cataluña  2015      56259.89
6               Cataluña  2016      60279.16
7               Cataluña  2017      61700.18
8               Cataluña  2018      61909.03
9               Cataluña  2019      63114.35
10  Comunidad Valenciana  2015      26394.08
11  Comunidad Valenciana  2016      28008.94
12  Comunidad Valenciana  2017      29385.72
13  Comunidad Valenciana  2018      30077.38
14  Comunidad Valenciana  2019      31122.29
15        Islas Baleares  2015      31171.69
16        Islas Baleares  2016      34534.21
17        Islas Baleares  2017      35363.51
18        Islas Baleares  2018      35783.84
19        Islas Baleares  2019      36350.84
20                Madrid  2015      33657.22
21                Madrid  2016      34075.56
22                Madrid  2017      34900.79
23                Madrid  2018      35933.86
24                Madrid  2019      36377.37

In [13]:
dfmedias_año=pd.merge(dfv_medias_año,dfp_medias_año,on=['ccaa','año'],how='inner')

dfmedias_año['Media_per_capita']=round(dfmedias_año['qty_pernoctaciones'] / dfmedias_año['qty_viajeros'],2)

display(dfmedias_año)

,ccaa,año,qty_viajeros,qty_pernoctaciones,Media_per_capita
0,Andalucia,2015,54911.94,162153.78,2.95
1,Andalucia,2016,58679.30,174908.81,2.98
2,Andalucia,2017,59445.66,176375.08,2.97
3,Andalucia,2018,60800.51,178900.89,2.94
4,Andalucia,2019,64042.56,183185.14,2.86
5,Cataluña,2015,56259.89,165639.85,2.94
6,Cataluña,2016,60279.16,176060.11,2.92
7,Cataluña,2017,61700.18,179510.64,2.91
8,Cataluña,2018,61909.03,176182.90,2.85
9,Cataluña,2019,63114.35,177813.89,2.82
10,Comunidad Valenciana,2015,26394.08,92175.60,3.49
11,Comunidad Valenciana,2016,28008.94,98513.96,3.52
12,Comunidad Valenciana,2017,29385.72,100714.52,3.43
13,Comunidad Valenciana,2018,30077.38,101412.27,3.37
14,Comunidad Valenciana,2019,31122.29,102118.73,3.28
15,Islas Baleares,2015,31171.69,194137.09,6.23
16,Islas Baleares,2016,34534.21,207098.33,6.00
17,Islas Baleares,2017,35363.51,208629.64,5.90
18,Islas Baleares,2018,35783.84,207262.38,5.79
19,Islas Baleares,2019,36350.84,202210.52,5.56
20,Madrid,2015,33657.22,63533.71,1.89
21,Madrid,2016,34075.56,63817.10,1.87
22,Madrid,2017,34900.79,66630.62,1.91
23,Madrid,2018,35933.86,67755.81,1.89
24,Madrid,2019,36377.37,69619.93,1.91