In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import mysql.connector
from pathlib import Path
from getpass import getpass

pd.set_option('display.max_columns', None)

In [2]:
def encontrar_raiz_proyecto(nombre_carpeta='Equip_34'):
    '''
    Función para encontrar la carpeta raíz del proyecto subiendo desde el directorio actual.
    '''
    actual = Path.cwd()
    for carpeta in [actual] + list(actual.parents):
        if carpeta.name == nombre_carpeta:
            return carpeta
    raise FileNotFoundError(f"No se encontró la carpeta '{nombre_carpeta}' subiendo desde {actual}")

raiz_proyecto = encontrar_raiz_proyecto('Equip_34')
ruta = raiz_proyecto / 'Data' / 'clean_dataset_06_07_2026.csv'
print(f"Ruta resuelta: {ruta}")
df_original = pd.read_csv(ruta)
df = df_original.copy()

Ruta resuelta: c:\Users\lacal\Desktop\IT_ACADEMY\simulador\ProjecteData\Equip_34\Data\clean_dataset_06_07_2026.csv

In [3]:
df

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price_€,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date
0,15695052,Wonderful room in the heart of BCN,Wonderful bedroom located in the heart of Barc...,958218,el Raval,Ciutat Vella,Private room,1,1.0,1.0,1.0,"TV,Cable TV,Internet,Wireless Internet,Air con...",350.0,3,10,NaN,29,59,89,364,2,2016-10-26,2016-10-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,82.0,spain,Barcelona,2017-01-04
1,14999488,Habitaci�n doble en bonito apartamento,Piso grande y bonito de 90 m2. Tranquilo y por...,7093663,el Camp d'en Grassot i Gr�cia Nova,Gr�cia,Private room,2,1.0,1.0,1.0,"Internet,Wireless Internet,Air conditioning,Ki...",250.0,1,30,NaN,4,18,48,104,2,2016-10-06,2016-12-27,900.0,100.0,100.0,100.0,90.0,100.0,100.0,VERDADERO,65.0,spain,Barcelona,2017-01-04
2,12265320,"Vila Olimp,Strandblick,Privatzimmer",Grosse&helle Wohnung. 2 private Zimmer (4 Pers...,13561936,la Vila Ol�mpica del Poblenou,Sant Mart�,Private room,2,2.0,1.0,2.0,"Internet,Wireless Internet,Air conditioning,Ki...",650.0,1,1125,NaN,30,60,90,365,22,2016-05-08,2016-12-27,990.0,100.0,100.0,100.0,100.0,100.0,100.0,FALSO,272.0,spain,Barcelona,2017-01-04
3,16272738,Comfortable double bedroom Parc G�ell,"Cerca del Barrio de Gracia, Parc G�ell i Sagra...",13952311,el Baix Guinard�,Horta-Guinard�,Private room,2,2.0,1.0,1.0,"TV,Wireless Internet,Kitchen,Smoking allowed,B...",760.0,2,1125,NaN,27,55,85,360,1,2017-01-02,2017-01-02,1000.0,100.0,100.0,100.0,80.0,80.0,80.0,VERDADERO,10.0,spain,Barcelona,2017-01-04
4,16262996,"Lovely, cheap, nice room in the heart of Barce...","We have a nice and cozy room for two, in a spa...",106351045,el Raval,Ciutat Vella,Private room,2,1.0,1.0,1.0,"Wireless Internet,Kitchen,Smoking allowed,Brea...",350.0,1,1125,NaN,27,54,84,85,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,Barcelona,2017-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7688,29535697,TIME CAPSULE - Deluxe two bedrooms with balcony,"Luxurious,spacious and sunny two bedrooms apar...",167159066,Centro,NaN,Entire home/apt,4,1.0,2.0,2.0,"Essentials, Iron, Hair dryer, First aid kit, C...",2250.0,2,7,VERDADERO,0,0,0,123,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,NaN,spain,Malaga,2021-02-27
7689,18499980,Apartamento en Port D'Aro,Acogedor apartamento ubicado en planta baja de...,128380878,Castell-Platja d'Aro,NaN,Entire home/apt,6,2.0,3.0,4.0,"Washer, Wifi, Essentials, Pool, Bathtub, Heati...",1140.0,6,1125,VERDADERO,0,0,0,0,4,2017-08-30,2019-08-16,1000.0,100.0,100.0,100.0,100.0,100.0,100.0,VERDADERO,9.0,spain,Girona,2021-02-27
7690,20854917,Estudio para 2 personas zona Arenal,Este estudio de 25 m2 presenta una decoraci�n ...,137959507,Arenal,Casco Antiguo,Hotel room,2,1.0,1.0,1.0,"Lockbox, Air conditioning, Carbon monoxide ala...",700.0,1,30,VERDADERO,25,39,59,255,1,2018-11-12,2018-11-12,800.0,60.0,100.0,100.0,100.0,100.0,100.0,VERDADERO,4.0,spain,Sevilla,2021-02-27
7691,11956034,Apartamento Deluxe Centro hist�rico,"Apartamento boutique, a 80 mts de la catedral,...",63843735,Santa Cruz,Casco Antiguo,Entire home/apt,4,1.0,1.0,1.0,"Essentials, TV, Iron, Heating, Wifi, Hangers, ...",1650.0,1,1125,VERDADERO,27,44,74,338,6,2016-07-31,2021-01-03,930.0,90.0,90.0,90.0,90.0,100.0,90.0,VERDADERO,11.0,spain,Sevilla,2021-02-27
7692,4079653,VERY LUMINOUS APARTMENT,This apartment is located very close to the ce...,21160988,Centro,NaN,Entire home/apt,3,1.0,1.0,2.0,"Essentials, Iron, Hair dryer, First aid kit, C...",490.0,2,1125,VERDADERO,29,59,89,179,76,2017-04-16,2020-08-09,900.0,90.0,90.0,100.0,100.0,90.0,90.0,VERDADERO,161.0,spain,Malaga,2021-02-27

In [7]:
periodos = [30, 60, 90, 365]

for p in periodos:
    df[f"occupancy_{p}"] = p - df[f"availability_{p}"]

In [8]:
periodos = [30, 60, 90, 365]

for p in periodos:
    df[f"occupancy_{p}_pct"] = (
        (p - df[f"availability_{p}"]) / p
    ) * 100

In [9]:
df

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price_€,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date,occupancy_30,occupancy_60,occupancy_90,occupancy_365,occupancy_30_pct,occupancy_60_pct,occupancy_90_pct,occupancy_365_pct
0,15695052,Wonderful room in the heart of BCN,Wonderful bedroom located in the heart of Barc...,958218,el Raval,Ciutat Vella,Private room,1,1.0,1.0,1.0,"TV,Cable TV,Internet,Wireless Internet,Air con...",350.0,3,10,NaN,29,59,89,364,2,2016-10-26,2016-10-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,82.0,spain,Barcelona,2017-01-04,1,1,1,1,3.333333,1.666667,1.111111,0.273973
1,14999488,Habitaci�n doble en bonito apartamento,Piso grande y bonito de 90 m2. Tranquilo y por...,7093663,el Camp d'en Grassot i Gr�cia Nova,Gr�cia,Private room,2,1.0,1.0,1.0,"Internet,Wireless Internet,Air conditioning,Ki...",250.0,1,30,NaN,4,18,48,104,2,2016-10-06,2016-12-27,900.0,100.0,100.0,100.0,90.0,100.0,100.0,VERDADERO,65.0,spain,Barcelona,2017-01-04,26,42,42,261,86.666667,70.000000,46.666667,71.506849
2,12265320,"Vila Olimp,Strandblick,Privatzimmer",Grosse&helle Wohnung. 2 private Zimmer (4 Pers...,13561936,la Vila Ol�mpica del Poblenou,Sant Mart�,Private room,2,2.0,1.0,2.0,"Internet,Wireless Internet,Air conditioning,Ki...",650.0,1,1125,NaN,30,60,90,365,22,2016-05-08,2016-12-27,990.0,100.0,100.0,100.0,100.0,100.0,100.0,FALSO,272.0,spain,Barcelona,2017-01-04,0,0,0,0,0.000000,0.000000,0.000000,0.000000
3,16272738,Comfortable double bedroom Parc G�ell,"Cerca del Barrio de Gracia, Parc G�ell i Sagra...",13952311,el Baix Guinard�,Horta-Guinard�,Private room,2,2.0,1.0,1.0,"TV,Wireless Internet,Kitchen,Smoking allowed,B...",760.0,2,1125,NaN,27,55,85,360,1,2017-01-02,2017-01-02,1000.0,100.0,100.0,100.0,80.0,80.0,80.0,VERDADERO,10.0,spain,Barcelona,2017-01-04,3,5,5,5,10.000000,8.333333,5.555556,1.369863
4,16262996,"Lovely, cheap, nice room in the heart of Barce...","We have a nice and cozy room for two, in a spa...",106351045,el Raval,Ciutat Vella,Private room,2,1.0,1.0,1.0,"Wireless Internet,Kitchen,Smoking allowed,Brea...",350.0,1,1125,NaN,27,54,84,85,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSO,NaN,spain,Barcelona,2017-01-04,3,6,6,280,10.000000,10.000000,6.666667,76.712329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7688,29535697,TIME CAPSULE - Deluxe two bedrooms with balcony,"Luxurious,spacious and sunny two bedrooms apar...",167159066,Centro,NaN,Entire home/apt,4,1.0,2.0,2.0,"Essentials, Iron, Hair dryer, First aid kit, C...",2250.0,2,7,VERDADERO,0,0,0,123,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VERDADERO,NaN,spain,Malaga,2021-02-27,30,60,90,242,100.000000,100.000000,100.000000,66.301370
7689,18499980,Apartamento en Port D'Aro,Acogedor apartamento ubicado en planta baja de...,128380878,Castell-Platja d'Aro,NaN,Entire home/apt,6,2.0,3.0,4.0,"Washer, Wifi, Essentials, Pool, Bathtub, Heati...",1140.0,6,1125,VERDADERO,0,0,0,0,4,2017-08-30,2019-08-16,1000.0,100.0,100.0,100.0,100.0,100.0,100.0,VERDADERO,9.0,spain,Girona,2021-02-27,30,60,90,365,100.000000,100.000000,100.000000,100.000000
7690,20854917,Estudio para 2 personas zona Arenal,Este estudio de 25 m2 presenta una decoraci�n ...,137959507,Arenal,Casco Antiguo,Hotel room,2,1.0,1.0,1.0,"Lockbox, Air conditioning, Carbon monoxide ala...",700.0,1,30,VERDADERO,25,39,59,255,1,2018-11-12,2018-11-12,800.0,60.0,100.0,100.0,100.0,100.0,100.0,VERDADERO,4.0,spain,Sevilla,2021-02-27,5,21,31,110,16.666667,35.000000,34.444444,30.136986
7691,11956034,Apartamento Deluxe Centro hist�rico,"Apartamento boutique, a 80 mts de la catedral,...",63843735,Santa Cruz,Casco Antiguo,Entire home/apt,4,1.0,1.0,1.0,"Essentials, TV, Iron, Heating, Wifi, Hangers, ...",1650.0,1,1125,VERDADERO,27,44,74,338,6,2016-07-31,2021-01-03,930.0,90.0,90.0,90.0,90.0,100.0,90.0,VERDADERO,11.0,spain,Sevilla,2021-02-27,3,16,16,27,10.000000,26.666667,17.777778,7.397260
7692,4079653,VERY LUMINOUS APARTMENT,This apartment is located very close to the ce...,21160988,Centro,NaN,Entire home/apt,3,1.0,1.0,2.0,"Essentials, Iron, Hair dryer, First aid kit, C...",490.0,2,1125,VERDADERO,29,59,89,179,76,2017-04-16,2020-08-09,900.0,90.0,90.0,100.0,100.0,90.0,90.0,VERDADERO,161.0,spain,Malaga,2021-02-27,1,1,1,186,3.333333,1.666667,1.111111,50.958904

In [10]:
df.columns

Index(['apartment_id', 'name', 'description', 'host_id', 'neighbourhood_name',
       'neighbourhood_district', 'room_type', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'amenities_list', 'price_€', 'minimum_nights',
       'maximum_nights', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'first_review_date', 'last_review_date',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'is_instant_bookable', 'reviews_per_month',
       'country', 'city', 'insert_date', 'occupancy_30', 'occupancy_60',
       'occupancy_90', 'occupancy_365', 'occupancy_30_pct', 'occupancy_60_pct',
       'occupancy_90_pct', 'occupancy_365_pct'],
      dtype='object')