# Exploración Inicial de los Datos (Exploratory Data Analysis - EDA)

In [63]:
# imports
import pandas as pd
import json
import numpy as np


# graficos
import matplotlib.pyplot as plt

In [2]:
# tablas full view, scrolleables
pd.set_option("display.max_rows", None, "display.max_columns", None) ## para ver outputs scrolleables

In [ ]:
# Ruta LOCAL !!! CAMBIAR 
RUTA_LECTURA = ".../ecf_2021.csv"

In [5]:
# Crear dataframe + read csv
df_raw = pd.read_csv(RUTA_LECTURA  , sep=";")

In [8]:
# print
df_raw.head()

,a01,a02,a0000,a0400,a04,a0800,a0100,a0320,a1030,a1040,a0910,a1100,a1200,a1300,a1400,a1410,a1420a,a1420b,a1420c,a1420d,a1420e,a1420f,a1420g,a1500,a1510,a1600,a1520,a1530,a2000,a1700,a1710,a1900,a2100,a2200,a2300,a2500,a2400,a2600,a2700,b0100,b0110a,b0110b,b0110c,b0110d,b0110e,b0110f,b0110g,b0120a,b0120b,b0120c,b0120d,b0120e,b0120f,b0130a,b0130b,b0130c,b0208,b0308,b0408,b0201,b0301,b0401,b0202,b0302,b0402,b0203,b0303,b0403,b0204,b0304,b0404,b0205,b0305,b0405,b0206,b0306,b0406,b0207,b0307,b0407,b0209,b0309,b0409,b0210,b0310,b0410,b0212,b0312,b0412,b1100a,b1100b,b1100c,b1100d,b1100e,b1100f,b1100g,b1100i,b1100h,b0502,b0503,b0600,b0720a,b0720b,b0720c,b0720d,b0720e,b0720f,b0720g,b0720h,b0720i,b0710a,b0710b,b0710c,b0710d,b0710e,b0710f,b0710g,b0710h,b0710i,b1000a,b1000b,b1000c,b1000d,b1000e,b1000f,b1000g,b1000h,b1000i,b1000j,b1103,b1201,b1203a,b1203b,b1203c,b1203d,b1203e,b1203f,b1203g,b1204a,b1204b,b1204c,b1204d,b1204e,b1204f,b1204g,b1205a,b1205b,b1205c,b1205d,b1205e,b1206a,b1206b,b1206c,b1206d,b1206e,b1207a,b1207b,b1207c,b1208a,b1208b,b1208c,b1208d,b1209a,b1209b,b1209c,b1209d,b1230a,b1230b,b1230c,b1230d,b1230e,b1230f,b1230g,b1230h,c0100,c0200a,c0200b,c0200c,c0200d,c0200e,c0200f,c0200g,c0200h,c0200i,c0200j,c0200k,c0300,c0500,c0600a,c0600b,c0600c,c0600d,c0600e,c0600f,c0600g,c0600h,c0600i,c0600j,c0600k,c0400a,c0400b,c0400c,c0400d,c0400e,c0400f,c0400g,c0400h,c0400i,c0400j,c0400k,c0400l,c0400m,c0400n,d0101,d0104,d0110,d0113,d0102,d0114,d0115,d0117,d0103,d0116,d0105,d0106,d0107,d0108,d0109,d0111,d0112,d0300,d0400,d0500,d0600,d0610a,d0610b,d0610c,d0610d,d0610e,e0100,e0500,e0600,e0700,e0800,e0900,e1001,e1002,e1003,e1004,e1005,e1200,e1101,e0401,e0402,e0300,e1400,e1500,e1600,e1701,e1702,e1800,e1300,i0100,i0200a,i0200b,i0200c,i0200d,i0200e,i0200h,i0200f,i0200g,i0200j,i0300,i0500a,i0500b,i0500c,i0500d,i0500e,i0500f,i0500g,i0500h,i0500i,i0500k,i0500j,i0800,i0510,i0520a,i0520b,i0520c,i0520e,i0520f,i0520d,i0520g,i0601,i0602,i0700,i0900,i1000,i0400a,i0400b,i0400c,i0400d,i0400e,j0100,j0110,j0200,j0300a,j0300b,j0300c,j0300d,j0300e,j0300f,j0300g,j0300h,j0300i,j0300j,j0300k,j0300l,j0300m,j0300n,j0300p,j0300o,j0400,j0500,j0600,j0700,j0800a,j0800b,j0800c,j0800d,j0800e,j0800f,j0800h,j0800g,j0810,j0900a,j0900b,j0900c,j0900d,j0910a,j0910b,j0910c,j0910d,j0910e,j0910f,j0920,j1000,j1100,j1201,j1202,j1203,j1300,j1400,j1600,k1908,k1901,k1902,k1903,k1904,k1905,k1906,k1907,k1909,k1910,k1912,k0100,k0500,k0600,k0700,k0800,k0900,k1001,k1002,k1003,k1004,k1005,k1200,k1101,k0401,k0402,k0300,k1400,k1500,k1600,k1701,k1702,k1800,k1300,k2020,negativa_pmi,tmp_e0401,age,f0900a,f1000a,weight,a0940,a0930,a0300,a0310,ccaaf,a0930_b,a0950,f1100,f1200,f1200_b,f1300,a0900b,a0900c,a0900d,a0900e,a0900f,a0900l,a0900j,a0900h,a0900g,a0900i,a0900a,a0900k,a1800,a0200,f0900b,f1000b,f0900c,f1000c,f0900d,f1000d,f0900e,f1000e,ID
0,2022,6,0,1982,40,-98,1,0,2,2,3,7,5,-98,4,1,0,1,0,0,0,0,0,2,11,-98,2,-98,2,-98,21,0,50,80,-98,3,2,11,8,1,0,1,0,1,1,0,0,1,0,0,0,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,0,1,0,0,1,0,0,1,1,1,1,1,0,1,0,0,1,0,0,1,0,0,0,-98,0,-98,-98,-98,-98,0,1,6,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,0,1,1,0,0,1,1,0,0,1,0,0,0,0,0,0,0,60,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,5,5,5,3,2,4,4,5,3,2,3,2,2,3,5,3,2,1,1,-98,20,4,1,3,1,1,3,200.0,1,0.0,120.0,2,1,1,-97,1,1,1,1,3,18,500.0,1.0,30.0,4,1,2,1,5,1,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,1,0,0,0,0,0,1,0,0,0,0,2007,-98,-98,-98,-98,-98,-98,-98,-98,1,1,450,80,0,1,2,5,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,800,2,1500,1,0,0,0,0,0,0,0,1,0,0,0,1,-98,-98,-98,-98,-98,-98,-98,0,-98,0,0,0,4,-5,3,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,69.70,40,1,1,6814.1260,1,44,-98,-98,1,-98,15,1,40,-98,0,1,0,0,0,0,0,0,0,0,0,0,0,44,1,1,1,-98,-98,-98,-98,0,0,1
1,2022,3,0,1967,54,-98,1,0,1,-98,2,8,5,-98,1,0,0,1,1,1,1,0,0,2,11,-98,1,-98,-99,-98,27,0,20,10,-98,-98,-98,11,8,1,1,1,1,1,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,-98,-98,-98,-98,-98,-98,1,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,0,0,0,0,0,0,1,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,1,0,0,1,0,0,0,3,1,0,0,0,0,0,0,0,0,0,0,67,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,3,5,4,4,2,2,2,4,2,2,4,4,4,4,4,4,1,1,1,-98,50,0,2,0,8,0,3,200.0,3,0.0,100.0,-97,-97,1,-97,0,3,0,2,3,24,-97.0,3.0,30.0,2,2,1,5,1,2,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,0,0,0,0,0,0,1,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,-98,-98,-98,1,0,2,1,6,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,300,2,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,1,0,1,0,0,1,0,0,3,0,-98,0,0,1,4,-98,3,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,88.47,54,1,1,3277.0151,-98,-98,-98,-98,5,-98,-98,1,54,-98,0,0,0,0,1,0,0,0,0,0,0,0,0,22,5,-98,-98,1,1,-98,-98,-98,-98,2
2,2022,2,1,1967,54,-98,1,0,6,-98,1,4,-98,-98,5,0,0,0,0,0,0,0,1,2,4,-98,1,-98,1,-98,34,0,0,75,-98,-98,-98,11,4,1,0,1,0,1,1,0,0,0,0,0,1,1,0,1,1,0,1,0,0,1,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,-98,-98,1,1,-98,1,0,-98,4,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,1,0,0,0,0,0,0,0,4,1,0,1,0,0,1,1,1,0,0,0,60,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,4,5,5,3,3,3,2,1,2,1,4,3,3,3,2,1,5,0,-98,0,0,5,0,5,0,0,3,200.0,3,0.0,102.0,1,1,1,1,-98,9,1,1,3,18,5.0,10.0,30.0,4,1,2,1,10,2,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,0,0,0,0,0,0,1,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,-98,-98,-98,1,0,0,0,10,0,0,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,7,350,2,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,1,-98,-98,-98,-98,-98,-98,-98,0,-98,0,0,0,4,-5,3,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,68.56,54,-98,-98,1730.8894,-98,-98,-98,-98,11,-98,-98,-98,-98,-98,-98,0,0,0,0,0,0,0,0,0,0,1,0,36,11,-98,-98,-98,-98,-98,-98,-98,-98,3
3,2022,5,1,1974,48,-98,1,0,2,2,3,4,-98,-98,2,0,0,0,0,0,0,0,1,2,11,-98,1,-98,2,-98,25,0,0,30,-98,7,5,11,9,1,0,1,0,1,1,0,0,0,0,0,1,0,0,1,1,0,1,1,0,1,1,0,1,1,0,1,0,0,1,0,0,1,0,0,1,0,0,1,1,0,1,1,0,1,0,0,1,0,0,0,0,0,-98,-98,-98,-98,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,1,0,0,0,0,0,0,0,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,0,1,1,1,0,4,1,1,0,0,0,0,0,0,0,0,0,62,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,5,5,5,3,1,5,2,4,1,3,1,5,3,2,4,2,4,1,0,-98,50,0,8,2,0,0,3,200.0,2,0.0,102.0,2,1,1,-97,-97,-98,1,3,3,18,100.0,10.0,30.0,4,1,2,1,7,1,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,1,0,0,0,0,1,0,0,0,1,0,2021,1,0,0,0,0,1,1,0,1,1,289,100,0,0,0,2,8,0,0,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,4,500,2,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,1,-98,-98,-98,-98,-98,-98,-98,0,-98,0,0,0,4,-98,3,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98.0,-98,-98,-98,-98,-98,-98,-98,-98,98.48,48,1,1,3449.5601,0,41,-98,-98,5,-98,17,1,48,-98,1,1,0,0,0,0,0,0,0,0,0,0,0,59,5,1,1,-98,-98,-98,-98,0,0,4
4,2022,6,1,1972,49,-98,1,0,1,-98,2,2,-98,-98,1,0,0,0,0,0,0,0,1,2,11,-98,1,-98,2,-98,15,0,10,10,-98,-98,-98,9,5,1,1,1,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,-98,-98,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,1,1,1,1,0,1,0,0,1,0,0,1,0,0,1,-98,-98,-98,-98,-98,-98,0,0,-5,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,0,0,0,0,0,0,1,0,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,1,1,0,1,1,1,0,3,1,0,0,0,0,0,0,0,1,0,0,65,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,2,5,3,5,1,1,2,4,1,1,1,4,2,4,4,1,3,0,-98,0,25,10,0,0,0,0,1,-97.0,3,0.0,-97.0,-97,-97,1,-97,-97,-98,1,1,3,24,2.0,-97.0,100.0,2,2,-97,4,5,2,-98,-98,-98,-98,-98,-98,-98,-98,-98,-98,1,0,0,0,1,0,0,0,0,1,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,-98,-98,-98,0,10,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2,120,1,0,-98,-98,-98,-98,-98,-98,-98,-98,-98,0,0,0,1,-98,-98,-98,-98,-98,-98,-98,1,1,1,1,0,2,-98,3,0,1,1,1,1,1,1,1,1,1,1,1,250,3,0,-97.0,4,1,1,1,-98,4,1,2,-97,18,-97,40.0,-97,1,1,1,2,5,3,0,73.16,49,0,0,2644.1462,-98,-98,-98,-98,4,-98,-98,3,76,-98,0,0,0,0,1,0,0,0,0,0,0,0,0,92,4,-98,-98,1,1,-98,-98,-98,-98,5

In [ ]:
# ver total registros / total columnas y datatype.

print(f"Registros: {len(df_raw)}")
print(f"Columnas: {df_raw.shape[1]}") # son 400 columnas, así que reduciremos. 
#print("\nTipos de datos:")
#print(df_raw.dtypes)

Registros: 7764
Columnas: 429

In [60]:
# df_num numérico _ COLUMNAS CONOCIMIENTOS
columnas_raw = [ "a0000", "a0400", "a04" ,"e0100", "e0500", "e0600", "e0700", "e0800", "e0900", "e1001", "e1002", "e1003", "e1004",]

df_num = df_raw.loc[:, columnas_raw]


## Renombras columnas

df_num = df_num.rename(columns={
    #socio-demo
    "a0000" : "género",             #[1= Male , 0 = Female, -98 = otros]
    "a0400" : "anio_nac",
    "a04"   : "edad" ,
    
    ####################
    # competencias financieras
    ## Respuestas: no sabe (-97), se niega a responder (-99). respuesta irrelevante (-999).

    "e0100" : "autoevaluacion",     # 1 = muy alto,  2 = bastante alto, 3 = promedio, 4 = bastante bajo, 5 = muy bajo.
    "e0500" : "division_simple" ,   # respuesta correcta: 200 __ valor numérico abierto. 
    "e0600" : "inflacion",          # respuesta correcta: 3 y 4. ## Ranking 1 a 4.  Código especial: -5
    "e0700" : "interes-prestamo",   # respuesta correcta: 0 ## Código especial: -5
    "e0800" : "interes-simple",     # respuesta correcta: 102  __ valor numérico abierto.
    "e0900" : "interes-compuesto",  # resp correcta 1    #Código especial: -5  

    "e1001" : "riesgo_a",           # todas siguientes son afirmaciones verdadero = 1 / falso = 0
    "e1002" : "riesgo_b", 
    "e1003" : "riesgo_c",            # resp correcta 1    #Código especial: -5  
    "e1004" : "riesgo_d",
    })
    

# ver tabla
df_num.head(10)

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
0,0,1982,40,3,200.0,1,0.0,120.0,2,1,1,-97,1
1,0,1967,54,3,200.0,3,0.0,100.0,-97,-97,1,-97,0
2,1,1967,54,3,200.0,3,0.0,102.0,1,1,1,1,-98
3,1,1974,48,3,200.0,2,0.0,102.0,2,1,1,-97,-97
4,1,1972,49,1,-97.0,3,0.0,-97.0,-97,-97,1,-97,-97
5,1,1960,61,3,250.0,3,0.0,110.0,1,1,1,1,-98
6,0,1973,48,4,200.0,3,0.0,102.0,1,1,1,1,-98
7,1,1986,36,1,-97.0,1,0.0,-97.0,4,1,1,-97,-97
8,1,1969,52,1,200.0,-5,0.0,-5.0,-97,1,1,0,-98
9,1,1982,40,3,225.0,2,0.0,102.0,4,1,1,1,-98

_____

### RECORTE **COMPETENCIAS FINANCIERAS**

In [ ]:
# recorte. seleccion de columnas necesarias
columnas_raw = [ "a0000", "a0400", "a04" ,"e0100", "e0500", "e0600", "e0700", "e0800", "e0900", "e1001", "e1002", "e1003", "e1004",]

df = df_raw.loc[:, columnas_raw]


## Renombras columnas

df = df.rename(columns={
    #socio-demo
    "a0000" : "género",             #[1= Male , 0 = Female, -98 = otros]
    "a0400" : "anio_nac",
    "a04"   : "edad" ,
    
    ####################
    # competencias financieras
    ## Respuestas: no sabe (-97), se niega a responder (-99). respuesta irrelevante (-999).

    "e0100" : "autoevaluacion",     # 1 = muy alto,  2 = bastante alto, 3 = promedio, 4 = bastante bajo, 5 = muy bajo.
    "e0500" : "division_simple" ,   # respuesta correcta: 200 __ valor numérico abierto. 
    "e0600" : "inflacion",          # respuesta correcta: 3 y 4. ## Ranking 1 a 4.  Código especial: -5
    "e0700" : "interes-prestamo",   # respuesta correcta: 0 ## Código especial: -5
    "e0800" : "interes-simple",     # respuesta correcta: 102  __ valor numérico abierto.
    "e0900" : "interes-compuesto",  # resp correcta 1    #Código especial: -5  

    "e1001" : "riesgo_a",           # todas siguientes son afirmaciones verdadero = 1 / falso = 0
    "e1002" : "riesgo_b", 
    "e1003" : "riesgo_c",           # resp correcta 1    #Código especial: -5  
    "e1004" : "riesgo_d",
    })
    

# ver tabla
df.head(10)

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
0,0,1982,40,3,200.0,1,0.0,120.0,2,1,1,-97,1
1,0,1967,54,3,200.0,3,0.0,100.0,-97,-97,1,-97,0
2,1,1967,54,3,200.0,3,0.0,102.0,1,1,1,1,-98
3,1,1974,48,3,200.0,2,0.0,102.0,2,1,1,-97,-97
4,1,1972,49,1,-97.0,3,0.0,-97.0,-97,-97,1,-97,-97
5,1,1960,61,3,250.0,3,0.0,110.0,1,1,1,1,-98
6,0,1973,48,4,200.0,3,0.0,102.0,1,1,1,1,-98
7,1,1986,36,1,-97.0,1,0.0,-97.0,4,1,1,-97,-97
8,1,1969,52,1,200.0,-5,0.0,-5.0,-97,1,1,0,-98
9,1,1982,40,3,225.0,2,0.0,102.0,4,1,1,1,-98

In [41]:
# ver total registros / total columnas y datatype.

print(f"Registros: {len(df)}")
print(f"Columnas: {df.shape[1]}")
print("\nTipos de datos:")
print(df.dtypes)

Registros: 7764
Columnas: 13

Tipos de datos:
género                 int64
anio_nac               int64
edad                   int64
autoevaluacion         int64
division_simple      float64
inflacion              int64
interes-prestamo     float64
interes-simple       float64
interes-compuesto      int64
riesgo_a               int64
riesgo_b               int64
riesgo_c               int64
riesgo_d               int64
dtype: object

In [42]:
# Min/Max de variables

display(df.select_dtypes(include='number').agg(['min', 'max'])) #seleccion por datatype NUMERO

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
min,0,-99,-98,-99,-99.0,-99,-99.0,-99.0,-99,-99,-99,-99,-99
max,1,2003,80,5,170000.0,4,500.0,12500.0,4,1,1,1,1

## validaciones codigos especiales

In [ ]:
print("\n autoevaluacion")
df["autoevaluacion" ].value_counts(dropna=False)

# validación codigos especiales
# -97       4
# -99       1

 autoevaluacion

 3     3624
 2     2305
 1     1150
 4      598
 5       82
-97       4
-99       1
Name: autoevaluacion, dtype: int64

In [81]:
print("\n division_simple")
df["division_simple" ].value_counts(dropna=False).head(10)

#respuesta correcta 200  
# # cantidad de aciertos: 6574

 division_simple

 200.0     6574
-97.0       301
 250.0      260
 1000.0     198
 175.0       43
 225.0       36
 150.0       32
 2000.0      31
 100.0       25
 500.0       24
Name: division_simple, dtype: int64

In [ ]:
print("\n inflacion")
df["inflacion" ].value_counts(dropna=False)

#respuesta correcta 3. 
# codigos especialess
# -97     523
# -5       49
# -99      11

 inflacion

 3     5250
 1     1110
 2      810
-97     523
-5       49
 4       11
-99      11
Name: inflacion, dtype: int64

In [79]:
print("\n interes-prestamo")
df["interes-prestamo" ].value_counts(dropna=False).head(5)

# respuesta correcta 0. 
# cantidad de aciertos: 7588

 interes-prestamo

 0.0      7588
-97.0       84
-5.0        22
 100.0      11
 25.0       10
Name: interes-prestamo, dtype: int64

In [ ]:
print("\n interes-simple")
df["interes-simple" ].value_counts(dropna=False).head(5)

# respuesta correcta : 102
# cantidad de aciertos: 4208

 interes-simple

 102.0    4208
-97.0     1425
 120.0     884
 100.0     182
 200.0     110
Name: interes-simple, dtype: int64

In [ ]:
print("\n interes-compuesto")
df["interes-compuesto" ].value_counts(dropna=False) #.head(5)

# respuesta correcta: 1
# codigos especiales:
# -97     788
# -5       65
# -99      45

 interes-compuesto

 1     3344
 2     2301
-97     788
 4      643
 3      578
-5       65
-99      45
Name: interes-compuesto, dtype: int64

In [ ]:
print("\n riesgo_a	")
df["riesgo_a" ].value_counts(dropna=False) #.head(5)

# respuesta correcta: 1
# codigos especiales:
# -97     425
# -99       4

 riesgo_a

 1     6720
 0      615
-97     425
-99       4
Name: riesgo_a, dtype: int64

In [ ]:
print("\n riesgo_b	")
df["riesgo_b" ].value_counts(dropna=False) #.head(5)

# respuesta correcta: 1
# codigos especiales:
# -97     280
# -99       1

 riesgo_b

 1     7023
 0      460
-97     280
-99       1
Name: riesgo_b, dtype: int64

____

_____

## reemplazar códigos especiales

In [149]:
# códigos especiales [-97, -98, -99, -999,] - CONTEO CANTIDAD

codigos_especiales = [-97, -98, -99, -999,]

columnas = [ "edad",
    "autoevaluacion", "division_simple", "inflacion",
    "interes-prestamo", "interes-simple", "interes-compuesto",
    "riesgo_a", "riesgo_b", "riesgo_c", "riesgo_d"
]

# tabla de conteo suma de codigos especiales
resumen_codigos = pd.DataFrame({
    col: df[col].value_counts().reindex(codigos_especiales).fillna(0).astype(int)
    for col in columnas
}).T
resumen_codigos.columns = ["no_sabe_-97", "no_aplica_-98", "se_niega_-99", "irrelevante_-999",]
resumen_codigos["total_especiales"] = resumen_codigos.sum(axis=1)

display(resumen_codigos)

,no_sabe_-97,no_aplica_-98,se_niega_-99,irrelevante_-999,total_especiales
edad,0,9,0,0,9
autoevaluacion,0,0,0,0,0
division_simple,0,0,0,0,0
inflacion,0,0,0,0,0
interes-prestamo,0,0,0,0,0
interes-simple,0,0,0,0,0
interes-compuesto,0,0,0,0,0
riesgo_a,0,0,0,0,0
riesgo_b,0,0,0,0,0
riesgo_c,0,0,0,0,0
riesgo_d,0,0,0,0,0

In [150]:
# reemmplazar por NAN ## [-97, -98, -99, -999,]
df[columnas] = df[columnas].replace(codigos_especiales, pd.NA) 

df[columnas].head(5)

,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
0,40,3,200.0,1,0.0,120.0,2,1,1,<NA>,1
1,54,3,200.0,3,0.0,100.0,<NA>,<NA>,1,<NA>,0
2,54,3,200.0,3,0.0,102.0,1,1,1,1,<NA>
3,48,3,200.0,2,0.0,102.0,2,1,1,<NA>,<NA>
4,49,1,<NA>,3,0.0,<NA>,<NA>,<NA>,1,<NA>,<NA>

In [45]:
# códigos especial -5 sólo en inflacion  - Interes prestamo  -  Interes compuesto 
### e0600 - e0900 - e1003 raw data _ ver documentacion:  variables_informe 

cod_esp = [-5]

columnas_esp= [ "inflacion", "interes-compuesto", "riesgo_c"]  

# tabla de conteo 
resumen_codigos = pd.DataFrame({
    col: df[col].value_counts().reindex(cod_esp).fillna(0).astype(int)
    for col in columnas_esp
}).T
resumen_codigos.columns = ["desconocido_-5"]


display(resumen_codigos)

                   desconocido_-5
inflacion                      49
interes-compuesto              65
riesgo_c                       17

In [46]:
df[columnas_esp] = df[columnas_esp].replace(cod_esp, pd.NA)  # reemplazar # códigos especial -5 


display(df[columnas_esp].head(10))

display(df["inflacion" ].value_counts(dropna=False))

  inflacion interes-compuesto riesgo_c
0         1                 2     <NA>
1         3              <NA>     <NA>
2         3                 1        1
3         2                 2     <NA>
4         3              <NA>     <NA>
5         3                 1        1
6         3                 1        1
7         1                 4     <NA>
8      <NA>              <NA>        0
9         2                 4        1

3.0    5250
1.0    1110
2.0     810
NaN     583
4.0      11
Name: inflacion, dtype: int64

In [47]:
display(df[columnas].describe()) ## columnas "object"

display(df_num.describe()) ## columnas numéricas

,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
count,7759,7450.0,7181,7673.0,6303.0,6866,7335,7483,6292,988
unique,5,77.0,4,16.0,116.0,4,2,2,2,3
top,3,200.0,3,0.0,102.0,1,1,1,1,1
freq,3624,6574.0,5250,7588.0,4208.0,3344,6720,7023,4137,566

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
count,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000,7764.000000
mean,0.518805,1971.818135,46.773570,2.440366,253.175837,-4.320067,-0.754748,90.195629,-8.882535,-4.495234,-2.606388,-17.658295,-85.412030
std,0.499678,72.246051,16.393713,2.681115,1951.025418,25.217895,14.124925,301.189471,30.607286,22.378994,18.295952,38.113539,32.795477
min,0.000000,-99.000000,-98.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,0.000000,1962.000000,35.000000,2.000000,200.000000,2.000000,0.000000,100.000000,1.000000,1.000000,1.000000,0.000000,-98.000000
50%,1.000000,1974.000000,47.000000,3.000000,200.000000,3.000000,0.000000,102.000000,1.000000,1.000000,1.000000,1.000000,-98.000000
75%,1.000000,1986.000000,59.000000,3.000000,200.000000,3.000000,0.000000,102.000000,2.000000,1.000000,1.000000,1.000000,-98.000000
max,1.000000,2003.000000,80.000000,5.000000,170000.000000,4.000000,500.000000,12500.000000,4.000000,1.000000,1.000000,1.000000,1.000000

In [48]:
display(df.select_dtypes(include='number').agg(['min', 'max'])) #seleccion por datatype NUMERO

     género  anio_nac  edad
min       0       -99   -98
max       1      2003    80

In [49]:
display(df[columnas_esp].head(10))

  inflacion interes-compuesto riesgo_c
0         1                 2     <NA>
1         3              <NA>     <NA>
2         3                 1        1
3         2                 2     <NA>
4         3              <NA>     <NA>
5         3                 1        1
6         3                 1        1
7         1                 4     <NA>
8      <NA>              <NA>        0
9         2                 4        1

In [29]:
display(df.head(5))

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
0,0,1982,40,3,200.0,1,0.0,120.0,2,1,1,<NA>,1
1,0,1967,54,3,200.0,3,0.0,100.0,<NA>,<NA>,1,<NA>,0
2,1,1967,54,3,200.0,3,0.0,102.0,1,1,1,1,<NA>
3,1,1974,48,3,200.0,2,0.0,102.0,2,1,1,<NA>,<NA>
4,1,1972,49,1,<NA>,3,0.0,<NA>,<NA>,<NA>,1,<NA>,<NA>

___

In [ ]:
## DESCRIBE SIN CODIGOS ESPECIALES

columnas = [ 
    "autoevaluacion", "division_simple", "inflacion",
    "interes-prestamo", "interes-simple", "interes-compuesto",
    "riesgo_a", "riesgo_b", "riesgo_c", "riesgo_d"
]
columnas_esp = ["inflacion", "interes-compuesto", "riesgo_c"]

codigos_especiales = [-97, -98, -99, -999]
cod_esp = [-5]

resultados = {}
for col in columnas:
    excluir = codigos_especiales + (cod_esp if col in columnas_esp else [])
    serie = df_num[col]
    serie_valida = serie[~serie.isin(excluir)]
    resultados[col] = serie_valida.describe()

df_describe = pd.DataFrame(resultados).T
display(df_describe)

,count,mean,std,min,25%,50%,75%,max
autoevaluacion,7759.0,2.504704,0.874105,1.0,2.0,3.0,3.0,5.0
division_simple,7450.0,267.938416,1990.368653,-5.0,200.0,200.0,200.0,170000.0
inflacion,7181.0,2.579585,0.745625,1.0,2.0,3.0,3.0,4.0
interes-prestamo,7673.0,0.388523,9.504984,-5.0,0.0,0.0,0.0,500.0
interes-simple,6303.0,133.597947,318.956813,-5.0,102.0,102.0,102.0,12500.0
interes-compuesto,6866.0,1.784445,0.948413,1.0,1.0,2.0,2.0,4.0
riesgo_a,7335.0,0.916155,0.277173,0.0,1.0,1.0,1.0,1.0
riesgo_b,7483.0,0.938527,0.240211,0.0,1.0,1.0,1.0,1.0
riesgo_c,6292.0,0.657502,0.474583,0.0,0.0,1.0,1.0,1.0
riesgo_d,988.0,0.461538,0.957844,-5.0,0.0,1.0,1.0,1.0

In [296]:
display(df_num.head(10))

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d
0,0,1982,40,3,200.0,1,0.0,120.0,2,1,1,-97,1
1,0,1967,54,3,200.0,3,0.0,100.0,-97,-97,1,-97,0
2,1,1967,54,3,200.0,3,0.0,102.0,1,1,1,1,-98
3,1,1974,48,3,200.0,2,0.0,102.0,2,1,1,-97,-97
4,1,1972,49,1,-97.0,3,0.0,-97.0,-97,-97,1,-97,-97
5,1,1960,61,3,250.0,3,0.0,110.0,1,1,1,1,-98
6,0,1973,48,4,200.0,3,0.0,102.0,1,1,1,1,-98
7,1,1986,36,1,-97.0,1,0.0,-97.0,4,1,1,-97,-97
8,1,1969,52,1,200.0,-5,0.0,-5.0,-97,1,1,0,-98
9,1,1982,40,3,225.0,2,0.0,102.0,4,1,1,1,-98

_____
_____

## RANKING

### EVALUAR RESPUESTAS x cada colummna

In [68]:
### FUNCIÓN evaluar_ TEST DE LA FUNCIÓN
def evaluar_correcta_simple(serie, valores_correctos):
    """Devuelve 1 si el valor está en valores_correctos, 0 si no, NaN si la celda es NaN."""
    return serie.where(serie.isna(), serie.isin(valores_correctos).astype(int))

In [ ]:
# Prueba: serie con un valor correcto (3), incorrectos (1, 2) y un NaN
serie_prueba = pd.Series([3, 1, np.nan, 4, 2])
display(evaluar_correcta_simple(serie_prueba, [3, 4])) ## valores correctos 3, 4

In [69]:
### FUNCIÓN  

def evaluar_interes_compuesto(serie_compuesto, serie_correcta_simple):
    """Correcto (1) solo si el valor es 1 y además interes-simple fue correcta. NaN si el valor es NaN."""
    return serie_compuesto.where(
        serie_compuesto.isna(),
        ((serie_compuesto == 1) & (serie_correcta_simple == 1)).astype(int)
    )

In [ ]:
# Prueba: compuesto correcto+simple correcta, compuesto correcto+simple incorrecta (dependencia),
# compuesto incorrecto, y compuesto NaN
serie_compuesto = pd.Series([1, 1, 2, np.nan])
serie_simple_correcta = pd.Series([1, 0, 1, 1])
display(evaluar_interes_compuesto(serie_compuesto, serie_simple_correcta))

0    1.0
1    0.0
2    0.0
3    NaN
dtype: float64

In [71]:
### EVALUACIÓN POR COLUMNA

df["correcta_division_simple"] = evaluar_correcta_simple(df["division_simple"], [200])
df["correcta_inflacion"] = evaluar_correcta_simple(df["inflacion"], [3, 4])
df["correcta_interes_prestamo"] = evaluar_correcta_simple(df["interes-prestamo"], [0])
df["correcta_interes_simple"] = evaluar_correcta_simple(df["interes-simple"], [102])
df["correcta_riesgo_a"] = evaluar_correcta_simple(df["riesgo_a"], [1])
df["correcta_riesgo_b"] = evaluar_correcta_simple(df["riesgo_b"], [1])
df["correcta_riesgo_c"] = evaluar_correcta_simple(df["riesgo_c"], [1])
df["correcta_riesgo_d"] = evaluar_correcta_simple(df["riesgo_d"], [1])

In [72]:
#### aplicar interes-compuesto, que depende de correcta_interes_simple ya calculada en la celda anterior

df["correcta_interes_compuesto"] = evaluar_interes_compuesto(df["interes-compuesto"], df["correcta_interes_simple"])

In [ ]:
### ver df

display(df[["division_simple", "correcta_division_simple",
            "inflacion", "correcta_inflacion",
            "interes-prestamo", "correcta_interes_prestamo",
            "interes-simple", "correcta_interes_simple",
            "interes-compuesto", "correcta_interes_compuesto",
            "riesgo_a", "correcta_riesgo_a",
            "riesgo_b", "correcta_riesgo_b",
            "riesgo_c", "correcta_riesgo_c",
            "riesgo_d", "correcta_riesgo_d"]].head(10))

,division_simple,correcta_division_simple,inflacion,correcta_inflacion,interes-prestamo,correcta_interes_prestamo,interes-simple,correcta_interes_simple,interes-compuesto,correcta_interes_compuesto,riesgo_a,correcta_riesgo_a,riesgo_b,correcta_riesgo_b,riesgo_c,correcta_riesgo_c,riesgo_d,correcta_riesgo_d
0,200.0,1,1,0,0.0,1,120.0,0,2,0,1,1,1,1,<NA>,<NA>,1,1
1,200.0,1,3,1,0.0,1,100.0,0,<NA>,<NA>,<NA>,<NA>,1,1,<NA>,<NA>,0,0
2,200.0,1,3,1,0.0,1,102.0,1,1,1,1,1,1,1,1,1,<NA>,<NA>
3,200.0,1,2,0,0.0,1,102.0,1,2,0,1,1,1,1,<NA>,<NA>,<NA>,<NA>
4,<NA>,<NA>,3,1,0.0,1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1,1,<NA>,<NA>,<NA>,<NA>
5,250.0,0,3,1,0.0,1,110.0,0,1,0,1,1,1,1,1,1,<NA>,<NA>
6,200.0,1,3,1,0.0,1,102.0,1,1,1,1,1,1,1,1,1,<NA>,<NA>
7,<NA>,<NA>,1,0,0.0,1,<NA>,<NA>,4,0,1,1,1,1,<NA>,<NA>,<NA>,<NA>
8,200.0,1,<NA>,<NA>,0.0,1,-5.0,0,<NA>,<NA>,1,1,1,1,0,0,<NA>,<NA>
9,225.0,0,2,0,0.0,1,102.0,1,4,0,1,1,1,1,1,1,<NA>,<NA>

In [82]:
## función CALCULAR SCORE

def calcular_score(df, columnas):
    """Suma las columnas indicadas fila por fila, tratando NaN como 0."""
    return df[columnas].fillna(0).sum(axis=1).astype(int)

In [201]:
## aplicar función a cada columna

columnas_score_oficial = [
    "correcta_inflacion",
    "correcta_interes_prestamo",
    "correcta_interes_simple",
    "correcta_interes_compuesto",
    "correcta_riesgo_a",
    "correcta_riesgo_c",
    "correcta_riesgo_d",
]

df["score_conocimiento_0_7"] = calcular_score(df, columnas_score_oficial)


## resultados

display(df[columnas_score_oficial + ["score_conocimiento_0_7"]].head(10))

,correcta_inflacion,correcta_interes_prestamo,correcta_interes_simple,correcta_interes_compuesto,correcta_riesgo_a,correcta_riesgo_c,correcta_riesgo_d,score_conocimiento_0_7
0,0,1,0,0,1,<NA>,1,3
1,1,1,0,<NA>,<NA>,<NA>,0,2
2,1,1,1,1,1,1,<NA>,6
3,0,1,1,0,1,<NA>,<NA>,3
4,1,1,<NA>,<NA>,<NA>,<NA>,<NA>,2
5,1,1,0,0,1,1,<NA>,4
6,1,1,1,1,1,1,<NA>,6
7,0,1,<NA>,0,1,<NA>,<NA>,2
8,<NA>,1,0,<NA>,1,0,<NA>,2
9,0,1,1,0,1,1,<NA>,4

In [202]:
### ver resultados: EDAD Y SCORE

display(df[["edad","score_conocimiento_0_7"]].head(10))

  edad  score_conocimiento_0_7
0   40                       3
1   54                       2
2   54                       6
3   48                       3
4   49                       2
5   61                       4
6   48                       6
7   36                       2
8   52                       2
9   40                       4

In [ ]:
## DF SÓLO EDAD Y SCORE
df_edad_score = df[["edad","score_conocimiento_0_7"]]

display(df_edad_score.head(10))

   edad  score_conocimiento_0_7
0    40                       3
1    54                       2
2    54                       6
3    48                       3
4    49                       2
5    61                       4
6    48                       6
7    36                       2
8    52                       2
9    40                       4

______

### ranking: alto , medio, bajo

In [92]:
## función CLASIFICAR
def clasificar_ranking(score):
    """Clasifica el score 0-7 en bajo (0-3), medio (4-5) o alto (6-7)."""
    if score <= 3:
        return "bajo"
    elif score <= 5:
        return "medio"
    return "alto"

In [95]:
df["ranking_conocimiento"] = df["score_conocimiento_0_7"].apply(clasificar_ranking)
display(df[["score_conocimiento_0_7", "ranking_conocimiento"]].head(10))

   score_conocimiento_0_7 ranking_conocimiento
0                       3                 bajo
1                       2                 bajo
2                       6                 alto
3                       3                 bajo
4                       2                 bajo
5                       4                medio
6                       6                 alto
7                       2                 bajo
8                       2                 bajo
9                       4                medio

In [96]:
display(df.head(10))

,género,anio_nac,edad,autoevaluacion,division_simple,inflacion,interes-prestamo,interes-simple,interes-compuesto,riesgo_a,riesgo_b,riesgo_c,riesgo_d,correcta_inflacion,correcta_interes_prestamo,correcta_interes_simple,correcta_riesgo_a,correcta_division_simple,correcta_riesgo_b,correcta_riesgo_c,correcta_riesgo_d,correcta_interes_compuesto,score_conocimiento_0_7,ranking_conocimiento
0,0,1982,40,3,200.0,1,0.0,120.0,2,1,1,<NA>,1,0,1,0,1,1,1,<NA>,1,0,3,bajo
1,0,1967,54,3,200.0,3,0.0,100.0,<NA>,<NA>,1,<NA>,0,1,1,0,<NA>,1,1,<NA>,0,<NA>,2,bajo
2,1,1967,54,3,200.0,3,0.0,102.0,1,1,1,1,<NA>,1,1,1,1,1,1,1,<NA>,1,6,alto
3,1,1974,48,3,200.0,2,0.0,102.0,2,1,1,<NA>,<NA>,0,1,1,1,1,1,<NA>,<NA>,0,3,bajo
4,1,1972,49,1,<NA>,3,0.0,<NA>,<NA>,<NA>,1,<NA>,<NA>,1,1,<NA>,<NA>,<NA>,1,<NA>,<NA>,<NA>,2,bajo
5,1,1960,61,3,250.0,3,0.0,110.0,1,1,1,1,<NA>,1,1,0,1,0,1,1,<NA>,0,4,medio
6,0,1973,48,4,200.0,3,0.0,102.0,1,1,1,1,<NA>,1,1,1,1,1,1,1,<NA>,1,6,alto
7,1,1986,36,1,<NA>,1,0.0,<NA>,4,1,1,<NA>,<NA>,0,1,<NA>,1,<NA>,1,<NA>,<NA>,0,2,bajo
8,1,1969,52,1,200.0,<NA>,0.0,-5.0,<NA>,1,1,0,<NA>,<NA>,1,0,1,1,1,0,<NA>,<NA>,2,bajo
9,1,1982,40,3,225.0,2,0.0,102.0,4,1,1,1,<NA>,0,1,1,1,0,1,1,<NA>,0,4,medio

In [101]:
## DF SÓLO EDAD Y RANKING

df_ranking = df[["edad","ranking_conocimiento"]]

display(df_ranking.head(10))

   edad ranking_conocimiento
0    40                 bajo
1    54                 bajo
2    54                 alto
3    48                 bajo
4    49                 bajo
5    61                medio
6    48                 alto
7    36                 bajo
8    52                 bajo
9    40                medio

_______
_______

## VISUALIZACIONES

In [110]:
# imports gráficos
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go

# DarkMode Plotly
pio.templates.default = "plotly_dark"
from plotly.subplots import make_subplots # permite visualizar varios gráficos

pio.templates["custom"] = pio.templates["plotly_dark"]
pio.templates["custom"].layout.paper_bgcolor = "#050a30"
pio.templates["custom"].layout.plot_bgcolor  = "#050a30"
pio.templates.default = "custom"

In [131]:
## función CONTAR TOTAL x ranking

def contar_por_ranking(df):
    """Cuenta cuántas personas hay en cada categoría de ranking_conocimiento."""
    return df["ranking_conocimiento"].value_counts().rename_axis("ranking_conocimiento").reset_index(name="cantidad")

In [238]:
### CHART PIE / cantidad de personas por ranking de conocimiento financiero

ranking_conteo = contar_por_ranking(df)

colores_ranking = {
    "alto": "seagreen",
    "medio": "darkseagreen",
    "bajo": "sandybrown",
}

fig_pie = px.pie(
    ranking_conteo,
    values="cantidad",
    names="ranking_conocimiento",
    color="ranking_conocimiento",
    color_discrete_map=colores_ranking,
    title='Conocimiento financiero, cantidad de personas',
    category_orders={"ranking_conocimiento": ["alto", "medio", "bajo"]},
)

fig_pie.update_traces(
    texttemplate="%{percent:.0%}",
    textposition="auto",
    textfont=dict(size=20, color="#050a30", ),
)


fig_pie.show()

In [237]:
## función para contar personas por edad y ranking
def contar_por_edad_y_ranking(df):
    """Cuenta cuántas personas hay por cada combinación de edad y ranking_conocimiento."""
    return df.groupby(["edad", "ranking_conocimiento"]).size().reset_index(name="cantidad") #agrupar por edad y resultado

edad_ranking_conteo = contar_por_edad_y_ranking(df)

colores_ranking = {
    "alto": "seagreen",
    "medio": "darkseagreen",
    "bajo": "sandybrown",
}

# grafico de barras
fig_edad = px.bar(edad_ranking_conteo, 
                  x="edad", 
                  y="cantidad", 
                  color="ranking_conocimiento",
                  color_discrete_map=colores_ranking,
                  category_orders={"ranking_conocimiento": ["alto", "medio", "bajo"]},)
fig_edad.show()

______
### Rangos por edad

18-30 : jovenes, 
31-40 : adultos-jovenes, 
41-50 : adultos, 
51-60 : senior, 
61-80 : senior-mayores

In [292]:
## función pandas cut, cortar por rangos

def asignar_age_bracket(serie_edad):
    """Clasifica la edad en bracket: jovenes, adultos-jovenes, adultos, senior, mayores. NaN si la edad es NaN."""
    bordes = [17, 30, 40, 50, 60, 80]
    etiquetas = ["jovenes", "adultos-jovenes", "adultos", "senior", "mayores"]
    return pd.cut(pd.to_numeric(serie_edad, errors="coerce"), bins=bordes, labels=etiquetas)


## columna rango-edad
df["rango_edad"] = asignar_age_bracket(df["edad"])

## ver
display(df[["edad", "rango_edad"]].head(10))

  edad       rango_edad
0   40  adultos-jovenes
1   54           senior
2   54           senior
3   48          adultos
4   49          adultos
5   61          mayores
6   48          adultos
7   36  adultos-jovenes
8   52           senior
9   40  adultos-jovenes

### Porcentajes por bracket de edad: 
dentro de cada grupo de edad, qué proporción es alto/medio/bajo (cada barra suma 100%).

In [294]:
## función group by personas por cada combinación de rango_edad y ranking_conocimiento
def contar_por_bracket_y_ranking(df):
    """Cuenta personas por cada combinación de rango_edad y ranking_conocimiento."""
    return df.groupby(["rango_edad", "ranking_conocimiento"]).size().reset_index(name="cantidad")



### función convertir la cantidad en porcentaje  
def calcular_porcentaje_por_bracket(conteo):
    """Convierte la cantidad en porcentaje dentro de cada rango_edad (cada bracket suma 100%)."""
    return conteo.assign(porcentaje=conteo["cantidad"] / conteo.groupby("rango_edad")["cantidad"].transform("sum") * 100)


## aplicar funciones
bracket_ranking_porcentaje = calcular_porcentaje_por_bracket(contar_por_bracket_y_ranking(df))


## gráfico BARRAS
fig_rangos_edad = px.bar(
    bracket_ranking_porcentaje,
    x="rango_edad",
    y="porcentaje",
    color="ranking_conocimiento",
    color_discrete_map=colores_ranking,
    category_orders={"ranking_conocimiento": ["bajo", "medio", "alto"]},
    text="porcentaje",
    )
fig_rangos_edad.update_traces(
    textposition="auto",
    textfont=dict(size=20, color="#050a30", ),
    )
fig_rangos_edad.update_traces(texttemplate="%{text:.0f}%")
fig_rangos_edad.show()

_______
_______

### DETALLE DEL RANKING "ALTO"

In [204]:
## función filtrar sólo ranking
def filtrar_por_ranking(df, ranking):
    """Filtra el dataframe dejando solo las filas con el ranking_conocimiento indicado."""
    return df[df["ranking_conocimiento"] == ranking]


## función resumen estadístico
def resumen_estadistico_edad(df):
    """Devuelve media, mediana, mínimo y máximo de la columna edad."""
    return df["edad"].agg(["mean", "median", "min", "max"])


## aplicar funciones
df_alto = filtrar_por_ranking(df, "alto")
display(resumen_estadistico_edad(df_alto))

mean      47.11901
median    48.00000
min       18.00000
max       80.00000
Name: edad, dtype: float64

In [206]:
## gráfico

fig_hist_alto = px.histogram(
    df_alto,
    x="edad",
    nbins=20,
    color_discrete_sequence=["seagreen"],
    title="Distribución de edades, ranking de conocimiento financiero alto",
)
fig_hist_alto.show()

insights:
vemos 40 a 54 predominan en el ranking "alto"

In [214]:
def resumen_score_por_bracket(df):
    """Calcula media, mediana y desviación estándar del score por cada rango de edad."""
    return df.groupby("rango_edad")["score_conocimiento_0_7"].agg(["mean", "median", "std", "count"])

display(resumen_score_por_bracket(df))

                     mean  median       std  count
rango_edad
jovenes          3.724138     4.0  1.366981   1450
adultos-jovenes  3.922824     4.0  1.376151   1218
adultos          4.075715     4.0  1.377382   1783
senior           4.073156     4.0  1.366782   1613
mayores          3.769367     4.0  1.431690   1691

In [293]:
## función

def media_score_por_bracket(df):
    """Calcula la media del score de conocimiento financiero por cada rango de edad."""
    return df.groupby("rango_edad")["score_conocimiento_0_7"].mean().reset_index(name="score_promedio")

## orden grupo de edades
orden_brackets = ["jovenes", "adultos-jovenes", "adultos", "senior", "mayores"]

media_bracket = media_score_por_bracket(df).assign(
    rango_edad=lambda d: pd.Categorical(d["rango_edad"], categories=orden_brackets, ordered=True)
).sort_values("rango_edad")


#gráfico
fig_line = px.line(
    media_bracket,
    x="rango_edad",
    y="score_promedio",
    markers=True,
    title="Score promedio de conocimiento financiero por rango de edad",
    text="score_promedio",
    
)
fig_line.update_yaxes(range=[3.5, 4.5])
fig_line.update_traces(texttemplate="%{text:.2f}", textfont_size=16,  )
fig_line.show()

Insights. La media en todos los grupos es bastante cerca:
Aquí hacemos zoom para ver las medias

____
___

#### Analizar en detalle son: inflacion, interes-compuesto, riesgo_d, 
columna de acierto: correcta_inflacion, correcta_interes_compuesto, correcta_riesgo_d.

In [243]:
### distribución de acierto por rango_edad


## función para calcular tasa de acierto por bracket
def tasa_acierto_por_bracket(df, columna_correcta):
    """Calcula el porcentaje de acierto de una columna correcta_* dentro de cada rango_edad."""
    return df.groupby("rango_edad")[columna_correcta].mean().mul(100).reset_index(name="porcentaje_acierto")


## unir en un  dataframe
variables_detalle = ["correcta_inflacion", "correcta_interes_compuesto", "correcta_riesgo_d"]


acierto_por_bracket = pd.concat(
    [tasa_acierto_por_bracket(df, col).assign(variable=col) for col in variables_detalle],
    ignore_index=True,
)

display(acierto_por_bracket.head(20))

         rango_edad  porcentaje_acierto                    variable
0           jovenes           66.641791          correcta_inflacion
1   adultos-jovenes           66.197183          correcta_inflacion
2           adultos           73.724792          correcta_inflacion
3            senior           77.432164          correcta_inflacion
4           mayores           79.760320          correcta_inflacion
5           jovenes           26.100386  correcta_interes_compuesto
6   adultos-jovenes           28.330373  correcta_interes_compuesto
7           adultos           31.101643  correcta_interes_compuesto
8            senior           29.705056  correcta_interes_compuesto
9           mayores           24.672489  correcta_interes_compuesto
10          jovenes           58.641975           correcta_riesgo_d
11  adultos-jovenes           63.576159           correcta_riesgo_d
12          adultos           61.016949           correcta_riesgo_d
13           senior           51.643192           correcta_riesgo_d
14          mayores           53.777778           correcta_riesgo_d

In [295]:
## gráfico de conceptos financieros

orden_brackets = ["jovenes", "adultos-jovenes", "adultos", "senior", "mayores"]

nombres_variables = {
    "correcta_inflacion": "Inflación",
    "correcta_interes_compuesto": "Interés compuesto",
    "correcta_riesgo_d": "Diversificación de riesgo",
}

colores_variables = {
    "Inflación": "powderblue",
    "Interés compuesto": "thistle",
    "Diversificación de riesgo": "khaki",
}

acierto_por_bracket_ordenado = acierto_por_bracket.assign(
    rango_edad=lambda d: pd.Categorical(d["rango_edad"], categories=orden_brackets, ordered=True),
    variable=lambda d: d["variable"].map(nombres_variables),
).sort_values("rango_edad")


##grafico
fig_detalle = px.bar(
    acierto_por_bracket_ordenado,
    x="rango_edad",
    y="porcentaje_acierto",
    color="variable",
    color_discrete_map=colores_variables,
    category_orders={"variable": ["Inflación", "Diversificación de riesgo", "Interés compuesto"]},
    barmode="group",
    title="Porcentaje de acierto por conceptos financieros",
    labels={
        "rango_edad": "Rango de edad",
        "porcentaje_acierto": "Porcentaje de acierto",
        "variable": "Concepto financiero",
        },
    text="porcentaje_acierto",
)
fig_detalle.update_traces(texttemplate="%{text:.0f}%", textfont_size=16,)
fig_detalle.show()

_____
____