**Data Reduction**

Instalaciones

pip install mysql

Importaciones

In [11]:
import pandas as pd
import mysql.connector
import warnings

Conexión data

In [45]:
warnings.filterwarnings('ignore', message=".*pandas only supports SQLAlchemy connectable.*")

#Configuración de conexión
config = {
    'host': '212.227.90.6',
    'user': 'Equipo24',
    'password': 'E1q2u3i4p5o24',
    'database': 'Equip_24'
}

try:
    conn = mysql.connector.connect(**config) 
    cursor = conn.cursor()

    cursor.execute("SELECT database();")
    db_actual = cursor.fetchone()[0]
    print(f"--- Conectado con éxito a: {db_actual} ---\n")

    cursor.execute("SHOW TABLES;")
    tablas = cursor.fetchall()

    dataframes = {}

    for (tabla,) in tablas:
        try:
            print(f"Cargando tabla: {tabla}...")
            query = f"SELECT * FROM {tabla}"
            dataframes[tabla] = pd.read_sql(query, conn)
        except Exception as e:
            print(f"No se pudo cargar la tabla {tabla}: {e}")

    if 'RRHH' in dataframes:
        RRHH = dataframes['RRHH']
        print("\n" + "="*30)
        print("MUESTRA DE TABLA RRHH:")
        print("="*30)
        print(RRHH.head())
    else:
        print("\nLa tabla 'RRHH' no se encontró en la base de datos.")

except mysql.connector.Error as err:
    print(f"Error de conexión a MySQL: {err}")

#finally:
#    if 'conn' in locals() and conn.is_connected():
#        cursor.close()
#        conn.close()
#        print("\n--- Conexión cerrada correctamente ---")

--- Conectado con éxito a: Equip_24 ---

Cargando tabla: RRHH...

==============================
MUESTRA DE TABLA RRHH:
==============================
   ID  Reason_absence  Month_absence  Day_week  Seasons  \
0  14              11             11         2        4
1  36              13              4         4        3
2   9               6              7         3        1
3  28               9              7         3        1
4   9              12              3         3        2

   Transportation_expense  Distance_Residence_Work  Service_time  Age  \
0                     155                       12            14   34
1                     118                       13            18   50
2                     228                       14            16   58
3                     225                       26             9   28
4                     228                       14            16   58

  Work_load_Average_day  ...  Disciplinary_failure Education Son  \
0               284,031  ...                     0         1   2
1               239,409  ...                     0         1   1
2               264,604  ...                     0         1   2
3               230,290  ...                     0         1   1
4               222,196  ...                     0         1   2

  Social_drinker Social_smoker Pet Weight  Height  Body_mass_index  \
0              1             0   0     95     196               25
1              1             0   0     98     178               31
2              0             0   1     65     172               22
3              0             0   2     69     169               24
4              0             0   1     65     172               22

   Absenteeism_hours
0                120
1                120
2                120
3                112
4                112

[5 rows x 21 columns]

In [46]:
RRHH

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
0,14,11,11,2,4,155,12,14,34,"284,031",...,0,1,2,1,0,0,95,196,25,120
1,36,13,4,4,3,118,13,18,50,"239,409",...,0,1,1,1,0,0,98,178,31,120
2,9,6,7,3,1,228,14,16,58,"264,604",...,0,1,2,0,0,1,65,172,22,120
3,28,9,7,3,1,225,26,9,28,"230,290",...,0,1,1,0,0,2,69,169,24,112
4,9,12,3,3,2,228,14,16,58,"222,196",...,0,1,2,0,0,1,65,172,22,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,2,0,6,2,3,235,29,12,48,"275,089",...,1,1,1,0,1,5,88,163,33,0
736,21,0,6,2,3,268,11,8,33,"275,089",...,1,2,0,0,0,0,79,178,25,0
737,4,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",...,0,1,1,0,0,1,77,175,25,0

Eliminamos columnas Weight y Height

In [47]:
RRHH = RRHH.drop(columns=['Weight', 'Height'])

In [48]:
RRHH

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,Hit_target,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Body_mass_index,Absenteeism_hours
0,14,11,11,2,4,155,12,14,34,"284,031",97,0,1,2,1,0,0,25,120
1,36,13,4,4,3,118,13,18,50,"239,409",98,0,1,1,1,0,0,31,120
2,9,6,7,3,1,228,14,16,58,"264,604",93,0,1,2,0,0,1,22,120
3,28,9,7,3,1,225,26,9,28,"230,290",92,0,1,1,0,0,2,24,112
4,9,12,3,3,2,228,14,16,58,"222,196",99,0,1,2,0,0,1,22,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,2,0,6,2,3,235,29,12,48,"275,089",96,1,1,1,0,1,5,33,0
736,21,0,6,2,3,268,11,8,33,"275,089",96,1,2,0,0,0,0,25,0
737,4,0,0,3,1,118,14,13,40,"271,219",95,0,1,1,1,0,8,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",95,0,1,2,1,0,2,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",95,0,1,1,0,0,1,25,0

Eliminación de lineas duplicadas

In [50]:
print (RRHH.duplicated().sum())

34

In [51]:
RRHH=RRHH.drop_duplicates()

In [52]:
print (RRHH.duplicated().sum())

0

In [53]:
RRHH

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,Hit_target,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Body_mass_index,Absenteeism_hours
0,14,11,11,2,4,155,12,14,34,"284,031",97,0,1,2,1,0,0,25,120
1,36,13,4,4,3,118,13,18,50,"239,409",98,0,1,1,1,0,0,31,120
2,9,6,7,3,1,228,14,16,58,"264,604",93,0,1,2,0,0,1,22,120
3,28,9,7,3,1,225,26,9,28,"230,290",92,0,1,1,0,0,2,24,112
4,9,12,3,3,2,228,14,16,58,"222,196",99,0,1,2,0,0,1,22,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,2,0,6,2,3,235,29,12,48,"275,089",96,1,1,1,0,1,5,33,0
736,21,0,6,2,3,268,11,8,33,"275,089",96,1,2,0,0,0,0,25,0
737,4,0,0,3,1,118,14,13,40,"271,219",95,0,1,1,1,0,8,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",95,0,1,2,1,0,2,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",95,0,1,1,0,0,1,25,0

Queda pendiente poder encontrar la forma de añadir nueva columna con año de registro.