In [66]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv(r"C:\Personal\Susi\Bank Simulator\ECF files\04_Conocimientos_Financieros_2016_GEN.csv", sep=";")

# -----------------------------
# Create variables (BEFORE cleaning)
# -----------------------------
df = df.rename(columns={
    "e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...": "e0600",
    "e0900: cuanto dinero habra en la cuenta despues de cinco anios?": "e0900",
    "e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...": "e1003"
})
# e0600 (Inflation)
df["correct_e0600"] = df["e0600"].isin([3, 4]).astype(int)
df["dk_e0600"] = (df["e0600"] == -97).astype(int)
df["da_e0600"] = df["e0600"].isin([-99, -5]).astype(int)
df["incorrect_e0600"] = 1 - df["correct_e0600"] - df["dk_e0600"] - df["da_e0600"]

# e0900 (Compound interest)
df["correct_e0900"] = (df["e0900"] == 1).astype(int)
df["dk_e0900"] = (df["e0900"] == -97).astype(int)
df["da_e0900"] = df["e0900"].isin([-99, -5]).astype(int)
df["incorrect_e0900"] = 1 - df["correct_e0900"] - df["dk_e0900"] - df["da_e0900"]

# e1003 (Risk diversification)
df["correct_e1003"] = (df["e1003"] == 1).astype(int)
df["dk_e1003"] = (df["e1003"] == -97).astype(int)
df["da_e1003"] = df["e1003"].isin([-99, -5]).astype(int)
df["incorrect_e1003"] = 1 - df["correct_e1003"] - df["dk_e1003"] - df["da_e1003"]

# -----------------------------
# Clean missing values
# -----------------------------
df.replace([-97, -99, -5], pd.NA, inplace=True)
df.head(10)

# -----------------------------
# Save cleaned dataset
# -----------------------------
#df.to_csv("cleaned_dataset.csv", index=False)

#print("Cleaning complete. File saved as cleaned_dataset.csv")

,a01: anio de la entrevista,e0100: como calificaria sus conocimientos generales sobre temas financieros?,e0500: imagine que cinco hermanos reciben eur1000...?,e0600,e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0900,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,e1002: una inflacion elevada significa que el coste de la vida esta aumentando..,e1003,...,da_e0600,incorrect_e0600,correct_e0900,dk_e0900,da_e0900,incorrect_e0900,correct_e1003,dk_e1003,da_e1003,incorrect_e1003
0,2016,3,200,3,0,102.0,1,<NA>,1,<NA>,...,0,0,1,0,0,0,0,1,0,0
1,2016,3,200,3,0,102.0,2,1,1,1,...,0,0,0,0,0,1,1,0,0,0
2,2016,2,200,3,0,102.0,2,1,1,<NA>,...,0,0,0,0,0,1,0,1,0,0
3,2016,2,200,3,0,120.0,2,1,1,<NA>,...,0,0,0,0,0,1,0,1,0,0
4,2016,1,<NA>,3,0,102.0,<NA>,<NA>,<NA>,<NA>,...,0,0,0,1,0,0,0,1,0,0
5,2017,3,200,1,0,102.0,1,<NA>,1,1,...,0,1,1,0,0,0,1,0,0,0
6,2017,2,200,3,0,102.0,2,1,1,1,...,0,0,0,0,0,1,1,0,0,0
7,2017,3,200,3,0,120.0,2,1,1,1,...,0,0,0,0,0,1,1,0,0,0
8,2016,2,225,1,0,<NA>,<NA>,0,1,<NA>,...,0,1,0,1,0,0,0,1,0,0
9,2017,3,200,3,0,102.0,1,1,1,0,...,0,0,1,0,0,0,0,0,0,1

In [68]:
df = df.rename(columns={
   "e0600": "e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...",
   "e0900" :"e0900: cuanto dinero habra en la cuenta despues de cinco anios?" ,
   "e1003": "e1003: por lo general, es posible reducir el riesgo de invertir en bolsa..." 
})

In [70]:
df.head()

,a01: anio de la entrevista,e0100: como calificaria sus conocimientos generales sobre temas financieros?,e0500: imagine que cinco hermanos reciben eur1000...?,e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...,e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0900: cuanto dinero habra en la cuenta despues de cinco anios?,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,e1002: una inflacion elevada significa que el coste de la vida esta aumentando..,"e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...",...,da_e0600,incorrect_e0600,correct_e0900,dk_e0900,da_e0900,incorrect_e0900,correct_e1003,dk_e1003,da_e1003,incorrect_e1003
0,2016,3,200,3,0,102.0,1,<NA>,1,<NA>,...,0,0,1,0,0,0,0,1,0,0
1,2016,3,200,3,0,102.0,2,1,1,1,...,0,0,0,0,0,1,1,0,0,0
2,2016,2,200,3,0,102.0,2,1,1,<NA>,...,0,0,0,0,0,1,0,1,0,0
3,2016,2,200,3,0,120.0,2,1,1,<NA>,...,0,0,0,0,0,1,0,1,0,0
4,2016,1,<NA>,3,0,102.0,<NA>,<NA>,<NA>,<NA>,...,0,0,0,1,0,0,0,1,0,0

In [72]:
print(df.columns.tolist())

['a01: anio de la entrevista', 'e0100: como calificaria sus conocimientos generales sobre temas financieros?', 'e0500: imagine que cinco hermanos reciben eur1000...?', 'e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...', 'e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...', 'e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...', 'e0900: cuanto dinero habra en la cuenta despues de cinco anios?', 'e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo', 'e1002: una inflacion elevada significa que el coste de la vida esta aumentando..', 'e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...', 'e1101: que fondo obtuvo el mejor rendimiento al termino de los seis anios?', 'e1102: cual hubiera sido el fondo con mejor rendimiento en tres anios?', 'e1200: una hipoteca a 15 anios requiere normalmente pagos mensuales mas...', 'e0200a: durante que periodo cayeron los nacimientos? a.1957-1967', 'e0200b: durante que periodo cayeron los nacimientos? b.1967-1977', 'e0200c: durante que periodo cayeron los nacimientos? c.1977-1987', 'e0200d: durante que periodo cayeron los nacimientos? d.1987-1997', 'e0200e: durante que periodo cayeron los nacimientos? e.1997-2007', 'e0401: puede senialar en que frase del texto se indica...?', 'e0402: a que edad comenzo a participar cabaniero en competiciones de natacion?', 'e0403: elija la respuesta que mejor resume el texto que acaba de leer', 'e0300: imagine que para producir cinco aparatos se necesitan cinco maquinas...', 'correct_e0600', 'dk_e0600', 'da_e0600', 'incorrect_e0600', 'correct_e0900', 'dk_e0900', 'da_e0900', 'incorrect_e0900', 'correct_e1003', 'dk_e1003', 'da_e1003', 'incorrect_e1003']

In [74]:
cols_to_drop = [
    'a01: anio de la entrevista',
    'e0500: imagine que cinco hermanos reciben eur1000...?',
    'e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...',
    'e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...',
    
    'e0200a: durante que periodo cayeron los nacimientos? a.1957-1967',
    'e0200b: durante que periodo cayeron los nacimientos? b.1967-1977',
    'e0200c: durante que periodo cayeron los nacimientos? c.1977-1987',
    'e0200d: durante que periodo cayeron los nacimientos? d.1987-1997',
    'e0200e: durante que periodo cayeron los nacimientos? e.1997-2007',
    
    'e0401: puede senialar en que frase del texto se indica...?',
    'e0402: a que edad comenzo a participar cabaniero en competiciones de natacion?',
    'e0403: elija la respuesta que mejor resume el texto que acaba de leer',
    
    'e0300: imagine que para producir cinco aparatos se necesitan cinco maquinas...'
]

In [76]:
df = df.drop(columns=cols_to_drop)

In [78]:
# Dictionary mapping old column names to new Spanish titles
rename_dict = {
    'correct_e0600': 'Inflación - Correcto',
    'dk_e0600': 'Inflación - No sabe',
    'da_e0600': 'Inflación - No aplica',
    'incorrect_e0600': 'Inflación - Incorrecto',
    'correct_e0900': 'Interés Compuesto - Correcto',
    'dk_e0900': 'Interés Compuesto - No sabe',
    'da_e0900': 'Interés Compuesto - No aplica',
    'incorrect_e0900': 'Interés Compuesto - Incorrecto',
    'correct_e1003': 'Diversificación Riesgo - Correcto',
    'dk_e1003': 'Diversificación Riesgo - No sabe',
    'da_e1003': 'Diversificación Riesgo - No aplica',
    'incorrect_e1003': 'Diversificación Riesgo - Incorrecto'
}

# Rename columns in your DataFrame
df = df.rename(columns=rename_dict)

In [83]:

rename_dict1= {
    "e0100: como calificaria sus conocimientos generales sobre temas financieros?": "Autoevaluación del conocimiento financiero general",
    "e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...": "Toma de decisiones en un escenario financiero diferido (espera de un año)",
    "e0900: cuanto dinero habra en la cuenta despues de cinco anios?": "Cálculo del saldo de la cuenta después de cinco años",
    "e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo": "Reconocimiento de la relación entre alta rentabilidad y alto riesgo",
    "e1002: una inflacion elevada significa que el coste de la vida esta aumentando..": "Reconocimiento de la inflación como aumento del coste de vida",
    "e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...": "Reconocimiento de la reducción del riesgo mediante diversificación",
    "e1200: una hipoteca a 15 anios requiere normalmente pagos mensuales mas...": "Comprensión de pagos mensuales más altos en hipotecas a corto plazo",
    "e1101: que fondo obtuvo el mejor rendimiento al termino de los seis anios?": "Identificación del fondo con mejor rendimiento en seis años",
    "Inflación - Correcto": "Inflación – Respuestas correctas",
    "Inflación - No sabe": "Inflación – No sabe",
    "Inflación - No aplica": "Inflación – No aplica",
    "Inflación - Incorrecto": "Inflación – Respuestas incorrectas",
    "Interés Compuesto - Correcto": "Interés compuesto – Respuestas correctas",
    "Interés Compuesto - No sabe": "Interés compuesto – No sabe",
    "Interés Compuesto - No aplica": "Interés compuesto – No aplica",
    "Interés Compuesto - Incorrecto": "Interés compuesto – Respuestas incorrectas",
    "Diversificación Riesgo - Correcto": "Diversificación – Respuestas correctas",
    "Diversificación Riesgo - No sabe": "Diversificación – No sabe",
    "Diversificación Riesgo - No aplica": "Diversificación – No aplica",
    "Diversificación Riesgo - Incorrecto": "Diversificación – Respuestas incorrectas"
}

df = df.rename(columns =rename_dict1)

In [85]:
df.to_csv("C:/Personal/Susi/Bank Simulator/ECF files/04_Conocimientos_Financieros_2016_GEN_Cleaned.csv", index=False)