In [253]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv(r"C:\Personal\Susi\Bank Simulator\ECF files\04_Conocimientos_Financieros_2021_GEN.csv", sep=";")

In [255]:
df.head()

,a01: anio de la entrevista,e0100: como calificaria sus conocimientos generales sobre temas financieros?,e0500: imagine que cinco hermanos reciben eur1000...?,e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...,e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0900: cuanto dinero habra en la cuenta despues de cinco anios?,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,e1002: una inflacion elevada significa que el coste de la vida esta aumentando..,"e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...",...,e0401: puede senialar en que frase del texto se indica...?,e0402: a que edad comenzo a participar cabaniero en competiciones de natacion?,e0300: imagine que para producir cinco aparatos se necesitan cinco maquinas...,e1400,e1500,e1600,e1701,e1702,e1800,e1300
0,2022,3,200.0,1,0.0,120.0,2,1,1,-97,...,3,18,500.0,1.0,30.0,4,1,2,1,5
1,2022,3,200.0,3,0.0,100.0,-97,-97,1,-97,...,3,24,-97.0,3.0,30.0,2,2,1,5,1
2,2022,3,200.0,3,0.0,102.0,1,1,1,1,...,3,18,5.0,10.0,30.0,4,1,2,1,10
3,2022,3,200.0,2,0.0,102.0,2,1,1,-97,...,3,18,100.0,10.0,30.0,4,1,2,1,7
4,2022,1,-97.0,3,0.0,-97.0,-97,-97,1,-97,...,3,24,2.0,-97.0,100.0,2,2,-97,4,5

In [257]:
df = df.rename(columns={
    "e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...": "e0600",
    "e0900: cuanto dinero habra en la cuenta despues de cinco anios?": "e0900",
    "e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...": "e1003"
})
# e0600 (Inflation)
df["correct_e0600"] = df["e0600"].isin([3, 4]).astype(int)
df["dk_e0600"] = (df["e0600"] == -97).astype(int)
df["da_e0600"] = df["e0600"].isin([-99, -5]).astype(int)
df["incorrect_e0600"] = 1 - df["correct_e0600"] - df["dk_e0600"] - df["da_e0600"]

# e0900 (Compound interest)
df["correct_e0900"] = (df["e0900"] == 1).astype(int)
df["dk_e0900"] = (df["e0900"] == -97).astype(int)
df["da_e0900"] = df["e0900"].isin([-99, -5]).astype(int)
df["incorrect_e0900"] = 1 - df["correct_e0900"] - df["dk_e0900"] - df["da_e0900"]

# e1003 (Risk diversification)
df["correct_e1003"] = (df["e1003"] == 1).astype(int)
df["dk_e1003"] = (df["e1003"] == -97).astype(int)
df["da_e1003"] = df["e1003"].isin([-99, -5]).astype(int)
df["incorrect_e1003"] = 1 - df["correct_e1003"] - df["dk_e1003"] - df["da_e1003"]

# -----------------------------
# Clean missing values
# -----------------------------
df.replace([-97, -99, -5], pd.NA, inplace=True)
df.head(10)

,a01: anio de la entrevista,e0100: como calificaria sus conocimientos generales sobre temas financieros?,e0500: imagine que cinco hermanos reciben eur1000...?,e0600,e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0900,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,e1002: una inflacion elevada significa que el coste de la vida esta aumentando..,e1003,...,da_e0600,incorrect_e0600,correct_e0900,dk_e0900,da_e0900,incorrect_e0900,correct_e1003,dk_e1003,da_e1003,incorrect_e1003
0,2022,3,200.0,1,0.0,120.0,2,1,1,<NA>,...,0,1,0,0,0,1,0,1,0,0
1,2022,3,200.0,3,0.0,100.0,<NA>,<NA>,1,<NA>,...,0,0,0,1,0,0,0,1,0,0
2,2022,3,200.0,3,0.0,102.0,1,1,1,1,...,0,0,1,0,0,0,1,0,0,0
3,2022,3,200.0,2,0.0,102.0,2,1,1,<NA>,...,0,1,0,0,0,1,0,1,0,0
4,2022,1,<NA>,3,0.0,<NA>,<NA>,<NA>,1,<NA>,...,0,0,0,1,0,0,0,1,0,0
5,2022,3,250.0,3,0.0,110.0,1,1,1,1,...,0,0,1,0,0,0,1,0,0,0
6,2022,4,200.0,3,0.0,102.0,1,1,1,1,...,0,0,1,0,0,0,1,0,0,0
7,2022,1,<NA>,1,0.0,<NA>,4,1,1,<NA>,...,0,1,0,0,0,1,0,1,0,0
8,2022,1,200.0,<NA>,0.0,<NA>,<NA>,1,1,0,...,1,0,0,1,0,0,0,0,0,1
9,2022,3,225.0,2,0.0,102.0,4,1,1,1,...,0,1,0,0,0,1,1,0,0,0

In [259]:
df = df.rename(columns={
   "e0600": "e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...",
   "e0900" :"e0900: cuanto dinero habra en la cuenta despues de cinco anios?" ,
   "e1003": "e1003: por lo general, es posible reducir el riesgo de invertir en bolsa..." 
})

In [261]:
df.head()

,a01: anio de la entrevista,e0100: como calificaria sus conocimientos generales sobre temas financieros?,e0500: imagine que cinco hermanos reciben eur1000...?,e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...,e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...,e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...,e0900: cuanto dinero habra en la cuenta despues de cinco anios?,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,e1002: una inflacion elevada significa que el coste de la vida esta aumentando..,"e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...",...,da_e0600,incorrect_e0600,correct_e0900,dk_e0900,da_e0900,incorrect_e0900,correct_e1003,dk_e1003,da_e1003,incorrect_e1003
0,2022,3,200.0,1,0.0,120.0,2,1,1,<NA>,...,0,1,0,0,0,1,0,1,0,0
1,2022,3,200.0,3,0.0,100.0,<NA>,<NA>,1,<NA>,...,0,0,0,1,0,0,0,1,0,0
2,2022,3,200.0,3,0.0,102.0,1,1,1,1,...,0,0,1,0,0,0,1,0,0,0
3,2022,3,200.0,2,0.0,102.0,2,1,1,<NA>,...,0,1,0,0,0,1,0,1,0,0
4,2022,1,<NA>,3,0.0,<NA>,<NA>,<NA>,1,<NA>,...,0,0,0,1,0,0,0,1,0,0

In [263]:
print(df.columns.tolist())

['a01: anio de la entrevista', 'e0100: como calificaria sus conocimientos generales sobre temas financieros?', 'e0500: imagine que cinco hermanos reciben eur1000...?', 'e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...', 'e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...', 'e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...', 'e0900: cuanto dinero habra en la cuenta despues de cinco anios?', 'e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo', 'e1002: una inflacion elevada significa que el coste de la vida esta aumentando..', 'e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...', 'e1004', 'e1005', 'e1200: una hipoteca a 15 anios requiere normalmente pagos mensuales mas...', 'e1101: que fondo obtuvo el mejor rendimiento al termino de los seis anios?', 'e0401: puede senialar en que frase del texto se indica...?', 'e0402: a que edad comenzo a participar cabaniero en competiciones de natacion?', 'e0300: imagine que para producir cinco aparatos se necesitan cinco maquinas...', 'e1400', 'e1500', 'e1600', 'e1701', 'e1702', 'e1800', 'e1300', 'correct_e0600', 'dk_e0600', 'da_e0600', 'incorrect_e0600', 'correct_e0900', 'dk_e0900', 'da_e0900', 'incorrect_e0900', 'correct_e1003', 'dk_e1003', 'da_e1003', 'incorrect_e1003']

In [265]:
cols_to_drop = [
    'a01: anio de la entrevista',
    'e0500: imagine que cinco hermanos reciben eur1000...?',
    'e0700: si presta eur25 a un amigo una noche y este le devuelve eur25...',
    'e0800: ingresa eur100 en una cuenta de ahorro con un interes fijo...',
    
       
    'e0401: puede senialar en que frase del texto se indica...?',
    'e0402: a que edad comenzo a participar cabaniero en competiciones de natacion?',
       
    'e0300: imagine que para producir cinco aparatos se necesitan cinco maquinas...', "e1004", "e1005",
    "e1300", "e1400", "e1500", "e1600", "e1701", "e1702", "e1800"
]

In [267]:
df = df.drop(columns=cols_to_drop)

In [269]:
# Dictionary mapping old column names to new 
rename_dict = {
    'correct_e0600': 'Inflación - Correcto',
    'dk_e0600': 'Inflación - No sabe',
    'da_e0600': 'Inflación - No aplica',
    'incorrect_e0600': 'Inflación - Incorrecto',
    'correct_e0900': 'Interés Compuesto - Correcto',
    'dk_e0900': 'Interés Compuesto - No sabe',
    'da_e0900': 'Interés Compuesto - No aplica',
    'incorrect_e0900': 'Interés Compuesto - Incorrecto',
    'correct_e1003': 'Diversificación Riesgo - Correcto',
    'dk_e1003': 'Diversificación Riesgo - No sabe',
    'da_e1003': 'Diversificación Riesgo - No aplica',
    'incorrect_e1003': 'Diversificación Riesgo - Incorrecto'
}

# Rename columns in your DataFrame
df = df.rename(columns=rename_dict)

In [271]:
df.head()

,e0100: como calificaria sus conocimientos generales sobre temas financieros?,e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...,e0900: cuanto dinero habra en la cuenta despues de cinco anios?,e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo,e1002: una inflacion elevada significa que el coste de la vida esta aumentando..,"e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...",e1200: una hipoteca a 15 anios requiere normalmente pagos mensuales mas...,e1101: que fondo obtuvo el mejor rendimiento al termino de los seis anios?,Inflación - Correcto,Inflación - No sabe,Inflación - No aplica,Inflación - Incorrecto,Interés Compuesto - Correcto,Interés Compuesto - No sabe,Interés Compuesto - No aplica,Interés Compuesto - Incorrecto,Diversificación Riesgo - Correcto,Diversificación Riesgo - No sabe,Diversificación Riesgo - No aplica,Diversificación Riesgo - Incorrecto
0,3,1,2,1,1,<NA>,1,1,0,0,0,1,0,0,0,1,0,1,0,0
1,3,3,<NA>,<NA>,1,<NA>,0,2,1,0,0,0,0,1,0,0,0,1,0,0
2,3,3,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0
3,3,2,2,1,1,<NA>,1,3,0,0,0,1,0,0,0,1,0,1,0,0
4,1,3,<NA>,<NA>,1,<NA>,1,1,1,0,0,0,0,1,0,0,0,1,0,0

In [273]:

rename_dict1= {
    "e0100: como calificaria sus conocimientos generales sobre temas financieros?": "Autoevaluación del conocimiento financiero general",
    "e0600: imagine ahora que los cinco hermanos tuvieran que esperar un anio...": "Toma de decisiones en un escenario financiero diferido (espera de un año)",
    "e0900: cuanto dinero habra en la cuenta despues de cinco anios?": "Cálculo del saldo de la cuenta después de cinco años",
    "e1001: una inversion con una rentabilidad elevada puede ser de alto riesgo": "Reconocimiento de la relación entre alta rentabilidad y alto riesgo",
    "e1002: una inflacion elevada significa que el coste de la vida esta aumentando..": "Reconocimiento de la inflación como aumento del coste de vida",
    "e1003: por lo general, es posible reducir el riesgo de invertir en bolsa...": "Reconocimiento de la reducción del riesgo mediante diversificación",
    "e1200: una hipoteca a 15 anios requiere normalmente pagos mensuales mas...": "Comprensión de pagos mensuales más altos en hipotecas a corto plazo",
    "e1101: que fondo obtuvo el mejor rendimiento al termino de los seis anios?": "Identificación del fondo con mejor rendimiento en seis años",
    "Inflación - Correcto": "Inflación – Respuestas correctas",
    "Inflación - No sabe": "Inflación – No sabe",
    "Inflación - No aplica": "Inflación – No aplica",
    "Inflación - Incorrecto": "Inflación – Respuestas incorrectas",
    "Interés Compuesto - Correcto": "Interés compuesto – Respuestas correctas",
    "Interés Compuesto - No sabe": "Interés compuesto – No sabe",
    "Interés Compuesto - No aplica": "Interés compuesto – No aplica",
    "Interés Compuesto - Incorrecto": "Interés compuesto – Respuestas incorrectas",
    "Diversificación Riesgo - Correcto": "Diversificación – Respuestas correctas",
    "Diversificación Riesgo - No sabe": "Diversificación – No sabe",
    "Diversificación Riesgo - No aplica": "Diversificación – No aplica",
    "Diversificación Riesgo - Incorrecto": "Diversificación – Respuestas incorrectas"
}

df = df.rename(columns =rename_dict1)

In [277]:
df.head()

,Autoevaluación del conocimiento financiero general,Toma de decisiones en un escenario financiero diferido (espera de un año),Cálculo del saldo de la cuenta después de cinco años,Reconocimiento de la relación entre alta rentabilidad y alto riesgo,Reconocimiento de la inflación como aumento del coste de vida,Reconocimiento de la reducción del riesgo mediante diversificación,Comprensión de pagos mensuales más altos en hipotecas a corto plazo,Identificación del fondo con mejor rendimiento en seis años,Inflación – Respuestas correctas,Inflación – No sabe,Inflación – No aplica,Inflación – Respuestas incorrectas,Interés compuesto – Respuestas correctas,Interés compuesto – No sabe,Interés compuesto – No aplica,Interés compuesto – Respuestas incorrectas,Diversificación – Respuestas correctas,Diversificación – No sabe,Diversificación – No aplica,Diversificación – Respuestas incorrectas
0,3,1,2,1,1,<NA>,1,1,0,0,0,1,0,0,0,1,0,1,0,0
1,3,3,<NA>,<NA>,1,<NA>,0,2,1,0,0,0,0,1,0,0,0,1,0,0
2,3,3,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0
3,3,2,2,1,1,<NA>,1,3,0,0,0,1,0,0,0,1,0,1,0,0
4,1,3,<NA>,<NA>,1,<NA>,1,1,1,0,0,0,0,1,0,0,0,1,0,0

In [275]:
df.to_csv("C:/Personal/Susi/Bank Simulator/ECF files/04_Conocimientos_Financieros_2021_GEN_Cleaned.csv", index=False)