# Data Cleaning Informe ECF 2021

## Librerias

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

## Carga del fichero csv

In [2]:
df = pd.read_csv(
    r"..\Data\Bronze_ECF_090226.csv",
    sep=","
)
df.shape

(7764, 25)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7764 entries, 0 to 7763
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cat_educacion       7764 non-null   object
 1   estado_laboral      7764 non-null   object
 2   familia             7588 non-null   object
 3   riq_inmob           7732 non-null   object
 4   ahorro              7764 non-null   float64
 5   deuda               7761 non-null   float64
 6   adq_ahorro2         7764 non-null   float64
 7   adq_deuda2          7762 non-null   float64
 8   adq_otro            7764 non-null   float64
 9   ahorra_12m          7764 non-null   int64
 10  consumo_ahorros     7764 non-null   int64
 11  cred_inf            7764 non-null   int64
 12  cred_form           7764 non-null   int64
 13  cred_add            7764 non-null   int64
 14  impago              7764 non-null   int64
 15  ayudas              7764 non-null   int64
 16  rechazo             7764 non-null   int64
 17  semirechazo         7764 non-null   int64
 18  nopiden             7764 non-null   int64
 19  age                 7764 non-null   int64
 20  ID                  7764 non-null   int64
 21  year                7764 non-null   int64
 22  inflacion_ok        7181 non-null   float64
 23  interes_comp_ok     6866 non-null   float64
 24  diversificacion_ok  6292 non-null   float64
dtypes: float64(8), int64(13), object(4)
memory usage: 1.5+ MB

In [4]:
df.head()

,cat_educacion,estado_laboral,familia,riq_inmob,ahorro,deuda,adq_ahorro2,adq_deuda2,adq_otro,ahorra_12m,...,ayudas,rechazo,semirechazo,nopiden,age,ID,year,inflacion_ok,interes_comp_ok,diversificacion_ok
0,Universidad,Asalariado,Vive con pareja,Solo residencia principal,0.0,1.0,0.0,1.0,1.0,1,...,0,0,0,0,40,1,2022,0.0,0.0,NaN
1,Universidad,Asalariado,Otros adultos,Residencia principal y otras,0.0,1.0,0.0,0.0,0.0,0,...,0,0,0,1,54,2,2022,1.0,NaN,NaN
2,Educación Secundaria,Asalariado,Vive solo,Residencia principal y otras,1.0,0.0,1.0,0.0,1.0,1,...,0,0,0,0,54,3,2022,1.0,1.0,1.0
3,Educación Secundaria,Asalariado,Vive con pareja,Solo residencia principal,1.0,1.0,0.0,0.0,0.0,1,...,0,0,0,0,48,4,2022,0.0,0.0,NaN
4,Educación Primaria,Asalariado,Otros adultos,Solo residencia principal,0.0,1.0,0.0,1.0,1.0,0,...,0,0,0,0,49,5,2022,1.0,NaN,NaN

## 1. Tratamiento de valores NULL

In [7]:
columns_with_null = df.columns[df.isnull().any()].tolist()
columns_with_null

['familia',
 'riq_inmob',
 'deuda',
 'adq_deuda2',
 'inflacion_ok',
 'interes_comp_ok',
 'diversificacion_ok']

In [9]:
# 1) Eliminación de nulls con una ocurrencia inferior al 3% dentro de la variable en cuestión (household_type, residence_type, deuda, adq_deuda2)
df = df.dropna(subset=["familia", "riq_inmob","deuda", "adq_deuda2"])

In [10]:
columns_with_null = df.columns[df.isnull().any()].tolist()
columns_with_null

['inflacion_ok', 'interes_comp_ok', 'diversificacion_ok']

In [11]:
# 2) Cambio de nulls con una ocurrencia superior al 3% por -1 (inflacion_ok, interes_comp_ok, diversificacion_ok) 

df[["inflacion_ok", "interes_comp_ok", "diversificacion_ok"]] = (
    df[["inflacion_ok", "interes_comp_ok", "diversificacion_ok"]]
    .fillna(-1)
)

C:\Users\edo\AppData\Local\Temp\ipykernel_22592\1252206482.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["inflacion_ok", "interes_comp_ok", "diversificacion_ok"]] = (

In [12]:
columns_with_null = df.columns[df.isnull().any()].tolist()
columns_with_null

[]

## 2. Estandarización de formatos

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7554 entries, 0 to 7763
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cat_educacion       7554 non-null   object
 1   estado_laboral      7554 non-null   object
 2   familia             7554 non-null   object
 3   riq_inmob           7554 non-null   object
 4   ahorro              7554 non-null   float64
 5   deuda               7554 non-null   float64
 6   adq_ahorro2         7554 non-null   float64
 7   adq_deuda2          7554 non-null   float64
 8   adq_otro            7554 non-null   float64
 9   ahorra_12m          7554 non-null   int64
 10  consumo_ahorros     7554 non-null   int64
 11  cred_inf            7554 non-null   int64
 12  cred_form           7554 non-null   int64
 13  cred_add            7554 non-null   int64
 14  impago              7554 non-null   int64
 15  ayudas              7554 non-null   int64
 16  rechazo             7554 non-null   int64
 17  semirechazo         7554 non-null   int64
 18  nopiden             7554 non-null   int64
 19  age                 7554 non-null   int64
 20  ID                  7554 non-null   int64
 21  year                7554 non-null   int64
 22  inflacion_ok        7554 non-null   float64
 23  interes_comp_ok     7554 non-null   float64
 24  diversificacion_ok  7554 non-null   float64
dtypes: float64(8), int64(13), object(4)
memory usage: 1.5+ MB

In [14]:
# Cambio de literal int a variables binarias
df["ahorro"] = df["ahorro"].astype(int)
df["deuda"] = df["deuda"].astype(int)
df["adq_ahorro2"] = df["adq_ahorro2"].astype(int)
df["adq_deuda2"] = df["adq_deuda2"].astype(int)
df["adq_otro"] = df["adq_otro"].astype(int)
df["inflacion_ok"] = df["inflacion_ok"].astype(int)
df["interes_comp_ok"] = df["interes_comp_ok"].astype(int)
df["diversificacion_ok"] = df["diversificacion_ok"].astype(int)

C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ahorro"] = df["ahorro"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["deuda"] = df["deuda"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["adq_ahorro2"] = df["adq_ahorro2"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["adq_deuda2"] = df["adq_deuda2"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["adq_otro"] = df["adq_otro"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["inflacion_ok"] = df["inflacion_ok"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["interes_comp_ok"] = df["interes_comp_ok"].astype(int)
C:\Users\edo\AppData\Local\Temp\ipykernel_22592\795915133.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["diversificacion_ok"] = df["diversificacion_ok"].astype(int)

## 3. Validación final

In [15]:
# NULL summary 
null_counts = df.isna().sum()
null_summary = (
    null_counts[null_counts > 0]
    .sort_values(ascending=False)
    .rename("null_count")
    .reset_index()
    .rename(columns={"index": "column"})
)

print("=== NULLS (only columns with >0) ===")
display(null_summary)
print()

=== NULLS (only columns with >0) ===

Empty DataFrame
Columns: [column, null_count]
Index: []

In [16]:
# Types
types_summary = (
    df.dtypes.astype(str)
    .rename("dtype")
    .reset_index()
    .rename(columns={"index": "column"})
)

print("=== DTYPES ===")
display(types_summary)
print()

=== DTYPES ===

                column   dtype
0        cat_educacion  object
1       estado_laboral  object
2              familia  object
3            riq_inmob  object
4               ahorro   int64
5                deuda   int64
6          adq_ahorro2   int64
7           adq_deuda2   int64
8             adq_otro   int64
9           ahorra_12m   int64
10     consumo_ahorros   int64
11            cred_inf   int64
12           cred_form   int64
13            cred_add   int64
14              impago   int64
15              ayudas   int64
16             rechazo   int64
17         semirechazo   int64
18             nopiden   int64
19                 age   int64
20                  ID   int64
21                year   int64
22        inflacion_ok   int64
23     interes_comp_ok   int64
24  diversificacion_ok   int64

## Exportar el dataset limpio (Silver)

In [18]:
df.to_csv(
    r"..\Data\Silver_ECF_090226_2.csv",
    index=False,
    encoding="utf-8"
)