Нам необходимо скорректировать нашу бизнес-стратегию, чтобы соответствовать новым (формирующимся) тенденциям и максимально использовать рыночные возможности.

Нужно ли нам корректировать сегменты клиентов с учётом демографических прогнозов Национального института статистики (INE)?

Необходимо ли адаптировать наши текущие продукты/предложения или создавать новые на основе национальных тенденций в финансовом поведении и уровне финансовых компетенций населения? (ECF)

# Librerias

In [15]:
import pandas as pd
import numpy as np

In [16]:
path_fichero= r"C:\Users\edo\Desktop\Simulacion Empresarial\ecf_2021.csv"

# EDA técnica

In [ ]:
df_fichero = pd.read_csv(
    path_fichero,
    sep=";",
    encoding="utf-8"
)

df_fichero

,a01,a02,a0000,a0400,a04,a0800,a0100,a0320,a1030,a1040,...,a0200,f0900b,f1000b,f0900c,f1000c,f0900d,f1000d,f0900e,f1000e,ID
0,2022,6,0,1982,40,-98,1,0,2,2,...,1,1,1,-98,-98,-98,-98,0,0,1
1,2022,3,0,1967,54,-98,1,0,1,-98,...,5,-98,-98,1,1,-98,-98,-98,-98,2
2,2022,2,1,1967,54,-98,1,0,6,-98,...,11,-98,-98,-98,-98,-98,-98,-98,-98,3
3,2022,5,1,1974,48,-98,1,0,2,2,...,5,1,1,-98,-98,-98,-98,0,0,4
4,2022,6,1,1972,49,-98,1,0,1,-98,...,4,-98,-98,1,1,-98,-98,-98,-98,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7759,2021,12,0,1992,29,-98,1,0,1,-98,...,2,-98,-98,1,1,1,1,1,0,7760
7760,2022,4,1,1953,68,-98,1,0,2,2,...,7,1,1,-98,-98,-98,-98,-98,-98,7761
7761,2022,3,0,1985,36,-98,1,0,1,-98,...,5,-98,-98,1,1,-98,-98,-98,-98,7762
7762,2022,3,1,1959,62,-98,1,0,2,2,...,6,1,0,-98,-98,-98,-98,0,0,7763
7763,2022,6,0,1976,45,-98,1,0,2,2,...,16,1,1,-98,-98,-98,-98,0,0,7764

In [20]:
print(df_fichero.columns.tolist())

['a01', 'a02', 'a0000', 'a0400', 'a04', 'a0800', 'a0100', 'a0320', 'a1030', 'a1040', 'a0910', 'a1100', 'a1200', 'a1300', 'a1400', 'a1410', 'a1420a', 'a1420b', 'a1420c', 'a1420d', 'a1420e', 'a1420f', 'a1420g', 'a1500', 'a1510', 'a1600', 'a1520', 'a1530', 'a2000', 'a1700', 'a1710', 'a1900', 'a2100', 'a2200', 'a2300', 'a2500', 'a2400', 'a2600', 'a2700', 'b0100', 'b0110a', 'b0110b', 'b0110c', 'b0110d', 'b0110e', 'b0110f', 'b0110g', 'b0120a', 'b0120b', 'b0120c', 'b0120d', 'b0120e', 'b0120f', 'b0130a', 'b0130b', 'b0130c', 'b0208', 'b0308', 'b0408', 'b0201', 'b0301', 'b0401', 'b0202', 'b0302', 'b0402', 'b0203', 'b0303', 'b0403', 'b0204', 'b0304', 'b0404', 'b0205', 'b0305', 'b0405', 'b0206', 'b0306', 'b0406', 'b0207', 'b0307', 'b0407', 'b0209', 'b0309', 'b0409', 'b0210', 'b0310', 'b0410', 'b0212', 'b0312', 'b0412', 'b1100a', 'b1100b', 'b1100c', 'b1100d', 'b1100e', 'b1100f', 'b1100g', 'b1100i', 'b1100h', 'b0502', 'b0503', 'b0600', 'b0720a', 'b0720b', 'b0720c', 'b0720d', 'b0720e', 'b0720f', 'b0720g', 'b0720h', 'b0720i', 'b0710a', 'b0710b', 'b0710c', 'b0710d', 'b0710e', 'b0710f', 'b0710g', 'b0710h', 'b0710i', 'b1000a', 'b1000b', 'b1000c', 'b1000d', 'b1000e', 'b1000f', 'b1000g', 'b1000h', 'b1000i', 'b1000j', 'b1103', 'b1201', 'b1203a', 'b1203b', 'b1203c', 'b1203d', 'b1203e', 'b1203f', 'b1203g', 'b1204a', 'b1204b', 'b1204c', 'b1204d', 'b1204e', 'b1204f', 'b1204g', 'b1205a', 'b1205b', 'b1205c', 'b1205d', 'b1205e', 'b1206a', 'b1206b', 'b1206c', 'b1206d', 'b1206e', 'b1207a', 'b1207b', 'b1207c', 'b1208a', 'b1208b', 'b1208c', 'b1208d', 'b1209a', 'b1209b', 'b1209c', 'b1209d', 'b1230a', 'b1230b', 'b1230c', 'b1230d', 'b1230e', 'b1230f', 'b1230g', 'b1230h', 'c0100', 'c0200a', 'c0200b', 'c0200c', 'c0200d', 'c0200e', 'c0200f', 'c0200g', 'c0200h', 'c0200i', 'c0200j', 'c0200k', 'c0300', 'c0500', 'c0600a', 'c0600b', 'c0600c', 'c0600d', 'c0600e', 'c0600f', 'c0600g', 'c0600h', 'c0600i', 'c0600j', 'c0600k', 'c0400a', 'c0400b', 'c0400c', 'c0400d', 'c0400e', 'c0400f', 'c0400g', 'c0400h', 'c0400i', 'c0400j', 'c0400k', 'c0400l', 'c0400m', 'c0400n', 'd0101', 'd0104', 'd0110', 'd0113', 'd0102', 'd0114', 'd0115', 'd0117', 'd0103', 'd0116', 'd0105', 'd0106', 'd0107', 'd0108', 'd0109', 'd0111', 'd0112', 'd0300', 'd0400', 'd0500', 'd0600', 'd0610a', 'd0610b', 'd0610c', 'd0610d', 'd0610e', 'e0100', 'e0500', 'e0600', 'e0700', 'e0800', 'e0900', 'e1001', 'e1002', 'e1003', 'e1004', 'e1005', 'e1200', 'e1101', 'e0401', 'e0402', 'e0300', 'e1400', 'e1500', 'e1600', 'e1701', 'e1702', 'e1800', 'e1300', 'i0100', 'i0200a', 'i0200b', 'i0200c', 'i0200d', 'i0200e', 'i0200h', 'i0200f', 'i0200g', 'i0200j', 'i0300', 'i0500a', 'i0500b', 'i0500c', 'i0500d', 'i0500e', 'i0500f', 'i0500g', 'i0500h', 'i0500i', 'i0500k', 'i0500j', 'i0800', 'i0510', 'i0520a', 'i0520b', 'i0520c', 'i0520e', 'i0520f', 'i0520d', 'i0520g', 'i0601', 'i0602', 'i0700', 'i0900', 'i1000', 'i0400a', 'i0400b', 'i0400c', 'i0400d', 'i0400e', 'j0100', 'j0110', 'j0200', 'j0300a', 'j0300b', 'j0300c', 'j0300d', 'j0300e', 'j0300f', 'j0300g', 'j0300h', 'j0300i', 'j0300j', 'j0300k', 'j0300l', 'j0300m', 'j0300n', 'j0300p', 'j0300o', 'j0400', 'j0500', 'j0600', 'j0700', 'j0800a', 'j0800b', 'j0800c', 'j0800d', 'j0800e', 'j0800f', 'j0800h', 'j0800g', 'j0810', 'j0900a', 'j0900b', 'j0900c', 'j0900d', 'j0910a', 'j0910b', 'j0910c', 'j0910d', 'j0910e', 'j0910f', 'j0920', 'j1000', 'j1100', 'j1201', 'j1202', 'j1203', 'j1300', 'j1400', 'j1600', 'k1908', 'k1901', 'k1902', 'k1903', 'k1904', 'k1905', 'k1906', 'k1907', 'k1909', 'k1910', 'k1912', 'k0100', 'k0500', 'k0600', 'k0700', 'k0800', 'k0900', 'k1001', 'k1002', 'k1003', 'k1004', 'k1005', 'k1200', 'k1101', 'k0401', 'k0402', 'k0300', 'k1400', 'k1500', 'k1600', 'k1701', 'k1702', 'k1800', 'k1300', 'k2020', 'negativa_pmi', 'tmp_e0401', 'age', 'f0900a', 'f1000a', 'weight', 'a0940', 'a0930', 'a0300', 'a0310', 'ccaaf', 'a0930_b', 'a0950', 'f1100', 'f1200', 'f1200_b', 'f1300', 'a0900b', 'a0900c', 'a0900d', 'a0900e', 'a0900f', 'a0900l', 'a0900j', 'a0900h', 'a0900g', 'a0900i', 'a0900a', 'a0900k', 'a1800', 'a0200', 'f0900b', 'f1000b', 'f0900c', 'f1000c', 'f0900d', 'f1000d', 'f0900e', 'f1000e', 'ID']

In [34]:
df_fichero.shape

(7764, 429)

In [19]:
df_fichero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7764 entries, 0 to 7763
Columns: 429 entries, a01 to ID
dtypes: float64(10), int64(419)
memory usage: 25.4 MB

## % de datos faltantes entre columnas

In [36]:
miss = (
    df_fichero.isna()
      .mean()
      .mul(100)
      .round(2)
      .sort_values(ascending=False)
      .to_frame("missing_pct")
)
display(miss.head())

        missing_pct
a01             0.0
i0700           0.0
i0601           0.0
i0520g          0.0
i0520d          0.0

## Valores únicos por columna

In [ ]:
nunique = df_fichero.nunique(dropna=True).sort_values()
display(nunique.head()) 
display(nunique.tail())

a01       2
j1400     2
a0900i    2
a0900g    2
b0209     2
dtype: int64

j0700         213
i0700         462
weight       2544
tmp_e0401    5470
ID           7764
dtype: int64

## Datos constantes y casi constantes
- constante - 1 valor único
- casi constante: un modo ocupa >= 99,5% de los valores

In [38]:
const_cols = nunique[nunique <= 1].index.tolist()

In [39]:
def top_share(s: pd.Series) -> float:
    vc = s.value_counts(dropna=True)
    if vc.empty:
        return np.nan
    return vc.iloc[0] / vc.sum()

top_share_series = df_fichero.apply(top_share).sort_values(ascending=False)

near_const_cols = top_share_series[top_share_series >= 0.995].index.tolist()

print("constant cols:", len(const_cols))
print("near-constant cols (>=99.5% same):", len(near_const_cols))

constant cols: 0
near-constant cols (>=99.5% same): 10

### Ejemplos

In [40]:
display(pd.DataFrame({
    "nunique": nunique.loc[near_const_cols],
    "top_share": top_share_series.loc[near_const_cols].round(4)
}).sort_values(["top_share", "nunique"], ascending=[False, True]).head(30))

        nunique  top_share
a0900k        2     0.9997
a0900f        2     0.9990
a0900j        2     0.9986
b0110f        3     0.9979
a0800        15     0.9977
a0900h        2     0.9972
b1207c        4     0.9963
b1207b        4     0.9963
b1207a        4     0.9963
a0900l        2     0.9956

## Comprobación de la validez de las columnas numéricas

In [ ]:
num_cols = df_fichero.select_dtypes(include=["number"]).columns
ranges = df_fichero[num_cols].agg(["min", "max", "mean", "std"]).T
ranges["missing_pct"] = df_fichero[num_cols].isna().mean() * 100
ranges = ranges.round(3).sort_values("std", ascending=False)

display(ranges.head(30))  # los campos más dispersos
display(ranges.tail(30))  # los binarios/casi constantes

           min           max       mean          std  missing_pct
e1400   -99.00  1.100000e+08  14208.355  1248389.044          0.0
e0300   -99.00  1.000000e+08  13157.533  1134903.059          0.0
j0700   -99.00  4.680000e+04   1307.705     3039.705          0.0
weight  420.19  1.941142e+04   4639.769     2990.281          0.0
ID        1.00  7.764000e+03   3882.500     2241.418          0.0
e0500   -99.00  1.700000e+05    253.176     1951.025          0.0
i0800   -99.00  2.022000e+03   1256.460     1003.990          0.0
k0300   -99.00  5.000000e+04    -17.540      941.789          0.0
j0500   -99.00  3.000000e+03    359.509      302.867          0.0
e0800   -99.00  1.250000e+04     90.196      301.189          0.0
i0700   -99.00  4.000000e+03     63.276      301.054          0.0
a0310   -98.00  2.021000e+03    -46.418      299.828          0.0
i0300   -99.00  3.000000e+03      8.350      260.231          0.0
k1400   -99.00  1.000000e+04    -61.553      233.662          0.0
k0500   -99.00  5.000000e+03    -16.831      200.382          0.0
k0800   -99.00  2.400000e+03    -50.971      110.765          0.0
a2200   -99.00  1.000000e+02    -20.811       79.859          0.0
i0900   -99.00  1.500000e+02    -52.752       77.708          0.0
a0930   -99.00  9.200000e+01    -14.794       74.383          0.0
a0400   -99.00  2.003000e+03   1971.818       72.246          0.0
c0300   -99.00  1.250000e+02     14.995       71.996          0.0
a0950   -99.00  6.600000e+01    -23.285       59.659          0.0
a2100   -99.00  1.000000e+02    -27.233       58.711          0.0
k1500   -99.00  1.000000e+02    -67.303       54.945          0.0
f1200   -99.00  9.200000e+01     28.896       53.873          0.0
b0502   -99.00  1.200000e+01    -47.417       52.380          0.0
a2300   -99.00  1.000000e+02    -80.260       50.569          0.0
a2500   -99.00  1.000000e+01    -34.612       50.071          0.0
a2000   -99.00  5.000000e+00    -46.558       50.026          0.0
a1040   -99.00  3.000000e+00    -50.404       49.841          0.0

           min     max      mean    std  missing_pct
b0202    -97.0     1.0     0.886  1.151          0.0
b0206    -97.0     1.0     0.939  1.132          0.0
j1600     -5.0     3.0     2.590  0.811          0.0
b0110d    -5.0     1.0     0.468  0.525          0.0
b0110a    -5.0     1.0     0.603  0.516          0.0
b0110c    -5.0     1.0     0.373  0.511          0.0
a0000      0.0     1.0     0.519  0.500          0.0
b0110e    -5.0     1.0     0.688  0.492          0.0
a0900b     0.0     1.0     0.622  0.485          0.0
a01     2021.0  2022.0  2021.747  0.435          0.0
b0110b    -5.0     1.0     0.835  0.406          0.0
a0900e     0.0     1.0     0.180  0.384          0.0
b0212      0.0     1.0     0.870  0.336          0.0
a0900a     0.0     1.0     0.124  0.329          0.0
a0100      0.0     1.0     0.879  0.326          0.0
b0204      0.0     1.0     0.905  0.294          0.0
a0900g     0.0     1.0     0.092  0.289          0.0
b0110g    -5.0     1.0     0.026  0.229          0.0
a0900d     0.0     1.0     0.040  0.196          0.0
b0210      0.0     1.0     0.967  0.179          0.0
a0900c     0.0     1.0     0.033  0.178          0.0
b0110f    -5.0     1.0    -0.003  0.154          0.0
b0209      0.0     1.0     0.984  0.125          0.0
b0201      0.0     1.0     0.985  0.123          0.0
a0900i     0.0     1.0     0.010  0.099          0.0
a0900l     0.0     1.0     0.004  0.066          0.0
a0900h     0.0     1.0     0.003  0.053          0.0
a0900j     0.0     1.0     0.001  0.038          0.0
a0900f     0.0     1.0     0.001  0.032          0.0
a0900k     0.0     1.0     0.000  0.016          0.0

In [ ]:
profile = pd.DataFrame({
    "dtype": df_fichero.dtypes.astype(str),
    "missing_pct": df_fichero.isna().mean().mul(100).round(2),
    "nunique": df_fichero.nunique(dropna=True),
    "top_share": top_share_series.round(4),
})
profile = profile.sort_values(["missing_pct", "top_share"], ascending=[False, False])
display(profile.head(40))

           dtype  missing_pct  nunique  top_share
a0900k     int64          0.0        2     0.9997
a0900f     int64          0.0        2     0.9990
a0900j     int64          0.0        2     0.9986
b0110f     int64          0.0        3     0.9979
a0800      int64          0.0       15     0.9977
a0900h     int64          0.0        2     0.9972
b1207a     int64          0.0        4     0.9963
b1207b     int64          0.0        4     0.9963
b1207c     int64          0.0        4     0.9963
a0900l     int64          0.0        2     0.9956
b0120f     int64          0.0        4     0.9943
b1000i     int64          0.0        4     0.9902
a0900i     int64          0.0        2     0.9901
b1100f     int64          0.0        3     0.9896
b1205a     int64          0.0        5     0.9862
b1205b     int64          0.0        5     0.9862
b1205c     int64          0.0        5     0.9862
b1205d     int64          0.0        5     0.9862
b1205e     int64          0.0        5     0.9862
b0201      int64          0.0        2     0.9847
b0209      int64          0.0        2     0.9840
b1209a     int64          0.0        3     0.9839
b1209b     int64          0.0        3     0.9839
b1209c     int64          0.0        3     0.9839
b1209d     int64          0.0        3     0.9839
b0100      int64          0.0        5     0.9838
b0207      int64          0.0        3     0.9820
j0900b     int64          0.0        5     0.9807
b1000f     int64          0.0        4     0.9784
f1200_b    int64          0.0       15     0.9781
e0700    float64          0.0       18     0.9773
j0910a     int64          0.0        4     0.9758
j0910b     int64          0.0        4     0.9758
j0910c     int64          0.0        4     0.9758
j0910d     int64          0.0        4     0.9758
j0910e     int64          0.0        4     0.9758
j0910f     int64          0.0        4     0.9758
j0920      int64          0.0        7     0.9758
b1204a     int64          0.0        3     0.9753
b1204b     int64          0.0        3     0.9753

## 1. Recodificación

#### Recodificación del nivel educativo a partir de la variable original a1100

In [21]:
# Recodificación del nivel educativo a partir de la variable original a1100


def recode_education(x):
    if pd.isna(x):
        return None  # Missing real
    
    if x in [1, 2, 3]:
        return "Educación Primaria"
    elif x in [4, 5]:
        return "Educación Secundaria"
    elif x in [6, 7, 8, 9]:
        return "Universidad"
    elif x in [98, 99]:
        return None  # No sabe / No contesta (si existen)
    else:
        return None  # Otros códigos no contemplados

df_fichero["educacion_cat"] = df_fichero["a1100"].apply(recode_education)

df_fichero["educacion_cat"].value_counts(dropna=False)

educacion_cat
Universidad             3252
Educación Primaria      2580
Educación Secundaria    1932
Name: count, dtype: int64

#### Recodificación de la situación laboral a partir de a1500 y a2000

In [22]:
# 1) Verificar previamente los valores reales de a1500 y a2000.
# 2) Confirmar que a2000 solo aplica cuando a1500 == 2 (asalariado).
# 3) Controlar posibles códigos 98/99 (No sabe / No contesta).

def recode_labor_status(row):

    a1500 = row["a1500"]
    a2000 = row["a2000"]

    if pd.isna(a1500) and pd.isna(a2000):
        return None  # Missing real

    if a1500 == 1:
        return "Autónomo"

    elif a1500 == 2 or a2000 == 1:
        return "Asalariado"

    elif a1500 == 5:
        return "Desempleado"

    elif a1500 == 6:
        return "Jubilado"

    elif a1500 in [4, 7, 8, 9, 10]:
        return "Otros inactivos"

    elif a1500 in [98, 99]:
        return None  # No sabe / No contesta (si existen)

    else:
        return None  # Códigos no contemplados


df_fichero["labor_status"] = df_fichero.apply(recode_labor_status, axis=1)

df_fichero["labor_status"].value_counts(dropna=False)

labor_status
Asalariado         3859
Otros inactivos    1158
Jubilado           1065
Autónomo            871
Desempleado         811
Name: count, dtype: int64

#### Recodificación del tipo de hogar a partir de variables a0900*

In [26]:
# 1) Verificar que los códigos 1 significan "Sí".
# 2) Confirmar si pueden existir códigos 98/99.
# 3) El orden de condiciones importa: pareja tiene prioridad.

def recode_household(row):

    # Vive con pareja
    if row["a0900b"] == 1:
        return "Vive con pareja"
    
    # Vive solo (vive solo y no tiene pareja)
    elif row["a0900a"] == 1 and row["a0900b"] != 1:
        return "Vive solo"
    
    # Vive con otros adultos (sin pareja pero con otros adultos)
    elif row["a0900b"] != 1 and any(
        row[col] == 1 for col in ["a0900d", "a0900e", "a0900g", "a0900h", "a0900i", "a0900j"]
    ):
        return "Otros adultos"
    
    else:
        return None  # Missing o combinaciones no contempladas


df_fichero["household_type"] = df_fichero.apply(recode_household, axis=1)

# Validación distribución
df_fichero["household_type"].value_counts(dropna=False)

# Inspección de casos no clasificados
df_fichero.loc[
    df_fichero["household_type"].isna(),
    ["a0900a","a0900b","a0900d","a0900e","a0900g","a0900h","a0900i","a0900j"]
]

      a0900a  a0900b  a0900d  a0900e  a0900g  a0900h  a0900i  a0900j
13         0       0       0       0       0       0       0       0
19         0       0       0       0       0       0       0       0
129        0       0       0       0       0       0       0       0
149        0       0       0       0       0       0       0       0
167        0       0       0       0       0       0       0       0
...      ...     ...     ...     ...     ...     ...     ...     ...
7493       0       0       0       0       0       0       0       0
7566       0       0       0       0       0       0       0       0
7730       0       0       0       0       0       0       0       0
7746       0       0       0       0       0       0       0       0
7761       0       0       0       0       0       0       0       0

[176 rows x 8 columns]

In [31]:
df_fichero.loc[
    df_fichero["household_type"].notna(),
    ["household_type"]
]

       household_type
0     Vive con pareja
1       Otros adultos
2           Vive solo
3     Vive con pareja
4       Otros adultos
...               ...
7758  Vive con pareja
7759    Otros adultos
7760  Vive con pareja
7762  Vive con pareja
7763  Vive con pareja

[7588 rows x 1 columns]

#### Recodificación del tipo de residencia a partir de i0100 e i1000

In [32]:
# WARNING:
# 1) Verificar previamente los códigos reales de i0100 e i1000.
# 2) Confirmar si existen códigos 98/99 (No sabe / No contesta).
# 3) Controlar posibles missing con pd.isna().

def recode_residence(row):

    i0100 = row["i0100"]
    i1000 = row["i1000"]

    # Missing real
    if pd.isna(i0100):
        return None

    # No posee residencia principal
    if i0100 in [3, 4]:
        return "No posee residencia principal"

    # Tiene residencia principal
    if i0100 in [1, 2]:

        if pd.isna(i1000):
            return None  # Missing en otras viviendas

        if i1000 == 0:
            return "Solo residencia principal"

        elif i1000 == 1:
            return "Residencia principal y otras"

        elif i1000 in [98, 99]:
            return None  # No sabe / No contesta

        else:
            return None  # Código inesperado

    elif i0100 in [98, 99]:
        return None  # No sabe / No contesta

    else:
        return None  # Otros códigos no contemplados


df_fichero["residence_type"] = df_fichero.apply(recode_residence, axis=1)

# Validación recomendada
df_fichero["residence_type"].value_counts(dropna=False)

residence_type
Solo residencia principal        3026
Residencia principal y otras     2889
No posee residencia principal    1817
None                               32
Name: count, dtype: int64

#### Recodificación residencia (i0100 + i1000)

In [33]:

def recode_residence(row):

    i0100 = row["i0100"]
    i1000 = row["i1000"]

    if pd.isna(i0100):
        return None

    if i0100 in [3, 4]:
        return "No posee residencia principal"

    if i0100 in [1, 2]:

        if pd.isna(i1000):
            return None

        if i1000 == 0:
            return "Solo residencia principal"

        if i1000 == 1:
            return "Residencia principal y otras"

    return None


df_fichero["residence_type"] = df_fichero.apply(recode_residence, axis=1)

df_fichero["residence_type"].value_counts(dropna=False)

residence_type
Solo residencia principal        3026
Residencia principal y otras     2889
No posee residencia principal    1817
None                               32
Name: count, dtype: int64

#### Recodificación residencia (i0100 + i1000)

In [45]:

# WARNING:
# 1) Verificar que el valor 1 corresponde efectivamente a "Sí".
# 2) Confirmar códigos DK/DA reales en bloque B.
# 3) Revisar que todas las columnas existen en df_fichero.

YES = 1  # En ECF normalmente 1 = "Sí"

def any_yes(df: pd.DataFrame, cols: list[str]) -> pd.Series:
    """
    Devuelve:
    1  → si al menos una variable en 'cols' tiene valor YES
    0  → si ninguna tiene YES (y no son todas missing)
    NaN → si todas están en missing (incluye DK/DA)
    """
    
    # Reemplazar DK/DA por NaN
    sub = df[cols].replace([-97, -99, -5], np.nan)
    
    has_any = (sub == YES).any(axis=1)
    all_nan = sub.isna().all(axis=1)
    
    return np.where(all_nan, np.nan, has_any.astype(int))


# --- Posee vehículos de ahorro ---
ahorro = ["b0302","b0303","b0304","b0305","b0308","b0312"]
df_fichero["ahorro"] = any_yes(df_fichero, ahorro)


# --- Posee deuda ---
deuda = ["b0301","b0306"]
df_fichero["deuda"] = any_yes(df_fichero, deuda)


# --- Adquirió ahorro últimos 2 años ---
adq_ahorro2 = ["b0402","b0403","b0404","b0405","b0408","b0412"]
df_fichero["adq_ahorro2"] = any_yes(df_fichero, adq_ahorro2)


# --- Adquirió deuda últimos 2 años ---
adq_deuda2 = ["b0401","b0406"]
df_fichero["adq_deuda2"] = any_yes(df_fichero, adq_deuda2)


# --- Adquirió cualquier producto financiero ---
adq_otro = adq_ahorro2 + adq_deuda2 + ["b0407","b0409","b0410"]
df_fichero["adq_otro"] = any_yes(df_fichero, adq_otro)


# OUTPUT CONTROL
df_fichero[["ahorro","deuda","adq_ahorro2","adq_deuda2","adq_otro"]].value_counts(dropna=False).head(20)

ahorro  deuda  adq_ahorro2  adq_deuda2  adq_otro
0.0     0.0    0.0          0.0         0.0         2095
1.0     0.0    1.0          0.0         1.0          817
0.0     1.0    0.0          0.0         0.0          728
1.0     0.0    0.0          0.0         0.0          712
0.0     1.0    0.0          1.0         1.0          667
1.0     1.0    0.0          0.0         0.0          471
0.0     0.0    0.0          0.0         1.0          444
1.0     1.0    1.0          0.0         1.0          359
                            1.0         1.0          334
               0.0          1.0         1.0          326
0.0     1.0    0.0          0.0         1.0          200
1.0     0.0    0.0          0.0         1.0          180
        1.0    0.0          0.0         1.0          141
0.0     0.0    0.0          1.0         1.0           92
               1.0          0.0         1.0           62
1.0     0.0    1.0          1.0         1.0           42
0.0     1.0    1.0          1.0         1.0           38
1.0     0.0    0.0          1.0         1.0           25
0.0     1.0    1.0          0.0         1.0           17
        0.0    1.0          1.0         1.0           11
Name: count, dtype: int64

#### Construcción variables de vulnerabilidad y financiación (bloques J y B)

In [46]:
# WARNING:
# 1) Usar df_fichero, no df.
# 2) Verificar que 1 = "Sí" y que no existan códigos DK/DA distintos.
# 3) Este enfoque convierte missing en 0 (revisar si es deseado).

# Ahorra (b1000j == 0 normalmente significa "Sí")
df_fichero["ahorra_12m"] = (df_fichero["b1000j"] == 0).astype(int)

# Uso de ahorros propios
df_fichero["consumo_ahorros"] = (
    (df_fichero["j0300a"] == 1) |
    (df_fichero["j0300b"] == 1) |
    (df_fichero["j0300g"] == 1)
).astype(int)

# Crédito informal
df_fichero["cred_inf"] = (
    (df_fichero["j0300c"] == 1) |
    (df_fichero["j0300d"] == 1)
).astype(int)

# Líneas de crédito / tarjetas / préstamos formales
df_fichero["cred_line"] = (
    (df_fichero["j0300e"] == 1) |
    (df_fichero["j0300f"] == 1) |
    (df_fichero["j0300i"] == 1) |
    (df_fichero["j0300j"] == 1)
).astype(int)

# Crédito adicional
df_fichero["cred_add"] = (
    (df_fichero["j0300k"] == 1) |
    (df_fichero["j0300l"] == 1) |
    (df_fichero["j0300h"] == 1)
).astype(int)

# Impago
df_fichero["impago"] = (
    (df_fichero["j0300m"] == 1) |
    (df_fichero["j0300n"] == 1)
).astype(int)

# Ayudas externas
df_fichero["ayudas"] = (df_fichero["j0300o"] == 1).astype(int)

# Rechazo crédito
df_fichero["rechazo"] = (df_fichero["j0900a"] == 1).astype(int)

# Semirechazo
df_fichero["semirechazo"] = (df_fichero["j0900b"] == 1).astype(int)

# No solicita crédito
df_fichero["nopiden"] = (df_fichero["j0900c"] == 1).astype(int)


# OUTPUT CONTROL
df_fichero[
    ["ahorra_12m","consumo_ahorros","cred_inf","cred_line","cred_add",
     "impago","ayudas","rechazo","semirechazo","nopiden"]
].value_counts(dropna=False).head(20)

ahorra_12m  consumo_ahorros  cred_inf  cred_line  cred_add  impago  ayudas  rechazo  semirechazo  nopiden
1           0                0         0          0         0       0       0        0            0          4540
0           0                0         0          0         0       0       0        0            0          1292
1           1                0         0          0         0       0       0        0            0           462
0           1                0         0          0         0       0       0        0            0           241
            0                1         0          0         0       0       0        0            0           140
1           0                1         0          0         0       0       0        0            0            93
                             0         0          0         0       0       1        0            0            77
            1                1         0          0         0       0       0        0            0            72
0           0                0         0          0         1       0       0        0            0            43
1           0                0         0          0         0       0       0        1            0            42
0           0                0         1          0         0       0       0        0            0            33
1           0                0         1          0         0       0       0        0            0            32
0           0                0         0          0         0       0       0        0            1            31
1           0                0         0          0         0       0       0        0            1            30
0           0                0         0          0         0       0       1        0            0            25
1           1                0         1          0         0       0       0        0            0            23
0           1                1         0          0         0       0       0        0            0            23
            0                0         0          1         0       0       0        0            0            20
1           1                0         0          0         0       0       0        0            1            18
            0                0         0          0         1       0       0        0            0            17
Name: count, dtype: int64

#### Construcción dataset analítico final (core)

In [42]:
df_fichero.columns

Index(['a01', 'a02', 'a0000', 'a0400', 'a04', 'a0800', 'a0100', 'a0320',
       'a1030', 'a1040',
       ...
       'ahorra', 'ahorros', 'cred_inf', 'cred_line', 'cred_add', 'impago',
       'ayudas', 'rechazo', 'semirechazo', 'nopiden'],
      dtype='object', length=448)

In [48]:
# DATASET ANALÍTICO FINAL

core_cols = [
    "educacion_cat",
    "labor_status",
    "household_type",
    "residence_type",
    "ahorro",
    "deuda",
    "adq_ahorro2",
    "adq_deuda2",
    "adq_otro",
    "ahorra_12m",
    "consumo_ahorros",
    "cred_inf",
    "cred_line",
    "cred_add",
    "impago",
    "ayudas",
    "rechazo",
    "semirechazo",
    "nopiden",
    "age"
]
df_analitico = df_fichero[core_cols].copy()

df_analitico

,educacion_cat,labor_status,household_type,residence_type,ahorro,deuda,adq_ahorro2,adq_deuda2,adq_otro,ahorra_12m,consumo_ahorros,cred_inf,cred_line,cred_add,impago,ayudas,rechazo,semirechazo,nopiden,age
0,Universidad,Asalariado,Vive con pareja,Solo residencia principal,0.0,1.0,0.0,1.0,1.0,1,1,0,0,0,0,0,0,0,0,40
1,Universidad,Asalariado,Otros adultos,Residencia principal y otras,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,1,54
2,Educación Secundaria,Asalariado,Vive solo,Residencia principal y otras,1.0,0.0,1.0,0.0,1.0,1,0,0,0,0,0,0,0,0,0,54
3,Educación Secundaria,Asalariado,Vive con pareja,Solo residencia principal,1.0,1.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,48
4,Educación Primaria,Asalariado,Otros adultos,Solo residencia principal,0.0,1.0,0.0,1.0,1.0,0,0,0,0,1,0,0,0,0,0,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7759,Universidad,Asalariado,Otros adultos,Residencia principal y otras,1.0,0.0,1.0,0.0,1.0,0,0,0,0,0,0,0,0,0,0,29
7760,Universidad,Jubilado,Vive con pareja,Residencia principal y otras,1.0,0.0,1.0,0.0,1.0,1,0,0,0,0,0,0,0,0,0,68
7761,Educación Primaria,Asalariado,None,Solo residencia principal,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,36
7762,Educación Primaria,Autónomo,Vive con pareja,Residencia principal y otras,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,62
7763,Universidad,Asalariado,Vive con pareja,Residencia principal y otras,1.0,1.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,45

In [49]:


# ===============================
# CHECKS
# ===============================

# 1. Columnas
print("Columnas:")
print(df_analitico.columns.tolist())

# 2. Shape
print("\nShape:")
print(df_analitico.shape)

# 3. Missing por columna
print("\nMissing por columna:")
print(df_analitico.isna().sum())

# 4. Distribución rápida
for col in df_analitico.columns:
    print(f"\nDistribución {col}:")
    print(df_analitico[col].value_counts(dropna=False))

Columnas:
['educacion_cat', 'labor_status', 'household_type', 'residence_type', 'ahorro', 'deuda', 'adq_ahorro2', 'adq_deuda2', 'adq_otro', 'ahorra_12m', 'consumo_ahorros', 'cred_inf', 'cred_line', 'cred_add', 'impago', 'ayudas', 'rechazo', 'semirechazo', 'nopiden', 'age']

Shape:
(7764, 20)

Missing por columna:
educacion_cat        0
labor_status         0
household_type     176
residence_type      32
ahorro               0
deuda                3
adq_ahorro2          0
adq_deuda2           2
adq_otro             0
ahorra_12m           0
consumo_ahorros      0
cred_inf             0
cred_line            0
cred_add             0
impago               0
ayudas               0
rechazo              0
semirechazo          0
nopiden              0
age                  0
dtype: int64

Distribución educacion_cat:
educacion_cat
Universidad             3252
Educación Primaria      2580
Educación Secundaria    1932
Name: count, dtype: int64

Distribución labor_status:
labor_status
Asalariado         3859
Otros inactivos    1158
Jubilado           1065
Autónomo            871
Desempleado         811
Name: count, dtype: int64

Distribución household_type:
household_type
Vive con pareja    4827
Otros adultos      1800
Vive solo           961
None                176
Name: count, dtype: int64

Distribución residence_type:
residence_type
Solo residencia principal        3026
Residencia principal y otras     2889
No posee residencia principal    1817
None                               32
Name: count, dtype: int64

Distribución ahorro:
ahorro
0.0    4356
1.0    3408
Name: count, dtype: int64

Distribución deuda:
deuda
0.0    4480
1.0    3281
NaN       3
Name: count, dtype: int64

Distribución adq_ahorro2:
adq_ahorro2
0.0    6083
1.0    1681
Name: count, dtype: int64

Distribución adq_deuda2:
adq_deuda2
0.0    6227
1.0    1535
NaN       2
Name: count, dtype: int64

Distribución adq_otro:
adq_otro
0.0    4008
1.0    3756
Name: count, dtype: int64

Distribución ahorra_12m:
ahorra_12m
1    5678
0    2086
Name: count, dtype: int64

Distribución consumo_ahorros:
consumo_ahorros
0    6738
1    1026
Name: count, dtype: int64

Distribución cred_inf:
cred_inf
0    7209
1     555
Name: count, dtype: int64

Distribución cred_line:
cred_line
0    7521
1     243
Name: count, dtype: int64

Distribución cred_add:
cred_add
0    7619
1     145
Name: count, dtype: int64

Distribución impago:
impago
0    7545
1     219
Name: count, dtype: int64

Distribución ayudas:
ayudas
0    7721
1      43
Name: count, dtype: int64

Distribución rechazo:
rechazo
0    7519
1     245
Name: count, dtype: int64

Distribución semirechazo:
semirechazo
0    7641
1     123
Name: count, dtype: int64

Distribución nopiden:
nopiden
0    7576
1     188
Name: count, dtype: int64

Distribución age:
age
54    215
46    200
45    189
44    186
47    186
     ...
75     64
76     63
78     49
79     38
80     10
Name: count, Length: 63, dtype: int64

In [50]:
# 1) Ver columnas
print(df_analitico.columns)

# 2) Ver tipos
print(df_analitico.dtypes)

# 3) Ver missing por columna
df_analitico.isna().sum()

# 4) Distribución rápida por variable
for col in df_analitico.columns:
    print("\n", col)
    print(df_analitico[col].value_counts(dropna=False))

Index(['educacion_cat', 'labor_status', 'household_type', 'residence_type',
       'ahorro', 'deuda', 'adq_ahorro2', 'adq_deuda2', 'adq_otro',
       'ahorra_12m', 'consumo_ahorros', 'cred_inf', 'cred_line', 'cred_add',
       'impago', 'ayudas', 'rechazo', 'semirechazo', 'nopiden', 'age'],
      dtype='object')
educacion_cat       object
labor_status        object
household_type      object
residence_type      object
ahorro             float64
deuda              float64
adq_ahorro2        float64
adq_deuda2         float64
adq_otro           float64
ahorra_12m           int64
consumo_ahorros      int64
cred_inf             int64
cred_line            int64
cred_add             int64
impago               int64
ayudas               int64
rechazo              int64
semirechazo          int64
nopiden              int64
age                  int64
dtype: object

 educacion_cat
educacion_cat
Universidad             3252
Educación Primaria      2580
Educación Secundaria    1932
Name: count, dtype: int64

 labor_status
labor_status
Asalariado         3859
Otros inactivos    1158
Jubilado           1065
Autónomo            871
Desempleado         811
Name: count, dtype: int64

 household_type
household_type
Vive con pareja    4827
Otros adultos      1800
Vive solo           961
None                176
Name: count, dtype: int64

 residence_type
residence_type
Solo residencia principal        3026
Residencia principal y otras     2889
No posee residencia principal    1817
None                               32
Name: count, dtype: int64

 ahorro
ahorro
0.0    4356
1.0    3408
Name: count, dtype: int64

 deuda
deuda
0.0    4480
1.0    3281
NaN       3
Name: count, dtype: int64

 adq_ahorro2
adq_ahorro2
0.0    6083
1.0    1681
Name: count, dtype: int64

 adq_deuda2
adq_deuda2
0.0    6227
1.0    1535
NaN       2
Name: count, dtype: int64

 adq_otro
adq_otro
0.0    4008
1.0    3756
Name: count, dtype: int64

 ahorra_12m
ahorra_12m
1    5678
0    2086
Name: count, dtype: int64

 consumo_ahorros
consumo_ahorros
0    6738
1    1026
Name: count, dtype: int64

 cred_inf
cred_inf
0    7209
1     555
Name: count, dtype: int64

 cred_line
cred_line
0    7521
1     243
Name: count, dtype: int64

 cred_add
cred_add
0    7619
1     145
Name: count, dtype: int64

 impago
impago
0    7545
1     219
Name: count, dtype: int64

 ayudas
ayudas
0    7721
1      43
Name: count, dtype: int64

 rechazo
rechazo
0    7519
1     245
Name: count, dtype: int64

 semirechazo
semirechazo
0    7641
1     123
Name: count, dtype: int64

 nopiden
nopiden
0    7576
1     188
Name: count, dtype: int64

 age
age
54    215
46    200
45    189
44    186
47    186
     ...
75     64
76     63
78     49
79     38
80     10
Name: count, Length: 63, dtype: int64