# Extracción de datos de los csv

**Índice**

*FORMACIÓN EN LAS EMPRESAS*

EAL-16	Empresas según actividad económica por **competencias** consideradas importantes para el desarrollo en los próximos años  
- EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS
- EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS 
- EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS
- EAL-16c. EMPRESAS DE *MÁS DE 499* TRABAJADORES SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS 
- EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS
- EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS 
- EAL-16f. EMPRESAS DEL SECTOR *SERVICIOS* SEGÚN GRADO DE IMPORTANCIA  PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS 

EAL-17	Empresas, según **si impartieron formación**, por *tamaño* de la empresa, *actividad económica* y *comunidad autónoma* (importición cursos y otros tipos de formación/ solo cursos/solo otros tipos)

EAL-18	Empresas, según **detectaran o no necesidades formativas** de su personal e **impartieran o no formación**, por *tamaño* de la empresa, *actividad* económica y *comunidad* autónoma  
EAL-18a	Empresas, según actividad económica, por competencias consideradas importantes para el desarrollo en los próximos años 
- EAL-18a. EMPRESAS QUE **PROPORCIONARON FORMACIÓN** A SUS TRABAJADORES SEGÚN **MEDIO** UTILIZADO POR *TAMAÑO* DE LA EMPRESA, *ACTIVIDAD* ECONÓMICA Y *COMUNIDAD* AUTÓNOMA
EAL-18b	Empresas, según si impartieron formación, por tamaño de la empresa, actividad económica y comunidad autónoma
- EAL-18b. EMPRESAS QUE **PROPORCIONARON FORMACIÓN** A SUS TRABAJADORES *EN SUSPENSIÓN DE CONTRATO* Y/O REDUCCION DE JORNADA POR *TAMAÑO* DE LA EMPRESA, *ACTIVIDAD* ECONÓMICA Y *COMUNIDAD* AUTÓNOMA
EAL-18c	Empresas, según detectaran o no necesidades formativas de su personal e impartieran o no formación, por tamaño de la empresa, actividad económica y comunidad autónoma  
- EAL-18c. EMPRESAS QUE **PROPORCIONARON FORMACIÓN** A SUS TRABAJADORES SOBRE **SEGURIDAD**, **SALUD** E **HIGIENE** EN EL TRABAJO POR *TAMAÑO* DE LA EMPRESA, *ACTIVIDAD* ECONÓMICA Y *COMUNIDAD* AUTÓNOMA. **Importante para perfil y absentismo!!**

EAL-19	Empresas que **proporcionaron formación** a sus trabajadores, según *sector* de actividad, por *tamaño* de la empresa

EAL-20	Empresas que **proporcionaron formación** a sus trabajadores, **por competencias** en las que se han formado, por *tamaño* de la empresa  
EAL-21	Empresas que **proporcionaron formación** a sus trabajadores, **por competencias** en las que se han formado, por *sector* de actividad  
EAL-22	Empresas que proporcionaron formación a sus trabajadores, por **competencias** en las que se han formado, por *comunidad* autónoma


EAL-23	Empresas que pro`p QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES, SEGÚN *GRADO DE RELEVANCIA* DE **POSIBLES OBJETIVOS** DE LAS ACCIONES FORMATIVAS  
- EAL-23. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS
- EAL-23a. *EMPRESAS DE 5 A 49 TRABAJADORES* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS 
- EAL-23b. *EMPRESAS DE 50 A 499 TRABAJADORES* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS 
- EAL-23c. *EMPRESAS DE MÁS DE 499 TRABAJADORES* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS
- EAL-23d. EMPRESAS DE LA *INDUSTRIA* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS
- EAL-23e. EMPRESAS DE LA *CONSTRUCCIÓN* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS
- EAL-23f. EMPRESAS DEL SECTOR *SERVICIOS* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE RELEVANCIA DE POSIBLES OBJETIVOS DE LAS ACCIONES FORMATIVAS 


EAL-24	Empresas que *proporcionaron* formación a sus trabajadores, según **grado de limitación** a la formación que supusieron ciertos motivos
- EAL-24a. EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE LIMITACIÓN A LA FORMACIÓN  QUE SUPUSIERON CIERTOS MOTIVOS 
- EAL-24b. EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE LIMITACIÓN A LA FORMACIÓN  QUE SUPUSIERON CIERTOS MOTIVOS
- EAL-24c. EMPRESAS DE *MÁS DE 499* TRABAJADORES QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE LIMITACIÓN A LA FORMACIÓN  QUE SUPUSIERON CIERTOS MOTIVOS
- EAL-24d. EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE LIMITACIÓN A LA FORMACIÓN  QUE SUPUSIERON CIERTOS MOTIVOS
- EAL-24e. EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE LIMITACIÓN A LA FORMACIÓN  QUE SUPUSIERON CIERTOS MOTIVOS 
- EAL-24f. EMPRESAS DEL SECTOR *SERVICIOS* QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE LIMITACIÓN A LA FORMACIÓN  QUE SUPUSIERON CIERTOS MOTIVOS

EAL-25	Empresas que no proporcionaron formación a sus trabajadores, según **grado de influencia** que supusieron ciertos motivos para no proporcionar formación
- EAL-25. EMPRESAS QUE **NO PROPORCIONARON** FORMACIÓN A SUS TRABAJADORES SEGÚN *GRADO DE INFLUENCIA* QUE SUPUSIERON CIERTOS MOTIVOS PARA NO PROPORCIONAR FORMACIÓN
- EAL-25a. EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE INFLUENCIA QUE SUPUSIERON CIERTOS MOTIVOS PARA NO PROPORCIONAR FORMACIÓN 
- EAL-25b. EMPRESAS DE *50 O MÁS TRABAJADORES* QUE NO PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE INFLUENCIA QUE SUPUSIERON CIERTOS MOTIVOS PARA NO PROPORCIONAR FORMACIÓN 
- EAL-25c. EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE INFLUENCIA QUE SUPUSIERON CIERTOS MOTIVOS PARA NO PROPORCIONAR FORMACIÓN 
- EAL-25d. EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE INFLUENCIA QUE SUPUSIERON CIERTOS MOTIVOS PARA NO PROPORCIONAR FORMACIÓN
- EAL-25e. EMPRESAS DEL SECTOR *SERVICIOS* QUE NO PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN GRADO DE INFLUENCIA QUE SUPUSIERON CIERTOS MOTIVOS PARA NO PROPORCIONAR FORMACIÓN

# Librerías

In [1]:
import pandas as pd
import re
from pathlib import Path

# Documentos

In [68]:
EAL_25 = '../../Data/interim/EAL/2024/EAL-25.csv'
EAL_24 = '../../Data/interim/EAL/2024/EAL-24.csv'
EAL_23 = '../../Data/interim/EAL/2024/EAL-23.csv'

EAL_22 = '../../Data/interim/EAL/2024/EAL-22.csv'
EAL_21 = '../../Data/interim/EAL/2024/EAL-21.csv'
EAL_20 = '../../Data/interim/EAL/2024/EAL-20.csv'

EAL_17 = '../../Data/interim/EAL/2024/EAL-17.csv'
EAL_18 = '../../Data/interim/EAL/2024/EAL-18.csv'
EAL_18a = '../../Data/interim/EAL/2024/EAL-18a.csv'
EAL_18b = '../../Data/interim/EAL/2024/EAL-18b.csv'
EAL_18c = '../../Data/interim/EAL/2024/EAL-18c.csv'

In [3]:
OUTPUT_FILES = "../../Data/processed/EAL/2024"

# Funciones extracción

In [4]:
def process_eal17_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Nombres finales de las columnas numéricas
    columnas_valores = [
        "total_empresas",
        "empresas_formacion_total",
        "formacion_cursos_y_otros",
        "solo_cursos",
        "solo_otros_tipos_formacion",
        "empresas_no_formacion"
    ]

    # 3. Detectar columnas que contienen valores numéricos
    patron_numero = r"^\s*\d+(?:[,.]\d+)?\s*$"

    numeric_like = df.map(
        lambda x: bool(re.match(patron_numero, str(x)))
        if pd.notna(x) else False
    )

    value_cols = [
        col for col in df.columns[1:]
        if numeric_like[col].sum() > 0
    ]

    # En caso de que detecte más columnas, nos quedamos con las 6 principales
    if len(value_cols) != 6:
        counts = numeric_like.iloc[:, 1:].sum().sort_values(ascending=False)
        value_cols = sorted(counts[counts > 0].head(6).index.tolist())

    if len(value_cols) != 6:
        raise ValueError(f"Se esperaban 6 columnas numéricas, pero se detectaron {len(value_cols)}: {value_cols}")

    # 4. Crear dataframe base
    col_ambito = df.columns[0]

    df_out = df[[col_ambito] + value_cols].copy()
    df_out.columns = ["ambito"] + columnas_valores

    # 5. Convertir columnas numéricas
    for col in columnas_valores:
        df_out[col] = (
            df_out[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .str.replace("%", "", regex=False)
        )

        df_out[col] = pd.to_numeric(df_out[col], errors="coerce")

    # 6. Detectar filas de datos y filas de bloque
    is_data = df_out[columnas_valores].notna().sum(axis=1) > 0

    is_section = (
        df_out["ambito"].notna()
        & ~is_data
        & ~df_out["ambito"].astype(str).str.match(
            r"^EAL-|^Año\s+\d{4}|\(\d+\)",
            case=False,
            na=False
        )
    )

    # 7. Crear columna dimension
    df_out["dimension"] = df_out["ambito"].where(is_section).ffill()

    # 8. Quedarnos solo con filas con datos
    df_out = df_out[is_data].copy()

    # La primera fila TOTAL no tiene bloque previo
    df_out["dimension"] = df_out["dimension"].fillna("TOTAL")

    df_out.loc[
        df_out["ambito"].astype(str).str.upper().eq("TOTAL"),
        "dimension"
    ] = "TOTAL"

    # 9. Insertar metadatos
    df_out.insert(0, "anio", anio)
    df_out.insert(1, "tabla", tabla)
    df_out.insert(2, "pregunta", pregunta)

    # 10. Orden final
    df_out = df_out[
        [
            "anio",
            "tabla",
            "pregunta",
            "dimension",
            "ambito"
        ] + columnas_valores
    ].reset_index(drop=True)

    return df_out

EAL-23 A 25

In [5]:
def read_csv_categorias(doc_path):
    df = (
        pd.read_csv(doc_path, encoding="utf-8")
        .iloc[1:]
        .reset_index(drop=True)
        .rename(columns={
            "ENCUESTA ANUAL LABORAL": "ambito",
            "Unnamed: 1": "TOTAL",
            "Unnamed: 2": "NADA",
            "Unnamed: 3": "POCO",
            "Unnamed: 4": "BASTANTE",
            "EAL": "MUCHO"
        })
    )

    return df

In [6]:
def transformation(df, anio=2024, filas_debajo_eliminar=2):
    df = df.copy()

    col_texto = "ambito"
    patron_tabla = r"^(EAL-\d+[A-Za-z]?)"

    # Detectar código de tabla: EAL-25, EAL-25a, EAL-25b...
    tabla_detectada = (
        df[col_texto]
        .astype(str)
        .str.extract(patron_tabla, expand=False)
    )

    # Filas donde empieza una tabla
    mask_tabla = tabla_detectada.notna()

    # Pregunta completa asociada a cada bloque
    pregunta_detectada = (
        df[col_texto]
        .where(mask_tabla)
        .ffill()
        .astype(str)
        .str.replace(r"^EAL-\d+[A-Za-z]?\.\s*", "", regex=True)
    )

    # Insertar columnas al principio
    df.insert(0, "anio", anio)
    df.insert(1, "tabla", tabla_detectada.ffill())
    df.insert(2, "pregunta", pregunta_detectada)

    # Eliminar fila de pregunta + N filas inferiores
    mask_eliminar = pd.concat(
        [
            mask_tabla.shift(i, fill_value=False)
            for i in range(filas_debajo_eliminar + 1)
        ],
        axis=1
    ).any(axis=1)

    df = df.loc[~mask_eliminar].reset_index(drop=True)

    return df

In [7]:
def process_categorias(doc_path, anio=2024, filas_debajo_eliminar=2):
    df = read_csv_categorias(doc_path)
    df = transformation(
        df,
        anio=anio,
        filas_debajo_eliminar=filas_debajo_eliminar
    )

    return df

Función para formato largo

In [8]:
def to_long_format(
    df,
    id_vars,
    value_vars,
    var_name,
    value_name="porcentaje"
):
    df = df.copy()

    df_long = df.melt(
        id_vars=id_vars,
        value_vars=value_vars,
        var_name=var_name,
        value_name=value_name
    )

    df_long[value_name] = (
        df_long[value_name]
        .astype(str)
        .str.replace(",", ".", regex=False)
        .str.replace("%", "", regex=False)
    )

    df_long[value_name] = pd.to_numeric(
        df_long[value_name],
        errors="coerce"
    )

    df_long = df_long.dropna(subset=[value_name]).reset_index(drop=True)

    return df_long

Read csv con una sola tabla (EAL-20, EAL-21, EAL-22)

In [9]:
def read_csv_eal(doc_path):
    df = pd.read_csv(doc_path, encoding="utf-8", header=None)

    df = df.map(
        lambda x: re.sub(r"\s+", " ", str(x)).strip()
        if pd.notna(x) else pd.NA
    )

    df = df.replace(["", "nan", "NaN"], pd.NA)

    return df

EAL-22 CCAA

In [10]:
def process_ccaa_long(df, anio=2024):
    df = df.copy()

    # -----------------------------
    # 1. Extract table and question
    # -----------------------------
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
        ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # -----------------------------
    # 2. Detect CCAA header rows
    # -----------------------------
    ccaa_keywords = [
        "TOTAL", "ANDALUCÍA", "ARAGÓN", "ASTURIAS (PRINCIPADO DE)", "BALEARES (ILLES)",
        "CANARIAS", "CANTABRIA", "CASTILLA-LA MANCHA", "CASTILLA Y LEÓN", "CATALUÑA",
        "COMUNITAT VALENCIANA", "EXTREMADURA", "GALICIA", "MADRID (COMUNIDAD DE)",
        "MURCIA (REGIÓN DE)", "NAVARRA (COMUNIDAD FORAL DE)", "PAÍS VASCO", "RIOJA, LA"
    ]

    patron_ccaa = "|".join(re.escape(x) for x in ccaa_keywords)

    mask_headers = df.apply(
        lambda row: row.astype(str)
        .str.contains(patron_ccaa, case=False, regex=True)
        .sum() >= 2,
        axis=1
    )

    header_rows = df.index[mask_headers].tolist()

    # -----------------------------
    # 3. Process each horizontal block
    # -----------------------------
    bloques = []
    col_competencia = df.columns[0]

    for i, header_row in enumerate(header_rows):

        start_row = header_row + 1

        if i + 1 < len(header_rows):
            end_row = header_rows[i + 1]
        else:
            end_row = len(df)

        header = df.loc[header_row]

        value_cols = header[header.notna()].index.tolist()
        value_cols = [c for c in value_cols if c != col_competencia]

        nombres_ccaa = header[value_cols].tolist()

        block = df.loc[start_row:end_row - 1, [col_competencia] + value_cols].copy()

        block.columns = ["competencia"] + nombres_ccaa

        block = block[block["competencia"].notna()].copy()

        block_long = block.melt(
            id_vars="competencia",
            var_name="comunidad_autonoma",
            value_name="porcentaje"
        )

        bloques.append(block_long)

    # -----------------------------
    # 4. Concatenate and clean values
    # -----------------------------
    df_final = pd.concat(bloques, ignore_index=True)

    df_final["porcentaje"] = (
        df_final["porcentaje"]
        .astype(str)
        .str.replace(",", ".", regex=False)
        .str.replace("%", "", regex=False)
    )

    df_final["porcentaje"] = pd.to_numeric(
        df_final["porcentaje"],
        errors="coerce"
    )

    df_final = df_final.dropna(subset=["porcentaje"]).reset_index(drop=True)

    # -----------------------------
    # 5. Add metadata
    # -----------------------------
    df_final.insert(0, "anio", anio)
    df_final.insert(1, "tabla", tabla)
    df_final.insert(2, "pregunta", pregunta)

    return df_final

EAL-20 trabajadores

In [11]:
def process_trabajadores_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Columnas esperadas para tamaño de empresa
    columnas_trabajadores = [
        "TOTAL",
        "DE 5 A 9 TRABAJADORES",
        "DE 10 A 49 TRABAJADORES",
        "DE 50 A 249 TRABAJADORES",
        "DE 250 A 499 TRABAJADORES",
        "MÁS DE 499 TRABAJADORES"
    ]

    patron_trabajadores = "|".join(re.escape(x) for x in columnas_trabajadores)

    # 3. Detectar fila de cabecera
    mask_header = df.apply(
        lambda row: row.astype(str)
        .str.contains(patron_trabajadores, case=False, regex=True)
        .sum() >= 2,
        axis=1
    )

    header_row = df.index[mask_header][0]

    # 4. Detectar columnas donde están los tamaños de empresa
    header = df.loc[header_row]

    value_cols = header[
        header.astype(str).str.contains(
            patron_trabajadores,
            case=False,
            regex=True,
            na=False
        )
    ].index.tolist()

    nombres_columnas = header[value_cols].tolist()

    # 5. Extraer bloque de datos
    col_competencia = df.columns[0]

    df_trabajadores = df.loc[
        header_row + 1:,
        [col_competencia] + value_cols
    ].copy()

    df_trabajadores.columns = ["competencia"] + nombres_columnas

    # 6. Eliminar filas vacías o notas al pie
    df_trabajadores = df_trabajadores[
        df_trabajadores["competencia"].notna()
    ].copy()

    # 7. Convertir columnas numéricas
    for col in nombres_columnas:
        df_trabajadores[col] = (
            df_trabajadores[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .str.replace("%", "", regex=False)
        )

        df_trabajadores[col] = pd.to_numeric(
            df_trabajadores[col],
            errors="coerce"
        )

    # Eliminar notas o filas sin datos numéricos
    df_trabajadores = df_trabajadores.dropna(subset=["TOTAL"]).reset_index(drop=True)

    # 8. Insertar metadatos
    df_trabajadores.insert(0, "anio", anio)
    df_trabajadores.insert(1, "tabla", tabla)
    df_trabajadores.insert(2, "pregunta", pregunta)

    return df_trabajadores

EAL-21 SECTORES

In [12]:
def process_sector_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Detectar fila de cabecera
    columnas_sector = ["TOTAL", "INDUSTRIA", "CONSTRUCCIÓN", "SERVICIOS"]
    patron_sector = "|".join(re.escape(x) for x in columnas_sector)

    mask_header = df.apply(
        lambda row: row.astype(str)
        .str.contains(patron_sector, case=False, regex=True)
        .sum() >= 2,
        axis=1
    )

    header_row = df.index[mask_header][0]

    # 3. Detectar columnas donde están TOTAL, INDUSTRIA, etc.
    header = df.loc[header_row]

    value_cols = header[
        header.astype(str).str.contains(
            patron_sector,
            case=False,
            regex=True,
            na=False
        )
    ].index.tolist()

    nombres_columnas = header[value_cols].tolist()

    # 4. Extraer bloque de datos
    col_competencia = df.columns[0]

    df_sector = df.loc[
        header_row + 1:,
        [col_competencia] + value_cols
    ].copy()

    df_sector.columns = ["competencia"] + nombres_columnas

    # 5. Eliminar filas vacías o notas al pie
    df_sector = df_sector[df_sector["competencia"].notna()].copy()

    # 6. Convertir columnas numéricas
    for col in nombres_columnas:
        df_sector[col] = (
            df_sector[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .str.replace("%", "", regex=False)
        )

        df_sector[col] = pd.to_numeric(df_sector[col], errors="coerce")

    # Eliminar filas que no tengan datos numéricos en TOTAL
    df_sector = df_sector.dropna(subset=["TOTAL"]).reset_index(drop=True)

    # 7. Insertar metadatos
    df_sector.insert(0, "anio", anio)
    df_sector.insert(1, "tabla", tabla)
    df_sector.insert(2, "pregunta", pregunta)

    return df_sector

# Procesamiento

## EAL-17 (Fede también)

In [13]:
df_17_raw = read_csv_eal(EAL_17)
df_17 = process_eal17_wide(df_17_raw, anio=2024)

df_17.head()

,anio,tabla,pregunta,dimension,ambito,total_empresas,empresas_formacion_total,formacion_cursos_y_otros,solo_cursos,solo_otros_tipos_formacion,empresas_no_formacion
0,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TOTAL,TOTAL,100.0,73.468,60.220,25.366,14.415,26.532
1,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,De 5 a 9 trabajadores,100.0,65.319,51.321,28.014,20.665,34.681
2,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,De 10 a 49 trabajadores,100.0,79.228,64.481,25.163,10.356,20.772
3,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,De 50 a 249 trabajadores,100.0,94.759,79.559,15.091,5.349,5.241
4,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,De 250 a 499 trabajadores,100.0,98.371,85.856,11.710,2.434,1.629

In [14]:
df_17['dimension'].unique()

<StringArray>
['TOTAL', 'TAMAÑO DE LA EMPRESA', 'ACTIVIDAD ECONÓMICA', 'COMUNIDAD AUTÓNOMA']
Length: 4, dtype: str

In [15]:
df_17['ambito'].unique()

<StringArray>
[                                                                           'TOTAL',
                                                            'De 5 a 9 trabajadores',
                                                          'De 10 a 49 trabajadores',
                                                         'De 50 a 249 trabajadores',
                                                        'De 250 a 499 trabajadores',
                                                          'Más de 499 trabajadores',
                                                                        'Industria',
                                                                     'Construcción',
                                               'Comercio y reparación de vehículos',
                                                      'Transporte y almacenamiento',
                                                                       'Hostelería',
 'Información, comunicaciones, actividades financieras, de seguros e inmobiliarias',
                                'Actividades profesionales, científicas y técnicas',
                               'Actividades administrativas y servicios auxiliares',
       'Actividades artísticas, recreativas y de entretenimiento y otros servicios',
                                                                        'Andalucía',
                                                                           'Aragón',
                                                         'Asturias (Principado de)',
                                                                  'Balears (Illes)',
                                                                         'Canarias',
                                                                        'Cantabria',
                                                               'Castilla-La Mancha',
                                                                  'Castilla y León',
                                                                         'Cataluña',
                                                             'Comunitat Valenciana',
                                                                      'Extremadura',
                                                                          'Galicia',
                                                            'Madrid (Comunidad de)',
                                                               'Murcia (Región de)',
                                                     'Navarra (Comunidad Foral de)',
                                                                       'País Vasco',
                                                                        'Rioja, La']
Length: 32, dtype: str

### Subset

In [16]:
ambito_keep = ['TOTAL',
'Más de 499 trabajadores',
'Industria',
'Construcción',
'Comercio y reparación de vehículos',
'Transporte y almacenamiento',
'Hostelería',
'Actividades administrativas y servicios auxiliares',
'Actividades artísticas, recreativas y de entretenimiento y otros servicios',
'Andalucía',
'Cataluña',
'Comunitat Valenciana',
'Madrid (Comunidad de)',
'País Vasco',
]

df_17_subset = df_17[
    df_17["ambito"].isin(ambito_keep)
].copy()

In [17]:
df_17_subset

,anio,tabla,pregunta,dimension,ambito,total_empresas,empresas_formacion_total,formacion_cursos_y_otros,solo_cursos,solo_otros_tipos_formacion,empresas_no_formacion
0,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TOTAL,TOTAL,100.0,73.468,60.220,25.366,14.415,26.532
5,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,100.0,99.298,88.305,9.742,1.953,0.702
6,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Industria,100.0,76.222,64.223,20.911,14.866,23.778
7,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Construcción,100.0,77.713,61.593,29.467,8.940,22.287
8,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,100.0,73.959,62.349,23.788,13.863,26.041
9,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,100.0,77.405,55.376,34.796,9.828,22.595
10,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Hostelería,100.0,60.735,42.630,36.362,21.008,39.265
13,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,100.0,74.261,64.392,22.657,12.951,25.739
14,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",100.0,73.509,62.515,20.437,17.047,26.491
15,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Andalucía,100.0,73.324,53.315,31.577,15.109,26.676
23,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Cataluña,100.0,76.296,65.436,20.504,14.060,23.704
24,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,100.0,74.320,58.492,27.612,13.896,25.680
27,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),100.0,72.991,62.348,22.853,14.799,27.009
30,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,País Vasco,100.0,71.171,64.009,24.950,11.042,28.829

In [18]:
df_17_subset_long = to_long_format(
    df=df_17_subset,
    id_vars=["anio", "tabla", "pregunta", "dimension", "ambito"],
    value_vars=[
        "total_empresas",
        "empresas_formacion_total",
        "formacion_cursos_y_otros",
        "solo_cursos",
        "solo_otros_tipos_formacion",
        "empresas_no_formacion"
    ],
    var_name="indicador",
    value_name="porcentaje"
)

df_17_subset_long

,anio,tabla,pregunta,dimension,ambito,indicador,porcentaje
0,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TOTAL,TOTAL,total_empresas,100.000
1,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,total_empresas,100.000
2,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Industria,total_empresas,100.000
3,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Construcción,total_empresas,100.000
4,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,total_empresas,100.000
...,...,...,...,...,...,...,...
79,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Andalucía,empresas_no_formacion,26.676
80,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Cataluña,empresas_no_formacion,23.704
81,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,empresas_no_formacion,25.680
82,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),empresas_no_formacion,27.009
83,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,País Vasco,empresas_no_formacion,28.829

## EAL-18

In [62]:
def process_eal18_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Nombres finales de columnas numéricas
    columnas_valores = [
        "detectaron_total",
        "detectaron_proporcionaron_formacion",
        "detectaron_no_proporcionaron_formacion",
        "no_detectaron_total",
        "no_detectaron_proporcionaron_formacion",
        "no_detectaron_no_proporcionaron_formacion"
    ]

    # 3. Detectar columnas con valores numéricos
    patron_numero = r"^\s*\d+(?:[,.]\d+)?\s*$"

    numeric_like = df.map(
        lambda x: bool(re.match(patron_numero, str(x)))
        if pd.notna(x) else False
    )

    value_cols = [
        col for col in df.columns[1:]
        if numeric_like[col].sum() > 0
    ]

    value_cols = sorted(value_cols)

    if len(value_cols) != 6:
        raise ValueError(
            f"Se esperaban 6 columnas numéricas, pero se detectaron {len(value_cols)}: {value_cols}"
        )

    # 4. Crear dataframe base
    col_ambito = df.columns[0]

    df_out = df[[col_ambito] + value_cols].copy()
    df_out.columns = ["ambito"] + columnas_valores

    # 5. Convertir columnas numéricas
    for col in columnas_valores:
        df_out[col] = (
            df_out[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .str.replace("%", "", regex=False)
        )

        df_out[col] = pd.to_numeric(df_out[col], errors="coerce")

    # 6. Detectar filas con datos reales
    is_data = df_out[columnas_valores].notna().sum(axis=1) > 0

    # 7. Detectar filas de sección
    is_section = (
        df_out["ambito"].notna()
        & ~is_data
        & ~df_out["ambito"].astype(str).str.match(
            r"^EAL-|^Año\s+\d{4}|\(\d+\)",
            case=False,
            na=False
        )
    )

    # 8. Crear columna dimension
    df_out["dimension"] = df_out["ambito"].where(is_section).ffill()

    # 9. Quedarnos solo con filas con datos
    df_out = df_out[is_data].copy()

    # La fila TOTAL no tiene sección previa
    df_out["dimension"] = df_out["dimension"].fillna("TOTAL")

    df_out.loc[
        df_out["ambito"].astype(str).str.upper().eq("TOTAL"),
        "dimension"
    ] = "TOTAL"

    # 10. Añadir metadatos
    df_out.insert(0, "anio", anio)
    df_out.insert(1, "tabla", tabla)
    df_out.insert(2, "pregunta", pregunta)

    # 11. Orden final
    df_out = df_out[
        [
            "anio",
            "tabla",
            "pregunta",
            "dimension",
            "ambito"
        ] + columnas_valores
    ].reset_index(drop=True)

    return df_out

In [63]:
df_18_raw = read_csv_eal(EAL_18)
df_18 = process_eal18_wide(df_18_raw, anio=2024)

df_18.head()

,anio,tabla,pregunta,dimension,ambito,detectaron_total,detectaron_proporcionaron_formacion,detectaron_no_proporcionaron_formacion,no_detectaron_total,no_detectaron_proporcionaron_formacion,no_detectaron_no_proporcionaron_formacion
0,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TOTAL,TOTAL,29.123694,89.974511,10.025489,70.876306,66.570590,33.429410
1,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TAMAÑO DE LA EMPRESA,De 5 a 9 trabajadores,23.671862,83.544726,16.455274,76.328138,59.481181,40.518819
2,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TAMAÑO DE LA EMPRESA,De 10 a 49 trabajadores,31.724690,93.100741,6.899259,68.275310,72.749236,27.250764
3,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TAMAÑO DE LA EMPRESA,De 50 a 249 trabajadores,48.701094,98.742720,1.266525,51.298906,90.863612,9.136388
4,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TAMAÑO DE LA EMPRESA,De 250 a 499 trabajadores,58.708189,100.000000,0.000000,41.253364,96.831314,3.168686

### Subset

In [64]:
ambito_keep = ['TOTAL',
'Más de 499 trabajadores',
'Industria',
'Construcción',
'Comercio y reparación de vehículos',
'Transporte y almacenamiento',
'Hostelería',
'Actividades administrativas y servicios auxiliares',
'Actividades artísticas, recreativas y de entretenimiento y otros servicios',
'Andalucía',
'Cataluña',
'Comunitat Valenciana',
'Madrid (Comunidad de)',
'País Vasco',
]

df_18_subset = df_18[
    df_18["ambito"].isin(ambito_keep)
].copy()

In [65]:
df_18_subset

,anio,tabla,pregunta,dimension,ambito,detectaron_total,detectaron_proporcionaron_formacion,detectaron_no_proporcionaron_formacion,no_detectaron_total,no_detectaron_proporcionaron_formacion,no_detectaron_no_proporcionaron_formacion
0,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TOTAL,TOTAL,29.123694,89.974511,10.025489,70.876306,66.570590,33.429410
5,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,62.753623,99.769053,0.230947,37.246377,98.702983,1.297017
6,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Industria,29.340514,91.943067,8.063373,70.659486,69.761720,30.238280
7,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Construcción,27.053957,90.611641,9.388359,72.946043,73.016647,26.983353
8,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,28.467349,90.868950,9.131050,71.532651,67.384332,32.615668
9,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,25.901905,95.031299,4.968701,74.098095,71.218545,28.781455
10,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Hostelería,30.271329,82.452506,17.547494,69.728671,51.019961,48.980039
13,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,28.286468,93.127579,6.872421,71.713532,65.673438,34.326562
14,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",26.601052,89.684569,10.315431,73.398948,67.478218,32.521782
15,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Andalucía,27.268815,88.163346,11.836654,72.731185,67.635602,32.361933
23,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Cataluña,31.722109,90.311634,9.688366,68.277891,69.361787,30.638213
24,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,26.022668,94.221709,5.778291,73.977332,66.967668,33.035714
27,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),35.432441,91.263257,8.736743,64.567559,63.013225,36.986775
30,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,País Vasco,26.840242,92.489942,7.510058,73.159758,63.698237,36.301763

## EAL-18a (també Fede)

In [69]:
def process_eal18a_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Nombres finales de columnas numéricas
    columnas_valores = [
        "total",
        "cursos_empresa",
        "cursos_otra_organizacion",
        "formacion_puesto_trabajo",
        "aprendizaje_rotacion",
        "conferencias_seminarios"
    ]

    # 3. Detectar columnas con valores numéricos
    patron_numero = r"^\s*\d+(?:[,.]\d+)?\s*$"

    numeric_like = df.map(
        lambda x: bool(re.match(patron_numero, str(x)))
        if pd.notna(x) else False
    )

    value_cols = [
        col for col in df.columns[1:]
        if numeric_like[col].sum() > 0
    ]

    value_cols = sorted(value_cols)

    if len(value_cols) != 6:
        raise ValueError(
            f"Se esperaban 6 columnas numéricas, pero se detectaron {len(value_cols)}: {value_cols}"
        )

    # 4. Crear dataframe base
    col_ambito = df.columns[0]

    df_out = df[[col_ambito] + value_cols].copy()
    df_out.columns = ["ambito"] + columnas_valores

    # 5. Convertir columnas numéricas
    for col in columnas_valores:
        df_out[col] = (
            df_out[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .str.replace("%", "", regex=False)
        )

        df_out[col] = pd.to_numeric(df_out[col], errors="coerce")

    # 6. Detectar filas con datos
    is_data = df_out[columnas_valores].notna().sum(axis=1) > 0

    # 7. Detectar filas de bloque: TOTAL, TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA, CCAA...
    is_section = (
        df_out["ambito"].notna()
        & ~is_data
        & ~df_out["ambito"].astype(str).str.match(
            r"^EAL-|^Año\s+\d{4}|\(\d+\)",
            case=False,
            na=False
        )
    )

    # 8. Crear columna dimension
    df_out["dimension"] = df_out["ambito"].where(is_section).ffill()

    # 9. Quedarse solo con filas de datos reales
    df_out = df_out[is_data].copy()

    # La primera fila TOTAL no tiene sección previa
    df_out["dimension"] = df_out["dimension"].fillna("TOTAL")

    df_out.loc[
        df_out["ambito"].astype(str).str.upper().eq("TOTAL"),
        "dimension"
    ] = "TOTAL"

    # 10. Añadir metadatos
    df_out.insert(0, "anio", anio)
    df_out.insert(1, "tabla", tabla)
    df_out.insert(2, "pregunta", pregunta)

    # 11. Orden final
    df_out = df_out[
        [
            "anio",
            "tabla",
            "pregunta",
            "dimension",
            "ambito"
        ] + columnas_valores
    ].reset_index(drop=True)

    return df_out

In [70]:
df_18a_raw = read_csv_eal(EAL_18a)
df_18a = process_eal18a_wide(df_18a_raw, anio=2024)

df_18a.head()

,anio,tabla,pregunta,dimension,ambito,total,cursos_empresa,cursos_otra_organizacion,formacion_puesto_trabajo,aprendizaje_rotacion,conferencias_seminarios
0,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,73.468278,34.269329,73.709969,56.005492,27.375278,35.086542
1,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 5 a 9 trabajadores,65.319423,27.217848,65.989117,51.141371,22.937813,32.188656
2,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 10 a 49 trabajadores,79.227905,35.028637,79.002872,57.331022,29.277350,33.998708
3,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 50 a 249 trabajadores,94.759353,58.777973,84.135506,70.508861,36.475507,51.399249
4,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 250 a 499 trabajadores,98.385236,76.162564,85.384916,76.865963,46.697929,57.796014

### Subset

In [72]:
ambito_keep = ['TOTAL',
'Más de 499 trabajadores',
'Industria',
'Construcción',
'Comercio y reparación de vehículos',
'Transporte y almacenamiento',
'Hostelería',
'Actividades administrativas y servicios auxiliares',
'Actividades artísticas, recreativas y de entretenimiento y otros servicios',
'Andalucía',
'Cataluña',
'Comunitat Valenciana',
'Madrid (Comunidad de)',
'País Vasco',
]

df_18a_subset = df_18a[
    df_18a["ambito"].isin(ambito_keep)
].copy()

In [73]:
df_18a_subset

,anio,tabla,pregunta,dimension,ambito,total,cursos_empresa,cursos_otra_organizacion,formacion_puesto_trabajo,aprendizaje_rotacion,conferencias_seminarios
0,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,73.468278,34.269329,73.709969,56.005492,27.375278,35.086542
5,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,99.275362,85.450122,84.963504,80.048662,51.532847,65.596107
6,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Industria,76.222600,34.293577,76.121179,61.910901,36.081017,33.867169
7,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Construcción,77.712290,22.420652,84.768610,57.771672,21.273003,23.030251
8,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,73.958727,38.680615,71.445779,54.400700,29.940268,41.624315
9,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,77.406769,30.568829,79.668783,52.052104,24.258690,20.416312
10,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Hostelería,60.735371,25.970788,68.136490,54.371695,21.531100,13.127676
13,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,74.261496,36.374821,74.834256,60.200943,28.282414,39.518830
14,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",73.507801,40.519529,67.162337,57.172827,24.520269,43.228235
15,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Andalucía,73.324726,23.902570,76.823751,47.927417,26.162236,27.756719
23,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Cataluña,76.295600,37.301272,75.365660,58.316773,30.781002,41.250000
24,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,74.320098,38.074398,71.119340,55.536105,26.032654,32.280761
27,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),72.991275,41.842742,71.675800,58.771505,26.178157,38.468204
30,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,País Vasco,71.174036,44.731962,69.774107,58.917734,31.507080,36.791976

## EAL-18b (també Fede)

In [78]:
def process_eal18b_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Nombres finales de columnas numéricas
    columnas_valores = [
        "empresas_suspension_reduccion",
        "total_trabajadores_formados",
        "porcentaje_0",
        "mas_0_hasta_25",
        "mas_25_hasta_50",
        "mas_50_hasta_75",
        "mas_75_hasta_100",
        "porcentaje_100"
    ]

    # 3. Detectar columnas con valores numéricos
    patron_numero = r"^\s*\d+(?:[,.]\d+)?\s*$"

    numeric_like = df.map(
        lambda x: bool(re.match(patron_numero, str(x)))
        if pd.notna(x) else False
    )

    value_cols = [
        col for col in df.columns[1:]
        if numeric_like[col].sum() > 0
    ]

    value_cols = sorted(value_cols)

    if len(value_cols) != len(columnas_valores):
        raise ValueError(
            f"Se esperaban {len(columnas_valores)} columnas numéricas, "
            f"pero se detectaron {len(value_cols)}: {value_cols}"
        )

    # 4. Crear dataframe base
    col_ambito = df.columns[0]

    df_out = df[[col_ambito] + value_cols].copy()
    df_out.columns = ["ambito"] + columnas_valores

    # 5. Convertir columnas numéricas
    for col in columnas_valores:
        df_out[col] = (
            df_out[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .str.replace("%", "", regex=False)
        )

        df_out[col] = pd.to_numeric(df_out[col], errors="coerce")

    # 6. Detectar filas con datos reales
    is_data = df_out[columnas_valores].notna().sum(axis=1) > 0

    # 7. Detectar filas de bloque
    is_section = (
        df_out["ambito"].notna()
        & ~is_data
        & ~df_out["ambito"].astype(str).str.match(
            r"^EAL-|^Año\s+\d{4}|\(\d+\)",
            case=False,
            na=False
        )
    )

    # 8. Crear columna dimension
    df_out["dimension"] = df_out["ambito"].where(is_section).ffill()

    # 9. Quedarnos solo con filas de datos
    df_out = df_out[is_data].copy()

    df_out["dimension"] = df_out["dimension"].fillna("TOTAL")

    df_out.loc[
        df_out["ambito"].astype(str).str.upper().eq("TOTAL"),
        "dimension"
    ] = "TOTAL"

    # 10. Añadir metadatos
    df_out.insert(0, "anio", anio)
    df_out.insert(1, "tabla", tabla)
    df_out.insert(2, "pregunta", pregunta)

    # 11. Orden final
    df_out = df_out[
        [
            "anio",
            "tabla",
            "pregunta",
            "dimension",
            "ambito"
        ] + columnas_valores
    ].reset_index(drop=True)

    return df_out

In [80]:
df_18b_raw = read_csv_eal(EAL_18b)
df_18b = process_eal18b_wide(df_18b_raw, anio=2024)

df_18b.head()

,anio,tabla,pregunta,dimension,ambito,empresas_suspension_reduccion,total_trabajadores_formados,porcentaje_0,mas_0_hasta_25,mas_25_hasta_50,mas_50_hasta_75,mas_75_hasta_100,porcentaje_100
0,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,1.396570,100.0,81.299,13.061,1.327,2.022,0.420,1.871
1,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 5 a 9 trabajadores,0.763845,100.0,85.635,9.391,1.418,2.351,0.000,1.206
2,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 10 a 49 trabajadores,1.563983,100.0,82.378,13.232,0.000,2.052,0.312,2.025
3,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 50 a 249 trabajadores,3.367701,100.0,64.167,23.950,4.927,1.052,1.926,3.978
4,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 250 a 499 trabajadores,9.919262,100.0,69.215,19.402,4.646,0.000,3.834,2.904

### Subset

In [81]:
ambito_keep = ['TOTAL',
'Más de 499 trabajadores',
'Industria',
'Construcción',
'Comercio y reparación de vehículos',
'Transporte y almacenamiento',
'Hostelería',
'Actividades administrativas y servicios auxiliares',
'Actividades artísticas, recreativas y de entretenimiento y otros servicios',
'Andalucía',
'Cataluña',
'Comunitat Valenciana',
'Madrid (Comunidad de)',
'País Vasco',
]

df_18b_subset = df_18b[
    df_18b["ambito"].isin(ambito_keep)
].copy()

In [82]:
df_18b_subset

,anio,tabla,pregunta,dimension,ambito,empresas_suspension_reduccion,total_trabajadores_formados,porcentaje_0,mas_0_hasta_25,mas_25_hasta_50,mas_50_hasta_75,mas_75_hasta_100,porcentaje_100
0,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,1.396570,100.0,81.299,13.061,1.327,2.022,0.420,1.871
5,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,11.787440,100.0,66.136,26.049,5.791,1.364,0.325,0.334
6,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Industria,3.526077,100.0,79.042,12.156,0.385,1.863,0.546,6.008
7,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Construcción,0.131222,100.0,84.067,8.563,0.058,5.920,1.391,0.000
8,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,0.230648,100.0,85.276,11.029,1.964,0.000,0.000,1.732
9,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,0.851236,100.0,82.853,16.628,0.328,0.000,0.191,0.000
10,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Hostelería,2.805053,100.0,86.534,13.319,0.128,0.019,0.000,0.000
13,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,1.405949,100.0,85.590,9.907,3.315,0.094,1.094,0.000
14,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",1.002358,100.0,68.871,6.066,6.637,12.714,0.063,5.650
15,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Andalucía,1.949181,100.0,86.189,8.659,2.918,0.933,0.000,1.301
23,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Cataluña,1.726961,100.0,69.010,18.953,0.327,8.934,0.399,2.377
24,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,3.052366,100.0,79.585,19.840,0.112,0.463,0.000,0.000
27,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),0.416721,100.0,81.248,12.697,3.062,0.160,1.051,1.782
30,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,País Vasco,1.235827,100.0,66.394,19.083,0.000,0.000,0.000,14.523

## EAL-18c (també Fede)

In [85]:
def process_eal18c_wide(df, anio=2024):
    df = df.copy()

    # 1. Extraer tabla y pregunta
    values = df.stack().dropna().astype(str)

    titulo = values[
        values.str.match(r"^EAL-\d+[A-Za-z]?\.", na=False)
    ].iloc[0]

    tabla = re.match(r"^(EAL-\d+[A-Za-z]?)", titulo).group(1)

    pregunta = re.sub(
        r"^EAL-\d+[A-Za-z]?\.\s*",
        "",
        titulo
    )

    # 2. Nombre final de la columna numérica
    columna_valor = "porcentaje_formacion_seguridad_salud"

    # 3. Detectar columna con valores numéricos
    patron_numero = r"^\s*\d+(?:[,.]\d+)?\s*$"

    numeric_like = df.map(
        lambda x: bool(re.match(patron_numero, str(x)))
        if pd.notna(x) else False
    )

    value_cols = [
        col for col in df.columns[1:]
        if numeric_like[col].sum() > 0
    ]

    if len(value_cols) != 1:
        raise ValueError(
            f"Se esperaba 1 columna numérica, pero se detectaron {len(value_cols)}: {value_cols}"
        )

    value_col = value_cols[0]

    # 4. Crear dataframe base
    col_ambito = df.columns[0]

    df_out = df[[col_ambito, value_col]].copy()
    df_out.columns = ["ambito", columna_valor]

    # 5. Convertir columna numérica
    df_out[columna_valor] = (
        df_out[columna_valor]
        .astype(str)
        .str.replace(",", ".", regex=False)
        .str.replace("%", "", regex=False)
    )

    df_out[columna_valor] = pd.to_numeric(
        df_out[columna_valor],
        errors="coerce"
    )

    # 6. Detectar filas con datos reales
    is_data = df_out[columna_valor].notna()

    # 7. Detectar filas de sección
    is_section = (
        df_out["ambito"].notna()
        & ~is_data
        & ~df_out["ambito"].astype(str).str.match(
            r"^EAL-|^Año\s+\d{4}|\(\d+\)",
            case=False,
            na=False
        )
    )

    # 8. Crear columna dimension
    df_out["dimension"] = df_out["ambito"].where(is_section).ffill()

    # 9. Quedarnos solo con filas con datos
    df_out = df_out[is_data].copy()

    df_out["dimension"] = df_out["dimension"].fillna("TOTAL")

    df_out.loc[
        df_out["ambito"].astype(str).str.upper().eq("TOTAL"),
        "dimension"
    ] = "TOTAL"

    # 10. Añadir metadatos
    df_out.insert(0, "anio", anio)
    df_out.insert(1, "tabla", tabla)
    df_out.insert(2, "pregunta", pregunta)

    # 11. Orden final
    df_out = df_out[
        [
            "anio",
            "tabla",
            "pregunta",
            "dimension",
            "ambito",
            columna_valor
        ]
    ].reset_index(drop=True)

    return df_out

In [88]:
df_18c_raw = read_csv_eal(EAL_18c)
df_18c = process_eal18c_wide(df_18c_raw, anio=2024)

df_18c.head()

,anio,tabla,pregunta,dimension,ambito,porcentaje_formacion_seguridad_salud
0,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,75.813
1,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 5 a 9 trabajadores,68.611
2,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 10 a 49 trabajadores,81.343
3,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 50 a 249 trabajadores,92.156
4,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,De 250 a 499 trabajadores,95.577

### Subset

In [89]:
ambito_keep = ['TOTAL',
'Más de 499 trabajadores',
'Industria',
'Construcción',
'Comercio y reparación de vehículos',
'Transporte y almacenamiento',
'Hostelería',
'Actividades administrativas y servicios auxiliares',
'Actividades artísticas, recreativas y de entretenimiento y otros servicios',
'Andalucía',
'Cataluña',
'Comunitat Valenciana',
'Madrid (Comunidad de)',
'País Vasco',
]

df_18c_subset = df_18c[
    df_18c["ambito"].isin(ambito_keep)
].copy()

In [90]:
df_18c_subset

,anio,tabla,pregunta,dimension,ambito,porcentaje_formacion_seguridad_salud
0,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,75.813
5,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,96.501
6,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Industria,81.214
7,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Construcción,81.458
8,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,74.164
9,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,81.207
10,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Hostelería,73.552
13,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,75.604
14,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",69.206
15,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Andalucía,76.023
23,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Cataluña,79.948
24,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,81.864
27,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),74.704
30,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,País Vasco,62.846

## EAL-20

In [19]:
df_20_raw = read_csv_eal(EAL_20)
df_20 = process_trabajadores_wide(df_20_raw, anio=2024)

df_20.head()

,anio,tabla,pregunta,competencia,TOTAL,DE 5 A 9 TRABAJADORES,DE 10 A 49 TRABAJADORES,DE 50 A 249 TRABAJADORES,DE 250 A 499 TRABAJADORES,MÁS DE 499 TRABAJADORES
0,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,16.347340,15.343619,15.804993,22.430750,25.322392,30.510949
1,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,28.494848,29.855895,26.931117,28.578895,34.153966,33.333333
2,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,24.530267,27.373940,22.586210,19.846059,21.570926,27.055961
3,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,17.027644,15.670464,18.738422,15.816981,12.817507,13.333333
4,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,50.838810,48.254094,52.131239,56.943983,55.763970,54.014599

### Subset

In [20]:
cols_keep = [
    "anio",
    "tabla",
    "pregunta",
    "competencia",
    "TOTAL",
    "MÁS DE 499 TRABAJADORES"
]

df_20_subset = df_20[cols_keep].copy()

In [21]:
df_20_subset_long = to_long_format(
    df=df_20_subset,
    id_vars=["anio", "tabla", "pregunta", "competencia"],
    value_vars=["TOTAL", "MÁS DE 499 TRABAJADORES"],
    var_name="tamano_empresa",
    value_name="porcentaje"
)

In [22]:
df_20_subset_long

,anio,tabla,pregunta,competencia,tamano_empresa,porcentaje
0,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,TOTAL,16.347340
1,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,TOTAL,28.494848
2,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,TOTAL,24.530267
3,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,TOTAL,17.027644
4,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,TOTAL,50.838810
5,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De resolución de problemas (localización de pr...,TOTAL,11.209969
6,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,TOTAL,7.478712
7,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,TOTAL,12.666991
8,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,TOTAL,5.310919
9,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,TOTAL,1.254936
10,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,TOTAL,13.934268
11,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,MÁS DE 499 TRABAJADORES,30.510949
12,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,MÁS DE 499 TRABAJADORES,33.333333
13,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,MÁS DE 499 TRABAJADORES,27.055961
14,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,MÁS DE 499 TRABAJADORES,13.333333
15,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,MÁS DE 499 TRABAJADORES,54.014599
16,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De resolución de problemas (localización de pr...,MÁS DE 499 TRABAJADORES,13.187348
17,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,MÁS DE 499 TRABAJADORES,27.639903
18,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,MÁS DE 499 TRABAJADORES,25.109489
19,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,MÁS DE 499 TRABAJADORES,12.749392
20,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,MÁS DE 499 TRABAJADORES,2.822384
21,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,MÁS DE 499 TRABAJADORES,11.776156

## EAL-21

In [23]:
df_21_raw = read_csv_eal(EAL_21)
df_21 = process_sector_wide(df_21_raw, anio=2024)

df_21.head()

,anio,tabla,pregunta,competencia,TOTAL,INDUSTRIA,CONSTRUCCIÓN,SERVICIOS
0,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,16.347340,16.486105,15.703615,16.439153
1,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,28.494848,24.620076,24.630091,30.078036
2,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,24.530267,9.157845,5.801208,31.456162
3,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,17.027644,19.208171,14.684754,16.994533
4,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,50.838810,64.154498,66.288887,44.985817

### Subset

In [24]:
cols_keep = [
    "anio",
    "tabla",
    "pregunta",
    "competencia",
    "TOTAL",
    "SERVICIOS"
]

df_21_subset = df_21[cols_keep].copy()

In [25]:
df_21_subset_long = to_long_format(
    df=df_21,
    id_vars=["anio", "tabla", "pregunta", "competencia"],
    value_vars=["TOTAL", "SERVICIOS"],
    var_name="sector",
    value_name="porcentaje"
)

df_21_subset_long

,anio,tabla,pregunta,competencia,sector,porcentaje
0,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,TOTAL,16.347340
1,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,TOTAL,28.494848
2,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,TOTAL,24.530267
3,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,TOTAL,17.027644
4,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,TOTAL,50.838810
5,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De resolución de problemas (localización de pr...,TOTAL,11.209969
6,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,TOTAL,7.478712
7,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,TOTAL,12.666991
8,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,TOTAL,5.310919
9,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,TOTAL,1.254936
10,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,TOTAL,13.934268
11,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,SERVICIOS,16.439153
12,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,SERVICIOS,30.078036
13,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,SERVICIOS,31.456162
14,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,SERVICIOS,16.994533
15,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,SERVICIOS,44.985817
16,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De resolución de problemas (localización de pr...,SERVICIOS,10.889696
17,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,SERVICIOS,8.258975
18,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,SERVICIOS,13.841581
19,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,SERVICIOS,5.807584
20,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,SERVICIOS,1.266180
21,2024,EAL-21,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,SERVICIOS,13.401950

**Validación**
- 11 preguntas con 4 sectores equivalen a las 44 filas del df

## EAL-22

In [26]:
df_22_raw = read_csv_eal(EAL_22)
df_22_long = process_ccaa_long(df_22_raw, anio=2024)

In [27]:
df_22_long

,anio,tabla,pregunta,competencia,comunidad_autonoma,porcentaje
0,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,TOTAL,16.347340
1,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,TOTAL,28.494848
2,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,TOTAL,24.530267
3,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,TOTAL,17.027644
4,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,TOTAL,50.838810
...,...,...,...,...,...,...
193,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,"RIOJA, LA",5.816555
194,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,"RIOJA, LA",13.255034
195,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,"RIOJA, LA",3.131991
196,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,"RIOJA, LA",1.957494
197,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,"RIOJA, LA",11.129754

In [28]:
df_22_long['comunidad_autonoma'].unique()

<StringArray>
[                       'TOTAL',                    'ANDALUCÍA',
                       'ARAGÓN',     'ASTURIAS (PRINCIPADO DE)',
              'BALEARS (ILLES)',                     'CANARIAS',
                    'CANTABRIA',           'CASTILLA-LA MANCHA',
              'CASTILLA Y LEÓN',                     'CATALUÑA',
         'COMUNITAT VALENCIANA',                  'EXTREMADURA',
                      'GALICIA',        'MADRID (COMUNIDAD DE)',
           'MURCIA (REGIÓN DE)', 'NAVARRA (COMUNIDAD FORAL DE)',
                   'PAÍS VASCO',                    'RIOJA, LA']
Length: 18, dtype: str

**Validación**
- 18 CCAA en el documento excel
- 11 preguntas con 18 CCAA equivalen a las 198 filas del df

### Subset

In [29]:
ccaa_keep = [
    "TOTAL",
    "CATALUÑA",
    "MADRID (COMUNIDAD DE)",
    "ANDALUCÍA",
    "PAÍS VASCO",
    "COMUNITAT VALENCIANA"
]

df_22_subset_long = df_22_long[
    df_22_long["comunidad_autonoma"].isin(ccaa_keep)
].copy()

df_22_subset_long

,anio,tabla,pregunta,competencia,comunidad_autonoma,porcentaje
0,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,TOTAL,16.347340
1,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,TOTAL,28.494848
2,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,TOTAL,24.530267
3,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,TOTAL,17.027644
4,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,TOTAL,50.838810
...,...,...,...,...,...,...
182,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,PAÍS VASCO,10.510789
183,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,PAÍS VASCO,9.794336
184,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,PAÍS VASCO,7.021241
185,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,PAÍS VASCO,0.134862
186,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,PAÍS VASCO,11.126096

## EAL-23

In [30]:
df_23 = process_categorias(EAL_23)

In [31]:
df_23

,anio,tabla,pregunta,ambito,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Responder a un sistema predeterminado de promo...,100,24.833,42.321,26.86,5.987
1,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Readaptar al personal a los cambios técnicos i...,100,12.615,22.193,49.421,15.771
2,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Readaptar al personal a los cambios organizati...,100,14.246,29.411,44.323,12.02
3,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Adaptar al personal recién incorporado a las t...,100,7.888,15.038,50.533,26.541
4,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Mejorar la cualificación básica del personal p...,100,8.168,22.567,51.043,18.222
5,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Adaptación impuesta por cambios normativos,100,8.955,22.904,42.755,25.385
6,2024,EAL-23a,EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCION...,Responder a un sistema predeterminado de promo...,100,26.215,42.352,25.663,5.77
7,2024,EAL-23a,EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCION...,Readaptar al personal a los cambios técnicos i...,100,13.406,22.523,48.979,15.093
8,2024,EAL-23a,EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCION...,Readaptar al personal a los cambios organizati...,100,14.992,29.748,43.875,11.385
9,2024,EAL-23a,EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCION...,Adaptar al personal recién incorporado a las t...,100,8.366,15.287,50.501,25.846
10,2024,EAL-23a,EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCION...,Mejorar la cualificación básica del personal p...,100,8.508,22.676,50.974,17.842
11,2024,EAL-23a,EMPRESAS DE 5 A 49 TRABAJADORES QUE PROPORCION...,Adaptación impuesta por cambios normativos,100,9.245,22.663,42.547,25.545
12,2024,EAL-23b,EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCI...,Responder a un sistema predeterminado de promo...,100,12.656,42.521,37.171,7.652
13,2024,EAL-23b,EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCI...,Readaptar al personal a los cambios técnicos i...,100,5.686,19.516,53.359,21.44
14,2024,EAL-23b,EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCI...,Readaptar al personal a los cambios organizati...,100,7.78,26.446,48.185,17.589
15,2024,EAL-23b,EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCI...,Adaptar al personal recién incorporado a las t...,100,3.731,13.026,50.737,32.506
16,2024,EAL-23b,EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCI...,Mejorar la cualificación básica del personal p...,100,5.099,21.391,51.774,21.736
17,2024,EAL-23b,EMPRESAS DE 50 A 499 TRABAJADORES QUE PROPORCI...,Adaptación impuesta por cambios normativos,100,6.494,25.048,44.465,23.994
18,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Responder a un sistema predeterminado de promo...,100,7.551,36.456,44.463,11.53
19,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Readaptar al personal a los cambios técnicos i...,100,2.345,15.439,54.421,27.794
20,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Readaptar al personal a los cambios organizati...,100,3.682,25.152,50.874,20.292
21,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Adaptar al personal recién incorporado a las t...,100,1.267,9.804,51.856,37.073
22,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Mejorar la cualificación básica del personal p...,100,4.796,23.62,50.479,21.105
23,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Adaptación impuesta por cambios normativos,100,4.237,25.702,46.8,23.261
24,2024,EAL-23d,EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FO...,Responder a un sistema predeterminado de promo...,100,23.083,44.985,27.291,4.641
25,2024,EAL-23d,EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FO...,Readaptar al personal a los cambios técnicos i...,100,10.579,20.232,52.653,16.536
26,2024,EAL-23d,EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FO...,Readaptar al personal a los cambios organizati...,100,12.616,29.389,47.951,10.044
27,2024,EAL-23d,EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FO...,Adaptar al personal recién incorporado a las t...,100,7.527,13.819,52.765,25.889
28,2024,EAL-23d,EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FO...,Mejorar la cualificación básica del personal p...,100,8.622,20.749,54.127,16.502
29,2024,EAL-23d,EMPRESAS DE LA INDUSTRIA QUE PROPORCIONARON FO...,Adaptación impuesta por cambios normativos,100,9.336,21.57,45.944,23.15
30,2024,EAL-23e,EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON...,Responder a un sistema predeterminado de promo...,100,26.644,45.327,23.875,4.154
31,2024,EAL-23e,EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON...,Readaptar al personal a los cambios técnicos i...,100,13.994,28.679,46.599,10.728
32,2024,EAL-23e,EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON...,Readaptar al personal a los cambios organizati...,100,16.786,33.498,41.561,8.155
33,2024,EAL-23e,EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON...,Adaptar al personal recién incorporado a las t...,100,8.741,16.595,52.589,22.075
34,2024,EAL-23e,EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON...,Mejorar la cualificación básica del personal p...,100,7.393,20.185,53.103,19.32
35,2024,EAL-23e,EMPRESAS DE LA CONSTRUCCIÓN QUE PROPORCIONARON...,Adaptación impuesta por cambios normativos,100,7.167,18.34,48.138,26.356
36,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Responder a un sistema predeterminado de promo...,100,24.872,41.166,27.332,6.63
37,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Readaptar al personal a los cambios técnicos i...,100,12.8,21.391,49.249,16.561
38,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Readaptar al personal a los cambios organizati...,100,14.121,28.64,44.052,13.187
39,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Adaptar al personal recién incorporado a las t...,100,7.805,15.009,49.654,27.532
40,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Mejorar la cualificación básica del personal p...,100,8.216,23.417,49.976,18.391
41,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Adaptación impuesta por cambios normativos,100,9.211,24.064,41.034,25.691

In [32]:
df_23['tabla'].unique()

<StringArray>
['EAL-23', 'EAL-23a', 'EAL-23b', 'EAL-23c', 'EAL-23d', 'EAL-23e', 'EAL-23f']
Length: 7, dtype: str

**Validación**  
- Comprobado el número de filas finales con el excel inicial (7 tablas de 6 filas de resultados)
- Los decimales son correctos, en el excel solo se muestra un decimal pero si se mueve la coma se ven todos los que aparecen en el df importado

### Subset datos relevantes

In [33]:
df_23['tabla'].unique()

<StringArray>
['EAL-23', 'EAL-23a', 'EAL-23b', 'EAL-23c', 'EAL-23d', 'EAL-23e', 'EAL-23f']
Length: 7, dtype: str

In [34]:
col_keep = ['EAL-23', 'EAL-23c', 'EAL-23f']

df_23_subset = df_23[df_23["tabla"].isin(col_keep)].copy()

In [35]:
df_23_subset

,anio,tabla,pregunta,ambito,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Responder a un sistema predeterminado de promo...,100,24.833,42.321,26.86,5.987
1,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Readaptar al personal a los cambios técnicos i...,100,12.615,22.193,49.421,15.771
2,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Readaptar al personal a los cambios organizati...,100,14.246,29.411,44.323,12.02
3,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Adaptar al personal recién incorporado a las t...,100,7.888,15.038,50.533,26.541
4,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Mejorar la cualificación básica del personal p...,100,8.168,22.567,51.043,18.222
5,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Adaptación impuesta por cambios normativos,100,8.955,22.904,42.755,25.385
18,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Responder a un sistema predeterminado de promo...,100,7.551,36.456,44.463,11.53
19,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Readaptar al personal a los cambios técnicos i...,100,2.345,15.439,54.421,27.794
20,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Readaptar al personal a los cambios organizati...,100,3.682,25.152,50.874,20.292
21,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Adaptar al personal recién incorporado a las t...,100,1.267,9.804,51.856,37.073
22,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Mejorar la cualificación básica del personal p...,100,4.796,23.62,50.479,21.105
23,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Adaptación impuesta por cambios normativos,100,4.237,25.702,46.8,23.261
36,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Responder a un sistema predeterminado de promo...,100,24.872,41.166,27.332,6.63
37,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Readaptar al personal a los cambios técnicos i...,100,12.8,21.391,49.249,16.561
38,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Readaptar al personal a los cambios organizati...,100,14.121,28.64,44.052,13.187
39,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Adaptar al personal recién incorporado a las t...,100,7.805,15.009,49.654,27.532
40,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Mejorar la cualificación básica del personal p...,100,8.216,23.417,49.976,18.391
41,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Adaptación impuesta por cambios normativos,100,9.211,24.064,41.034,25.691

## EAL-24

In [36]:
df_24 = process_categorias(EAL_24)

In [37]:
df_24['tabla'].unique()

<StringArray>
['EAL-24', 'EAL-24a', 'EAL-24b', 'EAL-24c', 'EAL-24d', 'EAL-24e', 'EAL-24f']
Length: 7, dtype: str

**Validación**  
- Comprobado el número de filas finales con el excel inicial (6 tablas de 10 filas de resultados)
- Los decimales son correctos, en el excel solo se muestra un decimal pero si se mueve la coma se ven todos los que aparecen en el df importado

### Subset datos relevantes

In [38]:
df_24['tabla'].unique()

<StringArray>
['EAL-24', 'EAL-24a', 'EAL-24b', 'EAL-24c', 'EAL-24d', 'EAL-24e', 'EAL-24f']
Length: 7, dtype: str

In [39]:
col_keep = ['EAL-24', 'EAL-24c', 'EAL-24f']

df_24_subset = df_24[df_24["tabla"].isin(col_keep)].copy()

In [40]:
df_24_subset

,anio,tabla,pregunta,ambito,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,El nivel de formación de los empleados era el ...,100,8.964,19.548,53.724,17.765
1,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La empresa prefirió contratar a personal con l...,100,21.954,25.684,39.843,12.519
2,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Dificultad para evaluar la necesidades de form...,100,31.45,51.904,14.719,1.928
3,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La falta de cursos de formación adecuados en e...,100,26.775,45.123,20.708,7.394
4,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,El alto coste de los cursos de formación,100,21.532,36.681,28.491,13.295
5,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La empresa prefirió tener personal con contrat...,100,68.584,23.204,6.415,1.797
6,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,El mayor esfuerzo realizado en años anteriores...,100,32.592,42.286,20.426,4.696
7,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La elevada carga de trabajo y el escaso tiempo...,100,15.221,28.392,39.031,17.356
8,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Dificultad para acceder a ayudas o subvencione...,100,25.833,36.915,23.157,14.095
9,2024,EAL-24,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras razones,100,68.296,22.73,5.969,3.004
30,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,El nivel de formación de los empleados era el ...,100,12.96,33.75,47.697,5.594
31,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La empresa prefirió contratar a personal con l...,100,16.438,45.815,31.742,6.005
32,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Dificultad para evaluar la necesidades de form...,100,31.285,55.211,12.062,1.442
33,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La falta de cursos de formación adecuados en e...,100,26.306,53.799,17.182,2.713
34,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,El alto coste de los cursos de formación,100,17.847,44.584,30.667,6.903
35,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La empresa prefirió tener personal con contrat...,100,67.016,27.424,5.012,0.548
36,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,El mayor esfuerzo realizado en años anteriores...,100,30.689,47.535,19.701,2.075
37,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La elevada carga de trabajo y el escaso tiempo...,100,10.645,34.299,41.209,13.847
38,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Dificultad para acceder a ayudas o subvencione...,100,32.125,44.83,17.307,5.739
39,2024,EAL-24c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Otras razones,100,66.751,25.775,5.614,1.86
60,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,El nivel de formación de los empleados era el ...,100,9.804,19.018,52.966,18.212
61,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La empresa prefirió contratar a personal con l...,100,22.127,24.242,40.054,13.577
62,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Dificultad para evaluar la necesidades de form...,100,31.896,51.337,14.996,1.771
63,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La falta de cursos de formación adecuados en e...,100,27.241,45.197,20.15,7.413
64,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,El alto coste de los cursos de formación,100,21.275,36.415,28.771,13.539
65,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La empresa prefirió tener personal con contrat...,100,69.942,22.01,6.172,1.876
66,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,El mayor esfuerzo realizado en años anteriores...,100,34.423,42.09,19.098,4.389
67,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La elevada carga de trabajo y el escaso tiempo...,100,15.595,28.249,38.791,17.365
68,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Dificultad para acceder a ayudas o subvencione...,100,26.134,36.469,22.508,14.89
69,2024,EAL-24f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Otras razones,100,69.01,21.876,5.87,3.245

## EAL-25

In [41]:
df_25 = process_categorias(EAL_25)

In [42]:
df_25

,anio,tabla,pregunta,ambito,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El nivel de formación de los empleados era el ...,100,7.497,11.745,48.18,32.578
1,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió contratar a personal con l...,100,16.991,14.927,45.484,22.598
2,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para evaluar la necesidades de form...,100,33.929,46.144,15.427,4.501
3,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La falta de cursos de formación adecuados en e...,100,32.974,40.854,18.727,7.444
4,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El alto coste de los cursos de formación,100,32.154,34.644,22.305,10.896
5,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió tener personal con contrat...,100,69.386,20.775,7.963,1.875
6,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El mayor esfuerzo realizado en años anteriores...,100,42.478,33.815,18.795,4.912
7,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La elevada carga de trabajo y el escaso tiempo...,100,23.112,29.498,30.973,16.417
8,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para acceder a ayudas o subvencione...,100,36.386,31.367,20.381,11.866
9,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Otras razones,100,63.988,21.749,7.994,6.269
10,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,El nivel de formación de los empleados era el ...,100,7.412,11.741,48.169,32.679
11,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,La empresa prefirió contratar a personal con l...,100,16.933,14.912,45.532,22.623
12,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,Dificultad para evaluar la necesidades de form...,100,33.964,46.106,15.4,4.53
13,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,La falta de cursos de formación adecuados en e...,100,32.925,40.784,18.826,7.465
14,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,El alto coste de los cursos de formación,100,32.082,34.621,22.4,10.896
15,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,La empresa prefirió tener personal con contrat...,100,69.529,20.622,7.951,1.898
16,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,El mayor esfuerzo realizado en años anteriores...,100,42.562,33.738,18.726,4.975
17,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,La elevada carga de trabajo y el escaso tiempo...,100,23.035,29.488,31.004,16.473
18,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,Dificultad para acceder a ayudas o subvencione...,100,36.4,31.288,20.423,11.888
19,2024,EAL-25a,EMPRESAS DE 5 A 49 TRABAJADORES QUE NO PROPORC...,Otras razones,100,64.149,21.632,8,6.218
20,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El nivel de formación de los empleados era el ...,100,13.937,12.085,49.03,24.948
21,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La empresa prefirió contratar a personal con l...,100,21.345,16.108,41.856,20.691
22,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Dificultad para evaluar la necesidades de form...,100,31.261,48.978,17.449,2.312
23,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La falta de cursos de formación adecuados en e...,100,36.665,46.178,11.29,5.867
24,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El alto coste de los cursos de formación,100,37.611,36.39,15.092,10.907
25,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La empresa prefirió tener personal con contrat...,100,58.533,32.396,8.904,0.166
26,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El mayor esfuerzo realizado en años anteriores...,100,36.081,39.704,24.049,0.166
27,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La elevada carga de trabajo y el escaso tiempo...,100,28.984,30.222,28.625,12.169
28,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Dificultad para acceder a ayudas o subvencione...,100,35.266,37.366,17.212,10.155
29,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Otras razones,100,51.771,30.562,7.505,10.162
30,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,El nivel de formación de los empleados era el ...,100,13.214,7.434,49.004,30.347
31,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,La empresa prefirió contratar a personal con l...,100,25.095,14.558,43.075,17.273
32,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,Dificultad para evaluar la necesidades de form...,100,37.041,46.399,12.945,3.616
33,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,La falta de cursos de formación adecuados en e...,100,33.867,36.866,22.171,7.096
34,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,El alto coste de los cursos de formación,100,37.267,35.115,18.993,8.625
35,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,La empresa prefirió tener personal con contrat...,100,66.354,26.541,5.327,1.779
36,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,El mayor esfuerzo realizado en años anteriores...,100,36.851,33.204,22.792,7.154
37,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,La elevada carga de trabajo y el escaso tiempo...,100,27.894,29.472,28.819,13.815
38,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,Dificultad para acceder a ayudas o subvencione...,100,37.393,35.11,19.182,8.315
39,2024,EAL-25c,EMPRESAS DE LA INDUSTRIA QUE NO PROPORCIONARON...,Otras razones,100,64.884,24.289,7.065,3.762
40,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,El nivel de formación de los empleados era el ...,100,7.691,10.23,51.07,31.01
41,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,La empresa prefirió contratar a personal con l...,100,14.642,10.337,47.549,27.472
42,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,Dificultad para evaluar la necesidades de form...,100,33.076,46.938,18.784,1.201
43,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,La falta de cursos de formación adecuados en e...,100,30.729,42.589,17.272,9.409
44,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,El alto coste de los cursos de formación,100,31.002,39.195,20.201,9.602
45,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,La empresa prefirió tener personal con contrat...,100,68.365,19.871,9.176,2.588
46,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,El mayor esfuerzo realizado en años anteriores...,100,38.623,31.368,25.005,5.004
47,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,La elevada carga de trabajo y el escaso tiempo...,100,22.019,28.502,37.624,11.854
48,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,Dificultad para acceder a ayudas o subvencione...,100,36.437,32.349,20.796,10.418
49,2024,EAL-25d,EMPRESAS DE LA CONSTRUCCIÓN QUE NO PROPORCIONA...,Otras razones,100,64.002,21.277,9.319,5.402
50,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El nivel de formación de los empleados era el ...,100,6.457,12.723,47.626,33.194
51,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió contratar a personal con l...,100,15.886,15.641,45.619,22.854
52,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para evaluar la necesidades de form...,100,33.498,45.986,15.393,5.123
53,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La falta de cursos de formación adecuados en e...,100,33.133,41.316,18.323,7.229
54,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El alto coste de los cursos de formación,100,31.411,33.919,23.188,11.481
55,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió tener personal con contrat...,100,70.067,19.881,8.26,1.792
56,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El mayor esfuerzo realizado en años anteriores...,100,44.018,34.269,17.211,4.502
57,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La elevada carga de trabajo y el escaso tiempo...,100,22.419,29.643,30.416,17.522
58,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para acceder a ayudas o subvencione...,100,36.2,30.566,20.535,12.699
59,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Otras razones,100,63.827,21.365,7.972,6.836

In [43]:
df_25['TOTAL'].unique()

<StringArray>
['100']
Length: 1, dtype: str

In [44]:
df_25['tabla'].unique()

<StringArray>
['EAL-25', 'EAL-25a', 'EAL-25b', 'EAL-25c', 'EAL-25d', 'EAL-25e']
Length: 6, dtype: str

In [45]:
df_25_long = to_long_format(
    df=df_25,
    id_vars=["anio", "tabla", "pregunta", "ambito"],
    value_vars=["NADA", "POCO", "BASTANTE", "MUCHO"],
    var_name="categoria",
    value_name="porcentaje"
)

In [46]:
df_25_long

,anio,tabla,pregunta,ambito,categoria,porcentaje
0,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El nivel de formación de los empleados era el ...,NADA,7.497
1,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió contratar a personal con l...,NADA,16.991
2,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para evaluar la necesidades de form...,NADA,33.929
3,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La falta de cursos de formación adecuados en e...,NADA,32.974
4,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El alto coste de los cursos de formación,NADA,32.154
...,...,...,...,...,...,...
235,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió tener personal con contrat...,MUCHO,1.792
236,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El mayor esfuerzo realizado en años anteriores...,MUCHO,4.502
237,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La elevada carga de trabajo y el escaso tiempo...,MUCHO,17.522
238,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para acceder a ayudas o subvencione...,MUCHO,12.699
239,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Otras razones,MUCHO,6.836

In [47]:
df_25_long['categoria'].unique()

<StringArray>
['NADA', 'POCO', 'BASTANTE', 'MUCHO']
Length: 4, dtype: str

La categoria total siempre es 100, así que se elimina

**Validación**  
- Comprobado el número de filas finales con el excel inicial (6 tablas de 10 filas de resultados)
- Los decimales son correctos, en el excel solo se muestra un decimal pero si se mueve la coma se ven todos los que aparecen en el df importado

### Subset con datos relevantes para nuestro caso

In [48]:
df_25['tabla'].unique()

<StringArray>
['EAL-25', 'EAL-25a', 'EAL-25b', 'EAL-25c', 'EAL-25d', 'EAL-25e']
Length: 6, dtype: str

In [49]:
col_keep = ['EAL-25', 'EAL-25b', 'EAL-25e']

df_25_subset = df_25[df_25["tabla"].isin(col_keep)].copy()

In [50]:
df_25_subset

,anio,tabla,pregunta,ambito,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El nivel de formación de los empleados era el ...,100,7.497,11.745,48.18,32.578
1,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió contratar a personal con l...,100,16.991,14.927,45.484,22.598
2,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para evaluar la necesidades de form...,100,33.929,46.144,15.427,4.501
3,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La falta de cursos de formación adecuados en e...,100,32.974,40.854,18.727,7.444
4,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El alto coste de los cursos de formación,100,32.154,34.644,22.305,10.896
5,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió tener personal con contrat...,100,69.386,20.775,7.963,1.875
6,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El mayor esfuerzo realizado en años anteriores...,100,42.478,33.815,18.795,4.912
7,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La elevada carga de trabajo y el escaso tiempo...,100,23.112,29.498,30.973,16.417
8,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para acceder a ayudas o subvencione...,100,36.386,31.367,20.381,11.866
9,2024,EAL-25,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Otras razones,100,63.988,21.749,7.994,6.269
20,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El nivel de formación de los empleados era el ...,100,13.937,12.085,49.03,24.948
21,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La empresa prefirió contratar a personal con l...,100,21.345,16.108,41.856,20.691
22,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Dificultad para evaluar la necesidades de form...,100,31.261,48.978,17.449,2.312
23,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La falta de cursos de formación adecuados en e...,100,36.665,46.178,11.29,5.867
24,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El alto coste de los cursos de formación,100,37.611,36.39,15.092,10.907
25,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La empresa prefirió tener personal con contrat...,100,58.533,32.396,8.904,0.166
26,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El mayor esfuerzo realizado en años anteriores...,100,36.081,39.704,24.049,0.166
27,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La elevada carga de trabajo y el escaso tiempo...,100,28.984,30.222,28.625,12.169
28,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Dificultad para acceder a ayudas o subvencione...,100,35.266,37.366,17.212,10.155
29,2024,EAL-25b,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Otras razones,100,51.771,30.562,7.505,10.162
50,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El nivel de formación de los empleados era el ...,100,6.457,12.723,47.626,33.194
51,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió contratar a personal con l...,100,15.886,15.641,45.619,22.854
52,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para evaluar la necesidades de form...,100,33.498,45.986,15.393,5.123
53,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La falta de cursos de formación adecuados en e...,100,33.133,41.316,18.323,7.229
54,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El alto coste de los cursos de formación,100,31.411,33.919,23.188,11.481
55,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió tener personal con contrat...,100,70.067,19.881,8.26,1.792
56,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El mayor esfuerzo realizado en años anteriores...,100,44.018,34.269,17.211,4.502
57,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La elevada carga de trabajo y el escaso tiempo...,100,22.419,29.643,30.416,17.522
58,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para acceder a ayudas o subvencione...,100,36.2,30.566,20.535,12.699
59,2024,EAL-25e,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Otras razones,100,63.827,21.365,7.972,6.836

## DF FORMACION TIPO (EAL-17)

In [51]:
df_formacion_tipo = df_17_subset.copy()
df_formacion_tipo

,anio,tabla,pregunta,dimension,ambito,total_empresas,empresas_formacion_total,formacion_cursos_y_otros,solo_cursos,solo_otros_tipos_formacion,empresas_no_formacion
0,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TOTAL,TOTAL,100.0,73.468,60.220,25.366,14.415,26.532
5,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,100.0,99.298,88.305,9.742,1.953,0.702
6,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Industria,100.0,76.222,64.223,20.911,14.866,23.778
7,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Construcción,100.0,77.713,61.593,29.467,8.940,22.287
8,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,100.0,73.959,62.349,23.788,13.863,26.041
9,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,100.0,77.405,55.376,34.796,9.828,22.595
10,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Hostelería,100.0,60.735,42.630,36.362,21.008,39.265
13,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,100.0,74.261,64.392,22.657,12.951,25.739
14,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",100.0,73.509,62.515,20.437,17.047,26.491
15,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Andalucía,100.0,73.324,53.315,31.577,15.109,26.676
23,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Cataluña,100.0,76.296,65.436,20.504,14.060,23.704
24,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,100.0,74.320,58.492,27.612,13.896,25.680
27,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),100.0,72.991,62.348,22.853,14.799,27.009
30,2024,EAL-17,EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TA...,COMUNIDAD AUTÓNOMA,País Vasco,100.0,71.171,64.009,24.950,11.042,28.829

## DF FORMACION NECESIDADES (EAL-18)

In [66]:
df_formacion_necesidades = df_18_subset.copy()
df_formacion_necesidades

,anio,tabla,pregunta,dimension,ambito,detectaron_total,detectaron_proporcionaron_formacion,detectaron_no_proporcionaron_formacion,no_detectaron_total,no_detectaron_proporcionaron_formacion,no_detectaron_no_proporcionaron_formacion
0,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TOTAL,TOTAL,29.123694,89.974511,10.025489,70.876306,66.570590,33.429410
5,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,62.753623,99.769053,0.230947,37.246377,98.702983,1.297017
6,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Industria,29.340514,91.943067,8.063373,70.659486,69.761720,30.238280
7,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Construcción,27.053957,90.611641,9.388359,72.946043,73.016647,26.983353
8,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,28.467349,90.868950,9.131050,71.532651,67.384332,32.615668
9,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,25.901905,95.031299,4.968701,74.098095,71.218545,28.781455
10,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Hostelería,30.271329,82.452506,17.547494,69.728671,51.019961,48.980039
13,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,28.286468,93.127579,6.872421,71.713532,65.673438,34.326562
14,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",26.601052,89.684569,10.315431,73.398948,67.478218,32.521782
15,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Andalucía,27.268815,88.163346,11.836654,72.731185,67.635602,32.361933
23,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Cataluña,31.722109,90.311634,9.688366,68.277891,69.361787,30.638213
24,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,26.022668,94.221709,5.778291,73.977332,66.967668,33.035714
27,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),35.432441,91.263257,8.736743,64.567559,63.013225,36.986775
30,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FOR...,COMUNIDAD AUTÓNOMA,País Vasco,26.840242,92.489942,7.510058,73.159758,63.698237,36.301763

## DF FORMACION MEDIO (EAL-18a)

In [74]:
df_formacion_medio = df_18a_subset.copy()
df_formacion_medio

,anio,tabla,pregunta,dimension,ambito,total,cursos_empresa,cursos_otra_organizacion,formacion_puesto_trabajo,aprendizaje_rotacion,conferencias_seminarios
0,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,73.468278,34.269329,73.709969,56.005492,27.375278,35.086542
5,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,99.275362,85.450122,84.963504,80.048662,51.532847,65.596107
6,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Industria,76.222600,34.293577,76.121179,61.910901,36.081017,33.867169
7,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Construcción,77.712290,22.420652,84.768610,57.771672,21.273003,23.030251
8,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,73.958727,38.680615,71.445779,54.400700,29.940268,41.624315
9,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,77.406769,30.568829,79.668783,52.052104,24.258690,20.416312
10,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Hostelería,60.735371,25.970788,68.136490,54.371695,21.531100,13.127676
13,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,74.261496,36.374821,74.834256,60.200943,28.282414,39.518830
14,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",73.507801,40.519529,67.162337,57.172827,24.520269,43.228235
15,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Andalucía,73.324726,23.902570,76.823751,47.927417,26.162236,27.756719
23,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Cataluña,76.295600,37.301272,75.365660,58.316773,30.781002,41.250000
24,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,74.320098,38.074398,71.119340,55.536105,26.032654,32.280761
27,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),72.991275,41.842742,71.675800,58.771505,26.178157,38.468204
30,2024,EAL-18a,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,País Vasco,71.174036,44.731962,69.774107,58.917734,31.507080,36.791976

## DF FORMACION SUSPENSIÓN CONTRATO (EAL-18B)

In [83]:
df_formacion_suspension_contrato = df_18b_subset.copy()
df_formacion_suspension_contrato

,anio,tabla,pregunta,dimension,ambito,empresas_suspension_reduccion,total_trabajadores_formados,porcentaje_0,mas_0_hasta_25,mas_25_hasta_50,mas_50_hasta_75,mas_75_hasta_100,porcentaje_100
0,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,1.396570,100.0,81.299,13.061,1.327,2.022,0.420,1.871
5,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,11.787440,100.0,66.136,26.049,5.791,1.364,0.325,0.334
6,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Industria,3.526077,100.0,79.042,12.156,0.385,1.863,0.546,6.008
7,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Construcción,0.131222,100.0,84.067,8.563,0.058,5.920,1.391,0.000
8,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,0.230648,100.0,85.276,11.029,1.964,0.000,0.000,1.732
9,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,0.851236,100.0,82.853,16.628,0.328,0.000,0.191,0.000
10,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Hostelería,2.805053,100.0,86.534,13.319,0.128,0.019,0.000,0.000
13,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,1.405949,100.0,85.590,9.907,3.315,0.094,1.094,0.000
14,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",1.002358,100.0,68.871,6.066,6.637,12.714,0.063,5.650
15,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Andalucía,1.949181,100.0,86.189,8.659,2.918,0.933,0.000,1.301
23,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Cataluña,1.726961,100.0,69.010,18.953,0.327,8.934,0.399,2.377
24,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,3.052366,100.0,79.585,19.840,0.112,0.463,0.000,0.000
27,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),0.416721,100.0,81.248,12.697,3.062,0.160,1.051,1.782
30,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,País Vasco,1.235827,100.0,66.394,19.083,0.000,0.000,0.000,14.523

## DF FORMACION SEGURIDAD SALUD HIGIENE (EAL-18C)

In [91]:
df_formacion_seguridad_salud = df_18c_subset.copy()
df_formacion_seguridad_salud

,anio,tabla,pregunta,dimension,ambito,porcentaje_formacion_seguridad_salud
0,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TOTAL,TOTAL,75.813
5,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,96.501
6,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Industria,81.214
7,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Construcción,81.458
8,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Comercio y reparación de vehículos,74.164
9,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Transporte y almacenamiento,81.207
10,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Hostelería,73.552
13,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,Actividades administrativas y servicios auxili...,75.604
14,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,ACTIVIDAD ECONÓMICA,"Actividades artísticas, recreativas y de entre...",69.206
15,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Andalucía,76.023
23,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Cataluña,79.948
24,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Comunitat Valenciana,81.864
27,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,Madrid (Comunidad de),74.704
30,2024,EAL-18c,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,COMUNIDAD AUTÓNOMA,País Vasco,62.846

## DF COMPETENCIAS FORMACIÓN (TAMAÑO EMPRESA, CCAA, SECTOR; EAL-20, 21, 22)

In [52]:
df_competencias_formacion = pd.concat([df_20_subset_long,df_21_subset_long, df_22_subset_long])
df_competencias_formacion

,anio,tabla,pregunta,competencia,tamano_empresa,porcentaje,sector,comunidad_autonoma
0,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De dirección,TOTAL,16.347340,NaN,NaN
1,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De trabajo en equipo,TOTAL,28.494848,NaN,NaN
2,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,De atención al público/ trato a clientes,TOTAL,24.530267,NaN,NaN
3,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Administrativas de oficina,TOTAL,17.027644,NaN,NaN
4,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Técnicas específicas del puesto de trabajo,TOTAL,50.838810,NaN,NaN
...,...,...,...,...,...,...,...,...
182,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,En lenguas extranjeras,NaN,10.510789,NaN,PAÍS VASCO
183,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Generales de tecnologías de la información,NaN,9.794336,NaN,PAÍS VASCO
184,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Profesionales de tecnologías de la información,NaN,7.021241,NaN,PAÍS VASCO
185,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Básicas de cálculo y/o comunicación oral o esc...,NaN,0.134862,NaN,PAÍS VASCO
186,2024,EAL-22,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras,NaN,11.126096,NaN,PAÍS VASCO

## DF RELEVANCIA OBJETIVOS (EAL-23)

In [53]:
df_relevancia_objetivos = df_23_subset.copy()
df_relevancia_objetivos = df_relevancia_objetivos.drop(columns=["TOTAL"])

In [54]:
df_relevancia_objetivos

,anio,tabla,pregunta,ambito,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Responder a un sistema predeterminado de promo...,24.833,42.321,26.86,5.987
1,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Readaptar al personal a los cambios técnicos i...,12.615,22.193,49.421,15.771
2,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Readaptar al personal a los cambios organizati...,14.246,29.411,44.323,12.02
3,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Adaptar al personal recién incorporado a las t...,7.888,15.038,50.533,26.541
4,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Mejorar la cualificación básica del personal p...,8.168,22.567,51.043,18.222
5,2024,EAL-23,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Adaptación impuesta por cambios normativos,8.955,22.904,42.755,25.385
18,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Responder a un sistema predeterminado de promo...,7.551,36.456,44.463,11.53
19,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Readaptar al personal a los cambios técnicos i...,2.345,15.439,54.421,27.794
20,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Readaptar al personal a los cambios organizati...,3.682,25.152,50.874,20.292
21,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Adaptar al personal recién incorporado a las t...,1.267,9.804,51.856,37.073
22,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Mejorar la cualificación básica del personal p...,4.796,23.62,50.479,21.105
23,2024,EAL-23c,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Adaptación impuesta por cambios normativos,4.237,25.702,46.8,23.261
36,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Responder a un sistema predeterminado de promo...,24.872,41.166,27.332,6.63
37,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Readaptar al personal a los cambios técnicos i...,12.8,21.391,49.249,16.561
38,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Readaptar al personal a los cambios organizati...,14.121,28.64,44.052,13.187
39,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Adaptar al personal recién incorporado a las t...,7.805,15.009,49.654,27.532
40,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Mejorar la cualificación básica del personal p...,8.216,23.417,49.976,18.391
41,2024,EAL-23f,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Adaptación impuesta por cambios normativos,9.211,24.064,41.034,25.691

## DF LIMITACIONES (EAL-24 & EAL-25)

EAL-24 proporcionaron formación - grado limitación a la formación  
EAL-25 NO proporcionaron formación - grado de influencia

In [55]:
df_24_subset.insert(2,'proporcionaron_formacion','Si')
df_25_subset.insert(2,'proporcionaron_formacion','No')

In [56]:
df_limitaciones = pd.concat([df_24_subset,df_25_subset])
df_limitaciones = df_limitaciones.drop(columns=["TOTAL"])
df_limitaciones

,anio,tabla,proporcionaron_formacion,pregunta,ambito,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,El nivel de formación de los empleados era el ...,8.964,19.548,53.724,17.765
1,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La empresa prefirió contratar a personal con l...,21.954,25.684,39.843,12.519
2,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Dificultad para evaluar la necesidades de form...,31.45,51.904,14.719,1.928
3,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La falta de cursos de formación adecuados en e...,26.775,45.123,20.708,7.394
4,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,El alto coste de los cursos de formación,21.532,36.681,28.491,13.295
5,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La empresa prefirió tener personal con contrat...,68.584,23.204,6.415,1.797
6,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,El mayor esfuerzo realizado en años anteriores...,32.592,42.286,20.426,4.696
7,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,La elevada carga de trabajo y el escaso tiempo...,15.221,28.392,39.031,17.356
8,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Dificultad para acceder a ayudas o subvencione...,25.833,36.915,23.157,14.095
9,2024,EAL-24,Si,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TR...,Otras razones,68.296,22.73,5.969,3.004
30,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,El nivel de formación de los empleados era el ...,12.96,33.75,47.697,5.594
31,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La empresa prefirió contratar a personal con l...,16.438,45.815,31.742,6.005
32,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Dificultad para evaluar la necesidades de form...,31.285,55.211,12.062,1.442
33,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La falta de cursos de formación adecuados en e...,26.306,53.799,17.182,2.713
34,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,El alto coste de los cursos de formación,17.847,44.584,30.667,6.903
35,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La empresa prefirió tener personal con contrat...,67.016,27.424,5.012,0.548
36,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,El mayor esfuerzo realizado en años anteriores...,30.689,47.535,19.701,2.075
37,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,La elevada carga de trabajo y el escaso tiempo...,10.645,34.299,41.209,13.847
38,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Dificultad para acceder a ayudas o subvencione...,32.125,44.83,17.307,5.739
39,2024,EAL-24c,Si,EMPRESAS DE MÁS DE 499 TRABAJADORES QUE PROPOR...,Otras razones,66.751,25.775,5.614,1.86
60,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,El nivel de formación de los empleados era el ...,9.804,19.018,52.966,18.212
61,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La empresa prefirió contratar a personal con l...,22.127,24.242,40.054,13.577
62,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Dificultad para evaluar la necesidades de form...,31.896,51.337,14.996,1.771
63,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La falta de cursos de formación adecuados en e...,27.241,45.197,20.15,7.413
64,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,El alto coste de los cursos de formación,21.275,36.415,28.771,13.539
65,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La empresa prefirió tener personal con contrat...,69.942,22.01,6.172,1.876
66,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,El mayor esfuerzo realizado en años anteriores...,34.423,42.09,19.098,4.389
67,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,La elevada carga de trabajo y el escaso tiempo...,15.595,28.249,38.791,17.365
68,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Dificultad para acceder a ayudas o subvencione...,26.134,36.469,22.508,14.89
69,2024,EAL-24f,Si,EMPRESAS DEL SECTOR SERVICIOS QUE PROPORCIONAR...,Otras razones,69.01,21.876,5.87,3.245
0,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El nivel de formación de los empleados era el ...,7.497,11.745,48.18,32.578
1,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió contratar a personal con l...,16.991,14.927,45.484,22.598
2,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para evaluar la necesidades de form...,33.929,46.144,15.427,4.501
3,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La falta de cursos de formación adecuados en e...,32.974,40.854,18.727,7.444
4,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El alto coste de los cursos de formación,32.154,34.644,22.305,10.896
5,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La empresa prefirió tener personal con contrat...,69.386,20.775,7.963,1.875
6,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,El mayor esfuerzo realizado en años anteriores...,42.478,33.815,18.795,4.912
7,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,La elevada carga de trabajo y el escaso tiempo...,23.112,29.498,30.973,16.417
8,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Dificultad para acceder a ayudas o subvencione...,36.386,31.367,20.381,11.866
9,2024,EAL-25,No,EMPRESAS QUE NO PROPORCIONARON FORMACIÓN A SUS...,Otras razones,63.988,21.749,7.994,6.269
20,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El nivel de formación de los empleados era el ...,13.937,12.085,49.03,24.948
21,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La empresa prefirió contratar a personal con l...,21.345,16.108,41.856,20.691
22,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Dificultad para evaluar la necesidades de form...,31.261,48.978,17.449,2.312
23,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La falta de cursos de formación adecuados en e...,36.665,46.178,11.29,5.867
24,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El alto coste de los cursos de formación,37.611,36.39,15.092,10.907
25,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La empresa prefirió tener personal con contrat...,58.533,32.396,8.904,0.166
26,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,El mayor esfuerzo realizado en años anteriores...,36.081,39.704,24.049,0.166
27,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,La elevada carga de trabajo y el escaso tiempo...,28.984,30.222,28.625,12.169
28,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Dificultad para acceder a ayudas o subvencione...,35.266,37.366,17.212,10.155
29,2024,EAL-25b,No,EMPRESAS DE 50 O MÁS TRABAJADORES QUE NO PROPO...,Otras razones,51.771,30.562,7.505,10.162
50,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El nivel de formación de los empleados era el ...,6.457,12.723,47.626,33.194
51,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió contratar a personal con l...,15.886,15.641,45.619,22.854
52,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para evaluar la necesidades de form...,33.498,45.986,15.393,5.123
53,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La falta de cursos de formación adecuados en e...,33.133,41.316,18.323,7.229
54,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El alto coste de los cursos de formación,31.411,33.919,23.188,11.481
55,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La empresa prefirió tener personal con contrat...,70.067,19.881,8.26,1.792
56,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,El mayor esfuerzo realizado en años anteriores...,44.018,34.269,17.211,4.502
57,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,La elevada carga de trabajo y el escaso tiempo...,22.419,29.643,30.416,17.522
58,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Dificultad para acceder a ayudas o subvencione...,36.2,30.566,20.535,12.699
59,2024,EAL-25e,No,EMPRESAS DEL SECTOR SERVICIOS QUE NO PROPORCIO...,Otras razones,63.827,21.365,7.972,6.836

## Guardar df en csv

Pasada a markdown por "seguridad" de que no se machaquen los documentos

# Carpeta de salida: ../../Data/processed/EAL/2024
output_folder = Path(OUTPUT_FILES)
output_folder.mkdir(parents=True, exist_ok=True)

# Diccionario con los dataframes finales
dfs_finales = {
    "df_competencias_formacion": df_competencias_formacion,
    "df_relevancia_objetivos": df_relevancia_objetivos,
    "df_limitaciones": df_limitaciones,
    "df_formacion_tipo":df_formacion_tipo,
    "df_formacion_necesidades":df_formacion_necesidades,
    "df_formacion_medio":df_formacion_medio,
    "df_formacion_suspension_contrato":df_formacion_suspension_contrato,
    "df_formacion_seguridad_salud":df_formacion_seguridad_salud
}

# Guardar cada dataframe como CSV
for name, df in dfs_finales.items():
    output_path = output_folder / f"{name}.csv"

    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

print(f"CSV files saved in: {output_folder}")