# Data cleaning Desafío 1

## Import libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Files

## Files path

In [ ]:
DATA_RRHH_RAW_FILE = '../Data/raw/raw_data_25052026.csv'

DATA_OUTPUT_FILE = '../Data/clean/clean_data_25052026.csv'

## Read files

In [3]:
df_RRHH = pd.read_csv(DATA_RRHH_RAW_FILE)
df_RRHH.sample(5)

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
659,36,28,12,3,4,118,13,18,50,"236,629",...,0,1,1,1,0,0,98,178,31,1
188,3,28,4,4,3,179,51,18,38,"239,409",...,0,1,0,1,0,0,89,170,31,8
604,15,28,6,5,3,291,31,12,40,"275,089",...,0,1,1,1,0,1,73,171,25,2
49,11,13,4,5,3,289,36,13,33,"326,452",...,0,1,2,1,0,1,90,172,30,16
502,33,23,11,2,4,248,25,14,47,"284,031",...,0,1,2,0,0,1,86,165,32,2

# Data cleaning

In [4]:
df_RRHH.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,740.0,18.017568,11.021247,1.0,9.0,18.0,28.0,36.0
Reason_absence,740.0,19.216216,8.433406,0.0,13.0,23.0,26.0,28.0
Month_absence,740.0,6.324324,3.436287,0.0,3.0,6.0,9.0,12.0
Day_week,740.0,3.914865,1.421675,2.0,3.0,4.0,5.0,6.0
Seasons,740.0,2.544595,1.111831,1.0,2.0,3.0,4.0,4.0
Transportation_expense,740.0,221.329730,66.952223,118.0,179.0,225.0,260.0,388.0
Distance_Residence_Work,740.0,29.631081,14.836788,5.0,16.0,26.0,50.0,52.0
Service_time,740.0,12.554054,4.384873,1.0,9.0,13.0,16.0,29.0
Age,740.0,36.450000,6.478772,27.0,31.0,37.0,40.0,58.0
Hit_target,740.0,94.587838,3.779313,81.0,93.0,95.0,97.0,100.0
Disciplinary_failure,740.0,0.054054,0.226277,0.0,0.0,0.0,0.0,1.0
Education,740.0,1.291892,0.673238,1.0,1.0,1.0,1.0,4.0
Son,740.0,1.018919,1.098489,0.0,0.0,1.0,2.0,4.0
Social_drinker,740.0,0.567568,0.495749,0.0,0.0,1.0,1.0,1.0
Social_smoker,740.0,0.072973,0.260268,0.0,0.0,0.0,0.0,1.0
Pet,740.0,0.745946,1.318258,0.0,0.0,0.0,1.0,8.0
Weight,740.0,79.035135,12.883211,56.0,69.0,83.0,89.0,108.0
Height,740.0,172.114865,6.034995,163.0,169.0,170.0,172.0,196.0
Body_mass_index,740.0,26.677027,4.285452,19.0,24.0,25.0,31.0,38.0
Absenteeism_hours,740.0,6.924324,13.330998,0.0,2.0,3.0,8.0,120.0

In [5]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           740 non-null    int64
 2   Month_absence            740 non-null    int64
 3   Day_week                 740 non-null    int64
 4   Seasons                  740 non-null    int64
 5   Transportation_expense   740 non-null    int64
 6   Distance_Residence_Work  740 non-null    int64
 7   Service_time             740 non-null    int64
 8   Age                      740 non-null    int64
 9   Work_load_Average_day    740 non-null    str
 10  Hit_target               740 non-null    int64
 11  Disciplinary_failure     740 non-null    int64
 12  Education                740 non-null    int64
 13  Son                      740 non-null    int64
 14  Social_drinker           740 non-null    int64
 15  Social_smoker            740 non-null    int64
 16  Pet                      740 non-null    int64
 17  Weight                   740 non-null    int64
 18  Height                   740 non-null    int64
 19  Body_mass_index          740 non-null    int64
 20  Absenteeism_hours        740 non-null    int64
dtypes: int64(20), str(1)
memory usage: 121.5 KB

## Change Work_load_Average_day to float (, to .)

In [6]:
df_RRHH['Work_load_Average_day'] = df_RRHH['Work_load_Average_day'].str.replace(',', '.', regex=False).astype(float)

In [7]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           740 non-null    int64
 2   Month_absence            740 non-null    int64
 3   Day_week                 740 non-null    int64
 4   Seasons                  740 non-null    int64
 5   Transportation_expense   740 non-null    int64
 6   Distance_Residence_Work  740 non-null    int64
 7   Service_time             740 non-null    int64
 8   Age                      740 non-null    int64
 9   Work_load_Average_day    740 non-null    float64
 10  Hit_target               740 non-null    int64
 11  Disciplinary_failure     740 non-null    int64
 12  Education                740 non-null    int64
 13  Son                      740 non-null    int64
 14  Social_drinker           740 non-null    int64
 15  Social_smoker            740 non-null    int64
 16  Pet                      740 non-null    int64
 17  Weight                   740 non-null    int64
 18  Height                   740 non-null    int64
 19  Body_mass_index          740 non-null    int64
 20  Absenteeism_hours        740 non-null    int64
dtypes: float64(1), int64(20)
memory usage: 121.5 KB

## Month_absence 0 - to nan

Check df

In [8]:
df_RRHH[df_RRHH['Month_absence'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

In [9]:
df_RRHH[(df_RRHH['Reason_absence'] == 0) & (df_RRHH['Disciplinary_failure'] == 0)]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

Change

In [10]:
df_RRHH['Month_absence'] = df_RRHH['Month_absence'].replace(0, np.nan)

Check change correct

In [11]:
df_RRHH['Month_absence'].unique()

array([11.,  4.,  7.,  3.,  6., 12., 10.,  5.,  8.,  9.,  1.,  2., nan])

In [12]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           740 non-null    int64
 2   Month_absence            737 non-null    float64
 3   Day_week                 740 non-null    int64
 4   Seasons                  740 non-null    int64
 5   Transportation_expense   740 non-null    int64
 6   Distance_Residence_Work  740 non-null    int64
 7   Service_time             740 non-null    int64
 8   Age                      740 non-null    int64
 9   Work_load_Average_day    740 non-null    float64
 10  Hit_target               740 non-null    int64
 11  Disciplinary_failure     740 non-null    int64
 12  Education                740 non-null    int64
 13  Son                      740 non-null    int64
 14  Social_drinker           740 non-null    int64
 15  Social_smoker            740 non-null    int64
 16  Pet                      740 non-null    int64
 17  Weight                   740 non-null    int64
 18  Height                   740 non-null    int64
 19  Body_mass_index          740 non-null    int64
 20  Absenteeism_hours        740 non-null    int64
dtypes: float64(2), int64(19)
memory usage: 121.5 KB

## BMI - changed due to inconsistencies and add one decimal (medically relevant)

In [13]:
df_bmi = df_RRHH[['Weight','Height', 'Body_mass_index']]
df_bmi

     Weight  Height  Body_mass_index
0        95     196               25
1        98     178               31
2        65     172               22
3        69     169               24
4        65     172               22
..      ...     ...              ...
735      88     163               33
736      79     178               25
737      98     170               34
738     100     170               35
739      77     175               25

[740 rows x 3 columns]

Since we have both weight and height, calculate BMI

In [14]:
df_bmi['BMI_calculated'] = (
    df_bmi['Weight'] / ((df_bmi['Height'] / 100) ** 2)
)

In [15]:
df_bmi['BMI_calculated_round'] = (
    df_bmi['Weight'] / ((df_bmi['Height'] / 100) ** 2)
).round().astype(int)

In [16]:
df_bmi['BMI_calculated_round_1'] = (
    df_bmi['Weight'] / ((df_bmi['Height'] / 100) ** 2)
).round(1)

In [17]:
df_bmi[df_bmi['BMI_calculated_round'] != df_bmi['Body_mass_index']]

,Weight,Height,Body_mass_index,BMI_calculated,BMI_calculated_round,BMI_calculated_round_1
50,88,172,29,29.745809,30,29.7
64,88,172,29,29.745809,30,29.7
89,88,172,29,29.745809,30,29.7
145,88,172,29,29.745809,30,29.7
178,88,172,29,29.745809,30,29.7
182,88,172,29,29.745809,30,29.7
193,88,172,29,29.745809,30,29.7
196,88,172,29,29.745809,30,29.7
218,75,178,25,23.671254,24,23.7
222,75,178,25,23.671254,24,23.7
229,108,172,36,36.506220,37,36.5
240,75,175,25,24.489796,24,24.5
247,88,172,29,29.745809,30,29.7
250,88,172,29,29.745809,30,29.7
254,75,178,25,23.671254,24,23.7
261,75,175,25,24.489796,24,24.5
285,88,172,29,29.745809,30,29.7
303,88,172,29,29.745809,30,29.7
307,88,172,29,29.745809,30,29.7
328,88,172,29,29.745809,30,29.7
338,88,172,29,29.745809,30,29.7
364,88,172,29,29.745809,30,29.7
377,88,172,29,29.745809,30,29.7
402,75,178,25,23.671254,24,23.7
403,108,172,36,36.506220,37,36.5
425,75,178,25,23.671254,24,23.7
430,75,178,25,23.671254,24,23.7
440,75,178,25,23.671254,24,23.7
495,108,172,36,36.506220,37,36.5
503,88,172,29,29.745809,30,29.7
505,88,172,29,29.745809,30,29.7
536,108,172,36,36.506220,37,36.5
571,75,178,25,23.671254,24,23.7
593,75,178,25,23.671254,24,23.7
598,75,178,25,23.671254,24,23.7
646,88,172,29,29.745809,30,29.7
655,88,172,29,29.745809,30,29.7
664,88,172,29,29.745809,30,29.7
682,108,172,36,36.506220,37,36.5
725,88,172,29,29.745809,30,29.7

Change (Insert new column calculated next to previous column)

In [18]:
df_RRHH.insert(20,'BMI_calculated',(
    df_RRHH['Weight'] / ((df_RRHH['Height'] / 100) ** 2)
).round(1))

Check change

In [19]:
df_RRHH[['ID','BMI_calculated','Body_mass_index']]

     ID  BMI_calculated  Body_mass_index
0    14            24.7               25
1    36            30.9               31
2     9            22.0               22
3    28            24.2               24
4     9            22.0               22
..   ..             ...              ...
735   2            33.1               33
736  21            24.9               25
737   4            33.9               34
738   8            34.6               35
739  35            25.1               25

[740 rows x 3 columns]

In [20]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           740 non-null    int64
 2   Month_absence            737 non-null    float64
 3   Day_week                 740 non-null    int64
 4   Seasons                  740 non-null    int64
 5   Transportation_expense   740 non-null    int64
 6   Distance_Residence_Work  740 non-null    int64
 7   Service_time             740 non-null    int64
 8   Age                      740 non-null    int64
 9   Work_load_Average_day    740 non-null    float64
 10  Hit_target               740 non-null    int64
 11  Disciplinary_failure     740 non-null    int64
 12  Education                740 non-null    int64
 13  Son                      740 non-null    int64
 14  Social_drinker           740 non-null    int64
 15  Social_smoker            740 non-null    int64
 16  Pet                      740 non-null    int64
 17  Weight                   740 non-null    int64
 18  Height                   740 non-null    int64
 19  Body_mass_index          740 non-null    int64
 20  BMI_calculated           740 non-null    float64
 21  Absenteeism_hours        740 non-null    int64
dtypes: float64(3), int64(19)
memory usage: 127.3 KB

## Row of ID 29 with different demographics correspond to ID 28

In [21]:
df_RRHH[df_RRHH['ID'] == 29]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
252,29,14,5.0,5,3,225,15,15,41,237.656,...,4,2,1,0,2,94,182,28,28.4,8
253,29,22,5.0,6,3,225,15,15,41,237.656,...,4,2,1,0,2,94,182,28,28.4,8
441,29,19,5.0,4,3,225,15,15,41,237.656,...,4,2,1,0,2,94,182,28,28.4,3
555,29,28,2.0,6,2,225,15,15,41,264.249,...,4,2,1,0,2,94,182,28,28.4,2
698,29,0,9.0,2,4,225,26,9,28,241.476,...,1,1,0,0,2,69,169,24,24.2,0

In [22]:
df_RRHH[(df_RRHH['Age'] == 28) & (df_RRHH['Distance_Residence_Work'] == 26) & (df_RRHH['Service_time'] == 9)]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
3,28,9,7.0,3,1,225,26,9,28,230.290,...,1,1,0,0,2,69,169,24,24.2,112
47,28,11,3.0,4,3,225,26,9,28,343.253,...,1,1,0,0,2,69,169,24,24.2,16
115,28,11,3.0,2,3,225,26,9,28,343.253,...,1,1,0,0,2,69,169,24,24.2,8
116,28,11,3.0,3,3,225,26,9,28,343.253,...,1,1,0,0,2,69,169,24,24.2,8
123,28,19,5.0,3,3,225,26,9,28,378.884,...,1,1,0,0,2,69,169,24,24.2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,28,23,9.0,4,1,225,26,9,28,261.756,...,1,1,0,0,2,69,169,24,24.2,1
686,28,13,10.0,5,4,225,26,9,28,284.853,...,1,1,0,0,2,69,169,24,24.2,1
695,28,11,5.0,2,3,225,26,9,28,237.656,...,1,1,0,0,2,69,169,24,24.2,1
698,29,0,9.0,2,4,225,26,9,28,241.476,...,1,1,0,0,2,69,169,24,24.2,0
729,28,0,10.0,2,4,225,26,9,28,284.853,...,1,1,0,0,2,69,169,24,24.2,0

In [23]:
df_RRHH[(df_RRHH['Age'] == 28) & (df_RRHH['Distance_Residence_Work'] == 26) & (df_RRHH['Service_time'] == 9)& (df_RRHH['Reason_absence'] == 0)]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
698,29,0,9.0,2,4,225,26,9,28,241.476,...,1,1,0,0,2,69,169,24,24.2,0
729,28,0,10.0,2,4,225,26,9,28,284.853,...,1,1,0,0,2,69,169,24,24.2,0

Change

In [24]:
df_RRHH.loc[698, 'ID'] = 28

Check change

In [25]:
df_RRHH[(df_RRHH['Age'] == 28) & (df_RRHH['Distance_Residence_Work'] == 26) & (df_RRHH['Service_time'] == 9)]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
3,28,9,7.0,3,1,225,26,9,28,230.290,...,1,1,0,0,2,69,169,24,24.2,112
47,28,11,3.0,4,3,225,26,9,28,343.253,...,1,1,0,0,2,69,169,24,24.2,16
115,28,11,3.0,2,3,225,26,9,28,343.253,...,1,1,0,0,2,69,169,24,24.2,8
116,28,11,3.0,3,3,225,26,9,28,343.253,...,1,1,0,0,2,69,169,24,24.2,8
123,28,19,5.0,3,3,225,26,9,28,378.884,...,1,1,0,0,2,69,169,24,24.2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,28,23,9.0,4,1,225,26,9,28,261.756,...,1,1,0,0,2,69,169,24,24.2,1
686,28,13,10.0,5,4,225,26,9,28,284.853,...,1,1,0,0,2,69,169,24,24.2,1
695,28,11,5.0,2,3,225,26,9,28,237.656,...,1,1,0,0,2,69,169,24,24.2,1
698,28,0,9.0,2,4,225,26,9,28,241.476,...,1,1,0,0,2,69,169,24,24.2,0
729,28,0,10.0,2,4,225,26,9,28,284.853,...,1,1,0,0,2,69,169,24,24.2,0

In [26]:
df_RRHH[df_RRHH['ID'] == 29]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
252,29,14,5.0,5,3,225,15,15,41,237.656,...,4,2,1,0,2,94,182,28,28.4,8
253,29,22,5.0,6,3,225,15,15,41,237.656,...,4,2,1,0,2,94,182,28,28.4,8
441,29,19,5.0,4,3,225,15,15,41,237.656,...,4,2,1,0,2,94,182,28,28.4,3
555,29,28,2.0,6,2,225,15,15,41,264.249,...,4,2,1,0,2,94,182,28,28.4,2

## Reason absence 0 to nan - It is not a code and mainly corresponding to disciplinary failure 1

In [27]:
df_RRHH[df_RRHH['Reason_absence'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
696,36,0,7.0,3,1,118,13,18,50,239.554,...,1,1,1,0,0,98,178,31,30.9,0
697,20,0,9.0,2,4,260,50,11,36,241.476,...,1,4,1,0,0,65,168,23,23.0,0
698,28,0,9.0,2,4,225,26,9,28,241.476,...,1,1,0,0,2,69,169,24,24.2,0
699,11,0,9.0,3,4,289,36,13,33,241.476,...,1,2,1,0,1,90,172,30,30.4,0
700,36,0,9.0,3,4,118,13,18,50,241.476,...,1,1,1,0,0,98,178,31,30.9,0
701,13,0,9.0,4,4,369,17,12,31,241.476,...,1,3,1,0,0,70,169,25,24.5,0
702,36,0,10.0,4,4,118,13,18,50,253.465,...,1,1,1,0,0,98,178,31,30.9,0
704,2,0,4.0,2,3,235,29,12,48,326.452,...,1,1,0,1,5,88,163,33,33.1,0
705,7,0,5.0,4,3,279,5,14,39,378.884,...,1,2,1,1,0,68,168,24,24.1,0
706,18,0,5.0,4,3,330,16,4,28,378.884,...,2,0,0,0,0,84,182,25,25.4,0
707,23,0,5.0,4,3,378,49,11,36,378.884,...,1,2,0,1,4,65,174,21,21.5,0
708,31,0,5.0,4,3,388,15,9,50,378.884,...,1,0,0,0,0,76,178,24,24.0,0
709,20,0,7.0,5,1,260,50,11,36,275.312,...,1,4,1,0,0,65,168,23,23.0,0
710,5,0,9.0,5,1,235,20,13,43,294.217,...,1,1,1,0,0,106,167,38,38.0,0
711,8,0,9.0,3,1,231,35,14,39,294.217,...,1,2,1,0,2,100,170,35,34.6,0
712,19,0,9.0,3,1,291,50,12,32,294.217,...,1,0,1,0,0,65,169,23,22.8,0
713,5,0,9.0,5,4,235,20,13,43,294.217,...,1,1,1,0,0,106,167,38,38.0,0
714,36,0,10.0,6,4,118,13,18,50,265.017,...,1,1,1,0,0,98,178,31,30.9,0
715,33,0,10.0,6,4,248,25,14,47,265.017,...,1,2,0,0,1,86,165,32,31.6,0
716,5,0,10.0,4,4,235,20,13,43,265.017,...,1,1,1,0,0,106,167,38,38.0,0
717,5,0,10.0,6,4,235,20,13,43,265.017,...,1,1,1,0,0,106,167,38,38.0,0
718,20,0,10.0,3,4,260,50,11,36,265.017,...,1,4,1,0,0,65,168,23,23.0,0
719,15,0,10.0,3,4,291,31,12,40,265.017,...,1,1,1,0,1,73,171,25,25.0,0
720,30,0,10.0,3,4,157,27,6,29,265.017,...,1,0,1,1,0,75,185,22,21.9,0
721,18,0,11.0,3,4,330,16,4,28,284.031,...,2,0,0,0,0,84,182,25,25.4,0
722,23,0,11.0,6,4,378,49,11,36,284.031,...,1,2,0,1,4,65,174,21,21.5,0
723,7,0,11.0,3,4,279,5,14,39,284.031,...,1,2,1,1,0,68,168,24,24.1,0
724,13,0,3.0,4,2,369,17,12,31,244.387,...,1,3,1,0,0,70,169,25,24.5,0
725,1,0,3.0,5,3,235,11,14,37,244.387,...,3,1,0,0,1,88,172,29,29.7,0
726,24,0,3.0,5,3,246,25,16,41,244.387,...,1,0,1,0,0,67,170,23,23.2,0
727,36,0,3.0,5,3,118,13,18,50,244.387,...,1,1,1,0,0,98,178,31,30.9,0
728,3,0,6.0,6,3,179,51,18,38,253.957,...,1,0,1,0,0,89,170,31,30.8,0
729,28,0,10.0,2,4,225,26,9,28,284.853,...,1,1,0,0,2,69,169,24,24.2,0
730,15,0,11.0,3,4,291,31,12,40,268.519,...,1,1,1,0,1,73,171,25,25.0,0
731,11,0,11.0,4,4,289,36,13,33,268.519,...,1,2,1,0,1,90,172,30,30.4,0
732,5,0,11.0,5,4,235,20,13,43,268.519,...,1,1,1,0,0,106,167,38,38.0,0
733,36,0,5.0,3,3,118,13,18,50,237.656,...,1,1,1,0,0,98,178,31,30.9,0
734,23,0,5.0,4,3,378,49,11,36,237.656,...,1,2,0,1,4,65,174,21,21.5,0
735,2,0,6.0,2,3,235,29,12,48,275.089,...,1,1,0,1,5,88,163,33,33.1,0
736,21,0,6.0,2,3,268,11,8,33,275.089,...,2,0,0,0,0,79,178,25,24.9,0
737,4,0,NaN,3,1,118,14,13,40,271.219,...,1,1,1,0,8,98,170,34,33.9,0
738,8,0,NaN,4,2,231,35,14,39,271.219,...,1,2,1,0,2,100,170,35,34.6,0
739,35,0,NaN,6,3,179,45,14,53,271.219,...,1,1,0,0,1,77,175,25,25.1,0

Change

In [28]:
df_RRHH['Reason_absence'] = df_RRHH['Reason_absence'].replace(0, np.nan)

Check change correct

In [29]:
df_RRHH['Reason_absence'].unique()

array([11., 13.,  6.,  9., 12., 19., 18.,  1., 10., 14.,  7., 28.,  2.,
       26., 23., 22., 21., 24., 17.,  8.,  5., 15.,  4., 25.,  3., 27.,
       16., nan])

In [30]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           697 non-null    float64
 2   Month_absence            737 non-null    float64
 3   Day_week                 740 non-null    int64
 4   Seasons                  740 non-null    int64
 5   Transportation_expense   740 non-null    int64
 6   Distance_Residence_Work  740 non-null    int64
 7   Service_time             740 non-null    int64
 8   Age                      740 non-null    int64
 9   Work_load_Average_day    740 non-null    float64
 10  Hit_target               740 non-null    int64
 11  Disciplinary_failure     740 non-null    int64
 12  Education                740 non-null    int64
 13  Son                      740 non-null    int64
 14  Social_drinker           740 non-null    int64
 15  Social_smoker            740 non-null    int64
 16  Pet                      740 non-null    int64
 17  Weight                   740 non-null    int64
 18  Height                   740 non-null    int64
 19  Body_mass_index          740 non-null    int64
 20  BMI_calculated           740 non-null    float64
 21  Absenteeism_hours        740 non-null    int64
dtypes: float64(4), int64(18)
memory usage: 127.3 KB

## Seasons to correct season by month

Seasons (summer (1), autumn (2), winter (3), spring (4))  
España:  
- 1 (summer): 6 - 9 (originally 1 - not change)
- 2 (autumn): 9 - 12 (originally 4 - CHANGE)
- 3 (winter): 12 - 3 (originally 2 - CHANGE)
- 4 (spring): 3 - 6 (originally 3 - CHANGE)

In [31]:
df_RRHH.groupby('Seasons')['Month_absence'].unique()

Seasons
1     [7.0, 8.0, 9.0, 6.0, nan]
2    [3.0, 12.0, 1.0, 2.0, nan]
3     [4.0, 3.0, 6.0, 5.0, nan]
4       [11.0, 12.0, 10.0, 9.0]
Name: Month_absence, dtype: object

Change

In [32]:
df_RRHH['Seasons'] = df_RRHH['Seasons'].replace({
    4.0: 2.0,
    2.0: 3.0,
    3.0: 4.0
})

Check

In [33]:
df_RRHH.groupby('Seasons')['Month_absence'].unique()

Seasons
1     [7.0, 8.0, 9.0, 6.0, nan]
2       [11.0, 12.0, 10.0, 9.0]
3    [3.0, 12.0, 1.0, 2.0, nan]
4     [4.0, 3.0, 6.0, 5.0, nan]
Name: Month_absence, dtype: object

## Create a column with the labels corresponding to the numbers

Dictionaries

In [34]:
reason_labels = {
    1: "Enfermedades infecciosas y parasitarias",
    2: "Neoplasias",
    3: "Sangre e inmunidad",
    4: "Endocrinas, nutricionales y metabólicas",
    5: "Trastornos mentales y del comportamiento",
    6: "Sistema nervioso",
    7: "Ojo y anexos",
    8: "Oído y apófisis mastoides",
    9: "Sistema circulatorio",
    10: "Sistema respiratorio",
    11: "Sistema digestivo",
    12: "Piel y tejido subcutáneo",
    13: "Sistema musculoesquelético",
    14: "Sistema genitourinario",
    15: "Embarazo, parto y puerperio",
    16: "Afecciones perinatales",
    17: "Malformaciones congénitas",
    18: "Síntomas y hallazgos no clasificados",
    19: "Lesiones, intoxicaciones y consecuencias externas",
    20: "Causas externas de morbilidad y mortalidad",
    21: "Factores de salud y contacto sanitario",
    22: "Seguimiento de paciente",
    23: "Consulta médica",
    24: "Donación de sangre",
    25: "Examen de laboratorio",
    26: "Ausencia injustificada",
    27: "Fisioterapia",
    28: "Consulta dental",
}

month_labels = {
    1.0: "Enero", 2.0: "Febrero", 3.0: "Marzo", 4.0: "Abril", 5.0: "Mayo", 6.0: "Junio",
    7.0: "Julio", 8.0: "Agosto", 9.0: "Septiembre", 10.0: "Octubre", 11.0: "Noviembre", 12.0: "Diciembre",
}

day_labels = {2: "Lunes", 3: "Martes", 4: "Miércoles", 5: "Jueves", 6: "Viernes"}
season_labels = {1: "Verano", 2: "Otoño", 3: "Invierno", 4: "Primavera"}
education_labels = {1: "Secundaria", 2: "Grado", 3: "Posgrado", 4: "Máster/Doctorado"}

Create function to do it for each column

In [35]:
def insert_column_labels(df, column: str, name_new_column: str, labels: dict):
    
    col_index = df.columns.get_loc(column)

    df.insert(
        col_index + 1,
        name_new_column,
        df[column].replace(labels)
    )

In [36]:
df_RRHH.columns

Index(['ID', 'Reason_absence', 'Month_absence', 'Day_week', 'Seasons',
       'Transportation_expense', 'Distance_Residence_Work', 'Service_time',
       'Age', 'Work_load_Average_day', 'Hit_target', 'Disciplinary_failure',
       'Education', 'Son', 'Social_drinker', 'Social_smoker', 'Pet', 'Weight',
       'Height', 'Body_mass_index', 'BMI_calculated', 'Absenteeism_hours'],
      dtype='str')

Change

In [37]:
insert_column_labels(df_RRHH,'Month_absence','Month_absence_name',month_labels)
insert_column_labels(df_RRHH,'Reason_absence','Reason_absence_name',reason_labels)
insert_column_labels(df_RRHH,'Day_week','Day_week_name',day_labels)
insert_column_labels(df_RRHH,'Seasons','Seasons_name',season_labels)
insert_column_labels(df_RRHH,'Education','Education_name',education_labels)

In [38]:
df_RRHH.columns

Index(['ID', 'Reason_absence', 'Reason_absence_name', 'Month_absence',
       'Month_absence_name', 'Day_week', 'Day_week_name', 'Seasons',
       'Seasons_name', 'Transportation_expense', 'Distance_Residence_Work',
       'Service_time', 'Age', 'Work_load_Average_day', 'Hit_target',
       'Disciplinary_failure', 'Education', 'Education_name', 'Son',
       'Social_drinker', 'Social_smoker', 'Pet', 'Weight', 'Height',
       'Body_mass_index', 'BMI_calculated', 'Absenteeism_hours'],
      dtype='str')

In [39]:
df_RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           697 non-null    float64
 2   Reason_absence_name      697 non-null    object
 3   Month_absence            737 non-null    float64
 4   Month_absence_name       737 non-null    object
 5   Day_week                 740 non-null    int64
 6   Day_week_name            740 non-null    object
 7   Seasons                  740 non-null    int64
 8   Seasons_name             740 non-null    object
 9   Transportation_expense   740 non-null    int64
 10  Distance_Residence_Work  740 non-null    int64
 11  Service_time             740 non-null    int64
 12  Age                      740 non-null    int64
 13  Work_load_Average_day    740 non-null    float64
 14  Hit_target               740 non-null    int64
 15  Disciplinary_failure     740 non-null    int64
 16  Education                740 non-null    int64
 17  Education_name           740 non-null    object
 18  Son                      740 non-null    int64
 19  Social_drinker           740 non-null    int64
 20  Social_smoker            740 non-null    int64
 21  Pet                      740 non-null    int64
 22  Weight                   740 non-null    int64
 23  Height                   740 non-null    int64
 24  Body_mass_index          740 non-null    int64
 25  BMI_calculated           740 non-null    float64
 26  Absenteeism_hours        740 non-null    int64
dtypes: float64(4), int64(18), object(5)
memory usage: 156.2+ KB

In [40]:
df_RRHH.sample(5)

,ID,Reason_absence,Reason_absence_name,Month_absence,Month_absence_name,Day_week,Day_week_name,Seasons,Seasons_name,Transportation_expense,...,Education_name,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,BMI_calculated,Absenteeism_hours
643,26,13.0,Sistema musculoesquelético,8.0,Agosto,5,Jueves,1,Verano,300,...,Secundaria,2,1,1,1,77,175,25,25.1,1
222,25,1.0,Enfermedades infecciosas y parasitarias,11.0,Noviembre,6,Viernes,2,Otoño,235,...,Posgrado,0,0,0,0,75,178,25,23.7,8
196,1,13.0,Sistema musculoesquelético,6.0,Junio,3,Martes,1,Verano,235,...,Posgrado,1,0,0,1,88,172,29,29.7,8
225,34,8.0,Oído y apófisis mastoides,11.0,Noviembre,3,Martes,2,Otoño,118,...,Secundaria,0,0,0,0,83,172,28,28.1,8
521,3,28.0,Consulta dental,6.0,Junio,2,Lunes,1,Verano,179,...,Secundaria,0,1,0,0,89,170,31,30.8,2

# Save to csv file

In [ ]:
# df_RRHH.to_csv(DATA_OUTPUT_FILE,encoding='utf-8', index=False)