# Librerías

In [44]:
import pandas as pd
import numpy as np
import re
import pathlib as Path
import unicodedata

# Documents

Extraer los datos de los últimos 5 años (2020 - 2024):
Hojas de formación en las empresas, contexto y errores muestreo
Extraemos todos los datos respecto a formación en las empresas pero después analizaremos solo (en el caso de algunas tablas de formación cogeremos ya las específicas de servicios [e.g. 2024 EAL-23 y 23c]):
CCAA: Total y Cataluña y otras CCAA donde tenemos sede (Madrid, Valencia, Sevilla y Bilbao)
Tamaño empresa: más de 499
Sector Transporte y almacenamiento y cuando agregado servicios

TABLAS CONTEXTO
2020, 2021, 2022, 2023, 2024:
EAL-C1, EAL-C2, EAL-C3

TABLAS FORMACIÓN EMPRESAS
2020, 2021, 2022:
EAL-16, EAL-17, EAL-18, EAL-19, EAL-20, EAL-21, EAL-22, EAL-24, EAL-25

2023, 2024 añadido:
EAL-18a, EAL-18b, EAL-18c

ERRORES MUESTREO
2020, 2021, 2022, 2023, 2024:
EAL-M1

He hagut de fer: pip install openpyxl (és l'engine de pandas per excel més nous)

In [45]:
import pandas as pd
from pathlib import Path

def encontrar_raiz_repo(inicio=None):
    ruta = Path(inicio or Path.cwd()).resolve()
    for candidata in [ruta, *ruta.parents]:
        if (candidata / "Equip_31").exists():
            return candidata
    raise FileNotFoundError("No se encontró la raíz del repositorio con Equip_31.")

REPO_ROOT = encontrar_raiz_repo()

# Ruta relativa dentro del repositorio Git.
file_path_rel = Path("Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx")
file_path = REPO_ROOT / file_path_rel

print("Raíz repo:", REPO_ROOT)
print("Excel origen:", file_path_rel)
print("Archivo existe:", file_path.exists())

if not file_path.exists():
    raise FileNotFoundError(f"No existe el Excel esperado: {file_path}")

sheets_to_extract = [
    # TABLAS CONTEXTO
    "EAL-C1", "EAL-C2", "EAL-C3",

    # TABLAS FORMACIÓN EMPRESAS
    "EAL-16", "EAL-17", "EAL-18", "EAL-19", "EAL-20", "EAL-21",
    "EAL-22", "EAL-23", "EAL-24", "EAL-25",
    "EAL-18a", "EAL-18b", "EAL-18c",

    # ERRORES MUESTREO
    "EAL-M1"
]

# Read selected sheets into a dictionary of DataFrames
dfs = pd.read_excel(
    file_path,
    sheet_name=sheets_to_extract,
    header=None,
    dtype=str
)

# Basic cleaning: remove fully empty rows and columns
for sheet_name, df in dfs.items():
    df = df.dropna(how="all")
    df = df.dropna(axis=1, how="all")
    df = df.reset_index(drop=True)
    dfs[sheet_name] = df

Raíz repo: /Users/fedeur/ProjecteData
Excel origen: Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx
Archivo existe: True

In [46]:
dfs["EAL-23"]

,0,1,2,3,4,5
0,ENCUESTA ANUAL LABORAL,NaN,NaN,NaN,NaN,EAL
1,,NaN,NaN,NaN,NaN,Volver al índice
2,EAL-23. EMPRESAS QUE PROPORCIONARON FORMACIÓN ...,NaN,NaN,NaN,NaN,NaN
3,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
4,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
5,Responder a un sistema predeterminado de promo...,100,24.833,42.321,26.86,5.987
6,Readaptar al personal a los cambios técnicos i...,100,12.615,22.193,49.421,15.771
7,Readaptar al personal a los cambios organizati...,100,14.246,29.411,44.323,12.02
8,Adaptar al personal recién incorporado a las t...,100,7.888,15.038,50.533,26.541
9,Mejorar la cualificación básica del personal p...,100,8.168,22.567,51.043,18.222
10,Adaptación impuesta por cambios normativos,100,8.955,22.904,42.755,25.385
11,EAL-23a. EMPRESAS DE 5 A 49 TRABAJADORES QUE P...,NaN,NaN,NaN,NaN,NaN
12,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
13,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
14,Responder a un sistema predeterminado de promo...,100,26.215,42.352,25.663,5.77
15,Readaptar al personal a los cambios técnicos i...,100,13.406,22.523,48.979,15.093
16,Readaptar al personal a los cambios organizati...,100,14.992,29.748,43.875,11.385
17,Adaptar al personal recién incorporado a las t...,100,8.366,15.287,50.501,25.846
18,Mejorar la cualificación básica del personal p...,100,8.508,22.676,50.974,17.842
19,Adaptación impuesta por cambios normativos,100,9.245,22.663,42.547,25.545
20,EAL-23b. EMPRESAS DE 50 A 499 TRABAJADORES QUE...,NaN,NaN,NaN,NaN,NaN
21,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
22,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
23,Responder a un sistema predeterminado de promo...,100,12.656,42.521,37.171,7.652
24,Readaptar al personal a los cambios técnicos i...,100,5.686,19.516,53.359,21.44
25,Readaptar al personal a los cambios organizati...,100,7.78,26.446,48.185,17.589
26,Adaptar al personal recién incorporado a las t...,100,3.731,13.026,50.737,32.506
27,Mejorar la cualificación básica del personal p...,100,5.099,21.391,51.774,21.736
28,Adaptación impuesta por cambios normativos,100,6.494,25.048,44.465,23.994
29,EAL-23c. EMPRESAS DE MÁS DE 499 TRABAJADORES Q...,NaN,NaN,NaN,NaN,NaN
30,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
31,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
32,Responder a un sistema predeterminado de promo...,100,7.551,36.456,44.463,11.53
33,Readaptar al personal a los cambios técnicos i...,100,2.345,15.439,54.421,27.794
34,Readaptar al personal a los cambios organizati...,100,3.682,25.152,50.874,20.292
35,Adaptar al personal recién incorporado a las t...,100,1.267,9.804,51.856,37.073
36,Mejorar la cualificación básica del personal p...,100,4.796,23.62,50.479,21.105
37,Adaptación impuesta por cambios normativos,100,4.237,25.702,46.8,23.261
38,EAL-23d. EMPRESAS DE LA INDUSTRIA QUE PROPORCI...,NaN,NaN,NaN,NaN,NaN
39,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
40,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
41,Responder a un sistema predeterminado de promo...,100,23.083,44.985,27.291,4.641
42,Readaptar al personal a los cambios técnicos i...,100,10.579,20.232,52.653,16.536
43,Readaptar al personal a los cambios organizati...,100,12.616,29.389,47.951,10.044
44,Adaptar al personal recién incorporado a las t...,100,7.527,13.819,52.765,25.889
45,Mejorar la cualificación básica del personal p...,100,8.622,20.749,54.127,16.502
46,Adaptación impuesta por cambios normativos,100,9.336,21.57,45.944,23.15
47,EAL-23e. EMPRESAS DE LA CONSTRUCCIÓN QUE PROPO...,NaN,NaN,NaN,NaN,NaN
48,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
49,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
50,Responder a un sistema predeterminado de promo...,100,26.644,45.327,23.875,4.154
51,Readaptar al personal a los cambios técnicos i...,100,13.994,28.679,46.599,10.728
52,Readaptar al personal a los cambios organizati...,100,16.786,33.498,41.561,8.155
53,Adaptar al personal recién incorporado a las t...,100,8.741,16.595,52.589,22.075
54,Mejorar la cualificación básica del personal p...,100,7.393,20.185,53.103,19.32
55,Adaptación impuesta por cambios normativos,100,7.167,18.34,48.138,26.356
56,EAL-23f. EMPRESAS DEL SECTOR SERVICIOS QUE PRO...,NaN,NaN,NaN,NaN,NaN
57,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
58,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
59,Responder a un sistema predeterminado de promo...,100,24.872,41.166,27.332,6.63
60,Readaptar al personal a los cambios técnicos i...,100,12.8,21.391,49.249,16.561
61,Readaptar al personal a los cambios organizati...,100,14.121,28.64,44.052,13.187
62,Adaptar al personal recién incorporado a las t...,100,7.805,15.009,49.654,27.532
63,Mejorar la cualificación básica del personal p...,100,8.216,23.417,49.976,18.391
64,Adaptación impuesta por cambios normativos,100,9.211,24.064,41.034,25.691

In [47]:
# Output folder dentro del repositorio Git.
output_folder_rel = Path("Equip_31/Data/Processed/EAL/2024")
output_folder = REPO_ROOT / output_folder_rel
output_folder.mkdir(parents=True, exist_ok=True)

# Save each dataframe as CSV
for sheet_name, df in dfs.items():
    output_path = output_folder / f"{sheet_name}.csv"

    df.to_csv(
        output_path,
        index=False,
        header=False,
        encoding="utf-8-sig"
    )

print(f"CSV files saved in: {output_folder_rel}")

CSV files saved in: Equip_31/Data/Processed/EAL/2024

## Normalización estructural de EAL-16

A partir de aquí se trabaja con el CSV extraído de la hoja `EAL-16`. Las rutas se resuelven desde la raíz del repositorio para que el notebook funcione aunque se ejecute desde otra carpeta.

In [48]:
# ============================================================
# CONFIGURACIÓN
# ============================================================

from pathlib import Path
import re
import unicodedata
import pandas as pd

def encontrar_raiz_repo(inicio=None):
    """Devuelve la raíz del repositorio buscando la carpeta Equip_31."""
    ruta = Path(inicio or Path.cwd()).resolve()
    for candidata in [ruta, *ruta.parents]:
        if (candidata / "Equip_31").exists():
            return candidata
    raise FileNotFoundError("No se encontró la raíz del repositorio con Equip_31.")

REPO_ROOT = encontrar_raiz_repo()

# Ruta relativa dentro del repositorio Git.
archivo_csv_rel = Path("Equip_31/Data/Processed/EAL/2024/EAL-16.csv")
archivo_csv = REPO_ROOT / archivo_csv_rel

# Excel oficial raw, usado solo para comprobación y trazabilidad.
archivo_raw_rel = Path("Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx")
archivo_raw = REPO_ROOT / archivo_raw_rel

ANIO = 2024
HOJA = "EAL-16"

print("Raíz repo:", REPO_ROOT)
print("Ruta relativa:", archivo_csv_rel)
print("CSV existe:", archivo_csv.exists())
print("CSV resuelto:", archivo_csv)
print("Raw existe:", archivo_raw.exists())
print("Raw resuelto:", archivo_raw)

if not archivo_csv.exists():
    raise FileNotFoundError(f"No existe el CSV esperado: {archivo_csv}")
if not archivo_raw.exists():
    raise FileNotFoundError(f"No existe el Excel raw esperado: {archivo_raw}")

Raíz repo: /Users/fedeur/ProjecteData
Ruta relativa: Equip_31/Data/Processed/EAL/2024/EAL-16.csv
CSV existe: True
CSV resuelto: /Users/fedeur/ProjecteData/Equip_31/Data/Processed/EAL/2024/EAL-16.csv
Raw existe: True
Raw resuelto: /Users/fedeur/ProjecteData/Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx

## Funciones auxiliares

Estas funciones limpian texto, detectan las subtablas internas de `EAL-16` y asignan metadatos estructurales: ámbito, sector, tamaño de empresa y CCAA.

In [49]:
# ============================================================
# FUNCIONES AUXILIARES
# ============================================================

def limpiar_texto(valor):
    if pd.isna(valor):
        return ""
    valor = str(valor).replace("\n", " ")
    valor = re.sub(r"\s+", " ", valor)
    return valor.strip()

def quitar_acentos(texto):
    texto = unicodedata.normalize("NFKD", str(texto))
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    return texto.lower().strip()

def extraer_codigo_subtabla(texto):
    match = re.match(r"^(EAL-16[a-f]?)\.", limpiar_texto(texto), flags=re.IGNORECASE)
    return match.group(1).upper() if match else None

def metadatos_subtabla(codigo, titulo):
    """
    Asigna solo las dimensiones que realmente desagrega cada subtabla.

    Regla metodológica para EAL-16:
    - EAL-16: total empresas; no desagrega por sector, tamaño ni CCAA.
    - EAL-16a/b/c: desagrega por tamaño de empresa; sector y CCAA no aplican.
    - EAL-16d/e/f: desagrega por sector agregado; tamaño y CCAA no aplican.
    """
    metadatos = {
        "Ámbito": "Total empresas",
        "Sector": "",
        "Tamaño Empresa": "",
        "CCAA": "",
    }

    if codigo == "EAL-16A":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = "5 a 49 trabajadores"
    elif codigo == "EAL-16B":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = "50 a 499 trabajadores"
    elif codigo == "EAL-16C":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = "Más de 499 trabajadores"
    elif codigo == "EAL-16D":
        metadatos["Ámbito"] = "Sector agregado"
        metadatos["Sector"] = "Industria"
    elif codigo == "EAL-16E":
        metadatos["Ámbito"] = "Sector agregado"
        metadatos["Sector"] = "Construcción"
    elif codigo == "EAL-16F":
        metadatos["Ámbito"] = "Sector agregado"
        metadatos["Sector"] = "Servicios"

    return metadatos

def fila_es_cabecera(row):
    valores = [limpiar_texto(x).upper() for x in row.tolist()]
    return {"TOTAL", "NADA", "POCO", "BASTANTE", "MUCHO"}.issubset(set(valores))

## Lectura del CSV original

Se lee el CSV procesado por la extracción previa, sin asumir encabezado fijo.

In [50]:
# ============================================================
# LECTURA DEL CSV ORIGINAL
# ============================================================

df_raw = pd.read_csv(
    archivo_csv,
    header=None,
    dtype=str,
    keep_default_na=False
)

df_raw = df_raw.map(limpiar_texto)
df_raw = df_raw.replace("", pd.NA)
df_raw = df_raw.dropna(how="all")
df_raw = df_raw.dropna(axis=1, how="all")
df_raw = df_raw.fillna("").reset_index(drop=True)

print("Dimensión original:", df_raw.shape)
display(df_raw.head(20))

Dimensión original: (93, 6)

,0,1,2,3,4,5
0,ENCUESTA ANUAL LABORAL,,,,,EAL
1,,,,,,Volver al índice
2,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,,,,,
3,Año 2024. Porcentaje sobre el total de empresas.,,,,,
4,,TOTAL,NADA,POCO,BASTANTE,MUCHO
5,De dirección,100,10.414,18.818,40.283,30.484
6,De trabajo en equipo,100,2.224,5.822,45.125,46.829
7,De atención al público/ trato a clientes,100,5.128,13.392,37.144,44.336
8,Administrativas de oficina,100,11.117,25.313,37.788,25.782
9,De resolución de problemas (localización de pr...,100,5.893,15.752,44.063,34.292
10,En lenguas extranjeras,100,23.022,40.356,24.568,12.054
11,Básicas de cálculo y/o comunicación oral o esc...,100,22.688,36.513,29.697,11.102
12,Generales de tecnologías de la información,100,13.593,29.346,39.173,17.888
13,Profesionales de tecnologías de la información,100,26.908,37.656,24.493,10.944
14,"Competencias técnicas, prácticas y otras espec...",100,13.417,18.861,36.496,31.226
15,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,,,,,
16,Año 2024. Porcentaje respecto al total de empr...,,,,,
17,,TOTAL,NADA,POCO,BASTANTE,MUCHO
18,De dirección,100,11.075,19.589,39.991,29.345
19,De trabajo en equipo,100,2.321,5.976,45.426,46.277

## Conversión de EAL-16 a formato largo

`EAL-16.csv` contiene varias subtablas apiladas: total, tamaños de empresa y sectores. El parser detecta cada bloque y convierte las columnas `TOTAL`, `NADA`, `POCO`, `BASTANTE` y `MUCHO` en la columna `Variable`.

In [51]:
# ============================================================
# PARSEAR SUBTABLAS Y PASAR A FORMATO LARGO
# ============================================================

registros = []
titulo_actual = None
codigo_actual = None
variables_actuales = None
metadatos_actuales = None

for _, row in df_raw.iterrows():
    primera_celda = limpiar_texto(row.iloc[0])
    codigo_detectado = extraer_codigo_subtabla(primera_celda)

    if codigo_detectado:
        codigo_actual = codigo_detectado
        titulo_actual = primera_celda
        variables_actuales = None
        metadatos_actuales = metadatos_subtabla(codigo_actual, titulo_actual)
        continue

    if codigo_actual and fila_es_cabecera(row):
        variables_actuales = [limpiar_texto(x).upper() for x in row.tolist()]
        continue

    if not (codigo_actual and variables_actuales):
        continue

    categoria = primera_celda
    if categoria == "":
        continue

    for posicion, variable in enumerate(variables_actuales):
        if posicion == 0 or variable == "":
            continue

        valor = limpiar_texto(row.iloc[posicion]) if posicion < len(row) else ""
        if valor == "":
            continue

        registros.append({
            "Año": ANIO,
            "Hoja": HOJA,
            "Título de tabla": titulo_actual,
            "Categoría": categoria,
            "Variable": variable,
            "Valor": valor,
            "Ámbito": metadatos_actuales["Ámbito"],
            "Sector": metadatos_actuales["Sector"],
            "Tamaño Empresa": metadatos_actuales["Tamaño Empresa"],
            "CCAA": metadatos_actuales["CCAA"],
        })

df_largo = pd.DataFrame(registros)
df_largo["Valor"] = pd.to_numeric(df_largo["Valor"], errors="coerce")

columnas_finales = [
    "Año",
    "Hoja",
    "Título de tabla",
    "Categoría",
    "Variable",
    "Valor",
    "Ámbito",
    "Sector",
    "Tamaño Empresa",
    "CCAA",
]

df_largo = df_largo[columnas_finales]

print("Dimensión final:", df_largo.shape)
print("Subtablas detectadas:", df_largo["Título de tabla"].nunique())
print("Categorías detectadas:", df_largo["Categoría"].nunique())
display(df_largo.head(50))

Dimensión final: (350, 10)
Subtablas detectadas: 7
Categorías detectadas: 10

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,TOTAL,100.000,Total empresas,,,
1,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,NADA,10.414,Total empresas,,,
2,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,POCO,18.818,Total empresas,,,
3,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,BASTANTE,40.283,Total empresas,,,
4,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,MUCHO,30.484,Total empresas,,,
5,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,TOTAL,100.000,Total empresas,,,
6,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,NADA,2.224,Total empresas,,,
7,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,POCO,5.822,Total empresas,,,
8,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,BASTANTE,45.125,Total empresas,,,
9,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,MUCHO,46.829,Total empresas,,,
10,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,TOTAL,100.000,Total empresas,,,
11,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,NADA,5.128,Total empresas,,,
12,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,POCO,13.392,Total empresas,,,
13,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,BASTANTE,37.144,Total empresas,,,
14,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,MUCHO,44.336,Total empresas,,,
15,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,TOTAL,100.000,Total empresas,,,
16,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,NADA,11.117,Total empresas,,,
17,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,POCO,25.313,Total empresas,,,
18,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,BASTANTE,37.788,Total empresas,,,
19,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,MUCHO,25.782,Total empresas,,,
20,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,TOTAL,100.000,Total empresas,,,
21,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,NADA,5.893,Total empresas,,,
22,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,POCO,15.752,Total empresas,,,
23,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,BASTANTE,44.063,Total empresas,,,
24,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,MUCHO,34.292,Total empresas,,,
25,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,TOTAL,100.000,Total empresas,,,
26,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,NADA,23.022,Total empresas,,,
27,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,POCO,40.356,Total empresas,,,
28,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,BASTANTE,24.568,Total empresas,,,
29,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,MUCHO,12.054,Total empresas,,,
30,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,TOTAL,100.000,Total empresas,,,
31,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,NADA,22.688,Total empresas,,,
32,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,POCO,36.513,Total empresas,,,
33,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,BASTANTE,29.697,Total empresas,,,
34,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,MUCHO,11.102,Total empresas,,,
35,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,TOTAL,100.000,Total empresas,,,
36,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,NADA,13.593,Total empresas,,,
37,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,POCO,29.346,Total empresas,,,
38,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,BASTANTE,39.173,Total empresas,,,
39,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,MUCHO,17.888,Total empresas,,,
40,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,TOTAL,100.000,Total empresas,,,
41,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,NADA,26.908,Total empresas,,,
42,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,POCO,37.656,Total empresas,,,
43,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,BASTANTE,24.493,Total empresas,,,
44,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,MUCHO,10.944,Total empresas,,,
45,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",TOTAL,100.000,Total empresas,,,
46,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",NADA,13.417,Total empresas,,,
47,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",POCO,18.861,Total empresas,,,
48,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",BASTANTE,36.496,Total empresas,,,
49,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",MUCHO,31.226,Total empresas,,,

## Validación interna y visualización completa de EAL-16

Se comprueban dimensiones y conteo esperado, y después se muestra completo `df_largo` para revisión manual.

In [52]:
# ============================================================
# VALIDACIÓN INTERNA Y VISUALIZACIÓN COMPLETA DE EAL-16
# ============================================================

columnas_esperadas = [
    "Año", "Hoja", "Título de tabla", "Categoría", "Variable",
    "Valor", "Ámbito", "Sector", "Tamaño Empresa", "CCAA"
]

assert list(df_largo.columns) == columnas_esperadas
assert df_largo.shape == (350, 10)
assert not df_largo.empty
assert df_largo["Valor"].notna().all()

print("EAL-16 validado internamente")
print("Forma df_largo:", df_largo.shape)
print("Cálculo esperado: 7 bloques x 10 competencias x 5 variables = 350 registros")

print()
print("Resumen para revisar contra el Excel raw:")
display(
    df_largo.groupby(["Ámbito", "Sector", "Tamaño Empresa", "CCAA"], dropna=False)
    .size()
    .reset_index(name="n_registros")
)

print()
print("df_largo completo:")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_largo)

EAL-16 validado internamente
Forma df_largo: (350, 10)
Cálculo esperado: 7 bloques x 10 competencias x 5 variables = 350 registros

Resumen para revisar contra el Excel raw:

            Ámbito        Sector           Tamaño Empresa CCAA  n_registros
0  Sector agregado  Construcción                                         50
1  Sector agregado     Industria                                         50
2  Sector agregado     Servicios                                         50
3   Tamaño empresa                    5 a 49 trabajadores                50
4   Tamaño empresa                  50 a 499 trabajadores                50
5   Tamaño empresa                Más de 499 trabajadores                50
6   Total empresas                                                       50

df_largo completo:

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De dirección,TOTAL,100.000,Total empresas,,,
1,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De dirección,NADA,10.414,Total empresas,,,
2,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De dirección,POCO,18.818,Total empresas,,,
3,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De dirección,BASTANTE,40.283,Total empresas,,,
4,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De dirección,MUCHO,30.484,Total empresas,,,
5,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De trabajo en equipo,TOTAL,100.000,Total empresas,,,
6,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De trabajo en equipo,NADA,2.224,Total empresas,,,
7,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De trabajo en equipo,POCO,5.822,Total empresas,,,
8,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De trabajo en equipo,BASTANTE,45.125,Total empresas,,,
9,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De trabajo en equipo,MUCHO,46.829,Total empresas,,,
10,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De atención al público/ trato a clientes,TOTAL,100.000,Total empresas,,,
11,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De atención al público/ trato a clientes,NADA,5.128,Total empresas,,,
12,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De atención al público/ trato a clientes,POCO,13.392,Total empresas,,,
13,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De atención al público/ trato a clientes,BASTANTE,37.144,Total empresas,,,
14,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De atención al público/ trato a clientes,MUCHO,44.336,Total empresas,,,
15,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Administrativas de oficina,TOTAL,100.000,Total empresas,,,
16,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Administrativas de oficina,NADA,11.117,Total empresas,,,
17,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Administrativas de oficina,POCO,25.313,Total empresas,,,
18,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Administrativas de oficina,BASTANTE,37.788,Total empresas,,,
19,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Administrativas de oficina,MUCHO,25.782,Total empresas,,,
20,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",TOTAL,100.000,Total empresas,,,
21,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",NADA,5.893,Total empresas,,,
22,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",POCO,15.752,Total empresas,,,
23,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",BASTANTE,44.063,Total empresas,,,
24,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",MUCHO,34.292,Total empresas,,,
25,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,En lenguas extranjeras,TOTAL,100.000,Total empresas,,,
26,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,En lenguas extranjeras,NADA,23.022,Total empresas,,,
27,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,En lenguas extranjeras,POCO,40.356,Total empresas,,,
28,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,En lenguas extranjeras,BASTANTE,24.568,Total empresas,,,
29,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,En lenguas extranjeras,MUCHO,12.054,Total empresas,,,
30,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Básicas de cálculo y/o comunicación oral o escrita,TOTAL,100.000,Total empresas,,,
31,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Básicas de cálculo y/o comunicación oral o escrita,NADA,22.688,Total empresas,,,
32,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Básicas de cálculo y/o comunicación oral o escrita,POCO,36.513,Total empresas,,,
33,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Básicas de cálculo y/o comunicación oral o escrita,BASTANTE,29.697,Total empresas,,,
34,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Básicas de cálculo y/o comunicación oral o escrita,MUCHO,11.102,Total empresas,,,
35,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Generales de tecnologías de la información,TOTAL,100.000,Total empresas,,,
36,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Generales de tecnologías de la información,NADA,13.593,Total empresas,,,
37,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Generales de tecnologías de la información,POCO,29.346,Total empresas,,,
38,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Generales de tecnologías de la información,BASTANTE,39.173,Total empresas,,,
39,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Generales de tecnologías de la información,MUCHO,17.888,Total empresas,,,
40,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Profesionales de tecnologías de la información,TOTAL,100.000,Total empresas,,,
41,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Profesionales de tecnologías de la información,NADA,26.908,Total empresas,,,
42,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Profesionales de tecnologías de la información,POCO,37.656,Total empresas,,,
43,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Profesionales de tecnologías de la información,BASTANTE,24.493,Total empresas,,,
44,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Profesionales de tecnologías de la información,MUCHO,10.944,Total empresas,,,
45,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",TOTAL,100.000,Total empresas,,,
46,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",NADA,13.417,Total empresas,,,
47,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",POCO,18.861,Total empresas,,,
48,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",BASTANTE,36.496,Total empresas,,,
49,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",MUCHO,31.226,Total empresas,,,
50,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De dirección,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
51,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De dirección,NADA,11.075,Tamaño empresa,,5 a 49 trabajadores,
52,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De dirección,POCO,19.589,Tamaño empresa,,5 a 49 trabajadores,
53,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De dirección,BASTANTE,39.991,Tamaño empresa,,5 a 49 trabajadores,
54,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De dirección,MUCHO,29.345,Tamaño empresa,,5 a 49 trabajadores,
55,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De trabajo en equipo,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
56,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De trabajo en equipo,NADA,2.321,Tamaño empresa,,5 a 49 trabajadores,
57,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De trabajo en equipo,POCO,5.976,Tamaño empresa,,5 a 49 trabajadores,
58,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De trabajo en equipo,BASTANTE,45.426,Tamaño empresa,,5 a 49 trabajadores,
59,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De trabajo en equipo,MUCHO,46.277,Tamaño empresa,,5 a 49 trabajadores,
60,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De atención al público/ trato a clientes,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
61,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De atención al público/ trato a clientes,NADA,5.200,Tamaño empresa,,5 a 49 trabajadores,
62,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De atención al público/ trato a clientes,POCO,13.151,Tamaño empresa,,5 a 49 trabajadores,
63,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De atención al público/ trato a clientes,BASTANTE,36.884,Tamaño empresa,,5 a 49 trabajadores,
64,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De atención al público/ trato a clientes,MUCHO,44.764,Tamaño empresa,,5 a 49 trabajadores,
65,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Administrativas de oficina,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
66,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Administrativas de oficina,NADA,11.815,Tamaño empresa,,5 a 49 trabajadores,
67,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Administrativas de oficina,POCO,25.651,Tamaño empresa,,5 a 49 trabajadores,
68,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Administrativas de oficina,BASTANTE,36.989,Tamaño empresa,,5 a 49 trabajadores,
69,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Administrativas de oficina,MUCHO,25.545,Tamaño empresa,,5 a 49 trabajadores,
70,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
71,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",NADA,6.161,Tamaño empresa,,5 a 49 trabajadores,
72,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",POCO,16.142,Tamaño empresa,,5 a 49 trabajadores,
73,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",BASTANTE,43.592,Tamaño empresa,,5 a 49 trabajadores,
74,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",MUCHO,34.104,Tamaño empresa,,5 a 49 trabajadores,
75,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,En lenguas extranjeras,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
76,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,En lenguas extranjeras,NADA,23.741,Tamaño empresa,,5 a 49 trabajadores,
77,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,En lenguas extranjeras,POCO,40.753,Tamaño empresa,,5 a 49 trabajadores,
78,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,En lenguas extranjeras,BASTANTE,23.986,Tamaño empresa,,5 a 49 trabajadores,
79,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,En lenguas extranjeras,MUCHO,11.519,Tamaño empresa,,5 a 49 trabajadores,
80,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Básicas de cálculo y/o comunicación oral o escrita,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
81,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Básicas de cálculo y/o comunicación oral o escrita,NADA,23.741,Tamaño empresa,,5 a 49 trabajadores,
82,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Básicas de cálculo y/o comunicación oral o escrita,POCO,36.767,Tamaño empresa,,5 a 49 trabajadores,
83,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Básicas de cálculo y/o comunicación oral o escrita,BASTANTE,28.759,Tamaño empresa,,5 a 49 trabajadores,
84,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Básicas de cálculo y/o comunicación oral o escrita,MUCHO,10.733,Tamaño empresa,,5 a 49 trabajadores,
85,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Generales de tecnologías de la información,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
86,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Generales de tecnologías de la información,NADA,14.343,Tamaño empresa,,5 a 49 trabajadores,
87,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Generales de tecnologías de la información,POCO,30.144,Tamaño empresa,,5 a 49 trabajadores,
88,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Generales de tecnologías de la información,BASTANTE,38.530,Tamaño empresa,,5 a 49 trabajadores,
89,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Generales de tecnologías de la información,MUCHO,16.983,Tamaño empresa,,5 a 49 trabajadores,
90,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Profesionales de tecnologías de la información,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,

In [53]:
pd.set_option("display.max_rows", None)

display(df_largo)

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,TOTAL,100.000,Total empresas,,,
1,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,NADA,10.414,Total empresas,,,
2,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,POCO,18.818,Total empresas,,,
3,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,BASTANTE,40.283,Total empresas,,,
4,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De dirección,MUCHO,30.484,Total empresas,,,
5,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,TOTAL,100.000,Total empresas,,,
6,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,NADA,2.224,Total empresas,,,
7,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,POCO,5.822,Total empresas,,,
8,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,BASTANTE,45.125,Total empresas,,,
9,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De trabajo en equipo,MUCHO,46.829,Total empresas,,,
10,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,TOTAL,100.000,Total empresas,,,
11,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,NADA,5.128,Total empresas,,,
12,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,POCO,13.392,Total empresas,,,
13,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,BASTANTE,37.144,Total empresas,,,
14,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De atención al público/ trato a clientes,MUCHO,44.336,Total empresas,,,
15,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,TOTAL,100.000,Total empresas,,,
16,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,NADA,11.117,Total empresas,,,
17,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,POCO,25.313,Total empresas,,,
18,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,BASTANTE,37.788,Total empresas,,,
19,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Administrativas de oficina,MUCHO,25.782,Total empresas,,,
20,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,TOTAL,100.000,Total empresas,,,
21,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,NADA,5.893,Total empresas,,,
22,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,POCO,15.752,Total empresas,,,
23,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,BASTANTE,44.063,Total empresas,,,
24,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,De resolución de problemas (localización de pr...,MUCHO,34.292,Total empresas,,,
25,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,TOTAL,100.000,Total empresas,,,
26,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,NADA,23.022,Total empresas,,,
27,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,POCO,40.356,Total empresas,,,
28,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,BASTANTE,24.568,Total empresas,,,
29,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,En lenguas extranjeras,MUCHO,12.054,Total empresas,,,
30,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,TOTAL,100.000,Total empresas,,,
31,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,NADA,22.688,Total empresas,,,
32,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,POCO,36.513,Total empresas,,,
33,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,BASTANTE,29.697,Total empresas,,,
34,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Básicas de cálculo y/o comunicación oral o esc...,MUCHO,11.102,Total empresas,,,
35,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,TOTAL,100.000,Total empresas,,,
36,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,NADA,13.593,Total empresas,,,
37,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,POCO,29.346,Total empresas,,,
38,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,BASTANTE,39.173,Total empresas,,,
39,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Generales de tecnologías de la información,MUCHO,17.888,Total empresas,,,
40,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,TOTAL,100.000,Total empresas,,,
41,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,NADA,26.908,Total empresas,,,
42,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,POCO,37.656,Total empresas,,,
43,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,BASTANTE,24.493,Total empresas,,,
44,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,Profesionales de tecnologías de la información,MUCHO,10.944,Total empresas,,,
45,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",TOTAL,100.000,Total empresas,,,
46,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",NADA,13.417,Total empresas,,,
47,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",POCO,18.861,Total empresas,,,
48,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",BASTANTE,36.496,Total empresas,,,
49,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,"Competencias técnicas, prácticas y otras espec...",MUCHO,31.226,Total empresas,,,
50,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De dirección,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
51,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De dirección,NADA,11.075,Tamaño empresa,,5 a 49 trabajadores,
52,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De dirección,POCO,19.589,Tamaño empresa,,5 a 49 trabajadores,
53,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De dirección,BASTANTE,39.991,Tamaño empresa,,5 a 49 trabajadores,
54,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De dirección,MUCHO,29.345,Tamaño empresa,,5 a 49 trabajadores,
55,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De trabajo en equipo,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
56,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De trabajo en equipo,NADA,2.321,Tamaño empresa,,5 a 49 trabajadores,
57,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De trabajo en equipo,POCO,5.976,Tamaño empresa,,5 a 49 trabajadores,
58,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De trabajo en equipo,BASTANTE,45.426,Tamaño empresa,,5 a 49 trabajadores,
59,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De trabajo en equipo,MUCHO,46.277,Tamaño empresa,,5 a 49 trabajadores,
60,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De atención al público/ trato a clientes,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
61,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De atención al público/ trato a clientes,NADA,5.200,Tamaño empresa,,5 a 49 trabajadores,
62,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De atención al público/ trato a clientes,POCO,13.151,Tamaño empresa,,5 a 49 trabajadores,
63,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De atención al público/ trato a clientes,BASTANTE,36.884,Tamaño empresa,,5 a 49 trabajadores,
64,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De atención al público/ trato a clientes,MUCHO,44.764,Tamaño empresa,,5 a 49 trabajadores,
65,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Administrativas de oficina,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
66,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Administrativas de oficina,NADA,11.815,Tamaño empresa,,5 a 49 trabajadores,
67,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Administrativas de oficina,POCO,25.651,Tamaño empresa,,5 a 49 trabajadores,
68,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Administrativas de oficina,BASTANTE,36.989,Tamaño empresa,,5 a 49 trabajadores,
69,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Administrativas de oficina,MUCHO,25.545,Tamaño empresa,,5 a 49 trabajadores,
70,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De resolución de problemas (localización de pr...,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
71,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De resolución de problemas (localización de pr...,NADA,6.161,Tamaño empresa,,5 a 49 trabajadores,
72,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De resolución de problemas (localización de pr...,POCO,16.142,Tamaño empresa,,5 a 49 trabajadores,
73,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De resolución de problemas (localización de pr...,BASTANTE,43.592,Tamaño empresa,,5 a 49 trabajadores,
74,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,De resolución de problemas (localización de pr...,MUCHO,34.104,Tamaño empresa,,5 a 49 trabajadores,
75,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,En lenguas extranjeras,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
76,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,En lenguas extranjeras,NADA,23.741,Tamaño empresa,,5 a 49 trabajadores,
77,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,En lenguas extranjeras,POCO,40.753,Tamaño empresa,,5 a 49 trabajadores,
78,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,En lenguas extranjeras,BASTANTE,23.986,Tamaño empresa,,5 a 49 trabajadores,
79,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,En lenguas extranjeras,MUCHO,11.519,Tamaño empresa,,5 a 49 trabajadores,
80,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Básicas de cálculo y/o comunicación oral o esc...,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
81,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Básicas de cálculo y/o comunicación oral o esc...,NADA,23.741,Tamaño empresa,,5 a 49 trabajadores,
82,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Básicas de cálculo y/o comunicación oral o esc...,POCO,36.767,Tamaño empresa,,5 a 49 trabajadores,
83,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Básicas de cálculo y/o comunicación oral o esc...,BASTANTE,28.759,Tamaño empresa,,5 a 49 trabajadores,
84,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Básicas de cálculo y/o comunicación oral o esc...,MUCHO,10.733,Tamaño empresa,,5 a 49 trabajadores,
85,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Generales de tecnologías de la información,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
86,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Generales de tecnologías de la información,NADA,14.343,Tamaño empresa,,5 a 49 trabajadores,
87,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Generales de tecnologías de la información,POCO,30.144,Tamaño empresa,,5 a 49 trabajadores,
88,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Generales de tecnologías de la información,BASTANTE,38.530,Tamaño empresa,,5 a 49 trabajadores,
89,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Generales de tecnologías de la información,MUCHO,16.983,Tamaño empresa,,5 a 49 trabajadores,
90,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Profesionales de tecnologías de la información,TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
91,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Profesionales de tecnologías de la información,NADA,28.160,Tamaño empresa,,5 a 49 trabajadores,
92,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Profesionales de tecnologías de la información,POCO,38.095,Tamaño empresa,,5 a 49 trabajadores,
93,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Profesionales de tecnologías de la información,BASTANTE,23.711,Tamaño empresa,,5 a 49 trabajadores,
94,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,Profesionales de tecnologías de la información,MUCHO,10.034,Tamaño empresa,,5 a 49 trabajadores,
95,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,"Competencias técnicas, prácticas y otras espec...",TOTAL,100.000,Tamaño empresa,,5 a 49 trabajadores,
96,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,"Competencias técnicas, prácticas y otras espec...",NADA,13.890,Tamaño empresa,,5 a 49 trabajadores,
97,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,"Competencias técnicas, prácticas y otras espec...",POCO,19.160,Tamaño empresa,,5 a 49 trabajadores,
98,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,"Competencias técnicas, prácticas y otras espec...",BASTANTE,36.312,Tamaño empresa,,5 a 49 trabajadores,
99,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,"Competencias técnicas, prácticas y otras espec...",MUCHO,30.638,Tamaño empresa,,5 a 49 trabajadores,
100,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De dirección,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
101,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De dirección,NADA,2.498,Tamaño empresa,,50 a 499 trabajadores,
102,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De dirección,POCO,9.573,Tamaño empresa,,50 a 499 trabajadores,
103,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De dirección,BASTANTE,43.903,Tamaño empresa,,50 a 499 trabajadores,
104,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De dirección,MUCHO,44.026,Tamaño empresa,,50 a 499 trabajadores,
105,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De trabajo en equipo,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
106,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De trabajo en equipo,NADA,1.103,Tamaño empresa,,50 a 499 trabajadores,
107,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De trabajo en equipo,POCO,4.062,Tamaño empresa,,50 a 499 trabajadores,
108,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De trabajo en equipo,BASTANTE,41.538,Tamaño empresa,,50 a 499 trabajadores,
109,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De trabajo en equipo,MUCHO,53.297,Tamaño empresa,,50 a 499 trabajadores,
110,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De atención al público/ trato a clientes,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
111,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De atención al público/ trato a clientes,NADA,4.355,Tamaño empresa,,50 a 499 trabajadores,
112,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De atención al público/ trato a clientes,POCO,16.362,Tamaño empresa,,50 a 499 trabajadores,
113,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De atención al público/ trato a clientes,BASTANTE,40.501,Tamaño empresa,,50 a 499 trabajadores,
114,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De atención al público/ trato a clientes,MUCHO,38.782,Tamaño empresa,,50 a 499 trabajadores,
115,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Administrativas de oficina,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
116,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Administrativas de oficina,NADA,2.678,Tamaño empresa,,50 a 499 trabajadores,
117,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Administrativas de oficina,POCO,21.162,Tamaño empresa,,50 a 499 trabajadores,
118,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Administrativas de oficina,BASTANTE,47.295,Tamaño empresa,,50 a 499 trabajadores,
119,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Administrativas de oficina,MUCHO,28.866,Tamaño empresa,,50 a 499 trabajadores,
120,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De resolución de problemas (localización de pr...,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
121,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De resolución de problemas (localización de pr...,NADA,2.760,Tamaño empresa,,50 a 499 trabajadores,
122,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De resolución de problemas (localización de pr...,POCO,10.937,Tamaño empresa,,50 a 499 trabajadores,
123,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De resolución de problemas (localización de pr...,BASTANTE,49.810,Tamaño empresa,,50 a 499 trabajadores,
124,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,De resolución de problemas (localización de pr...,MUCHO,36.493,Tamaño empresa,,50 a 499 trabajadores,
125,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,En lenguas extranjeras,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
126,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,En lenguas extranjeras,NADA,14.822,Tamaño empresa,,50 a 499 trabajadores,
127,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,En lenguas extranjeras,POCO,35.718,Tamaño empresa,,50 a 499 trabajadores,
128,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,En lenguas extranjeras,BASTANTE,31.244,Tamaño empresa,,50 a 499 trabajadores,
129,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,En lenguas extranjeras,MUCHO,18.217,Tamaño empresa,,50 a 499 trabajadores,
130,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Básicas de cálculo y/o comunicación oral o esc...,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
131,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Básicas de cálculo y/o comunicación oral o esc...,NADA,10.332,Tamaño empresa,,50 a 499 trabajadores,
132,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Básicas de cálculo y/o comunicación oral o esc...,POCO,33.790,Tamaño empresa,,50 a 499 trabajadores,
133,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Básicas de cálculo y/o comunicación oral o esc...,BASTANTE,40.670,Tamaño empresa,,50 a 499 trabajadores,
134,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Básicas de cálculo y/o comunicación oral o esc...,MUCHO,15.208,Tamaño empresa,,50 a 499 trabajadores,
135,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Generales de tecnologías de la información,TOTAL,100.000,Tamaño empresa,,50 a 499 trabajadores,
136,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEG...,Generales de tecnologías de la información,NADA,4.697,Tamaño empresa,,50 a 499 trabajadores,

## Normalización estructural de EAL-17 y EAL-18

Estas dos hojas tienen una estructura distinta a `EAL-16`: no son subtablas apiladas, sino una tabla con filas agrupadas por `TOTAL`, `TAMAÑO DE LA EMPRESA`, `ACTIVIDAD ECONÓMICA` y `COMUNIDAD AUTÓNOMA`. Se convierten a formato largo sin cruzar dimensiones que no aparecen cruzadas en el raw.

In [54]:
# ============================================================
# PARSER GENERAL PARA EAL-17 Y EAL-18
# ============================================================

SECCIONES_FILA = {
    "TAMAÑO DE LA EMPRESA": "Tamaño empresa",
    "ACTIVIDAD ECONÓMICA": "Sector",
    "COMUNIDAD AUTÓNOMA": "CCAA",
}


def leer_csv_hoja(hoja):
    ruta_rel = Path(f"Equip_31/Data/Processed/EAL/2024/{hoja}.csv")
    ruta = REPO_ROOT / ruta_rel
    if not ruta.exists():
        raise FileNotFoundError(f"No existe el CSV esperado: {ruta}")

    df = pd.read_csv(ruta, header=None, dtype=str, keep_default_na=False)
    df = df.map(limpiar_texto)
    df = df.replace("", pd.NA)
    df = df.dropna(how="all")
    df = df.dropna(axis=1, how="all")
    df = df.fillna("").reset_index(drop=True)
    return df, ruta_rel


def metadatos_fila(categoria, seccion_actual):
    metadatos = {
        "Ámbito": "Total empresas",
        "Sector": "",
        "Tamaño Empresa": "",
        "CCAA": "",
    }

    if categoria.upper() == "TOTAL":
        return metadatos

    if seccion_actual == "Tamaño empresa":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = categoria
    elif seccion_actual == "Sector":
        metadatos["Ámbito"] = "Sector"
        metadatos["Sector"] = categoria
    elif seccion_actual == "CCAA":
        metadatos["Ámbito"] = "CCAA"
        metadatos["CCAA"] = categoria

    return metadatos


def detectar_titulo_csv(df, hoja):
    for valor in df.iloc[:, 0].tolist():
        texto = limpiar_texto(valor)
        if texto.upper().startswith(f"{hoja}."):
            return texto
    return ""


def construir_variables_eal17(df):
    # En el CSV limpio, las cabeceras son las filas 4 y 5: grupo superior + subvariable.
    grupo_superior = [limpiar_texto(x) for x in df.iloc[4].tolist()]
    subvariable = [limpiar_texto(x) for x in df.iloc[5].tolist()]

    variables = {}
    grupo_actual = ""
    for col in range(1, df.shape[1]):
        if grupo_superior[col]:
            grupo_actual = grupo_superior[col]
        sub = subvariable[col]

        if col == 1:
            variables[col] = "TOTAL"
        elif grupo_actual and sub:
            variables[col] = f"{grupo_actual} - {sub}"
        elif grupo_actual:
            variables[col] = grupo_actual
        else:
            variables[col] = sub
    return variables, 6


def construir_variables_eal18(df):
    # En el CSV limpio, las cabeceras son las filas 4 y 5: grupo superior + subvariable.
    grupo_superior = [limpiar_texto(x) for x in df.iloc[4].tolist()]
    subvariable = [limpiar_texto(x) for x in df.iloc[5].tolist()]

    variables = {}
    grupo_actual = ""
    for col in range(1, df.shape[1]):
        if grupo_superior[col]:
            grupo_actual = grupo_superior[col]
        sub = subvariable[col]
        variables[col] = f"{grupo_actual} - {sub}" if grupo_actual and sub else (grupo_actual or sub)
    return variables, 6


def parsear_eal_17_18(hoja, constructor_variables):
    df, ruta_rel = leer_csv_hoja(hoja)
    titulo = detectar_titulo_csv(df, hoja)
    variables, fila_inicio_datos = constructor_variables(df)

    registros = []
    seccion_actual = None

    for _, row in df.iloc[fila_inicio_datos:].iterrows():
        categoria = limpiar_texto(row.iloc[0])
        if categoria == "":
            continue

        categoria_norm = categoria.upper()
        if categoria_norm in SECCIONES_FILA:
            seccion_actual = SECCIONES_FILA[categoria_norm]
            continue
        if categoria.startswith("("):
            continue

        metadatos = metadatos_fila(categoria, seccion_actual)

        for col, variable in variables.items():
            valor = limpiar_texto(row.iloc[col]) if col < len(row) else ""
            if valor == "":
                continue

            registros.append({
                "Año": ANIO,
                "Hoja": hoja,
                "Título de tabla": titulo,
                "Categoría": categoria,
                "Variable": variable,
                "Valor": pd.to_numeric(valor, errors="coerce"),
                "Ámbito": metadatos["Ámbito"],
                "Sector": metadatos["Sector"],
                "Tamaño Empresa": metadatos["Tamaño Empresa"],
                "CCAA": metadatos["CCAA"],
            })

    df_largo_hoja = pd.DataFrame(registros)[columnas_finales]
    print(f"{hoja} desde {ruta_rel}: {df.shape} -> {df_largo_hoja.shape}")
    return df_largo_hoja

## Dataframe largo de EAL-17

`EAL-17` indica si las empresas impartieron formación, con cortes por total, tamaño de empresa, actividad económica y comunidad autónoma.

In [55]:
# ============================================================
# EAL-17 A FORMATO LARGO
# ============================================================

df_eal17_largo = parsear_eal_17_18("EAL-17", construir_variables_eal17)

display(df_eal17_largo.head(40))
display(
    df_eal17_largo.groupby(["Ámbito", "Sector", "Tamaño Empresa", "CCAA"], dropna=False)
    .size()
    .reset_index(name="n_registros")
    .head(40)
)

EAL-17 desde Equip_31/Data/Processed/EAL/2024/EAL-17.csv: (42, 7) -> (192, 10)

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,TOTAL,TOTAL,100.000,Total empresas,,,
1,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,73.468,Total empresas,,,
2,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,60.220,Total empresas,,,
3,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,25.366,Total empresas,,,
4,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otr...,14.415,Total empresas,,,
5,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,TOTAL,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,26.532,Total empresas,,,
6,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 5 a 9 trabajadores,TOTAL,100.000,Tamaño empresa,,De 5 a 9 trabajadores,
7,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,65.319,Tamaño empresa,,De 5 a 9 trabajadores,
8,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,51.321,Tamaño empresa,,De 5 a 9 trabajadores,
9,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,28.014,Tamaño empresa,,De 5 a 9 trabajadores,
10,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otr...,20.665,Tamaño empresa,,De 5 a 9 trabajadores,
11,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 5 a 9 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,34.681,Tamaño empresa,,De 5 a 9 trabajadores,
12,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 10 a 49 trabajadores,TOTAL,100.000,Tamaño empresa,,De 10 a 49 trabajadores,
13,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,79.228,Tamaño empresa,,De 10 a 49 trabajadores,
14,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,64.481,Tamaño empresa,,De 10 a 49 trabajadores,
15,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,25.163,Tamaño empresa,,De 10 a 49 trabajadores,
16,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otr...,10.356,Tamaño empresa,,De 10 a 49 trabajadores,
17,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 10 a 49 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,20.772,Tamaño empresa,,De 10 a 49 trabajadores,
18,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 50 a 249 trabajadores,TOTAL,100.000,Tamaño empresa,,De 50 a 249 trabajadores,
19,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,94.759,Tamaño empresa,,De 50 a 249 trabajadores,
20,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,79.559,Tamaño empresa,,De 50 a 249 trabajadores,
21,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,15.091,Tamaño empresa,,De 50 a 249 trabajadores,
22,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otr...,5.349,Tamaño empresa,,De 50 a 249 trabajadores,
23,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 50 a 249 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,5.241,Tamaño empresa,,De 50 a 249 trabajadores,
24,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 250 a 499 trabajadores,TOTAL,100.000,Tamaño empresa,,De 250 a 499 trabajadores,
25,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,98.371,Tamaño empresa,,De 250 a 499 trabajadores,
26,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,85.856,Tamaño empresa,,De 250 a 499 trabajadores,
27,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,11.710,Tamaño empresa,,De 250 a 499 trabajadores,
28,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otr...,2.434,Tamaño empresa,,De 250 a 499 trabajadores,
29,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,De 250 a 499 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,1.629,Tamaño empresa,,De 250 a 499 trabajadores,
30,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Más de 499 trabajadores,TOTAL,100.000,Tamaño empresa,,Más de 499 trabajadores,
31,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,99.298,Tamaño empresa,,Más de 499 trabajadores,
32,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,88.305,Tamaño empresa,,Más de 499 trabajadores,
33,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,9.742,Tamaño empresa,,Más de 499 trabajadores,
34,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otr...,1.953,Tamaño empresa,,Más de 499 trabajadores,
35,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Más de 499 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,0.702,Tamaño empresa,,Más de 499 trabajadores,
36,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Industria,TOTAL,100.000,Sector,Industria,,
37,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,76.222,Sector,Industria,,
38,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartic...,64.223,Sector,Industria,,
39,2024,EAL-17,EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓ...,Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo imp...,20.911,Sector,Industria,,

,Ámbito,Sector,Tamaño Empresa,CCAA,n_registros
0,CCAA,,,Andalucía,6
1,CCAA,,,Aragón,6
2,CCAA,,,Asturias (Principado de),6
3,CCAA,,,Balears (Illes),6
4,CCAA,,,Canarias,6
5,CCAA,,,Cantabria,6
6,CCAA,,,Castilla y León,6
7,CCAA,,,Castilla-La Mancha,6
8,CCAA,,,Cataluña,6
9,CCAA,,,Comunitat Valenciana,6
10,CCAA,,,Extremadura,6
11,CCAA,,,Galicia,6
12,CCAA,,,Madrid (Comunidad de),6
13,CCAA,,,Murcia (Región de),6
14,CCAA,,,Navarra (Comunidad Foral de),6
15,CCAA,,,País Vasco,6
16,CCAA,,,"Rioja, La",6
17,Sector,Actividades administrativas y servicios auxili...,,,6
18,Sector,"Actividades artísticas, recreativas y de entre...",,,6
19,Sector,"Actividades profesionales, científicas y técnicas",,,6
20,Sector,Comercio y reparación de vehículos,,,6
21,Sector,Construcción,,,6
22,Sector,Hostelería,,,6
23,Sector,Industria,,,6
24,Sector,"Información, comunicaciones, actividades finan...",,,6
25,Sector,Transporte y almacenamiento,,,6
26,Tamaño empresa,,De 10 a 49 trabajadores,,6
27,Tamaño empresa,,De 250 a 499 trabajadores,,6
28,Tamaño empresa,,De 5 a 9 trabajadores,,6
29,Tamaño empresa,,De 50 a 249 trabajadores,,6
30,Tamaño empresa,,Más de 499 trabajadores,,6
31,Total empresas,,,,6

## Dataframe largo de EAL-18

`EAL-18` relaciona detección de necesidades formativas con impartición o no de formación, con los mismos cortes por total, tamaño de empresa, actividad económica y comunidad autónoma.

In [56]:
# ============================================================
# EAL-18 A FORMATO LARGO
# ============================================================

df_eal18_largo = parsear_eal_17_18("EAL-18", construir_variables_eal18)

display(df_eal18_largo.head(40))
display(
    df_eal18_largo.groupby(["Ámbito", "Sector", "Tamaño Empresa", "CCAA"], dropna=False)
    .size()
    .reset_index(name="n_registros")
    .head(40)
)

EAL-18 desde Equip_31/Data/Processed/EAL/2024/EAL-18.csv: (43, 7) -> (192, 10)

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,29.123694,Total empresas,,,
1,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,89.974511,Total empresas,,,
2,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,10.025489,Total empresas,,,
3,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,70.876306,Total empresas,,,
4,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,66.570590,Total empresas,,,
5,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,33.429410,Total empresas,,,
6,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 5 a 9 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,23.671862,Tamaño empresa,,De 5 a 9 trabajadores,
7,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 5 a 9 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,83.544726,Tamaño empresa,,De 5 a 9 trabajadores,
8,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 5 a 9 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,16.455274,Tamaño empresa,,De 5 a 9 trabajadores,
9,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 5 a 9 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,76.328138,Tamaño empresa,,De 5 a 9 trabajadores,
10,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 5 a 9 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,59.481181,Tamaño empresa,,De 5 a 9 trabajadores,
11,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 5 a 9 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,40.518819,Tamaño empresa,,De 5 a 9 trabajadores,
12,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 10 a 49 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,31.724690,Tamaño empresa,,De 10 a 49 trabajadores,
13,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 10 a 49 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,93.100741,Tamaño empresa,,De 10 a 49 trabajadores,
14,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 10 a 49 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,6.899259,Tamaño empresa,,De 10 a 49 trabajadores,
15,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 10 a 49 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,68.275310,Tamaño empresa,,De 10 a 49 trabajadores,
16,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 10 a 49 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,72.749236,Tamaño empresa,,De 10 a 49 trabajadores,
17,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 10 a 49 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,27.250764,Tamaño empresa,,De 10 a 49 trabajadores,
18,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 50 a 249 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,48.701094,Tamaño empresa,,De 50 a 249 trabajadores,
19,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 50 a 249 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,98.742720,Tamaño empresa,,De 50 a 249 trabajadores,
20,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 50 a 249 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,1.266525,Tamaño empresa,,De 50 a 249 trabajadores,
21,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 50 a 249 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,51.298906,Tamaño empresa,,De 50 a 249 trabajadores,
22,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 50 a 249 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,90.863612,Tamaño empresa,,De 50 a 249 trabajadores,
23,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 50 a 249 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,9.136388,Tamaño empresa,,De 50 a 249 trabajadores,
24,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 250 a 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,58.708189,Tamaño empresa,,De 250 a 499 trabajadores,
25,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 250 a 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,100.000000,Tamaño empresa,,De 250 a 499 trabajadores,
26,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 250 a 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,0.000000,Tamaño empresa,,De 250 a 499 trabajadores,
27,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 250 a 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,41.253364,Tamaño empresa,,De 250 a 499 trabajadores,
28,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 250 a 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,96.831314,Tamaño empresa,,De 250 a 499 trabajadores,
29,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,De 250 a 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,3.168686,Tamaño empresa,,De 250 a 499 trabajadores,
30,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Más de 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,62.753623,Tamaño empresa,,Más de 499 trabajadores,
31,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Más de 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,99.769053,Tamaño empresa,,Más de 499 trabajadores,
32,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Más de 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,0.230947,Tamaño empresa,,Más de 499 trabajadores,
33,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Más de 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,37.246377,Tamaño empresa,,Más de 499 trabajadores,
34,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Más de 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,98.702983,Tamaño empresa,,Más de 499 trabajadores,
35,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Más de 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,1.297017,Tamaño empresa,,Más de 499 trabajadores,
36,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Industria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,29.340514,Sector,Industria,,
37,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Industria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,91.943067,Sector,Industria,,
38,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Industria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSON...,8.063373,Sector,Industria,,
39,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESID...,Industria,NO DETECTARON NECESIDADES FORMATIVAS DE SU PER...,70.659486,Sector,Industria,,

,Ámbito,Sector,Tamaño Empresa,CCAA,n_registros
0,CCAA,,,Andalucía,6
1,CCAA,,,Aragón,6
2,CCAA,,,Asturias (Principado de),6
3,CCAA,,,Balears (Illes),6
4,CCAA,,,Canarias,6
5,CCAA,,,Cantabria,6
6,CCAA,,,Castilla y León,6
7,CCAA,,,Castilla-La Mancha,6
8,CCAA,,,Cataluña,6
9,CCAA,,,Comunitat Valenciana,6
10,CCAA,,,Extremadura,6
11,CCAA,,,Galicia,6
12,CCAA,,,Madrid (Comunidad de),6
13,CCAA,,,Murcia (Región de),6
14,CCAA,,,Navarra (Comunidad Foral de),6
15,CCAA,,,País Vasco,6
16,CCAA,,,"Rioja, La",6
17,Sector,Actividades administrativas y servicios auxili...,,,6
18,Sector,"Actividades artísticas, recreativas y de entre...",,,6
19,Sector,"Actividades profesionales, científicas y técnicas",,,6
20,Sector,Comercio y reparación de vehículos,,,6
21,Sector,Construcción,,,6
22,Sector,Hostelería,,,6
23,Sector,Industria,,,6
24,Sector,"Información, comunicaciones, actividades finan...",,,6
25,Sector,Transporte y almacenamiento,,,6
26,Tamaño empresa,,De 10 a 49 trabajadores,,6
27,Tamaño empresa,,De 250 a 499 trabajadores,,6
28,Tamaño empresa,,De 5 a 9 trabajadores,,6
29,Tamaño empresa,,De 50 a 249 trabajadores,,6
30,Tamaño empresa,,Más de 499 trabajadores,,6
31,Total empresas,,,,6

## Validación interna y visualización completa de EAL-17 y EAL-18

Se comprueban dimensiones y conteos esperados, y después se muestran completos los dataframes para revisión manual contra el Excel raw si hace falta.

In [57]:
# ============================================================
# VALIDACIÓN INTERNA Y VISUALIZACIÓN COMPLETA DE EAL-17 Y EAL-18
# ============================================================

assert df_eal17_largo.shape == (192, 10)
assert df_eal18_largo.shape == (192, 10)
assert list(df_eal17_largo.columns) == columnas_finales
assert list(df_eal18_largo.columns) == columnas_finales
assert df_eal17_largo["Valor"].notna().all()
assert df_eal18_largo["Valor"].notna().all()

print("EAL-17 y EAL-18 validados internamente")
print("EAL-17: 32 filas de categorías/desgloses x 6 variables = 192 registros")
print("EAL-18: 32 filas de categorías/desgloses x 6 variables = 192 registros")

print()
print("Resumen EAL-17 para revisar contra el Excel raw:")
display(
    df_eal17_largo.groupby(["Ámbito", "Sector", "Tamaño Empresa", "CCAA"], dropna=False)
    .size()
    .reset_index(name="n_registros")
)

print()
print("df_eal17_largo completo:")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal17_largo)

print()
print("Resumen EAL-18 para revisar contra el Excel raw:")
display(
    df_eal18_largo.groupby(["Ámbito", "Sector", "Tamaño Empresa", "CCAA"], dropna=False)
    .size()
    .reset_index(name="n_registros")
)

print()
print("df_eal18_largo completo:")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal18_largo)

EAL-17 y EAL-18 validados internamente
EAL-17: 32 filas de categorías/desgloses x 6 variables = 192 registros
EAL-18: 32 filas de categorías/desgloses x 6 variables = 192 registros

Resumen EAL-17 para revisar contra el Excel raw:

,Ámbito,Sector,Tamaño Empresa,CCAA,n_registros
0,CCAA,,,Andalucía,6
1,CCAA,,,Aragón,6
2,CCAA,,,Asturias (Principado de),6
3,CCAA,,,Balears (Illes),6
4,CCAA,,,Canarias,6
5,CCAA,,,Cantabria,6
6,CCAA,,,Castilla y León,6
7,CCAA,,,Castilla-La Mancha,6
8,CCAA,,,Cataluña,6
9,CCAA,,,Comunitat Valenciana,6
10,CCAA,,,Extremadura,6
11,CCAA,,,Galicia,6
12,CCAA,,,Madrid (Comunidad de),6
13,CCAA,,,Murcia (Región de),6
14,CCAA,,,Navarra (Comunidad Foral de),6
15,CCAA,,,País Vasco,6
16,CCAA,,,"Rioja, La",6
17,Sector,Actividades administrativas y servicios auxili...,,,6
18,Sector,"Actividades artísticas, recreativas y de entre...",,,6
19,Sector,"Actividades profesionales, científicas y técnicas",,,6
20,Sector,Comercio y reparación de vehículos,,,6
21,Sector,Construcción,,,6
22,Sector,Hostelería,,,6
23,Sector,Industria,,,6
24,Sector,"Información, comunicaciones, actividades finan...",,,6
25,Sector,Transporte y almacenamiento,,,6
26,Tamaño empresa,,De 10 a 49 trabajadores,,6
27,Tamaño empresa,,De 250 a 499 trabajadores,,6
28,Tamaño empresa,,De 5 a 9 trabajadores,,6
29,Tamaño empresa,,De 50 a 249 trabajadores,,6
30,Tamaño empresa,,Más de 499 trabajadores,,6
31,Total empresas,,,,6

df_eal17_largo completo:

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,TOTAL,100.000,Total empresas,,,
1,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,73.468,Total empresas,,,
2,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),60.220,Total empresas,,,
3,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),25.366,Total empresas,,,
4,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),14.415,Total empresas,,,
5,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,26.532,Total empresas,,,
6,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,TOTAL,100.000,Tamaño empresa,,De 5 a 9 trabajadores,
7,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,65.319,Tamaño empresa,,De 5 a 9 trabajadores,
8,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),51.321,Tamaño empresa,,De 5 a 9 trabajadores,
9,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),28.014,Tamaño empresa,,De 5 a 9 trabajadores,
10,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),20.665,Tamaño empresa,,De 5 a 9 trabajadores,
11,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,34.681,Tamaño empresa,,De 5 a 9 trabajadores,
12,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,TOTAL,100.000,Tamaño empresa,,De 10 a 49 trabajadores,
13,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,79.228,Tamaño empresa,,De 10 a 49 trabajadores,
14,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),64.481,Tamaño empresa,,De 10 a 49 trabajadores,
15,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),25.163,Tamaño empresa,,De 10 a 49 trabajadores,
16,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),10.356,Tamaño empresa,,De 10 a 49 trabajadores,
17,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,20.772,Tamaño empresa,,De 10 a 49 trabajadores,
18,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,TOTAL,100.000,Tamaño empresa,,De 50 a 249 trabajadores,
19,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,94.759,Tamaño empresa,,De 50 a 249 trabajadores,
20,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),79.559,Tamaño empresa,,De 50 a 249 trabajadores,
21,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),15.091,Tamaño empresa,,De 50 a 249 trabajadores,
22,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),5.349,Tamaño empresa,,De 50 a 249 trabajadores,
23,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,5.241,Tamaño empresa,,De 50 a 249 trabajadores,
24,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,TOTAL,100.000,Tamaño empresa,,De 250 a 499 trabajadores,
25,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,98.371,Tamaño empresa,,De 250 a 499 trabajadores,
26,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),85.856,Tamaño empresa,,De 250 a 499 trabajadores,
27,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),11.710,Tamaño empresa,,De 250 a 499 trabajadores,
28,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),2.434,Tamaño empresa,,De 250 a 499 trabajadores,
29,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,1.629,Tamaño empresa,,De 250 a 499 trabajadores,
30,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,TOTAL,100.000,Tamaño empresa,,Más de 499 trabajadores,
31,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,99.298,Tamaño empresa,,Más de 499 trabajadores,
32,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),88.305,Tamaño empresa,,Más de 499 trabajadores,
33,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),9.742,Tamaño empresa,,Más de 499 trabajadores,
34,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),1.953,Tamaño empresa,,Más de 499 trabajadores,
35,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,0.702,Tamaño empresa,,Más de 499 trabajadores,
36,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,TOTAL,100.000,Sector,Industria,,
37,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,76.222,Sector,Industria,,
38,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),64.223,Sector,Industria,,
39,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),20.911,Sector,Industria,,
40,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),14.866,Sector,Industria,,
41,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,23.778,Sector,Industria,,
42,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,TOTAL,100.000,Sector,Construcción,,
43,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,77.713,Sector,Construcción,,
44,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),61.593,Sector,Construcción,,
45,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),29.467,Sector,Construcción,,
46,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),8.940,Sector,Construcción,,
47,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,22.287,Sector,Construcción,,
48,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,TOTAL,100.000,Sector,Comercio y reparación de vehículos,,
49,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,73.959,Sector,Comercio y reparación de vehículos,,
50,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),62.349,Sector,Comercio y reparación de vehículos,,
51,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),23.788,Sector,Comercio y reparación de vehículos,,
52,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),13.863,Sector,Comercio y reparación de vehículos,,
53,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,26.041,Sector,Comercio y reparación de vehículos,,
54,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,TOTAL,100.000,Sector,Transporte y almacenamiento,,
55,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,77.405,Sector,Transporte y almacenamiento,,
56,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),55.376,Sector,Transporte y almacenamiento,,
57,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),34.796,Sector,Transporte y almacenamiento,,
58,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),9.828,Sector,Transporte y almacenamiento,,
59,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,22.595,Sector,Transporte y almacenamiento,,
60,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,TOTAL,100.000,Sector,Hostelería,,
61,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,60.735,Sector,Hostelería,,
62,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),42.630,Sector,Hostelería,,
63,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),36.362,Sector,Hostelería,,
64,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),21.008,Sector,Hostelería,,
65,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,39.265,Sector,Hostelería,,
66,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",TOTAL,100.000,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
67,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,80.544,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
68,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),73.696,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
69,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),13.463,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
70,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),12.840,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
71,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,19.456,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
72,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Actividades profesionales, científicas y técnicas",TOTAL,100.000,Sector,"Actividades profesionales, científicas y técnicas",,
73,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Actividades profesionales, científicas y técnicas",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,81.788,Sector,"Actividades profesionales, científicas y técnicas",,
74,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Actividades profesionales, científicas y técnicas",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),66.118,Sector,"Actividades profesionales, científicas y técnicas",,
75,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Actividades profesionales, científicas y técnicas",EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),18.706,Sector,"Actividades profesionales, científicas y técnicas",,

Resumen EAL-18 para revisar contra el Excel raw:

,Ámbito,Sector,Tamaño Empresa,CCAA,n_registros
0,CCAA,,,Andalucía,6
1,CCAA,,,Aragón,6
2,CCAA,,,Asturias (Principado de),6
3,CCAA,,,Balears (Illes),6
4,CCAA,,,Canarias,6
5,CCAA,,,Cantabria,6
6,CCAA,,,Castilla y León,6
7,CCAA,,,Castilla-La Mancha,6
8,CCAA,,,Cataluña,6
9,CCAA,,,Comunitat Valenciana,6
10,CCAA,,,Extremadura,6
11,CCAA,,,Galicia,6
12,CCAA,,,Madrid (Comunidad de),6
13,CCAA,,,Murcia (Región de),6
14,CCAA,,,Navarra (Comunidad Foral de),6
15,CCAA,,,País Vasco,6
16,CCAA,,,"Rioja, La",6
17,Sector,Actividades administrativas y servicios auxili...,,,6
18,Sector,"Actividades artísticas, recreativas y de entre...",,,6
19,Sector,"Actividades profesionales, científicas y técnicas",,,6
20,Sector,Comercio y reparación de vehículos,,,6
21,Sector,Construcción,,,6
22,Sector,Hostelería,,,6
23,Sector,Industria,,,6
24,Sector,"Información, comunicaciones, actividades finan...",,,6
25,Sector,Transporte y almacenamiento,,,6
26,Tamaño empresa,,De 10 a 49 trabajadores,,6
27,Tamaño empresa,,De 250 a 499 trabajadores,,6
28,Tamaño empresa,,De 5 a 9 trabajadores,,6
29,Tamaño empresa,,De 50 a 249 trabajadores,,6
30,Tamaño empresa,,Más de 499 trabajadores,,6
31,Total empresas,,,,6

df_eal18_largo completo:

,Año,Hoja,Título de tabla,Categoría,Variable,Valor,Ámbito,Sector,Tamaño Empresa,CCAA
0,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,29.123694,Total empresas,,,
1,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),89.974511,Total empresas,,,
2,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),10.025489,Total empresas,,,
3,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,70.876306,Total empresas,,,
4,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),66.570590,Total empresas,,,
5,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),33.429410,Total empresas,,,
6,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,23.671862,Tamaño empresa,,De 5 a 9 trabajadores,
7,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),83.544726,Tamaño empresa,,De 5 a 9 trabajadores,
8,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),16.455274,Tamaño empresa,,De 5 a 9 trabajadores,
9,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,76.328138,Tamaño empresa,,De 5 a 9 trabajadores,
10,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),59.481181,Tamaño empresa,,De 5 a 9 trabajadores,
11,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),40.518819,Tamaño empresa,,De 5 a 9 trabajadores,
12,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,31.724690,Tamaño empresa,,De 10 a 49 trabajadores,
13,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),93.100741,Tamaño empresa,,De 10 a 49 trabajadores,
14,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),6.899259,Tamaño empresa,,De 10 a 49 trabajadores,
15,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,68.275310,Tamaño empresa,,De 10 a 49 trabajadores,
16,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),72.749236,Tamaño empresa,,De 10 a 49 trabajadores,
17,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),27.250764,Tamaño empresa,,De 10 a 49 trabajadores,
18,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,48.701094,Tamaño empresa,,De 50 a 249 trabajadores,
19,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),98.742720,Tamaño empresa,,De 50 a 249 trabajadores,
20,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),1.266525,Tamaño empresa,,De 50 a 249 trabajadores,
21,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,51.298906,Tamaño empresa,,De 50 a 249 trabajadores,
22,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),90.863612,Tamaño empresa,,De 50 a 249 trabajadores,
23,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),9.136388,Tamaño empresa,,De 50 a 249 trabajadores,
24,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,58.708189,Tamaño empresa,,De 250 a 499 trabajadores,
25,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),100.000000,Tamaño empresa,,De 250 a 499 trabajadores,
26,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),0.000000,Tamaño empresa,,De 250 a 499 trabajadores,
27,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,41.253364,Tamaño empresa,,De 250 a 499 trabajadores,
28,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),96.831314,Tamaño empresa,,De 250 a 499 trabajadores,
29,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),3.168686,Tamaño empresa,,De 250 a 499 trabajadores,
30,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,62.753623,Tamaño empresa,,Más de 499 trabajadores,
31,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),99.769053,Tamaño empresa,,Más de 499 trabajadores,
32,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),0.230947,Tamaño empresa,,Más de 499 trabajadores,
33,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,37.246377,Tamaño empresa,,Más de 499 trabajadores,
34,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),98.702983,Tamaño empresa,,Más de 499 trabajadores,
35,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),1.297017,Tamaño empresa,,Más de 499 trabajadores,
36,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,29.340514,Sector,Industria,,
37,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),91.943067,Sector,Industria,,
38,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),8.063373,Sector,Industria,,
39,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,70.659486,Sector,Industria,,
40,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),69.761720,Sector,Industria,,
41,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),30.238280,Sector,Industria,,
42,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,27.053957,Sector,Construcción,,
43,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),90.611641,Sector,Construcción,,
44,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),9.388359,Sector,Construcción,,
45,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,72.946043,Sector,Construcción,,
46,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),73.016647,Sector,Construcción,,
47,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),26.983353,Sector,Construcción,,
48,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,28.467349,Sector,Comercio y reparación de vehículos,,
49,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),90.868950,Sector,Comercio y reparación de vehículos,,
50,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),9.131050,Sector,Comercio y reparación de vehículos,,
51,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,71.532651,Sector,Comercio y reparación de vehículos,,
52,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),67.384332,Sector,Comercio y reparación de vehículos,,
53,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),32.615668,Sector,Comercio y reparación de vehículos,,
54,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,25.901905,Sector,Transporte y almacenamiento,,
55,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),95.031299,Sector,Transporte y almacenamiento,,
56,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),4.968701,Sector,Transporte y almacenamiento,,
57,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,74.098095,Sector,Transporte y almacenamiento,,
58,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),71.218545,Sector,Transporte y almacenamiento,,
59,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),28.781455,Sector,Transporte y almacenamiento,,
60,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,30.271329,Sector,Hostelería,,
61,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),82.452506,Sector,Hostelería,,
62,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),17.547494,Sector,Hostelería,,
63,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,69.728671,Sector,Hostelería,,
64,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),51.019961,Sector,Hostelería,,
65,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2),48.980039,Sector,Hostelería,,
66,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,32.924543,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
67,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),94.811321,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
68,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),5.188679,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,
69,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,67.075457,Sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",,