# Librerías

In [1]:
import pandas as pd
import numpy as np
import re
import pathlib as Path
import unicodedata

# Documents

Extraer los datos de los últimos 5 años (2020 - 2024):
Hojas de formación en las empresas, contexto y errores muestreo
Extraemos todos los datos respecto a formación en las empresas pero después analizaremos solo (en el caso de algunas tablas de formación cogeremos ya las específicas de servicios [e.g. 2024 EAL-23 y 23c]):
CCAA: Total y Cataluña y otras CCAA donde tenemos sede (Madrid, Valencia, Sevilla y Bilbao)
Tamaño empresa: más de 499
Sector Transporte y almacenamiento y cuando agregado servicios

TABLAS CONTEXTO
2020, 2021, 2022, 2023, 2024:
EAL-C1, EAL-C2, EAL-C3

TABLAS FORMACIÓN EMPRESAS
2020, 2021, 2022:
EAL-16, EAL-17, EAL-18, EAL-19, EAL-20, EAL-21, EAL-22, EAL-24, EAL-25

2023, 2024 añadido:
EAL-18a, EAL-18b, EAL-18c

ERRORES MUESTREO
2020, 2021, 2022, 2023, 2024:
EAL-M1

He hagut de fer: pip install openpyxl (és l'engine de pandas per excel més nous)

In [2]:

from pathlib import Path


def encontrar_raiz_repo(inicio=None):
    ruta = Path(inicio or Path.cwd()).resolve()
    for candidata in [ruta, *ruta.parents]:
        if (candidata / "Equip_31").exists():
            return candidata
    raise FileNotFoundError("No se encontró la raíz del repositorio con Equip_31.")


REPO_ROOT = encontrar_raiz_repo()
INTERIM_DIR = REPO_ROOT / "Equip_31/Data/interim/EAL/2024"
ANIO = 2024

hojas_formacion_fede = [
    "EAL-16", "EAL-17", "EAL-18", "EAL-18a", "EAL-18b", "EAL-18c", "EAL-19", "EAL-20"
]

print("Raíz repo:", REPO_ROOT)
print("Carpeta interim:", INTERIM_DIR.relative_to(REPO_ROOT))
print("Carpeta existe:", INTERIM_DIR.exists())

faltantes = [hoja for hoja in hojas_formacion_fede if not (INTERIM_DIR / f"{hoja}.csv").exists()]
print("Archivos faltantes:", faltantes if faltantes else "ninguno")

Raíz repo: /Users/fedeur/ProjecteData
Carpeta interim: Equip_31/Data/interim/EAL/2024
Carpeta existe: True
Archivos faltantes: ninguno

In [3]:

# Vista rápida de los CSV disponibles en interim, sin crear archivos nuevos.
archivos_interim = sorted(INTERIM_DIR.glob("*.csv"))
for ruta in archivos_interim:
    print(ruta.name)

EAL-16.csv
EAL-17.csv
EAL-18.csv
EAL-18a.csv
EAL-18b.csv
EAL-18c.csv
EAL-19.csv
EAL-20.csv
EAL-21.csv
EAL-22.csv
EAL-23.csv
EAL-24.csv
EAL-25.csv
EAL-C1.csv
EAL-C2.csv
EAL-C3.csv
EAL-M1.csv

In [4]:

# Comprobación estructural mínima de los CSV ya existentes en interim.
resumen_interim = []
for ruta in archivos_interim:
    df_tmp = pd.read_csv(ruta, header=None, dtype=str, keep_default_na=False)
    resumen_interim.append({
        "archivo": ruta.name,
        "filas": df_tmp.shape[0],
        "columnas": df_tmp.shape[1],
    })

pd.DataFrame(resumen_interim)

        archivo  filas  columnas
0    EAL-16.csv     93         6
1    EAL-17.csv     42         7
2    EAL-18.csv     43         7
3   EAL-18a.csv     41         7
4   EAL-18b.csv     42         9
5   EAL-18c.csv     41         2
6    EAL-19.csv     11         5
7    EAL-20.csv     17         7
8    EAL-21.csv     17         5
9    EAL-22.csv     29        10
10   EAL-23.csv     65         6
11   EAL-24.csv     93         6
12   EAL-25.csv     80         6
13   EAL-C1.csv     43         7
14   EAL-C2.csv     44         8
15   EAL-C3.csv     43         4
16   EAL-M1.csv     40         4

## Normalización estructural de EAL-16 a EAL-20

A partir de aquí se leen los CSV ya extraídos en `Equip_31/Data/interim/EAL/2024`. La salida se alinea con el estilo de Sabina: columnas de metadatos en minúscula (`anio`, `tabla`, `pregunta`, `ambito`) y variables de respuesta en columnas limpias.

In [5]:

# ============================================================
# CONFIGURACIÓN
# ============================================================

import re
import unicodedata
import pandas as pd
from pathlib import Path

ANIO = 2024
INTERIM_DIR_REL = Path("Equip_31/Data/interim/EAL/2024")
INTERIM_DIR = REPO_ROOT / INTERIM_DIR_REL

print("Ruta relativa:", INTERIM_DIR_REL)
print("Carpeta existe:", INTERIM_DIR.exists())

if not INTERIM_DIR.exists():
    raise FileNotFoundError(f"No existe la carpeta interim esperada: {INTERIM_DIR}")

Ruta relativa: Equip_31/Data/interim/EAL/2024
Carpeta existe: True

## Funciones auxiliares

Estas funciones leen las hojas desde `interim`, limpian espacios y generan nombres de columnas homogéneos para que los dataframes queden comparables con los de Sabina.

In [6]:

# ============================================================
# FUNCIONES AUXILIARES
# ============================================================

def limpiar_texto(valor):
    if pd.isna(valor):
        return ""
    valor = str(valor).replace("\n", " ")
    valor = re.sub(r"\s+", " ", valor)
    return valor.strip()


def normalizar_columna(valor):
    valor = limpiar_texto(valor).upper()
    valor = re.sub(r"\s+", " ", valor)
    return valor


def leer_csv_eal(hoja):
    ruta = INTERIM_DIR / f"{hoja}.csv"
    if not ruta.exists():
        raise FileNotFoundError(f"No existe el CSV esperado: {ruta}")

    df = pd.read_csv(ruta, header=None, dtype=str, keep_default_na=False)
    df = df.map(limpiar_texto)
    df = df.replace("", pd.NA)
    df = df.dropna(how="all")
    df = df.dropna(axis=1, how="all")
    df = df.fillna("").reset_index(drop=True)
    return df


def extraer_tabla_pregunta(texto):
    texto = limpiar_texto(texto)
    match = re.match(r"^(EAL-\d+[A-Za-z]?)\.\s*(.*)$", texto)
    if not match:
        return "", texto
    return match.group(1), match.group(2).strip()


def detectar_titulo(df, hoja):
    for valor in df.iloc[:, 0].tolist():
        texto = limpiar_texto(valor)
        if texto.upper().startswith(f"{hoja.upper()}."):
            return texto
    return ""


def metadatos_base(anio, tabla, pregunta, ambito):
    return {
        "anio": anio,
        "tabla": tabla,
        "pregunta": pregunta,
        "ambito": ambito,
    }


def hacer_columnas_unicas(columnas):
    resultado = []
    contador = {}
    for columna in columnas:
        columna = normalizar_columna(columna) or "SIN_TITULO"
        if columna not in contador:
            contador[columna] = 1
            resultado.append(columna)
        else:
            contador[columna] += 1
            resultado.append(f"{columna}_{contador[columna]}")
    return resultado


def to_long_format(df, id_vars, value_vars, var_name, value_name="porcentaje"):
    df_long = df.melt(
        id_vars=id_vars,
        value_vars=value_vars,
        var_name=var_name,
        value_name=value_name,
    )
    return df_long.dropna(subset=[value_name]).reset_index(drop=True)

## Lectura del CSV original

Se muestra EAL-16 tal como quedó extraído en `interim`, para poder contrastarlo visualmente con el Excel raw cuando haga falta.

In [7]:

# ============================================================
# LECTURA DEL CSV ORIGINAL
# ============================================================

df_16_raw = leer_csv_eal("EAL-16")

print("Dimensión EAL-16 raw:", df_16_raw.shape)
display(df_16_raw.head(20))

Dimensión EAL-16 raw: (93, 6)

,0,1,2,3,4,5
0,ENCUESTA ANUAL LABORAL,,,,,EAL
1,,,,,,Volver al índice
2,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,,,,,
3,Año 2024. Porcentaje sobre el total de empresas.,,,,,
4,,TOTAL,NADA,POCO,BASTANTE,MUCHO
5,De dirección,100,10.414,18.818,40.283,30.484
6,De trabajo en equipo,100,2.224,5.822,45.125,46.829
7,De atención al público/ trato a clientes,100,5.128,13.392,37.144,44.336
8,Administrativas de oficina,100,11.117,25.313,37.788,25.782
9,De resolución de problemas (localización de pr...,100,5.893,15.752,44.063,34.292
10,En lenguas extranjeras,100,23.022,40.356,24.568,12.054
11,Básicas de cálculo y/o comunicación oral o esc...,100,22.688,36.513,29.697,11.102
12,Generales de tecnologías de la información,100,13.593,29.346,39.173,17.888
13,Profesionales de tecnologías de la información,100,26.908,37.656,24.493,10.944
14,"Competencias técnicas, prácticas y otras espec...",100,13.417,18.861,36.496,31.226
15,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,,,,,
16,Año 2024. Porcentaje respecto al total de empr...,,,,,
17,,TOTAL,NADA,POCO,BASTANTE,MUCHO
18,De dirección,100,11.075,19.589,39.991,29.345
19,De trabajo en equipo,100,2.321,5.976,45.426,46.277

## EAL-16 en formato ancho

Una fila por competencia y bloque de la hoja. Esta tabla queda con el mismo estilo base de Sabina: `anio`, `tabla`, `pregunta`, `ambito` y respuestas (`TOTAL`, `NADA`, `POCO`, `BASTANTE`, `MUCHO`).

In [8]:

# ============================================================
# EAL-16 A FORMATO ANCHO
# ============================================================

COLUMNAS_GRADO = ["TOTAL", "NADA", "POCO", "BASTANTE", "MUCHO"]

def fila_es_cabecera_grado(row):
    valores = [normalizar_columna(x) for x in row.tolist()]
    return set(COLUMNAS_GRADO).issubset(set(valores))


def process_eal16_wide(df, anio=2024):
    registros = []
    tabla_actual = None
    pregunta_actual = None
    columnas_actuales = None

    for _, row in df.iterrows():
        primera_celda = limpiar_texto(row.iloc[0])
        tabla_detectada, pregunta_detectada = extraer_tabla_pregunta(primera_celda)

        if re.match(r"^EAL-16[A-Za-z]?$", tabla_detectada):
            tabla_actual = tabla_detectada
            pregunta_actual = pregunta_detectada
            columnas_actuales = None
            continue

        if tabla_actual and fila_es_cabecera_grado(row):
            columnas_actuales = [normalizar_columna(x) for x in row.tolist()]
            continue

        if not (tabla_actual and columnas_actuales):
            continue

        ambito = primera_celda
        if ambito == "":
            continue

        registro = metadatos_base(anio, tabla_actual, pregunta_actual, ambito)
        for posicion, columna in enumerate(columnas_actuales):
            if columna in COLUMNAS_GRADO:
                registro[columna] = pd.to_numeric(limpiar_texto(row.iloc[posicion]), errors="coerce")
        registros.append(registro)

    columnas = ["anio", "tabla", "pregunta", "ambito", *COLUMNAS_GRADO]
    return pd.DataFrame(registros)[columnas]


df_16 = process_eal16_wide(df_16_raw, anio=ANIO)

print("df_16:", df_16.shape)
print("Esperado: 7 bloques x 10 categorías = 70 registros")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_16)

df_16: (70, 9)
Esperado: 7 bloques x 10 categorías = 70 registros

,anio,tabla,pregunta,ambito,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,De dirección,100,10.414,18.818,40.283,30.484
1,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,De trabajo en equipo,100,2.224,5.822,45.125,46.829
2,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,De atención al público/ trato a clientes,100,5.128,13.392,37.144,44.336
3,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,Administrativas de oficina,100,11.117,25.313,37.788,25.782
4,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,5.893,15.752,44.063,34.292
5,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,En lenguas extranjeras,100,23.022,40.356,24.568,12.054
6,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,Básicas de cálculo y/o comunicación oral o escrita,100,22.688,36.513,29.697,11.102
7,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,Generales de tecnologías de la información,100,13.593,29.346,39.173,17.888
8,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,Profesionales de tecnologías de la información,100,26.908,37.656,24.493,10.944
9,2024,EAL-16,EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPETENCIAS,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,13.417,18.861,36.496,31.226
10,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,De dirección,100,11.075,19.589,39.991,29.345
11,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,De trabajo en equipo,100,2.321,5.976,45.426,46.277
12,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,De atención al público/ trato a clientes,100,5.200,13.151,36.884,44.764
13,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,Administrativas de oficina,100,11.815,25.651,36.989,25.545
14,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,6.161,16.142,43.592,34.104
15,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,En lenguas extranjeras,100,23.741,40.753,23.986,11.519
16,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,Básicas de cálculo y/o comunicación oral o escrita,100,23.741,36.767,28.759,10.733
17,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,Generales de tecnologías de la información,100,14.343,30.144,38.530,16.983
18,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,Profesionales de tecnologías de la información,100,28.160,38.095,23.711,10.034
19,2024,EAL-16a,EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE ...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,13.890,19.160,36.312,30.638
20,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,De dirección,100,2.498,9.573,43.903,44.026
21,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,De trabajo en equipo,100,1.103,4.062,41.538,53.297
22,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,De atención al público/ trato a clientes,100,4.355,16.362,40.501,38.782
23,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Administrativas de oficina,100,2.678,21.162,47.295,28.866
24,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,2.760,10.937,49.810,36.493
25,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,En lenguas extranjeras,100,14.822,35.718,31.244,18.217
26,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Básicas de cálculo y/o comunicación oral o escrita,100,10.332,33.790,40.670,15.208
27,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Generales de tecnologías de la información,100,4.697,20.101,46.860,28.343
28,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Profesionales de tecnologías de la información,100,12.160,32.897,33.533,21.409
29,2024,EAL-16b,EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,7.808,15.121,38.807,38.263
30,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,De dirección,100,1.219,8.240,42.912,47.628
31,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,De trabajo en equipo,100,0.350,2.647,40.670,56.333
32,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,De atención al público/ trato a clientes,100,2.959,15.763,37.806,43.472
33,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,Administrativas de oficina,100,2.211,21.871,49.752,26.166
34,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,1.237,11.915,49.421,37.427
35,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,En lenguas extranjeras,100,8.034,33.434,36.148,22.384
36,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,Básicas de cálculo y/o comunicación oral o escrita,100,4.952,29.125,45.866,20.057
37,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,Generales de tecnologías de la información,100,2.056,14.576,48.346,35.022
38,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,Profesionales de tecnologías de la información,100,6.458,25.460,39.324,28.758
39,2024,EAL-16c,EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,6.080,16.604,37.880,39.435
40,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,De dirección,100,8.197,17.305,41.698,32.801
41,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,De trabajo en equipo,100,2.753,6.778,50.076,40.393
42,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,De atención al público/ trato a clientes,100,7.136,19.834,42.025,31.005
43,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,Administrativas de oficina,100,7.854,20.558,45.127,26.460
44,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,5.355,13.448,46.745,34.453
45,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,En lenguas extranjeras,100,26.050,40.489,23.916,9.544
46,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,Básicas de cálculo y/o comunicación oral o escrita,100,19.333,38.621,32.408,9.638
47,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,Generales de tecnologías de la información,100,10.605,27.884,44.776,16.735
48,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,Profesionales de tecnologías de la información,100,20.694,40.976,27.740,10.590
49,2024,EAL-16d,EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSA...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,5.024,11.106,43.003,40.867
50,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,De dirección,100,9.038,19.132,42.284,29.546
51,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,De trabajo en equipo,100,1.799,5.505,48.771,43.926
52,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,De atención al público/ trato a clientes,100,10.004,27.124,38.024,24.848
53,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,Administrativas de oficina,100,10.250,22.411,38.818,28.520
54,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,4.291,12.994,43.967,38.748
55,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,En lenguas extranjeras,100,37.183,45.380,13.307,4.130
56,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,Básicas de cálculo y/o comunicación oral o escrita,100,24.034,40.470,28.081,7.415
57,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,Generales de tecnologías de la información,100,15.576,33.079,38.295,13.050
58,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,Profesionales de tecnologías de la información,100,28.493,42.797,22.826,5.884
59,2024,EAL-16e,EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVE...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,6.518,9.411,40.560,43.510
60,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,De dirección,100,11.117,19.077,39.637,30.169
61,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,De trabajo en equipo,100,2.189,5.680,43.455,48.677
62,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,De atención al público/ trato a clientes,100,3.851,9.635,35.976,50.538
63,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,Administrativas de oficina,100,11.946,26.811,36.084,25.159
64,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,6.288,16.716,43.524,33.473
65,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,En lenguas extranjeras,100,19.897,39.443,26.688,13.971
66,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,Básicas de cálculo y/o comunicación oral o escrita,100,23.147,35.378,29.419,12.056
67,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,Generales de tecnologías de la información,100,13.863,28.992,38.165,18.980
68,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,Profesionales de tecnologías de la información,100,27.918,36.061,24.113,11.909
69,2024,EAL-16f,EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DI...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,16.375,22.136,34.430,27.059

## EAL-17 y EAL-18 en formato ancho

Estas hojas tienen cabeceras agrupadas. Se conservan en ancho para que la lectura sea directa y se usan los mismos metadatos base: `anio`, `tabla`, `pregunta`, `ambito`.

In [9]:

# ============================================================
# FUNCIONES PARA EAL-17 Y EAL-18 EN FORMATO ANCHO
# ============================================================

SECCIONES_FILA = {
    "TAMAÑO DE LA EMPRESA": "tamano_empresa",
    "ACTIVIDAD ECONÓMICA": "sector",
    "COMUNIDAD AUTÓNOMA": "ccaa",
}


def nombre_ambito(categoria, seccion_actual):
    if categoria.upper() == "TOTAL":
        return "total_empresas"
    return seccion_actual or "total_empresas"


def columnas_agrupadas(df, fila_grupo, fila_subgrupo, primera_columna_valor=1):
    grupo_superior = [limpiar_texto(x) for x in df.iloc[fila_grupo].tolist()]
    subvariable = [limpiar_texto(x) for x in df.iloc[fila_subgrupo].tolist()]

    columnas = {}
    grupo_actual = ""
    for col in range(primera_columna_valor, df.shape[1]):
        if grupo_superior[col]:
            grupo_actual = grupo_superior[col]
        sub = subvariable[col]

        if col == primera_columna_valor and not sub:
            nombre = "TOTAL"
        elif grupo_actual and sub:
            nombre = f"{grupo_actual} - {sub}"
        else:
            nombre = grupo_actual or sub or "TOTAL"

        columnas[col] = normalizar_columna(nombre)
    return columnas


def process_eal17_18_wide(hoja, anio=2024):
    df = leer_csv_eal(hoja)
    titulo = detectar_titulo(df, hoja)
    tabla, pregunta = extraer_tabla_pregunta(titulo)
    columnas_valor = columnas_agrupadas(df, fila_grupo=4, fila_subgrupo=5)

    registros = []
    seccion_actual = None
    for _, row in df.iloc[6:].iterrows():
        categoria = limpiar_texto(row.iloc[0])
        if categoria == "" or categoria.startswith("("):
            continue

        categoria_norm = categoria.upper()
        if categoria_norm in SECCIONES_FILA:
            seccion_actual = SECCIONES_FILA[categoria_norm]
            continue

        registro = metadatos_base(anio, tabla, pregunta, nombre_ambito(categoria, seccion_actual))
        registro["categoria"] = categoria

        for col, nombre_columna in columnas_valor.items():
            valor = limpiar_texto(row.iloc[col]) if col < len(row) else ""
            registro[nombre_columna] = pd.to_numeric(valor, errors="coerce")

        registros.append(registro)

    columnas_base = ["anio", "tabla", "pregunta", "ambito", "categoria"]
    columnas_valores = [nombre for _, nombre in sorted(columnas_valor.items())]
    return pd.DataFrame(registros)[columnas_base + columnas_valores]

## EAL-17 en formato ancho

In [10]:

# ============================================================
# EAL-17 A FORMATO ANCHO
# ============================================================

df_17 = process_eal17_18_wide("EAL-17", anio=ANIO)

print("df_17:", df_17.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_17)

df_17: (32, 11)

,anio,tabla,pregunta,ambito,categoria,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - IMPARTICIÓN DE CURSOS Y OTROS TIPOS DE FORMACIÓN (1),EMPRESAS QUE PROPORCIONAN FORMACIÓN - SÓLO IMPARTICIÓN DE CURSOS (1),EMPRESAS QUE PROPORCIONAN FORMACIÓN - SÓLO OTROS TIPOS DE FORMACIÓN (1),EMPRESAS QUE NO PROPORCIONAN FORMACIÓN
0,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",total_empresas,TOTAL,100,73.468,60.220,25.366,14.415,26.532
1,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 5 a 9 trabajadores,100,65.319,51.321,28.014,20.665,34.681
2,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 10 a 49 trabajadores,100,79.228,64.481,25.163,10.356,20.772
3,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 50 a 249 trabajadores,100,94.759,79.559,15.091,5.349,5.241
4,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 250 a 499 trabajadores,100,98.371,85.856,11.710,2.434,1.629
5,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,Más de 499 trabajadores,100,99.298,88.305,9.742,1.953,0.702
6,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Industria,100,76.222,64.223,20.911,14.866,23.778
7,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Construcción,100,77.713,61.593,29.467,8.940,22.287
8,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Comercio y reparación de vehículos,100,73.959,62.349,23.788,13.863,26.041
9,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Transporte y almacenamiento,100,77.405,55.376,34.796,9.828,22.595
10,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Hostelería,100,60.735,42.630,36.362,21.008,39.265
11,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",100,80.544,73.696,13.463,12.840,19.456
12,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades profesionales, científicas y técnicas",100,81.788,66.118,18.706,15.177,18.212
13,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Actividades administrativas y servicios auxiliares,100,74.261,64.392,22.657,12.951,25.739
14,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",100,73.509,62.515,20.437,17.047,26.491
15,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Andalucía,100,73.324,53.315,31.577,15.109,26.676
16,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Aragón,100,73.588,62.546,23.485,13.969,26.412
17,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Asturias (Principado de),100,73.020,55.700,31.219,13.081,26.980
18,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Balears (Illes),100,61.539,61.355,24.875,13.770,38.461
19,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Canarias,100,69.622,58.685,25.936,15.379,30.378
20,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Cantabria,100,71.587,63.019,27.056,9.925,28.413
21,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Castilla-La Mancha,100,73.928,58.307,24.862,16.831,26.072
22,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Castilla y León,100,70.568,55.103,29.104,15.794,29.432
23,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Cataluña,100,76.296,65.436,20.504,14.060,23.704
24,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Comunitat Valenciana,100,74.320,58.492,27.612,13.896,25.680
25,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Extremadura,100,75.343,60.458,25.756,13.786,24.657
26,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Galicia,100,75.145,62.840,21.214,15.946,24.855
27,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Madrid (Comunidad de),100,72.991,62.348,22.853,14.799,27.009
28,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Murcia (Región de),100,76.934,57.263,30.705,12.032,23.066
29,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Navarra (Comunidad Foral de),100,78.843,62.267,22.001,15.732,21.157
30,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,País Vasco,100,71.171,64.009,24.950,11.042,28.829
31,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,"Rioja, La",100,70.224,62.081,21.054,16.865,29.776

## EAL-18 en formato ancho

In [11]:

# ============================================================
# EAL-18 A FORMATO ANCHO
# ============================================================

df_18 = process_eal17_18_wide("EAL-18", anio=ANIO)

print("df_18:", df_18.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_18)

df_18: (32, 11)

,anio,tabla,pregunta,ambito,categoria,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - PROPORCIONARON FORMACIÓN (1),DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - NO PROPORCIONARON FORMACIÓN (1),NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - PROPORCIONARON FORMACIÓN (2),NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - NO PROPORCIONARON FORMACIÓN (2)
0,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,total_empresas,TOTAL,29.123694,89.974511,10.025489,70.876306,66.570590,33.429410
1,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 5 a 9 trabajadores,23.671862,83.544726,16.455274,76.328138,59.481181,40.518819
2,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 10 a 49 trabajadores,31.724690,93.100741,6.899259,68.275310,72.749236,27.250764
3,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 50 a 249 trabajadores,48.701094,98.742720,1.266525,51.298906,90.863612,9.136388
4,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 250 a 499 trabajadores,58.708189,100.000000,0.000000,41.253364,96.831314,3.168686
5,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,Más de 499 trabajadores,62.753623,99.769053,0.230947,37.246377,98.702983,1.297017
6,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Industria,29.340514,91.943067,8.063373,70.659486,69.761720,30.238280
7,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Construcción,27.053957,90.611641,9.388359,72.946043,73.016647,26.983353
8,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Comercio y reparación de vehículos,28.467349,90.868950,9.131050,71.532651,67.384332,32.615668
9,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Transporte y almacenamiento,25.901905,95.031299,4.968701,74.098095,71.218545,28.781455
10,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Hostelería,30.271329,82.452506,17.547494,69.728671,51.019961,48.980039
11,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",32.924543,94.811321,5.188679,67.075457,74.219561,25.780439
12,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,"Actividades profesionales, científicas y técnicas",33.656148,91.928009,8.071991,66.343852,75.578153,24.421847
13,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Actividades administrativas y servicios auxiliares,28.286468,93.127579,6.872421,71.713532,65.673438,34.326562
14,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",26.601052,89.684569,10.315431,73.398948,67.478218,32.521782
15,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Andalucía,27.268815,88.163346,11.836654,72.731185,67.635602,32.361933
16,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Aragón,29.243477,87.909060,12.090940,70.756523,67.639522,32.346241
17,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Asturias (Principado de),28.940731,88.071895,11.982571,71.059269,66.637090,33.362910
18,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Balears (Illes),24.984561,85.487288,14.512712,75.015439,53.828061,46.183700
19,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Canarias,32.171083,82.749277,17.250723,67.828917,63.228239,36.771761
20,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Cantabria,20.682680,93.031785,6.968215,79.317320,66.050367,33.949633
21,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Castilla-La Mancha,23.509449,91.404199,8.595801,76.490551,68.831300,31.168700
22,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Castilla y León,31.137803,83.291405,16.729560,68.862197,65.039340,34.951180
23,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Cataluña,31.722109,90.311634,9.688366,68.277891,69.361787,30.638213
24,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Comunitat Valenciana,26.022668,94.221709,5.778291,73.977332,66.967668,33.035714
25,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Extremadura,23.936956,88.203018,11.796982,76.063044,71.012303,28.987697
26,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Galicia,26.402254,92.650020,7.349980,73.597746,68.438922,31.568302
27,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Madrid (Comunidad de),35.432441,91.263257,8.736743,64.567559,63.013225,36.986775
28,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Murcia (Región de),23.245159,92.822611,7.177389,76.754841,72.339227,27.672035
29,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Navarra (Comunidad Foral de),28.000841,96.171171,3.828829,71.999159,72.291971,27.678832
30,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,País Vasco,26.840242,92.489942,7.510058,73.159758,63.698237,36.301763
31,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,"Rioja, La",21.563236,92.349727,7.650273,78.436764,64.346520,35.653480

## EAL-18a, EAL-18b, EAL-18c, EAL-19 y EAL-20 en formato ancho

Estas hojas tienen una estructura más simple: una columna de categoría y varias columnas de valores. Se procesan con una función común.

In [12]:

# ============================================================
# FUNCIONES PARA FORMATO ANCHO SIMPLE
# ============================================================

MARCADORES_SECCION = {
    "TAMAÑO DE LA EMPRESA",
    "ACTIVIDAD ECONÓMICA",
    "COMUNIDAD AUTÓNOMA",
}


def process_hoja_ancha_simple(hoja, fila_cabecera, fila_inicio_datos, anio=2024):
    df = leer_csv_eal(hoja)
    titulo = detectar_titulo(df, hoja)
    tabla, pregunta = extraer_tabla_pregunta(titulo)
    columnas_valor = hacer_columnas_unicas(df.iloc[fila_cabecera, 1:].tolist())

    registros = []
    seccion_actual = None
    for _, row in df.iloc[fila_inicio_datos:].iterrows():
        categoria = limpiar_texto(row.iloc[0])
        if categoria == "" or categoria.startswith("("):
            continue

        categoria_norm = categoria.upper()
        if categoria_norm in SECCIONES_FILA:
            seccion_actual = SECCIONES_FILA[categoria_norm]
            continue
        if categoria_norm in MARCADORES_SECCION:
            continue

        registro = metadatos_base(anio, tabla, pregunta, nombre_ambito(categoria, seccion_actual))
        registro["categoria"] = categoria

        for offset, columna in enumerate(columnas_valor, start=1):
            valor = limpiar_texto(row.iloc[offset]) if offset < len(row) else ""
            registro[columna] = pd.to_numeric(valor, errors="coerce")

        if all(pd.isna(registro[col]) for col in columnas_valor):
            continue

        registros.append(registro)

    columnas_base = ["anio", "tabla", "pregunta", "ambito", "categoria"]
    return pd.DataFrame(registros)[columnas_base + columnas_valor]

## EAL-18a en formato ancho

In [13]:
# ============================================================
# EAL-18A EN FORMATO ANCHO
# ============================================================

df_18a = process_hoja_ancha_simple("EAL-18a", fila_cabecera=4, fila_inicio_datos=5, anio=ANIO)

print("df_18a:", df_18a.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_18a)

df_18a: (32, 11)

,anio,tabla,pregunta,ambito,categoria,TOTAL,CURSOS DE FORMACIÓN DISEÑADOS Y GESTIONADOS POR SU EMPRESA,CURSOS DE FORMACIÓN DISEÑADOS Y GESTIONADOS POR OTRA ORGANIZACIÓN,"FORMACIÓN PLANIFICADA EN EL PUESTO DE TRABAJO, UTILIZANDO LOS MEDIOS HABITUALES DE TRABAJO","APRENDIZAJE PLANIFICADO A PARTIR DE ROTACIÓN DE PUESTOS DE TRABAJO, INTERCAMBIOS, ETC.","PARTICIPACIÓN EN CONFERENCIAS, SEMINARIOS, GRUPOS DE TRABAJO, TALLERES O FERIAS DE MUESTRAS"
0,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",total_empresas,TOTAL,73.468278,34.269329,73.709969,56.005492,27.375278,35.086542
1,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 5 a 9 trabajadores,65.319423,27.217848,65.989117,51.141371,22.937813,32.188656
2,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 10 a 49 trabajadores,79.227905,35.028637,79.002872,57.331022,29.277350,33.998708
3,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 50 a 249 trabajadores,94.759353,58.777973,84.135506,70.508861,36.475507,51.399249
4,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 250 a 499 trabajadores,98.385236,76.162564,85.384916,76.865963,46.697929,57.796014
5,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,Más de 499 trabajadores,99.275362,85.450122,84.963504,80.048662,51.532847,65.596107
6,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Industria,76.222600,34.293577,76.121179,61.910901,36.081017,33.867169
7,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Construcción,77.712290,22.420652,84.768610,57.771672,21.273003,23.030251
8,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Comercio y reparación de vehículos,73.958727,38.680615,71.445779,54.400700,29.940268,41.624315
9,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Transporte y almacenamiento,77.406769,30.568829,79.668783,52.052104,24.258690,20.416312
10,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Hostelería,60.735371,25.970788,68.136490,54.371695,21.531100,13.127676
11,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",80.544101,48.577128,73.397606,52.972074,31.788564,63.623670
12,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,"Actividades profesionales, científicas y técnicas",81.788176,42.449776,68.304581,51.031088,25.282718,59.222138
13,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Actividades administrativas y servicios auxiliares,74.261496,36.374821,74.834256,60.200943,28.282414,39.518830
14,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",73.507801,40.519529,67.162337,57.172827,24.520269,43.228235
15,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Andalucía,73.324726,23.902570,76.823751,47.927417,26.162236,27.756719
16,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Aragón,73.587186,36.262834,73.538672,54.976044,25.530459,38.644764
17,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Asturias (Principado de),73.013871,32.340242,74.395509,57.966321,21.200345,32.102763
18,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Balears (Illes),61.535068,30.394265,72.688172,55.641577,23.412186,36.071685
19,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Canarias,69.624593,29.797179,71.321259,59.961606,24.021367,28.428345
20,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Cantabria,71.580278,36.700812,78.205581,53.973861,27.446132,31.755563
21,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Castilla-La Mancha,73.929811,29.233177,76.306729,55.336463,27.470005,36.765780
22,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Castilla y León,70.565964,35.078631,70.767808,50.712303,26.938020,36.956522
23,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Cataluña,76.295600,37.301272,75.365660,58.316773,30.781002,41.250000
24,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Comunitat Valenciana,74.320098,38.074398,71.119340,55.536105,26.032654,32.280761
25,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Extremadura,75.340667,32.381783,69.078231,58.008281,33.994334,33.558509
26,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Galicia,75.144877,26.729871,74.479977,62.975803,27.126079,34.491298
27,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Madrid (Comunidad de),72.991275,41.842742,71.675800,58.771505,26.178157,38.468204
28,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Murcia (Región de),76.936376,28.460674,77.696629,53.696629,26.651685,30.617978
29,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Navarra (Comunidad Foral de),78.852218,35.643828,74.193548,59.877366,29.085577,36.736870
30,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,País Vasco,71.174036,44.731962,69.774107,58.917734,31.507080,36.791976
31,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,"Rioja, La",70.227808,37.863535,70.357942,59.451902,28.859060,36.744966

## EAL-18b en formato ancho

In [14]:
# ============================================================
# EAL-18B EN FORMATO ANCHO
# ============================================================

df_18b = process_hoja_ancha_simple("EAL-18b", fila_cabecera=5, fila_inicio_datos=7, anio=ANIO)

print("df_18b:", df_18b.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_18b)

df_18b: (31, 13)

,anio,tabla,pregunta,ambito,categoria,EMPRESAS QUE REALIZARON SUSPENSIÓN DE CONTRATO/REDUCCIÓN DE JORNADA,TOTAL,EL 0'%,MÁS DEL 0% HASTA EL 25%,MÁS DEL 25% HASTA EL 50%,MÁS DEL 50% HASTA EL 75%,MÁS DEL 75% HASTA EL 100%,EL 100%
0,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 5 a 9 trabajadores,0.763845,100,85.635,9.391,1.418,2.351,0.000,1.206
1,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 10 a 49 trabajadores,1.563983,100,82.378,13.232,0.000,2.052,0.312,2.025
2,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 50 a 249 trabajadores,3.367701,100,64.167,23.950,4.927,1.052,1.926,3.978
3,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 250 a 499 trabajadores,9.919262,100,69.215,19.402,4.646,0.000,3.834,2.904
4,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,Más de 499 trabajadores,11.787440,100,66.136,26.049,5.791,1.364,0.325,0.334
5,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Industria,3.526077,100,79.042,12.156,0.385,1.863,0.546,6.008
6,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Construcción,0.131222,100,84.067,8.563,0.058,5.920,1.391,0.000
7,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Comercio y reparación de vehículos,0.230648,100,85.276,11.029,1.964,0.000,0.000,1.732
8,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Transporte y almacenamiento,0.851236,100,82.853,16.628,0.328,0.000,0.191,0.000
9,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Hostelería,2.805053,100,86.534,13.319,0.128,0.019,0.000,0.000
10,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",1.178172,100,73.417,25.752,0.716,0.116,0.000,0.000
11,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,"Actividades profesionales, científicas y técnicas",0.340950,100,66.559,29.363,2.090,0.000,1.988,0.000
12,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Actividades administrativas y servicios auxiliares,1.405949,100,85.590,9.907,3.315,0.094,1.094,0.000
13,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",1.002358,100,68.871,6.066,6.637,12.714,0.063,5.650
14,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Andalucía,1.949181,100,86.189,8.659,2.918,0.933,0.000,1.301
15,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Aragón,1.057721,100,94.925,3.531,1.291,0.000,0.253,0.000
16,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Asturias (Principado de),0.772383,100,83.657,7.451,0.000,0.000,8.892,0.000
17,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Balears (Illes),0.035289,100,73.093,26.907,0.000,0.000,0.000,0.000
18,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Canarias,0.331241,100,77.763,22.237,0.000,0.000,0.000,0.000
19,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Cantabria,1.112516,100,78.692,11.272,0.629,9.408,0.000,0.000
20,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Castilla-La Mancha,0.462784,100,98.346,1.416,0.239,0.000,0.000,0.000
21,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Castilla y León,1.103205,100,95.891,3.299,0.000,0.000,0.000,0.810
22,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Cataluña,1.726961,100,69.010,18.953,0.327,8.934,0.399,2.377
23,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Comunitat Valenciana,3.052366,100,79.585,19.840,0.112,0.463,0.000,0.000
24,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Extremadura,1.231325,100,80.051,6.802,0.899,0.000,1.798,10.450
25,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Galicia,0.818757,100,88.408,10.332,0.420,0.000,0.840,0.000
26,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Madrid (Comunidad de),0.416721,100,81.248,12.697,3.062,0.160,1.051,1.782
27,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Murcia (Región de),0.458160,100,93.809,6.046,0.145,0.000,0.000,0.000
28,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Navarra (Comunidad Foral de),5.339500,100,77.908,4.953,0.000,7.804,0.000,9.335
29,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,País Vasco,1.235827,100,66.394,19.083,0.000,0.000,0.000,14.523
30,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,"Rioja, La",1.099764,100,76.991,11.669,7.139,1.476,2.725,0.000

## EAL-18c en formato ancho

In [15]:
# ============================================================
# EAL-18C EN FORMATO ANCHO
# ============================================================

df_18c = process_hoja_ancha_simple("EAL-18c", fila_cabecera=4, fila_inicio_datos=6, anio=ANIO)

print("df_18c:", df_18c.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_18c)

df_18c: (31, 6)

,anio,tabla,pregunta,ambito,categoria,PORCENTAJE DE EMPRESAS QUE PROPORCIONARON FORMACIÓN EN SEGURIDAD Y SALUD LABORAL
0,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",tamano_empresa,De 5 a 9 trabajadores,68.611
1,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",tamano_empresa,De 10 a 49 trabajadores,81.343
2,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",tamano_empresa,De 50 a 249 trabajadores,92.156
3,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",tamano_empresa,De 250 a 499 trabajadores,95.577
4,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",tamano_empresa,Más de 499 trabajadores,96.501
5,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,Industria,81.214
6,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,Construcción,81.458
7,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,Comercio y reparación de vehículos,74.164
8,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,Transporte y almacenamiento,81.207
9,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,Hostelería,73.552
10,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",73.552
11,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,"Actividades profesionales, científicas y técnicas",69.610
12,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,Actividades administrativas y servicios auxiliares,75.604
13,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",69.206
14,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Andalucía,76.023
15,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Aragón,71.581
16,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Asturias (Principado de),71.816
17,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Balears (Illes),69.231
18,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Canarias,78.616
19,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Cantabria,70.111
20,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Castilla-La Mancha,80.034
21,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Castilla y León,68.388
22,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Cataluña,79.948
23,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Comunitat Valenciana,81.864
24,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Extremadura,72.441
25,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Galicia,73.287
26,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Madrid (Comunidad de),74.704
27,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Murcia (Región de),80.108
28,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,Navarra (Comunidad Foral de),67.513
29,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,País Vasco,62.846
30,2024,EAL-18c,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SOBRE SEGURIDAD, SALUD E HIGIENE EN EL TRABAJO POR TAMAÑO D...",ccaa,"Rioja, La",69.049

## EAL-19 en formato ancho

In [16]:
# ============================================================
# EAL-19 EN FORMATO ANCHO
# ============================================================

df_19 = process_hoja_ancha_simple("EAL-19", fila_cabecera=4, fila_inicio_datos=5, anio=ANIO)

print("df_19:", df_19.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_19)

df_19: (6, 9)

,anio,tabla,pregunta,ambito,categoria,TOTAL,INDUSTRIA,CONSTRUCCIÓN,SERVICIOS
0,2024,EAL-19,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,total_empresas,TOTAL,73.468278,76.222600,77.712290,72.148643
1,2024,EAL-19,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,total_empresas,De 5 a 9 trabajadores,65.319423,63.058146,71.260095,64.621839
2,2024,EAL-19,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,total_empresas,De 10 a 49 trabajadores,79.227905,80.668769,83.545151,78.058545
3,2024,EAL-19,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,total_empresas,De 50 a 249 trabajadores,94.759353,97.169168,95.046440,93.740024
4,2024,EAL-19,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,total_empresas,De 250 a 499 trabajadores,98.385236,99.467377,100.000000,97.818599
5,2024,EAL-19,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,total_empresas,Más de 499 trabajadores,99.275362,99.782609,98.717949,99.151436

## EAL-20 en formato ancho

In [17]:
# ============================================================
# EAL-20 EN FORMATO ANCHO
# ============================================================

df_20 = process_hoja_ancha_simple("EAL-20", fila_cabecera=4, fila_inicio_datos=5, anio=ANIO)

print("df_20:", df_20.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_20)

df_20: (11, 11)

,anio,tabla,pregunta,ambito,categoria,TOTAL,DE 5 A 9 TRABAJADORES,DE 10 A 49 TRABAJADORES,DE 50 A 249 TRABAJADORES,DE 250 A 499 TRABAJADORES,MÁS DE 499 TRABAJADORES
0,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,De dirección,16.347340,15.343619,15.804993,22.430750,25.322392,30.510949
1,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,De trabajo en equipo,28.494848,29.855895,26.931117,28.578895,34.153966,33.333333
2,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,De atención al público/ trato a clientes,24.530267,27.373940,22.586210,19.846059,21.570926,27.055961
3,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,Administrativas de oficina,17.027644,15.670464,18.738422,15.816981,12.817507,13.333333
4,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,Técnicas específicas del puesto de trabajo,50.838810,48.254094,52.131239,56.943983,55.763970,54.014599
5,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",11.209969,11.767293,10.401264,11.911436,15.787417,13.187348
6,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,En lenguas extranjeras,7.478712,3.941978,7.740614,21.100394,27.471669,27.639903
7,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,Generales de tecnologías de la información,12.666991,11.324888,12.758545,17.261367,21.492771,25.109489
8,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,Profesionales de tecnologías de la información,5.310919,3.812620,5.996873,8.690075,7.854631,12.749392
9,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,Básicas de cálculo y/o comunicación oral o escrita,1.254936,1.059013,1.173541,2.537179,2.110199,2.822384
10,2024,EAL-20,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS QUE SE H...,total_empresas,Otras,13.934268,12.640893,14.933123,15.664940,14.146151,11.776156

## Unión de hojas compatibles

Se unen solo las hojas con una estructura de filas similar (`EAL-17`, `EAL-18`, `EAL-18a`, `EAL-18b`, `EAL-18c`). `EAL-16`, `EAL-19` y `EAL-20` se mantienen separadas porque responden a otra lógica de tabla.

In [18]:

# ============================================================
# UNIR HOJAS COMPATIBLES EN FORMATO ANCHO
# ============================================================

hojas_compatibles_ancho = [df_17, df_18, df_18a, df_18b, df_18c]

df_compatibles_ancho = pd.concat(
    hojas_compatibles_ancho,
    ignore_index=True,
    sort=False,
)

print("df_compatibles_ancho:", df_compatibles_ancho.shape)
print("Tablas incluidas:", df_compatibles_ancho["tabla"].unique().tolist())

with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_compatibles_ancho)

df_compatibles_ancho: (158, 30)
Tablas incluidas: ['EAL-17', 'EAL-18', 'EAL-18a', 'EAL-18b', 'EAL-18c']

,anio,tabla,pregunta,ambito,categoria,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - IMPARTICIÓN DE CURSOS Y OTROS TIPOS DE FORMACIÓN (1),EMPRESAS QUE PROPORCIONAN FORMACIÓN - SÓLO IMPARTICIÓN DE CURSOS (1),EMPRESAS QUE PROPORCIONAN FORMACIÓN - SÓLO OTROS TIPOS DE FORMACIÓN (1),EMPRESAS QUE NO PROPORCIONAN FORMACIÓN,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - TOTAL,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - PROPORCIONARON FORMACIÓN (1),DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - NO PROPORCIONARON FORMACIÓN (1),NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - TOTAL,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - PROPORCIONARON FORMACIÓN (2),NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - NO PROPORCIONARON FORMACIÓN (2),CURSOS DE FORMACIÓN DISEÑADOS Y GESTIONADOS POR SU EMPRESA,CURSOS DE FORMACIÓN DISEÑADOS Y GESTIONADOS POR OTRA ORGANIZACIÓN,"FORMACIÓN PLANIFICADA EN EL PUESTO DE TRABAJO, UTILIZANDO LOS MEDIOS HABITUALES DE TRABAJO","APRENDIZAJE PLANIFICADO A PARTIR DE ROTACIÓN DE PUESTOS DE TRABAJO, INTERCAMBIOS, ETC.","PARTICIPACIÓN EN CONFERENCIAS, SEMINARIOS, GRUPOS DE TRABAJO, TALLERES O FERIAS DE MUESTRAS",EMPRESAS QUE REALIZARON SUSPENSIÓN DE CONTRATO/REDUCCIÓN DE JORNADA,EL 0'%,MÁS DEL 0% HASTA EL 25%,MÁS DEL 25% HASTA EL 50%,MÁS DEL 50% HASTA EL 75%,MÁS DEL 75% HASTA EL 100%,EL 100%,PORCENTAJE DE EMPRESAS QUE PROPORCIONARON FORMACIÓN EN SEGURIDAD Y SALUD LABORAL
0,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",total_empresas,TOTAL,100.000000,73.468,60.220,25.366,14.415,26.532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 5 a 9 trabajadores,100.000000,65.319,51.321,28.014,20.665,34.681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 10 a 49 trabajadores,100.000000,79.228,64.481,25.163,10.356,20.772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 50 a 249 trabajadores,100.000000,94.759,79.559,15.091,5.349,5.241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 250 a 499 trabajadores,100.000000,98.371,85.856,11.710,2.434,1.629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,Más de 499 trabajadores,100.000000,99.298,88.305,9.742,1.953,0.702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Industria,100.000000,76.222,64.223,20.911,14.866,23.778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Construcción,100.000000,77.713,61.593,29.467,8.940,22.287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Comercio y reparación de vehículos,100.000000,73.959,62.349,23.788,13.863,26.041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Transporte y almacenamiento,100.000000,77.405,55.376,34.796,9.828,22.595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Hostelería,100.000000,60.735,42.630,36.362,21.008,39.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",100.000000,80.544,73.696,13.463,12.840,19.456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades profesionales, científicas y técnicas",100.000000,81.788,66.118,18.706,15.177,18.212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Actividades administrativas y servicios auxiliares,100.000000,74.261,64.392,22.657,12.951,25.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",100.000000,73.509,62.515,20.437,17.047,26.491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Andalucía,100.000000,73.324,53.315,31.577,15.109,26.676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Aragón,100.000000,73.588,62.546,23.485,13.969,26.412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Asturias (Principado de),100.000000,73.020,55.700,31.219,13.081,26.980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Balears (Illes),100.000000,61.539,61.355,24.875,13.770,38.461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Canarias,100.000000,69.622,58.685,25.936,15.379,30.378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Cantabria,100.000000,71.587,63.019,27.056,9.925,28.413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Castilla-La Mancha,100.000000,73.928,58.307,24.862,16.831,26.072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Castilla y León,100.000000,70.568,55.103,29.104,15.794,29.432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Cataluña,100.000000,76.296,65.436,20.504,14.060,23.704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Comunitat Valenciana,100.000000,74.320,58.492,27.612,13.896,25.680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Extremadura,100.000000,75.343,60.458,25.756,13.786,24.657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Galicia,100.000000,75.145,62.840,21.214,15.946,24.855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Madrid (Comunidad de),100.000000,72.991,62.348,22.853,14.799,27.009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Murcia (Región de),100.000000,76.934,57.263,30.705,12.032,23.066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Navarra (Comunidad Foral de),100.000000,78.843,62.267,22.001,15.732,21.157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,País Vasco,100.000000,71.171,64.009,24.950,11.042,28.829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,"Rioja, La",100.000000,70.224,62.081,21.054,16.865,29.776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,total_empresas,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,29.123694,89.974511,10.025489,70.876306,66.570590,33.429410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 5 a 9 trabajadores,NaN,NaN,NaN,NaN,NaN,NaN,23.671862,83.544726,16.455274,76.328138,59.481181,40.518819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 10 a 49 trabajadores,NaN,NaN,NaN,NaN,NaN,NaN,31.724690,93.100741,6.899259,68.275310,72.749236,27.250764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 50 a 249 trabajadores,NaN,NaN,NaN,NaN,NaN,NaN,48.701094,98.742720,1.266525,51.298906,90.863612,9.136388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,De 250 a 499 trabajadores,NaN,NaN,NaN,NaN,NaN,NaN,58.708189,100.000000,0.000000,41.253364,96.831314,3.168686,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,tamano_empresa,Más de 499 trabajadores,NaN,NaN,NaN,NaN,NaN,NaN,62.753623,99.769053,0.230947,37.246377,98.702983,1.297017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Industria,NaN,NaN,NaN,NaN,NaN,NaN,29.340514,91.943067,8.063373,70.659486,69.761720,30.238280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Construcción,NaN,NaN,NaN,NaN,NaN,NaN,27.053957,90.611641,9.388359,72.946043,73.016647,26.983353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Comercio y reparación de vehículos,NaN,NaN,NaN,NaN,NaN,NaN,28.467349,90.868950,9.131050,71.532651,67.384332,32.615668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Transporte y almacenamiento,NaN,NaN,NaN,NaN,NaN,NaN,25.901905,95.031299,4.968701,74.098095,71.218545,28.781455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Hostelería,NaN,NaN,NaN,NaN,NaN,NaN,30.271329,82.452506,17.547494,69.728671,51.019961,48.980039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",NaN,NaN,NaN,NaN,NaN,NaN,32.924543,94.811321,5.188679,67.075457,74.219561,25.780439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,"Actividades profesionales, científicas y técnicas",NaN,NaN,NaN,NaN,NaN,NaN,33.656148,91.928009,8.071991,66.343852,75.578153,24.421847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,Actividades administrativas y servicios auxiliares,NaN,NaN,NaN,NaN,NaN,NaN,28.286468,93.127579,6.872421,71.713532,65.673438,34.326562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",NaN,NaN,NaN,NaN,NaN,NaN,26.601052,89.684569,10.315431,73.398948,67.478218,32.521782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Andalucía,NaN,NaN,NaN,NaN,NaN,NaN,27.268815,88.163346,11.836654,72.731185,67.635602,32.361933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Aragón,NaN,NaN,NaN,NaN,NaN,NaN,29.243477,87.909060,12.090940,70.756523,67.639522,32.346241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Asturias (Principado de),NaN,NaN,NaN,NaN,NaN,NaN,28.940731,88.071895,11.982571,71.059269,66.637090,33.362910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Balears (Illes),NaN,NaN,NaN,NaN,NaN,NaN,24.984561,85.487288,14.512712,75.015439,53.828061,46.183700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Canarias,NaN,NaN,NaN,NaN,NaN,NaN,32.171083,82.749277,17.250723,67.828917,63.228239,36.771761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Cantabria,NaN,NaN,NaN,NaN,NaN,NaN,20.682680,93.031785,6.968215,79.317320,66.050367,33.949633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Castilla-La Mancha,NaN,NaN,NaN,NaN,NaN,NaN,23.509449,91.404199,8.595801,76.490551,68.831300,31.168700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Castilla y León,NaN,NaN,NaN,NaN,NaN,NaN,31.137803,83.291405,16.729560,68.862197,65.039340,34.951180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Cataluña,NaN,NaN,NaN,NaN,NaN,NaN,31.722109,90.311634,9.688366,68.277891,69.361787,30.638213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Comunitat Valenciana,NaN,NaN,NaN,NaN,NaN,NaN,26.022668,94.221709,5.778291,73.977332,66.967668,33.035714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Extremadura,NaN,NaN,NaN,NaN,NaN,NaN,23.936956,88.203018,11.796982,76.063044,71.012303,28.987697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Galicia,NaN,NaN,NaN,NaN,NaN,NaN,26.402254,92.650020,7.349980,73.597746,68.438922,31.568302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Madrid (Comunidad de),NaN,NaN,NaN,NaN,NaN,NaN,35.432441,91.263257,8.736743,64.567559,63.013225,36.986775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Murcia (Región de),NaN,NaN,NaN,NaN,NaN,NaN,23.245159,92.822611,7.177389,76.754841,72.339227,27.672035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,Navarra (Comunidad Foral de),NaN,NaN,NaN,NaN,NaN,NaN,28.000841,96.171171,3.828829,71.999159,72.291971,27.678832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,País Vasco,NaN,NaN,NaN,NaN,NaN,NaN,26.840242,92.489942,7.510058,73.159758,63.698237,36.301763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2024,EAL-18,EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO DE LA E...,ccaa,"Rioja, La",NaN,NaN,NaN,NaN,NaN,NaN,21.563236,92.349727,7.650273,78.436764,64.346520,35.653480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Versión larga de las hojas compatibles

Se genera una vista larga para análisis posterior, sin guardar archivos. Las columnas quedan alineadas con Sabina: metadatos + `variable` + `porcentaje`.

In [19]:

# ============================================================
# PASAR HOJAS COMPATIBLES A FORMATO LARGO
# ============================================================

columnas_id = ["anio", "tabla", "pregunta", "ambito", "categoria"]
columnas_valor = [columna for columna in df_compatibles_ancho.columns if columna not in columnas_id]

df_compatibles_largo = to_long_format(
    df=df_compatibles_ancho,
    id_vars=columnas_id,
    value_vars=columnas_valor,
    var_name="variable",
    value_name="porcentaje",
)

print("df_compatibles_largo:", df_compatibles_largo.shape)

with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_compatibles_largo)

df_compatibles_largo: (855, 7)

,anio,tabla,pregunta,ambito,categoria,variable,porcentaje
0,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",total_empresas,TOTAL,TOTAL,100.000000
1,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 5 a 9 trabajadores,TOTAL,100.000000
2,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 10 a 49 trabajadores,TOTAL,100.000000
3,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 50 a 249 trabajadores,TOTAL,100.000000
4,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 250 a 499 trabajadores,TOTAL,100.000000
5,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,Más de 499 trabajadores,TOTAL,100.000000
6,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Industria,TOTAL,100.000000
7,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Construcción,TOTAL,100.000000
8,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Comercio y reparación de vehículos,TOTAL,100.000000
9,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Transporte y almacenamiento,TOTAL,100.000000
10,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Hostelería,TOTAL,100.000000
11,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",TOTAL,100.000000
12,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades profesionales, científicas y técnicas",TOTAL,100.000000
13,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Actividades administrativas y servicios auxiliares,TOTAL,100.000000
14,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",TOTAL,100.000000
15,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Andalucía,TOTAL,100.000000
16,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Aragón,TOTAL,100.000000
17,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Asturias (Principado de),TOTAL,100.000000
18,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Balears (Illes),TOTAL,100.000000
19,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Canarias,TOTAL,100.000000
20,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Cantabria,TOTAL,100.000000
21,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Castilla-La Mancha,TOTAL,100.000000
22,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Castilla y León,TOTAL,100.000000
23,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Cataluña,TOTAL,100.000000
24,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Comunitat Valenciana,TOTAL,100.000000
25,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Extremadura,TOTAL,100.000000
26,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Galicia,TOTAL,100.000000
27,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Madrid (Comunidad de),TOTAL,100.000000
28,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Murcia (Región de),TOTAL,100.000000
29,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,Navarra (Comunidad Foral de),TOTAL,100.000000
30,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,País Vasco,TOTAL,100.000000
31,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",ccaa,"Rioja, La",TOTAL,100.000000
32,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",total_empresas,TOTAL,TOTAL,73.468278
33,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 5 a 9 trabajadores,TOTAL,65.319423
34,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 10 a 49 trabajadores,TOTAL,79.227905
35,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 50 a 249 trabajadores,TOTAL,94.759353
36,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,De 250 a 499 trabajadores,TOTAL,98.385236
37,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",tamano_empresa,Más de 499 trabajadores,TOTAL,99.275362
38,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Industria,TOTAL,76.222600
39,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Construcción,TOTAL,77.712290
40,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Comercio y reparación de vehículos,TOTAL,73.958727
41,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Transporte y almacenamiento,TOTAL,77.406769
42,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Hostelería,TOTAL,60.735371
43,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",TOTAL,80.544101
44,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,"Actividades profesionales, científicas y técnicas",TOTAL,81.788176
45,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,Actividades administrativas y servicios auxiliares,TOTAL,74.261496
46,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",TOTAL,73.507801
47,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Andalucía,TOTAL,73.324726
48,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Aragón,TOTAL,73.587186
49,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Asturias (Principado de),TOTAL,73.013871
50,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Balears (Illes),TOTAL,61.535068
51,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Canarias,TOTAL,69.624593
52,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Cantabria,TOTAL,71.580278
53,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Castilla-La Mancha,TOTAL,73.929811
54,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Castilla y León,TOTAL,70.565964
55,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Cataluña,TOTAL,76.295600
56,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Comunitat Valenciana,TOTAL,74.320098
57,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Extremadura,TOTAL,75.340667
58,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Galicia,TOTAL,75.144877
59,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Madrid (Comunidad de),TOTAL,72.991275
60,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Murcia (Región de),TOTAL,76.936376
61,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,Navarra (Comunidad Foral de),TOTAL,78.852218
62,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,País Vasco,TOTAL,71.174036
63,2024,EAL-18a,"EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN MEDIO UTILIZADO POR TAMAÑO DE LA EMPRESA, ACTIVIDAD E...",ccaa,"Rioja, La",TOTAL,70.227808
64,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 5 a 9 trabajadores,TOTAL,100.000000
65,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 10 a 49 trabajadores,TOTAL,100.000000
66,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 50 a 249 trabajadores,TOTAL,100.000000
67,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,De 250 a 499 trabajadores,TOTAL,100.000000
68,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,tamano_empresa,Más de 499 trabajadores,TOTAL,100.000000
69,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Industria,TOTAL,100.000000
70,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Construcción,TOTAL,100.000000
71,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Comercio y reparación de vehículos,TOTAL,100.000000
72,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Transporte y almacenamiento,TOTAL,100.000000
73,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Hostelería,TOTAL,100.000000
74,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",TOTAL,100.000000
75,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,"Actividades profesionales, científicas y técnicas",TOTAL,100.000000
76,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,Actividades administrativas y servicios auxiliares,TOTAL,100.000000
77,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,sector,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",TOTAL,100.000000
78,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Andalucía,TOTAL,100.000000
79,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Aragón,TOTAL,100.000000
80,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Asturias (Principado de),TOTAL,100.000000
81,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Balears (Illes),TOTAL,100.000000
82,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Canarias,TOTAL,100.000000
83,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Cantabria,TOTAL,100.000000
84,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Castilla-La Mancha,TOTAL,100.000000
85,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Castilla y León,TOTAL,100.000000
86,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Cataluña,TOTAL,100.000000
87,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Comunitat Valenciana,TOTAL,100.000000
88,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Extremadura,TOTAL,100.000000
89,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Galicia,TOTAL,100.000000
90,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Madrid (Comunidad de),TOTAL,100.000000
91,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Murcia (Región de),TOTAL,100.000000
92,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,Navarra (Comunidad Foral de),TOTAL,100.000000
93,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,País Vasco,TOTAL,100.000000
94,2024,EAL-18b,EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES EN SUSPENSIÓN DE CONTRATO Y/O REDUCCION DE JORNADA POR TAMA...,ccaa,"Rioja, La",TOTAL,100.000000
95,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",total_empresas,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,73.468000
96,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 5 a 9 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,65.319000
97,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 10 a 49 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,79.228000
98,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 50 a 249 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,94.759000
99,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,De 250 a 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,98.371000
100,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",tamano_empresa,Más de 499 trabajadores,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,99.298000
101,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Industria,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,76.222000
102,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Construcción,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,77.713000
103,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Comercio y reparación de vehículos,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,73.959000
104,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Transporte y almacenamiento,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,77.405000
105,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,Hostelería,EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,60.735000
106,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,80.544000
107,2024,EAL-17,"EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",sector,"Actividades profesionales, científicas y técnicas",EMPRESAS QUE PROPORCIONAN FORMACIÓN - TOTAL,81.788000