# Librerías

In [80]:
import pandas as pd
import numpy as np
import re
import pathlib as Path
import unicodedata

# Documents

Extraer los datos de los últimos 5 años (2020 - 2024):
Hojas de formación en las empresas, contexto y errores muestreo
Extraemos todos los datos respecto a formación en las empresas pero después analizaremos solo (en el caso de algunas tablas de formación cogeremos ya las específicas de servicios [e.g. 2024 EAL-23 y 23c]):
CCAA: Total y Cataluña y otras CCAA donde tenemos sede (Madrid, Valencia, Sevilla y Bilbao)
Tamaño empresa: más de 499
Sector Transporte y almacenamiento y cuando agregado servicios

TABLAS CONTEXTO
2020, 2021, 2022, 2023, 2024:
EAL-C1, EAL-C2, EAL-C3

TABLAS FORMACIÓN EMPRESAS
2020, 2021, 2022:
EAL-16, EAL-17, EAL-18, EAL-19, EAL-20, EAL-21, EAL-22, EAL-24, EAL-25

2023, 2024 añadido:
EAL-18a, EAL-18b, EAL-18c

ERRORES MUESTREO
2020, 2021, 2022, 2023, 2024:
EAL-M1

He hagut de fer: pip install openpyxl (és l'engine de pandas per excel més nous)

In [81]:
import pandas as pd
from pathlib import Path

def encontrar_raiz_repo(inicio=None):
    ruta = Path(inicio or Path.cwd()).resolve()
    for candidata in [ruta, *ruta.parents]:
        if (candidata / "Equip_31").exists():
            return candidata
    raise FileNotFoundError("No se encontró la raíz del repositorio con Equip_31.")

REPO_ROOT = encontrar_raiz_repo()

# Ruta relativa dentro del repositorio Git.
file_path_rel = Path("Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx")
file_path = REPO_ROOT / file_path_rel

print("Raíz repo:", REPO_ROOT)
print("Excel origen:", file_path_rel)
print("Archivo existe:", file_path.exists())

if not file_path.exists():
    raise FileNotFoundError(f"No existe el Excel esperado: {file_path}")

sheets_to_extract = [
    # TABLAS CONTEXTO
    "EAL-C1", "EAL-C2", "EAL-C3",

    # TABLAS FORMACIÓN EMPRESAS
    "EAL-16", "EAL-17", "EAL-18", "EAL-19", "EAL-20", "EAL-21",
    "EAL-22", "EAL-23", "EAL-24", "EAL-25",
    "EAL-18a", "EAL-18b", "EAL-18c",

    # ERRORES MUESTREO
    "EAL-M1"
]

# Read selected sheets into a dictionary of DataFrames
dfs = pd.read_excel(
    file_path,
    sheet_name=sheets_to_extract,
    header=None,
    dtype=str
)

# Basic cleaning: remove fully empty rows and columns
for sheet_name, df in dfs.items():
    df = df.dropna(how="all")
    df = df.dropna(axis=1, how="all")
    df = df.reset_index(drop=True)
    dfs[sheet_name] = df

Raíz repo: /Users/fedeur/ProjecteData
Excel origen: Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx
Archivo existe: True

In [82]:
dfs["EAL-23"]

,0,1,2,3,4,5
0,ENCUESTA ANUAL LABORAL,NaN,NaN,NaN,NaN,EAL
1,,NaN,NaN,NaN,NaN,Volver al índice
2,EAL-23. EMPRESAS QUE PROPORCIONARON FORMACIÓN ...,NaN,NaN,NaN,NaN,NaN
3,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
4,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
5,Responder a un sistema predeterminado de promo...,100,24.833,42.321,26.86,5.987
6,Readaptar al personal a los cambios técnicos i...,100,12.615,22.193,49.421,15.771
7,Readaptar al personal a los cambios organizati...,100,14.246,29.411,44.323,12.02
8,Adaptar al personal recién incorporado a las t...,100,7.888,15.038,50.533,26.541
9,Mejorar la cualificación básica del personal p...,100,8.168,22.567,51.043,18.222
10,Adaptación impuesta por cambios normativos,100,8.955,22.904,42.755,25.385
11,EAL-23a. EMPRESAS DE 5 A 49 TRABAJADORES QUE P...,NaN,NaN,NaN,NaN,NaN
12,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
13,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
14,Responder a un sistema predeterminado de promo...,100,26.215,42.352,25.663,5.77
15,Readaptar al personal a los cambios técnicos i...,100,13.406,22.523,48.979,15.093
16,Readaptar al personal a los cambios organizati...,100,14.992,29.748,43.875,11.385
17,Adaptar al personal recién incorporado a las t...,100,8.366,15.287,50.501,25.846
18,Mejorar la cualificación básica del personal p...,100,8.508,22.676,50.974,17.842
19,Adaptación impuesta por cambios normativos,100,9.245,22.663,42.547,25.545
20,EAL-23b. EMPRESAS DE 50 A 499 TRABAJADORES QUE...,NaN,NaN,NaN,NaN,NaN
21,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
22,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
23,Responder a un sistema predeterminado de promo...,100,12.656,42.521,37.171,7.652
24,Readaptar al personal a los cambios técnicos i...,100,5.686,19.516,53.359,21.44
25,Readaptar al personal a los cambios organizati...,100,7.78,26.446,48.185,17.589
26,Adaptar al personal recién incorporado a las t...,100,3.731,13.026,50.737,32.506
27,Mejorar la cualificación básica del personal p...,100,5.099,21.391,51.774,21.736
28,Adaptación impuesta por cambios normativos,100,6.494,25.048,44.465,23.994
29,EAL-23c. EMPRESAS DE MÁS DE 499 TRABAJADORES Q...,NaN,NaN,NaN,NaN,NaN
30,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
31,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
32,Responder a un sistema predeterminado de promo...,100,7.551,36.456,44.463,11.53
33,Readaptar al personal a los cambios técnicos i...,100,2.345,15.439,54.421,27.794
34,Readaptar al personal a los cambios organizati...,100,3.682,25.152,50.874,20.292
35,Adaptar al personal recién incorporado a las t...,100,1.267,9.804,51.856,37.073
36,Mejorar la cualificación básica del personal p...,100,4.796,23.62,50.479,21.105
37,Adaptación impuesta por cambios normativos,100,4.237,25.702,46.8,23.261
38,EAL-23d. EMPRESAS DE LA INDUSTRIA QUE PROPORCI...,NaN,NaN,NaN,NaN,NaN
39,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
40,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
41,Responder a un sistema predeterminado de promo...,100,23.083,44.985,27.291,4.641
42,Readaptar al personal a los cambios técnicos i...,100,10.579,20.232,52.653,16.536
43,Readaptar al personal a los cambios organizati...,100,12.616,29.389,47.951,10.044
44,Adaptar al personal recién incorporado a las t...,100,7.527,13.819,52.765,25.889
45,Mejorar la cualificación básica del personal p...,100,8.622,20.749,54.127,16.502
46,Adaptación impuesta por cambios normativos,100,9.336,21.57,45.944,23.15
47,EAL-23e. EMPRESAS DE LA CONSTRUCCIÓN QUE PROPO...,NaN,NaN,NaN,NaN,NaN
48,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
49,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
50,Responder a un sistema predeterminado de promo...,100,26.644,45.327,23.875,4.154
51,Readaptar al personal a los cambios técnicos i...,100,13.994,28.679,46.599,10.728
52,Readaptar al personal a los cambios organizati...,100,16.786,33.498,41.561,8.155
53,Adaptar al personal recién incorporado a las t...,100,8.741,16.595,52.589,22.075
54,Mejorar la cualificación básica del personal p...,100,7.393,20.185,53.103,19.32
55,Adaptación impuesta por cambios normativos,100,7.167,18.34,48.138,26.356
56,EAL-23f. EMPRESAS DEL SECTOR SERVICIOS QUE PRO...,NaN,NaN,NaN,NaN,NaN
57,Año 2024. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
58,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
59,Responder a un sistema predeterminado de promo...,100,24.872,41.166,27.332,6.63
60,Readaptar al personal a los cambios técnicos i...,100,12.8,21.391,49.249,16.561
61,Readaptar al personal a los cambios organizati...,100,14.121,28.64,44.052,13.187
62,Adaptar al personal recién incorporado a las t...,100,7.805,15.009,49.654,27.532
63,Mejorar la cualificación básica del personal p...,100,8.216,23.417,49.976,18.391
64,Adaptación impuesta por cambios normativos,100,9.211,24.064,41.034,25.691

In [83]:
# Output folder dentro del repositorio Git.
output_folder_rel = Path("Equip_31/Data/Processed/EAL/2024")
output_folder = REPO_ROOT / output_folder_rel
output_folder.mkdir(parents=True, exist_ok=True)

# Save each dataframe as CSV
for sheet_name, df in dfs.items():
    output_path = output_folder / f"{sheet_name}.csv"

    df.to_csv(
        output_path,
        index=False,
        header=False,
        encoding="utf-8-sig"
    )

print(f"CSV files saved in: {output_folder_rel}")

CSV files saved in: Equip_31/Data/Processed/EAL/2024

## Normalización estructural de EAL-16

A partir de aquí se trabaja con el CSV extraído de la hoja `EAL-16`. Las rutas se resuelven desde la raíz del repositorio para que el notebook funcione aunque se ejecute desde otra carpeta.

In [84]:
# ============================================================
# CONFIGURACIÓN
# ============================================================

from pathlib import Path
import re
import unicodedata
import pandas as pd

def encontrar_raiz_repo(inicio=None):
    """Devuelve la raíz del repositorio buscando la carpeta Equip_31."""
    ruta = Path(inicio or Path.cwd()).resolve()
    for candidata in [ruta, *ruta.parents]:
        if (candidata / "Equip_31").exists():
            return candidata
    raise FileNotFoundError("No se encontró la raíz del repositorio con Equip_31.")

REPO_ROOT = encontrar_raiz_repo()

# Ruta relativa dentro del repositorio Git.
archivo_csv_rel = Path("Equip_31/Data/Processed/EAL/2024/EAL-16.csv")
archivo_csv = REPO_ROOT / archivo_csv_rel

# Excel oficial raw, usado solo para comprobación y trazabilidad.
archivo_raw_rel = Path("Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx")
archivo_raw = REPO_ROOT / archivo_raw_rel

ANIO = 2024
HOJA = "EAL-16"

print("Raíz repo:", REPO_ROOT)
print("Ruta relativa:", archivo_csv_rel)
print("CSV existe:", archivo_csv.exists())
print("CSV resuelto:", archivo_csv)
print("Raw existe:", archivo_raw.exists())
print("Raw resuelto:", archivo_raw)

if not archivo_csv.exists():
    raise FileNotFoundError(f"No existe el CSV esperado: {archivo_csv}")
if not archivo_raw.exists():
    raise FileNotFoundError(f"No existe el Excel raw esperado: {archivo_raw}")

Raíz repo: /Users/fedeur/ProjecteData
Ruta relativa: Equip_31/Data/Processed/EAL/2024/EAL-16.csv
CSV existe: True
CSV resuelto: /Users/fedeur/ProjecteData/Equip_31/Data/Processed/EAL/2024/EAL-16.csv
Raw existe: True
Raw resuelto: /Users/fedeur/ProjecteData/Equip_31/Data/raw/EAL/Tablas_EAL_2024.xlsx

## Funciones auxiliares

Estas funciones limpian texto, detectan las subtablas internas de `EAL-16` y asignan metadatos estructurales: ámbito, sector, tamaño de empresa y CCAA.

In [85]:
# ============================================================
# FUNCIONES AUXILIARES
# ============================================================

def limpiar_texto(valor):
    if pd.isna(valor):
        return ""
    valor = str(valor).replace("\n", " ")
    valor = re.sub(r"\s+", " ", valor)
    return valor.strip()

def quitar_acentos(texto):
    texto = unicodedata.normalize("NFKD", str(texto))
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    return texto.lower().strip()

def extraer_codigo_subtabla(texto):
    match = re.match(r"^(EAL-16[a-f]?)\.", limpiar_texto(texto), flags=re.IGNORECASE)
    return match.group(1).upper() if match else None

def metadatos_subtabla(codigo, titulo):
    """
    Asigna solo las dimensiones que realmente desagrega cada subtabla.

    Regla metodológica para EAL-16:
    - EAL-16: total empresas; no desagrega por sector, tamaño ni CCAA.
    - EAL-16a/b/c: desagrega por tamaño de empresa; sector y CCAA no aplican.
    - EAL-16d/e/f: desagrega por sector agregado; tamaño y CCAA no aplican.
    """
    metadatos = {
        "Ámbito": "Total empresas",
        "Sector": "",
        "Tamaño Empresa": "",
        "CCAA": "",
    }

    if codigo == "EAL-16A":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = "5 a 49 trabajadores"
    elif codigo == "EAL-16B":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = "50 a 499 trabajadores"
    elif codigo == "EAL-16C":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = "Más de 499 trabajadores"
    elif codigo == "EAL-16D":
        metadatos["Ámbito"] = "Sector agregado"
        metadatos["Sector"] = "Industria"
    elif codigo == "EAL-16E":
        metadatos["Ámbito"] = "Sector agregado"
        metadatos["Sector"] = "Construcción"
    elif codigo == "EAL-16F":
        metadatos["Ámbito"] = "Sector agregado"
        metadatos["Sector"] = "Servicios"

    return metadatos

def fila_es_cabecera(row):
    valores = [limpiar_texto(x).upper() for x in row.tolist()]
    return {"TOTAL", "NADA", "POCO", "BASTANTE", "MUCHO"}.issubset(set(valores))

## Lectura del CSV original

Se lee el CSV procesado por la extracción previa, sin asumir encabezado fijo.

In [86]:
# ============================================================
# LECTURA DEL CSV ORIGINAL
# ============================================================

df_raw = pd.read_csv(
    archivo_csv,
    header=None,
    dtype=str,
    keep_default_na=False
)

df_raw = df_raw.map(limpiar_texto)
df_raw = df_raw.replace("", pd.NA)
df_raw = df_raw.dropna(how="all")
df_raw = df_raw.dropna(axis=1, how="all")
df_raw = df_raw.fillna("").reset_index(drop=True)

print("Dimensión original:", df_raw.shape)
display(df_raw.head(20))

Dimensión original: (93, 6)

,0,1,2,3,4,5
0,ENCUESTA ANUAL LABORAL,,,,,EAL
1,,,,,,Volver al índice
2,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PA...,,,,,
3,Año 2024. Porcentaje sobre el total de empresas.,,,,,
4,,TOTAL,NADA,POCO,BASTANTE,MUCHO
5,De dirección,100,10.414,18.818,40.283,30.484
6,De trabajo en equipo,100,2.224,5.822,45.125,46.829
7,De atención al público/ trato a clientes,100,5.128,13.392,37.144,44.336
8,Administrativas de oficina,100,11.117,25.313,37.788,25.782
9,De resolución de problemas (localización de pr...,100,5.893,15.752,44.063,34.292
10,En lenguas extranjeras,100,23.022,40.356,24.568,12.054
11,Básicas de cálculo y/o comunicación oral o esc...,100,22.688,36.513,29.697,11.102
12,Generales de tecnologías de la información,100,13.593,29.346,39.173,17.888
13,Profesionales de tecnologías de la información,100,26.908,37.656,24.493,10.944
14,"Competencias técnicas, prácticas y otras espec...",100,13.417,18.861,36.496,31.226
15,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN...,,,,,
16,Año 2024. Porcentaje respecto al total de empr...,,,,,
17,,TOTAL,NADA,POCO,BASTANTE,MUCHO
18,De dirección,100,11.075,19.589,39.991,29.345
19,De trabajo en equipo,100,2.321,5.976,45.426,46.277

## EAL-16 en formato ancho

La salida solicitada es una fila por categoría y bloque, manteniendo las columnas originales de respuesta (`TOTAL`, `NADA`, `POCO`, `BASTANTE`, `MUCHO`). En `EAL-16` hay 7 bloques y 10 categorías por bloque, por tanto quedan 70 registros.

In [87]:
# ============================================================
# EAL-16 A FORMATO ANCHO
# ============================================================

COLUMNAS_EAL16 = ["TOTAL", "NADA", "POCO", "BASTANTE", "MUCHO"]

registros = []
titulo_actual = None
codigo_actual = None
columnas_actuales = None
metadatos_actuales = None

for _, row in df_raw.iterrows():
    primera_celda = limpiar_texto(row.iloc[0])
    codigo_detectado = extraer_codigo_subtabla(primera_celda)

    if codigo_detectado:
        codigo_actual = codigo_detectado
        titulo_actual = primera_celda
        columnas_actuales = None
        metadatos_actuales = metadatos_subtabla(codigo_actual, titulo_actual)
        continue

    if codigo_actual and fila_es_cabecera(row):
        columnas_actuales = [limpiar_texto(x).upper() for x in row.tolist()]
        continue

    if not (codigo_actual and columnas_actuales):
        continue

    categoria = primera_celda
    if categoria == "":
        continue

    registro = {
        "Año": ANIO,
        "Hoja": HOJA,
        "Título de tabla": titulo_actual,
        "Categoría": categoria,
    }

    for posicion, columna in enumerate(columnas_actuales):
        if columna in COLUMNAS_EAL16:
            registro[columna] = pd.to_numeric(limpiar_texto(row.iloc[posicion]), errors="coerce")

    registros.append(registro)

df_eal16_ancho = pd.DataFrame(registros)
columnas_eal16_ancho = [
    "Año", "Hoja", "Título de tabla", "Categoría",
    "TOTAL", "NADA", "POCO", "BASTANTE", "MUCHO"
]
df_eal16_ancho = df_eal16_ancho[columnas_eal16_ancho]

assert df_eal16_ancho.shape[0] == 70
assert df_eal16_ancho[COLUMNAS_EAL16].notna().all().all()

print("EAL-16 ancho hasta columna MUCHO:", df_eal16_ancho.shape)
print("Esperado: 7 bloques x 10 categorías = 70 registros")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal16_ancho)

EAL-16 ancho hasta columna MUCHO: (70, 9)
Esperado: 7 bloques x 10 categorías = 70 registros

,Año,Hoja,Título de tabla,Categoría,TOTAL,NADA,POCO,BASTANTE,MUCHO
0,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De dirección,100,10.414,18.818,40.283,30.484
1,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De trabajo en equipo,100,2.224,5.822,45.125,46.829
2,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,De atención al público/ trato a clientes,100,5.128,13.392,37.144,44.336
3,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Administrativas de oficina,100,11.117,25.313,37.788,25.782
4,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,5.893,15.752,44.063,34.292
5,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,En lenguas extranjeras,100,23.022,40.356,24.568,12.054
6,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Básicas de cálculo y/o comunicación oral o escrita,100,22.688,36.513,29.697,11.102
7,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Generales de tecnologías de la información,100,13.593,29.346,39.173,17.888
8,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,Profesionales de tecnologías de la información,100,26.908,37.656,24.493,10.944
9,2024,EAL-16,EAL-16. EMPRESAS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS DE DIVERSAS COMPET...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,13.417,18.861,36.496,31.226
10,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De dirección,100,11.075,19.589,39.991,29.345
11,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De trabajo en equipo,100,2.321,5.976,45.426,46.277
12,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,De atención al público/ trato a clientes,100,5.200,13.151,36.884,44.764
13,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Administrativas de oficina,100,11.815,25.651,36.989,25.545
14,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,6.161,16.142,43.592,34.104
15,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,En lenguas extranjeras,100,23.741,40.753,23.986,11.519
16,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Básicas de cálculo y/o comunicación oral o escrita,100,23.741,36.767,28.759,10.733
17,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Generales de tecnologías de la información,100,14.343,30.144,38.530,16.983
18,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,Profesionales de tecnologías de la información,100,28.160,38.095,23.711,10.034
19,2024,EAL-16,EAL-16a. EMPRESAS DE 5 A 49 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,13.890,19.160,36.312,30.638
20,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,De dirección,100,2.498,9.573,43.903,44.026
21,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,De trabajo en equipo,100,1.103,4.062,41.538,53.297
22,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,De atención al público/ trato a clientes,100,4.355,16.362,40.501,38.782
23,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,Administrativas de oficina,100,2.678,21.162,47.295,28.866
24,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,2.760,10.937,49.810,36.493
25,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,En lenguas extranjeras,100,14.822,35.718,31.244,18.217
26,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,Básicas de cálculo y/o comunicación oral o escrita,100,10.332,33.790,40.670,15.208
27,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,Generales de tecnologías de la información,100,4.697,20.101,46.860,28.343
28,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,Profesionales de tecnologías de la información,100,12.160,32.897,33.533,21.409
29,2024,EAL-16,EAL-16b. EMPRESAS DE 50 A 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIM...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,7.808,15.121,38.807,38.263
30,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,De dirección,100,1.219,8.240,42.912,47.628
31,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,De trabajo en equipo,100,0.350,2.647,40.670,56.333
32,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,De atención al público/ trato a clientes,100,2.959,15.763,37.806,43.472
33,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,Administrativas de oficina,100,2.211,21.871,49.752,26.166
34,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,1.237,11.915,49.421,37.427
35,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,En lenguas extranjeras,100,8.034,33.434,36.148,22.384
36,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,Básicas de cálculo y/o comunicación oral o escrita,100,4.952,29.125,45.866,20.057
37,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,Generales de tecnologías de la información,100,2.056,14.576,48.346,35.022
38,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,Profesionales de tecnologías de la información,100,6.458,25.460,39.324,28.758
39,2024,EAL-16,EAL-16c. EMPRESAS DE MÁS DE 499 TRABAJADORES SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓX...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,6.080,16.604,37.880,39.435
40,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,De dirección,100,8.197,17.305,41.698,32.801
41,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,De trabajo en equipo,100,2.753,6.778,50.076,40.393
42,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,De atención al público/ trato a clientes,100,7.136,19.834,42.025,31.005
43,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Administrativas de oficina,100,7.854,20.558,45.127,26.460
44,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,5.355,13.448,46.745,34.453
45,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,En lenguas extranjeras,100,26.050,40.489,23.916,9.544
46,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Básicas de cálculo y/o comunicación oral o escrita,100,19.333,38.621,32.408,9.638
47,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Generales de tecnologías de la información,100,10.605,27.884,44.776,16.735
48,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,Profesionales de tecnologías de la información,100,20.694,40.976,27.740,10.590
49,2024,EAL-16,EAL-16d. EMPRESAS DE LA INDUSTRIA SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑOS D...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,5.024,11.106,43.003,40.867
50,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,De dirección,100,9.038,19.132,42.284,29.546
51,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,De trabajo en equipo,100,1.799,5.505,48.771,43.926
52,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,De atención al público/ trato a clientes,100,10.004,27.124,38.024,24.848
53,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,Administrativas de oficina,100,10.250,22.411,38.818,28.520
54,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,4.291,12.994,43.967,38.748
55,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,En lenguas extranjeras,100,37.183,45.380,13.307,4.130
56,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,Básicas de cálculo y/o comunicación oral o escrita,100,24.034,40.470,28.081,7.415
57,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,Generales de tecnologías de la información,100,15.576,33.079,38.295,13.050
58,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,Profesionales de tecnologías de la información,100,28.493,42.797,22.826,5.884
59,2024,EAL-16,EAL-16e. EMPRESAS DE LA CONSTRUCCIÓN SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS AÑO...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,6.518,9.411,40.560,43.510
60,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,De dirección,100,11.117,19.077,39.637,30.169
61,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,De trabajo en equipo,100,2.189,5.680,43.455,48.677
62,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,De atención al público/ trato a clientes,100,3.851,9.635,35.976,50.538
63,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,Administrativas de oficina,100,11.946,26.811,36.084,25.159
64,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",100,6.288,16.716,43.524,33.473
65,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,En lenguas extranjeras,100,19.897,39.443,26.688,13.971
66,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,Básicas de cálculo y/o comunicación oral o escrita,100,23.147,35.378,29.419,12.056
67,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,Generales de tecnologías de la información,100,13.863,28.992,38.165,18.980
68,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,Profesionales de tecnologías de la información,100,27.918,36.061,24.113,11.909
69,2024,EAL-16,EAL-16f. EMPRESAS DEL SECTOR SERVICIOS SEGÚN GRADO DE IMPORTANCIA PARA EL DESARROLLO DE LA EMPRESA EN LOS PRÓXIMOS A...,"Competencias técnicas, prácticas y otras específicas del puesto de trabajo",100,16.375,22.136,34.430,27.059

## EAL-17 y EAL-18 en formato ancho

Para estas hojas se mantiene una fila por categoría/desglose y se conservan las columnas originales de la tabla. La columna `Ámbito` indica si la fila corresponde a total, tamaño de empresa, sector o CCAA.

In [88]:
# ============================================================
# FUNCIONES PARA EAL-17 Y EAL-18 EN FORMATO ANCHO
# ============================================================

SECCIONES_FILA = {
    "TAMAÑO DE LA EMPRESA": "Tamaño empresa",
    "ACTIVIDAD ECONÓMICA": "Sector",
    "COMUNIDAD AUTÓNOMA": "CCAA",
}


def leer_csv_hoja(hoja):
    ruta_rel = Path(f"Equip_31/Data/Processed/EAL/2024/{hoja}.csv")
    ruta = REPO_ROOT / ruta_rel
    if not ruta.exists():
        raise FileNotFoundError(f"No existe el CSV esperado: {ruta}")

    df = pd.read_csv(ruta, header=None, dtype=str, keep_default_na=False)
    df = df.map(limpiar_texto)
    df = df.replace("", pd.NA)
    df = df.dropna(how="all")
    df = df.dropna(axis=1, how="all")
    df = df.fillna("").reset_index(drop=True)
    return df, ruta_rel


def metadatos_fila(categoria, seccion_actual):
    metadatos = {
        "Ámbito": "Total empresas",
        "Sector": "",
        "Tamaño Empresa": "",
        "CCAA": "",
    }

    if categoria.upper() == "TOTAL":
        return metadatos

    if seccion_actual == "Tamaño empresa":
        metadatos["Ámbito"] = "Tamaño empresa"
        metadatos["Tamaño Empresa"] = categoria
    elif seccion_actual == "Sector":
        metadatos["Ámbito"] = "Sector"
        metadatos["Sector"] = categoria
    elif seccion_actual == "CCAA":
        metadatos["Ámbito"] = "CCAA"
        metadatos["CCAA"] = categoria

    return metadatos


def detectar_titulo_csv(df, hoja):
    for valor in df.iloc[:, 0].tolist():
        texto = limpiar_texto(valor)
        if texto.upper().startswith(f"{hoja}."):
            return texto
    return ""


def nombres_columnas_eal17(df):
    grupo_superior = [limpiar_texto(x) for x in df.iloc[4].tolist()]
    subvariable = [limpiar_texto(x) for x in df.iloc[5].tolist()]

    columnas = {}
    grupo_actual = ""
    for col in range(1, df.shape[1]):
        if grupo_superior[col]:
            grupo_actual = grupo_superior[col]
        sub = subvariable[col]

        if col == 1:
            columnas[col] = "TOTAL"
        elif grupo_actual and sub:
            columnas[col] = f"{grupo_actual} - {sub}"
        elif grupo_actual:
            columnas[col] = grupo_actual
        else:
            columnas[col] = sub
    return columnas, 6


def nombres_columnas_eal18(df):
    grupo_superior = [limpiar_texto(x) for x in df.iloc[4].tolist()]
    subvariable = [limpiar_texto(x) for x in df.iloc[5].tolist()]

    columnas = {}
    grupo_actual = ""
    for col in range(1, df.shape[1]):
        if grupo_superior[col]:
            grupo_actual = grupo_superior[col]
        sub = subvariable[col]
        columnas[col] = f"{grupo_actual} - {sub}" if grupo_actual and sub else (grupo_actual or sub)
    return columnas, 6


def parsear_eal_17_18_ancho(hoja, constructor_columnas):
    df, ruta_rel = leer_csv_hoja(hoja)
    titulo = detectar_titulo_csv(df, hoja)
    columnas_valor, fila_inicio_datos = constructor_columnas(df)

    registros = []
    seccion_actual = None

    for _, row in df.iloc[fila_inicio_datos:].iterrows():
        categoria = limpiar_texto(row.iloc[0])
        if categoria == "":
            continue

        categoria_norm = categoria.upper()
        if categoria_norm in SECCIONES_FILA:
            seccion_actual = SECCIONES_FILA[categoria_norm]
            continue
        if categoria.startswith("("):
            continue

        metadatos = metadatos_fila(categoria, seccion_actual)
        registro = {
            "Año": ANIO,
            "Hoja": hoja,
            "Título de tabla": titulo,
            "Categoría": categoria,
            "Ámbito": metadatos["Ámbito"],
            "Sector": metadatos["Sector"],
            "Tamaño Empresa": metadatos["Tamaño Empresa"],
            "CCAA": metadatos["CCAA"],
        }

        for col, nombre_columna in columnas_valor.items():
            valor = limpiar_texto(row.iloc[col]) if col < len(row) else ""
            registro[nombre_columna] = pd.to_numeric(valor, errors="coerce")

        registros.append(registro)

    df_ancho = pd.DataFrame(registros)
    columnas_base = ["Año", "Hoja", "Título de tabla", "Categoría"]
    columnas_dim = ["Ámbito", "Sector", "Tamaño Empresa", "CCAA"]
    columnas_valores = [nombre for _, nombre in sorted(columnas_valor.items())]
    df_ancho = df_ancho[columnas_base + columnas_valores + columnas_dim]

    print(f"{hoja} desde {ruta_rel}: {df.shape} -> {df_ancho.shape}")
    return df_ancho

## EAL-17 en formato ancho

In [89]:
# ============================================================
# EAL-17 A FORMATO ANCHO
# ============================================================

df_eal17_ancho = parsear_eal_17_18_ancho("EAL-17", nombres_columnas_eal17)

assert df_eal17_ancho.shape[0] == 32
print("Esperado EAL-17: 32 filas de categorías/desgloses")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal17_ancho.iloc[:, :10])

EAL-17 desde Equip_31/Data/Processed/EAL/2024/EAL-17.csv: (42, 7) -> (32, 14)
Esperado EAL-17: 32 filas de categorías/desgloses

,Año,Hoja,Título de tabla,Categoría,TOTAL,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Total,EMPRESAS QUE PROPORCIONAN FORMACIÓN - Impartición de cursos y otros tipos de formación (1),EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo impartición de cursos (1),EMPRESAS QUE PROPORCIONAN FORMACIÓN - Sólo otros tipos de formación (1),EMPRESAS QUE NO PROPORCIONAN FORMACIÓN
0,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",TOTAL,100,73.468,60.220,25.366,14.415,26.532
1,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 5 a 9 trabajadores,100,65.319,51.321,28.014,20.665,34.681
2,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 10 a 49 trabajadores,100,79.228,64.481,25.163,10.356,20.772
3,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 50 a 249 trabajadores,100,94.759,79.559,15.091,5.349,5.241
4,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",De 250 a 499 trabajadores,100,98.371,85.856,11.710,2.434,1.629
5,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Más de 499 trabajadores,100,99.298,88.305,9.742,1.953,0.702
6,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Industria,100,76.222,64.223,20.911,14.866,23.778
7,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Construcción,100,77.713,61.593,29.467,8.940,22.287
8,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comercio y reparación de vehículos,100,73.959,62.349,23.788,13.863,26.041
9,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Transporte y almacenamiento,100,77.405,55.376,34.796,9.828,22.595
10,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Hostelería,100,60.735,42.630,36.362,21.008,39.265
11,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",100,80.544,73.696,13.463,12.840,19.456
12,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Actividades profesionales, científicas y técnicas",100,81.788,66.118,18.706,15.177,18.212
13,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Actividades administrativas y servicios auxiliares,100,74.261,64.392,22.657,12.951,25.739
14,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Actividades artísticas, recreativas y de entretenimiento y otros servicios",100,73.509,62.515,20.437,17.047,26.491
15,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Andalucía,100,73.324,53.315,31.577,15.109,26.676
16,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Aragón,100,73.588,62.546,23.485,13.969,26.412
17,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Asturias (Principado de),100,73.020,55.700,31.219,13.081,26.980
18,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Balears (Illes),100,61.539,61.355,24.875,13.770,38.461
19,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Canarias,100,69.622,58.685,25.936,15.379,30.378
20,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Cantabria,100,71.587,63.019,27.056,9.925,28.413
21,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Castilla-La Mancha,100,73.928,58.307,24.862,16.831,26.072
22,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Castilla y León,100,70.568,55.103,29.104,15.794,29.432
23,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Cataluña,100,76.296,65.436,20.504,14.060,23.704
24,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Comunitat Valenciana,100,74.320,58.492,27.612,13.896,25.680
25,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Extremadura,100,75.343,60.458,25.756,13.786,24.657
26,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Galicia,100,75.145,62.840,21.214,15.946,24.855
27,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Madrid (Comunidad de),100,72.991,62.348,22.853,14.799,27.009
28,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Murcia (Región de),100,76.934,57.263,30.705,12.032,23.066
29,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",Navarra (Comunidad Foral de),100,78.843,62.267,22.001,15.732,21.157
30,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA",País Vasco,100,71.171,64.009,24.950,11.042,28.829
31,2024,EAL-17,"EAL-17. EMPRESAS SEGÚN SI IMPARTIERON FORMACIÓN POR TAMAÑO DE LA EMPRESA, ACTIVIDAD ECONÓMICA Y COMUNIDAD AUTÓNOMA","Rioja, La",100,70.224,62.081,21.054,16.865,29.776

## EAL-18 en formato ancho

In [90]:
# ============================================================
# EAL-18 A FORMATO ANCHO
# ============================================================

df_eal18_ancho = parsear_eal_17_18_ancho("EAL-18", nombres_columnas_eal18)

assert df_eal18_ancho.shape[0] == 32
print("Esperado EAL-18: 32 filas de categorías/desgloses")
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal18_ancho.iloc[:, :10])

EAL-18 desde Equip_31/Data/Processed/EAL/2024/EAL-18.csv: (43, 7) -> (32, 14)
Esperado EAL-18: 32 filas de categorías/desgloses

,Año,Hoja,Título de tabla,Categoría,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (1),DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (1),NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Total,NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - Proporcionaron formación (2),NO DETECTARON NECESIDADES FORMATIVAS DE SU PERSONAL - No proporcionaron formación (2)
0,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,TOTAL,29.123694,89.974511,10.025489,70.876306,66.570590,33.429410
1,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 5 a 9 trabajadores,23.671862,83.544726,16.455274,76.328138,59.481181,40.518819
2,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 10 a 49 trabajadores,31.724690,93.100741,6.899259,68.275310,72.749236,27.250764
3,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 50 a 249 trabajadores,48.701094,98.742720,1.266525,51.298906,90.863612,9.136388
4,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,De 250 a 499 trabajadores,58.708189,100.000000,0.000000,41.253364,96.831314,3.168686
5,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Más de 499 trabajadores,62.753623,99.769053,0.230947,37.246377,98.702983,1.297017
6,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Industria,29.340514,91.943067,8.063373,70.659486,69.761720,30.238280
7,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Construcción,27.053957,90.611641,9.388359,72.946043,73.016647,26.983353
8,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comercio y reparación de vehículos,28.467349,90.868950,9.131050,71.532651,67.384332,32.615668
9,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Transporte y almacenamiento,25.901905,95.031299,4.968701,74.098095,71.218545,28.781455
10,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Hostelería,30.271329,82.452506,17.547494,69.728671,51.019961,48.980039
11,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",32.924543,94.811321,5.188679,67.075457,74.219561,25.780439
12,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Actividades profesionales, científicas y técnicas",33.656148,91.928009,8.071991,66.343852,75.578153,24.421847
13,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Actividades administrativas y servicios auxiliares,28.286468,93.127579,6.872421,71.713532,65.673438,34.326562
14,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",26.601052,89.684569,10.315431,73.398948,67.478218,32.521782
15,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Andalucía,27.268815,88.163346,11.836654,72.731185,67.635602,32.361933
16,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Aragón,29.243477,87.909060,12.090940,70.756523,67.639522,32.346241
17,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Asturias (Principado de),28.940731,88.071895,11.982571,71.059269,66.637090,33.362910
18,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Balears (Illes),24.984561,85.487288,14.512712,75.015439,53.828061,46.183700
19,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Canarias,32.171083,82.749277,17.250723,67.828917,63.228239,36.771761
20,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Cantabria,20.682680,93.031785,6.968215,79.317320,66.050367,33.949633
21,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Castilla-La Mancha,23.509449,91.404199,8.595801,76.490551,68.831300,31.168700
22,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Castilla y León,31.137803,83.291405,16.729560,68.862197,65.039340,34.951180
23,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Cataluña,31.722109,90.311634,9.688366,68.277891,69.361787,30.638213
24,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Comunitat Valenciana,26.022668,94.221709,5.778291,73.977332,66.967668,33.035714
25,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Extremadura,23.936956,88.203018,11.796982,76.063044,71.012303,28.987697
26,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Galicia,26.402254,92.650020,7.349980,73.597746,68.438922,31.568302
27,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Madrid (Comunidad de),35.432441,91.263257,8.736743,64.567559,63.013225,36.986775
28,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Murcia (Región de),23.245159,92.822611,7.177389,76.754841,72.339227,27.672035
29,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,Navarra (Comunidad Foral de),28.000841,96.171171,3.828829,71.999159,72.291971,27.678832
30,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,País Vasco,26.840242,92.489942,7.510058,73.159758,63.698237,36.301763
31,2024,EAL-18,EAL-18. EMPRESAS SEGÚN DETECTARAN O NO NECESIDADES FORMATIVAS DE SU PERSONAL E IMPARTIERAN O NO FORMACIÓN POR TAMAÑO...,"Rioja, La",21.563236,92.349727,7.650273,78.436764,64.346520,35.653480

## EAL-18a, EAL-18b, EAL-18c, EAL-19 y EAL-20 en formato ancho simple

Se continúa con el mismo criterio: una fila por categoría/desglose y las columnas originales de valores. Por ahora no se añaden columnas de ámbito, sector, tamaño empresa ni CCAA al final.

In [91]:
# ============================================================
# FUNCIONES PARA FORMATO ANCHO SIMPLE
# ============================================================

MARCADORES_SECCION = {
    "TAMAÑO DE LA EMPRESA",
    "ACTIVIDAD ECONÓMICA",
    "COMUNIDAD AUTÓNOMA",
}


def titulo_hoja(df, hoja):
    for valor in df.iloc[:, 0].tolist():
        texto = limpiar_texto(valor)
        if texto.upper().startswith(f"{hoja}."):
            return texto
    return ""


def limpiar_nombre_columna(nombre):
    nombre = limpiar_texto(nombre)
    nombre = re.sub(r"\s+", " ", nombre)
    return nombre


def hacer_columnas_unicas_simple(columnas):
    resultado = []
    contador = {}
    for columna in columnas:
        columna = limpiar_nombre_columna(columna) or "SIN_TITULO"
        if columna not in contador:
            contador[columna] = 1
            resultado.append(columna)
        else:
            contador[columna] += 1
            resultado.append(f"{columna}_{contador[columna]}")
    return resultado


def parsear_hoja_ancha_simple(hoja, fila_cabecera, fila_inicio_datos):
    df, ruta_rel = leer_csv_hoja(hoja)
    titulo = titulo_hoja(df, hoja)
    columnas_valor = hacer_columnas_unicas_simple(df.iloc[fila_cabecera, 1:].tolist())

    registros = []
    for _, row in df.iloc[fila_inicio_datos:].iterrows():
        categoria = limpiar_texto(row.iloc[0])
        if categoria == "":
            continue
        if categoria.upper() in MARCADORES_SECCION:
            continue
        if categoria.startswith("("):
            continue

        registro = {
            "Año": ANIO,
            "Hoja": hoja,
            "Título de tabla": titulo,
            "Categoría": categoria,
        }

        for offset, columna in enumerate(columnas_valor, start=1):
            valor = limpiar_texto(row.iloc[offset]) if offset < len(row) else ""
            registro[columna] = pd.to_numeric(valor, errors="coerce")

        # Evita filas sin ningún dato numérico.
        if all(pd.isna(registro[col]) for col in columnas_valor):
            continue

        registros.append(registro)

    df_ancho = pd.DataFrame(registros)
    df_ancho = df_ancho[["Año", "Hoja", "Título de tabla", "Categoría", *columnas_valor]]
    print(f"{hoja} desde {ruta_rel}: {df.shape} -> {df_ancho.shape}")
    return df_ancho

## EAL-18a en formato ancho

EAL-18a: medios utilizados por empresas que proporcionaron formación.

In [92]:
# ============================================================
# EAL-18a A FORMATO ANCHO SIMPLE
# ============================================================

df_eal18a_ancho = parsear_hoja_ancha_simple("EAL-18a", fila_cabecera=4, fila_inicio_datos=5)

print("EAL-18a ancho:", df_eal18a_ancho.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal18a_ancho)

EAL-18a desde Equip_31/Data/Processed/EAL/2024/EAL-18a.csv: (41, 7) -> (32, 10)
EAL-18a ancho: (32, 10)

,Año,Hoja,Título de tabla,Categoría,TOTAL,Cursos de formación diseñados y gestionados por su empresa,Cursos de formación diseñados y gestionados por otra organización,"Formación planificada en el puesto de trabajo, utilizando los medios habituales de trabajo","Aprendizaje planificado a partir de rotación de puestos de trabajo, intercambios, etc.","Participación en conferencias, seminarios, grupos de trabajo, talleres o ferias de muestras"
0,2024,EAL-18a,,TOTAL,73.468278,34.269329,73.709969,56.005492,27.375278,35.086542
1,2024,EAL-18a,,De 5 a 9 trabajadores,65.319423,27.217848,65.989117,51.141371,22.937813,32.188656
2,2024,EAL-18a,,De 10 a 49 trabajadores,79.227905,35.028637,79.002872,57.331022,29.277350,33.998708
3,2024,EAL-18a,,De 50 a 249 trabajadores,94.759353,58.777973,84.135506,70.508861,36.475507,51.399249
4,2024,EAL-18a,,De 250 a 499 trabajadores,98.385236,76.162564,85.384916,76.865963,46.697929,57.796014
5,2024,EAL-18a,,Más de 499 trabajadores,99.275362,85.450122,84.963504,80.048662,51.532847,65.596107
6,2024,EAL-18a,,Industria,76.222600,34.293577,76.121179,61.910901,36.081017,33.867169
7,2024,EAL-18a,,Construcción,77.712290,22.420652,84.768610,57.771672,21.273003,23.030251
8,2024,EAL-18a,,Comercio y reparación de vehículos,73.958727,38.680615,71.445779,54.400700,29.940268,41.624315
9,2024,EAL-18a,,Transporte y almacenamiento,77.406769,30.568829,79.668783,52.052104,24.258690,20.416312
10,2024,EAL-18a,,Hostelería,60.735371,25.970788,68.136490,54.371695,21.531100,13.127676
11,2024,EAL-18a,,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",80.544101,48.577128,73.397606,52.972074,31.788564,63.623670
12,2024,EAL-18a,,"Actividades profesionales, científicas y técnicas",81.788176,42.449776,68.304581,51.031088,25.282718,59.222138
13,2024,EAL-18a,,Actividades administrativas y servicios auxiliares,74.261496,36.374821,74.834256,60.200943,28.282414,39.518830
14,2024,EAL-18a,,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",73.507801,40.519529,67.162337,57.172827,24.520269,43.228235
15,2024,EAL-18a,,Andalucía,73.324726,23.902570,76.823751,47.927417,26.162236,27.756719
16,2024,EAL-18a,,Aragón,73.587186,36.262834,73.538672,54.976044,25.530459,38.644764
17,2024,EAL-18a,,Asturias (Principado de),73.013871,32.340242,74.395509,57.966321,21.200345,32.102763
18,2024,EAL-18a,,Balears (Illes),61.535068,30.394265,72.688172,55.641577,23.412186,36.071685
19,2024,EAL-18a,,Canarias,69.624593,29.797179,71.321259,59.961606,24.021367,28.428345
20,2024,EAL-18a,,Cantabria,71.580278,36.700812,78.205581,53.973861,27.446132,31.755563
21,2024,EAL-18a,,Castilla-La Mancha,73.929811,29.233177,76.306729,55.336463,27.470005,36.765780
22,2024,EAL-18a,,Castilla y León,70.565964,35.078631,70.767808,50.712303,26.938020,36.956522
23,2024,EAL-18a,,Cataluña,76.295600,37.301272,75.365660,58.316773,30.781002,41.250000
24,2024,EAL-18a,,Comunitat Valenciana,74.320098,38.074398,71.119340,55.536105,26.032654,32.280761
25,2024,EAL-18a,,Extremadura,75.340667,32.381783,69.078231,58.008281,33.994334,33.558509
26,2024,EAL-18a,,Galicia,75.144877,26.729871,74.479977,62.975803,27.126079,34.491298
27,2024,EAL-18a,,Madrid (Comunidad de),72.991275,41.842742,71.675800,58.771505,26.178157,38.468204
28,2024,EAL-18a,,Murcia (Región de),76.936376,28.460674,77.696629,53.696629,26.651685,30.617978
29,2024,EAL-18a,,Navarra (Comunidad Foral de),78.852218,35.643828,74.193548,59.877366,29.085577,36.736870
30,2024,EAL-18a,,País Vasco,71.174036,44.731962,69.774107,58.917734,31.507080,36.791976
31,2024,EAL-18a,,"Rioja, La",70.227808,37.863535,70.357942,59.451902,28.859060,36.744966

## EAL-18b en formato ancho

EAL-18b: formación durante suspensión de contrato o reducción de jornada.

In [93]:
# ============================================================
# EAL-18b A FORMATO ANCHO SIMPLE
# ============================================================

df_eal18b_ancho = parsear_hoja_ancha_simple("EAL-18b", fila_cabecera=5, fila_inicio_datos=7)

print("EAL-18b ancho:", df_eal18b_ancho.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal18b_ancho)

EAL-18b desde Equip_31/Data/Processed/EAL/2024/EAL-18b.csv: (41, 9) -> (31, 12)
EAL-18b ancho: (31, 12)

,Año,Hoja,Título de tabla,Categoría,Empresas que realizaron suspensión de contrato/reducción de jornada,Total,El 0'%,Más del 0% hasta el 25%,Más del 25% hasta el 50%,Más del 50% hasta el 75%,Más del 75% hasta el 100%,El 100%
0,2024,EAL-18b,,De 5 a 9 trabajadores,0.763845,100,85.635,9.391,1.418,2.351,0.000,1.206
1,2024,EAL-18b,,De 10 a 49 trabajadores,1.563983,100,82.378,13.232,0.000,2.052,0.312,2.025
2,2024,EAL-18b,,De 50 a 249 trabajadores,3.367701,100,64.167,23.950,4.927,1.052,1.926,3.978
3,2024,EAL-18b,,De 250 a 499 trabajadores,9.919262,100,69.215,19.402,4.646,0.000,3.834,2.904
4,2024,EAL-18b,,Más de 499 trabajadores,11.787440,100,66.136,26.049,5.791,1.364,0.325,0.334
5,2024,EAL-18b,,Industria,3.526077,100,79.042,12.156,0.385,1.863,0.546,6.008
6,2024,EAL-18b,,Construcción,0.131222,100,84.067,8.563,0.058,5.920,1.391,0.000
7,2024,EAL-18b,,Comercio y reparación de vehículos,0.230648,100,85.276,11.029,1.964,0.000,0.000,1.732
8,2024,EAL-18b,,Transporte y almacenamiento,0.851236,100,82.853,16.628,0.328,0.000,0.191,0.000
9,2024,EAL-18b,,Hostelería,2.805053,100,86.534,13.319,0.128,0.019,0.000,0.000
10,2024,EAL-18b,,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",1.178172,100,73.417,25.752,0.716,0.116,0.000,0.000
11,2024,EAL-18b,,"Actividades profesionales, científicas y técnicas",0.340950,100,66.559,29.363,2.090,0.000,1.988,0.000
12,2024,EAL-18b,,Actividades administrativas y servicios auxiliares,1.405949,100,85.590,9.907,3.315,0.094,1.094,0.000
13,2024,EAL-18b,,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",1.002358,100,68.871,6.066,6.637,12.714,0.063,5.650
14,2024,EAL-18b,,Andalucía,1.949181,100,86.189,8.659,2.918,0.933,0.000,1.301
15,2024,EAL-18b,,Aragón,1.057721,100,94.925,3.531,1.291,0.000,0.253,0.000
16,2024,EAL-18b,,Asturias (Principado de),0.772383,100,83.657,7.451,0.000,0.000,8.892,0.000
17,2024,EAL-18b,,Balears (Illes),0.035289,100,73.093,26.907,0.000,0.000,0.000,0.000
18,2024,EAL-18b,,Canarias,0.331241,100,77.763,22.237,0.000,0.000,0.000,0.000
19,2024,EAL-18b,,Cantabria,1.112516,100,78.692,11.272,0.629,9.408,0.000,0.000
20,2024,EAL-18b,,Castilla-La Mancha,0.462784,100,98.346,1.416,0.239,0.000,0.000,0.000
21,2024,EAL-18b,,Castilla y León,1.103205,100,95.891,3.299,0.000,0.000,0.000,0.810
22,2024,EAL-18b,,Cataluña,1.726961,100,69.010,18.953,0.327,8.934,0.399,2.377
23,2024,EAL-18b,,Comunitat Valenciana,3.052366,100,79.585,19.840,0.112,0.463,0.000,0.000
24,2024,EAL-18b,,Extremadura,1.231325,100,80.051,6.802,0.899,0.000,1.798,10.450
25,2024,EAL-18b,,Galicia,0.818757,100,88.408,10.332,0.420,0.000,0.840,0.000
26,2024,EAL-18b,,Madrid (Comunidad de),0.416721,100,81.248,12.697,3.062,0.160,1.051,1.782
27,2024,EAL-18b,,Murcia (Región de),0.458160,100,93.809,6.046,0.145,0.000,0.000,0.000
28,2024,EAL-18b,,Navarra (Comunidad Foral de),5.339500,100,77.908,4.953,0.000,7.804,0.000,9.335
29,2024,EAL-18b,,País Vasco,1.235827,100,66.394,19.083,0.000,0.000,0.000,14.523
30,2024,EAL-18b,,"Rioja, La",1.099764,100,76.991,11.669,7.139,1.476,2.725,0.000

## EAL-18c en formato ancho

EAL-18c: formación en seguridad y salud laboral.

In [94]:
# ============================================================
# EAL-18c A FORMATO ANCHO SIMPLE
# ============================================================

df_eal18c_ancho = parsear_hoja_ancha_simple("EAL-18c", fila_cabecera=4, fila_inicio_datos=6)

print("EAL-18c ancho:", df_eal18c_ancho.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal18c_ancho)

EAL-18c desde Equip_31/Data/Processed/EAL/2024/EAL-18c.csv: (40, 2) -> (31, 5)
EAL-18c ancho: (31, 5)

,Año,Hoja,Título de tabla,Categoría,PORCENTAJE DE EMPRESAS QUE PROPORCIONARON FORMACIÓN EN SEGURIDAD Y SALUD LABORAL
0,2024,EAL-18c,,De 5 a 9 trabajadores,68.611
1,2024,EAL-18c,,De 10 a 49 trabajadores,81.343
2,2024,EAL-18c,,De 50 a 249 trabajadores,92.156
3,2024,EAL-18c,,De 250 a 499 trabajadores,95.577
4,2024,EAL-18c,,Más de 499 trabajadores,96.501
5,2024,EAL-18c,,Industria,81.214
6,2024,EAL-18c,,Construcción,81.458
7,2024,EAL-18c,,Comercio y reparación de vehículos,74.164
8,2024,EAL-18c,,Transporte y almacenamiento,81.207
9,2024,EAL-18c,,Hostelería,73.552
10,2024,EAL-18c,,"Información, comunicaciones, actividades financieras, de seguros e inmobiliarias",73.552
11,2024,EAL-18c,,"Actividades profesionales, científicas y técnicas",69.610
12,2024,EAL-18c,,Actividades administrativas y servicios auxiliares,75.604
13,2024,EAL-18c,,"Actividades artísticas, recreativas y de entretenimiento y otros servicios",69.206
14,2024,EAL-18c,,Andalucía,76.023
15,2024,EAL-18c,,Aragón,71.581
16,2024,EAL-18c,,Asturias (Principado de),71.816
17,2024,EAL-18c,,Balears (Illes),69.231
18,2024,EAL-18c,,Canarias,78.616
19,2024,EAL-18c,,Cantabria,70.111
20,2024,EAL-18c,,Castilla-La Mancha,80.034
21,2024,EAL-18c,,Castilla y León,68.388
22,2024,EAL-18c,,Cataluña,79.948
23,2024,EAL-18c,,Comunitat Valenciana,81.864
24,2024,EAL-18c,,Extremadura,72.441
25,2024,EAL-18c,,Galicia,73.287
26,2024,EAL-18c,,Madrid (Comunidad de),74.704
27,2024,EAL-18c,,Murcia (Región de),80.108
28,2024,EAL-18c,,Navarra (Comunidad Foral de),67.513
29,2024,EAL-18c,,País Vasco,62.846
30,2024,EAL-18c,,"Rioja, La",69.049

## EAL-19 en formato ancho

EAL-19: empresas que proporcionaron formación por tamaño y sector agregado.

In [95]:
# ============================================================
# EAL-19 A FORMATO ANCHO SIMPLE
# ============================================================

df_eal19_ancho = parsear_hoja_ancha_simple("EAL-19", fila_cabecera=4, fila_inicio_datos=5)

print("EAL-19 ancho:", df_eal19_ancho.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal19_ancho)

EAL-19 desde Equip_31/Data/Processed/EAL/2024/EAL-19.csv: (11, 5) -> (6, 8)
EAL-19 ancho: (6, 8)

,Año,Hoja,Título de tabla,Categoría,TOTAL,INDUSTRIA,CONSTRUCCIÓN,SERVICIOS
0,2024,EAL-19,EAL-19. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,TOTAL,73.468278,76.222600,77.712290,72.148643
1,2024,EAL-19,EAL-19. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,De 5 a 9 trabajadores,65.319423,63.058146,71.260095,64.621839
2,2024,EAL-19,EAL-19. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,De 10 a 49 trabajadores,79.227905,80.668769,83.545151,78.058545
3,2024,EAL-19,EAL-19. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,De 50 a 249 trabajadores,94.759353,97.169168,95.046440,93.740024
4,2024,EAL-19,EAL-19. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,De 250 a 499 trabajadores,98.385236,99.467377,100.000000,97.818599
5,2024,EAL-19,EAL-19. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN SECTOR DE ACTIVIDAD POR TAMAÑO DE LA EMPRESA,Más de 499 trabajadores,99.275362,99.782609,98.717949,99.151436

## EAL-20 en formato ancho

EAL-20: competencias en las que se formó por tamaño de empresa.

In [96]:
# ============================================================
# EAL-20 A FORMATO ANCHO SIMPLE
# ============================================================

df_eal20_ancho = parsear_hoja_ancha_simple("EAL-20", fila_cabecera=4, fila_inicio_datos=5)

print("EAL-20 ancho:", df_eal20_ancho.shape)
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", 120):
    display(df_eal20_ancho)

EAL-20 desde Equip_31/Data/Processed/EAL/2024/EAL-20.csv: (17, 7) -> (11, 10)
EAL-20 ancho: (11, 10)

,Año,Hoja,Título de tabla,Categoría,TOTAL,DE 5 A 9 TRABAJADORES,DE 10 A 49 TRABAJADORES,DE 50 A 249 TRABAJADORES,DE 250 A 499 TRABAJADORES,MÁS DE 499 TRABAJADORES
0,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,De dirección,16.347340,15.343619,15.804993,22.430750,25.322392,30.510949
1,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,De trabajo en equipo,28.494848,29.855895,26.931117,28.578895,34.153966,33.333333
2,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,De atención al público/ trato a clientes,24.530267,27.373940,22.586210,19.846059,21.570926,27.055961
3,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,Administrativas de oficina,17.027644,15.670464,18.738422,15.816981,12.817507,13.333333
4,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,Técnicas específicas del puesto de trabajo,50.838810,48.254094,52.131239,56.943983,55.763970,54.014599
5,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,"De resolución de problemas (localización de problemas o fallos, análisis de sus causas y búsqueda de soluciones)",11.209969,11.767293,10.401264,11.911436,15.787417,13.187348
6,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,En lenguas extranjeras,7.478712,3.941978,7.740614,21.100394,27.471669,27.639903
7,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,Generales de tecnologías de la información,12.666991,11.324888,12.758545,17.261367,21.492771,25.109489
8,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,Profesionales de tecnologías de la información,5.310919,3.812620,5.996873,8.690075,7.854631,12.749392
9,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,Básicas de cálculo y/o comunicación oral o escrita,1.254936,1.059013,1.173541,2.537179,2.110199,2.822384
10,2024,EAL-20,EAL-20. EMPRESAS QUE PROPORCIONARON FORMACIÓN A SUS TRABAJADORES SEGÚN TAMAÑO DE LA EMPRESA POR COMPETENCIAS EN LAS ...,Otras,13.934268,12.640893,14.933123,15.664940,14.146151,11.776156