In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
df = pd.read_csv("data_cleaning_2026_20_04.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       706 non-null    int64
 1   Reason_absence           706 non-null    int64
 2   Month_absence            703 non-null    float64
 3   Day_week                 706 non-null    object
 4   Seasons                  706 non-null    object
 5   Transportation_expense   706 non-null    int64
 6   Distance_Residence_Work  706 non-null    int64
 7   Service_time             706 non-null    int64
 8   Age                      706 non-null    int64
 9   Work_load_Average_day    706 non-null    float64
 10  Hit_target               706 non-null    int64
 11  Disciplinary_failure     706 non-null    int64
 12  Education                706 non-null    int64
 13  Son                      706 non-null    int64
 14  Social_drinker           706 non-null    int64
 15  Social_smoker            706 non-null    int64
 16  Pet                      706 non-null    int64
 17  Weight                   706 non-null    int64
 18  Height                   706 non-null    int64
 19  Body_mass_index          706 non-null    int64
 20  Absenteeism_hours        706 non-null    int64
 21  Disease_flag             663 non-null    object
 22  Reason_absence_mapped    663 non-null    object
 23  Month_absence_mapped     703 non-null    object
 24  Education_mapped         706 non-null    object
dtypes: float64(2), int64(17), object(6)
memory usage: 138.0+ KB

In [6]:
df_clean = df.loc[:, ~df.columns.isin(['Pet', 'Weight', 'Height'])]

In [9]:
df_clean['Month_absence'].unique()

array([11.,  4.,  7.,  3.,  6., 12., 10.,  5.,  8.,  9.,  1.,  2., nan])

In [11]:
df_clean['Month_absence'] = df_clean['Month_absence'].astype('Int64')
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       706 non-null    int64
 1   Reason_absence           706 non-null    int64
 2   Month_absence            703 non-null    Int64
 3   Day_week                 706 non-null    object
 4   Seasons                  706 non-null    object
 5   Transportation_expense   706 non-null    int64
 6   Distance_Residence_Work  706 non-null    int64
 7   Service_time             706 non-null    int64
 8   Age                      706 non-null    int64
 9   Work_load_Average_day    706 non-null    float64
 10  Hit_target               706 non-null    int64
 11  Disciplinary_failure     706 non-null    int64
 12  Education                706 non-null    int64
 13  Son                      706 non-null    int64
 14  Social_drinker           706 non-null    int64
 15  Social_smoker            706 non-null    int64
 16  Body_mass_index          706 non-null    int64
 17  Absenteeism_hours        706 non-null    int64
 18  Disease_flag             663 non-null    object
 19  Reason_absence_mapped    663 non-null    object
 20  Month_absence_mapped     703 non-null    object
 21  Education_mapped         706 non-null    object
dtypes: Int64(1), float64(1), int64(14), object(6)
memory usage: 122.2+ KB

C:\Users\acaro\AppData\Local\Temp\ipykernel_16968\2354035266.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Month_absence'] = df_clean['Month_absence'].astype('Int64')

In [14]:
df_clean[df_clean['Absenteeism_hours'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Body_mass_index,Absenteeism_hours,Disease_flag,Reason_absence_mapped,Month_absence_mapped,Education_mapped
662,36,0,7,Tuesday,summer,118,13,18,50,239.554,...,1,1,1,0,31,0,NaN,NaN,July,high_school
663,20,0,9,Monday,spring,260,50,11,36,241.476,...,1,4,1,0,23,0,NaN,NaN,September,high_school
664,29,0,9,Monday,spring,225,26,9,28,241.476,...,1,1,0,0,24,0,NaN,NaN,September,high_school
665,11,0,9,Tuesday,spring,289,36,13,33,241.476,...,1,2,1,0,30,0,NaN,NaN,September,high_school
666,36,0,9,Tuesday,spring,118,13,18,50,241.476,...,1,1,1,0,31,0,NaN,NaN,September,high_school
667,13,0,9,Wednesday,spring,369,17,12,31,241.476,...,1,3,1,0,25,0,NaN,NaN,September,high_school
668,36,0,10,Wednesday,spring,118,13,18,50,253.465,...,1,1,1,0,31,0,NaN,NaN,October,high_school
669,34,27,1,Monday,autumn,118,10,10,37,308.593,...,1,0,0,0,28,0,Not disease,Physiotherapy,January,high_school
670,2,0,4,Monday,winter,235,29,12,48,326.452,...,1,1,0,1,33,0,NaN,NaN,April,high_school
671,7,0,5,Wednesday,winter,279,5,14,39,378.884,...,1,2,1,1,24,0,NaN,NaN,May,high_school
672,18,0,5,Wednesday,winter,330,16,4,28,378.884,...,2,0,0,0,25,0,NaN,NaN,May,graduate
673,23,0,5,Wednesday,winter,378,49,11,36,378.884,...,1,2,0,1,21,0,NaN,NaN,May,high_school
674,31,0,5,Wednesday,winter,388,15,9,50,378.884,...,1,0,0,0,24,0,NaN,NaN,May,high_school
675,20,0,7,Thursday,summer,260,50,11,36,275.312,...,1,4,1,0,23,0,NaN,NaN,July,high_school
676,5,0,9,Thursday,summer,235,20,13,43,294.217,...,1,1,1,0,38,0,NaN,NaN,September,high_school
677,8,0,9,Tuesday,summer,231,35,14,39,294.217,...,1,2,1,0,35,0,NaN,NaN,September,high_school
678,19,0,9,Tuesday,summer,291,50,12,32,294.217,...,1,0,1,0,23,0,NaN,NaN,September,high_school
679,5,0,9,Thursday,spring,235,20,13,43,294.217,...,1,1,1,0,38,0,NaN,NaN,September,high_school
680,36,0,10,Friday,spring,118,13,18,50,265.017,...,1,1,1,0,31,0,NaN,NaN,October,high_school
681,33,0,10,Friday,spring,248,25,14,47,265.017,...,1,2,0,0,32,0,NaN,NaN,October,high_school
682,5,0,10,Wednesday,spring,235,20,13,43,265.017,...,1,1,1,0,38,0,NaN,NaN,October,high_school
683,5,0,10,Friday,spring,235,20,13,43,265.017,...,1,1,1,0,38,0,NaN,NaN,October,high_school
684,20,0,10,Tuesday,spring,260,50,11,36,265.017,...,1,4,1,0,23,0,NaN,NaN,October,high_school
685,15,0,10,Tuesday,spring,291,31,12,40,265.017,...,1,1,1,0,25,0,NaN,NaN,October,high_school
686,30,0,10,Tuesday,spring,157,27,6,29,265.017,...,1,0,1,1,22,0,NaN,NaN,October,high_school
687,18,0,11,Tuesday,spring,330,16,4,28,284.031,...,2,0,0,0,25,0,NaN,NaN,November,graduate
688,23,0,11,Friday,spring,378,49,11,36,284.031,...,1,2,0,1,21,0,NaN,NaN,November,high_school
689,7,0,11,Tuesday,spring,279,5,14,39,284.031,...,1,2,1,1,24,0,NaN,NaN,November,high_school
690,13,0,3,Wednesday,autumn,369,17,12,31,244.387,...,1,3,1,0,25,0,NaN,NaN,March,high_school
691,1,0,3,Thursday,winter,235,11,14,37,244.387,...,3,1,0,0,29,0,NaN,NaN,March,postgraduate
692,24,0,3,Thursday,winter,246,25,16,41,244.387,...,1,0,1,0,23,0,NaN,NaN,March,high_school
693,36,0,3,Thursday,winter,118,13,18,50,244.387,...,1,1,1,0,31,0,NaN,NaN,March,high_school
694,3,0,6,Friday,winter,179,51,18,38,253.957,...,1,0,1,0,31,0,NaN,NaN,June,high_school
695,28,0,10,Monday,spring,225,26,9,28,284.853,...,1,1,0,0,24,0,NaN,NaN,October,high_school
696,15,0,11,Tuesday,spring,291,31,12,40,268.519,...,1,1,1,0,25,0,NaN,NaN,November,high_school
697,11,0,11,Wednesday,spring,289,36,13,33,268.519,...,1,2,1,0,30,0,NaN,NaN,November,high_school
698,5,0,11,Thursday,spring,235,20,13,43,268.519,...,1,1,1,0,38,0,NaN,NaN,November,high_school
699,36,0,5,Tuesday,winter,118,13,18,50,237.656,...,1,1,1,0,31,0,NaN,NaN,May,high_school
700,23,0,5,Wednesday,winter,378,49,11,36,237.656,...,1,2,0,1,21,0,NaN,NaN,May,high_school
701,2,0,6,Monday,winter,235,29,12,48,275.089,...,1,1,0,1,33,0,NaN,NaN,June,high_school
702,21,0,6,Monday,winter,268,11,8,33,275.089,...,2,0,0,0,25,0,NaN,NaN,June,graduate
703,4,0,<NA>,Tuesday,summer,118,14,13,40,271.219,...,1,1,1,0,34,0,NaN,NaN,NaN,high_school
704,8,0,<NA>,Wednesday,autumn,231,35,14,39,271.219,...,1,2,1,0,35,0,NaN,NaN,NaN,high_school
705,35,0,<NA>,Friday,winter,179,45,14,53,271.219,...,1,1,0,0,25,0,NaN,NaN,NaN,high_school

In [15]:
df_clean[df_clean['Month_absence'].isna()]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Education,Son,Social_drinker,Social_smoker,Body_mass_index,Absenteeism_hours,Disease_flag,Reason_absence_mapped,Month_absence_mapped,Education_mapped
703,4,0,<NA>,Tuesday,summer,118,14,13,40,271.219,...,1,1,1,0,34,0,NaN,NaN,NaN,high_school
704,8,0,<NA>,Wednesday,autumn,231,35,14,39,271.219,...,1,2,1,0,35,0,NaN,NaN,NaN,high_school
705,35,0,<NA>,Friday,winter,179,45,14,53,271.219,...,1,1,0,0,25,0,NaN,NaN,NaN,high_school

Decidimos quitar los valores faltante por el tipo de datos, al no representar un ausencia real por el tipo de dataset.

In [16]:
df_clean = df_clean[df_clean['Absenteeism_hours'] > 0]
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 662 entries, 0 to 661
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       662 non-null    int64
 1   Reason_absence           662 non-null    int64
 2   Month_absence            662 non-null    Int64
 3   Day_week                 662 non-null    object
 4   Seasons                  662 non-null    object
 5   Transportation_expense   662 non-null    int64
 6   Distance_Residence_Work  662 non-null    int64
 7   Service_time             662 non-null    int64
 8   Age                      662 non-null    int64
 9   Work_load_Average_day    662 non-null    float64
 10  Hit_target               662 non-null    int64
 11  Disciplinary_failure     662 non-null    int64
 12  Education                662 non-null    int64
 13  Son                      662 non-null    int64
 14  Social_drinker           662 non-null    int64
 15  Social_smoker            662 non-null    int64
 16  Body_mass_index          662 non-null    int64
 17  Absenteeism_hours        662 non-null    int64
 18  Disease_flag             662 non-null    object
 19  Reason_absence_mapped    662 non-null    object
 20  Month_absence_mapped     662 non-null    object
 21  Education_mapped         662 non-null    object
dtypes: Int64(1), float64(1), int64(14), object(6)
memory usage: 119.6+ KB

In [17]:
df_clean.to_csv("data_transformation_2026_22_04.csv", index=False, encoding="utf-8")