In [2]:
import pandas as pd

In [3]:
input_path = r"data/staySpain_cleaned.pkl"
df = pd.read_pickle(input_path)

In [4]:
pd.set_option("display.max_columns", None)

In [5]:
df.head()

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,NaN,Private room,2,2,1,1.0,"TV,Internet,Wifi,Air conditioning,Elevator,Buz...",400.0,3,365,VERDADERO,7,20,40,130,78,2010-01-02,2017-09-05,97.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,75.0,spain,malaga,2018-07-31
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,C�rmenes,Latina,Private room,1,1,1,1.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Free...",170.0,4,40,VERDADERO,0,0,0,162,33,2014-10-10,2018-07-15,92.0,9.0,9.0,10.0,10.0,8.0,9.0,FALSO,52.0,spain,madrid,2020-01-10
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1,2,2.0,"TV,Internet,Wifi,Air conditioning,Wheelchair a...",990.0,2,120,VERDADERO,26,31,31,270,148,2011-01-05,2019-07-22,98.0,10.0,10.0,10.0,10.0,10.0,10.0,VERDADERO,142.0,spain,sevilla,2019-07-29
3,35379,Double 02 CasanovaRooms Barcelona,Room at a my apartment. Kitchen and 2 bathroom...,152232,l'Antiga Esquerra de l'Eixample,Eixample,Private room,2,2,1,1.0,"TV,Internet,Wifi,Kitchen,Breakfast,Elevator,Bu...",400.0,2,730,VERDADERO,9,23,49,300,292,2012-03-13,2020-01-04,94.0,10.0,9.0,10.0,10.0,10.0,9.0,VERDADERO,306.0,spain,barcelona,2020-01-10
4,35801,Can Torras Farmhouse Studio Suite,Lay in bed & watch sunlight change the mood of...,153805,Quart,NaN,Private room,5,1,2,5.0,"Wifi,Pool,Free parking on premises,Breakfast,P...",900.0,1,180,VERDADERO,0,19,49,312,36,2011-07-08,2018-08-08,97.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,39.0,spain,girona,2019-02-19

# Quina és la puntuació mitjana donada pels usuaris als allotjaments turístics?

In [6]:
avg_rating = df["review_scores_rating"].mean().round(2)

print(f"La puntuació mitjana donada pels usuaris als allotjaments turístics és de {avg_rating}")

La puntuació mitjana donada pels usuaris als allotjaments turístics és de 92.01

# Quin percentatge d'allotjaments tenen una valoració general més gran de 80 a cada ciutat?

In [7]:
import pandas as pd

# Creamos una columna nueva que será TRUE si el review_scores_rating es superior a 80
df["rating_greather_than_80"] = df["review_scores_rating"] > 80

df.head()

,apartment_id,name,description,host_id,neighbourhood_name,neighbourhood_district,room_type,accommodates,bathrooms,bedrooms,beds,amenities_list,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review_date,last_review_date,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,is_instant_bookable,reviews_per_month,country,city,insert_date,rating_greather_than_80
0,11964,A ROOM WITH A VIEW,Private bedroom in our attic apartment. Right ...,45553,Centro,NaN,Private room,2,2,1,1.0,"TV,Internet,Wifi,Air conditioning,Elevator,Buz...",400.0,3,365,VERDADERO,7,20,40,130,78,2010-01-02,2017-09-05,97.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,75.0,spain,malaga,2018-07-31,True
1,21853,Bright and airy room,We have a quiet and sunny room with a good vie...,83531,C�rmenes,Latina,Private room,1,1,1,1.0,"TV,Internet,Wifi,Air conditioning,Kitchen,Free...",170.0,4,40,VERDADERO,0,0,0,162,33,2014-10-10,2018-07-15,92.0,9.0,9.0,10.0,10.0,8.0,9.0,FALSO,52.0,spain,madrid,2020-01-10,True
2,32347,Explore Cultural Sights from a Family-Friendly...,Open French doors and step onto a plant-filled...,139939,San Vicente,Casco Antiguo,Entire home/apt,4,1,2,2.0,"TV,Internet,Wifi,Air conditioning,Wheelchair a...",990.0,2,120,VERDADERO,26,31,31,270,148,2011-01-05,2019-07-22,98.0,10.0,10.0,10.0,10.0,10.0,10.0,VERDADERO,142.0,spain,sevilla,2019-07-29,True
3,35379,Double 02 CasanovaRooms Barcelona,Room at a my apartment. Kitchen and 2 bathroom...,152232,l'Antiga Esquerra de l'Eixample,Eixample,Private room,2,2,1,1.0,"TV,Internet,Wifi,Kitchen,Breakfast,Elevator,Bu...",400.0,2,730,VERDADERO,9,23,49,300,292,2012-03-13,2020-01-04,94.0,10.0,9.0,10.0,10.0,10.0,9.0,VERDADERO,306.0,spain,barcelona,2020-01-10,True
4,35801,Can Torras Farmhouse Studio Suite,Lay in bed & watch sunlight change the mood of...,153805,Quart,NaN,Private room,5,1,2,5.0,"Wifi,Pool,Free parking on premises,Breakfast,P...",900.0,1,180,VERDADERO,0,19,49,312,36,2011-07-08,2018-08-08,97.0,10.0,10.0,10.0,10.0,10.0,10.0,FALSO,39.0,spain,girona,2019-02-19,True

In [8]:
# Agrupamos por ciudad y calculamos el porcentaje
df_grouped = (df.groupby("city")["rating_greather_than_80"].mean() * 100).round(2).reset_index()

df_grouped

        city  rating_greather_than_80
0  barcelona                    72.61
1     girona                    58.43
2     madrid                    78.94
3     malaga                    83.19
4   mallorca                    65.69
5    menorca                    78.26
6    sevilla                    89.74
7   valencia                    86.53

In [9]:
# Ordenamos por porcentaje en orden desc
df_sorted = df_grouped.sort_values(by="rating_greather_than_80", ascending=False).reset_index(drop=True)

In [10]:
# Renombramos la columna
df_sorted = df_sorted.rename(columns={"rating_greather_than_80": "%_rating_greather_than_80"})

df_sorted

        city  %_rating_greather_than_80
0    sevilla                      89.74
1   valencia                      86.53
2     malaga                      83.19
3     madrid                      78.94
4    menorca                      78.26
5  barcelona                      72.61
6   mallorca                      65.69
7     girona                      58.43

In [15]:
def calculate_apartment_ratings_by_city(df):
    """
    Calcula estadísticas de apartamentos por ciudad basadas en puntuaciones de reseñas.
    
    Args:
        df (pandas.DataFrame): DataFrame con columnas 'city', 'apartment_id', 'review_scores_rating'
    
    Returns:
        pandas.DataFrame: DataFrame con las estadísticas por ciudad
    """
    # Filtrar registros con review_scores_rating no nulo
    filtered_df = df[df['review_scores_rating'].notnull()].copy()
    
    # Calcular si el rating es mayor a 80 (después de dividir por 10)
    filtered_df['above_80'] = (filtered_df['review_scores_rating']  > 80).astype(int)
    
    # Agrupar por ciudad y calcular las métricas
    result = (
        filtered_df
        .groupby('city')
        .agg(
            total_apartments=('apartment_id', 'count'),
            apartments_above_80=('above_80', 'sum')
        )
        .assign(
            percentage_above_80=lambda x: (x['apartments_above_80'] / x['total_apartments']) * 100
        )
        .reset_index()
    )
    
    return result


result = calculate_apartment_ratings_by_city(df)
print(result)

        city  total_apartments  apartments_above_80  percentage_above_80
0  barcelona              1695                 1482            87.433628
1     girona               753                  634            84.196547
2     madrid              1192                 1102            92.449664
3     malaga               310                  282            90.967742
4   mallorca               794                  720            90.680101
5    menorca               116                  108            93.103448
6    sevilla               315                  306            97.142857
7   valencia               279                  257            92.114695