In [201]:
import pandas as pd
import re
import os
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
   ---------------------------------------- 0.0/96.6 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/96.6 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/96.6 kB ? eta -:--:--
   ---------------- ----------------------- 41.0/96.6 kB 330.3 kB/s eta 0:00:01
   -------------------------------------- - 92.2/96.6 kB 655.4 kB/s eta 0:00:01
   ---------------------------------------- 96.6/96.6 kB 616.5 kB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\rubit\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [351]:
data_2021 = "TABLAS_EAL_2021.xlsx"

TABLAS COMPETENCIAS

In [352]:
df_20 = pd.read_excel(data_2021, sheet_name="EAL-20", skiprows=7)
df_20 = df_20.rename(columns={'Unnamed: 0': 'Competencias', 'DE 250 A 499 TRABAJADORES':'Empresa de entre 250 y 499 trabajadores' })

In [353]:
# 1. Eliminamos filas donde la columna 'Competencias' sea nula (NaN)
df_20 = df_20.dropna(subset=['Competencias'])

In [354]:
# Elimina cualquier fila que contenga "(1)" en la columna Competencias
df_20 = df_20[~df_20['Competencias'].str.contains("\(1\)", na=False)]

In [355]:
df_20

                                         Competencias      TOTAL  DE 5 A 9 TRABAJADORES  DE 10 A 49 TRABAJADORES  DE 50 A 249 TRABAJADORES  Empresa de entre 250 y 499 trabajadores  MÁS DE 499 TRABAJADORES
0                                        De dirección  18.460771              18.431138                17.875770                 19.890611                                26.426265                29.300196
1                                De trabajo en equipo  25.838363              28.643259                22.900274                 24.819204                                29.440258                31.458470
2            De atención al público/ trato a clientes  20.208615              22.934036                17.154130                 20.783956                                18.353068                27.076521
3                          Administrativas de oficina  18.017760              19.536046                16.876489                 16.675782                                13.078579                11.837802
4          Técnicas específicas del puesto de trabajo  46.677170              43.313441                48.147565                 56.572470                                52.529602                53.564421
5   De resolución de problemas (localización de pr...  11.202205              12.234048                10.323277                  9.595868                                13.024758                14.192283
6                              En lenguas extranjeras   7.862089               4.315011                 8.577627                 19.823762                                30.893434                26.880314
7         Generales de tecnologías de la información   13.936823              12.511610                14.127063                 18.906108                                22.604952                26.095487
8     Profesionales de tecnologías de la información    5.719140               4.996103                 5.734904                  8.392586                                11.410118                13.472858
9   Básicas de cálculo y/o comunicación oral o esc...   1.973054               1.872471                 1.997437                  2.090550                                 3.821313                 3.204709
10                                             Otras   13.931390              12.097403                15.574839                 15.271954                                15.823466                13.865271

In [314]:
# Carga el archivo tal como lo tienes
df_20 = pd.read_excel(data_2021, sheet_name="EAL-20", skiprows=7)

# Imprime cada columna con su número de índice
for i, col in enumerate(df_20.columns):
    print(f"Índice {i}: {col}")

Índice 0: Unnamed: 0
Índice 1: TOTAL
Índice 2: DE 5 A 9 TRABAJADORES
Índice 3: DE 10 A 49 TRABAJADORES
Índice 4: DE 50 A 249 TRABAJADORES
Índice 5: DE 250 A 499 TRABAJADORES
Índice 6: MÁS DE 499 TRABAJADORES

In [177]:
df_21 = pd.read_excel(data_2021, sheet_name="EAL-21", skiprows=7)
df_21 = df_21.rename(columns={'Unnamed: 0': 'Competencias'})

In [178]:
df_21

                                         Competencias      TOTAL  INDUSTRIA  CONSTRUCCIÓN  SERVICIOS
0                                        De dirección  18.460771  18.041518     15.788885  19.073773
1                                De trabajo en equipo  25.838363  22.548318     24.114137  26.983225
2            De atención al público/ trato a clientes  20.208615   7.959914      3.632973  26.405576
3                          Administrativas de oficina  18.017760  15.954188     17.030959  18.718515
4          Técnicas específicas del puesto de trabajo  46.677170  62.705798     65.139873  39.182766
5   De resolución de problemas (localización de pr...  11.202205  13.717967      8.664677  11.060586
6                              En lenguas extranjeras   7.862089   9.191124      1.723238   8.701676
7         Generales de tecnologías de la información   13.936823  11.730852      7.023499  15.801141
8     Profesionales de tecnologías de la información    5.719140   4.612742      2.905632   6.528922
9   Básicas de cálculo y/o comunicación oral o esc...   1.973054   1.165354      0.839239   2.390172
10                                             Otras   13.931390  13.640659     17.348004  13.353417
11                                                NaN        NaN        NaN           NaN        NaN
12  (1) Una empresa puede haber señalado de una a ...        NaN        NaN           NaN        NaN

In [179]:
df_21 = pd.read_excel(data_2021, sheet_name="EAL-21", skiprows=7)
df_21 = df_21.rename(columns={'Unnamed: 0': 'Competencias'})

In [180]:
EAL22 = "TABLAS_EAL_2021.xlsx"
nombre_hoja = "EAL-22"

# 1. Cargar la hoja sin procesar nada (todo como matriz)
df_todo_22 = pd.read_excel(EAL22, sheet_name=nombre_hoja, header=None)

# --- BLOQUE 1 (Líneas 8 a 18 de Excel) ---
# Extraemos nombres de columnas de la fila 7 y datos de la 8 a la 18
cols1_22 = df_todo_22.iloc[7, 0:10].tolist()
df1_22 = df_todo_22.iloc[8:19, 0:10].copy()
df1_22.columns = cols1

# --- BLOQUE 2 (Líneas 21 en adelante) ---
# Extraemos nombres de la fila 20 y datos de la 21 en adelante
cols2_22 = df_todo_22.iloc[20, 0:10].tolist()
df2_22 = df_todo_22.iloc[21:32, 0:10].copy()
df2_22.columns = cols2

# --- FUNCIÓN DE LIMPIEZA PARA EVITAR EL ATTRIBUTEERROR ---
def limpiar_tabla(df):
    # 1. Renombrar la primera columna (que suele ser NaN o Unnamed)
    df.rename(columns={df.columns[0]: 'Competencias'}, inplace=True)
    
    # 2. Limpiar nombres de columnas (convertir a string y quitar espacios)
    df.columns = [str(c).strip() for c in df.columns]
    
    # 3. Limpiar el contenido de la columna 'Competencias' únicamente
    # Usamos .astype(str) antes de .str para evitar errores con valores nulos
    df['Competencias'] = df['Competencias'].astype(str).str.strip()
    
    # 4. Eliminar filas donde la competencia sea 'nan' o esté vacía
    df = df[df['Competencias'] != 'nan'].dropna(subset=['Competencias'])
    return df

# Aplicar limpieza a ambos bloques
df1_22 = limpiar_tabla(df1_22)
df2_22 = limpiar_tabla(df2_22)

# --- UNIÓN FINAL ---
# 'inner' asegura que solo se junten las filas que coinciden en nombre
df_final_EAL22 = pd.merge(df1_22, df2_22, on='Competencias', how='inner')

In [182]:
df_final_EAL22

                                         Competencias      TOTAL  ANDALUCÍA     ARAGÓN ASTURIAS (PRINCIPADO DE) BALEARS (ILLES)   CANARIAS  CANTABRIA CASTILLA-LA MANCHA CASTILLA Y LEÓN   CATALUÑA COMUNITAT VALENCIANA EXTREMADURA    GALICIA MADRID (COMUNIDAD DE) MURCIA (REGIÓN DE) NAVARRA (COMUNIDAD FORAL DE) PAÍS VASCO  RIOJA, LA
0                                        De dirección  18.460771  17.958593  11.767627                14.649147       19.978896  16.075438  17.255622          16.732255       21.749821  21.411396            19.002268   12.858013  14.816714              19.24448           16.80978                    17.270862  18.095135  13.106445
1                                De trabajo en equipo  25.838363  28.708732  18.437603                21.079117       25.782624  27.301302  20.055071          21.614925       30.724311  26.879247            25.333333   27.239488  20.849355             26.398251          23.882986                    20.314637  25.593239  21.361332
2            De atención al público/ trato a clientes  20.208615  20.944011  16.153592                24.350014       20.242701  24.281545  13.400642          21.279697       20.807294    15.3816            21.151927   21.541743  23.865675             21.895689          23.111629                    16.826265  20.738975  18.609703
3                          Administrativas de oficina   18.01776  19.410158  14.316452                 18.73078       15.124868  13.729232   14.41028          15.201866       22.723082  19.798745            14.353741   23.583181   18.51662             18.124083          17.857663                    10.772914  20.153863  18.754526
4          Técnicas específicas del puesto de trabajo   46.67717  40.130345  59.549818                55.381605       48.012663  52.222721   55.71363           56.71185        46.68579  47.004705            49.183673   48.080439  54.533026             39.660286          46.427012                    46.819425  47.394084  53.149891
5   De resolución de problemas (localización de pr...  11.202205   8.442777   5.064548                10.259994        9.708055  11.315671   11.42726          13.321673       12.109415  10.094093            12.380952    13.01036  12.031103             14.301549          13.302285                    15.424077   9.101745   9.703114
6                              En lenguas extranjeras   7.862089   3.380402   4.601125                 5.535365        14.45656   4.827122   4.864617           3.323131         4.49749  11.231051             7.646259    1.919561   5.152525             12.513106           3.172755                     9.712722   10.31531   8.110065
7          Generales de tecnologías de la información  13.936823  14.311576   9.913936                12.328767       12.117482   9.407274  16.062414           11.92246       10.224362  16.194459            11.596372    13.77209  12.321627              16.60825          10.886334                    17.407661  15.949724   15.64084
8      Profesionales de tecnologías de la información    5.71914   4.785886   7.861635                  5.73106        2.638058   2.761563   6.975677           3.906136        4.538469   6.949817             4.671202    6.063376   3.469196               7.63608           7.713579                     5.574555   6.046159   6.806662
9   Básicas de cálculo y/o comunicación oral o esc...   1.973054   1.563477   2.598477                 1.789209        0.967288   2.290076   0.642497           0.743332        1.454769   1.351281              1.85941    2.010969   1.802957              3.349211           0.902343                     1.949384    4.10662   0.724113
10                                              Otras   13.93139  14.890886  16.633565                10.427733       14.139993  14.896722  16.291877          10.727299       15.070177  12.467329            14.185941   13.254113  16.576946             13.891136          13.680687                    16.552668   11.63723  14.916727

Unir tabla competencias

In [183]:
def limpiar_texto(df):
    #Quitar espacios en blanco al principio y al final
    df['Competencias'] = df['Competencias'].str.strip()
    
    return df

# Aplicamos la limpieza a tus tres tablas
df_20 = limpiar_texto(df_20)
df_21 = limpiar_texto(df_21)
df_final_EAL22 = limpiar_texto(df_final_EAL22)

In [184]:
# 1. Tabla de Tamaño: Solo nos interesa la columna de 250-499 y la columna de 'Competencia'
df_tamano_filt = df_20[['Competencias', 'TOTAL', 'DE 250 A 499 TRABAJADORES']]

# 2. Tabla de Sector: Solo nos interesa la columna de 'Servicios'
df_sector_filt = df_21[['Competencias', 'SERVICIOS']]

# 3. Tabla de Comunidades: Filtramos las filas de las 5 comunidades que mencionas
comunidades_interes = [
    'Competencias', 
    'CATALUÑA', 
    'COMUNITAT VALENCIANA', 
    'ANDALUCÍA', 
    'MADRID (COMUNIDAD DE)', 
    'PAÍS VASCO'
]
# Creamos el filtro seleccionando solo esas columnas
df_ccaa_filt = df_final_EAL22[comunidades_interes]

In [185]:
# Unimos la primera con la segunda
df_competencias_final = pd.merge(df_tamano_filt, df_sector_filt, on='Competencias', how='outer')

# Unimos el resultado con la de comunidades
df_competencias_final = pd.merge(df_competencias_final, df_ccaa_filt, on='Competencias', how='outer')

# Resultado: Tendrás una tabla con: 
# Competencias | DE 250 A 499... | SERVICIOS | CATALUÑA | ... etc.
print(df_competencias_final.head())

                                        Competencias      TOTAL  DE 250 A 499 TRABAJADORES  SERVICIOS   CATALUÑA COMUNITAT VALENCIANA  ANDALUCÍA MADRID (COMUNIDAD DE) PAÍS VASCO
0  (1) Una empresa puede haber señalado de una a ...        NaN                        NaN        NaN        NaN                  NaN        NaN                   NaN        NaN
1                         Administrativas de oficina  18.017760                  13.078579  18.718515  19.798745            14.353741  19.410158             18.124083  20.153863
2  Básicas de cálculo y/o comunicación oral o esc...   1.973054                   3.821313   2.390172   1.351281              1.85941   1.563477              3.349211    4.10662
3           De atención al público/ trato a clientes  20.208615                  18.353068  26.405576    15.3816            21.151927  20.944011             21.895689  20.738975
4                                       De dirección  18.460771                  26.426265  19.073773  21.411396            19.002268  17.958593              19.24448  18.095135

In [186]:
# Eliminamos filas donde todas las columnas (excepto 'Competencias') sean NaN
df_competencias_final = df_competencias_final.dropna(how='all', subset=df_competencias_final.columns.difference(['Competencias']))

In [188]:
df_competencias_final

                                         Competencias      TOTAL  DE 250 A 499 TRABAJADORES  SERVICIOS   CATALUÑA COMUNITAT VALENCIANA  ANDALUCÍA MADRID (COMUNIDAD DE) PAÍS VASCO
1                          Administrativas de oficina  18.017760                  13.078579  18.718515  19.798745            14.353741  19.410158             18.124083  20.153863
2   Básicas de cálculo y/o comunicación oral o esc...   1.973054                   3.821313   2.390172   1.351281              1.85941   1.563477              3.349211    4.10662
3            De atención al público/ trato a clientes  20.208615                  18.353068  26.405576    15.3816            21.151927  20.944011             21.895689  20.738975
4                                        De dirección  18.460771                  26.426265  19.073773  21.411396            19.002268  17.958593              19.24448  18.095135
5   De resolución de problemas (localización de pr...  11.202205                  13.024758  11.060586  10.094093            12.380952   8.442777             14.301549   9.101745
6                                De trabajo en equipo  25.838363                  29.440258  26.983225  26.879247            25.333333  28.708732             26.398251  25.593239
7                              En lenguas extranjeras   7.862089                  30.893434   8.701676  11.231051             7.646259   3.380402             12.513106   10.31531
8          Generales de tecnologías de la información  13.936823                  22.604952  15.801141  16.194459            11.596372  14.311576              16.60825  15.949724
9                                               Otras  13.931390                  15.823466  13.353417  12.467329            14.185941  14.890886             13.891136   11.63723
10     Profesionales de tecnologías de la información   5.719140                  11.410118   6.528922   6.949817             4.671202   4.785886               7.63608   6.046159
11         Técnicas específicas del puesto de trabajo  46.677170                  52.529602  39.182766  47.004705            49.183673  40.130345             39.660286  47.394084

In [250]:
import pandas as pd
import os
import re

def limpieza_minimalista(texto):
    if pd.isna(texto): return "nan"
    t = str(texto).strip()
    # 1. Identificar la nota del INE para eliminarla después
    if t.startswith("(1)") or "una empresa puede" in t.lower():
        return "BORRAR_NOTA"
    # 2. Solo quitamos espacios extra y saltos de línea, MANTENEMOS números y puntos
    t = re.sub(r'\s+', ' ', t) 
    return t.strip()

todos_los_años = []

for anio in range(2020, 2025):
    archivo_xlsx = f"TABLAS_EAL_{anio}.xlsx"
    archivo_xls = f"TABLAS_EAL_{anio}.xls"
    archivo = archivo_xlsx if os.path.exists(archivo_xlsx) else archivo_xls if os.path.exists(archivo_xls) else None

    if not archivo: continue

    try:
        print(f"🔄 Procesando {archivo}...")
        df_raw_20 = pd.read_excel(archivo, sheet_name="EAL-20", header=None)
        df_raw_21 = pd.read_excel(archivo, sheet_name="EAL-21", header=None)
        df_raw_22 = pd.read_excel(archivo, sheet_name="EAL-22", header=None)

        # Usamos tu función de búsqueda por keyword
        tab_20 = encontrar_tabla_por_keyword(df_raw_20, "TOTAL")
        tab_21 = encontrar_tabla_por_keyword(df_raw_21, "SERVICIOS")
        b1 = encontrar_tabla_por_keyword(df_raw_22, "ANDALUCÍA")
        b2 = encontrar_tabla_por_keyword(df_raw_22, "VASCO")

        tablas_listas = []
        for t in [tab_20, tab_21, b1, b2]:
            if t.empty: continue
            
            # Normalizar nombres de columnas
            t.columns = [str(c).upper().strip().replace('\n', ' ') for c in t.columns]
            t.columns = ['Competencias'] + list(t.columns[1:])
            
            # LIMPIEZA MÍNIMA: Solo espacios y detectar la nota
            t['Competencias'] = t['Competencias'].apply(limpieza_minimalista)
            
            # ELIMINAR SOLO LA NOTA (1)
            t = t[t['Competencias'] != "BORRAR_NOTA"].copy()
            
            t = t.loc[:, ~t.columns.duplicated()].copy()
            tablas_listas.append(t)

        # UNIR: Al no quitar números, "1. Administrativas" NO se juntará con "Administrativas"
        # Para solucionar los NaNs de 2020, vamos a hacer un truco:
        df_temp = pd.concat(tablas_listas, axis=0, sort=False)
        
        # Creamos una columna auxiliar que ignore los números SOLO para agrupar, 
        # pero mantenemos el nombre original
        df_temp['Key_Union'] = df_temp['Competencias'].str.replace(r'^\d+[\.\s\-]*', '', regex=True).str.lower().str.strip()
        
        # Agrupamos por la Key_Union para rellenar los NaNs, pero conservamos el nombre de la Competencia
        df_anio_final = df_temp.groupby('Key_Union').first().reset_index()
        
        # Restauramos el nombre original y borramos la llave auxiliar
        df_anio_final = df_anio_final.drop(columns=['Key_Union'])

        # Mapeo de columnas (CCAA y Tamaño)
        dicc_mapeo = {
            'CATALUÑA': 'CATA', 'COMUNITAT VALENCIANA': 'VALEN', 'ANDALUCÍA': 'ANDA', 
            'MADRID (COMUNIDAD DE)': 'MADRI', 'PAÍS VASCO': 'VASCO',
            'SERVICIOS': 'SERVICI', 'TOTAL': 'TOTAL', 'DE 250 A 499 TRABAJADORES': '250 A 499'
        }
        
        for estandar, clave in dicc_ccaa.items(): # Usamos tu dicc_ccaa o el mapeo
            for col in df_anio_final.columns:
                if clave in str(col).upper() and col not in ['Competencias', 'Año']:
                    df_anio_final = df_anio_final.rename(columns={col: estandar})

        df_anio_final['Año'] = anio
        cols_finales = ['Competencias', 'Año', 'TOTAL', 'DE 250 A 499 TRABAJADORES', 'SERVICIOS', 
                        'ANDALUCÍA', 'CATALUÑA', 'COMUNITAT VALENCIANA', 'MADRID (COMUNIDAD DE)', 'PAÍS VASCO']
        
        existentes = [c for c in cols_finales if c in df_anio_final.columns]
        todos_los_años.append(df_anio_final[existentes].copy())

    except Exception as e:
        print(f"❌ Error en {anio}: {e}")

# UNIÓN FINAL
df_final = pd.concat(todos_los_años, ignore_index=True)

# Filtro final: solo quitar filas vacías de verdad
df_final = df_final[df_final['Competencias'].str.len() > 3]

print(f"✅ ¡PROCESO COMPLETADO! Filas totales: {len(df_final)}")
display(df_final.sort_values(['Año', 'Competencias']))

🔄 Procesando TABLAS_EAL_2020.xls...
🔄 Procesando TABLAS_EAL_2021.xlsx...
🔄 Procesando TABLAS_EAL_2022.xlsx...
🔄 Procesando TABLAS_EAL_2023.xlsx...
🔄 Procesando TABLAS_EAL_2024.xlsx...
✅ ¡PROCESO COMPLETADO! Filas totales: 56

                                         Competencias   Año      TOTAL  SERVICIOS  ANDALUCÍA   CATALUÑA COMUNITAT VALENCIANA MADRID (COMUNIDAD DE) PAÍS VASCO
0                          Administrativas de oficina  2020  11.114247  11.129611  12.561069   9.156032              9.43293             10.525672  17.405494
1            De atención al público/ trato a clientes  2020  18.633907  23.863803   24.30916  18.531969            15.340667             17.595762  18.370955
2                      De comunicación oral o escrita  2020   1.390927   1.609155   0.557252   1.575984             0.510545              1.479218   2.760403
3                           De cálculo o lingüísticas  2020   0.593872   0.700746   0.431298   0.749675             0.237039              0.101874   0.598314
4                                        De dirección  2020  15.275113  15.581089  18.022901  10.595409            16.981705                    15  13.530052
5   De resolución de problemas (localización de pr...  2020  11.671119  12.245682  10.698473  13.973945             9.220203             16.320293   8.621159
6                                De trabajo en equipo  2020  21.726806   23.00022  22.610687  18.798521            19.005652             29.079055  23.551809
7                              En lenguas extranjeras  2020   9.327614   9.969628   5.496183  13.670743              7.94384             14.747351  10.946424
8          Generales de tecnologías de la información  2020  11.858625  12.731448   13.19084  13.061007             9.894852             12.770986  10.742453
10                                              Otras  2020  16.351858  16.999049  18.416031  21.507347              19.1576             11.454768    10.4161
11     Profesionales de tecnologías de la información  2020   4.751602   5.549254   3.645038   5.850798             4.096517               7.01304   6.173511
12         Técnicas específicas del puesto de trabajo  2020  53.492995  47.535495  43.255725   53.99327            54.099556             55.647922  59.899374
13                         Administrativas de oficina  2021   18.01776  18.718515  19.410158  19.798745            14.353741             18.124083  20.153863
14  Básicas de cálculo y/o comunicación oral o esc...  2021   1.973054   2.390172   1.563477   1.351281              1.85941              3.349211    4.10662
15           De atención al público/ trato a clientes  2021  20.208615  26.405576  20.944011    15.3816            21.151927             21.895689  20.738975
16                                       De dirección  2021  18.460771  19.073773  17.958593  21.411396            19.002268              19.24448  18.095135
17  De resolución de problemas (localización de pr...  2021  11.202205  11.060586   8.442777  10.094093            12.380952             14.301549   9.101745
18                               De trabajo en equipo  2021  25.838363  26.983225  28.708732  26.879247            25.333333             26.398251  25.593239
19                             En lenguas extranjeras  2021   7.862089   8.701676   3.380402  11.231051             7.646259             12.513106   10.31531
20         Generales de tecnologías de la información  2021  13.936823  15.801141  14.311576  16.194459            11.596372              16.60825  15.949724
22                                              Otras  2021   13.93139  13.353417  14.890886  12.467329            14.185941             13.891136   11.63723
23     Profesionales de tecnologías de la información  2021    5.71914   6.528922   4.785886   6.949817             4.671202               7.63608   6.046159
24         Técnicas específicas del puesto de trabajo  2021   46.67717  39.182766  40.130345  47.004705            49.183673             39.660286  47.394084
25                         Administrativas de oficina  2022  15.630854   17.28077  17.418993  14.425582            14.824776              19.06816  13.446953
26  Básicas de cálculo y/o comunicación oral o esc...  2022   1.601394   1.997728   1.975032   1.945542             0.590101              2.200972    1.49014
27           De atención al público/ trato a clientes  2022  23.473645  31.009624  29.271988  23.972603            21.135241             25.195541  17.453377
28                                       De dirección  2022  13.528077  14.900472  13.791556  13.059921            13.724861             17.272562  11.135897
29  De resolución de problemas (localización de pr...  2022  11.690936    12.0856   9.833076  11.681654            12.484445             14.060754  10.377443
30                               De trabajo en equipo  2022  24.281499  27.229362  25.911067  26.491722            22.580386             27.225008   17.04292
31                             En lenguas extranjeras  2022    8.89439  10.159603  10.713985   9.969325             8.819397             13.473482   7.584545
32         Generales de tecnologías de la información  2022  12.004142  13.186682  10.542853  14.135642            10.208342             16.282514  12.349424
34                                              Otras  2022  19.598136  18.458366  20.165521  17.318682            19.204368             19.304628  26.242527
35     Profesionales de tecnologías de la información  2022   5.492479   6.321358    6.05695   6.422809             3.267633              8.019125   6.397787
36         Técnicas específicas del puesto de trabajo  2022  41.638777   33.12571  38.013747  42.137995            47.589418             31.608762  41.465156
37                         Administrativas de oficina  2023  15.404153  16.434234  15.416156  17.460612             17.02492             14.620863  11.141237
38  Básicas de cálculo y/o comunicación oral o esc...  2023   1.914212   2.258273   1.080081   2.530314             3.638461              2.704755   0.517624
39           De atención al público/ trato a clientes  2023  21.546538  27.663706  21.496612  20.386868            19.730174             27.010892  17.804618
40                                       De dirección  2023  11.720302  11.605946  12.363427  11.366823              9.99965             13.636364  13.680059
41  De resolución de problemas (localización de pr...  2023   12.08924  13.872169  11.130835  14.394127            14.532872             11.232719  11.461671
42                               De trabajo en equipo  2023  25.101616  27.323574  28.229617  26.903407            27.108455             25.665061  23.186262
43                             En lenguas extranjeras  2023   8.198405   9.121675   4.720354  11.183288             9.464891             13.890344   8.495604
44         Generales de tecnologías de la información  2023  12.247244  12.771708    9.20069  12.952652            11.974415             18.857352  12.981678
46                                              Otras  2023   18.89761  18.121834  20.809061  20.403366            16.626472             15.532049  16.128502
47     Profesionales de tecnologías de la información  2023   6.125399   7.415336   4.812861    6.82793             5.854392             11.855886   4.527155
48         Técnicas específicas del puesto de trabajo  2023  41.047326  33.401095  36.450234   39.38794            42.399776             36.554776  49.338592
49                         Administrativas de oficina  2024  17.027644  16.994533  19.549534  15.007949            15.704427             15.478527  16.672286
50  Básicas de cálculo y/o comunicación oral o esc...  2024   1.254936    1.26618   0.819251   1.222178             1.255681              1.801963   0.134862
51           De atención al público/ trato a clientes  2024  24.530267  31.456162  25.978822   27.00318            26.110082             23.626864  25.429872
52                                       De dirección  2024   16.34734  16.439153  17.531975  16.399046            13.011278             17.451255  16.410991
53  De resolución de problemas (localización de pr...  2024  11.209969  10.889696  14.668264   9.848967             8.769567             11.076845  13.393459
54                               De trabajo en equipo  2024  28.494848  30.078036  27.035289  28.994436            28.840263             28.918058  21.813891
55                             En lenguas extranjeras  2024   7.478712   8.258975   5.536671  10.260334             5.975425             10.951956  10.510789
56         Generales de tecnologías de la información  2024  12.666991  13.841581   9.764985  16.289746            11.085676             17.257551   9.794336
58                                              Otras  2024  13.934268   13.40195  14.929936   11.56399            16.599899             13.110743  11.126096
59     Profesionales de tecnologías de la información  2024   5.310919   5.807584   4.460639    5.93601             3.430399              7.809354   7.021241
60         Técnicas específicas del puesto de trabajo  2024   50.83881  44.985817  46.910078   50.29213            51.873422             49.878935  55.824343

In [362]:
def limpieza_minimalista(texto):
    if pd.isna(texto): return "nan"
    t = str(texto).strip()
    if t.startswith("(1)") or "una empresa puede" in t.lower():
        return "BORRAR_NOTA"
    t = re.sub(r'\s+', ' ', t)
    return t.strip()

todos_los_años = []

dicc_mapeo = {
    'CATALUÑA': 'CATA', 'COMUNITAT VALENCIANA': 'VALEN', 'ANDALUCÍA': 'ANDA', 
    'MADRID (COMUNIDAD DE)': 'MADRI', 'PAÍS VASCO': 'VASCO',
    'SERVICIOS': 'SERVICI', 'TOTAL': 'TOTAL'
}

for anio in range(2020, 2025):
    archivo_xlsx = f"TABLAS_EAL_{anio}.xlsx"
    archivo_xls = f"TABLAS_EAL_{anio}.xls"
    archivo = archivo_xlsx if os.path.exists(archivo_xlsx) else archivo_xls if os.path.exists(archivo_xls) else None

    if not archivo: continue

    try:
        print(f"🔄 Procesando {archivo}...")
        df_raw_20 = pd.read_excel(archivo, sheet_name="EAL-20", header=None)
        df_raw_21 = pd.read_excel(archivo, sheet_name="EAL-21", header=None)
        df_raw_22 = pd.read_excel(archivo, sheet_name="EAL-22", header=None)

        tab_20 = encontrar_tabla_por_keyword(df_raw_20, "TOTAL")
        tab_21 = encontrar_tabla_por_keyword(df_raw_21, "SERVICIOS")
        b1 = encontrar_tabla_por_keyword(df_raw_22, "ANDALUCÍA")
        b2 = encontrar_tabla_por_keyword(df_raw_22, "VASCO")

        tablas_listas = []
        for i, t in enumerate([tab_20, tab_21, b1, b2]):
            if t.empty: continue
            
            # --- CORRECCIÓN CLAVE: Renombrar Índice 5 ANTES de limpiar columnas ---
            # Solo lo hacemos para la primera tabla (tab_20) que es la que tiene los tamaños
            if i == 0 and len(t.columns) >= 6:
                # Forzamos el nombre en el índice 5
                cols = list(t.columns)
                cols[5] = 'DE 250 A 499 TRABAJADORES'
                t.columns = cols

            # Limpiar nombres de columnas para que sean strings comparables
            t.columns = [str(c).upper().strip().replace('\n', ' ') for c in t.columns]
            
            # Asegurar que la primera columna siempre sea Competencias
            # (Pero mantenemos los nombres que acabamos de poner arriba)
            nombres_finales = ['Competencias'] + list(t.columns[1:])
            t.columns = nombres_finales
            
            # Limpieza de filas
            t['Competencias'] = t['Competencias'].apply(limpieza_minimalista)
            t = t[t['Competencias'] != "BORRAR_NOTA"].copy()
            
            # Crear clave de unión (normalización del texto de la competencia)
            t['Comp_Norm'] = t['Competencias'].str.replace(r'^\d+[\.\s\-]*', '', regex=True).str.strip()
            
            # Eliminar duplicados de columnas
            t = t.loc[:, ~t.columns.duplicated()].copy()
            tablas_listas.append(t)

        # Unir todas las tablas (Total, Servicios, CCAA)
        df_temp = pd.concat(tablas_listas, axis=0, sort=False)
        
        # Agrupar por el nombre normalizado para "rellenar" los huecos entre tablas
        df_anio_final = df_temp.groupby('Comp_Norm', as_index=False).first()
        df_anio_final = df_anio_final.drop(columns=['Comp_Norm'])

        # Renombrar según el diccionario de mapeo (Comunidades y Total)
        for estandar, clave in dicc_mapeo.items():
            for col in df_anio_final.columns:
                # Evitamos renombrar la de trabajadores por error
                if clave in str(col).upper() and col not in ['Competencias', 'DE 250 A 499 TRABAJADORES']:
                    df_anio_final = df_anio_final.rename(columns={col: estandar})

        df_anio_final['Año'] = anio
        
        cols_finales = ['Competencias', 'Año', 'TOTAL', 'DE 250 A 499 TRABAJADORES', 'SERVICIOS', 
                        'ANDALUCÍA', 'CATALUÑA', 'COMUNITAT VALENCIANA', 'MADRID (COMUNIDAD DE)', 'PAÍS VASCO']
        
        # Forzar que existan todas, si no existen se crean como None
        for c in cols_finales:
            if c not in df_anio_final.columns:
                df_anio_final[c] = None

        todos_los_años.append(df_anio_final[cols_finales].copy())

    except Exception as e:
        print(f"❌ Error en {anio}: {e}")

# Consolidación final de todos los años
if todos_los_años:
    df_final = pd.concat(todos_los_años, ignore_index=True)
    df_final = df_final[df_final['Competencias'].astype(str).str.len() > 3]
    display(df_final.sort_values(['Año', 'Competencias']))

🔄 Procesando TABLAS_EAL_2020.xls...
🔄 Procesando TABLAS_EAL_2021.xlsx...
🔄 Procesando TABLAS_EAL_2022.xlsx...
🔄 Procesando TABLAS_EAL_2023.xlsx...
🔄 Procesando TABLAS_EAL_2024.xlsx...

                                         Competencias   Año      TOTAL DE 250 A 499 TRABAJADORES  SERVICIOS  ANDALUCÍA   CATALUÑA COMUNITAT VALENCIANA MADRID (COMUNIDAD DE) PAÍS VASCO
0                          Administrativas de oficina  2020  11.114247                 10.057322  11.129611  12.561069   9.156032              9.43293             10.525672  17.405494
1            De atención al público/ trato a clientes  2020  18.633907                 18.603439  23.863803   24.30916  18.531969            15.340667             17.595762  18.370955
2                      De comunicación oral o escrita  2020   1.390927                  3.387181   1.609155   0.557252   1.575984             0.510545              1.479218   2.760403
3                           De cálculo o lingüísticas  2020   0.593872                  1.354872   0.700746   0.431298   0.749675             0.237039              0.101874   0.598314
4                                        De dirección  2020  15.275113                  23.03283  15.581089  18.022901  10.595409            16.981705                    15  13.530052
5   De resolución de problemas (localización de pr...  2020  11.671119                 13.757165  12.245682  10.698473  13.973945             9.220203             16.320293   8.621159
6                                De trabajo en equipo  2020  21.726806                 22.928609   23.00022  22.610687  18.798521            19.005652             29.079055  23.551809
7                              En lenguas extranjeras  2020   9.327614                 29.963523   9.969628   5.496183  13.670743              7.94384             14.747351  10.946424
8          Generales de tecnologías de la información  2020  11.858625                 22.355393  12.731448   13.19084  13.061007             9.894852             12.770986  10.742453
9                                               Otras  2020  16.351858                 13.913497  16.999049  18.416031  21.507347              19.1576             11.454768    10.4161
10     Profesionales de tecnologías de la información  2020   4.751602                 10.369984   5.549254   3.645038   5.850798             4.096517               7.01304   6.173511
11         Técnicas específicas del puesto de trabajo  2020  53.492995                 62.793121  47.535495  43.255725   53.99327            54.099556             55.647922  59.899374
13                         Administrativas de oficina  2021   18.01776                 13.078579  18.718515  19.410158  19.798745            14.353741             18.124083  20.153863
14  Básicas de cálculo y/o comunicación oral o esc...  2021   1.973054                  3.821313   2.390172   1.563477   1.351281              1.85941              3.349211    4.10662
15           De atención al público/ trato a clientes  2021  20.208615                 18.353068  26.405576  20.944011    15.3816            21.151927             21.895689  20.738975
16                                       De dirección  2021  18.460771                 26.426265  19.073773  17.958593  21.411396            19.002268              19.24448  18.095135
17  De resolución de problemas (localización de pr...  2021  11.202205                 13.024758  11.060586   8.442777  10.094093            12.380952             14.301549   9.101745
18                               De trabajo en equipo  2021  25.838363                 29.440258  26.983225  28.708732  26.879247            25.333333             26.398251  25.593239
19                             En lenguas extranjeras  2021   7.862089                 30.893434   8.701676   3.380402  11.231051             7.646259             12.513106   10.31531
20         Generales de tecnologías de la información  2021  13.936823                 22.604952  15.801141  14.311576  16.194459            11.596372              16.60825  15.949724
21                                              Otras  2021   13.93139                 15.823466  13.353417  14.890886  12.467329            14.185941             13.891136   11.63723
22     Profesionales de tecnologías de la información  2021    5.71914                 11.410118   6.528922   4.785886   6.949817             4.671202               7.63608   6.046159
23         Técnicas específicas del puesto de trabajo  2021   46.67717                 52.529602  39.182766  40.130345  47.004705            49.183673             39.660286  47.394084
25                         Administrativas de oficina  2022  15.630854                 11.715089   17.28077  17.418993  14.425582            14.824776              19.06816  13.446953
26  Básicas de cálculo y/o comunicación oral o esc...  2022   1.601394                  4.404873   1.997728   1.975032   1.945542             0.590101              2.200972    1.49014
27           De atención al público/ trato a clientes  2022  23.473645                 18.134958  31.009624  29.271988  23.972603            21.135241             25.195541  17.453377
28                                       De dirección  2022  13.528077                 24.226804  14.900472  13.791556  13.059921            13.724861             17.272562  11.135897
29  De resolución de problemas (localización de pr...  2022  11.690936                 15.557638    12.0856   9.833076  11.681654            12.484445             14.060754  10.377443
30                               De trabajo en equipo  2022  24.281499                 29.053421  27.229362  25.911067  26.491722            22.580386             27.225008   17.04292
31                             En lenguas extranjeras  2022    8.89439                 28.865979  10.159603  10.713985   9.969325             8.819397             13.473482   7.584545
32         Generales de tecnologías de la información  2022  12.004142                 20.899719  13.186682  10.542853  14.135642            10.208342             16.282514  12.349424
33                                              Otras  2022  19.598136                 13.870665  18.458366  20.165521  17.318682            19.204368             19.304628  26.242527
34     Profesionales de tecnologías de la información  2022   5.492479                  8.200562   6.321358    6.05695   6.422809             3.267633              8.019125   6.397787
35         Técnicas específicas del puesto de trabajo  2022  41.638777                 53.608247   33.12571  38.013747  42.137995            47.589418             31.608762  41.465156
37                         Administrativas de oficina  2023  15.404153                 14.250715  16.434234  15.416156  17.460612             17.02492             14.620863  11.141237
38  Básicas de cálculo y/o comunicación oral o esc...  2023   1.914212                  4.001633   2.258273   1.080081   2.530314             3.638461              2.704755   0.517624
39           De atención al público/ trato a clientes  2023  21.546538                    20.049  27.663706  21.496612  20.386868            19.730174             27.010892  17.804618
40                                       De dirección  2023  11.720302                 19.844835  11.605946  12.363427  11.366823              9.99965             13.636364  13.680059
41  De resolución de problemas (localización de pr...  2023   12.08924                 13.719886  13.872169  11.130835  14.394127            14.532872             11.232719  11.461671
42                               De trabajo en equipo  2023  25.101616                 28.460596  27.323574  28.229617  26.903407            27.108455             25.665061  23.186262
43                             En lenguas extranjeras  2023   8.198405                 29.236423   9.121675   4.720354  11.183288             9.464891             13.890344   8.495604
44         Generales de tecnologías de la información  2023  12.247244                 19.926501  12.771708    9.20069  12.952652            11.974415             18.857352  12.981678
45                                              Otras  2023   18.89761                 15.067374  18.121834  20.809061  20.403366            16.626472             15.532049  16.128502
46     Profesionales de tecnologías de la información  2023   6.125399                  8.697428   7.415336   4.812861    6.82793             5.854392             11.855886   4.527155
47         Técnicas específicas del puesto de trabajo  2023  41.047326                 45.773785  33.401095  36.450234   39.38794            42.399776             36.554776  49.338592
49                         Administrativas de oficina  2024  17.027644                 12.817507  16.994533  19.549534  15.007949            15.704427             15.478527  16.672286
50  Básicas de cálculo y/o comunicación oral o esc...  2024   1.254936                  2.110199    1.26618   0.819251   1.222178             1.255681              1.801963   0.134862
51           De atención al público/ trato a clientes  2024  24.530267                 21.570926  31.456162  25.978822   27.00318            26.110082             23.626864  25.429872
52                                       De dirección  2024   16.34734                 25.322392  16.439153  17.531975  16.399046            13.011278             17.451255  16.410991
53  De resolución de problemas (localización de pr...  2024  11.209969                 15.787417  10.889696  14.668264   9.848967             8.769567             11.076845  13.393459
54                               De trabajo en equipo  2024  28.494848                 34.153966  30.078036  27.035289  28.994436            28.840263             28.918058  21.813891
55                             En lenguas extranjeras  2024   7.478712                 27.471669   8.258975   5.536671  10.260334             5.975425             10.951956  10.510789
56         Generales de tecnologías de la información  2024  12.666991                 21.492771  13.841581   9.764985  16.289746            11.085676             17.257551   9.794336
57                                              Otras  2024  13.934268                 14.146151   13.40195  14.929936   11.56399            16.599899             13.110743  11.126096
58     Profesionales de tecnologías de la información  2024   5.310919                  7.854631   5.807584   4.460639    5.93601             3.430399              7.809354   7.021241
59         Técnicas específicas del puesto de trabajo  2024   50.83881                  55.76397  44.985817  46.910078   50.29213            51.873422             49.878935  55.824343

In [365]:
df_final = df_final.rename(columns={'TOTAL': 'Total empresas (sin filtrar)', 'DE 250 A 499 TRABAJADORES':'Empresa de entre 250 y 499 trabajadores', 'AÑO': 'Año', 'MADRID (COMUNIDAD DE)': 'Comunidad de Madrid', "ANDALUCÍA" : "Andalucía", "CATALUÑA" : "Cataluña", "COMUNITAT VALENCIANA" : "Comunitat Valenciana", "PAÍS VASCO" : "País Vasco", "SERVICIOS" : "Empresa de servicios" })

In [366]:
df_final

                                         Competencias   Año Total empresas (sin filtrar) Empresa de entre 250 y 499 trabajadores Empresa de servicios  Andalucía   Cataluña Comunitat Valenciana Comunidad de Madrid País Vasco
0                          Administrativas de oficina  2020                    11.114247                               10.057322            11.129611  12.561069   9.156032              9.43293           10.525672  17.405494
1            De atención al público/ trato a clientes  2020                    18.633907                               18.603439            23.863803   24.30916  18.531969            15.340667           17.595762  18.370955
2                      De comunicación oral o escrita  2020                     1.390927                                3.387181             1.609155   0.557252   1.575984             0.510545            1.479218   2.760403
3                           De cálculo o lingüísticas  2020                     0.593872                                1.354872             0.700746   0.431298   0.749675             0.237039            0.101874   0.598314
4                                        De dirección  2020                    15.275113                                23.03283            15.581089  18.022901  10.595409            16.981705                  15  13.530052
5   De resolución de problemas (localización de pr...  2020                    11.671119                               13.757165            12.245682  10.698473  13.973945             9.220203           16.320293   8.621159
6                                De trabajo en equipo  2020                    21.726806                               22.928609             23.00022  22.610687  18.798521            19.005652           29.079055  23.551809
7                              En lenguas extranjeras  2020                     9.327614                               29.963523             9.969628   5.496183  13.670743              7.94384           14.747351  10.946424
8          Generales de tecnologías de la información  2020                    11.858625                               22.355393            12.731448   13.19084  13.061007             9.894852           12.770986  10.742453
9                                               Otras  2020                    16.351858                               13.913497            16.999049  18.416031  21.507347              19.1576           11.454768    10.4161
10     Profesionales de tecnologías de la información  2020                     4.751602                               10.369984             5.549254   3.645038   5.850798             4.096517             7.01304   6.173511
11         Técnicas específicas del puesto de trabajo  2020                    53.492995                               62.793121            47.535495  43.255725   53.99327            54.099556           55.647922  59.899374
13                         Administrativas de oficina  2021                     18.01776                               13.078579            18.718515  19.410158  19.798745            14.353741           18.124083  20.153863
14  Básicas de cálculo y/o comunicación oral o esc...  2021                     1.973054                                3.821313             2.390172   1.563477   1.351281              1.85941            3.349211    4.10662
15           De atención al público/ trato a clientes  2021                    20.208615                               18.353068            26.405576  20.944011    15.3816            21.151927           21.895689  20.738975
16                                       De dirección  2021                    18.460771                               26.426265            19.073773  17.958593  21.411396            19.002268            19.24448  18.095135
17  De resolución de problemas (localización de pr...  2021                    11.202205                               13.024758            11.060586   8.442777  10.094093            12.380952           14.301549   9.101745
18                               De trabajo en equipo  2021                    25.838363                               29.440258            26.983225  28.708732  26.879247            25.333333           26.398251  25.593239
19                             En lenguas extranjeras  2021                     7.862089                               30.893434             8.701676   3.380402  11.231051             7.646259           12.513106   10.31531
20         Generales de tecnologías de la información  2021                    13.936823                               22.604952            15.801141  14.311576  16.194459            11.596372            16.60825  15.949724
21                                              Otras  2021                     13.93139                               15.823466            13.353417  14.890886  12.467329            14.185941           13.891136   11.63723
22     Profesionales de tecnologías de la información  2021                      5.71914                               11.410118             6.528922   4.785886   6.949817             4.671202             7.63608   6.046159
23         Técnicas específicas del puesto de trabajo  2021                     46.67717                               52.529602            39.182766  40.130345  47.004705            49.183673           39.660286  47.394084
25                         Administrativas de oficina  2022                    15.630854                               11.715089             17.28077  17.418993  14.425582            14.824776            19.06816  13.446953
26  Básicas de cálculo y/o comunicación oral o esc...  2022                     1.601394                                4.404873             1.997728   1.975032   1.945542             0.590101            2.200972    1.49014
27           De atención al público/ trato a clientes  2022                    23.473645                               18.134958            31.009624  29.271988  23.972603            21.135241           25.195541  17.453377
28                                       De dirección  2022                    13.528077                               24.226804            14.900472  13.791556  13.059921            13.724861           17.272562  11.135897
29  De resolución de problemas (localización de pr...  2022                    11.690936                               15.557638              12.0856   9.833076  11.681654            12.484445           14.060754  10.377443
30                               De trabajo en equipo  2022                    24.281499                               29.053421            27.229362  25.911067  26.491722            22.580386           27.225008   17.04292
31                             En lenguas extranjeras  2022                      8.89439                               28.865979            10.159603  10.713985   9.969325             8.819397           13.473482   7.584545
32         Generales de tecnologías de la información  2022                    12.004142                               20.899719            13.186682  10.542853  14.135642            10.208342           16.282514  12.349424
33                                              Otras  2022                    19.598136                               13.870665            18.458366  20.165521  17.318682            19.204368           19.304628  26.242527
34     Profesionales de tecnologías de la información  2022                     5.492479                                8.200562             6.321358    6.05695   6.422809             3.267633            8.019125   6.397787
35         Técnicas específicas del puesto de trabajo  2022                    41.638777                               53.608247             33.12571  38.013747  42.137995            47.589418           31.608762  41.465156
37                         Administrativas de oficina  2023                    15.404153                               14.250715            16.434234  15.416156  17.460612             17.02492           14.620863  11.141237
38  Básicas de cálculo y/o comunicación oral o esc...  2023                     1.914212                                4.001633             2.258273   1.080081   2.530314             3.638461            2.704755   0.517624
39           De atención al público/ trato a clientes  2023                    21.546538                                  20.049            27.663706  21.496612  20.386868            19.730174           27.010892  17.804618
40                                       De dirección  2023                    11.720302                               19.844835            11.605946  12.363427  11.366823              9.99965           13.636364  13.680059
41  De resolución de problemas (localización de pr...  2023                     12.08924                               13.719886            13.872169  11.130835  14.394127            14.532872           11.232719  11.461671
42                               De trabajo en equipo  2023                    25.101616                               28.460596            27.323574  28.229617  26.903407            27.108455           25.665061  23.186262
43                             En lenguas extranjeras  2023                     8.198405                               29.236423             9.121675   4.720354  11.183288             9.464891           13.890344   8.495604
44         Generales de tecnologías de la información  2023                    12.247244                               19.926501            12.771708    9.20069  12.952652            11.974415           18.857352  12.981678
45                                              Otras  2023                     18.89761                               15.067374            18.121834  20.809061  20.403366            16.626472           15.532049  16.128502
46     Profesionales de tecnologías de la información  2023                     6.125399                                8.697428             7.415336   4.812861    6.82793             5.854392           11.855886   4.527155
47         Técnicas específicas del puesto de trabajo  2023                    41.047326                               45.773785            33.401095  36.450234   39.38794            42.399776           36.554776  49.338592
49                         Administrativas de oficina  2024                    17.027644                               12.817507            16.994533  19.549534  15.007949            15.704427           15.478527  16.672286
50  Básicas de cálculo y/o comunicación oral o esc...  2024                     1.254936                                2.110199              1.26618   0.819251   1.222178             1.255681            1.801963   0.134862
51           De atención al público/ trato a clientes  2024                    24.530267                               21.570926            31.456162  25.978822   27.00318            26.110082           23.626864  25.429872
52                                       De dirección  2024                     16.34734                               25.322392            16.439153  17.531975  16.399046            13.011278           17.451255  16.410991
53  De resolución de problemas (localización de pr...  2024                    11.209969                               15.787417            10.889696  14.668264   9.848967             8.769567           11.076845  13.393459
54                               De trabajo en equipo  2024                    28.494848                               34.153966            30.078036  27.035289  28.994436            28.840263           28.918058  21.813891
55                             En lenguas extranjeras  2024                     7.478712                               27.471669             8.258975   5.536671  10.260334             5.975425           10.951956  10.510789
56         Generales de tecnologías de la información  2024                    12.666991                               21.492771            13.841581   9.764985  16.289746            11.085676           17.257551   9.794336
57                                              Otras  2024                    13.934268                               14.146151             13.40195  14.929936   11.56399            16.599899           13.110743  11.126096
58     Profesionales de tecnologías de la información  2024                     5.310919                                7.854631             5.807584   4.460639    5.93601             3.430399            7.809354   7.021241
59         Técnicas específicas del puesto de trabajo  2024                     50.83881                                55.76397            44.985817  46.910078   50.29213            51.873422           49.878935  55.824343