## PORCENTAJE DE EMPRESAS QUE NO PROPORCIONAN FORMACIÓN A SUS TRABAJADORES

# ¿Cuánto influyó ese motivo en la decisión de NO dar formación?

# 2020

In [51]:
import pandas as pd

df_25_2020 = pd.read_excel(
    r"C:\Users\crist\Documents\SIMULADOR\SPRINT4\TABLAS_EAL_2020.xlsx",
    sheet_name="EAL-25"
)

df_25_2020

,ENCUESTA ANUAL LABORAL,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,EAL
0,NaN,NaN,NaN,NaN,NaN,Volver al índice
1,NaN,NaN,NaN,NaN,NaN,NaN
2,EAL-25. EMPRESAS QUE NO PROPORCIONARON FORMACI...,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Año 2020. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
5,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
6,El nivel de formación de los empleados era el ...,100,10.844,6.873,48.706,33.577
7,La estrategia preferida de la empresa fue cont...,100,36.612,12.757,33.864,16.768
8,Dificultad para evaluar la necesidades de form...,100,47.492,36.964,13.09,2.454
9,La falta de cursos de formación adecuados en e...,100,41.245,30.356,20.72,7.68
10,El alto coste de los cursos de formación,100,39.785,27.504,24.127,8.584
11,El mayor esfuerzo realizado en años anteriores...,100,51.816,24.652,19.63,3.901
12,La elevada carga de trabajo y el escaso tiempo...,100,34.268,22.458,30.101,13.172
13,Dificultad para acceder a ayudas o subvencione...,100,41.162,27.661,21.691,9.486
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN
17,EAL-25a. EMPRESAS DE 5 A 49 TRABAJADORES QUE N...,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,Año 2020. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
20,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
21,El nivel de formación de los empleados era el ...,100,10.633,6.847,48.768,33.752
22,La estrategia preferida de la empresa fue cont...,100,36.585,12.675,33.967,16.773
23,Dificultad para evaluar la necesidades de form...,100,47.461,37.06,13.027,2.452
24,La falta de cursos de formación adecuados en e...,100,41.107,30.35,20.845,7.698
25,El alto coste de los cursos de formación,100,39.666,27.446,24.288,8.599
26,El mayor esfuerzo realizado en años anteriores...,100,51.811,24.628,19.686,3.874
27,La elevada carga de trabajo y el escaso tiempo...,100,34.21,22.493,30.145,13.153
28,Dificultad para acceder a ayudas o subvencione...,100,41.047,27.593,21.827,9.533
29,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN
32,EAL-25b. EMPRESAS DE 50 O MÁS TRABAJADORES QUE...,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN
34,Año 2020. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
35,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
36,El nivel de formación de los empleados era el ...,100,24.237,8.513,44.806,22.444
37,La estrategia preferida de la empresa fue cont...,100,38.276,17.954,27.328,16.443
38,Dificultad para evaluar la necesidades de form...,100,49.456,30.866,17.119,2.558
39,La falta de cursos de formación adecuados en e...,100,49.977,30.685,12.814,6.525
40,El alto coste de los cursos de formación,100,47.284,31.183,13.884,7.649
41,El mayor esfuerzo realizado en años anteriores...,100,52.131,26.164,16.083,5.621
42,La elevada carga de trabajo y el escaso tiempo...,100,38,20.272,27.336,14.392
43,Dificultad para acceder a ayudas o subvencione...,100,48.459,31.998,13.072,6.471
44,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN
47,EAL-25c. EMPRESAS DE LA INDUSTRIA QUE NO PROPO...,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN
49,Año 2020. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
50,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
51,El nivel de formación de los empleados era el ...,100,9.92,5.561,52.495,32.024
52,La estrategia preferida de la empresa fue cont...,100,43.746,15.925,29.359,10.971
53,Dificultad para evaluar la necesidades de form...,100,47.646,35.705,14.505,2.145
54,La falta de cursos de formación adecuados en e...,100,40.286,29.511,21.306,8.896
55,El alto coste de los cursos de formación,100,35.346,30.5,24.916,9.237
56,El mayor esfuerzo realizado en años anteriores...,100,48.008,26.214,21.408,4.37
57,La elevada carga de trabajo y el escaso tiempo...,100,29.43,21.1,36.165,13.305
58,Dificultad para acceder a ayudas o subvencione...,100,39.241,31.36,20.641,8.758
59,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN
62,EAL-25d. EMPRESAS DE LA CONSTRUCCIÓN QUE NO PR...,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN
64,Año 2020. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
65,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
66,El nivel de formación de los empleados era el ...,100,7.057,4.136,48.957,39.849
67,La estrategia preferida de la empresa fue cont...,100,33.397,12.806,35.033,18.763
68,Dificultad para evaluar la necesidades de form...,100,49.967,34.841,13.129,2.064
69,La falta de cursos de formación adecuados en e...,100,40.549,30.623,21.012,7.816
70,El alto coste de los cursos de formación,100,39.552,25.106,25.178,10.165
71,El mayor esfuerzo realizado en años anteriores...,100,46.341,24.078,21.44,8.141
72,La elevada carga de trabajo y el escaso tiempo...,100,32.506,23.021,30.494,13.979
73,Dificultad para acceder a ayudas o subvencione...,100,39.362,26.207,24.144,10.286
74,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN
77,EAL-25e. EMPRESAS DEL SECTOR SERVICIOS QUE NO ...,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN
79,Año 2020. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
80,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
81,El nivel de formación de los empleados era el ...,100,11.613,7.556,47.919,32.912
82,La estrategia preferida de la empresa fue cont...,100,35.701,12.124,34.572,17.603
83,Dificultad para evaluar la necesidades de form...,100,47.079,37.541,12.805,2.575
84,La falta de cursos de formación adecuados en e...,100,41.542,30.481,20.559,7.418
85,El alto coste de los cursos de formación,100,40.697,27.284,23.808,8.211
86,El mayor esfuerzo realizado en años anteriores...,100,53.416,24.433,18.999,3.152
87,La elevada carga de trabajo y el escaso tiempo...,100,35.497,22.639,28.843,13.021
88,Dificultad para acceder a ayudas o subvencione...,100,41.82,27.156,21.519,9.505

## BARRERAS EMPRESAS + 50 TRABAJADORES (2020)

In [52]:
# BLOQUE 50+ (filas aprox 37–46 según tu Excel)

df_50_2020 = df_25_2020.iloc[37:46, :6].copy()

df_50_2020.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

# limpiar filas raras
df_50_2020 = df_50_2020[df_50_2020["Motivo"].notna()]
df_50_2020 = df_50_2020[~df_50_2020["Motivo"].astype(str).str.startswith("(")]

# convertir a numérico
cols = ["Total", "Nada", "Poco", "Bastante", "Mucho"]
df_50_2020[cols] = df_50_2020[cols].astype(float)

# añadir info
df_50_2020["Grupo"] = "50+"
df_50_2020["Sector"] = "General"
df_50_2020["Año"] = 2020

df_50_2020

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
37,La estrategia preferida de la empresa fue cont...,100.0,38.276,17.954,27.328,16.443,50+,General,2020
38,Dificultad para evaluar la necesidades de form...,100.0,49.456,30.866,17.119,2.558,50+,General,2020
39,La falta de cursos de formación adecuados en e...,100.0,49.977,30.685,12.814,6.525,50+,General,2020
40,El alto coste de los cursos de formación,100.0,47.284,31.183,13.884,7.649,50+,General,2020
41,El mayor esfuerzo realizado en años anteriores...,100.0,52.131,26.164,16.083,5.621,50+,General,2020
42,La elevada carga de trabajo y el escaso tiempo...,100.0,38.000,20.272,27.336,14.392,50+,General,2020
43,Dificultad para acceder a ayudas o subvencione...,100.0,48.459,31.998,13.072,6.471,50+,General,2020

## BARRERAS SECTOR SERVICIOS (2020)

In [53]:
# BLOQUE SERVICIOS (filas aprox 82–91)

df_servicios = df_25_2020.iloc[82:91, :6].copy()

df_servicios.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

# limpiar
df_servicios = df_servicios[df_servicios["Motivo"].notna()]
df_servicios = df_servicios[~df_servicios["Motivo"].astype(str).str.startswith("(")]

# convertir a numérico
cols = ["Total", "Nada", "Poco", "Bastante", "Mucho"]
df_servicios[cols] = df_servicios[cols].astype(float)

# añadir info
df_servicios["Grupo"] = "Todos"
df_servicios["Sector"] = "Servicios"
df_servicios["Año"] = 2020

df_servicios

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
82,La estrategia preferida de la empresa fue cont...,100.0,35.701,12.124,34.572,17.603,Todos,Servicios,2020
83,Dificultad para evaluar la necesidades de form...,100.0,47.079,37.541,12.805,2.575,Todos,Servicios,2020
84,La falta de cursos de formación adecuados en e...,100.0,41.542,30.481,20.559,7.418,Todos,Servicios,2020
85,El alto coste de los cursos de formación,100.0,40.697,27.284,23.808,8.211,Todos,Servicios,2020
86,El mayor esfuerzo realizado en años anteriores...,100.0,53.416,24.433,18.999,3.152,Todos,Servicios,2020
87,La elevada carga de trabajo y el escaso tiempo...,100.0,35.497,22.639,28.843,13.021,Todos,Servicios,2020
88,Dificultad para acceder a ayudas o subvencione...,100.0,41.820,27.156,21.519,9.505,Todos,Servicios,2020

## CONCAT (2020)

In [54]:
df_final = pd.concat([df_50_2020, df_servicios], ignore_index=True)
df_final

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,La estrategia preferida de la empresa fue cont...,100.0,38.276,17.954,27.328,16.443,50+,General,2020
1,Dificultad para evaluar la necesidades de form...,100.0,49.456,30.866,17.119,2.558,50+,General,2020
2,La falta de cursos de formación adecuados en e...,100.0,49.977,30.685,12.814,6.525,50+,General,2020
3,El alto coste de los cursos de formación,100.0,47.284,31.183,13.884,7.649,50+,General,2020
4,El mayor esfuerzo realizado en años anteriores...,100.0,52.131,26.164,16.083,5.621,50+,General,2020
5,La elevada carga de trabajo y el escaso tiempo...,100.0,38.000,20.272,27.336,14.392,50+,General,2020
6,Dificultad para acceder a ayudas o subvencione...,100.0,48.459,31.998,13.072,6.471,50+,General,2020
7,La estrategia preferida de la empresa fue cont...,100.0,35.701,12.124,34.572,17.603,Todos,Servicios,2020
8,Dificultad para evaluar la necesidades de form...,100.0,47.079,37.541,12.805,2.575,Todos,Servicios,2020
9,La falta de cursos de formación adecuados en e...,100.0,41.542,30.481,20.559,7.418,Todos,Servicios,2020
10,El alto coste de los cursos de formación,100.0,40.697,27.284,23.808,8.211,Todos,Servicios,2020
11,El mayor esfuerzo realizado en años anteriores...,100.0,53.416,24.433,18.999,3.152,Todos,Servicios,2020
12,La elevada carga de trabajo y el escaso tiempo...,100.0,35.497,22.639,28.843,13.021,Todos,Servicios,2020
13,Dificultad para acceder a ayudas o subvencione...,100.0,41.820,27.156,21.519,9.505,Todos,Servicios,2020

# 2021

In [55]:
import pandas as pd

df_25_2021_raw = pd.read_excel(
    r"C:\Users\crist\Documents\SIMULADOR\SPRINT4\TABLAS_EAL_2021.xlsx",
    sheet_name="EAL-25",
    header=None
)

df_25_2021_raw

,0,1,2,3,4,5
0,ENCUESTA ANUAL LABORAL,NaN,NaN,NaN,NaN,EAL
1,NaN,NaN,NaN,NaN,NaN,Volver al índice
2,NaN,NaN,NaN,NaN,NaN,NaN
3,EAL-25. EMPRESAS QUE NO PROPORCIONARON FORMACI...,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,Año 2021. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
6,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
7,El nivel de formación de los empleados era el ...,100,8.252,11.022,49.075,31.65
8,La estrategia preferida de la empresa fue cont...,100,22.656,16.102,41.784,19.458
9,Dificultad para evaluar la necesidades de form...,100,32.646,45.35,18.455,3.548
10,La falta de cursos de formación adecuados en e...,100,32.612,40.011,23.237,4.14
11,El alto coste de los cursos de formación,100,32.471,35.402,24.192,7.935
12,La empresa prefirió tener personal con contrat...,100,72.632,18.771,7.048,1.549
13,El mayor esfuerzo realizado en años anteriores...,100,42.927,33.179,20.706,3.189
14,La elevada carga de trabajo y el escaso tiempo...,100,29.947,24.183,35.038,10.832
15,Dificultad para acceder a ayudas o subvencione...,100,33.525,33.42,26.36,6.694
16,Cancelación o aplazamiento de las actividades ...,100,43.909,30.088,17.546,8.457
17,Otras razones,100,61.03,25.17,10.355,3.445
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN
21,EAL-25a. EMPRESAS DE 5 A 49 TRABAJADORES QUE N...,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,Año 2021. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
24,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
25,El nivel de formación de los empleados era el ...,100,8.221,10.814,49.139,31.826
26,La estrategia preferida de la empresa fue cont...,100,22.742,15.877,41.863,19.518
27,Dificultad para evaluar la necesidades de form...,100,32.725,45.247,18.48,3.548
28,La falta de cursos de formación adecuados en e...,100,32.768,39.761,23.365,4.106
29,El alto coste de los cursos de formación,100,32.629,35.169,24.218,7.984
30,La empresa prefirió tener personal con contrat...,100,72.803,18.612,7.03,1.555
31,El mayor esfuerzo realizado en años anteriores...,100,43.055,32.942,20.792,3.212
32,La elevada carga de trabajo y el escaso tiempo...,100,30.084,24.072,34.976,10.868
33,Dificultad para acceder a ayudas o subvencione...,100,33.547,33.282,26.453,6.718
34,Cancelación o aplazamiento de las actividades ...,100,44.076,29.956,17.576,8.392
35,Otras razones,100,61.09,25.139,10.335,3.436
36,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN
39,EAL-25b. EMPRESAS DE 50 O MÁS TRABAJADORES QUE...,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN
41,Año 2021. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
42,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
43,El nivel de formación de los empleados era el ...,100,10.171,23.72,45.158,20.951
44,La estrategia preferida de la empresa fue cont...,100,17.406,29.846,36.933,15.816
45,Dificultad para evaluar la necesidades de form...,100,27.873,51.618,16.956,3.553
46,La falta de cursos de formación adecuados en e...,100,23.111,55.293,15.393,6.203
47,El alto coste de los cursos de formación,100,22.847,49.599,22.598,4.956
48,La empresa prefirió tener personal con contrat...,100,62.179,28.447,8.171,1.203
49,El mayor esfuerzo realizado en años anteriores...,100,35.113,47.646,15.468,1.773
50,La elevada carga de trabajo y el escaso tiempo...,100,21.574,30.965,38.846,8.614
51,Dificultad para acceder a ayudas o subvencione...,100,32.174,41.858,20.728,5.239
52,Cancelación o aplazamiento de las actividades ...,100,33.753,38.136,15.731,12.38
53,Otras razones,100,57.364,27.058,11.58,3.998
54,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN
57,EAL-25c. EMPRESAS DE LA INDUSTRIA QUE NO PROPO...,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN
59,Año 2021. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
60,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
61,El nivel de formación de los empleados era el ...,100,9.496,10.606,57.511,22.386
62,La estrategia preferida de la empresa fue cont...,100,28.559,18.829,39.241,13.371
63,Dificultad para evaluar la necesidades de form...,100,34.575,45.834,15.84,3.751
64,La falta de cursos de formación adecuados en e...,100,30.07,36.61,27.839,5.482
65,El alto coste de los cursos de formación,100,31.25,35.813,22.797,10.14
66,La empresa prefirió tener personal con contrat...,100,68.691,22,8.791,0.517
67,El mayor esfuerzo realizado en años anteriores...,100,37.018,35.37,24.068,3.544
68,La elevada carga de trabajo y el escaso tiempo...,100,25.347,27.489,35.746,11.417
69,Dificultad para acceder a ayudas o subvencione...,100,30.547,31.63,30.733,7.09
70,Cancelación o aplazamiento de las actividades ...,100,43.098,31.355,19.275,6.272
71,Otras razones,100,61.338,24.158,12.218,2.286
72,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN
75,EAL-25d. EMPRESAS DE LA CONSTRUCCIÓN QUE NO PR...,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN
77,Año 2021. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
78,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
79,El nivel de formación de los empleados era el ...,100,7.647,12.283,48.075,31.994
80,La estrategia preferida de la empresa fue cont...,100,19.921,17.1,46.151,16.828
81,Dificultad para evaluar la necesidades de form...,100,29.677,52.486,16.18,1.656
82,La falta de cursos de formación adecuados en e...,100,30.953,44.233,21.728,3.086
83,El alto coste de los cursos de formación,100,28.929,38.127,24.992,7.952
84,La empresa prefirió tener personal con contrat...,100,68.362,20.598,9.876,1.164
85,El mayor esfuerzo realizado en años anteriores...,100,35.318,31.802,26.753,6.126
86,La elevada carga de trabajo y el escaso tiempo...,100,24.725,26.675,38.187,10.414
87,Dificultad para acceder a ayudas o subvencione...,100,25.858,40.424,27.447,6.271
88,Cancelación o aplazamiento de las actividades ...,100,47.74,35.897,12.854,3.509
89,Otras razones,100,58.904,31.182,5.903,4.01
90,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN
93,EAL-25e. EMPRESAS DEL SECTOR SERVICIOS QUE NO ...,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN
95,Año 2021. Porcentaje sobre el total de empresa...,NaN,NaN,NaN,NaN,NaN
96,NaN,TOTAL,NADA,POCO,BASTANTE,MUCHO
97,El nivel de formación de los empleados era el ...,100,9.322,19.972,44.085,26.621
98,La estrategia preferida de la empresa fue cont...,100,19.895,23.023,40.511,16.571
99,Dificultad para evaluar la necesidades de form...,100,27.234,49.65,19.234,3.882
100,La falta de cursos de formación adecuados en e...,100,28.606,43.371,22.323,5.7
101,El alto coste de los cursos de formación,100,27.252,40.625,22.849,9.274
102,La empresa prefirió tener personal con contrat...,100,60.607,27.765,9.025,2.603
103,El mayor esfuerzo realizado en años anteriores...,100,36.482,39.792,20.221,3.505
104,La elevada carga de trabajo y el escaso tiempo...,100,24.137,31.667,33.178,11.018
105,Dificultad para acceder a ayudas o subvencione...,100,28.324,38.705,24.35,8.621
106,Cancelación o aplazamiento de las actividades ...,100,37.071,35.169,19.129,8.632
107,Otras razones,100,52.707,32.784,11.022,3.487

## BARRERAS EMPRESAS + 50 TRABAJADORES (2021)

In [56]:
df_25b_2021 = df_25_2021_raw.iloc[43:54, 0:6].copy()

df_25b_2021.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25b_2021[col] = pd.to_numeric(df_25b_2021[col], errors="coerce").round(2)

df_25b_2021["Grupo"] = "50+"
df_25b_2021["Sector"] = "General"
df_25b_2021["Año"] = 2021

df_25b_2021 = df_25b_2021.reset_index(drop=True)

df_25b_2021

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,10.17,23.72,45.16,20.95,50+,General,2021
1,La estrategia preferida de la empresa fue cont...,100,17.41,29.85,36.93,15.82,50+,General,2021
2,Dificultad para evaluar la necesidades de form...,100,27.87,51.62,16.96,3.55,50+,General,2021
3,La falta de cursos de formación adecuados en e...,100,23.11,55.29,15.39,6.20,50+,General,2021
4,El alto coste de los cursos de formación,100,22.85,49.60,22.60,4.96,50+,General,2021
5,La empresa prefirió tener personal con contrat...,100,62.18,28.45,8.17,1.20,50+,General,2021
6,El mayor esfuerzo realizado en años anteriores...,100,35.11,47.65,15.47,1.77,50+,General,2021
7,La elevada carga de trabajo y el escaso tiempo...,100,21.57,30.96,38.85,8.61,50+,General,2021
8,Dificultad para acceder a ayudas o subvencione...,100,32.17,41.86,20.73,5.24,50+,General,2021
9,Cancelación o aplazamiento de las actividades ...,100,33.75,38.14,15.73,12.38,50+,General,2021
10,Otras razones,100,57.36,27.06,11.58,4.00,50+,General,2021

## BARRERAS SECTOR SERVICIOS (2021)

In [57]:
df_25e_2021 = df_25_2021_raw.iloc[97:108, 0:6].copy()

df_25e_2021.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25e_2021[col] = pd.to_numeric(df_25e_2021[col], errors="coerce").round(2)

df_25e_2021["Grupo"] = "Todos"
df_25e_2021["Sector"] = "Servicios"
df_25e_2021["Año"] = 2021

df_25e_2021 = df_25e_2021.reset_index(drop=True)

df_25e_2021

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,9.32,19.97,44.08,26.62,Todos,Servicios,2021
1,La estrategia preferida de la empresa fue cont...,100,19.90,23.02,40.51,16.57,Todos,Servicios,2021
2,Dificultad para evaluar la necesidades de form...,100,27.23,49.65,19.23,3.88,Todos,Servicios,2021
3,La falta de cursos de formación adecuados en e...,100,28.61,43.37,22.32,5.70,Todos,Servicios,2021
4,El alto coste de los cursos de formación,100,27.25,40.62,22.85,9.27,Todos,Servicios,2021
5,La empresa prefirió tener personal con contrat...,100,60.61,27.76,9.02,2.60,Todos,Servicios,2021
6,El mayor esfuerzo realizado en años anteriores...,100,36.48,39.79,20.22,3.50,Todos,Servicios,2021
7,La elevada carga de trabajo y el escaso tiempo...,100,24.14,31.67,33.18,11.02,Todos,Servicios,2021
8,Dificultad para acceder a ayudas o subvencione...,100,28.32,38.70,24.35,8.62,Todos,Servicios,2021
9,Cancelación o aplazamiento de las actividades ...,100,37.07,35.17,19.13,8.63,Todos,Servicios,2021
10,Otras razones,100,52.71,32.78,11.02,3.49,Todos,Servicios,2021

## CONCAT(2021)

In [58]:
df_25_2021_final = pd.concat(
    [df_25b_2021, df_25e_2021],
    ignore_index=True
)

df_25_2021_final

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,10.17,23.72,45.16,20.95,50+,General,2021
1,La estrategia preferida de la empresa fue cont...,100,17.41,29.85,36.93,15.82,50+,General,2021
2,Dificultad para evaluar la necesidades de form...,100,27.87,51.62,16.96,3.55,50+,General,2021
3,La falta de cursos de formación adecuados en e...,100,23.11,55.29,15.39,6.20,50+,General,2021
4,El alto coste de los cursos de formación,100,22.85,49.60,22.60,4.96,50+,General,2021
5,La empresa prefirió tener personal con contrat...,100,62.18,28.45,8.17,1.20,50+,General,2021
6,El mayor esfuerzo realizado en años anteriores...,100,35.11,47.65,15.47,1.77,50+,General,2021
7,La elevada carga de trabajo y el escaso tiempo...,100,21.57,30.96,38.85,8.61,50+,General,2021
8,Dificultad para acceder a ayudas o subvencione...,100,32.17,41.86,20.73,5.24,50+,General,2021
9,Cancelación o aplazamiento de las actividades ...,100,33.75,38.14,15.73,12.38,50+,General,2021
10,Otras razones,100,57.36,27.06,11.58,4.00,50+,General,2021
11,El nivel de formación de los empleados era el ...,100,9.32,19.97,44.08,26.62,Todos,Servicios,2021
12,La estrategia preferida de la empresa fue cont...,100,19.90,23.02,40.51,16.57,Todos,Servicios,2021
13,Dificultad para evaluar la necesidades de form...,100,27.23,49.65,19.23,3.88,Todos,Servicios,2021
14,La falta de cursos de formación adecuados en e...,100,28.61,43.37,22.32,5.70,Todos,Servicios,2021
15,El alto coste de los cursos de formación,100,27.25,40.62,22.85,9.27,Todos,Servicios,2021
16,La empresa prefirió tener personal con contrat...,100,60.61,27.76,9.02,2.60,Todos,Servicios,2021
17,El mayor esfuerzo realizado en años anteriores...,100,36.48,39.79,20.22,3.50,Todos,Servicios,2021
18,La elevada carga de trabajo y el escaso tiempo...,100,24.14,31.67,33.18,11.02,Todos,Servicios,2021
19,Dificultad para acceder a ayudas o subvencione...,100,28.32,38.70,24.35,8.62,Todos,Servicios,2021
20,Cancelación o aplazamiento de las actividades ...,100,37.07,35.17,19.13,8.63,Todos,Servicios,2021
21,Otras razones,100,52.71,32.78,11.02,3.49,Todos,Servicios,2021

# 2022

## BARRERAS EMPRESAS + 50 TRABAJADORES (2022)

In [59]:
import pandas as pd

df_25_2022_raw = pd.read_excel(
    r"C:\Users\crist\Documents\SIMULADOR\SPRINT4\Tablas_EAL_2022.xlsx",
    sheet_name="EAL-25",
    header=None
)

df_25b_2022 = df_25_2022_raw.iloc[43:54, 0:6].copy()

df_25b_2022.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25b_2022[col] = pd.to_numeric(df_25b_2022[col], errors="coerce").round(2)

df_25b_2022["Grupo"] = "50+"
df_25b_2022["Sector"] = "General"
df_25b_2022["Año"] = 2022

df_25b_2022 = df_25b_2022.reset_index(drop=True)

df_25b_2022

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,13.47,11.74,56.51,18.28,50+,General,2022
1,La estrategia preferida de la empresa fue cont...,100,21.56,19.58,41.86,17.00,50+,General,2022
2,Dificultad para evaluar la necesidades de form...,100,29.01,48.47,19.97,2.55,50+,General,2022
3,La falta de cursos de formación adecuados en e...,100,30.76,40.57,26.09,2.58,50+,General,2022
4,El alto coste de los cursos de formación,100,26.86,42.82,27.45,2.88,50+,General,2022
5,La empresa prefirió tener personal con contrat...,100,65.92,19.74,12.35,1.99,50+,General,2022
6,El mayor esfuerzo realizado en años anteriores...,100,33.15,36.40,28.41,2.03,50+,General,2022
7,La elevada carga de trabajo y el escaso tiempo...,100,24.60,27.63,36.99,10.78,50+,General,2022
8,Dificultad para acceder a ayudas o subvencione...,100,28.63,35.69,26.38,9.31,50+,General,2022
9,Cancelación o aplazamiento de las actividades ...,100,46.58,33.16,17.69,2.58,50+,General,2022
10,Otras razones,100,52.01,28.91,17.60,1.48,50+,General,2022

## BARRERAS SECTOR SERVICIOS (2022)

In [60]:
df_25e_2022 = df_25_2022_raw.iloc[97:108, 0:6].copy()

df_25e_2022.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25e_2022[col] = pd.to_numeric(df_25e_2022[col], errors="coerce").round(2)

df_25e_2022["Grupo"] = "Todos"
df_25e_2022["Sector"] = "Servicios"
df_25e_2022["Año"] = 2022

df_25e_2022 = df_25e_2022.reset_index(drop=True)

df_25e_2022

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,7.84,14.85,52.36,24.95,Todos,Servicios,2022
1,La estrategia preferida de la empresa fue cont...,100,19.19,16.49,43.77,20.55,Todos,Servicios,2022
2,Dificultad para evaluar la necesidades de form...,100,28.51,47.28,19.49,4.72,Todos,Servicios,2022
3,La falta de cursos de formación adecuados en e...,100,28.24,42.41,19.66,9.70,Todos,Servicios,2022
4,El alto coste de los cursos de formación,100,26.34,37.95,24.88,10.83,Todos,Servicios,2022
5,La empresa prefirió tener personal con contrat...,100,68.73,20.67,7.34,3.26,Todos,Servicios,2022
6,El mayor esfuerzo realizado en años anteriores...,100,32.69,38.22,22.82,6.27,Todos,Servicios,2022
7,La elevada carga de trabajo y el escaso tiempo...,100,20.29,31.06,31.79,16.86,Todos,Servicios,2022
8,Dificultad para acceder a ayudas o subvencione...,100,28.03,34.62,26.63,10.72,Todos,Servicios,2022
9,Cancelación o aplazamiento de las actividades ...,100,48.07,39.08,7.36,5.49,Todos,Servicios,2022
10,Otras razones,100,55.69,30.22,7.48,6.61,Todos,Servicios,2022

## CONCAT (2022)

In [61]:
df_25_2022_final = pd.concat(
    [df_25b_2022, df_25e_2022],
    ignore_index=True
)

df_25_2022_final

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,13.47,11.74,56.51,18.28,50+,General,2022
1,La estrategia preferida de la empresa fue cont...,100,21.56,19.58,41.86,17.00,50+,General,2022
2,Dificultad para evaluar la necesidades de form...,100,29.01,48.47,19.97,2.55,50+,General,2022
3,La falta de cursos de formación adecuados en e...,100,30.76,40.57,26.09,2.58,50+,General,2022
4,El alto coste de los cursos de formación,100,26.86,42.82,27.45,2.88,50+,General,2022
5,La empresa prefirió tener personal con contrat...,100,65.92,19.74,12.35,1.99,50+,General,2022
6,El mayor esfuerzo realizado en años anteriores...,100,33.15,36.40,28.41,2.03,50+,General,2022
7,La elevada carga de trabajo y el escaso tiempo...,100,24.60,27.63,36.99,10.78,50+,General,2022
8,Dificultad para acceder a ayudas o subvencione...,100,28.63,35.69,26.38,9.31,50+,General,2022
9,Cancelación o aplazamiento de las actividades ...,100,46.58,33.16,17.69,2.58,50+,General,2022
10,Otras razones,100,52.01,28.91,17.60,1.48,50+,General,2022
11,El nivel de formación de los empleados era el ...,100,7.84,14.85,52.36,24.95,Todos,Servicios,2022
12,La estrategia preferida de la empresa fue cont...,100,19.19,16.49,43.77,20.55,Todos,Servicios,2022
13,Dificultad para evaluar la necesidades de form...,100,28.51,47.28,19.49,4.72,Todos,Servicios,2022
14,La falta de cursos de formación adecuados en e...,100,28.24,42.41,19.66,9.70,Todos,Servicios,2022
15,El alto coste de los cursos de formación,100,26.34,37.95,24.88,10.83,Todos,Servicios,2022
16,La empresa prefirió tener personal con contrat...,100,68.73,20.67,7.34,3.26,Todos,Servicios,2022
17,El mayor esfuerzo realizado en años anteriores...,100,32.69,38.22,22.82,6.27,Todos,Servicios,2022
18,La elevada carga de trabajo y el escaso tiempo...,100,20.29,31.06,31.79,16.86,Todos,Servicios,2022
19,Dificultad para acceder a ayudas o subvencione...,100,28.03,34.62,26.63,10.72,Todos,Servicios,2022
20,Cancelación o aplazamiento de las actividades ...,100,48.07,39.08,7.36,5.49,Todos,Servicios,2022
21,Otras razones,100,55.69,30.22,7.48,6.61,Todos,Servicios,2022

# 2023

In [62]:
import pandas as pd

df_25_2023_raw = pd.read_excel(
    r"C:\Users\crist\Documents\SIMULADOR\SPRINT4\Tablas_EAL_2023.xlsx",
    sheet_name="EAL-25",
    header=None
)

## BARRERAS EMPRESAS + 50 TRABAJADORES (2023)

In [63]:
df_25b_2023 = df_25_2023_raw.iloc[40:51, 0:6].copy()

df_25b_2023.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25b_2023[col] = pd.to_numeric(df_25b_2023[col], errors="coerce").round(2)

df_25b_2023["Grupo"] = "50+"
df_25b_2023["Sector"] = "General"
df_25b_2023["Año"] = 2023

df_25b_2023 = df_25b_2023.reset_index(drop=True)

df_25b_2023

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100.0,9.34,15.60,46.11,28.95,50+,General,2023
1,La empresa prefirió contratar a personal con l...,100.0,20.93,24.72,35.18,19.18,50+,General,2023
2,Dificultad para evaluar la necesidades de form...,100.0,24.53,50.51,22.12,2.84,50+,General,2023
3,La falta de cursos de formación adecuados en e...,100.0,27.97,44.56,17.15,10.32,50+,General,2023
4,El alto coste de los cursos de formación,100.0,30.82,36.38,22.27,10.53,50+,General,2023
5,La empresa prefirió tener personal con contrat...,100.0,68.14,19.18,10.26,2.42,50+,General,2023
6,El mayor esfuerzo realizado en años anteriores...,100.0,37.75,40.94,15.17,6.13,50+,General,2023
7,La elevada carga de trabajo y el escaso tiempo...,100.0,18.66,29.68,34.54,17.11,50+,General,2023
8,Dificultad para acceder a ayudas o subvencione...,100.0,34.52,37.12,19.53,8.83,50+,General,2023
9,Otras razones,100.0,52.85,35.57,6.17,5.40,50+,General,2023
10,NaN,NaN,NaN,NaN,NaN,NaN,50+,General,2023

## BARRERAS SECTOR SERVICIOS (2023)

In [64]:
df_25e_2023 = df_25_2023_raw.iloc[91:102, 0:6].copy()

df_25e_2023.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25e_2023[col] = pd.to_numeric(df_25e_2023[col], errors="coerce").round(2)

df_25e_2023["Grupo"] = "Todos"
df_25e_2023["Sector"] = "Servicios"
df_25e_2023["Año"] = 2023

df_25e_2023 = df_25e_2023.reset_index(drop=True)

df_25e_2023

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,13.68,13.59,47.16,25.57,Todos,Servicios,2023
1,La empresa prefirió contratar a personal con l...,100,21.53,16.96,42.31,19.21,Todos,Servicios,2023
2,Dificultad para evaluar la necesidades de form...,100,33.31,43.09,19.86,3.73,Todos,Servicios,2023
3,La falta de cursos de formación adecuados en e...,100,29.72,37.71,23.96,8.60,Todos,Servicios,2023
4,El alto coste de los cursos de formación,100,28.51,30.63,29.68,11.17,Todos,Servicios,2023
5,La empresa prefirió tener personal con contrat...,100,68.27,20.55,9.09,2.09,Todos,Servicios,2023
6,El mayor esfuerzo realizado en años anteriores...,100,39.51,35.39,20.58,4.53,Todos,Servicios,2023
7,La elevada carga de trabajo y el escaso tiempo...,100,24.86,27.31,36.28,11.55,Todos,Servicios,2023
8,Dificultad para acceder a ayudas o subvencione...,100,31.40,27.59,27.00,14.01,Todos,Servicios,2023
9,Otras razones,100,68.27,20.55,9.09,2.09,Todos,Servicios,2023

## CONCAT(2023)

In [65]:
df_25b_2023 = df_25b_2023[df_25b_2023["Motivo"].notna()].reset_index(drop=True)
df_25e_2023 = df_25e_2023[df_25e_2023["Motivo"].notna()].reset_index(drop=True)

df_25_2023_final = pd.concat(
    [df_25b_2023, df_25e_2023],
    ignore_index=True
)

df_25_2023_final

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100.0,9.34,15.60,46.11,28.95,50+,General,2023
1,La empresa prefirió contratar a personal con l...,100.0,20.93,24.72,35.18,19.18,50+,General,2023
2,Dificultad para evaluar la necesidades de form...,100.0,24.53,50.51,22.12,2.84,50+,General,2023
3,La falta de cursos de formación adecuados en e...,100.0,27.97,44.56,17.15,10.32,50+,General,2023
4,El alto coste de los cursos de formación,100.0,30.82,36.38,22.27,10.53,50+,General,2023
5,La empresa prefirió tener personal con contrat...,100.0,68.14,19.18,10.26,2.42,50+,General,2023
6,El mayor esfuerzo realizado en años anteriores...,100.0,37.75,40.94,15.17,6.13,50+,General,2023
7,La elevada carga de trabajo y el escaso tiempo...,100.0,18.66,29.68,34.54,17.11,50+,General,2023
8,Dificultad para acceder a ayudas o subvencione...,100.0,34.52,37.12,19.53,8.83,50+,General,2023
9,Otras razones,100.0,52.85,35.57,6.17,5.40,50+,General,2023
10,El nivel de formación de los empleados era el ...,100.0,13.68,13.59,47.16,25.57,Todos,Servicios,2023
11,La empresa prefirió contratar a personal con l...,100.0,21.53,16.96,42.31,19.21,Todos,Servicios,2023
12,Dificultad para evaluar la necesidades de form...,100.0,33.31,43.09,19.86,3.73,Todos,Servicios,2023
13,La falta de cursos de formación adecuados en e...,100.0,29.72,37.71,23.96,8.60,Todos,Servicios,2023
14,El alto coste de los cursos de formación,100.0,28.51,30.63,29.68,11.17,Todos,Servicios,2023
15,La empresa prefirió tener personal con contrat...,100.0,68.27,20.55,9.09,2.09,Todos,Servicios,2023
16,El mayor esfuerzo realizado en años anteriores...,100.0,39.51,35.39,20.58,4.53,Todos,Servicios,2023
17,La elevada carga de trabajo y el escaso tiempo...,100.0,24.86,27.31,36.28,11.55,Todos,Servicios,2023
18,Dificultad para acceder a ayudas o subvencione...,100.0,31.40,27.59,27.00,14.01,Todos,Servicios,2023
19,Otras razones,100.0,68.27,20.55,9.09,2.09,Todos,Servicios,2023

# 2024

In [66]:
import pandas as pd

df_25_2024_raw = pd.read_excel(
    r"C:\Users\crist\Documents\SIMULADOR\SPRINT4\Tablas_EAL_2024.xlsx",
    sheet_name="EAL-25",
    header=None
)

## BARRERAS EMPRESAS + 50 TRABAJADORES (2024)

In [67]:
df_25b_2024 = df_25_2024_raw.iloc[40:51, 0:6].copy()

df_25b_2024.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25b_2024[col] = pd.to_numeric(df_25b_2024[col], errors="coerce").round(2)

df_25b_2024["Grupo"] = "50+"
df_25b_2024["Sector"] = "General"
df_25b_2024["Año"] = 2024

df_25b_2024 = df_25b_2024.reset_index(drop=True)

df_25b_2024

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100.0,13.94,12.08,49.03,24.95,50+,General,2024
1,La empresa prefirió contratar a personal con l...,100.0,21.34,16.11,41.86,20.69,50+,General,2024
2,Dificultad para evaluar la necesidades de form...,100.0,31.26,48.98,17.45,2.31,50+,General,2024
3,La falta de cursos de formación adecuados en e...,100.0,36.66,46.18,11.29,5.87,50+,General,2024
4,El alto coste de los cursos de formación,100.0,37.61,36.39,15.09,10.91,50+,General,2024
5,La empresa prefirió tener personal con contrat...,100.0,58.53,32.40,8.90,0.17,50+,General,2024
6,El mayor esfuerzo realizado en años anteriores...,100.0,36.08,39.70,24.05,0.17,50+,General,2024
7,La elevada carga de trabajo y el escaso tiempo...,100.0,28.98,30.22,28.62,12.17,50+,General,2024
8,Dificultad para acceder a ayudas o subvencione...,100.0,35.27,37.37,17.21,10.15,50+,General,2024
9,Otras razones,100.0,51.77,30.56,7.50,10.16,50+,General,2024
10,NaN,NaN,NaN,NaN,NaN,NaN,50+,General,2024

## BARRERAS SECTOR SERVICIOS (2024)

In [68]:
df_25e_2024 = df_25_2024_raw.iloc[91:102, 0:6].copy()

df_25e_2024.columns = ["Motivo", "Total", "Nada", "Poco", "Bastante", "Mucho"]

for col in ["Total", "Nada", "Poco", "Bastante", "Mucho"]:
    df_25e_2024[col] = pd.to_numeric(df_25e_2024[col], errors="coerce").round(2)

df_25e_2024["Grupo"] = "Todos"
df_25e_2024["Sector"] = "Servicios"
df_25e_2024["Año"] = 2024

df_25e_2024 = df_25e_2024.reset_index(drop=True)

df_25e_2024

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100,6.46,12.72,47.63,33.19,Todos,Servicios,2024
1,La empresa prefirió contratar a personal con l...,100,15.89,15.64,45.62,22.85,Todos,Servicios,2024
2,Dificultad para evaluar la necesidades de form...,100,33.50,45.99,15.39,5.12,Todos,Servicios,2024
3,La falta de cursos de formación adecuados en e...,100,33.13,41.32,18.32,7.23,Todos,Servicios,2024
4,El alto coste de los cursos de formación,100,31.41,33.92,23.19,11.48,Todos,Servicios,2024
5,La empresa prefirió tener personal con contrat...,100,70.07,19.88,8.26,1.79,Todos,Servicios,2024
6,El mayor esfuerzo realizado en años anteriores...,100,44.02,34.27,17.21,4.50,Todos,Servicios,2024
7,La elevada carga de trabajo y el escaso tiempo...,100,22.42,29.64,30.42,17.52,Todos,Servicios,2024
8,Dificultad para acceder a ayudas o subvencione...,100,36.20,30.57,20.54,12.70,Todos,Servicios,2024
9,Otras razones,100,63.83,21.36,7.97,6.84,Todos,Servicios,2024

## CONCAT(2024)

In [69]:
df_25b_2024 = df_25b_2024[df_25b_2024["Motivo"].notna()].reset_index(drop=True)
df_25e_2024 = df_25e_2024[df_25e_2024["Motivo"].notna()].reset_index(drop=True)

df_25_2024_final = pd.concat(
    [df_25b_2024, df_25e_2024],
    ignore_index=True
)

df_25_2024_final

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,El nivel de formación de los empleados era el ...,100.0,13.94,12.08,49.03,24.95,50+,General,2024
1,La empresa prefirió contratar a personal con l...,100.0,21.34,16.11,41.86,20.69,50+,General,2024
2,Dificultad para evaluar la necesidades de form...,100.0,31.26,48.98,17.45,2.31,50+,General,2024
3,La falta de cursos de formación adecuados en e...,100.0,36.66,46.18,11.29,5.87,50+,General,2024
4,El alto coste de los cursos de formación,100.0,37.61,36.39,15.09,10.91,50+,General,2024
5,La empresa prefirió tener personal con contrat...,100.0,58.53,32.40,8.90,0.17,50+,General,2024
6,El mayor esfuerzo realizado en años anteriores...,100.0,36.08,39.70,24.05,0.17,50+,General,2024
7,La elevada carga de trabajo y el escaso tiempo...,100.0,28.98,30.22,28.62,12.17,50+,General,2024
8,Dificultad para acceder a ayudas o subvencione...,100.0,35.27,37.37,17.21,10.15,50+,General,2024
9,Otras razones,100.0,51.77,30.56,7.50,10.16,50+,General,2024
10,El nivel de formación de los empleados era el ...,100.0,6.46,12.72,47.63,33.19,Todos,Servicios,2024
11,La empresa prefirió contratar a personal con l...,100.0,15.89,15.64,45.62,22.85,Todos,Servicios,2024
12,Dificultad para evaluar la necesidades de form...,100.0,33.50,45.99,15.39,5.12,Todos,Servicios,2024
13,La falta de cursos de formación adecuados en e...,100.0,33.13,41.32,18.32,7.23,Todos,Servicios,2024
14,El alto coste de los cursos de formación,100.0,31.41,33.92,23.19,11.48,Todos,Servicios,2024
15,La empresa prefirió tener personal con contrat...,100.0,70.07,19.88,8.26,1.79,Todos,Servicios,2024
16,El mayor esfuerzo realizado en años anteriores...,100.0,44.02,34.27,17.21,4.50,Todos,Servicios,2024
17,La elevada carga de trabajo y el escaso tiempo...,100.0,22.42,29.64,30.42,17.52,Todos,Servicios,2024
18,Dificultad para acceder a ayudas o subvencione...,100.0,36.20,30.57,20.54,12.70,Todos,Servicios,2024
19,Otras razones,100.0,63.83,21.36,7.97,6.84,Todos,Servicios,2024

## CONCAT DE TODOS LOS AÑOS

In [73]:
df_total = pd.concat(
    [
        df_final,
        df_25_2021_final,
        df_25_2022_final,
        df_25_2023_final,
        df_25_2024_final
    ],
    ignore_index=True
)

df_total = df_total.round(2)

df_total

,Motivo,Total,Nada,Poco,Bastante,Mucho,Grupo,Sector,Año
0,La estrategia preferida de la empresa fue cont...,100.0,38.28,17.95,27.33,16.44,50+,General,2020
1,Dificultad para evaluar la necesidades de form...,100.0,49.46,30.87,17.12,2.56,50+,General,2020
2,La falta de cursos de formación adecuados en e...,100.0,49.98,30.68,12.81,6.52,50+,General,2020
3,El alto coste de los cursos de formación,100.0,47.28,31.18,13.88,7.65,50+,General,2020
4,El mayor esfuerzo realizado en años anteriores...,100.0,52.13,26.16,16.08,5.62,50+,General,2020
5,La elevada carga de trabajo y el escaso tiempo...,100.0,38.00,20.27,27.34,14.39,50+,General,2020
6,Dificultad para acceder a ayudas o subvencione...,100.0,48.46,32.00,13.07,6.47,50+,General,2020
7,La estrategia preferida de la empresa fue cont...,100.0,35.70,12.12,34.57,17.60,Todos,Servicios,2020
8,Dificultad para evaluar la necesidades de form...,100.0,47.08,37.54,12.80,2.58,Todos,Servicios,2020
9,La falta de cursos de formación adecuados en e...,100.0,41.54,30.48,20.56,7.42,Todos,Servicios,2020
10,El alto coste de los cursos de formación,100.0,40.70,27.28,23.81,8.21,Todos,Servicios,2020
11,El mayor esfuerzo realizado en años anteriores...,100.0,53.42,24.43,19.00,3.15,Todos,Servicios,2020
12,La elevada carga de trabajo y el escaso tiempo...,100.0,35.50,22.64,28.84,13.02,Todos,Servicios,2020
13,Dificultad para acceder a ayudas o subvencione...,100.0,41.82,27.16,21.52,9.51,Todos,Servicios,2020
14,El nivel de formación de los empleados era el ...,100.0,10.17,23.72,45.16,20.95,50+,General,2021
15,La estrategia preferida de la empresa fue cont...,100.0,17.41,29.85,36.93,15.82,50+,General,2021
16,Dificultad para evaluar la necesidades de form...,100.0,27.87,51.62,16.96,3.55,50+,General,2021
17,La falta de cursos de formación adecuados en e...,100.0,23.11,55.29,15.39,6.20,50+,General,2021
18,El alto coste de los cursos de formación,100.0,22.85,49.60,22.60,4.96,50+,General,2021
19,La empresa prefirió tener personal con contrat...,100.0,62.18,28.45,8.17,1.20,50+,General,2021
20,El mayor esfuerzo realizado en años anteriores...,100.0,35.11,47.65,15.47,1.77,50+,General,2021
21,La elevada carga de trabajo y el escaso tiempo...,100.0,21.57,30.96,38.85,8.61,50+,General,2021
22,Dificultad para acceder a ayudas o subvencione...,100.0,32.17,41.86,20.73,5.24,50+,General,2021
23,Cancelación o aplazamiento de las actividades ...,100.0,33.75,38.14,15.73,12.38,50+,General,2021
24,Otras razones,100.0,57.36,27.06,11.58,4.00,50+,General,2021
25,El nivel de formación de los empleados era el ...,100.0,9.32,19.97,44.08,26.62,Todos,Servicios,2021
26,La estrategia preferida de la empresa fue cont...,100.0,19.90,23.02,40.51,16.57,Todos,Servicios,2021
27,Dificultad para evaluar la necesidades de form...,100.0,27.23,49.65,19.23,3.88,Todos,Servicios,2021
28,La falta de cursos de formación adecuados en e...,100.0,28.61,43.37,22.32,5.70,Todos,Servicios,2021
29,El alto coste de los cursos de formación,100.0,27.25,40.62,22.85,9.27,Todos,Servicios,2021
30,La empresa prefirió tener personal con contrat...,100.0,60.61,27.76,9.02,2.60,Todos,Servicios,2021
31,El mayor esfuerzo realizado en años anteriores...,100.0,36.48,39.79,20.22,3.50,Todos,Servicios,2021
32,La elevada carga de trabajo y el escaso tiempo...,100.0,24.14,31.67,33.18,11.02,Todos,Servicios,2021
33,Dificultad para acceder a ayudas o subvencione...,100.0,28.32,38.70,24.35,8.62,Todos,Servicios,2021
34,Cancelación o aplazamiento de las actividades ...,100.0,37.07,35.17,19.13,8.63,Todos,Servicios,2021
35,Otras razones,100.0,52.71,32.78,11.02,3.49,Todos,Servicios,2021
36,El nivel de formación de los empleados era el ...,100.0,13.47,11.74,56.51,18.28,50+,General,2022
37,La estrategia preferida de la empresa fue cont...,100.0,21.56,19.58,41.86,17.00,50+,General,2022
38,Dificultad para evaluar la necesidades de form...,100.0,29.01,48.47,19.97,2.55,50+,General,2022
39,La falta de cursos de formación adecuados en e...,100.0,30.76,40.57,26.09,2.58,50+,General,2022
40,El alto coste de los cursos de formación,100.0,26.86,42.82,27.45,2.88,50+,General,2022
41,La empresa prefirió tener personal con contrat...,100.0,65.92,19.74,12.35,1.99,50+,General,2022
42,El mayor esfuerzo realizado en años anteriores...,100.0,33.15,36.40,28.41,2.03,50+,General,2022
43,La elevada carga de trabajo y el escaso tiempo...,100.0,24.60,27.63,36.99,10.78,50+,General,2022
44,Dificultad para acceder a ayudas o subvencione...,100.0,28.63,35.69,26.38,9.31,50+,General,2022
45,Cancelación o aplazamiento de las actividades ...,100.0,46.58,33.16,17.69,2.58,50+,General,2022
46,Otras razones,100.0,52.01,28.91,17.60,1.48,50+,General,2022
47,El nivel de formación de los empleados era el ...,100.0,7.84,14.85,52.36,24.95,Todos,Servicios,2022
48,La estrategia preferida de la empresa fue cont...,100.0,19.19,16.49,43.77,20.55,Todos,Servicios,2022
49,Dificultad para evaluar la necesidades de form...,100.0,28.51,47.28,19.49,4.72,Todos,Servicios,2022
50,La falta de cursos de formación adecuados en e...,100.0,28.24,42.41,19.66,9.70,Todos,Servicios,2022
51,El alto coste de los cursos de formación,100.0,26.34,37.95,24.88,10.83,Todos,Servicios,2022
52,La empresa prefirió tener personal con contrat...,100.0,68.73,20.67,7.34,3.26,Todos,Servicios,2022
53,El mayor esfuerzo realizado en años anteriores...,100.0,32.69,38.22,22.82,6.27,Todos,Servicios,2022
54,La elevada carga de trabajo y el escaso tiempo...,100.0,20.29,31.06,31.79,16.86,Todos,Servicios,2022
55,Dificultad para acceder a ayudas o subvencione...,100.0,28.03,34.62,26.63,10.72,Todos,Servicios,2022
56,Cancelación o aplazamiento de las actividades ...,100.0,48.07,39.08,7.36,5.49,Todos,Servicios,2022
57,Otras razones,100.0,55.69,30.22,7.48,6.61,Todos,Servicios,2022
58,El nivel de formación de los empleados era el ...,100.0,9.34,15.60,46.11,28.95,50+,General,2023
59,La empresa prefirió contratar a personal con l...,100.0,20.93,24.72,35.18,19.18,50+,General,2023
60,Dificultad para evaluar la necesidades de form...,100.0,24.53,50.51,22.12,2.84,50+,General,2023
61,La falta de cursos de formación adecuados en e...,100.0,27.97,44.56,17.15,10.32,50+,General,2023
62,El alto coste de los cursos de formación,100.0,30.82,36.38,22.27,10.53,50+,General,2023
63,La empresa prefirió tener personal con contrat...,100.0,68.14,19.18,10.26,2.42,50+,General,2023
64,El mayor esfuerzo realizado en años anteriores...,100.0,37.75,40.94,15.17,6.13,50+,General,2023
65,La elevada carga de trabajo y el escaso tiempo...,100.0,18.66,29.68,34.54,17.11,50+,General,2023
66,Dificultad para acceder a ayudas o subvencione...,100.0,34.52,37.12,19.53,8.83,50+,General,2023
67,Otras razones,100.0,52.85,35.57,6.17,5.40,50+,General,2023
68,El nivel de formación de los empleados era el ...,100.0,13.68,13.59,47.16,25.57,Todos,Servicios,2023
69,La empresa prefirió contratar a personal con l...,100.0,21.53,16.96,42.31,19.21,Todos,Servicios,2023
70,Dificultad para evaluar la necesidades de form...,100.0,33.31,43.09,19.86,3.73,Todos,Servicios,2023
71,La falta de cursos de formación adecuados en e...,100.0,29.72,37.71,23.96,8.60,Todos,Servicios,2023
72,El alto coste de los cursos de formación,100.0,28.51,30.63,29.68,11.17,Todos,Servicios,2023
73,La empresa prefirió tener personal con contrat...,100.0,68.27,20.55,9.09,2.09,Todos,Servicios,2023
74,El mayor esfuerzo realizado en años anteriores...,100.0,39.51,35.39,20.58,4.53,Todos,Servicios,2023
75,La elevada carga de trabajo y el escaso tiempo...,100.0,24.86,27.31,36.28,11.55,Todos,Servicios,2023
76,Dificultad para acceder a ayudas o subvencione...,100.0,31.40,27.59,27.00,14.01,Todos,Servicios,2023
77,Otras razones,100.0,68.27,20.55,9.09,2.09,Todos,Servicios,2023
78,El nivel de formación de los empleados era el ...,100.0,13.94,12.08,49.03,24.95,50+,General,2024
79,La empresa prefirió contratar a personal con l...,100.0,21.34,16.11,41.86,20.69,50+,General,2024
80,Dificultad para evaluar la necesidades de form...,100.0,31.26,48.98,17.45,2.31,50+,General,2024
81,La falta de cursos de formación adecuados en e...,100.0,36.66,46.18,11.29,5.87,50+,General,2024
82,El alto coste de los cursos de formación,100.0,37.61,36.39,15.09,10.91,50+,General,2024
83,La empresa prefirió tener personal con contrat...,100.0,58.53,32.40,8.90,0.17,50+,General,2024
84,El mayor esfuerzo realizado en años anteriores...,100.0,36.08,39.70,24.05,0.17,50+,General,2024
85,La elevada carga de trabajo y el escaso tiempo...,100.0,28.98,30.22,28.62,12.17,50+,General,2024
86,Dificultad para acceder a ayudas o subvencione...,100.0,35.27,37.37,17.21,10.15,50+,General,2024
87,Otras razones,100.0,51.77,30.56,7.50,10.16,50+,General,2024
88,El nivel de formación de los empleados era el ...,100.0,6.46,12.72,47.63,33.19,Todos,Servicios,2024
89,La empresa prefirió contratar a personal con l...,100.0,15.89,15.64,45.62,22.85,Todos,Servicios,2024
90,Dificultad para evaluar la necesidades de form...,100.0,33.50,45.99,15.39,5.12,Todos,Servicios,2024
91,La falta de cursos de formación adecuados en e...,100.0,33.13,41.32,18.32,7.23,Todos,Servicios,2024
92,El alto coste de los cursos de formación,100.0,31.41,33.92,23.19,11.48,Todos,Servicios,2024
93,La empresa prefirió tener personal con contrat...,100.0,70.07,19.88,8.26,1.79,Todos,Servicios,2024
94,El mayor esfuerzo realizado en años anteriores...,100.0,44.02,34.27,17.21,4.50,Todos,Servicios,2024
95,La elevada carga de trabajo y el escaso tiempo...,100.0,22.42,29.64,30.42,17.52,Todos,Servicios,2024
96,Dificultad para acceder a ayudas o subvencione...,100.0,36.20,30.57,20.54,12.70,Todos,Servicios,2024
97,Otras razones,100.0,63.83,21.36,7.97,6.84,Todos,Servicios,2024