In [2]:
import pandas as pd

eal_2023_dict = pd.read_excel("Tablas_EAL_2023.xlsx", sheet_name=["EAL-18a"], skiprows=5)

df_18a = eal_2023_dict["EAL-18a"]

df_18a.columns = [
    "Categoria", 
    "Total", 
    "Cursos_Externos", 
    "Cursos_Internos", 
    "Formacion_Puesto", 
    "Rotacion_Puestos", 
    "Conferencias_Seminarios"
]


df_18a = df_18a.dropna(subset=["Categoria"])

df_18a = df_18a[df_18a["Total"].notna()]

df_18a

,Categoria,Total,Cursos_Externos,Cursos_Internos,Formacion_Puesto,Rotacion_Puestos,Conferencias_Seminarios
1,TOTAL,72.932251,33.51468,72.118511,58.494234,26.923791,34.063854
4,De 5 a 9 trabajadores,64.67073,27.452634,66.497141,54.595202,26.269467,31.311321
5,De 10 a 49 trabajadores,79.013394,33.328382,74.868712,59.67687,25.119929,32.658179
6,De 50 a 249 trabajadores,94.064516,58.117774,85.302763,69.111307,36.576524,51.00921
7,De 250 a 499 trabajadores,98.31393,77.133524,84.646795,76.929359,42.01715,60.963659
8,Más de 499 trabajadores,99.188641,85.889571,85.071575,82.361963,50.869121,66.002045
11,Industria,78.356762,35.335511,72.393006,61.640809,33.150007,30.577838
12,Construcción,79.310809,25.605654,78.549823,63.259364,22.8947,21.925088
13,Comercio y reparación de vehículos,70.702769,34.41841,72.647356,58.602862,28.884518,40.046304
14,Transporte y almacenamiento,79.535758,29.931669,78.440513,53.049365,20.154544,17.306341
15,Hostelería,58.387782,23.458918,63.714466,58.234151,24.857041,17.404033
16,"Información, comunicaciones, actividades finan...",81.274725,47.985398,69.172526,56.429151,29.583559,54.286101
17,"Actividades profesionales, científicas y técnicas",82.792534,44.897408,73.321634,56.029518,24.586033,61.258099
18,Actividades administrativas y servicios auxili...,72.70554,36.890636,76.654753,56.933524,25.153681,34.381701
19,"Actividades artísticas, recreativas y de entre...",71.846197,37.50162,65.135415,51.768822,26.247246,46.650253
22,Andalucía,73.308284,26.79951,73.86554,55.19664,24.941871,28.039603
23,Aragón,78.902352,31.875081,73.132017,58.833398,29.190863,33.926958
24,Asturias (Principado de),74.890653,30.737616,71.62016,51.719663,18.689163,30.60783
25,Balears (Illes),67.030587,36.236371,65.203931,63.494414,31.578947,34.688383
26,Canarias,62.514076,35.807736,77.133106,56.958665,26.241942,28.981797
27,Cantabria,76.731657,31.795386,75.459712,58.609161,19.859579,26.847208
28,Castilla-La Mancha,69.834357,32.305122,73.619154,59.922049,22.672606,28.11804
29,Castilla y León,74.853918,31.775038,71.782134,56.994589,27.179988,27.650137
30,Cataluña,74.478543,35.726954,71.752939,59.729841,26.984945,40.831099
31,Comunitat Valenciana,72.760795,29.908077,67.690748,60.557128,28.964384,32.155465
32,Extremadura,68.839375,29.710145,74.613527,52.608696,23.502415,30.797101
33,Galicia,75.980682,30.263437,74.334346,52.906279,27.826824,36.930574
34,Madrid (Comunidad de),72.840425,41.930496,71.066149,63.001887,28.928609,38.814341
35,Murcia (Región de),73.763928,30.564078,68.657069,60.054284,27.967902,30.068445
36,Navarra (Comunidad Foral de),72.32387,34.981099,74.091306,55.39401,34.661239,40.8549
37,País Vasco,73.799418,37.063512,78.489853,54.334073,23.547778,33.14436
38,"Rioja, La",74.425059,32.818327,67.448055,60.628663,25.785828,30.900373

In [3]:
# 1. Ponemos la columna 'Categoria' como el índice (los nombres de las filas)
df_transpuesta = df_18a.set_index("Categoria")

# 2. Transponemos (la .T hace la magia de girar todo)
df_transpuesta = df_transpuesta.T

# Ahora tus columnas son "TOTAL", "De 5 a 9 trabajadores", "Andalucía", etc.
# Y tus filas son "Total", "Cursos_Externos", "Cursos_Internos"...

In [4]:
df_transpuesta

Categoria,TOTAL,De 5 a 9 trabajadores,De 10 a 49 trabajadores,De 50 a 249 trabajadores,De 250 a 499 trabajadores,Más de 499 trabajadores,Industria,Construcción,Comercio y reparación de vehículos,Transporte y almacenamiento,...,Castilla y León,Cataluña,Comunitat Valenciana,Extremadura,Galicia,Madrid (Comunidad de),Murcia (Región de),Navarra (Comunidad Foral de),País Vasco,"Rioja, La"
Total,72.932251,64.67073,79.013394,94.064516,98.31393,99.188641,78.356762,79.310809,70.702769,79.535758,...,74.853918,74.478543,72.760795,68.839375,75.980682,72.840425,73.763928,72.32387,73.799418,74.425059
Cursos_Externos,33.51468,27.452634,33.328382,58.117774,77.133524,85.889571,35.335511,25.605654,34.41841,29.931669,...,31.775038,35.726954,29.908077,29.710145,30.263437,41.930496,30.564078,34.981099,37.063512,32.818327
Cursos_Internos,72.118511,66.497141,74.868712,85.302763,84.646795,85.071575,72.393006,78.549823,72.647356,78.440513,...,71.782134,71.752939,67.690748,74.613527,74.334346,71.066149,68.657069,74.091306,78.489853,67.448055
Formacion_Puesto,58.494234,54.595202,59.67687,69.111307,76.929359,82.361963,61.640809,63.259364,58.602862,53.049365,...,56.994589,59.729841,60.557128,52.608696,52.906279,63.001887,60.054284,55.39401,54.334073,60.628663
Rotacion_Puestos,26.923791,26.269467,25.119929,36.576524,42.01715,50.869121,33.150007,22.8947,28.884518,20.154544,...,27.179988,26.984945,28.964384,23.502415,27.826824,28.928609,27.967902,34.661239,23.547778,25.785828
Conferencias_Seminarios,34.063854,31.311321,32.658179,51.00921,60.963659,66.002045,30.577838,21.925088,40.046304,17.306341,...,27.650137,40.831099,32.155465,30.797101,36.930574,38.814341,30.068445,40.8549,33.14436,30.900373

In [8]:
# 1. Quitamos los espacios en blanco al principio y al final de todos los nombres de columnas
df_transpuesta.columns = df_transpuesta.columns.str.strip()

# 2. Ahora ya puedes usar los nombres "limpios" sin miedo al KeyError
columnas_interes = [
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana"
]

# 3. Filtramos
df_seleccion = df_transpuesta[columnas_interes]

print(df_seleccion)

Categoria               De 250 a 499 trabajadores   Cataluña  Andalucía  \
Total                                    98.31393  74.478543  73.308284
Cursos_Externos                         77.133524  35.726954   26.79951
Cursos_Internos                         84.646795  71.752939   73.86554
Formacion_Puesto                        76.929359  59.729841   55.19664
Rotacion_Puestos                         42.01715  26.984945  24.941871
Conferencias_Seminarios                 60.963659  40.831099  28.039603

Categoria               Madrid (Comunidad de) País Vasco Comunitat Valenciana
Total                               72.840425  73.799418            72.760795
Cursos_Externos                     41.930496  37.063512            29.908077
Cursos_Internos                     71.066149  78.489853            67.690748
Formacion_Puesto                    63.001887  54.334073            60.557128
Rotacion_Puestos                    28.928609  23.547778            28.964384
Conferencias_Seminarios             38.814341   33.14436            32.155465

In [14]:
# Tienes que poner el "=" para que se guarde el cambio
df_seleccion = df_seleccion.round(2)

# Ahora, al imprimirla, verás que todo tiene 2 decimales
print(df_seleccion)

Categoria               De 250 a 499 trabajadores   Cataluña  Andalucía  \
Total                                    98.31393  74.478543  73.308284
Cursos_Externos                         77.133524  35.726954   26.79951
Cursos_Internos                         84.646795  71.752939   73.86554
Formacion_Puesto                        76.929359  59.729841   55.19664
Rotacion_Puestos                         42.01715  26.984945  24.941871
Conferencias_Seminarios                 60.963659  40.831099  28.039603

Categoria               Madrid (Comunidad de) País Vasco Comunitat Valenciana
Total                               72.840425  73.799418            72.760795
Cursos_Externos                     41.930496  37.063512            29.908077
Cursos_Internos                     71.066149  78.489853            67.690748
Formacion_Puesto                    63.001887  54.334073            60.557128
Rotacion_Puestos                    28.928609  23.547778            28.964384
Conferencias_Seminarios             38.814341   33.14436            32.155465

In [17]:
# 1. Convertimos todo a números (por si acaso Pandas cree que es texto)
df_seleccion = df_seleccion.apply(pd.to_numeric, errors='coerce')

# 2. Ahora redondeamos y GUARDAMOS el resultado
df_seleccion = df_seleccion.round(2)

# 3. Comprobamos
print(df_seleccion)

Categoria                De 250 a 499 trabajadores  Cataluña  Andalucía  \
Total                                        98.31     74.48      73.31
Cursos_Externos                              77.13     35.73      26.80
Cursos_Internos                              84.65     71.75      73.87
Formacion_Puesto                             76.93     59.73      55.20
Rotacion_Puestos                             42.02     26.98      24.94
Conferencias_Seminarios                      60.96     40.83      28.04

Categoria                Madrid (Comunidad de)  País Vasco  \
Total                                    72.84       73.80
Cursos_Externos                          41.93       37.06
Cursos_Internos                          71.07       78.49
Formacion_Puesto                         63.00       54.33
Rotacion_Puestos                         28.93       23.55
Conferencias_Seminarios                  38.81       33.14

Categoria                Comunitat Valenciana
Total                                   72.76
Cursos_Externos                         29.91
Cursos_Internos                         67.69
Formacion_Puesto                        60.56
Rotacion_Puestos                        28.96
Conferencias_Seminarios                 32.16

In [24]:
# Ahora 'df_formacion' contiene exactamente lo mismo que 'eal_2023_clean'
# 1. Creamos el nuevo nombre usando la tabla que SÍ existe
eal_2023_18a = df_seleccion

# 2. Comprobamos que funciona

In [25]:
eal_2023_18a

Categoria,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana
Total,98.31,74.48,73.31,72.84,73.80,72.76
Cursos_Externos,77.13,35.73,26.80,41.93,37.06,29.91
Cursos_Internos,84.65,71.75,73.87,71.07,78.49,67.69
Formacion_Puesto,76.93,59.73,55.20,63.00,54.33,60.56
Rotacion_Puestos,42.02,26.98,24.94,28.93,23.55,28.96
Conferencias_Seminarios,60.96,40.83,28.04,38.81,33.14,32.16

In [26]:
eal_2023_18a.insert(0, 'Año', 2023)

In [27]:
eal_2023_18a

Categoria,Año,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana
Total,2023,98.31,74.48,73.31,72.84,73.80,72.76
Cursos_Externos,2023,77.13,35.73,26.80,41.93,37.06,29.91
Cursos_Internos,2023,84.65,71.75,73.87,71.07,78.49,67.69
Formacion_Puesto,2023,76.93,59.73,55.20,63.00,54.33,60.56
Rotacion_Puestos,2023,42.02,26.98,24.94,28.93,23.55,28.96
Conferencias_Seminarios,2023,60.96,40.83,28.04,38.81,33.14,32.16