In [ ]:
import pandas as pd

eal_2023_dict = pd.read_excel("Tablas_EAL_2023.xlsx", sheet_name=["EAL-18a"], skiprows=5)

df_18a = eal_2023_dict["EAL-18a"]

df_18a.columns = [
    "Categoria", 
    "Total", 
    "Cursos_Externos", 
    "Cursos_Internos", 
    "Formacion_Puesto", 
    "Rotacion_Puestos", 
    "Conferencias_Seminarios"
]


df_18a = df_18a.dropna(subset=["Categoria"])

df_18a = df_18a[df_18a["Total"].notna()]

df_18a

,Categoria,Total,Cursos_Externos,Cursos_Internos,Formacion_Puesto,Rotacion_Puestos,Conferencias_Seminarios
1,TOTAL,72.932251,33.51468,72.118511,58.494234,26.923791,34.063854
4,De 5 a 9 trabajadores,64.67073,27.452634,66.497141,54.595202,26.269467,31.311321
5,De 10 a 49 trabajadores,79.013394,33.328382,74.868712,59.67687,25.119929,32.658179
6,De 50 a 249 trabajadores,94.064516,58.117774,85.302763,69.111307,36.576524,51.00921
7,De 250 a 499 trabajadores,98.31393,77.133524,84.646795,76.929359,42.01715,60.963659
8,Más de 499 trabajadores,99.188641,85.889571,85.071575,82.361963,50.869121,66.002045
11,Industria,78.356762,35.335511,72.393006,61.640809,33.150007,30.577838
12,Construcción,79.310809,25.605654,78.549823,63.259364,22.8947,21.925088
13,Comercio y reparación de vehículos,70.702769,34.41841,72.647356,58.602862,28.884518,40.046304
14,Transporte y almacenamiento,79.535758,29.931669,78.440513,53.049365,20.154544,17.306341
15,Hostelería,58.387782,23.458918,63.714466,58.234151,24.857041,17.404033
16,"Información, comunicaciones, actividades finan...",81.274725,47.985398,69.172526,56.429151,29.583559,54.286101
17,"Actividades profesionales, científicas y técnicas",82.792534,44.897408,73.321634,56.029518,24.586033,61.258099
18,Actividades administrativas y servicios auxili...,72.70554,36.890636,76.654753,56.933524,25.153681,34.381701
19,"Actividades artísticas, recreativas y de entre...",71.846197,37.50162,65.135415,51.768822,26.247246,46.650253
22,Andalucía,73.308284,26.79951,73.86554,55.19664,24.941871,28.039603
23,Aragón,78.902352,31.875081,73.132017,58.833398,29.190863,33.926958
24,Asturias (Principado de),74.890653,30.737616,71.62016,51.719663,18.689163,30.60783
25,Balears (Illes),67.030587,36.236371,65.203931,63.494414,31.578947,34.688383
26,Canarias,62.514076,35.807736,77.133106,56.958665,26.241942,28.981797
27,Cantabria,76.731657,31.795386,75.459712,58.609161,19.859579,26.847208
28,Castilla-La Mancha,69.834357,32.305122,73.619154,59.922049,22.672606,28.11804
29,Castilla y León,74.853918,31.775038,71.782134,56.994589,27.179988,27.650137
30,Cataluña,74.478543,35.726954,71.752939,59.729841,26.984945,40.831099
31,Comunitat Valenciana,72.760795,29.908077,67.690748,60.557128,28.964384,32.155465
32,Extremadura,68.839375,29.710145,74.613527,52.608696,23.502415,30.797101
33,Galicia,75.980682,30.263437,74.334346,52.906279,27.826824,36.930574
34,Madrid (Comunidad de),72.840425,41.930496,71.066149,63.001887,28.928609,38.814341
35,Murcia (Región de),73.763928,30.564078,68.657069,60.054284,27.967902,30.068445
36,Navarra (Comunidad Foral de),72.32387,34.981099,74.091306,55.39401,34.661239,40.8549
37,País Vasco,73.799418,37.063512,78.489853,54.334073,23.547778,33.14436
38,"Rioja, La",74.425059,32.818327,67.448055,60.628663,25.785828,30.900373

In [ ]:
# 1. Ponemos la columna 'Categoria' como el índice (los nombres de las filas)
df_transpuesta = df_18a.set_index("Categoria")

# 2. Transponemos (la .T hace la magia de girar todo)
df_transpuesta = df_transpuesta.T

# Ahora tus columnas son "TOTAL", "De 5 a 9 trabajadores", "Andalucía", etc.
# Y tus filas son "Total", "Cursos_Externos", "Cursos_Internos"...

In [ ]:
df_transpuesta

Categoria,TOTAL,De 5 a 9 trabajadores,De 10 a 49 trabajadores,De 50 a 249 trabajadores,De 250 a 499 trabajadores,Más de 499 trabajadores,Industria,Construcción,Comercio y reparación de vehículos,Transporte y almacenamiento,...,Castilla y León,Cataluña,Comunitat Valenciana,Extremadura,Galicia,Madrid (Comunidad de),Murcia (Región de),Navarra (Comunidad Foral de),País Vasco,"Rioja, La"
Total,72.932251,64.67073,79.013394,94.064516,98.31393,99.188641,78.356762,79.310809,70.702769,79.535758,...,74.853918,74.478543,72.760795,68.839375,75.980682,72.840425,73.763928,72.32387,73.799418,74.425059
Cursos_Externos,33.51468,27.452634,33.328382,58.117774,77.133524,85.889571,35.335511,25.605654,34.41841,29.931669,...,31.775038,35.726954,29.908077,29.710145,30.263437,41.930496,30.564078,34.981099,37.063512,32.818327
Cursos_Internos,72.118511,66.497141,74.868712,85.302763,84.646795,85.071575,72.393006,78.549823,72.647356,78.440513,...,71.782134,71.752939,67.690748,74.613527,74.334346,71.066149,68.657069,74.091306,78.489853,67.448055
Formacion_Puesto,58.494234,54.595202,59.67687,69.111307,76.929359,82.361963,61.640809,63.259364,58.602862,53.049365,...,56.994589,59.729841,60.557128,52.608696,52.906279,63.001887,60.054284,55.39401,54.334073,60.628663
Rotacion_Puestos,26.923791,26.269467,25.119929,36.576524,42.01715,50.869121,33.150007,22.8947,28.884518,20.154544,...,27.179988,26.984945,28.964384,23.502415,27.826824,28.928609,27.967902,34.661239,23.547778,25.785828
Conferencias_Seminarios,34.063854,31.311321,32.658179,51.00921,60.963659,66.002045,30.577838,21.925088,40.046304,17.306341,...,27.650137,40.831099,32.155465,30.797101,36.930574,38.814341,30.068445,40.8549,33.14436,30.900373

In [ ]:
# 1. Quitamos los espacios en blanco al principio y al final de todos los nombres de columnas
df_transpuesta.columns = df_transpuesta.columns.str.strip()

# 2. Ahora ya puedes usar los nombres "limpios" sin miedo al KeyError
columnas_interes = [
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana"
]

# 3. Filtramos
df_seleccion = df_transpuesta[columnas_interes]

print(df_seleccion)

Categoria               De 250 a 499 trabajadores   Cataluña  Andalucía  \
Total                                    98.31393  74.478543  73.308284
Cursos_Externos                         77.133524  35.726954   26.79951
Cursos_Internos                         84.646795  71.752939   73.86554
Formacion_Puesto                        76.929359  59.729841   55.19664
Rotacion_Puestos                         42.01715  26.984945  24.941871
Conferencias_Seminarios                 60.963659  40.831099  28.039603

Categoria               Madrid (Comunidad de) País Vasco Comunitat Valenciana
Total                               72.840425  73.799418            72.760795
Cursos_Externos                     41.930496  37.063512            29.908077
Cursos_Internos                     71.066149  78.489853            67.690748
Formacion_Puesto                    63.001887  54.334073            60.557128
Rotacion_Puestos                    28.928609  23.547778            28.964384
Conferencias_Seminarios             38.814341   33.14436            32.155465

In [ ]:
# Tienes que poner el "=" para que se guarde el cambio
df_seleccion = df_seleccion.round(2)

# Ahora, al imprimirla, verás que todo tiene 2 decimales
print(df_seleccion)

Categoria               De 250 a 499 trabajadores   Cataluña  Andalucía  \
Total                                    98.31393  74.478543  73.308284
Cursos_Externos                         77.133524  35.726954   26.79951
Cursos_Internos                         84.646795  71.752939   73.86554
Formacion_Puesto                        76.929359  59.729841   55.19664
Rotacion_Puestos                         42.01715  26.984945  24.941871
Conferencias_Seminarios                 60.963659  40.831099  28.039603

Categoria               Madrid (Comunidad de) País Vasco Comunitat Valenciana
Total                               72.840425  73.799418            72.760795
Cursos_Externos                     41.930496  37.063512            29.908077
Cursos_Internos                     71.066149  78.489853            67.690748
Formacion_Puesto                    63.001887  54.334073            60.557128
Rotacion_Puestos                    28.928609  23.547778            28.964384
Conferencias_Seminarios             38.814341   33.14436            32.155465

In [ ]:
# 1. Convertimos todo a números (por si acaso Pandas cree que es texto)
df_seleccion = df_seleccion.apply(pd.to_numeric, errors='coerce')

# 2. Ahora redondeamos y GUARDAMOS el resultado
df_seleccion = df_seleccion.round(2)

# 3. Comprobamos
print(df_seleccion)

Categoria                De 250 a 499 trabajadores  Cataluña  Andalucía  \
Total                                        98.31     74.48      73.31
Cursos_Externos                              77.13     35.73      26.80
Cursos_Internos                              84.65     71.75      73.87
Formacion_Puesto                             76.93     59.73      55.20
Rotacion_Puestos                             42.02     26.98      24.94
Conferencias_Seminarios                      60.96     40.83      28.04

Categoria                Madrid (Comunidad de)  País Vasco  \
Total                                    72.84       73.80
Cursos_Externos                          41.93       37.06
Cursos_Internos                          71.07       78.49
Formacion_Puesto                         63.00       54.33
Rotacion_Puestos                         28.93       23.55
Conferencias_Seminarios                  38.81       33.14

Categoria                Comunitat Valenciana
Total                                   72.76
Cursos_Externos                         29.91
Cursos_Internos                         67.69
Formacion_Puesto                        60.56
Rotacion_Puestos                        28.96
Conferencias_Seminarios                 32.16

In [ ]:
# Ahora 'df_formacion' contiene exactamente lo mismo que 'eal_2023_clean'
# 1. Creamos el nuevo nombre usando la tabla que SÍ existe
eal_2023_18a = df_seleccion

# 2. Comprobamos que funciona

In [ ]:
eal_2023_18a

Categoria,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana
Total,98.31,74.48,73.31,72.84,73.80,72.76
Cursos_Externos,77.13,35.73,26.80,41.93,37.06,29.91
Cursos_Internos,84.65,71.75,73.87,71.07,78.49,67.69
Formacion_Puesto,76.93,59.73,55.20,63.00,54.33,60.56
Rotacion_Puestos,42.02,26.98,24.94,28.93,23.55,28.96
Conferencias_Seminarios,60.96,40.83,28.04,38.81,33.14,32.16

In [ ]:
eal_2023_18a.insert(0, 'Año', 2023)

In [ ]:
eal_2023_18a

Categoria,Año,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana
Total,2023,98.31,74.48,73.31,72.84,73.80,72.76
Cursos_Externos,2023,77.13,35.73,26.80,41.93,37.06,29.91
Cursos_Internos,2023,84.65,71.75,73.87,71.07,78.49,67.69
Formacion_Puesto,2023,76.93,59.73,55.20,63.00,54.33,60.56
Rotacion_Puestos,2023,42.02,26.98,24.94,28.93,23.55,28.96
Conferencias_Seminarios,2023,60.96,40.83,28.04,38.81,33.14,32.16

In [ ]:
import pandas as pd

# 1. Cargar la hoja (asegúrate de que el nombre coincida)
df_18b = pd.read_excel("Tablas_EAL_2023.xlsx", sheet_name="EAL-18b", skiprows=5)

# 2. Renombrar las columnas basándonos en tu texto
# Nota: La primera columna es la categoría, la segunda el % de empresas con ERTE, y el resto los rangos de formación.
df_18b.columns = [
    "Categoria", 
    "Empresas_con_ERTE", 
    "Total_100", 
    "El_0_porc", 
    "De_0_a_25", 
    "De_25_a_50", 
    "De_50_a_75", 
    "De_75_a_100", 
    "El_100_porc"
]

# 3. Limpiar: quitar filas vacías y espacios en los nombres de las categorías
df_18b = df_18b.dropna(subset=["Empresas_con_ERTE"])
df_18b["Categoria"] = df_18b["Categoria"].str.strip()

# 4. Transponer para que las CCAA y Tamaños sean columnas
df_18b_trans = df_18b.set_index("Categoria").T
columnas_totales = [
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana",
    "Transporte y almacenamiento"  # <-- La nueva que querías añadir
]

# 2. Filtramos la tabla transpuesta (df_18b_trans) con esta nueva lista
eal_2023_18b = df_18b_trans[columnas_totales].copy()

# 3. Limpiamos: Convertimos a números y redondeamos
eal_2023_18b = eal_2023_18b.apply(pd.to_numeric, errors='coerce').round(2)

# 4. Añadimos el año al principio
if 'Año' not in eal_2023_18b.columns:
    eal_2023_18b.insert(0, 'Año', 2023)

# 5. Ver el resultado final unificado
print("--- TABLA 18b UNIFICADA (Incluye Transporte) ---")
print(eal_2023_18b)

--- TABLA 18b UNIFICADA (Incluye Transporte) ---
Categoria           Año  De 250 a 499 trabajadores  Cataluña  Andalucía  \
Empresas_con_ERTE  2023                       9.15      3.10       3.96
Total_100          2023                     100.00    100.00     100.00
El_0_porc          2023                      62.42     88.68      87.68
De_0_a_25          2023                      25.32      7.53       7.01
De_25_a_50         2023                       3.28      0.98       2.17
De_50_a_75         2023                       3.68      1.12       0.74
De_75_a_100        2023                       2.60      0.44       0.22
El_100_porc        2023                       2.70      1.25       2.17

Categoria          Madrid (Comunidad de)  País Vasco  Comunitat Valenciana  \
Empresas_con_ERTE                   4.45        3.61                  5.47
Total_100                         100.00      100.00                100.00
El_0_porc                          87.18       85.24                 90.28
De_0_a_25                           6.65        8.39                  6.87
De_25_a_50                          2.46        2.63                  1.03
De_50_a_75                          0.85        1.12                  0.20
De_75_a_100                         0.17        0.65                  0.68
El_100_porc                         2.69        1.98                  0.94

Categoria          Transporte y almacenamiento
Empresas_con_ERTE                         2.00
Total_100                               100.00
El_0_porc                                87.65
De_0_a_25                                 8.49
De_25_a_50                                0.90
De_50_a_75                                0.87
De_75_a_100                               0.86
El_100_porc                               1.22

In [ ]:
eal_2023_18b

Categoria,Año,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana,Transporte y almacenamiento
Empresas_con_ERTE,2023,9.15,3.10,3.96,4.45,3.61,5.47,2.00
Total_100,2023,100.00,100.00,100.00,100.00,100.00,100.00,100.00
El_0_porc,2023,62.42,88.68,87.68,87.18,85.24,90.28,87.65
De_0_a_25,2023,25.32,7.53,7.01,6.65,8.39,6.87,8.49
De_25_a_50,2023,3.28,0.98,2.17,2.46,2.63,1.03,0.90
De_50_a_75,2023,3.68,1.12,0.74,0.85,1.12,0.20,0.87
De_75_a_100,2023,2.60,0.44,0.22,0.17,0.65,0.68,0.86
El_100_porc,2023,2.70,1.25,2.17,2.69,1.98,0.94,1.22

In [ ]:
# 1. Definimos la lista de columnas incluyendo el "TOTAL" (que está en tu df_18b_trans)
columnas_finales = [
    "TOTAL",                     # <-- La ponemos primero
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana",
    "Transporte y almacenamiento"
]

# 2. Filtramos la tabla transpuesta
eal_2023_18b = df_18b_trans[columnas_finales].copy()

# 3. Limpieza de datos (numéricos y redondeo)
eal_2023_18b = eal_2023_18b.apply(pd.to_numeric, errors='coerce').round(2)

# 4. Insertamos el Año en la posición 0
if 'Año' not in eal_2023_18b.columns:
    eal_2023_18b.insert(0, 'Año', 2023)

# 5. Ver el resultado con TOTAL al principio
print("--- TABLA 18b COMPLETA (Con TOTAL al inicio) ---")
print(eal_2023_18b)

--- TABLA 18b COMPLETA (Con TOTAL al inicio) ---
Categoria           Año   TOTAL  De 250 a 499 trabajadores  Cataluña  \
Empresas_con_ERTE  2023    3.74                       9.15      3.10
Total_100          2023  100.00                     100.00    100.00
El_0_porc          2023   88.75                      62.42     88.68
De_0_a_25          2023    7.06                      25.32      7.53
De_25_a_50         2023    1.45                       3.28      0.98
De_50_a_75         2023    0.70                       3.68      1.12
De_75_a_100        2023    0.48                       2.60      0.44
El_100_porc        2023    1.56                       2.70      1.25

Categoria          Andalucía  Madrid (Comunidad de)  País Vasco  \
Empresas_con_ERTE       3.96                   4.45        3.61
Total_100             100.00                 100.00      100.00
El_0_porc              87.68                  87.18       85.24
De_0_a_25               7.01                   6.65        8.39
De_25_a_50              2.17                   2.46        2.63
De_50_a_75              0.74                   0.85        1.12
De_75_a_100             0.22                   0.17        0.65
El_100_porc             2.17                   2.69        1.98

Categoria          Comunitat Valenciana  Transporte y almacenamiento
Empresas_con_ERTE                  5.47                         2.00
Total_100                        100.00                       100.00
El_0_porc                         90.28                        87.65
De_0_a_25                          6.87                         8.49
De_25_a_50                         1.03                         0.90
De_50_a_75                         0.20                         0.87
De_75_a_100                        0.68                         0.86
El_100_porc                        0.94                         1.22

In [ ]:
eal_2023_18b

Categoria,Año,TOTAL,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana,Transporte y almacenamiento
Empresas_con_ERTE,2023,3.74,9.15,3.10,3.96,4.45,3.61,5.47,2.00
Total_100,2023,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
El_0_porc,2023,88.75,62.42,88.68,87.68,87.18,85.24,90.28,87.65
De_0_a_25,2023,7.06,25.32,7.53,7.01,6.65,8.39,6.87,8.49
De_25_a_50,2023,1.45,3.28,0.98,2.17,2.46,2.63,1.03,0.90
De_50_a_75,2023,0.70,3.68,1.12,0.74,0.85,1.12,0.20,0.87
De_75_a_100,2023,0.48,2.60,0.44,0.22,0.17,0.65,0.68,0.86
El_100_porc,2023,1.56,2.70,1.25,2.17,2.69,1.98,0.94,1.22

In [ ]:
import pandas as pd
import re

# 1. Cargar la hoja
df_18c = pd.read_excel("Tablas_EAL_2023.xlsx", sheet_name="EAL-18c", skiprows=5)
df_18c = df_18c.iloc[:, :1] # Solo nos interesa la primera columna donde está todo pegado
df_18c.columns = ["Bruto"]

# 2. Función mágica para separar el nombre del número (ej: "Andalucía75.5" -> "Andalucía", 75.5)
def separar_datos(texto):
    match = re.search(r'([a-zA-Z\s\(\),áéíóúÁÉÍÓÚñÑ]+)([\d\.]+)$', str(texto))
    if match:
        return match.group(1).strip(), float(match.group(2))
    return texto, None

# 3. Aplicar la separación
df_18c[['Categoria', 'Porcentaje_Seguridad_Salud']] = df_18c['Bruto'].apply(
    lambda x: pd.Series(separar_datos(x))
)

# 4. Limpiar y Transponer
df_18c_clean = df_18c.dropna(subset=['Porcentaje_Seguridad_Salud'])
df_18c_trans = df_18c_clean.set_index("Categoria").T

# 5. Seleccionar con los nombres exactos de tu tabla
columnas_finales = [
    "TOTAL",
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana",
    "Transporte y almacenamiento"
]

# Filtramos solo las que existen para evitar errores
columnas_reales = [c for c in columnas_finales if c in df_18c_trans.columns]
eal_2023_18c = df_18c_trans[columnas_reales].copy()

# 6. Añadir año y mostrar
eal_2023_18c.insert(0, 'Año', 2023)
print("--- TABLA 18c (Limpieza por Regex) ---")
print(eal_2023_18c)

--- TABLA 18c (Limpieza por Regex) ---
Categoria                    Año
Bruto                       2023
Porcentaje_Seguridad_Salud  2023

In [ ]:
import pandas as pd

# 1. Creamos los datos directamente de tu texto para evitar errores de lectura del Excel
datos_18c = {
    "TOTAL": [73.8],
    "De 250 a 499 trabajadores": [95.6],
    "Cataluña": [76.5],
    "Andalucía": [75.5],
    "Madrid (Comunidad de)": [72.7],
    "País Vasco": [64.6],
    "Comunitat Valenciana": [77.7],
    "Transporte y almacenamiento": [78.1]
}

# 2. Convertir en DataFrame
eal_2023_18c = pd.DataFrame(datos_18c)

# 3. Añadir el Año al principio
eal_2023_18c.insert(0, 'Año', 2023)

# 4. Cambiar el nombre del índice para que quede igual que las otras tablas
eal_2023_18c.index = ["Porcentaje_Seguridad_Salud"]

print("--- TABLA 18c DEFINITIVA ---")
print(eal_2023_18c)

--- TABLA 18c DEFINITIVA ---
                             Año  TOTAL  De 250 a 499 trabajadores  Cataluña  \
Porcentaje_Seguridad_Salud  2023   73.8                       95.6      76.5

                            Andalucía  Madrid (Comunidad de)  País Vasco  \
Porcentaje_Seguridad_Salud       75.5                   72.7        64.6

                            Comunitat Valenciana  Transporte y almacenamiento
Porcentaje_Seguridad_Salud                  77.7                         78.1

In [ ]:
eal_2023_18b.to_csv("eal_2023_18b.csv", index=True)

In [ ]:

df_18a_2024 = pd.read_excel("Tablas_EAL_2024.xlsx", sheet_name="EAL-18a", skiprows=7)

# 2. Nos quedamos solo con las columnas necesarias (Categoria + los 6 medios formativos)
df_18a_2024 = df_18a_2024.iloc[:, :7]

# 3. Asignar nombres cortos a las columnas para que sean fáciles de graficar
df_18a_2024.columns = [
    "Categoria",
    "TOTAL_Empresas_Formacion",
    "Cursos_Propios",
    "Cursos_Externos",
    "Formacion_Puesto",
    "Rotacion_Intercambio",
    "Conferencias_Talleres"
]

# 4. Limpieza: quitar filas vacías y espacios
df_18a_2024 = df_18a_2024.dropna(subset=["TOTAL_Empresas_Formacion"])
df_18a_2024["Categoria"] = df_18a_2024["Categoria"].str.strip()

# 5. Transponer para tener las CCAA y sectores como columnas
df_18a_trans = df_18a_2024.set_index("Categoria").T

# 6. Seleccionamos tus columnas clave con el TOTAL al principio
columnas_finales = [
    "TOTAL",
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana",
    "Transporte y almacenamiento"
]

# Filtramos solo las que existan (por si acaso hay algún cambio de nombre en 2024)
columnas_reales = [c for c in columnas_finales if c in df_18a_trans.columns]

eal_2024_18a = df_18a_trans[columnas_reales].copy()
eal_2024_18a = eal_2024_18a.apply(pd.to_numeric, errors='coerce').round(2)
eal_2024_18a.insert(0, 'Año', 2024)

print("--- TABLA 18a: MEDIOS FORMATIVOS (AÑO 2024) ---")
print(eal_2024_18a)

--- TABLA 18a: MEDIOS FORMATIVOS (AÑO 2024) ---
Categoria                  Año  De 250 a 499 trabajadores  Cataluña  \
TOTAL_Empresas_Formacion  2024                      98.39     76.30
Cursos_Propios            2024                      76.16     37.30
Cursos_Externos           2024                      85.38     75.37
Formacion_Puesto          2024                      76.87     58.32
Rotacion_Intercambio      2024                      46.70     30.78
Conferencias_Talleres     2024                      57.80     41.25

Categoria                 Andalucía  Madrid (Comunidad de)  País Vasco  \
TOTAL_Empresas_Formacion      73.32                  72.99       71.17
Cursos_Propios                23.90                  41.84       44.73
Cursos_Externos               76.82                  71.68       69.77
Formacion_Puesto              47.93                  58.77       58.92
Rotacion_Intercambio          26.16                  26.18       31.51
Conferencias_Talleres         27.76                  38.47       36.79

Categoria                 Comunitat Valenciana  Transporte y almacenamiento
TOTAL_Empresas_Formacion                 74.32                        77.41
Cursos_Propios                           38.07                        30.57
Cursos_Externos                          71.12                        79.67
Formacion_Puesto                         55.54                        52.05
Rotacion_Intercambio                     26.03                        24.26
Conferencias_Talleres                    32.28                        20.42

In [ ]:
eal_2024_18a

Categoria,Año,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana,Transporte y almacenamiento
TOTAL_Empresas_Formacion,2024,98.39,76.30,73.32,72.99,71.17,74.32,77.41
Cursos_Propios,2024,76.16,37.30,23.90,41.84,44.73,38.07,30.57
Cursos_Externos,2024,85.38,75.37,76.82,71.68,69.77,71.12,79.67
Formacion_Puesto,2024,76.87,58.32,47.93,58.77,58.92,55.54,52.05
Rotacion_Intercambio,2024,46.70,30.78,26.16,26.18,31.51,26.03,24.26
Conferencias_Talleres,2024,57.80,41.25,27.76,38.47,36.79,32.28,20.42

In [ ]:


# 1. Cargar la hoja (skiprows=7 suele ser el estándar para esta tabla)
df_18b_2024 = pd.read_excel("Tablas_EAL_2024.xlsx", sheet_name="EAL-18b", skiprows=7)

# 2. Renombrar columnas (usamos los mismos nombres que en 2023 para que sean compatibles)
df_18b_2024.columns = [
    "Categoria", 
    "Empresas_con_ERTE", 
    "Total_100", 
    "El_0_porc", 
    "De_0_a_25", 
    "De_25_a_50", 
    "De_50_a_75", 
    "De_75_a_100", 
    "El_100_porc"
]

# 3. Limpieza de filas y espacios
df_18b_2024 = df_18b_2024.dropna(subset=["Empresas_con_ERTE"])
df_18b_2024["Categoria"] = df_18b_2024["Categoria"].str.strip()

# 4. Transponer
df_18b_trans = df_18b_2024.set_index("Categoria").T

# 5. Seleccionar columnas (TOTAL al principio)
columnas_finales = [
    "TOTAL",
    "De 250 a 499 trabajadores", 
    "Cataluña", 
    "Andalucía", 
    "Madrid (Comunidad de)", 
    "País Vasco", 
    "Comunitat Valenciana",
    "Transporte y almacenamiento"
]

eal_2024_18b = df_18b_trans[columnas_finales].copy()
eal_2024_18b = eal_2024_18b.apply(pd.to_numeric, errors='coerce').round(2)
eal_2024_18b.insert(0, 'Año', 2024)

# 6. Reordenar filas: El 100% arriba del todo
orden_filas = [
    "El_100_porc", 
    "Empresas_con_ERTE", 
    "Total_100", 
    "El_0_porc", 
    "De_0_a_25", 
    "De_25_a_50", 
    "De_50_a_75", 
    "De_75_a_100"
]
eal_2024_18b = eal_2024_18b.reindex(orden_filas)

print("--- TABLA 18b FINAL (AÑO 2024) ---")
print(eal_2024_18b)

--- TABLA 18b FINAL (AÑO 2024) ---
Categoria           Año   TOTAL  De 250 a 499 trabajadores  Cataluña  \
El_100_porc        2024    1.87                       2.90      2.38
Empresas_con_ERTE  2024    1.40                       9.92      1.73
Total_100          2024  100.00                     100.00    100.00
El_0_porc          2024   81.30                      69.22     69.01
De_0_a_25          2024   13.06                      19.40     18.95
De_25_a_50         2024    1.33                       4.65      0.33
De_50_a_75         2024    2.02                       0.00      8.93
De_75_a_100        2024    0.42                       3.83      0.40

Categoria          Andalucía  Madrid (Comunidad de)  País Vasco  \
El_100_porc             1.30                   1.78       14.52
Empresas_con_ERTE       1.95                   0.42        1.24
Total_100             100.00                 100.00      100.00
El_0_porc              86.19                  81.25       66.39
De_0_a_25               8.66                  12.70       19.08
De_25_a_50              2.92                   3.06        0.00
De_50_a_75              0.93                   0.16        0.00
De_75_a_100             0.00                   1.05        0.00

Categoria          Comunitat Valenciana  Transporte y almacenamiento
El_100_porc                        0.00                         0.00
Empresas_con_ERTE                  3.05                         0.85
Total_100                        100.00                       100.00
El_0_porc                         79.58                        82.85
De_0_a_25                         19.84                        16.63
De_25_a_50                         0.11                         0.33
De_50_a_75                         0.46                         0.00
De_75_a_100                        0.00                         0.19

In [ ]:
eal_2024_18b

Categoria,Año,TOTAL,De 250 a 499 trabajadores,Cataluña,Andalucía,Madrid (Comunidad de),País Vasco,Comunitat Valenciana,Transporte y almacenamiento
El_100_porc,2024,1.87,2.90,2.38,1.30,1.78,14.52,0.00,0.00
Empresas_con_ERTE,2024,1.40,9.92,1.73,1.95,0.42,1.24,3.05,0.85
Total_100,2024,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
El_0_porc,2024,81.30,69.22,69.01,86.19,81.25,66.39,79.58,82.85
De_0_a_25,2024,13.06,19.40,18.95,8.66,12.70,19.08,19.84,16.63
De_25_a_50,2024,1.33,4.65,0.33,2.92,3.06,0.00,0.11,0.33
De_50_a_75,2024,2.02,0.00,8.93,0.93,0.16,0.00,0.46,0.00
De_75_a_100,2024,0.42,3.83,0.40,0.00,1.05,0.00,0.00,0.19

In [ ]:
import pandas as pd

# 1. Creamos el diccionario con los datos exactos que pasaste
datos_18c_2024 = {
    "TOTAL": [75.8],
    "De 250 a 499 trabajadores": [95.6],
    "Cataluña": [79.9],
    "Andalucía": [76.0],
    "Madrid (Comunidad de)": [74.7],
    "País Vasco": [62.8],
    "Comunitat Valenciana": [81.9],
    "Transporte y almacenamiento": [81.2]
}

# 2. Convertir en DataFrame
eal_2024_18c = pd.DataFrame(datos_18c_2024)

# 3. Añadir el Año y el nombre de la métrica
eal_2024_18c.insert(0, 'Año', 2024)
eal_2024_18c.index = ["Porcentaje_Seguridad_Salud"]

print("--- TABLA 18c: SEGURIDAD Y SALUD (AÑO 2024) ---")
print(eal_2024_18c)

--- TABLA 18c: SEGURIDAD Y SALUD (AÑO 2024) ---
                             Año  TOTAL  De 250 a 499 trabajadores  Cataluña  \
Porcentaje_Seguridad_Salud  2024   75.8                       95.6      79.9

                            Andalucía  Madrid (Comunidad de)  País Vasco  \
Porcentaje_Seguridad_Salud       76.0                   74.7        62.8

                            Comunitat Valenciana  Transporte y almacenamiento
Porcentaje_Seguridad_Salud                  81.9                         81.2

In [ ]:
eal_2024_18b.to_csv("eal_2024_18b.csv", index=True)